### ISSUE TITLE
top-level exports is not immutable

### ISSUE THREAD

**Issue by hardfist** [babel/babel#9049] opened 2018-11-20 16:25 UTC
## Bug Report

**Current Behavior**
according to https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html, It says that top-level exports is immutable. so I test it on babel and node esm module loader, but it generates different results.

**Input Code**
the demo is here https://github.com/hardfist/babel-module 
`npm run esm` and `npm run cjs` generates different result.
```js
// main.mjs
import * as lib from './lib';

lib.name = 'lib';
console.log('lib:',lib);

```
```js
// lib.mjs
export const foo = 'bar';
```
esm results
```
(node:70216) ExperimentalWarning: The ESM module loader is experimental.
TypeError: Cannot add property name, object is not extensible
```
babel results
```
lib: { foo: 'bar', name: 'lib' }
```
**Expected behavior/code**
same behavior for babel and node esm module loader
**Babel Configuration (.babelrc, package.json, cli command)**

```js
module.exports = {
  presets: [
    [
      '@babel/env',
      {
        modules: 'commonjs',
        targets: {
          node: 'current',
        },
      },
    ],
  ],
};
```

**Environment**
- Babel version(s): 7.1.6
- Node/npm version: 10.13.0
- OS: 10.12.4
- How you are using Babel: cli

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by nicolo-ribaudo** [comment] 2019-02-19 09:50
I'm closing this as a duplicate of https://github.com/babel/babel/issues/2276

**Closed by nicolo-ribaudo** 2019-02-19 09:50 UTC
