### ISSUE TITLE
Unary async arrow misprinted as concise async arrow when the binding identifier has leading comments

### ISSUE THREAD

**Issue by MrEfrem** [babel/babel#12500] opened 2020-12-14 08:05 UTC
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

- [REPL](https://babel.dev/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=IYd2EsBcAIGsDsCmAPAdJATseBnYBjScAe3gApgcBPefaMgegConoABSKgB0WgG9sVAL7QmDaJmQBKaAF4AfPwBQQqQG4lQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.12.10&externalPlugins=)

**Input Code**

```js
await knex.transaction(async (/** @type {any} */ trx) => {
});
```

is compiled to:

```js
"use strict";

await knex.transaction(async
/** @type {any} */
trx => {});
```

and Node.JS throws so error:
```
SyntaxError: missing ) after argument list at Module._compile (internal/modules/cjs/loader.js:723:23) at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10) at Module.load (internal/modules/cjs/loader.js:653:32) at tryModuleLoad (internal/modules/cjs/loader.js:593:12) at Function.Module._load (internal/modules/cjs/loader.js:585:3) at Module.require (internal/modules/cjs/loader.js:692:17) at require (internal/modules/cjs/helpers.js:25:18) at Object.<anonymous> (/workspace/src/index.js:30:38) at Module._compile (internal/modules/cjs/loader.js:778:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```

**Expected behavior**

My source code should be compiled to this one without breaking `async (/** comments */ param) => ...`:
```js
"use strict";

await knex.transaction(async (/** @type {any} */ trx) => {});
```

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
{
  "presets": [
    [
      "@babel/env",
      {
        "targets": {
          "node": 10
        },
        "useBuiltIns": "usage",
        "corejs": 3
      }
    ]
  ]
}
```

**Environment**

```

```
- Babel version(s): v7.12.10
- Node/npm version: Node 10/yarn 1.22.5
- OS: macOS 11.0.1
- Monorepo: no
- How you are using Babel: `@babel/cli`
- Typescript: 4.1.3

**Possible Solution**

**Additional context**

I use Typescript JSDoc comments.

**Comment by nicolo-ribaudo** [comment] 2020-12-14 08:23
The problem is that Babel doesn't support compiling top-level await to CommonJS or to AMD. You can either compile to SystemJS modules, or use a bundler that supports it. (Bundlers have access to the whole module graph, so they can more easily transform top-level await).

**Comment by MrEfrem** [comment] 2020-12-14 08:30
It isn't the top level await. Above that part of source code I have:
```js
/**
 * @param {{
    req: import('express').Request,
    res: import('express').Response,
    knex: any,
  }} options
 */
const someRoute = async ({ req, res, knex }) => {
  ...
  await knex.transaction(async (/** @type {any} */ trx) => {
    ...
  });
  ...
}
export default someRoute;
```

And it's the server side source code. I won't use any bundlers for it. I need to keep the original file tree. 

My workaround is:
```js
await knex.transaction(
      /** @type {(trx: any) => Promise<void>} */ async (trx) => {
}
```
then compiler doesn't break `async (param) =>`. But I thought that is bug in the compiler, no?

**Comment by MrEfrem** [comment] 2020-12-14 08:32
Changed [REPL](https://babel.dev/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBBIFsCmAlEBXKSYF4YEMIBPMYGACgG8YAnJARwBpakJmBrMJADxgF8AlLgB8MajABQMAgHd8AS1iceAOig18kfMCjzw5QiTLkA9ACozMAAJQiAB2yVNRPjDMmY67kJyjKEgEhQSBAAGyQVUJAAc3IvAQBuaWkpfkSUvgkgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.12.10&externalPlugins=). And check REPL please. There isn't compiling to CommonJS.

**Comment by nicolo-ribaudo** [comment] 2020-12-14 10:31
Thanks, this is indeed a bug with `@babel/generator`:
```js
async (/** @type {any} */ trx) => {
}

// ->

async
/** @type {any} */
trx => {};
```

**Comment by MrEfrem** [comment] 2020-12-14 10:35
No problems.

**Comment by nwalters512** [comment] 2021-04-11 22:06
Just ran into this myself in the context of introducing Jest to a project - was finally able to trace this back to Babel. If anyone can point me in the right direction, I'd like to try to contribute a fix for this.

**Comment by nicolo-ribaudo** [comment] 2021-04-11 22:17
Thanks!

The problem is likely in https://github.com/babel/babel/blob/672a58660f0b15691c44582f1f3fdcdac0fa0d2f/packages/babel-generator/src/generators/methods.ts#L115-L141, where we decide how to print the arrow function parameters.

If it helps, you can reproduce it with this code:
```js
const input = `
fn(async (/* comment */ x) => {})
`;

const ast = parser.parse(input);

console.log(generator.default(ast));
```



If it is the first time that you contribute to Babel, follow these steps: (you need to have `make` and `yarn` available on your machine)
1. Fork the repo
1. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
1. Run `yarn && make bootstrap`
1. Wait :hourglass_flowing_sand: 
1. Run `make watch` (or `make build` whenever you change a file)
1. Add a test in `packages/babel-generator/test/fixtures/comments` (only `input.js`; `output.js` will be automatically generated)
1. Update the code!
1. `yarn jest babel-generator` to run the tests
    - If some test outputs don't match but the new results are correct, you can delete the bad `output.js` files and run the tests again
    - If you prefer, you can run `OVERWRITE=true yarn jest babel-generator` and they will be automatically updated.
1. If it is working, run `make test` to run all the tests
1. Run `git push` and open a PR!

**Comment by nwalters512** [comment] 2021-04-11 23:36
Thanks for the pointers! Excited to make my first contribution to Babel - I opened up a PR at #13136.

Re: `yarn && make bootstrap`, it looks like `make bootstrap` already runs `yarn install` - it could save a small amount of time for future recipients of these instructions to just have folks run `make bootstrap` 🙂

**Comment by nicolo-ribaudo** [comment] 2021-04-12 00:46
Oh thanks; I never updated those instructions since I wrote them the first time 😅

**Closed** 2021-04-12 14:10 UTC
Labels: i: bug, pkg: generator
