### ISSUE TITLE
Bug with destructuring args in a try/catch in an async function

### ISSUE THREAD

**Issue by mattkrick** [babel/babel#5462] opened 2017-03-13 17:46 UTC
### Input Code
```js
 const tryCatchWrapper = (target) => async (...targetArgs) => {
    try {
      return target(...targetArgs);
    } catch (e) {
      throw errorObj({_error: e.message});
   }
 };
```

### Babel Configuration (.babelrc, package.json, cli command)
babeljs.io standard config

### Expected Behavior

```js
"use strict";

function _asyncToGenerator(fn) { return function () { var gen = fn.apply(this, arguments); return new Promise(function (resolve, reject) { function step(key, arg) { try { var info = gen[key](arg); var value = info.value; } catch (error) { reject(error); return; } if (info.done) { resolve(value); } else { return Promise.resolve(value).then(function (value) { step("next", value); }, function (err) { step("throw", err); }); } } return step("next"); }); }; }

var tryCatchWrapper = function tryCatchWrapper(target) {
  return function () {
    var _ref = _asyncToGenerator(regeneratorRuntime.mark(function _callee() {
      for (var _len = arguments.length, targetArgs = Array(_len), _key = 0; _key < _len; _key++) {
        targetArgs[_key] = arguments[_key];
      }

      return regeneratorRuntime.wrap(function _callee$(_context) {
        while (1) {
          switch (_context.prev = _context.next) {
            case 0:
              _context.prev = 0;

              targetArgs;
              return _context.abrupt("return", target.apply(undefined, targetArgs));

            case 5:
              _context.prev = 5;
              _context.t0 = _context["catch"](0);
              throw errorObj({ _error: _context.t0.message });

            case 8:
            case "end":
              return _context.stop();
          }
        }
      }, _callee, undefined, [[0, 5]]);
    }));

    return function () {
      return _ref.apply(this, arguments);
    };
  }();
};
```

### Current Behavior
```js
"use strict";

var _arguments = arguments;

function _asyncToGenerator(fn) { return function () { var gen = fn.apply(this, arguments); return new Promise(function (resolve, reject) { function step(key, arg) { try { var info = gen[key](arg); var value = info.value; } catch (error) { reject(error); return; } if (info.done) { resolve(value); } else { return Promise.resolve(value).then(function (value) { step("next", value); }, function (err) { step("throw", err); }); } } return step("next"); }); }; }

var tryCatchWrapper = function tryCatchWrapper(target) {
  return function () {
    var _ref = _asyncToGenerator(regeneratorRuntime.mark(function _callee() {
      var _args = _arguments;
      return regeneratorRuntime.wrap(function _callee$(_context) {
        while (1) {
          switch (_context.prev = _context.next) {
            case 0:
              _context.prev = 0;
              return _context.abrupt("return", target.apply(undefined, _args));

            case 4:
              _context.prev = 4;
              _context.t0 = _context["catch"](0);
              throw errorObj({ _error: _context.t0.message });

            case 7:
            case "end":
              return _context.stop();
          }
        }
      }, _callee, undefined, [[0, 4]]);
    }));

    return function () {
      return _ref.apply(this, arguments);
    };
  }();
};
```

### Possible Solution
Reference the destructured args:
```js
 const tryCatchWrapper = (target) => async (...targetArgs) => {
    try {
      targetArgs; // do this!
      return target(...targetArgs);
    } catch (e) {
      throw errorObj({_error: e.message});
   }
 };
```

### Context
Made a try/catch wrapper for calling stripe. it bugs out! But then when i put a `console.log` in there, it works fine, which makes it extra confusing.
A call might look like this: 
```js
stripe.invoices.retrieveUpcoming = tryCatchWrapper(stripe.invoices.retrieveUpcoming.bind(stripe.invoices));
```

### Your Environment
babeljs.io

**Comment by montogeek** [comment] 2017-03-14 21:07
What is
> babeljs.io standard config

?
```js
{
  "presets": ["env"]
}
```
?

**Comment by mattkrick** [comment] 2017-03-14 21:57
This is a transpilation done on the babel website

**Comment by existentialism** [comment] 2017-03-14 22:06
Dupe of https://github.com/babel/babel/issues/4270 https://github.com/babel/babel/issues/4219 https://github.com/babel/babel/issues/3077

**Comment by aaronang** [comment] 2017-03-15 01:31
Closing this issue because it is a duplicate. Thank you for taking the time to report though 😄

**Closed by aaronang** 2017-03-15 01:31 UTC
