### ISSUE TITLE
Option to use runtime only for helpers, not polyfills

### ISSUE THREAD

**Issue by callumlocke** [babel/babel#2524] opened 2015-10-12 17:29 UTC
I know there is an externalHelpers option, but I don't want to add things to my global environment. I want my code to simply import helpers as needed, just like with runtime, but without runtime's other feature of importing things like Map and Set from core-js.

As far as I can tell this isn't possible?

**Comment by sebmck** [comment] 2015-10-12 17:30
Duplicate of #2417, #2059, #2001 and #1233.

**Closed by sebmck** 2015-10-12 17:30 UTC

**Comment by callumlocke** [comment] 2015-10-12 17:59
I don't think it's a duplicate. The external-helpers only work if you are able to modify the global environment.

I need runtime's behaviour of automatically adding `require()` calls as needed for stuff like `_createClass` and `_classCallCheck`. Is this likely to be possible in future?

**Comment by sebmck** [comment] 2015-10-12 18:30
That's exactly what those issues are asking for. The runtime just for helpers and not core-js. You can see those issues for more info.

**Comment by callumlocke** [comment] 2015-10-18 21:56
Sorry if I'm being dumb, but I've just read through all those issues again, and they are not the same. Those issues were all solved with externalHelpers. Or am I missing something?
