### ISSUE TITLE
@babel/helpers JSX code is not compatible with ES3

### ISSUE THREAD

**Issue by sormy** [babel/babel#10145] opened 2019-06-29 06:46 UTC
## Bug Report

**Current Behavior**

https://github.com/babel/babel/blob/1d3f9815df747902ae535706f032081bc4825b87/packages/babel-helpers/src/helpers.js#L35

The code is:

```js
typeof Symbol === "function" && Symbol.for && Symbol.for("react.element")
```

**Input Code**

`Symbol.for` is incorrect syntax in ES3 because `for` is a keyword. This is causing parsing error in IE7, for example.

**Expected behavior/code**

It should be written as `Symbol["for"]` to be compatible with all browsers.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
    presets: [
      // transform-function-name is breaking React 0.14.x: '_renderedComponent' is null or not an object
      // generators are not supported on IE7
      ["@babel/preset-env", {
        targets: ["IE 7"],
        loose: true, /* es3 */
        exclude: [
          "transform-function-name",
          "transform-regenerator",
          "transform-async-to-generator"
        ]
      }],
      ["@babel/preset-react", { development: false }],
      "@babel/preset-typescript"
    ],
}
```

**Environment**

- Babel version(s): @babel/helpers@7.4.3
- Node/npm version: Node 8.x
- OS: macOS 10.12.6
- Monorepo: no
- How you are using Babel: rollup plugin

**Possible Solution**

Changing just one line to the line below fixes the problem without negative impact on modern platforms:

```js
typeof Symbol === "function" && Symbol["for"] && Symbol["for"]("react.element")
```

Previously opened CR: https://github.com/babel/babel/pull/9799

**Comment by sormy** [comment] 2019-06-29 06:51
Seems like a regression because it was already fixed here: https://github.com/babel/babel/pull/9799

**Comment by nicolo-ribaudo** [comment] 2019-06-30 17:46
Can you post the full input and the full output? I'm getting this output, and `for` is correctly wrapped in quotes:
```js
"use strict";

var REACT_ELEMENT_TYPE;

function _jsx(type, props, key, children) { if (!REACT_ELEMENT_TYPE) { REACT_ELEMENT_TYPE = typeof Symbol === "function" && Symbol["for"] && Symbol["for"]("react.element") || 0xeac7; } var defaultProps = type && type.defaultProps; var childrenLength = arguments.length - 3; if (!props && childrenLength !== 0) { props = { children: void 0 }; } if (props && defaultProps) { for (var propName in defaultProps) { if (props[propName] === void 0) { props[propName] = defaultProps[propName]; } } } else if (!props) { props = defaultProps || {}; } if (childrenLength === 1) { props.children = children; } else if (childrenLength > 1) { var childArray = new Array(childrenLength); for (var i = 0; i < childrenLength; i++) { childArray[i] = arguments[i + 3]; } props.children = childArray; } return { $$typeof: REACT_ELEMENT_TYPE, type: type, key: key === undefined ? null : '' + key, ref: null, props: props, _owner: null }; }

_jsx(Baz, {
  foo: "bar"
}, "1");
```

**Comment by sormy** [comment] 2019-07-01 14:29
I traced down the issue. An example is here: https://github.com/sormy/babel-helpers-es3-bug
Rollup babel plugin is using `@babel/helper-module-imports` to inject helpers from `@babel/helpers` and this module injects helpers as it is without transformation. I propose to make this one line fix to `@babel/helpers` to fix use case when `@babel/helper-module-imports` is used directly.

**Comment by nicolo-ribaudo** [comment] 2019-07-01 22:05
Thank you for the repo. I'm not opposed to changing our helper's code _per se_, but I think that we should fix the root cause of this. In the future Babel helpers will require new es features, so this problem will come up again.
I belive that this should be fixed in `rollup-plugin-babel`: it should allow transpiling the helpers that it injects.

As a workaround, you can use `@babel/runtime` instead of relying on `rollup-plugin-babel` to automatically inject them. You can update your example repo as follows:
```js
// .babelrc (renamed to babel.config.js)

module.exports = {
  "presets": [
    ["@babel/preset-env", { "targets": ["IE 7"], "loose": true }],
    "@babel/preset-react"
  ],
  "plugins": [
    "@babel/plugin-transform-react-inline-elements",
    ["@babel/plugin-transform-runtime", { "useESModules": true }]
  ]
};
```

```js
// rollup.config.js

import babel from "rollup-plugin-babel"
import resolve from "rollup-plugin-node-resolve";

export default [
  {
    input: "test.js",
    plugins: [
      resolve(),
      babel({ runtimeHelpers: true }),
    ],
    external: (path) => !path.startsWith("@babel/runtime/helpers"),
    output: {
      file: `test.out.rollup.js`,
      format: "iife",
      compact: false,
      freeze: false,
      name: "FulfillmentHIGComponents"
    }
  }
]
```

```json5
// package.json
{
  "scripts": {
    "build": "npm run build-rollup && npm run build-babel",
    "build-rollup": "rollup -c",
    "build-babel": "babel test.js --out-file test.out.babel.js"
  },
  "dependencies": {
    "@babel/cli": "^7.4.3",
    "@babel/core": "^7.4.3",
    "@babel/plugin-transform-react-inline-elements": "^7.2.0",
    "@babel/plugin-transform-runtime": "^7.4.4",
    "@babel/preset-env": "^7.4.3",
    "@babel/preset-react": "^7.0.0",
    "@babel/runtime": "^7.4.5",
    "rollup": "^1.16.3",
    "rollup-plugin-babel": "^4.3.3",
    "rollup-plugin-node-resolve": "^5.2.0"
  }
}

```

**Comment by sormy** [comment] 2019-07-02 19:52
The issue explained here is **the only** ES3 compatibility issue in `@babel/helpers` I'm aware of. Everything else is written in pretty compatible way. 

Asking all consumers of `@babel/helpers` to pull `@babel/core` and `@babel/preset-env` as a dependency and do runtime transformation from `Symbol.for` to `Symbol["for"]` is much more difficult (new code, tests, slower, extra dependencies) rather than just updating this one line. Proposed workaround looks ok but still not simple and intuitive as proposed one line fixer.

The right way I think is to compile helpers to the lowers supported ecma version on `@babel/helpers` publish phase but it is totally fine to fix this issue manually using proposed one line fix. This one line fix won't have any impact on modern browsers but will introduce es3 support for free without requirement for developers to write, test and support and new code.

**Comment by nicolo-ribaudo** [comment] 2019-07-02 21:04
> Asking all consumers of @babel/helpers to pull @babel/core and @babel/preset-env as a dependency and do runtime transformation from Symbol.for to Symbol["for"] is much more difficult

`@babel/helpers` is not meant to be used directly: it's an internal package which needs to be injected by something else (`@babel/core`, `@babel/transform-runtime`, etc). The packages which inject `@babel/helpers` are responsible of transpiling them.
`@babel/runtime` _is not_ "loading Babel at runtime": it's a package which contains all the helpers already transpiled down to ES3, and it is how helpers are meant to be consumed.
`rollup-plugin-babel` tries to abstract away that package, by automatically injecting the helpers, but it doesn't transpile them.

cc @Andarist I have tried too look at `rollup-plugin-babel`'s internally works, and I understood that it generates a "virtual" file containing all the helpers. Is there anything preventing Babel from transpiling that virtual file?

**Comment by nicolo-ribaudo** [comment] 2019-07-02 21:06
@sormy If you reopen your PR I will accept it, but I'd like this issue to also be fixed at the fundamental level.

**Comment by sormy** [comment] 2019-07-02 21:31
@nicolo-ribaudo Thank you, can't reopen, but will rebase and resubmit it.

**Comment by nicolo-ribaudo** [comment] 2019-07-02 22:10
Note for myself: this is related to https://github.com/rollup/rollup-plugin-babel/issues/312#issuecomment-507830484

**Comment by Andarist** [comment] 2019-07-03 06:50
> cc @Andarist I have tried too look at rollup-plugin-babel's internally works, and I understood that it generates a "virtual" file containing all the helpers. Is there anything preventing Babel from transpiling that virtual file?

We've had issues with babel transpiling helpers code - I don't remember exactly but seems like it was some problem similar to `typeof` helper (which uses typeof operator) being transformed with typeof plugin. I remember merging once PR which tried to do exactly that (transpiling virtual module) but had to revert it - https://github.com/rollup/rollup-plugin-babel/pull/227#issuecomment-401634742

**Comment by nicolo-ribaudo** [comment] 2019-07-03 08:29
That's right. There should be a way (maybe via Babel's `overrides`) to specify a different config for helpers, to include only the necessary transforms.

**Comment by Andarist** [comment] 2019-07-03 09:38
It would be possible to transform this virtual module with different Babel setting than the rest of the code, but that approach is not future-proof - we can't be sure that such overrides setting won't have to change in the future.

**Comment by nicolo-ribaudo** [comment] 2019-07-03 11:08
That's as much future-proof as it is to specify a different config to transpile `@babel/runtime`.

**Closed** 2019-07-03 14:49 UTC
Labels: i: bug
