### ISSUE TITLE
Cannot find module '@babel/runtime/helpers/typeof' with @babel/runtime installed

### ISSUE THREAD

**Issue by michaelyara** [babel/babel#11872] opened 2020-07-23 21:17 UTC
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**
I'm attempting to package [swagger2openapi](https://github.com/Mermade/oas-kit/tree/master/packages/swagger2openapi) as a standalone library for use in the browser using browserify, bableify, and Babel 7.10.4. Due to my environment I cannot package the library with my application.

I need the runtime component for this, so I installed `@babel/plugin-transform-runtime` and `@babel/runtime`. I removed the browserify config from package.json and use the following command:

```shell
browserify swagger2openapi.js -s swagger2openapi -t [ babelify --presets [ @babel/preset-env ] --plugins [ @babel/plugin-transform-runtime ] --global true]  > swagger2openapi.es5.min.js
```

Running the command results in the following error:

```shell
Error: Cannot find module '@babel/runtime/helpers/typeof' from '/usr/local/google/home/michaelyara/.nvm/versions/node/v10.17.0/lib/node_modules/browserify/node_modules/url'
    at /usr/local/google/home/michaelyara/.nvm/versions/node/v10.17.0/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/usr/local/google/home/michaelyara/.nvm/versions/node/v10.17.0/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/usr/local/google/home/michaelyara/.nvm/versions/node/v10.17.0/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/usr/local/google/home/michaelyara/.nvm/versions/node/v10.17.0/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/local/google/home/michaelyara/.nvm/versions/node/v10.17.0/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /usr/local/google/home/michaelyara/.nvm/versions/node/v10.17.0/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:153:21)
```

I have verified that `node_modules/@babel/runtime/helpers/typeof.js` does exist. I have also attempted to delete `node_modules`, clear all caches, and reboot my machine, without effect. 

- Command: `ls -la node_modules/@babel/runtime/helpers/`

```shell
total 344
drwxr-x--- 3 michaelyara primarygroup  4096 Jul 23 14:29 .
drwxr-x--- 4 michaelyara primarygroup  4096 Jul 23 14:29 ..
-rw-r----- 1 michaelyara primarygroup   830 Oct 26  1985 applyDecoratedDescriptor.js
-rw-r----- 1 michaelyara primarygroup   234 Oct 26  1985 arrayLikeToArray.js
-rw-r----- 1 michaelyara primarygroup   106 Oct 26  1985 arrayWithHoles.js
-rw-r----- 1 michaelyara primarygroup   185 Oct 26  1985 arrayWithoutHoles.js
-rw-r----- 1 michaelyara primarygroup   219 Oct 26  1985 assertThisInitialized.js
-rw-r----- 1 michaelyara primarygroup  1059 Oct 26  1985 asyncGeneratorDelegate.js
-rw-r----- 1 michaelyara primarygroup  2045 Oct 26  1985 AsyncGenerator.js
-rw-r----- 1 michaelyara primarygroup   458 Oct 26  1985 asyncIterator.js
-rw-r----- 1 michaelyara primarygroup   809 Oct 26  1985 asyncToGenerator.js
-rw-r----- 1 michaelyara primarygroup   155 Oct 26  1985 awaitAsyncGenerator.js
-rw-r----- 1 michaelyara primarygroup    86 Oct 26  1985 AwaitValue.js
-rw-r----- 1 michaelyara primarygroup   196 Oct 26  1985 classCallCheck.js
-rw-r----- 1 michaelyara primarygroup   168 Oct 26  1985 classNameTDZError.js
-rw-r----- 1 michaelyara primarygroup   653 Oct 26  1985 classPrivateFieldDestructureSet.js
-rw-r----- 1 michaelyara primarygroup   342 Oct 26  1985 classPrivateFieldGet.js
-rw-r----- 1 michaelyara primarygroup   267 Oct 26  1985 classPrivateFieldLooseBase.js
-rw-r----- 1 michaelyara primarygroup   137 Oct 26  1985 classPrivateFieldLooseKey.js
-rw-r----- 1 michaelyara primarygroup   489 Oct 26  1985 classPrivateFieldSet.js
-rw-r----- 1 michaelyara primarygroup   231 Oct 26  1985 classPrivateMethodGet.js
-rw-r----- 1 michaelyara primarygroup   142 Oct 26  1985 classPrivateMethodSet.js
-rw-r----- 1 michaelyara primarygroup   347 Oct 26  1985 classStaticPrivateFieldSpecGet.js
-rw-r----- 1 michaelyara primarygroup   494 Oct 26  1985 classStaticPrivateFieldSpecSet.js
-rw-r----- 1 michaelyara primarygroup   256 Oct 26  1985 classStaticPrivateMethodGet.js
-rw-r----- 1 michaelyara primarygroup   165 Oct 26  1985 classStaticPrivateMethodSet.js
-rw-r----- 1 michaelyara primarygroup   659 Oct 26  1985 construct.js
-rw-r----- 1 michaelyara primarygroup   596 Oct 26  1985 createClass.js
-rw-r----- 1 michaelyara primarygroup  1424 Oct 26  1985 createForOfIteratorHelper.js
-rw-r----- 1 michaelyara primarygroup   840 Oct 26  1985 createForOfIteratorHelperLoose.js
-rw-r----- 1 michaelyara primarygroup   702 Oct 26  1985 createSuper.js
-rw-r----- 1 michaelyara primarygroup 13357 Oct 26  1985 decorate.js
-rw-r----- 1 michaelyara primarygroup   384 Oct 26  1985 defaults.js
-rw-r----- 1 michaelyara primarygroup   681 Oct 26  1985 defineEnumerableProperties.js
-rw-r----- 1 michaelyara primarygroup   289 Oct 26  1985 defineProperty.js
drwxr-x--- 2 michaelyara primarygroup  4096 Jul 23 14:29 esm
-rw-r----- 1 michaelyara primarygroup   427 Oct 26  1985 extends.js
-rw-r----- 1 michaelyara primarygroup   600 Oct 26  1985 get.js
-rw-r----- 1 michaelyara primarygroup   267 Oct 26  1985 getPrototypeOf.js
-rw-r----- 1 michaelyara primarygroup   505 Oct 26  1985 inherits.js
-rw-r----- 1 michaelyara primarygroup   223 Oct 26  1985 inheritsLoose.js
-rw-r----- 1 michaelyara primarygroup   400 Oct 26  1985 initializerDefineProperty.js
-rw-r----- 1 michaelyara primarygroup   262 Oct 26  1985 initializerWarningHelper.js
-rw-r----- 1 michaelyara primarygroup   248 Oct 26  1985 instanceof.js
-rw-r----- 1 michaelyara primarygroup   147 Oct 26  1985 interopRequireDefault.js
-rw-r----- 1 michaelyara primarygroup  1179 Oct 26  1985 interopRequireWildcard.js
-rw-r----- 1 michaelyara primarygroup   140 Oct 26  1985 isNativeFunction.js
-rw-r----- 1 michaelyara primarygroup   394 Oct 26  1985 isNativeReflectConstruct.js
-rw-r----- 1 michaelyara primarygroup   168 Oct 26  1985 iterableToArray.js
-rw-r----- 1 michaelyara primarygroup   605 Oct 26  1985 iterableToArrayLimit.js
-rw-r----- 1 michaelyara primarygroup   372 Oct 26  1985 iterableToArrayLimitLoose.js
-rw-r----- 1 michaelyara primarygroup  1138 Oct 26  1985 jsx.js
-rw-r----- 1 michaelyara primarygroup   325 Oct 26  1985 maybeArrayLike.js
-rw-r----- 1 michaelyara primarygroup   185 Oct 26  1985 newArrowCheck.js
-rw-r----- 1 michaelyara primarygroup   231 Oct 26  1985 nonIterableRest.js
-rw-r----- 1 michaelyara primarygroup   230 Oct 26  1985 nonIterableSpread.js
-rw-r----- 1 michaelyara primarygroup   160 Oct 26  1985 objectDestructuringEmpty.js
-rw-r----- 1 michaelyara primarygroup  1068 Oct 26  1985 objectSpread2.js
-rw-r----- 1 michaelyara primarygroup   631 Oct 26  1985 objectSpread.js
-rw-r----- 1 michaelyara primarygroup   665 Oct 26  1985 objectWithoutProperties.js
-rw-r----- 1 michaelyara primarygroup   384 Oct 26  1985 objectWithoutPropertiesLoose.js
-rw-r----- 1 michaelyara primarygroup   343 Oct 26  1985 possibleConstructorReturn.js
-rw-r----- 1 michaelyara primarygroup   119 Oct 26  1985 readOnlyError.js
-rw-r----- 1 michaelyara primarygroup  1250 Oct 26  1985 set.js
-rw-r----- 1 michaelyara primarygroup   237 Oct 26  1985 setPrototypeOf.js
-rw-r----- 1 michaelyara primarygroup   181 Oct 26  1985 skipFirstGeneratorNext.js
-rw-r----- 1 michaelyara primarygroup   432 Oct 26  1985 slicedToArray.js
-rw-r----- 1 michaelyara primarygroup   457 Oct 26  1985 slicedToArrayLoose.js
-rw-r----- 1 michaelyara primarygroup   289 Oct 26  1985 superPropBase.js
-rw-r----- 1 michaelyara primarygroup   252 Oct 26  1985 taggedTemplateLiteral.js
-rw-r----- 1 michaelyara primarygroup   187 Oct 26  1985 taggedTemplateLiteralLoose.js
-rw-r----- 1 michaelyara primarygroup   132 Oct 26  1985 tdz.js
-rw-r----- 1 michaelyara primarygroup   208 Oct 26  1985 temporalRef.js
-rw-r----- 1 michaelyara primarygroup    70 Oct 26  1985 temporalUndefined.js
-rw-r----- 1 michaelyara primarygroup   396 Oct 26  1985 toArray.js
-rw-r----- 1 michaelyara primarygroup   431 Oct 26  1985 toConsumableArray.js
-rw-r----- 1 michaelyara primarygroup   482 Oct 26  1985 toPrimitive.js
-rw-r----- 1 michaelyara primarygroup   252 Oct 26  1985 toPropertyKey.js
-rw-r----- 1 michaelyara primarygroup   479 Oct 26  1985 typeof.js
-rw-r----- 1 michaelyara primarygroup   528 Oct 26  1985 unsupportedIterableToArray.js
-rw-r----- 1 michaelyara primarygroup   212 Oct 26  1985 wrapAsyncGenerator.js
-rw-r----- 1 michaelyara primarygroup  1129 Oct 26  1985 wrapNativeSuper.js
-rw-r----- 1 michaelyara primarygroup  1994 Oct 26  1985 wrapRegExp.js
```

**Expected behavior**
I expect the package execution to succeed without error.

**Babel Configuration**

- Filename: `package.json`

```js
{
  "name": "swagger2openapi",
  "version": "6.2.1",
  "description": "Convert Swagger 2.0 definitions to OpenApi 3.0 and validate",
  "main": "index.js",
  "bin": {
    "swagger2openapi": "./swagger2openapi.js",
    "oas-validate": "./oas-validate.js",
    "boast": "./boast.js"
  },
  "funding": "https://github.com/Mermade/oas-kit?sponsor=1",
  "scripts": {
    "test": "mocha"
  },
  "repository": {
    "url": "https://github.com/Mermade/oas-kit.git",
    "type": "git"
  },
  "bugs": {
    "url": "https://github.com/mermade/oas-kit/issues"
  },
  "author": "Mike Ralphson <mike.ralphson@gmail.com>",
  "license": "BSD-3-Clause",
  "dependencies": {
    "@babel/runtime": "7.10.4",
    "better-ajv-errors": "^0.6.1",
    "call-me-maybe": "^1.0.1",
    "node-fetch-h2": "^2.3.0",
    "node-readfiles": "^0.2.0",
    "oas-kit-common": "^1.0.8",
    "oas-resolver": "^2.4.1",
    "oas-schema-walker": "^1.1.4",
    "oas-validator": "^4.0.6",
    "reftools": "^1.1.3",
    "yaml": "^1.8.3",
    "yargs": "^15.3.1"
  },
  "keywords": [
    "swagger",
    "openapi",
    "openapi2",
    "openapi3",
    "converter",
    "conversion",
    "validator",
    "validation",
    "resolver",
    "lint",
    "linter"
  ],
  "gitHead": "5cbeab49334ebe18c117764d086e1cfe7d708e97",
  "devDependencies": {
    "@babel/core": "7.10.4",
    "@babel/plugin-transform-runtime": "7.10.4",
    "@babel/preset-env": "7.10.4",
    "babelify": "10.0.0"
  }
}
```

**Environment**

- Babel version(s): 7.10.4
- Node/npm version: Node v10.17.0/npm 6.11.3
- OS: Linux 5.6 Debian GNU/Linux
- Monorepo: ?
- How you are using Babel: browserify + babelify

**Possible Solution**

**Additional context**
Add any other context about the problem here. Or a screenshot if applicable

**Comment by Rahulgarg30591** [comment] 2020-09-24 08:47
Hello, @michaelyara any luck, I am facing the same?

**Comment by AlexVipond** [comment] 2020-10-27 17:55
@michaelyara @Rahulgarg30591 if your files are importing runtime helpers as ES modules, try importing from `@babel/runtime/helpers/esm/<helper>` instead of `@babel/runtime/helpers/<helper>`. If your build step allows you to alias import paths to other paths, this package might help you easily alias any and all `@babel/runtime/helpers` imports to the `esm` directory: https://baleada.dev/docs/alias-babel-runtime

The package provides a function that I designed for Vite configuration, but the function returns a plain JavaScript object that should be pretty easy to reformat for other tools' configurations if necessary.

**Comment by nicolo-ribaudo** [comment] 2021-01-30 14:01
Closing, since we cannot reproduce this bug.

**Closed by nicolo-ribaudo** 2021-01-30 14:01 UTC
Labels: i: bug, i: needs reproduction
