### ISSUE TITLE
@babel/plugin-proposal-decorators does not work properly with class properties

### ISSUE THREAD

**Issue by tomitrescak** [babel/babel#11596] opened 2020-05-22 06:09 UTC
## Bug Report

Following code works correctly with Typescript compiler but fails with Babel.

**Current behavior**
A clear and concise description of the behavior.

**Input Code**

```js
function undoable(target: any, propertyKey: string) {
  Object.defineProperty(target, propertyKey, {
    get: function () {
      return 'customFoo';
    },
  });
}

class PropModel {
  @undoable foo?: string;
}

const g = new PropModel();
console.log(g.foo); // her is 'undefined' with Babel, but 'customFoo' with Typescript
```

**Expected behavior**
A clear and concise description of what you expected to happen (or code).

I am able to override class protptype in the decorator.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
{
  "presets": ["next/babel"],
  "plugins": [
    "jsx-control-statements",
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    ["@babel/plugin-proposal-class-properties", { "loose": true }]
  ],
  "env": {
    "test": {
      "plugins": ["babel-plugin-istanbul"]
    }
  }
}
```

**Environment**

```
  System:
    OS: Windows 10 10.0.18363
  Binaries:
    Node: 12.16.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
```

- Monorepo: No
- How you are using Babel: Webpack

**Possible Solution**

**Additional context**
Add any other context about the problem here. Or a screenshot if applicable

**Comment by JLHwung** [comment] 2021-02-04 20:30
Duplicate of #9773

**Comment by JLHwung** [comment] 2021-02-04 20:33
See https://github.com/babel/babel/issues/9773#issuecomment-476867466 for the workaround. This is of known discrepancy between Babel and TS. Babel applies an extra `[DefineProperty]` on class properties, TS only decorates the prototype. The original legacy spec does not specify how decorators should be integrated with class properties.

**Closed by JLHwung** 2021-02-04 20:33 UTC
Labels: i: bug, i: needs triage
