### ISSUE TITLE
How to traverse root path

### ISSUE THREAD

**Issue by liuxingbaoyu** [babel/babel#11051] opened 2020-01-23 17:44 UTC
Hello, how do I traverse the root path?
I found [this issue](https://github.com/babel/babel/issues/9683), but it has been idle for a long time.
Is there any good way? thank!

**Comment by nicolo-ribaudo** [comment] 2020-01-24 22:01
Currently this is not possible.
You can do something like this:
```js
function traverseFromRoot(path, visitor, state) {
  visitor = traverse.visitors.explode(visitor);
  if (visitor[path.type]) visitor[path.type].enter.call(state, path, state);
  path.traverse(visitor, state);
  if (visitor[path.type]) visitor[path.type].enter.call(state, path, state);
}
```

I'm closing this as a duplicate of the issue you linked.

**Closed by nicolo-ribaudo** 2020-01-24 22:01 UTC
Labels: i: needs triage, i: question

**Comment by liuxingbaoyu** [comment] 2020-01-25 11:33
@nicolo-ribaudo Thank you! Should I `exit` after `enter`?

**Comment by nicolo-ribaudo** [comment] 2020-01-25 14:11
Oh yeah, right!

**Comment by liuxingbaoyu** [comment] 2020-01-25 14:47
> Oh yeah, right!

Thanks!

**Comment by liuxingbaoyu** [comment] 2020-01-26 07:24
This works for me.
```js
function traverseFromRoot(path, visitor, state) {
    visitor = traverse.visitors.explode(visitor);
    if (visitor[path.type] && visitor[path.type].enter) visitor[path.type].enter[0].call(state, path, state);
    path.traverse(visitor, state);
    if (visitor[path.type] && visitor[path.type].exit) visitor[path.type].exit[0].call(state, path, state);
}
```
