### ISSUE TITLE
Regression: `TypeError: Cannot read property 'node' of undefined` in  `@babel/plugin-proposal-decorators@7.0.0-beta.35`

### ISSUE THREAD

**Issue by jrencz** [babel/babel#7049] opened 2017-12-18 14:55 UTC
I recently tried `babel@7.0.0-beta.35` and I noticed that there's a regression.

My dependency chain is:
(my project) <-- `@babel/preset-stage-0` <-- `@babel/preset-stage-1` <-- `@babel/plugin-proposal-decorators`

It looks like the pre-beta.35 version of the plugin did opt out because of this code:

https://github.com/babel/babel/blob/a7c9264c792baf8aa09ae47887c88863245eb4ca/packages/babel-plugin-proposal-decorators/src/index.js#L375-L381

While beta.35 does not opt out at its replacement:

https://github.com/babel/babel/blob/8a4124b2ffaf33f032383667fa7956bf64759828/packages/babel-plugin-proposal-decorators/src/index.js#L261

(introduced via https://github.com/babel/babel/commit/9cc0a26694df2a5af508689d7f7b145e7ca483a5)

I was not able to track it down to a minimum reproducible example yet.
All I was able to check is that the result of expression `path.get("right.arguments")` in 

https://github.com/babel/babel/blob/8a4124b2ffaf33f032383667fa7956bf64759828/packages/babel-plugin-proposal-decorators/src/index.js#L268

has length of `1`.
I also checked that adding `if (!path.get("right.arguments")[1]) return;` prevents the error from being triggered but it was only a blind guess of mine to add that line there. I'm not aware of the consequences of such move

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-beta.35
| Babylon          | n/a 
| node             | 8.9.1
| npm              | 5.5.1
| Operating System | macOS 10.13.1

**Comment by hzoo** [comment] 2017-12-18 15:02
Duplicate of https://github.com/babel/babel/issues/7045, https://github.com/babel/babel/issues/7041, etc. I'l leave this open since it seems like it's going to keep getting reported before we release

**Comment by hzoo** [comment] 2017-12-25 19:09
Released [beta.36](https://github.com/babel/babel/releases/tag/v7.0.0-beta.36) with the fix, Merry Christmas y'all!

**Closed by hzoo** 2017-12-25 19:09 UTC
