### ISSUE TITLE
"new (() => {})" must throw a TypeError

### ISSUE THREAD

**Issue by malyw** [babel/babel#2208] opened 2015-08-13 10:12 UTC
Expected: Throw and error
Chrome console- ![Chrome console](http://i.imgur.com/IHTlVIp.png)

Current: Just invoke an arrow function as constructor
Babel-  ![Babel](http://i.imgur.com/uVOshAo.png)
Babel live- https://babeljs.io/repl/#?experimental=false&evaluate=true&loose=false&spec=true&code=let%20foo%20%3D%20(x)%20%3D%3E%20console.log('inside%20an%20arrow%20function')%3B%0A%0Avar%20ert%20%3D%20new%20foo()%3B

Spec:
http://tc39wiki.calculist.org/es6/arrow-functions/
"Details" section -> text "So new (() => {}) throws a TypeError"

**Comment by Skalman** [comment] 2015-08-13 11:05
See also #1692.

**Comment by sebmck** [comment] 2015-08-13 12:31
Duplicate of #616, see #1692 which introduces an `es6.spec.arrowFunctions` transformer that includes a workaround that covers some of these semantics.

**Closed by sebmck** 2015-08-13 12:31 UTC
