### ISSUE TITLE
Runner Keeps Running in Background

### ISSUE THREAD

**Issue by dotsinspace** [babel/babel#16532] opened 2024-05-27 04:28 UTC
### How are you using Babel?

@babel/node

### Input code

```js
{
  "name": "__server",
  "version": "1.21.1",
  "private": true,
  "lint-staged": {
    "*.{js,md, json}": [
      "eslint --fix"
    ]
  },
  "pnpm": {
    "overrides": {
      "graphql": "16.8.0"
    }
  },
  "workspaces": [
    "packages/*"
  ],
  "scripts": {
    "pre-commit": "lint-staged && pnpm run build",
    "clean": "pnpm recursive run clean && rimraf node_modules pnpm-lock.yaml",
    "pm2": "pnpm run build && pm2 start ./.build/index.js",
    "dev": "export NODE_ENV='DEVELOPMENT' && NODE_OPTIONS=--trace-warnings && DEBUG=*,-babel-watch:*,*pdu.command.out*,-babel,-babel:*,-express:*,-nodemon,-prisma:*,-prisma:client:*,-body-parser:json,-nodemon:*,-babel-watch:*,-winston:*,-ioredis:*,-nodemon::*,-snapdragon:*,-prisma-client,-finalhandler,-winston:create-logger,-follow-redirects nodemon --exec babel-watch index.js",
    "upgrade": "pnpm recursive run upgrade",
    "copy::configuration": "cp package.json pnpm-workspace.yaml schema.prisma .env ./.build",
    "copy::files": "npx babel index.js config.js .env client-identity.p12 ca.key ca.pem --out-dir ./.build --copy-files --ignore node_modules",
    "prebuild": "rm -rf ./.build && mkdir -p ./.build && pnpm run copy::files && pnpm run copy::configuration && pnpm recursive run build && pnpm install",
    "build": "pnpm run prebuild && cd ./.build && pnpm install --shamefully-hoist --ignore-scripts && npx prisma generate",
    "docz::build": "rm -rf ./docs/ && jsdoc -c .jsdoc.json -r .",
    "docz::start": "cd ./docs && http-server ./"
  },
  "dependencies": {
    "@babel/eslint-parser": "7.23.9",
    "@babel/plugin-proposal-pipeline-operator": "7.23.3",
    "@prisma/client": "5.8.1",
    "app-root-path": "3.1.0",
    "debug": "4.3.4",
    "dotenv": "16.4.1",
    "enum": "3.0.4",
    "eslint-config-semistandard": "17.0.0",
    "eslint-config-standard": "17.1.0",
    "eslint-plugin-import": "2.29.1",
    "eslint-plugin-n": "15.7.0",
    "eslint-plugin-promise": "6.1.1",
    "esm": "^3.2.25",
    "fix-esm": "^1.0.1",
    "fs-capacitor": "8.0.0",
    "graphql-import-node": "0.0.5",
    "grunt-jsdoc": "2.4.1",
    "gsm": "^0.1.4",
    "htmlparser": "1.7.7",
    "mcc-mnc-list": "1.1.11",
    "nanolith": "^0.4.6",
    "rc-parser": "1.0.2",
    "rimraf": "5.0.5"
  },
  "devDependencies": {
    "@babel/cli": "7.23.9",
    "@babel/core": "7.23.9",
    "@babel/node": "7.23.9",
    "@babel/plugin-proposal-export-default-from": "7.23.3",
    "@babel/plugin-proposal-export-namespace-from": "7.18.9",
    "@babel/plugin-proposal-object-rest-spread": "7.20.7",
    "@babel/plugin-proposal-partial-application": "7.23.3",
    "@babel/plugin-proposal-throw-expressions": "7.23.3",
    "@babel/plugin-syntax-class-properties": "7.12.13",
    "@babel/plugin-syntax-export-default-from": "7.23.3",
    "@babel/plugin-transform-modules-commonjs": "7.23.3",
    "@babel/plugin-transform-runtime": "7.23.9",
    "@babel/plugin-transform-shorthand-properties": "7.23.3",
    "@babel/polyfill": "7.12.1",
    "@babel/preset-env": "7.23.9",
    "@babel/register": "7.23.7",
    "@babel/runtime": "7.23.9",
    "babel-eslint": "10.1.0",
    "babel-loader": "9.1.3",
    "babel-node": "0.0.1-security",
    "babel-plugin-dynamic-import-node": "2.3.3",
    "babel-plugin-inline-json-import": "0.3.2",
    "babel-plugin-module-resolver": "5.0.0",
    "babel-plugin-root-import": "6.6.0",
    "babel-watch": "7.8.1",
    "eslint": "8.56.0",
    "eslint-config-prettier": "9.1.0",
    "eslint-plugin-prettier": "5.1.3",
    "husky": "8.0.3",
    "lint-staged": "10.4.0",
    "npm": "10.4.0",
    "npm-check-updates": "16.14.14",
    "pnpm": "8.15.0",
    "prisma": "5.8.1"
  },
  "engines": {
    "node": "20.5.0"
  }
}
```

### Configuration file name

babel.config.js

### Configuration

```js
/*
 * EXPORTS
 */
module.exports = __babel => {
  // Use cache.
  __babel.cache(true)

  // Return configuration.
  return {
    'presets': [
      [
        '@babel/preset-env',
        {
          'modules': 'auto'
        }
      ]
    ],
    'plugins': [
      '@babel/plugin-proposal-export-default-from',
      '@babel/plugin-proposal-throw-expressions',
      '@babel/plugin-transform-shorthand-properties',
      '@babel/plugin-syntax-export-default-from',
      'babel-plugin-root-import',
      'dynamic-import-node',
      ['module-resolver', { 'root': ['./', './packages/*'] }],
      ['@babel/plugin-transform-modules-commonjs', { 'allowTopLevelThis': true }],
      ['@babel/plugin-transform-runtime', { 'regenerator': true }],
    ],
    "babelrcRoots": [
      ".",
      "packages/*",
    ],
    'ignore': [
      'credential.json',
      '**/dist/**',
      '**/node_modules/**',
      '**/pgdata/**',
      '**/uploads/**',
      '**/.idea/**'
    ]
  }
}
```

### Current and expected behavior

NOTE: Everything is working fine. But i want to know is it intentionally or am i missing something.

Issue: -> Babel runner.js keeps running even after i have closed my ```Development Server``` and run the ```Production Server``` using ```pnpm run build``` in package.json.

and this is causing huge cpu usage all the time.

<img width="1728" alt="Screenshot 2024-05-27 at 9 58 13 AM" src="https://github.com/babel/babel/assets/76559517/29a0d8d4-c022-4e73-8682-398aca35f913">

### Environment

```

  System:
    OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
  Binaries:
    Node: 20.5.0 - ~/.nvm/versions/node/v20.5.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.5.0/bin/yarn
    npm: 10.4.0 - ~/smsflash__node/node_modules/.bin/npm
    pnpm: 8.15.0 - ~/smsflash__node/node_modules/.bin/pnpm
  Monorepos:
    Yarn Workspaces: 1.22.22
  npmPackages:
    @babel/cli: 7.23.9 => 7.23.9 
    @babel/core: 7.23.9 => 7.23.9 
    @babel/eslint-parser: 7.23.9 => 7.23.9 
    @babel/node: 7.23.9 => 7.23.9 
    @babel/plugin-proposal-export-default-from: 7.23.3 => 7.23.3 
    @babel/plugin-proposal-export-namespace-from: 7.18.9 => 7.18.9 
    @babel/plugin-proposal-object-rest-spread: 7.20.7 => 7.20.7 
    @babel/plugin-proposal-partial-application: 7.23.3 => 7.23.3 
    @babel/plugin-proposal-pipeline-operator: 7.23.3 => 7.23.3 
    @babel/plugin-proposal-throw-expressions: 7.23.3 => 7.23.3 
    @babel/plugin-syntax-class-properties: 7.12.13 => 7.12.13 
    @babel/plugin-syntax-export-default-from: 7.23.3 => 7.23.3 
    @babel/plugin-transform-modules-commonjs: 7.23.3 => 7.23.3 
    @babel/plugin-transform-runtime: 7.23.9 => 7.23.9 
    @babel/plugin-transform-shorthand-properties: 7.23.3 => 7.23.3 
    @babel/polyfill: 7.12.1 => 7.12.1 
    @babel/preset-env: 7.23.9 => 7.23.9 
    @babel/register: 7.23.7 => 7.23.7 
    @babel/runtime: 7.23.9 => 7.23.9 
    babel-eslint: 10.1.0 => 10.1.0 
    babel-loader: 9.1.3 => 9.1.3 
    babel-node: 0.0.1-security => 0.0.1-security 
    babel-plugin-dynamic-import-node: 2.3.3 => 2.3.3 
    babel-plugin-inline-json-import: 0.3.2 => 0.3.2 
    babel-plugin-module-resolver: 5.0.0 => 5.0.0 
    babel-plugin-root-import: 6.6.0 => 6.6.0 
    babel-watch: 7.8.1 => 7.8.1 
    eslint: 8.56.0 => 8.56.0 
```

### Possible solution

Just Restart the Server and Execute ```Production Server``` NOTE: Don't run ```pnpm run dev``` else runner will keep running again and again.

**Comment by JLHwung** [comment] 2024-05-27 05:52
According to your package.json `pnpm run dev` will execute (wrapped for clarity)

```sh
export NODE_ENV='DEVELOPMENT' && \
  NODE_OPTIONS=--trace-warnings && \
  DEBUG=*,-babel-watch:*,*pdu.command.out*,-babel,-babel:*,-express:*,-nodemon,-prisma:*,-prisma:client:*,-body-parser:json,-nodemon:*,-babel-watch:*,-winston:*,-ioredis:*,-nodemon::*,-snapdragon:*,-prisma-client,-finalhandler,-winston:create-logger,-follow-redirects \
  nodemon --exec babel-watch index.js"
```

Can you reproduce this issue _without_ using `nodemon`? For example, just run `babel-watch index.js`. BTW `babel-watch` is not maintained by us, it will be great if you reproduce this issue only using `@babel/cli` or `@babel/node`.

**Comment by dotsinspace** [comment] 2024-06-03 13:40
i jumped from ```babel-node``` itself..ending up using nodemon..there is only option and that is to restart the server.

**Comment by nicolo-ribaudo** [comment] 2024-06-20 11:01
Closing since this issue seem to be caused by packages that we do not maintain (`babel-watch` or `nodemon`). We can reopen if there is a reproduction using `@babel/node` or `@babel/cli`.

**Closed by nicolo-ribaudo** 2024-06-20 11:01 UTC
Labels: i: question
