### ISSUE TITLE
Specification compliance for Module Namespace Objects during import * as foo

### ISSUE THREAD

**Issue by yossarian21** [babel/babel#9107] opened 2018-11-30 22:28 UTC
## Bug Report

Relates to #2276

**Current Behavior**
The following Babel behavior is inconsistent and out of compliance with the specification.

```javascript
// foo.js
export function foo() {}
export default foo;

// other.js
import * as foo from './foo';
foo.foo = 'bar'; // correctly errors
foo.default = 'bar'; // does not error; incorrect
foo.baz = 'bar'; // does not error; incorrect - a Module Namespace Object is not extensible
```

The relevant parts of the specification:
https://www.ecma-international.org/ecma-262/6.0/#sec-module-namespace-objects

> A Module Namespace Object is a module namespace exotic object that provides runtime **property-based access** to a module’s exported bindings

https://www.ecma-international.org/ecma-262/6.0/#sec-module-namespace-exotic-objects

> Each such property has the attributes {[[Configurable]]: false, [[Enumerable]]: true}. Module namespace objects are not extensible.

https://www.ecma-international.org/ecma-262/6.0/#table-42 - the default export is a named export named "default"

**Input Code**
https://github.com/yossarian21/import-spec

```bash
npm install
npm test
```

**Expected behavior/code**
Behavior should be consistent when attempting to assign to an exported symbol named "default" or not named "default" and should conform to the ECMAScript specification.

**Babel Configuration (.babelrc, package.json, cli command)**

https://github.com/yossarian21/import-spec/blob/master/.babelrc
```js
{
    "presets": [
        "@babel/preset-env"
    ]
}
```

**Environment**
- Babel version(s): 7.1.6
- Node/npm version: Node 8.11.1, NPM 5.6.0
- OS: OSX 10.13.6
- Monorepo N/A
- How you are using Babel: cli, register, and loader all affected

**Possible Solution**
For a default export:
```js
// instead of
newObj.default = foo;
// could produce output like a named export:
Object.defineProperty(newObj, 'default', {
    enumerable: true,
    get: function () {
        return foo.default;
    }
);
```

**Comment by nicolo-ribaudo** [comment] 2021-01-31 22:47
Duplicate of https://github.com/babel/babel/issues/2276

**Closed by nicolo-ribaudo** 2021-01-31 22:47 UTC
Labels: spec-violation
