### ISSUE TITLE
[Bug]: Cannot find module '@babel/preset-env/lib/utils'

### ISSUE THREAD

**Issue by Webdvpv** [babel/babel#13758] opened 2021-09-14 12:44 UTC
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

You can see the problem here:
https://github.com/paulmillr/chokidar/issues/1147

### Current and expected behavior

While I use Nuxt.js, I got a module error.

### Environment

System:
    OS: Windows 10 10.0.19043
  Binaries:
    Node: 16.4.2 - C:\Program Files\nodejs\node.EXE
    npm: 7.18.1 - C:\Program Files\nodejs\npm.CMD

**Comment by JLHwung** [comment] 2021-09-14 14:23
Duplicate of https://github.com/nuxt/nuxt.js/pull/8881.

Please update `@nuxt/babel-preset-app` to 2.15.6.

**Closed** 2022-09-04 20:53 UTC
Labels: i: question, area: downstream
