### ISSUE TITLE
Spread operator not working on HTMLcollection in old devices like iPhone 4s

### ISSUE THREAD

**Issue by butlimous** [babel/babel#11762] opened 2020-06-30 12:50 UTC
## Bug Report
**Current behavior**

Spreading an HTMLcollection over an array does not work in iPhone 4s and produces this error:

```
Invalid attempt to spread non-iterable instance. In order to be iterable, non-array objects 
must have a [Symbol.iterator]()method.
```

**Input Code**

```js
const test = [...document.getElementsByTagName('div'), 'xyz'];
```

Working:        Mac browsers (Chrome, Firefox, Safari), Android Chrome (Meizu M5 Note - 2016), and iPhone 8
Not working: iPhone 4s (iOS 9) and very likely other old devices

**Expected behavior**

It should just work on old devices like the iPhone 4s because new browsers now consider HTML collections as iterables (the fact that they work in most, if not all of, recent browsers).

**Environment**

```
  System:
    OS: macOS 10.15.5
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    npm: 6.14.5 - /usr/local/bin/npm
    Babel: 7.9.0
    Babel preset-env: 7.9.5
 - How you are using Babel: [`loader`]
```

**Comment by JLHwung** [comment] 2020-06-30 13:27
Please upgrade to Babel 7.10 and specify `allowArrayLike: true` (https://babeljs.io/docs/en/babel-plugin-transform-spread#allowarraylike)

```json
{
  "plugins": [
    ["@babel/plugin-transform-spread", {
      "allowArrayLike": true
    }]
  ]
}
```

**Comment by JLHwung** [comment] 2020-06-30 13:28
Duplicate of #10509

**Closed by JLHwung** 2020-06-30 13:28 UTC
Labels: i: bug, i: needs triage
