### ISSUE TITLE
[Bug]: #16658 possibly causes value.ensureFunctionName is not a function

### ISSUE THREAD

**Issue by mikevoets** [babel/babel#16684] opened 2024-07-28 20:45 UTC
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

When using `@babel/helper-function-name` internally as a deep dependency (7.23.0 and 7.24.7) it causes the latest version of @babel/preset-env to fail our test suite:

```
TypeError: /home/runner/work/optimal-components/optimal-components/src/testSetup/setupTestingLibrary.js: value.ensureFunctionName is not a function

      at PluginPass.ensureFunctionName (node_modules/@babel/plugin-transform-function-name/src/index.ts:39:17)
      at call (node_modules/@babel/core/node_modules/@babel/traverse/src/visitors.ts:304:14)
      at NodePath.call [as _call] (node_modules/@babel/core/node_modules/@babel/traverse/src/path/context.ts:36:20)
      at NodePath.call (node_modules/@babel/core/node_modules/@babel/traverse/src/path/context.ts:21:18)
      at NodePath.call [as visit] (node_modules/@babel/core/node_modules/@babel/traverse/src/path/context.ts:95:31)
      at TraversalContext.visit [as visitQueue] (node_modules/@babel/core/node_modules/@babel/traverse/src/context.ts:147:16)
      at TraversalContext.visitQueue [as visitMultiple] (node_modules/@babel/core/node_modules/@babel/traverse/src/context.ts:98:17)
      at TraversalContext.visitMultiple [as visit] (node_modules/@babel/core/node_modules/@babel/traverse/src/context.ts:177:19)
      at visit (node_modules/@babel/core/node_modules/@babel/traverse/src/traverse-node.ts:40:17)
      at NodePath.visit (node_modules/@babel/core/node_modules/@babel/traverse/src/path/context.ts:102:33)
      at TraversalContext.visit [as visitQueue] (node_modules/@babel/core/node_modules/@babel/traverse/src/context.ts:147:16)
      at TraversalContext.visitQueue [as visitMultiple] (node_modules/@babel/core/node_modules/@babel/traverse/src/context.ts:98:17)
      at TraversalContext.visitMultiple [as visit] (node_modules/@babel/core/node_modules/@babel/traverse/src/context.ts:177:19)
      at visit (node_modules/@babel/core/node_modules/@babel/traverse/src/traverse-node.ts:40:17)
      at NodePath.visit (node_modules/@babel/core/node_modules/@babel/traverse/src/path/context.ts:102:33)
      at TraversalContext.visit [as visitQueue] (node_modules/@babel/core/node_modules/@babel/traverse/src/context.ts:147:16)
      at TraversalContext.visitQueue [as visitSingle] (node_modules/@babel/core/node_modules/@babel/traverse/src/context.ts:108:19)
      at TraversalContext.visitSingle [as visit] (node_modules/@babel/core/node_modules/@babel/traverse/src/context.ts:179:19)
      at visit (node_modules/@babel/core/node_modules/@babel/traverse/src/traverse-node.ts:40:17)
      at NodePath.visit (node_modules/@babel/core/node_modules/@babel/traverse/src/path/context.ts:102:33)
      at TraversalContext.visit [as visitQueue] (node_modules/@babel/core/node_modules/@babel/traverse/src/context.ts:147:16)
      at TraversalContext.visitQueue [as visitMultiple] (node_modules/@babel/core/node_modules/@babel/traverse/src/context.ts:98:17)
      at TraversalContext.visitMultiple [as visit] (node_modules/@babel/core/node_modules/@babel/traverse/src/context.ts:177:19)
      at visit (node_modules/@babel/core/node_modules/@babel/traverse/src/traverse-node.ts:40:17)
      at NodePath.visit (node_modules/@babel/core/node_modules/@babel/traverse/src/path/context.ts:102:33)
      at TraversalContext.visit [as visitQueue] (node_modules/@babel/core/node_modules/@babel/traverse/src/context.ts:147:16)
      at TraversalContext.visitQueue [as visitSingle] (node_modules/@babel/core/node_modules/@babel/traverse/src/context.ts:108:19)
      at TraversalContext.visitSingle [as visit] (node_modules/@babel/core/node_modules/@babel/traverse/src/context.ts:179:19)
      at visit (node_modules/@babel/core/node_modules/@babel/traverse/src/traverse-node.ts:40:17)
      at traverse (node_modules/@babel/core/node_modules/@babel/traverse/src/index.ts:82:15)
      at transformFile (node_modules/@babel/core/src/transformation/index.ts:[12](https://github.com/optimalworkshop/optimal-components/actions/runs/10133835826/job/28019421259?pr=529#step:5:13)4:15)
          at transformFile.next (<anonymous>)
      at transformFile (node_modules/@babel/core/src/transformation/index.ts:48:12)
          at run.next (<anonymous>)
      at transform (node_modules/@babel/core/src/transform.ts:29:20)
          at transform.next (<anonymous>)
      at evaluateSync (node_modules/gensync/index.js:251:28)
      at sync (node_modules/gensync/index.js:89:[14](https://github.com/optimalworkshop/optimal-components/actions/runs/10133835826/job/28019421259?pr=529#step:5:15))
```

This seems to have been caused by https://github.com/babel/babel/pull/16658.

### Current and expected behavior

It's failing our test suite when running babel.

Expected behaviour is to keep passing.

### Environment

Babel version: 7.25.0
Yarn version: 4.1.1
OS: Apple M1 Pro Version 14.5 (23F79)

**Comment by JLHwung** [comment] 2024-07-28 22:11
Duplicate of #16682.

Please upgrade `@babel/plugin-transform-function-name` to 7.25.1 or remove `@babel/*` in your lock files and install again so that there will not be duplicate `@babel/traverse` copies in the node_modules.

**Comment by mikevoets** [comment] 2024-07-28 23:43
Hey @JLHwung thanks for your fast reply. I tried adding `"@babel/plugin-transform-function-name": "^7.25.1"` to our dependencies list in package.json, but this didn't solve the issue on our end. "@babel/preset-env" 7.25.0 (latest) still uses 7.25.0 of this package.

**Comment by JLHwung** [comment] 2024-07-29 00:10
@mikevoets `@babel/plugin-transform-function-name` is a transitive dependency of preset-env, after installing it, you can run `npm dedupe` or `yarn dedupe`, which should pick up the latest Babel plugin, and then safely remove it from your package.json.

**Comment by XinChou16** [comment] 2024-07-29 02:24
same issue, value.requeueComputedkeyAndDecorators is not function, when lock @babel/traverse 7.20.1

**Comment by TaR1z** [comment] 2024-07-29 05:01
try to lock package.json `@babel/traverse version`
```json
"overrides": {
  "@babel/traverse": "7.25.1"
}
```

**Comment by Hao-yiwen** [comment] 2024-07-29 07:10
Same question.i think today all lock version of `@babel/traverse` maybe will meet this question.

**Comment by nicolo-ribaudo** [comment] 2024-07-29 09:25
This issue only affects `@babel/plugin-transform-function-name` 7.25.0 with `@babel/traverse` versions older than 7.25.0. There are three possible changes you can make to avoid the error:
- Update @babel/traverse to 7.25.0 or higher (recommended)
- Update @babel/plugin-transform-function-name to 7.25.1 or higher
- Downgrade @babel/plugin-transform-function-name to a version older than 7.25.0 (discouraged)

**Closed by nicolo-ribaudo** 2024-07-29 09:25 UTC
Labels: i: needs triage
