### ISSUE TITLE
Poor support for TypeScript not-null assertions

### ISSUE THREAD

**Issue by Zarel** [babel/babel#7962] opened 2018-05-17 22:06 UTC
## Bug Report

**Current Behavior**
TypeScript's postfix `!` not-null assertion isn't supported in various commonly used scenarios, such as `a! *= 1;` and `a! / 10`

**Input Code**
```ts
function doSomething(a: number | null) {

  // SyntaxError: src/test.ts: Unexpected token =
  a! *= 1;

  // SyntaxError: src/test.ts: Unterminated regular expression
  return a! / 2;

}
```

**Expected behavior/code**
No error

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
	"plugins": [
		"@babel/plugin-transform-typescript"
	]
}
```

**Environment**
- Babel version(s): v7.0.0-beta.47
- Node/npm version: Node 10.1.0 / npm 6
- OS: macOS 10.13.4
- Monorepo ?
- How you are using Babel: `cli`

**Comment by nicolo-ribaudo** [comment] 2018-05-17 22:18
`a! = 2` has been fixed by https://github.com/babel/babel/pull/7888

**Comment by Zarel** [comment] 2018-05-18 01:00
I've updated the first post to Babel 7.0.0-beta.47

`a! += 1` is fixed now! Unfortunately, `a! *= 1` is still an error. :(

**Comment by CoskunSunali** [comment] 2018-05-20 01:28
`const container = document.getElementById('app')!;` piece of code also throws `Unexpected token, expected ";"` because of the `!`.

**Comment by existentialism** [comment] 2018-05-21 02:16
@CoskunSunali what version? I'm not able to reproduce a parsing error in babylon@7.0.0-beta.47

**Closed** 2018-05-24 14:31 UTC
Labels: Has PR, area: typescript, i: bug
