### ISSUE TITLE
problems about creating language based on Babel

### ISSUE THREAD

**Issue by jiyinyiyong** [babel/babel#2698] opened 2015-10-31 05:08 UTC
I was maintaining a small language called CirruScript(http://script.cirru.org/) which is transformed to JavaScript AST and compile to JavaScript with Babel handling some ES6 features. The project was started in babel@5.x and I have to update since babel bumped 6. Here are my code for updating..
https://github.com/Cirru/scirpus/tree/master/test

I got some problems here, probably I need some help to fix them:

1) it appear quite slow to load(or really run) plugins presets. Last version is still pretty fast. I don't know what's happening is that `transformFromAst`:

[file](https://github.com/Cirru/scirpus/blob/master/test/write-code.cirru)

```js
var cirruCode = fs.readFileSync("cirru/" + file + ".cirru", "utf8"),
    cirruAST = parser.pare(cirruCode, file),
    ast = operations.transform(cirruAST),
    result = babel.transformFromAst(ast, "", {
      presets: ["es2015"]
    });
```

```text
➤➤ time cirru-script write-code.cirru
... some logs...

real	0m14.679s
user	0m10.563s
sys	0m2.535s
```

2) ~~As I found that `browser.js` in `babel-core` is totally empty~~(another issue). Also, by reading the code I found `transformFromAst` is likely removed from browser code, which makes it difficult to compile code in browsers with AST. Well, it's not a common case.

3) My code provides a parser and transformer, reads text and returns JavaScript compatible to babylon. As I tried to find a ES6 AST transformer and a code generator, I only get `babel-generator` for code generation. The whole ES6 AST transformer is inside `babel-core` with lots of code. It's quite a large bundle.

I agree that Babel is a code transformer rather than a AST transformer and my case is rare. But please let me know what you think about such cases?

**Comment by thejameskyle** [comment] 2015-10-31 05:16
1) This is already an ongoing issue a couple people have mentioned. Some have said it no longer is an issue with npm 3 but I haven't been able to reproduce either way.
2) There's an existing issue for this (https://github.com/babel/babel/issues/2635) mind removing it from this issue to keep it clean?
3) I'm not sure what you're asking for. You should be able to hand off a babylon compatible AST to `transformFromAst` no problem and you can use `babel-generator` independently.

**Comment by jiyinyiyong** [comment] 2015-10-31 05:50
1) I'm running `npm@2.14.4`. I'm quite curious can I manual require that plugin to see if that helps with the performance?

2) Picture removed. Personally I hope there's still `transformFromAst` available in `browser.js`.

3) As I tried, `babel-generator` returns ES6 code, which I a function to return ES5 code. So there's still a missing part to me.

**Comment by thejameskyle** [comment] 2015-10-31 05:55
>  can I manual require that plugin

```js
babel.transform('...', { plugins: [require('babel-plugin-name')] });
```

> I hope there's still transformFromAst available in browser.js.

It will be once that's fixed.

3. `babel-generator` will simply print out the AST you hand it, it does not transform code in any way.

**Comment by jiyinyiyong** [comment] 2015-10-31 06:23
1) got some logs via `time-require` https://gist.github.com/jiyinyiyong/9520243a2e67e466937a

3) I thought a code transformer is divided to 3 parts,

* parser(`babylon`): source code -> IR
* transformer(part of `babel-core`): IR -> target IR
* code generator(`babel-generator`): target IR -> target code

while `babel-core` actually contains all three components in it.

**Comment by sebmck** [comment] 2015-10-31 06:25
The modules aren't being deduped so more than one instance is being loaded of each.

**Comment by jiyinyiyong** [comment] 2015-10-31 06:33
@sebmck `deduped`? Word not found in dictionary..

So is there a solution now?

**Comment by thejameskyle** [comment] 2015-10-31 06:36
By deduped he means `npm dedupe`

**Comment by sebmck** [comment] 2015-11-02 07:01
Closing this as there's nothing actionable here. Feel free to ask specific questions on the Slack channel.

**Closed by sebmck** 2015-11-02 07:01 UTC
