### ISSUE TITLE
Node enumerable methods make babel's AST difficult to test against

### ISSUE THREAD

**Issue by tmcw** [babel/babel#2543] opened 2015-10-15 21:27 UTC
Specifically the __clone method here: https://github.com/babel/babel/blob/369b9fdc4bf541933f24184a7e8ad7ec0776d600/packages/babylon/src/parser/node.js

I'm writing a system that compares a modified Babel AST at one step in the process, and the existence of enumerable properties makes it difficult to compare a JSON fixture against a produced AST: https://github.com/documentationjs/documentation/blob/master/test/test.js#L62

**Comment by sebmck** [comment] 2015-10-16 03:38
Is there something actionable here? I'm not sure what the issue is and what the proposed solution is (if any).

**Comment by sebmck** [comment] 2015-10-20 02:30
Closing this as there's nothing actionable here. If you have a concrete suggestion feel free to reopen.

**Closed by sebmck** 2015-10-20 02:30 UTC
