### ISSUE TITLE
process.on('message', ...) does not work

### ISSUE THREAD

**Issue by ChrisCinelli** [babel/babel#2886] opened 2015-11-06 22:57 UTC
I am trying to send a message to a parent process with `child.send(...)`.
In the parent I have `process.on('message', function(data){...})` but `function(data)` never get called.

The method work without babel.

See also: http://stackoverflow.com/questions/10394206/how-to-send-message-to-parent-process and http://stackoverflow.com/questions/30700942/trying-to-fork-a-node-js-process-using-gulp-and-babel-on-windows (btw, it is the same on a Mac)

**Comment by loganfsmyth** [comment] 2015-11-07 00:45
This isn't actionable without a solid reproducible example. Could you create a git repo to demonstrate the issue?

**Comment by sebmck** [comment] 2015-11-08 13:41
Closing due to lack of reproducible example. Please reopen or comment on this issue if you manage to narrow it down to a minimal reproducible example because without it we can't do much.

**Closed by sebmck** 2015-11-08 13:41 UTC
Labels: pending triage
