### ISSUE TITLE
Babel picks up translations in ignored folder

### ISSUE THREAD

**Issue by mathieudevos** [babel/babel#7070] opened 2017-12-20 08:26 UTC
### Bug report

Babel is running translations on files which are inside ignored folder(s)

### Expected Behavior
Ignore everything inside ignored folder(s)

### Current Behavior
Babel translates items inside the folder if it finds things that tell babel to translate is

### Possible Solution
Properly ignore folders, don't even check inside them

### Context
Cross-linking reference: [hawk#277](https://github.com/hueniverse/hawk/issues/227)

Basically we have our src folder in our repo, and our dist repo (uncommitted). The build server runs yarn in the src folder, runs all unit tests inside of it.
If this completes it runs babel translation with the following .babelrc

```
{
  "ignore": [
    "node_modules",
    "test"
  ],
  "plugins": [
    "transform-async-to-generator",
    "transform-runtime"
  ],
  "presets": ["es2015"]
}
```

However, taking a look in my build server, I can see the following log:

```
src/folder1/handler.js -> dist/folder1/handler.js
src/folder2/handler.js -> dist/folder1/handler.js
...
src/node_modules/hawk/client.js -> dist/node_modules/hawk/client.js
src/node_modules/hawk/dist/browser.js -> dist/node_modules/hawk/dist/browser.js
src/node_modules/hawk/lib/browser.js -> dist/node_modules/hawk/lib/browser.js
src/node_modules/hawk/lib/client.js -> dist/node_modules/hawk/lib/client.js
src/node_modules/hawk/lib/crypto.js -> dist/node_modules/hawk/lib/crypto.js
src/node_modules/hawk/lib/index.js -> dist/node_modules/hawk/lib/index.js
src/node_modules/hawk/lib/server.js -> dist/node_modules/hawk/lib/server.js
src/node_modules/hawk/lib/utils.js -> dist/node_modules/hawk/lib/utils.js
...
src/folder_last/index.js -> dist/folder_last/index.js
```

Hawk has the following items which (I think) is causing this issue:
`.babelrc`

Hawk already has said they will not fix this issue, and technically, this is a babel issue imho.

**Comment by therobinkim** [comment] 2018-01-18 04:43
According to https://github.com/babel/babel/issues/5664#issuecomment-297016006, it looks like it's fixed in Babel 7.x.

Related: https://github.com/babel/babel/pull/4708#issuecomment-292824191

**Comment by carlevans719** [comment] 2018-02-24 00:01
I've just hit a problem caused by this in 7.0.0-beta.40. 

I have configured the node_modules folder to be ignored in my project's `.babelrc`, but babel-cli is throwing an exception because it is finding duplicate configs inside one of my installed node modules ([`esrecurse`](https://github.com/estools/esrecurse)).

I expected that, because `node_modules` is ignored, that the files inside it would not be scanned at all, however, from looking through the [debug output](https://gist.github.com/carlevans719/2a40aceebdacea04293878187f8ec78e) and [the code](https://github.com/babel/babel/blob/master/packages/babel-core/src/config/files/configuration.js#L50), it appears that the ignore is only being applied after the check for duplicate configs. 

This strikes me as a redundant check because we know that we'll never parse/transpile files anyway so (I think) that duplicate configs won't matter to me. Rather, they are only the concern of the module author, or developer who _doesn't_ ignore their node_modules folder.

I'm aware that there is ongoing? discussion about how hierarchical `.babelrc`s (or synonymous configs) should be handled in #6766. But if the current behaviour is undesired I'd be happy to raise a PR to either:
- only check for duplicate configs if the folder in question hasn't been ignored, or
- not scan ignored folders in the first place


If needed I can get a repro up tomorrow evening.

**Comment by loganfsmyth** [comment] 2018-08-12 00:15
I think Babel 7 addresses most of these complaints since `.babelrc` files are never accessed across `node_modules` borders, and `babel.config.js` files provide a way to have project-level configs that affect whatever files you need.

**Closed by loganfsmyth** 2018-08-12 00:15 UTC
