### ISSUE TITLE
6.x: ExportAllDeclaration causes "Invariant Violation: To get a node path the parent needs to exist"

### ISSUE THREAD

**Issue by douglasduteil** [babel/babel#2763] opened 2015-11-02 22:26 UTC
Hi @sebmck 

I ran into this an issue with ExportAllDeclaration transpilation today.
It seems like there is some kind of collision between the **transform-es2015-block-scoping** and the **transform-es2015-modules-commonjs**.
Here is a sample:

```sh
$ npm ls babel-cli babel-core babel-plugin-transform-es2015-modules-commonjs babel-plugin-transform-es2015-block-scoping
foo@1.0.0 /home/war/tmp/foo
├─┬ babel-cli@6.0.15 
│ └── babel-core@6.0.17 
├── babel-plugin-transform-es2015-block-scoping@6.0.14 
└── babel-plugin-transform-es2015-modules-commonjs@6.0.15 
```

```js
// .babelrc
{
  "plugins": [
    "babel-plugin-transform-es2015-block-scoping",
    "babel-plugin-transform-es2015-modules-commonjs"
  ]
} 
```

```js
// index.js
export * from "FAIL"
```

---

```sh
$ ./node_modules/.bin/babel index.js                                                                                                          
Error: index.js: Invariant Violation: To get a node path the parent needs to exist
    at Object.invariant [as default] (/home/war/tmp/foo/node_modules/invariant/invariant.js:44:15)
    at Function.get (/home/war/tmp/foo/node_modules/babel-traverse/lib/path/index.js:82:27)
    at TraversalContext.create (/home/war/tmp/foo/node_modules/babel-traverse/lib/context.js:73:30)
    at NodePath._containerInsert (/home/war/tmp/foo/node_modules/babel-traverse/lib/path/modification.js:80:32)
    at NodePath._containerInsertBefore (/home/war/tmp/foo/node_modules/babel-traverse/lib/path/modification.js:138:15)
    at NodePath.insertBefore (/home/war/tmp/foo/node_modules/babel-traverse/lib/path/modification.js:57:19)
    at BlockScoping.wrapClosure (/home/war/tmp/foo/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:483:21)
    at BlockScoping.run (/home/war/tmp/foo/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:383:12)
    at PluginPass.Loop (/home/war/tmp/foo/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:89:36)
    at newFn (/home/war/tmp/foo/node_modules/babel-traverse/lib/visitors.js:233:27)

```

**Comment by douglasduteil** [comment] 2015-11-02 22:28
Strangely this code is working...

```js
// index.js
export * from "FAIL"
export {}
```

````sh
$ ./node_modules/.bin/babel index.js
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _FAIL = require("FAIL");

var _loop = function (_key2) {
  if (_key2 === "default") return "continue";
  Object.defineProperty(exports, _key2, {
    enumerable: true,
    get: function () {
      return _FAIL[_key2];
    }
  });
};

for (var _key2 in _FAIL) {
  var _ret = _loop(_key2);

  if (_ret === "continue") continue;
}

export {}; // index.js
````

Any idea ?

**Comment by moimikey** [comment] 2015-11-03 04:31
dupe of #2436?

**Comment by loganfsmyth** [comment] 2015-11-03 05:07
@moimikey Nope. That issue is about a change to how `export * from` is transformed, and this one is an actual bug in the transformation process.

**Comment by moimikey** [comment] 2015-11-03 16:18
@loganfsmyth gotit. thanks for clarifying!

**Comment by Alphapage** [comment] 2015-11-09 14:10
ES6 syntax is broken with Babel6.
All my code is broken now. I can't use ES2015.
It seems Babel6 is alpha or beta but not a released version !!

**Comment by GGAlanSmithee** [comment] 2015-11-09 14:23
That kind of feedback isn't very productive. If you have found a bug, why don't you create an issue with steps to reproduce? (After verifying that it has not been reported already.)

Also, you can still use v5.x until v6 has gotten more stable. (Which it already has in the short time since it ws released.)

**Comment by GGAlanSmithee** [comment] 2015-11-09 14:26
Also, have you read [this](http://babeljs.io/blog/2015/10/31/setting-up-babel-6/)?

**Comment by Alphapage** [comment] 2015-11-09 14:38
I understand you want to build a tool which is more than an ES2015 transpiler.
But for me the heart of Babel is to transpile ES2015 and it doesn't work with Babel6.
I think the priority would be to solve ES2015 transpiling problems like this issue (export * from ... causing "Invariant Violation: To get a node path the parent needs to exist") then polish extra features.

I know this is not very productive, but if it may help to solve the problem quickly!

**Comment by thejameskyle** [comment] 2015-11-16 10:44
Thank spammers for the locked issue

**Closed** 2016-09-07 20:10 UTC
