### ISSUE TITLE
Non-strict common output doesn't have exports = default when I have multiple exports

### ISSUE THREAD

**Issue by bfred-it** [babel/babel#2410] opened 2015-09-22 07:48 UTC
> In order to encourage the use of CommonJS and ES6 modules, when exporting a default `export` **with no other exports** `module.exports` will be set in addition to `exports["default"].`

I found this behavior to be counter-intuitive: it works… until you export more variables. Definitely unexpected :(

This could be fixed by switching by having `module.exports = default` before other exports, added via `module.exports.doSomething = doSomething`

**Comment by jmm** [comment] 2015-09-22 15:15
Hello @bfred-it, welcome to the Babel community! This seems to be a duplicate of #2047, so I'm going to close it. Please see the discussion there and also #2212.

**Closed by jmm** 2015-09-22 15:15 UTC

**Comment by bfred-it** [comment] 2015-09-23 22:37
Sorry about that! Searching completely slipped my mind :disappointed:

**Comment by jmm** [comment] 2015-09-23 22:46
@bfred-it No problem, everybody forgets sometimes.

**Comment by forivall** [comment] 2015-09-23 23:03
Your avatar is perfect for goof-ups like this.

**Comment by jmm** [comment] 2015-09-23 23:32
@forivall I was thinking the same thing -- he looks duly chastened.

**Comment by bfred-it** [comment] 2015-09-24 00:43
I goof up so often that I decided that everything I do online must be accompanied by that.
