### ISSUE TITLE
Can't parse async arrow function declaration with typescript template type (works with pure typescript)

### ISSUE THREAD

**Issue by mcongy** [babel/babel#9594] opened 2019-02-26 15:20 UTC
## Bug Report

**Current Behavior**

Babel can't parse the following syntax. Works perfectly when using pure typescript.

**Input Code**
```js
const importRowsToElasticDB = async <T>(rows: T[], indexName: string, typeName: string): Promise<any> => {
                                                                                       ^
Unexpected token, expected ";"

    at Object.raise (/Users/congy/Desktop/projects/ua-app-backend/node_modules/@babel/parser/lib/index.js:3831:17)
    at Object.unexpected (/Users/congy/Desktop/projects/ua-app-backend/node_modules/@babel/parser/lib/index.js:5143:16)
    at Object.semicolon (/Users/congy/Desktop/projects/ua-app-backend/node_modules/@babel/parser/lib/index.js:5131:40)
    at Object.parseVarStatement (/Users/congy/Desktop/projects/ua-app-backend/node_modules/@babel/parser/lib/index.js:7715:10)
    at Object.parseStatementContent (/Users/congy/Desktop/projects/ua-app-backend/node_modules/@babel/parser/lib/index.js:7310:21)
    at Object.parseStatementContent (/Users/congy/Desktop/projects/ua-app-backend/node_modules/@babel/parser/lib/index.js:10130:18)
    at Object.parseStatement (/Users/congy/Desktop/projects/ua-app-backend/node_modules/@babel/parser/lib/index.js:7243:17)
    at Object.parseBlockOrModuleBlockBody (/Users/congy/Desktop/projects/ua-app-backend/node_modules/@babel/parser/lib/index.js:7810:25)
    at Object.parseBlockBody (/Users/congy/Desktop/projects/ua-app-backend/node_modules/@babel/parser/lib/index.js:7797:10)
    at Object.parseTopLevel (/Users/congy/Desktop/projects/ua-app-backend/node_modules/@babel/parser/lib/index.js:7181:10)
    at Object.parse (/Users/congy/Desktop/projects/ua-app-backend/node_modules/@babel/parser/lib/index.js:8660:17)
    at parse (/Users/congy/Desktop/projects/ua-app-backend/node_modules/@babel/parser/lib/index.js:10660:38)
    at parser (/Users/congy/Desktop/projects/ua-app-backend/node_modules/@babel/core/lib/transformation/normalize-file.js:170:34)
    at normalizeFile (/Users/congy/Desktop/projects/ua-app-backend/node_modules/@babel/core/lib/transformation/normalize-file.js:138:11)
    at runSync (/Users/congy/Desktop/projects/ua-app-backend/node_modules/@babel/core/lib/transformation/index.js:44:43)
    at runAsync (/Users/congy/Desktop/projects/ua-app-backend/node_modules/@babel/core/lib/transformation/index.js:35:14)
    at process.nextTick (/Users/congy/Desktop/projects/ua-app-backend/node_modules/@babel/core/lib/transform.js:34:34)
    at process._tickCallback (internal/process/next_tick.js:61:11)
 ```

**Expected behavior/code**

babel-typescript correctly parses this syntax

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": [
    "@babel/preset-typescript",
    ["@babel/preset-env", {
      "targets": { "node": "8.10" },
      "useBuiltIns": "usage",
      "modules": false,
      "loose": true
    }]
  ],
  "plugins": [
    "babel-plugin-node-source-map-support",
    "@babel/plugin-proposal-optional-catch-binding"
  ]
}
```

**Environment**
- Babel version(s): @babel/core@7.3.4, @babel/preset-typescript@7.3.3
- Node/npm version: Node 11/yarn 1.13
- OS: e.g. OSX 10.13.6
- Monorepo: no
- How you are using Babel: via webpack (latest v4)
- typescript: 3.3.3

**Comment by danez** [comment] 2019-02-27 00:56
Could you run one of the following commands and post the output?
If you use yarn:
```
yarn list --pattern @babel/parser
```
or npm
```
npm list @babel/parser
```

**Comment by nicolo-ribaudo** [comment] 2019-02-27 01:03
Maybe fixed by https://github.com/babel/babel/pull/9593. Is there any other async arrow function with generics before that one?

**Comment by danez** [comment] 2019-02-27 01:04
I wasn't able to reproduce in the repl, just with this one line of code.

**Comment by mcongy** [comment] 2019-02-27 11:57
@danez 

@babel/parser@7.3.4

I tried installing multiple exact versions of every @babel/<> package I use, even @babel/parser, @babel/helpers, typescript and webpack/webpack-cli without any success.

I even tried it on windows PC, outcome is the same.

For now, I decided to use old "function" syntax.

**Comment by dobesv** [comment] 2019-03-06 19:24
Here's a gist that reproduces the issue:

https://gist.github.com/dobesv/500df96b5d2d6edbe9a1af1722aa3029

**Comment by nicolo-ribaudo** [comment] 2019-03-06 19:59
Ok, given the two arrow functions this is definitely a duplicate of https://github.com/babel/babel/issues/9560. It will be fixed in the next release!

**Closed by nicolo-ribaudo** 2019-03-06 19:59 UTC
Labels: area: typescript, i: bug
