### ISSUE TITLE
Error: ES Modules may not assign module.exports or exports.*, Use ESM export syntax, instead: 581

### ISSUE THREAD

**Issue by takhello** [babel/babel#12731] opened 2021-02-01 03:00 UTC
## Bug Report
```
Error: ES Modules may not assign module.exports or exports.*, Use ESM export syntax, instead: 581
```

**Current behavior**
```
Error: ES Modules may not assign module.exports or exports.*, Use ESM export syntax, instead: 581
```

**Expected behavior**
There is no abnormal

**Environment**

webpack version: "webpack": "^5.13.0",
Node.js version: v10.15.3
Operating System: mac
Additional tools:vscode
"@babel/core": "^7.12.10",
"@babel/preset-env": "^7.12.11",

**Possible Solution**

**Additional context**
babel.config.js:
```js
module.exports = {
  presets: [
    [
      '@babel/preset-env',
      {
        corejs: 2,
        useBuiltIns: 'usage'
      }
    ],
    '@vue/babel-preset-jsx'
  ],
  plugins: []

}
```

**Comment by nicolo-ribaudo** [comment] 2021-02-01 21:07
This error is not thrown by Babel, but by webpack.  Can you post your webpack config?

**Comment by Mikilll94** [comment] 2021-02-16 18:14
@nicolas-marien 
I have encountered the same error. Here is the repro project:
[vue-webpack-test.zip](https://github.com/babel/babel/files/5990701/vue-webpack-test.zip)

Here is my webpack config:

```js
const path = require('path')
const { VueLoaderPlugin } = require('vue-loader')
const { CleanWebpackPlugin } = require('clean-webpack-plugin')
const HtmlWebpackPlugin = require('html-webpack-plugin')

module.exports = {
    mode: 'development',
    entry: {
        main: './src/main.js',
    },
    devServer: {
        hot: true,
    },
    module: {
        rules: [
            {
                test: /\.vue$/,
                use: 'vue-loader'
            },
            {
                test: /\.css$/,
                use: [
                    'vue-style-loader',
                    {
                        loader: 'css-loader',
                        options: {
                            esModule: false
                        }
                    },
                ]
            },
            {
                test: /\.scss$/,
                use: [
                    'vue-style-loader',
                    {
                        loader: 'css-loader',
                        options: {
                            esModule: false
                        }
                    },
                    'sass-loader'
                ]
            },
            {
                test: /\.js$/,
                exclude: /core-js/,
                use: 'babel-loader'
            }
        ]
    },
    plugins: [
        new CleanWebpackPlugin(),
        new HtmlWebpackPlugin({
            title: 'Vue + Webpack test',
            template: 'public/index.html',
            scriptLoading: 'blocking'
        }),
        new VueLoaderPlugin()
    ],
    output: {
        filename: '[name].bundle.js',
        path: path.resolve(__dirname, 'dist'),
    }
}
```

**Comment by nicolo-ribaudo** [comment] 2021-02-16 22:10
@Mikilll94 I canno reproduce it:
```
vue-webpack-test on  master [?] is 📦 v1.0.0 via ⬢ v12.17.0 took 6s 
⇣6% ➜ npm run build

> vue-webpack-test@1.0.0 build /home/nicolo/Documenti/dev/babel-bugs/vue-webpack-test
> webpack --config webpack.config.dev.js

asset main.bundle.js 565 KiB [emitted] (name: main)
asset index.html 279 bytes [emitted]
runtime modules 1.54 KiB 6 modules
modules by path ./node_modules/core-js/ 156 KiB
  modules by path ./node_modules/core-js/internals/*.js 85.5 KiB 116 modules
  modules by path ./node_modules/core-js/modules/*.js 70.6 KiB 40 modules
modules by path ./src/ 4.83 KiB 9 modules
modules by path ./components/*.vue 4.56 KiB 8 modules
modules by path ./assets/*.scss 1.49 KiB
  ./assets/app.scss 1.17 KiB [built] [code generated]
  ./node_modules/css-loader/dist/cjs.js??clonedRuleSet-2[0].rules[0].use[1]!./node_modules/sass-loader/dist/cjs.js!./assets/app.scss 332 bytes [built] [code generated]
modules by path ./node_modules/vue-style-loader/lib/*.js 6.74 KiB
  ./node_modules/vue-style-loader/lib/addStylesClient.js 6.09 KiB [built] [code generated]
  ./node_modules/vue-style-loader/lib/listToStyles.js 671 bytes [built] [code generated]
./node_modules/vue/dist/vue.runtime.esm.js 221 KiB [built] [code generated]
./node_modules/vue-loader/lib/runtime/componentNormalizer.js 2.71 KiB [built] [code generated]
./node_modules/css-loader/dist/runtime/api.js 1.74 KiB [built] [code generated]
webpack 5.22.0 compiled successfully in 1972 ms
```

**Comment by Mikilll94** [comment] 2021-02-16 22:15
@nicolo-ribaudo 
This is not a bug during build time. You need to run the app. Please execute:
```
npm install
npm run dev
```

Go to localhost:8080, open devtools and you will see this bug.

**Comment by nicolo-ribaudo** [comment] 2021-02-16 22:18
@Mikilll94 Adding `sourceType: "unambiguous"` to `babel.config.js` seems to fix the error.

`"umabiguous"` tells Babel to automatically detect if it's transforming a CJS or ESM file, so that it doesn't inject `import` statements in CJS dependencies.

Then there is another error (`process is not defined`), but it seems unrelated.

**Comment by Mikilll94** [comment] 2021-02-16 23:27
@nicolo-ribaudo 
Thanks, I confirm that adding `sourceType: "unambiguous"` fixes the error.

However, I don't have this bug `process is not defined`. Could you check this again?

**Comment by nicolo-ribaudo** [comment] 2021-02-16 23:32
Oh I don't see `process is not defined` anymore, maybe it was something else I changed :thinking: 

Anyway, I'm now going to close this issue since we don't have the webpack config for the OP, so I can just _assume_ that it was the same problem as you had!

**Closed by nicolo-ribaudo** 2021-02-16 23:32 UTC
Labels: i: question

**Comment by wfabio** [comment] 2021-04-14 01:32
Adding `"sourceType": "unambiguous"` to my babel.config.json fixed the issue

 ```
babel.config.json

{
  "sourceType": "unambiguous",
  "plugins": ["@babel/plugin-transform-runtime"],
  "presets": ["@babel/preset-env"]
}
```

Thank you so much!

**Comment by AnRADI** [comment] 2021-04-14 13:51
> @Mikilll94 Adding `sourceType: "unambiguous"` to `babel.config.js` seems to fix the error.
thanks
