### ISSUE TITLE
6.x: "_undefined is not defined" with stage-1 transform and static props on subclass

### ISSUE THREAD

**Issue by mjetek** [babel/babel#2722] opened 2015-11-01 16:53 UTC
I use webpack, react and babel 6.0.14 with the folowing `.babelrc` file
```
{
  "presets": ["stage-1", "es2015", "react"]
}
```
My code transpiles without any errors but on runtime I get an error that either _undefined or Reflect is not defined. The same code with `"presets": ["es2015", "react"]` works.

**Comment by loganfsmyth** [comment] 2015-11-01 17:25
@mjetek Make sure you have the polyfill loaded for `Reflect`. I don't know what do say for `_undefined` though. Can you trim down your code to a sample that reproduces the issue?

**Comment by Stryzhevskyi** [comment] 2015-11-01 18:27
I have the same [issue](https://gist.github.com/Stryzhevskyi/266a8d6d9bd2d97e8827) (`Uncaught ReferenceError: _undefined is not defined` in App.js). Also I can't use `export default class App {/*implementation*/}` , it throws : `Module build failed: Error: pathToProject/src/js/App.js: We don't know what to do with this node type. We were previously a Statement but we can't fit in here?` . This passes without errors: 
```
class App {/*implementation*/}
export default App
```

**Comment by loganfsmyth** [comment] 2015-11-01 19:24
Okay, ignoring the `Reflect` issue, since that's just polyfill issue. I did some checking and the `_undefined is not defined` seems like an issue with the ordering of plugins.

Here's a simple repro case:

Input:
```
class Child extends Parent {
  static staticProp = {};
}
```

with `--plugins transform-class-properties,transform-class-constructor-call`

```
var _super = Parent;

let _Child = class Child extends _super {};

var Child = function (...args) {
  if (this instanceof Child) {
    return Reflect.construct(_Child, args);
  } else {
    return _super.apply(this, args);
  }
};

Child.__proto__ = _Child;
Child.staticProp = {};
```

whereas with `--plugins transform-class-constructor-call,transform-class-properties`

```
var _temp;

var _super = Parent;

let _Child = (_temp = class Child extends _super {}, _undefined.staticProp = {}, _undefined, _temp);

var Child = function (...args) {
  if (this instanceof Child) {
    return Reflect.construct(_Child, args);
  } else {
    return _super.apply(this, args);
  }
};

Child.__proto__ = _Child;
Child;
```

**Comment by dustinwtf** [comment] 2015-11-02 01:14
:+1:  Same issue here

**Comment by dracupid** [comment] 2015-11-02 02:20
Same issue, +1

**Comment by thejameskyle** [comment] 2015-11-02 02:22
Please do not +1 issues, it's not helpful. I've deleted the ones here.

**Comment by hzoo** [comment] 2015-11-06 15:07
Some debugging - `throw new Error("We don't know what to do with this node type. We were previously a Statement but we can't fit in here?");` is [from](https://github.com/babel/babel/blob/0b88a89b87b18bddecbd9f6eae9eaa993e86bf1e/packages/babel-traverse/src/path/modification.js#L125) in `path.insertAfter` which is called [here](https://github.com/babel/babel/blob/5508f4de567ec59b2bc85f371deddd912be138ef/packages/babel-plugin-transform-class-properties/src/index.js#L137). `path.node.type` is `ClassDeclaration` and `path.parentPath.node.type` is `ExportDefaultDeclaration`. Class properties used to be a part of the class transform so maybe there needs to be a special case for static since the result is expected to be something like 

```
"use strict";

var Foo = (function () {
  function Foo() {
    babelHelpers.classCallCheck(this, Foo);
  }

  babelHelpers.createClass(Foo, null, [{
    key: "bar",
    value: "foo",
    enumerable: true
  }]);
  return Foo;
})();
```

for 

```
class Foo {
  static bar = "foo";
}
```

**Comment by thejameskyle** [comment] 2015-11-09 19:26
Closing in favor of https://github.com/babel/babel/issues/2868

**Closed by thejameskyle** 2015-11-09 19:26 UTC
Labels: pending triage
