### ISSUE TITLE
auxiliaryComment not before helper

### ISSUE THREAD

**Issue by stoeffel** [babel/babel#1715] opened 2015-06-09 18:12 UTC
I compiled my module with `--auxiliary-comment=istanbul ignore next` and it added the comment,
but there is `exports.__esModule = true;` after the comment and before the helper.

```js
// istanbul ignore next
"use strict";

exports.__esModule = true;

var _extends = Object.assign || function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; };

```

So istanbul ignores  `exports.__esModule = true;`  but not the helper.

![screen shot 2015-06-09 at 20 05 25](https://cloud.githubusercontent.com/assets/1217681/8065625/e67a922a-0ee2-11e5-82f5-cfe439341f24.png)

Am I doing something wrong or is this a bug? 

refs https://github.com/1-liners/1-liners/pull/105

**Comment by sebmck** [comment] 2015-06-10 00:27
I can't reproduce this. Please provide steps to reproduce.

**Comment by sebmck** [comment] 2015-06-10 00:29
Figured it out. You're passing compiled Babel code through Babel again (evidenced by the extremely weird formatting of that code). Closing this as it's not a Babel issue and resides in your config/setup.

**Closed by sebmck** 2015-06-10 00:29 UTC

**Comment by stoeffel** [comment] 2015-06-10 04:18
Thanks a lot for your help. So the problem must be with babel-plugin-object-assign. Because I just ran  
`cd ./module; babel --loose=all ./*.js --out-dir ../` (`npm run compile`) and the code looked like this.

**Comment by stoeffel** [comment] 2015-06-10 05:24
I will just move to `babel-runtime` instead of `babel-plugin-object-assign`. Thanks again for your help.
