### ISSUE TITLE
private property lost context in `Promise.finally()` when using arrow function

### ISSUE THREAD

**Issue by piranna** [babel/babel#9970] opened 2019-05-13 10:05 UTC
## Bug Report

**Current Behavior**
I'm setting an arrow function as resolver of a `Promise.finally()`. This arrow function is setting to `false` a private attribute in my class to indicate the Promise has finally (by instance, the private attribute host the Promise itself, I use it as a flag to know if the promised operation is running).

After transpiling with Babel, I get an error about "setting a private attribute of a not object instance". Reviewing the transpiled code, it has converted the arrow function in a regular function, loosing the `this` context and using global one instead, throwing that error.

**Input Code**

This is a reduced version of my failing code, it checks if the private attribute has a value set (the `Promise` object) and if so use it, if not create a new one. This way, all calls to `Sample.connect()` method will return and wait for the same `Promise` object if a connection is currently being stablished.

```js
class Sample
{
  #connecting

  connect()
  {
    if(this.#connecting) return this.#connecting

    this.#connecting = ConnectWithPromise()
      .then(console.log, this.emit.bind(this, 'error'))
      .finally(() => this.#connecting = false)

    return this.#connecting
  }
}
```

**Expected behavior/code**
The output code should be like this, it's said, maintain the arrow function:

```js
  connect()
  {
    const connecting = _classPrivateFieldGet(this, _connecting);

    if (connecting) return connecting;

    _classPrivateFieldSet(this, _connecting, ConnectWithPromise().then(console.log, this.emit.bind(this, 'error')).finally(() => {
      _classPrivateFieldSet(this, _connecting, false);
    }));

    return _classPrivateFieldGet(this, _connecting);
  }
```

but instead, it gets converted to use a regular function, like this:

```js
  connect()
  {
    const connecting = _classPrivateFieldGet(this, _connecting);

    if (connecting) return connecting;

    _classPrivateFieldSet(this, _connecting, ConnectWithPromise().then(console.log, this.emit.bind(this, 'error')).finally(function() {
      _classPrivateFieldSet(this, _connecting, false);
    }));

    return _classPrivateFieldGet(this, _connecting);
  }
```

**Babel Configuration (.babelrc, package.json, cli command)**

```js
module.exports = {
  plugins: [
    '@babel/plugin-transform-flow-strip-types',
    '@babel/plugin-proposal-class-properties',
    '@babel/plugin-proposal-optional-chaining',
    '@babel/plugin-proposal-private-methods'
  ],
  presets: [
    'module:metro-react-native-babel-preset',
    'module:react-native-dotenv'
  ]
}
```
```json
{
  "name": "testRN",
  "version": "2.0.0-0",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "android:clean": "cd android && ./gradlew clean",
    "android:dev_menu": "adb shell input keyevent KEYCODE_MENU",
    "android:emulator": "scripts/android:emulator.js",
    "android:log": "react-native log-android",
    "android:release": "cd android && ./gradlew assembleRelease",
    "android:release:test": "npm run android -- --variant=release",
    "docs:api": "jsdoc2md --files **/*.js --global-index-format none > docs/api.md",
    "docs:build": "gitbook build",
    "docs:clean": "rimraf _book",
    "docs:serve": "gitbook serve",
    "install": "gitbook install",
    "ios": "react-native run-ios",
    "ios:release": "react-native bundle --platform=ios",
    "kill_server": "fuser -k 8081/tcp || true",
    "lint": "eslint .",
    "postdocs:api": "git add docs/api.md",
    "predocs:api": "mkdir -p docs",
    "predocs:build": "npm run docs:api",
    "predocs:serve": "npm run docs:api",
    "preandroid": "scripts/preandroid.sh",
    "preandroid:release:test": "npm run android:release",
    "prestart": "npm run kill_server",
    "pretest": "npm run lint",
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "true"
  },
  "dependencies": {
    "@lingbe/client-core": "github:lingbeapp/client-core",
    "@lingbe/react-native-base-components": "github:lingbeapp/react-native-base-components",
    "@redux-offline/redux-offline": "^2.5.1",
    "es6-symbol": "^3.1.1",
    "i18n-js": "^3.2.1",
    "max-timeout": "^1.0.0",
    "moment": "^2.24.0",
    "node-libs-react-native": "^1.0.3",
    "react": "16.8.6",
    "react-native": "^0.59.8",
    "react-native-animatable": "^1.3.2",
    "react-native-check-box": "^2.1.7",
    "react-native-date-picker": "^2.3.0",
    "react-native-device-info": "^1.4.3",
    "react-native-dotenv": "^0.2.0",
    "react-native-gesture-handler": "^1.1.0",
    "react-native-gifted-chat": "^0.7.3",
    "react-native-keyboard-aware-scroll-view": "^0.8.0",
    "react-native-parsed-text": "^0.0.21",
    "react-native-responsive-ui": "^1.1.1",
    "react-native-safe-area": "^0.5.0",
    "react-native-splash-screen": "^3.2.0",
    "react-native-vector-icons": "^6.4.2",
    "react-native-webrtc": "^1.69.1",
    "react-navigation": "^3.8.1",
    "react-redux": "^6.0.1",
    "redux": "^4.0.1",
    "socket.io-client": "^2.0.4",
    "vm-browserify": "^1.1.0"
  },
  "devDependencies": {
    "@babel/core": "^7.4.4",
    "@babel/plugin-proposal-class-properties": "^7.4.4",
    "@babel/plugin-proposal-optional-chaining": "^7.2.0",
    "@babel/plugin-proposal-private-methods": "^7.4.4",
    "@babel/plugin-transform-flow-strip-types": "^7.4.4",
    "@babel/preset-env": "^7.4.4",
    "babel-eslint": "^11.0.0-beta.0",
    "babel-jest": "24.7.1",
    "eslint": "^5.16.0",
    "eslint-config-standard": "^12.0.0",
    "eslint-plugin-extra-rules": "^0.8.1",
    "eslint-plugin-import": "^2.17.2",
    "eslint-plugin-jest": "^22.5.1",
    "eslint-plugin-jsdoc": "^4.8.3",
    "eslint-plugin-json": "^1.4.0",
    "eslint-plugin-jsx-a11y": "^6.2.1",
    "eslint-plugin-node": "^8.0.1",
    "eslint-plugin-promise": "^4.1.1",
    "eslint-plugin-react": "^7.12.4",
    "eslint-plugin-sort-keys-fix": "^1.0.1",
    "eslint-plugin-standard": "^4.0.0",
    "gitbook-cli": "^2.3.2",
    "husky": "^2.1.0",
    "jest-cli": "24.7.1",
    "jsdoc-to-markdown": "^4.0.1",
    "metro-react-native-babel-preset": "0.53.1",
    "react-test-renderer": "16.8.6"
  },
  "husky": {
    "hooks": {
      "pre-commit": "npm test && npm run docs:api",
      "pre-push": "npm test"
    }
  },
  "jest": {
    "collectCoverageFrom": [
      "src/**/*.js"
    ],
    "preset": "react-native",
    "transformIgnorePatterns": [
      "node_modules/(?!(@expo/react-native-action-sheet|react-native|react-native-check-box|react-native-communications|react-native-device-info|react-native-gifted-chat|react-native-gesture-handler|react-native-iphone-x-helper|react-native-keyboard-aware-scroll-view|react-native-lightbox|react-native-parsed-text|react-native-responsive-ui|react-native-screens|react-native-video|react-navigation-stack)/)"
    ]
  },
  "rnpm": {
    "assets": [
      "./assets/fonts/"
    ]
  }
}
```
```sh
npm start -- --reset-cache
```

**Environment**
- Babel version(s): 7.4.4
- Node/npm version: Node 12.2.0 / npm 6.9.0
- OS: Ubuntu 19.04
- Monorepo: no
- How you are using Babel: React Native CLI

**Possible Solution**
I changed by hand the regular function for an arrow function in the generated code, and it worked flawlessly.

**Comment by nicolo-ribaudo** [comment] 2019-05-13 19:44
Can you create a repository which reproduces the issue (possibly using only Babel)? I can't reproduce it using the repl: https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAEDKYFsAOICmAoA3u60DEwA9gHbGrAAuAlsQObo7RGnkUAUAlI9rrlQGZsKACyoQAdARJlKNWh2gAnVBQCui4tBFjJzGdToNeW0RKktZdaAF5oAYWmsA6lREAFRYQRjUnRsfERVGI2ZghCNHEQQloAGhMdVG8KcQAjGgATIVN4gHJURU9FXI4uY1xxfhowEBAATzZOGwA-BLM9VjkbaH4aiFQufyUVdU1tdsdLelwAX3Q5oA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Cstage-2%2Ctypescript&prettier=false&targets=&version=7.4.4&externalPlugins=

**Comment by nicolo-ribaudo** [comment] 2019-06-30 17:50
I'm closing this issue since the requested information has not been provided.

**Closed by nicolo-ribaudo** 2019-06-30 17:50 UTC
Labels: awaiting reply, i: bug
