### ISSUE TITLE
babel 7 can not bind(this) in constructor.

### ISSUE THREAD

**Issue by km-tr** [babel/babel#8593] opened 2018-08-31 08:36 UTC
It worked on babel 6.
It occurred in React Component on babel 7.

Here is an example.

```js
// browser error: Uncaught TypeError: Cannot read property 'bind' of undefined

export default class App extends React.Component {
  constructor(props: Props) {
    super(props);
    console.log(this); // App class Object
    console.log(this.onChange); // undefined (Property exists)
    this.onChange = this.onChange.bind(this);
  }

  onChange() {}
}
```

**Comment by nicolo-ribaudo** [comment] 2018-08-31 13:32
Where is `onChange` defined?

**Comment by km-tr** [comment] 2018-08-31 23:54
@nicolo-ribaudo
We modified the example.
It is defined after the constructor.

**Comment by jridgewell** [comment] 2018-09-01 04:46
Using `eslint-plugin-flowtype`? I'm guessing you're running into https://github.com/babel/babel/issues/8583. Do https://github.com/babel/babel/issues/8583#issuecomment-417718399.

**Comment by ckshekhar** [comment] 2018-09-10 10:16
It seems to problem with `@babel/preset-flow` is not able to remove flow type annotations.
There is a workaround add `@babel/plugin-transform-flow-strip-types` before `@babel/plugin-proposal-class-properties` in plugins.
```
plugins: [
  "@babel/plugin-transform-runtime",
  "@babel/plugin-transform-flow-strip-types",
  "@babel/plugin-proposal-class-properties",
  "@babel/plugin-proposal-object-rest-spread"
]
```

**Comment by italoj** [comment] 2018-10-24 16:56
Someone have a fix for this?

**Comment by Ctaque** [comment] 2018-10-28 08:28
I'm having the same issue without flow typing.
Here is my  [package.json](https://hastebin.com/piwijehaha.json)

**Comment by nicolo-ribaudo** [comment] 2018-10-28 19:49
As a workaround, you can wrap your type annotations in flow comments:
```js
class A {
  /*: onChange: () => void */

  constructor () {
    this.onChange = this.onChange.bind(this);
  }
}
```

**Comment by km-tr** [comment] 2019-02-04 06:05
Is it better to close it?

**Comment by nicolo-ribaudo** [comment] 2019-03-26 23:31
Closing as a duplicate of https://github.com/babel/babel/issues/8417

**Closed by nicolo-ribaudo** 2019-03-26 23:31 UTC
