### ISSUE TITLE
Import from module that exports an object

### ISSUE THREAD

**Issue by jleplomet** [babel/babel#2762] opened 2015-11-02 22:04 UTC
Hello

I am a problem with Babel 6.0.17 and importing modules. My files:

js/actions/constantsActions
```
export function updateConstants {...}
```

js/actions/index.js
```
import * as constantsActions from './constantsActions';

export default {
  ...constantsActions
};
```

js/main.js
```
import {constantsUpdate} from './actions';

constantsUpdate() // function constantsUpdate is undefined
```

The problem is in main.js with the expected function constantsUpdate being undefined. This code was working with Babel 5. Is there a plugin I am missing or could this be a bug? 

.babelrc
```
{
  "presets": [
    "es2015",
    "stage-0",
    "react"
  ],
  "plugins": [
    "transform-object-rest-spread"
  ]
}
```

**Comment by loganfsmyth** [comment] 2015-11-02 22:08
Duplicate of https://github.com/babel/babel/issues/2724.

This is not valid ES6 and while it did work in Babel 5, it no longer works in Babel 6.

For your example, you should just be doing

    export * from './constantsActions';

**Closed by loganfsmyth** 2015-11-02 22:08 UTC

**Comment by jleplomet** [comment] 2015-11-02 22:54
Makes sense. Although, I am getting an error with your suggestion:

```
Invariant Violation: To get a node path the parent needs to exist while parsing file: ...
```

**Comment by loganfsmyth** [comment] 2015-11-03 03:10
@jleplomet yeah, looks like there's an issue with ExportAll https://github.com/babel/babel/issues/2763

**Comment by jazlalli** [comment] 2015-11-13 15:49
Hi
Sorry to tack onto a closed issue, but I'm experiencing the same problem here, without the invalid ES6 mentioned by @loganfsmyth (https://github.com/babel/babel/issues/2762#issuecomment-153172898).

```js
// file1.js
var queries = {
  f1: function () {},
  f2: function () {}
};
export default queries;

// file2.js
import {f2} from './file1';
console.log(f2); // f2 is 'undefined'
```

This has stopped working since upgrading to Babel 6, and I'm using the es2015 preset.

Is the code above valid? From my understanding of modules and spread, I would expect that to work. Any thoughts? Happy to open a new issue if needed/preferred.

**Comment by jmm** [comment] 2015-11-13 15:56
@jazlalli That's invalid. You're exporting only a `default` and trying to import a binding named `f2` -- there's no exported binding named `f2`. That's exactly why the change (see #2212) was made. Also, there's no spread here.

**Comment by jazlalli** [comment] 2015-11-13 16:00
@jmm OK, thanks. Turns out I've been doing it wrong then.

I'll go back and re-learn wtf I'm doing. Thanks. :confused:
