### ISSUE TITLE
arrow function as decorator argument breaks decorator initialization

### ISSUE THREAD

**Issue by deepsweet** [babel/babel#2088] opened 2015-07-27 05:36 UTC
https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&playground=false&code=%40test(()%20%3D%3E%20123)%0Aclass%20A%20%7B%7D%0A%0A%40test(()%20%3D%3E%20%7B%20return%20123%20%7D)%0Aclass%20B%20%7B%7D%0A%0A%40test(function()%20%7B%20return%20123%20%7D)%0Aclass%20%D0%A1%20%7B%7D

**Comment by sebmck** [comment] 2015-07-27 05:37
Duplicate of #2086.

**Closed by sebmck** 2015-07-27 05:37 UTC

**Comment by deepsweet** [comment] 2015-07-27 05:38
oops, thanks! waiting for a new patch version :)
