### ISSUE TITLE
TypeError: Cannot read property 'buildError' of undefined

### ISSUE THREAD

**Issue by yiye** [babel/babel#8689] opened 2018-09-12 02:50 UTC
## Bug Report

**Current Behavior**
A clear and concise description of the behavior.
![image](https://user-images.githubusercontent.com/3963651/45399034-3584e500-b679-11e8-9b39-74505e92b71e.png)

**Input Code**
- REPL or Repo link if applicable:

```bash
TypeError: Cannot read property 'buildError' of undefined
    at Scope.checkBlockScopedCollisions (/Users/puss/work/ioc/parrot-tool-must/node_modules/_@babel_traverse@7.0.0@@babel/traverse/lib/scope/index.js:347:22)
    at Scope.registerBinding (/Users/puss/work/ioc/parrot-tool-must/node_modules/_@babel_traverse@7.0.0@@babel/traverse/lib/scope/index.js:504:16)
    at Scope.registerDeclaration (/Users/puss/work/ioc/parrot-tool-must/node_modules/_@babel_traverse@7.0.0@@babel/traverse/lib/scope/index.js:452:14)
    at Object.Declaration (/Users/puss/work/ioc/parrot-tool-must/node_modules/_@babel_traverse@7.0.0@@babel/traverse/lib/scope/index.js:125:12)
    at NodePath._call (/Users/puss/work/ioc/parrot-tool-must/node_modules/_@babel_traverse@7.0.0@@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/puss/work/ioc/parrot-tool-must/node_modules/_@babel_traverse@7.0.0@@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/puss/work/ioc/parrot-tool-must/node_modules/_@babel_traverse@7.0.0@@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/Users/puss/work/ioc/parrot-tool-must/node_modules/_@babel_traverse@7.0.0@@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitMultiple (/Users/puss/work/ioc/parrot-tool-must/node_modules/_@babel_traverse@7.0.0@@babel/traverse/lib/context.js:85:17)
    at TraversalContext.visit (/Users/puss/work/ioc/parrot-tool-must/node_modules/_@babel_traverse@7.0.0@@babel/traverse/lib/context.js:144:19)

```

**Environment**
- Babel version(s): [v7.0.0]
- Node/npm version: [Node v10.9.0/npm 5.15.0]
- OS: [e.g. OSX 10.13.6]
- Monorepo [e.g. yes/no/Lerna]
- How you are using Babel: [`AST parser`]
.

**Comment by loganfsmyth** [comment] 2018-09-12 02:54
This may be a duplicate, but it's hard to tell without a full reproduction example. What config and input source are you using to produce this error? How are you calling Babel? It would be great if you could provide a repository that reproduces the error.

**Comment by chrisregnier** [comment] 2018-09-15 17:42
I'm getting the same thing where hub isn't defined.
Here's the rough outline of what I'm doing.
```javascript
let code = `
  function foo(v) {
    let v = 8
  }
`;
let ast = parse(code, {
  sourceType: 'module',
  sourceFilename: 'failingTest',
  ranges: true,
  plugins: [
    'jsx',
    'flow',
    'classProperties',
    'objectRestSpread'
  ]
})
traverse(ast, {
  Program(path) {
    console.log('here')
  }
}, null, { stateData: {} });
```

**Comment by chrisregnier** [comment] 2018-09-15 17:45
ya this looks like a duplicate of #8262 , although I don't t think it needs to be typescript.

**Comment by loganfsmyth** [comment] 2018-09-15 18:45
Cool, this is actually a duplicate of #8617. That other one is triggering the same broken code, but that other one isn't supposed to trigger an error in the first place.

**Closed by loganfsmyth** 2018-09-15 18:45 UTC

**Comment by chrisregnier** [comment] 2018-09-15 19:29
ya I believe they all have the same cause. Looks like hub isn't initialized in our case in the root path so when context.create tries to grab it recursively from the parentPath, nothing's there. I've gotten the error here and the one in 8262 for the same reason, but with slightly different test code.

**Comment by loganfsmyth** [comment] 2018-09-15 20:01
Yup, I mostly clarify because for #8262 it is different because it actually shouldn't be a "Duplicate declaration" in the first place.
