### ISSUE TITLE
`babel-plugin-transform-runtime` requires `babel-runtime` 5.0.0, but imports 6.1.4's files

### ISSUE THREAD

**Issue by jamesknelson** [babel/babel#3001] opened 2015-11-12 04:18 UTC
If I install `babel-plugin-transform-runtime` into a new project, NPM will install `babel-runtime` 5.x. This makes sense, as basically everything else uses a 5.x `babel-runtime` too.

The problem is that it requires methods based on the 6.1.4 filenames, rendering it basically useless.

This produces errors like this when I try to run Webpack on the resultant files:

```
Module not found: Error: Cannot resolve module 'babel-runtime/helpers/defineProperty'
Module not found: Error: Cannot resolve module 'babel-runtime/helpers/slicedToArray'
Module not found: Error: Cannot resolve module 'babel-runtime/helpers/objectWithoutProperties'
```

These errors only occur when running `babel-plugin-transform-runtime`. I've tried it on 6.1.4, 6.1.2 and 6.0.2. I've also tried downgrading the versions of various other packages to 6.1.2 and 6.0.2. I've also removed `node_modules` and done a complete `npm install` on each of these steps.

**Comment by jamesknelson** [comment] 2015-11-12 04:47
A little more playing around has narrowed the cause of this down to upgrading from `babel-runtime` 6.0.14 to 6.1.4.

You can see the bug in action in this repo: https://github.com/unicorn-standard/starter-kit/tree/babel-upgrade

**Comment by sebmck** [comment] 2015-11-12 05:03
Moreorless a duplicate of #2989 which I fixed with the commit attached to it.

**Closed by sebmck** 2015-11-12 05:03 UTC
