### ISSUE TITLE
[bug] Unable to destructure object with rest operator 

### ISSUE THREAD

**Issue by andykras** [babel/babel#7730] opened 2018-04-14 12:12 UTC
### Input Code
```js
const user = { name: 'Max', password: '123', _id: 1, __v: 42 }
const fields = ['__v', 'password']
const filtered = fields.reduce((a, c) => (({ [c]: _, ...rest } = a), rest), user)
```
this code compiled and works as expected on **node**, but fails on **babel**

### Babel/Babylon Configuration (.babelrc, package.json, cli command)
Using babel 6.26.0
```js
package.json
...
  "devDependencies": {
    "babel": "^6.23.0",
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.0",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-preset-env": "^1.6.1"
  }
```

### Expected Behavior
Get filtered user without `__v` and `password` fields

### Current Behavior
Cannot compile code. Output log:
```sh
$ babel --plugins transform-object-rest-spread src/index.js
babel-preset-env: `DEBUG` option

Using targets:
{}

Modules transform: commonjs

Using plugins:
  check-es2015-constants {}
  transform-es2015-arrow-functions {}
  transform-es2015-block-scoped-functions {}
  transform-es2015-block-scoping {}
  transform-es2015-classes {}
  transform-es2015-computed-properties {}
  transform-es2015-destructuring {}
  transform-es2015-duplicate-keys {}
  transform-es2015-for-of {}
  transform-es2015-function-name {}
  transform-es2015-literals {}
  transform-es2015-object-super {}
  transform-es2015-parameters {}
  transform-es2015-shorthand-properties {}
  transform-es2015-spread {}
  transform-es2015-sticky-regex {}
  transform-es2015-template-literals {}
  transform-es2015-typeof-symbol {}
  transform-es2015-unicode-regex {}
  transform-regenerator {}
  transform-exponentiation-operator {}
  transform-async-to-generator {}
  syntax-trailing-function-commas {}
TypeError: src/index.js: Property arguments[0] of CallExpression expected node to be of a type ["Expression","SpreadElement"] but instead got undefined
    at validate (node_modules\babel-cli\node_modules\babel-types\lib\definitions\index.js:109:13)
    at validator (node_modules\babel-cli\node_modules\babel-types\lib\definitions\index.js:57:7)
    at Object.validate (node_modules\babel-cli\node_modules\babel-types\lib\definitions\index.js:190:10)
    at validate (node_modules\babel-cli\node_modules\babel-types\lib\index.js:505:9)
    at Object.builder (node_modules\babel-cli\node_modules\babel-types\lib\index.js:466:7)
    at createObjectSpread (C:\Tools\projects\em2\backpack-test\node_modules\babel-plugin-transform-object-rest-spread\lib\index.js:70:38)
    at PluginPass.AssignmentExpression (C:\Tools\projects\em2\backpack-test\node_modules\babel-plugin-transform-object-rest-spread\lib\index.js:186:38)
    at newFn (node_modules\babel-cli\node_modules\babel-traverse\lib\visitors.js:276:21)
    at NodePath._call (node_modules\babel-cli\node_modules\babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (node_modules\babel-cli\node_modules\babel-traverse\lib\path\context.js:48:17)
```

### Possible Solution
rewrite filtered like this
```js
const filtered = fields.reduce((a, c) => {
  const { [c]: _, ...rest } = a
  return rest
}, user)
```

### Context
I was trying to do code in one line like this
```js
(a, c) => (({ [c]: _, ...rest } = a), rest)
```
instead of this:
```js
(a, c) => {
  const { [c]: _, ...rest } = a
  return rest
}
```
### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.26.0 (babel-core 6.26.0)
| node             | v9.11.1
| npm              | 5.6.0
| Operating System | Win10

**Comment by caub** [comment] 2018-04-14 17:34
```js
let _, rest;
const filtered = fields.reduce((a, c) => ({ [c]: _, ...rest } = a, rest), user);
```
would be slighly better (else _ and rest are never declared), but still fails it seems

```js
const filtered = fields.reduce((a, c) => {
  const { [c]: _, ...rest } = a;
  return rest
}, user);
```
works for now, but good issue

**Comment by andykras** [comment] 2018-04-14 18:55
also please note that code
```js
const just_fun = p => ({ foo: 'bar' }, { bar: 'baz' })
console.log(just_fun())
```
compiles successfully into
```js
'use strict';

var just_fun = function just_fun(p) {
  return { foo: 'bar' }, { bar: 'baz' };
};
console.log(just_fun());
```
and results in output
```js
{ bar: 'baz' }
```

**Comment by mkarajohn** [comment] 2018-04-23 12:12
I am having a very similar issue, with the difference that Babel doesn't crash in my case.

### Input Code
`const { [id]: obsolete, ...rest } = state` 
where `state` is a dictionary of id-value pairs.

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```
"devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.0",
    "babel-eslint": "^8.0.1",
    "babel-loader": "^7.1.2",
    "babel-plugin-react-css-modules": "^3.3.1",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-plugin-transform-react-inline-elements": "^6.22.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-register": "^6.26.0"
}
```

### Expected Behavior

After the above operation is run, if my initial `state` was something like `{1: <value>, 2: <value>}` and the `id === 1` we would expect that `rest` should be `{2: <value>}`

### Current Behavior

`obsolete` is set correctly, however `rest` still includes the id-value pair of `obsolete`. Meaning, if my initial `state` was something like `{1: <value>, 2: <value>}` and the `id === 1` , `rest` is  `{1: <value>, 2: <value>}`

**Comment by hzoo** [comment] 2018-04-23 12:25
Ok I'm closing since this is fixed in v7. If you aren't willing to use v7 yet that's reasonable, although I will say that people are using it in production already (my old company, Adobe and it's in CRA/wordpress/next.js now). We should probably track it haha.

**Closed by hzoo** 2018-04-23 12:25 UTC
