### ISSUE TITLE
Comment parsing is not deterministic

### ISSUE THREAD

**Issue by matthewrobertson** [babel/babel#9165] opened 2018-12-11 19:22 UTC
## Bug Report

**Current Behavior**
Comment nodes get attached to arbitrary AST nodes. Parsing is not consistent when a comment could be parsed as leading or trailing (IMO we should default to leading comment). In the worst case, a single comment will appear multiple times in the AST.

**Input Code**
https://astexplorer.net/#/gist/16b95c55446b6e7c2c7d0e1f6e9415ae/af378da42bb1bafd344f1b87251f2259eb7796b1

**Expected behavior/code**
- Every comment should get exactly one AST node. 
- Leading vs trailing parsing should be consistent between statements and object properties.

**Environment**
- @babel/parser@7.1.3
- Node 10.13.0/npm 6.4.1
- repros on windows and mac

**Possible Solution**
Always default to leading comments

**Additional Context**

From linked AST explorer example, a single comment appears twice in the AST:

<img width="871" alt="comment parsing" src="https://user-images.githubusercontent.com/644493/49824449-f416db00-fd36-11e8-929d-d143766306d0.PNG">

**Comment by danez** [comment] 2018-12-12 19:30
Thanks for reporting. This is already on our list and we even had a PR already (#9084), but haven't landed anything yet.

**Comment by JLHwung** [comment] 2022-09-28 19:20
I cannot reproduce this issue in Babel 7.19. It is probably fixed in https://github.com/babel/babel/pull/13521.

**Closed by JLHwung** 2022-09-28 19:20 UTC
Labels: i: bug, pkg: parser, area: comments
