### ISSUE TITLE
Importing and re-exporting TypeScript enum causes undefined export in v7.0.0-beta.32 loose mode.

### ISSUE THREAD

**Issue by phyllisstein** [babel/babel#6817] opened 2017-11-13 17:42 UTC
### Choose one: is this a bug report or feature request?
Bug report.

### Summary
When attempting to import and re-export a TypeScript `enum` with `@babel/preset-env` in loose mode, Babel generates code with an undefined export that throws a `TypeError` at runtime. This issue appeared after upgrading `@babel/preset-env` from `v7.0.0-beta.31` to `v7.0.0-beta.32`.

Some sample code is below, but see <https://github.com/phyllisstein/babel-env-loose-mwe> for a complete MWE.

### Input Code

```ts
// src/some-enum/index.ts

export enum SomeEnum {
  MY_NAME = 'MY_NAME',
  YOUR_NAME = 'YOUR_NAME',
}
```

```ts
// src/enums.ts

import { SomeEnum } from './some-enum'

export { SomeEnum }
```

```ts
// src/index.ts

import { SomeEnum } from './enums'

const payload = { name: 'phyllisstein', type: SomeEnum.MY_NAME }

console.log(`You did the thing, ${ payload.name }!`)
```

<details>
<summary>v7.0.0-beta.31 Emitted JS</summary>

```js
// lib/enums.js

"use strict";

exports.__esModule = true;
Object.defineProperty(exports, "SomeEnum", {
  enumerable: true,
  get: function () {
    return _someEnum.SomeEnum;
  }
});

var _someEnum = require("./some-enum");
```
</details>

<details>
<summary>v7.0.0-beta.32 Emitted JS</summary>

```js
// lib/enums.js

"use strict";

exports.__esModule = true;
exports.SomeEnum = _someEnum.SomeEnum;

var _someEnum = require("./some-enum");
```
</details>

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```json
{
  "presets": [
    ["@babel/env", {
      "targets": {
        "node": "current"
      },
      "loose": true
    }],
    "@babel/typescript"
  ]
}
```

### Expected Behavior
I should be able to import the enum and run the code transpiled from `src/index.ts` successfully.

### Current Behavior
Babel emits code that throws a `TypeError` at runtime:

<details>
<summary>:boom:</summary>

```
TypeError: Cannot read property 'SomeEnum' of undefined
    at Object.<anonymous> (/Users/daniel/Repos/Personal/babel-env-loose-mwe/lib/enums.js:4:30)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/daniel/Repos/Personal/babel-env-loose-mwe/lib/index.js:3:14)
    at Module._compile (module.js:635:30)
```
</details>

### Possible Solution
![](http://phyl.li/dunno.gif)

### Context
We use TypeScript's enums as action creator `type`s in our React/Redux code. I noticed the issue when attempting to import the enum into a test module and make assertions with it.

### Your Environment
| software         | version(s)
| ---------------- | -------
| Babel            |  v7.0.0-beta.32
| Babylon          | N/A
| node             | v8.9.1
| npm              | v5.5.1
| Operating System | macOS 10.13.2 (17C67b)

**Comment by hzoo** [comment] 2017-11-13 17:49
Hey I reported this already at https://github.com/babel/babel/issues/6805 (unrelated to typescript just a generic export issue) I believe?

**Comment by hzoo** [comment] 2017-11-13 17:50
Duplicate of https://github.com/babel/babel/issues/6805

**Closed** 2017-11-13 17:50 UTC
Labels: i: bug, i: duplicate

**Comment by phyllisstein** [comment] 2017-11-13 17:52
Ack! Thanks for pointing me in the right direction, I _thought_ those looked suspiciously similar 😬. Love that "Good First Issue" tag, maybe I'll take a crack.

**Comment by hzoo** [comment] 2017-11-13 17:53
Please do! Looks like someone is giving it a shot but feel free to work on it and compare with another PR if you want to get involved (and/or join slack)
