### ISSUE TITLE
Invalid output on async + destructuring parameter / arguments

### ISSUE THREAD

**Issue by bottleofwater** [babel/babel#1146] opened 2015-04-03 13:48 UTC
Hi,

[(demo)](https://babeljs.io/repl/#?experimental=true&evaluate=false&loose=false&spec=false&code=async%20function%20test(%20%7B%20a%20%7D%20%3D%20%7B%20%7D%20)%20%7B%0A%20%20alert(%20a%20)%3B%0A%20%20alert(%20arguments%20)%3B%0A%7D%0A%0Atest(%20%7B%20a%20%3A%2010%20%7D%20)%3B%0A)

```js
async function test( { a } = { } ) {
  alert( a );
  alert( arguments );
}

test( { a : 10 } );
```

Babel will alert undefined, because the destructuring parameters are evaluated inside the regenerator wrapper, which doesn't preserve the `arguments` variable. Actually, any use of `arguments` inside the body of an async function will fail.

**Comment by sebmck** [comment] 2015-04-03 13:49
Duplicate of #1016.

**Closed by sebmck** 2015-04-03 13:49 UTC

**Comment by bottleofwater** [comment] 2015-04-03 13:52
Yeah, I was browsing the issues and just saw it. Sorry.

**Comment by sebmck** [comment] 2015-04-03 13:53
All good :smile: Better to be safe than sorry.
