### ISSUE TITLE
babel-node cannot transpile code outside its own directory

### ISSUE THREAD

**Issue by renatonmendes** [babel/babel#7566] opened 2018-03-14 12:49 UTC
I´m trying to build a server code with some shared code between projects.

My current directory structure:

```
|- server
|    |-- package.json
|    |-- server.js, another stuff.js
|
|- common
    |-- schema
             |-- index.js

```

My common/schema/index.js:

```
import { GraphQLSchema } from 'graphql';

import RootQuery from './queries';
import RootMutation from './mutations';
import types from './types'

export default new GraphQLSchema({
	types: types,
	query: RootQuery,
	mutation: RootMutation
});

```
At server.js, I´m calling schemas and receiving the following error:

`$ npm run server`

```
import { GraphQLSchema } from "graphql";
^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at loader (D:\dev\server\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (D:\dev\server\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:/dev/server/routes.js:25:1)
    at Module._compile (module.js:570:32)
    at loader (D:\dev\server\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (D:\dev\server\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

My package.json:
```
{
  "name": "server",
  "version": "1",
  "private": true,
  "scripts": {
    "start": "concurrently \"babel-node start-server\" \"babel-node start-client\"",
    "server": "nodemon --exec \"babel-node start-server.js\"",
    "client": "nodemon --exec \"babel-node start-client.js\"",
    "lint": "eslint ."
  },
  "dependencies": {
    "babel-cli": "^6.24.1",
    "babel-core": "^6.25.0",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-es2016": "^6.24.1",
    "babel-preset-es2017": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "bcryptjs": "^2.4.3",
    "body-parser": "^1.17.2",
    "connect-mongo": "^2.0.0",
    "crypto": "^1.0.1",
    "express": "^4.15.3",
    "express-graphql": "^0.6.12",
    "graphql": "^0.13.1",
    "graphql-relay": "^0.5.4",
    "jwt-simple": "^0.5.1",
    "mongoose": "^5.0.10",
    "morgan": "^1.8.2",
    "nodemailer": "^4.6.0",
    "passport": "^0.4.0",
    "passport-jwt": "^4.0.0",
    "path": "^0.12.7",
    "validator": "^9.1.1"
  },
  "devDependencies": {
    "concurrently": "3.5.1",
    "eslint": "^4.18.2",
    "eslint-config-airbnb": "16.1.0",
    "eslint-plugin-import": "2.9.0",
    "eslint-plugin-jsx-a11y": "6.0.3",
    "eslint-plugin-react": "7.7.0",
    "fs-extra": "^5.0.0",
    "node-fetch": "^2.1.1",
    "nodemon": "^1.11.0"
  },
  "babel": {
    "presets": [
      "es2015",
      "stage-0",
      "es2017"
    ],
    "plugins": [
      "transform-runtime"
    ]
  }
}
```

How to allow babel to transpile code that stays outside its running structure ?

**Comment by alex-shamshurin** [comment] 2018-05-01 14:04
Try to rename `.babelrc` to `babel.config.js` and put it to the root

**Comment by vjpr** [comment] 2018-05-10 07:44
I'm facing the same problem.

I have a monorepo and `babel.config.js` in the monorepo root.

I have a sub-package from which I run a cli tool.

When I run the cli tool from the monorepo root `babel-node /monorepo/cli/index.js`, it uses `babel.config.js`.

But when I run the cli tool from a sub-package (`babel-node ../../monorepo/cli/index.js`), it does not use `babel.config.js`. The old functionality use to search up, but this behavior changed in beta.46.

Is there a way to configure `babel-node` to use a specific `babel.config.js` or search upwards? Or maybe I need to programmatically run `babel-register` with the babelrcRoots config set...

**Comment by SavePointSam** [comment] 2018-07-12 18:03
I'm running into the exact same issue here. No matter what I try babel doesn't find `babel.config.js` in the root despite @loganfsmyth's [message](https://github.com/facebook/jest/issues/6053#issuecomment-383632515) about this functionality. It appears babel is still stopping at the first package.json and not continuing to search up the tree.

There is mention of a `root` config option in the current `next` [babel docs](https://babeljs.io/docs/en/next/babelconfigjs#specifying-the-root-folder), but there is [no reference](https://babeljs.io/docs/en/babel-core#options) to it anywhere else (including the source of babel itself). It appears that the `root` config was designed to help babel know about a monorepo set up. However, babel is currently using this functionality in their monorepo and I cannot find any indication as to why it isn't working for my set up. All other settings have been removed and it refuses to go up the tree to find my new global config.

It would be very nice if there was a way to verify this, but it appears the proposal to add a flag to dump debugging information has [gone stale](https://github.com/babel/babel/pull/4806).

For a bit more detail I have the following structure:

```
root
├── packages
│   ├── node-app
│   │   └── package.json
│   └── library
│       └── package.json
├── babel.config.js
├── lerna.json
└── package.json
```

Inside of `node-app`, I am using nodemon to run my application and use `@babel/node` (it does look like this will be replaced with extended functionality from `@babel/cli` in the future, though that is unclear) to JIT transpile.

`node-app` depends on `library`. While `node-app` was being transpiled when the babel configuration was inside it's local `package.json`, `library` was not (too be expected with babel@7-beta.46) (also, it kind of was, but it didn't load the plugins that were needed).

However, now that I've stripped out the local settings and moved them to the repository root, even the `node-app` isn't transpiled when run. I've event tried throwing an error inside my `babel.config.js` when it's run and I've never seen it thrown.

I'm at a loss as to what to do next to fix this.

**Comment by mxmzb** [comment] 2018-07-12 19:16
you need to add an `--ignore` flag to your `babel-node` command, that whitelists your linked package in your `node_modules`. more on it here: https://github.com/cloverfield-tools/universal-react-boilerplate/issues/41#issuecomment-143053807

**Comment by SavePointSam** [comment] 2018-07-12 22:03
I've learned that the `root directory` mentioned in the opening paragraph of [this document](https://babeljs.io/docs/en/next/babelconfigjs#lookup-behavior) actually means the CWD when the babel command is run, so babel only looks adject to it's processing directory. UNLESS you use the `root` option, though I haven't discovered how that is implemented as there is no documentation other than that it should exist.

I'll be looking into that more after I solve some other issues I'm having and update accordingly.

**Comment by SavePointSam** [comment] 2018-07-12 23:11
My final problem actually came from using the nodemon JS API over the CLI. For some reason the same commands failed.

```js
// fails
nodemon(`./src/index.js --exec "babel-node --ignore '/node_modules/(?!library)'"`);
```
```shell
# succeeds
$ nodemon ./src/index.js --exec "babel-node --ignore '/node_modules/(?!library)'"
```

My next problem comes from having `babel.config.js` in the package root rather than the repository root. I'll be looking into the alleged `root` option soon.

**Comment by SavePointSam** [comment] 2018-07-13 16:19
I've ultimately opted for creating my own babel-preset in my monorepo that defines everything I need. I then have a `babel.config.js` inside the root of all my packages that simply has the following:

```
module.exports = {
  presets: ['module:@SavePointSam/babel-preset'],
};
```

I did notice that putting my `ignore` settings in my `babel.config.js` don't work while putting them as a flag on the `babel-node` CLI does. So, I'd like to fix that as well. However, for my use case aside from some prettier config, I have everything working as needed.

**Comment by SavePointSam** [comment] 2018-07-13 16:55
It turns out that the incompatibilty has to do with how `babel-node` is written. However, it is looked at for deprecation in favor of a more robust `@babel/cli`, so I'm just going to leave the `--ignore` flag on `babel-node` as the functionality in `babel.config.js` doesn't work the same way at the flag.

**Comment by SavePointSam** [comment] 2018-07-13 19:12
To properly close this ticket, the answer to the original question:

```shell
$ babel-node --ignore anyValue ./path/to/entry.js
```

By default, `babel-node` will ignore anything outside the CWD from which it is called. Adding the `--ignore` flag disables this default functionality and the actual value provided to the flag doesn't matter. You can optimize the ignore by providing a pattern to which things you explicitly want ignored so you don't end up compiling literally everything that babel comes into contact with.

I would also like to note that the `ignore` property in the new `babel.config.js` does NOT work in the same way that the flag for `babel-node` works. I cannot elaborate further (outside my knowledge), I just know that they don't accomplish the same thing and are not comparable.

**Closed** 2018-08-12 00:00 UTC
