### ISSUE TITLE
babel-node doesn't recognize/pass on all node flags

### ISSUE THREAD

**Issue by zyklus** [babel/babel#2284] opened 2015-08-30 07:18 UTC
e.g.:

```sh
➜  test  node --allow-natives-syntax
>
(^C again to quit)
>

➜  test  babel-node --allow-natives-syntax

  error: unknown option `--allow-natives-syntax'
```

**Comment by sebmck** [comment] 2015-08-30 13:14
Moreorless a dupe of #2166. It needs to be added to [this](https://github.com/babel/babel/blob/master/packages/babel-cli/src/babel-node.js) file or you need to use the option specified in the [docs](https://babeljs.io/docs/usage/cli/#usage):

```sh
$ babel-node script.js -- --allow-natives-syntax
```

**Closed by sebmck** 2015-08-30 13:14 UTC
