### ISSUE TITLE
@babel/preset-env fails to add the correct es.promise polyfill for Firefox 68 and below

### ISSUE THREAD

**Issue by MaRuifeng** [babel/babel#12029] opened 2020-09-03 02:09 UTC
## Bug Report

JS code using syntax like `Promise.resolve(true).finally(() => console.log('Promise polyfill works'))` fails to execute in Firefox after babel transformation with target `{firefox: '68'}`. 

**Current behavior**

Below error is observed in Firefox's console when trying to execute the input code in a react app's entry index.ts file. It's gone when the target version is set at 69 or higher. 

```
TypeError: Promise.resolve(...).finally is not a function
```

**Input Code**

```js
Promise.resolve(true).finally(() => console.log('Promise polyfill works'));
```

**Expected behavior**
The simple promise finally test code should execute successfully with "Promise polyfill works' output to the browser's console. 

**Babel Configuration via Webpack babel-loader**
- Filename: `webpack.config.js`

```js
  module: {
    rules: [
      {
        test: /\.(jsx?|tsx?)$/,
        exclude: /node_modules\/.*/,
        use: {
          loader: 'babel-loader',
          options: {
            cacheDirectory: true,
            plugins: ['react-hot-loader/babel'],
            presets: [
              '@babel/preset-react',
              '@babel/preset-typescript',
              [
                '@babel/preset-env',
                {
                  targets: {
                    firefox: '68',
                  },
                  useBuiltIns: 'usage',
                  corejs: '3.6',
                  debug: true,
                },
              ],
            ],
          },
        },
      }
    ],
  },
```

**Environment**

```
  System:
    OS: macOS Mojave 10.14.6
  Firefox: 68.8.0esr
  Binaries:
    Node: 10.19.0 - ~/.nvm/versions/node/v10.19.0/bin/node
    npm: 6.14.7 - ~/.nvm/versions/node/v10.19.0/bin/npm
  npmPackages:
    @babel/cli: ^7.8.4 => 7.8.4
    @babel/core: ^7.9.0 => 7.9.0
    @babel/plugin-proposal-class-properties: ^7.8.3 => 7.8.3
    @babel/plugin-proposal-object-rest-spread: ^7.9.5 => 7.9.5
    @babel/plugin-syntax-dynamic-import: ^7.8.3 => 7.8.3
    @babel/plugin-transform-runtime: ^7.9.0 => 7.9.0
    @babel/preset-env: ^7.9.5 => 7.9.5
    @babel/preset-react: ^7.9.4 => 7.9.4
    @babel/preset-typescript: ^7.9.0 => 7.9.0
    @babel/register: ^7.9.0 => 7.9.0
    @babel/runtime: ^7.9.2 => 7.9.2
    babel-eslint: ^10.0.3 => 10.0.3
    babel-jest: ^24.5.0 => 24.9.0
    babel-loader: ^8.0.5 => 8.0.6
    eslint: ^6.3.0 => 6.6.0
    jest: ^25.0.0 => 25.1.0
    webpack: ^4.29.6 => 4.41.0

```

**Possible Solution**
For now my workaround is: 

1. Config `@babel/preset-env` to purposely exclude `es.promise` polyfill. 

```
exclude: ['es.promise'],
```
2. Add it through Webpack's entrypoint config since it's still needed. 

```
entry: ['core-js/es/promise', 'index.ts'],
```

**Additional context**
I am not sure whether this is indeed a bug. Posted it here for more advice. The original problem is documented at https://stackoverflow.com/questions/63683074/promise-polyfill-does-not-work-in-firefox-and-ie11-when-added-via-webpack-babel.

**Comment by nicolo-ribaudo** [comment] 2021-01-30 14:02
Closing, since we cannot reproduce this bug.

**Closed by nicolo-ribaudo** 2021-01-30 14:02 UTC
Labels: i: bug, i: needs reproduction

**Comment by lk77** [comment] 2021-03-22 11:26
Hello,

any news on this ? 

excluding es.promise did the trick
