### ISSUE TITLE
shasum check failed for preset-env-7.8.4.tgz

### ISSUE THREAD

**Issue by derMart** [babel/babel#11153] opened 2020-02-18 08:10 UTC
running
`npm install --save babel-loader @babel/core @babel/preset-env`
gives the following error:
```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Martin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "babel-loader" "@babel/core" "@babel/preset-env"
npm ERR! node v10.0.0
npm ERR! npm  v3.9.5

npm ERR! shasum check failed for C:\Users\Martin\AppData\Local\Temp\npm-7220-32b6c023\registry.npmjs.org\_40babel\preset-env\-\preset-env-7.8.4.tgz
npm ERR! Expected: 9dac6df5f423015d3d49b6e9e5fa3413e4a72c4e
npm ERR! Actual:   72c9f2f0e7f8d30ca282aa98c7577c69f004c6f6
npm ERR! From:     https://registry.npmjs.org/@babel/preset-env/-/preset-env-7.8.4.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Projekte\trovent-vulscan\npm-debug.log
```

see also https://github.com/npm/cli/issues/802 which includes npm-debug.log

kind regards

**Comment by nicolo-ribaudo** [comment] 2020-02-18 09:52
This is definitely not a big with Babel.
Try cleaning your cache, or if you are using a proxy between you and npm it's cache.

**Comment by JLHwung** [comment] 2020-02-23 02:38
Closing this since it is not reproducible.

**Closed by JLHwung** 2020-02-23 02:38 UTC
Labels: i: npm cache, i: question
