### ISSUE TITLE
Require hook fails inexplicably on Node v0.10.x on Linux

### ISSUE THREAD

**Issue by dallonf** [babel/babel#1588] opened 2015-05-20 21:17 UTC
Fair warning: I don't have a good simple repro for this. I'll provide all the details I can...

So we have a server-side app using Babel's Require hook (`require('babel/register')({sourceMaps: 'inline'});`). When deployed to a server running Ubuntu 14.04.1 LTS and Node v0.10.33, it seems to compile something invalid, throwing errors like this:

```
TypeError: /my-app/lib/some-file.js: Cannot read property '_module' of undefined
    at Scope.hasBinding (/my-app/node_modules/babel/node_modules/babel-core/lib/babel/traversal/scope.js:851:23)
    at Scope.generateUid (/my-app/node_modules/babel/node_modules/babel-core/lib/babel/traversal/scope.js:285:19)
    at Scope.generateUidIdentifier (/my-app/node_modules/babel/node_modules/babel-core/lib/babel/traversal/scope.js:270:30)
    at Scope.rename (/my-app/node_modules/babel/node_modules/babel-core/lib/babel/traversal/scope.js:417:31)
    at CommonJSFormatter._setup (/my-app/node_modules/babel/node_modules/babel-core/lib/babel/transformation/modules/common.js:48:11)
    at CommonJSFormatter.setup (/my-app/node_modules/babel/node_modules/babel-core/lib/babel/transformation/modules/common.js:41:10)
    at TraversalPath.exit (/my-app/node_modules/babel/node_modules/babel-core/lib/babel/transformation/transformers/internal/modules.js:125:28)
    at TraversalPath.call (/my-app/node_modules/babel/node_modules/babel-core/lib/babel/traversal/path/index.js:928:28)
    at TraversalPath.visit (/my-app/node_modules/babel/node_modules/babel-core/lib/babel/traversal/path/index.js:978:14)
    at TraversalContext.visitSingle (/my-app/node_modules/babel/node_modules/babel-core/lib/babel/traversal/context.js:90:12)
```

This seems to have started with Babel 5.4.x, it hadn't happened before with 5.3.x.

Sorry I can't provide any more details! I'm pretty bewildered by this and I don't have time to set up a VM and confirm my suspicions...

**Comment by sebmck** [comment] 2015-05-20 23:01
Can you post the module source or a minimal reproducible example with the file it's erroring on?

**Comment by sebmck** [comment] 2015-05-24 21:58
Closing this due to lack of reproducible example.

**Closed by sebmck** 2015-05-24 21:58 UTC
