### ISSUE TITLE
Babel-cli broken?

### ISSUE THREAD

**Issue by Swaagie** [babel/babel#2676] opened 2015-10-30 13:55 UTC
Using the babel-cli@6.0.12 with node@4.2.1 seems to be broken. Tried uninstalling both the global installed version as well as reinstalling local, nothing seems to make it work

```
> demo@1.0.0 start /projects/demo
> babel-node index.js

/projects/demo/index.js:3
import express from 'express';
^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at loader (/projects/demo/node_modules/babel-cli/node_modules/babel-core/lib/api/register/node.js:136:5)
    at Object.require.extensions.(anonymous function) [as .js] (/projects/demo/node_modules/babel-cli/node_modules/babel-core/lib/api/register/node.js:146:7)
```

**Comment by jmm** [comment] 2015-10-30 14:08
@Swaagie You probably just need to load the preset. Can you try this?:

```
$ npm i babel-preset-es2015
$ babel-node --presets babel-preset-es2015 index.js
```

**Comment by Swaagie** [comment] 2015-10-30 14:12
That works thanks, might be a good improvement to have this available as default or have the CLI tool issue a warning if a preset is missing or otherwise. It used to be harmony level 2 by default, this moves away from that default.

**Comment by claudiopro** [comment] 2015-10-30 14:14
:+1: I have the same issue, this change in behavior is going to cause some grief

**Comment by hzoo** [comment] 2015-10-30 14:19
http://babeljs.io/blog/2015/10/29/6.0.0/#opt-in-plugins In the blog post it explains that we are are moving to make everything opt-in (so it will do nothing by default). Yeah could be helpful to make a warning message about adding some plugins/presets if nothing is specified?

**Comment by jmm** [comment] 2015-10-30 14:20
@Swaagie 
> That works thanks

Ok, great. (You can of course configure the preset via `.babelrc` instead.)

> might be a good improvement to have this available as default or have the CLI tool issue a warning if a preset is missing or otherwise. It used to be harmony level 2 by default, this moves away from that default.

If you haven't yet, take a look at the release blog post. The major story of v6 is extracting all transforms from core into plugins and not transforming anything by default, so that's by design and not going to change. Now that Babel has no opinion about what transforms should run there'd be no way to issue a warning (except maybe if 0 presets or plugins are configured, maybe?) It will take some time for people to get informed about the new model.

If you have any other problems check out the support resources mentioned in the README:

> <p align="center">For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>.</p>

> <p align="center">The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.</p>

**Closed by jmm** 2015-10-30 14:20 UTC

**Comment by claudiopro** [comment] 2015-10-30 14:27
Let me disagree with this approach:

> It will take some time for people to get informed about the new model.

While it's a good idea to read release notes, such a relevant change in behavior can't be turned on by default without a deprecation or warnings. For instance, `npm` is doing a great job by warning about change in automatic install of peer dependencies in v3 for instance :-)

**Comment by hzoo** [comment] 2015-10-30 14:29
> (except maybe if 0 presets or plugins are configured, maybe?)

Might be useful for people simply updating to 6.0 without changing anyway (although they should probably read the relevant changes/docs anyway like mentioned).

**Comment by claudiopro** [comment] 2015-10-30 14:31
@hzoo :+1:

**Comment by jmm** [comment] 2015-10-30 14:50
@claudiopro 
> While it's a good idea to read release notes, such a relevant change in behavior can't be turned on by default without a deprecation or warnings.

So what specifically are you in favor of, issuing a warning if 0 presets or plugins are configured? Not sure what else would be possible.

@hzoo Yeah I saw that you had the same idea:
> warning message about adding some plugins/presets if nothing is specified


> Might be useful for people simply updating to 6.0 without changing anyway

Do you just mean that the warning would be helpful even for people starting fresh with v6?

**Comment by claudiopro** [comment] 2015-10-30 14:52
@jmm I believe @hzoo's suggestion to issue a warning if there are no presets is a good compromise

**Comment by jmm** [comment] 2015-10-30 15:06
@claudiopro Ok, thanks. It would have to be if there are no presets or plugins.

**Comment by claudiopro** [comment] 2015-10-30 15:08
@jmm thank you!

**Comment by jmm** [comment] 2015-10-30 15:23
@claudiopro @Swaagie: **sebmck** is probably going to be the one who makes this call. I suggest you run it by him on slack or open a new feature request issue for this warning message.
