### ISSUE TITLE
Babel rewrites react prop names as well as variable names

### ISSUE THREAD

**Issue by mhintz** [babel/babel#1604] opened 2015-05-22 08:48 UTC
I came across the following situation that had some really unexpected behavior:

```javascript
let [left, top] = (function that returns [number, number]);

var reactComponent = (
<Component left={left} top={top} />
);
```

inside reactComponent, this.props.top was undefined...

I checked out the generated code, and it looks like babel was rewriting the variable `top` to `_top`, but it was also rewriting the prop to `_top`,  so I was left with `<Component left={left} _top={_top}`, and was losing my prop.

(Rhyming totally unintentional...)

**Comment by monsanto** [comment] 2015-05-22 09:07
I can't reproduce w/ variations on your (invalid as-is) code. Can you please provide a minimal, self-contained test case that demonstrates your problem? Also please ensure you are using the latest version of Babel

**Comment by sebmck** [comment] 2015-05-22 09:24
Duplicate of #1596. Please upgrade.

**Closed by sebmck** 2015-05-22 09:24 UTC

**Comment by mhintz** [comment] 2015-06-11 22:01
Yep, this was because of not having the latest version. Sorry for the duplicate!
