### ISSUE TITLE
Cannot set core-js version for helper-only transformation in `@babel/tranform-runtime`

### ISSUE THREAD

**Issue by sodatea** [babel/babel#9903] opened 2019-04-26 08:34 UTC
## Feature Request

**Is your feature request related to a problem? Please describe.**

Basically we are trying to resolve this issue in [@vue/babel-preset-app](https://github.com/vuejs/vue-cli/blob/v3.0.5/packages/%40vue/babel-preset-app):
> https://github.com/babel/babel/issues/6628
> How can we write ES20xx and ship the smallest amount of code (for a given target environment)?

To be more specific, this item:
> * babel helpers: reference the same helpers instead of recreating per file (either via [/packages/babel-plugin-transform-runtime@`7.0`#options](https://github.com/babel/babel/tree/7.0/packages/babel-plugin-transform-runtime#options)

- To achieve that we need to combine `@babel/preset-env` with `@babel/transform-runtime`, and the latter one is only used to do helper transformation.
- The default runtime has a blocking issue though, see https://github.com/babel/babel/issues/7597
- So to circumvent it we have to use `@babel/runtime-corejs2`. I know it's not the best solution but it's an acceptable compromise/tradeoff in practice.
- Before beta.56 we were able to disable `polyfills` option while still referring the helper functions to `@babel/runtime-corejs2`.
- But after [this commit](https://github.com/babel/babel/commit/3210a7a873d6aced7aa3313a8be5121d8c4e5072#diff-76ec2b062a79e02e8adc6218241c667e), `polyfills` option is removed because it is now the default behavior.
- An unintended consequence is that we can no longer point `helpers` to any other runtime package without introducing core-js polyfills along with it.

**Describe the solution you'd like**

Bring back the `polyfills` option, allowing the user to opt-out it while still being able to specify a core-js version for helpers.

**Describe alternatives you've considered**
N/A

**Teachability, Documentation, Adoption, Migration Strategy**
N/A

**Comment by nicolo-ribaudo** [comment] 2019-04-26 09:03
As a workaround, you can use https://github.com/tleunen/babel-plugin-module-resolver to alias `@babel/runtime` -> `@babel/runtime-corejs2`

**Comment by nicolo-ribaudo** [comment] 2019-05-13 21:01
@sodatea I have been thinking about this issue today, and I think that the proper solution would be to transpile `@babel/runtime`'s helpers using `@babel/plugin-transform-runtime` itself.
This is tricky, because we should aboud transpiling everything else except for polyfills, to avoid injecting references to themselves inside the helpers.
A working config might look like this:
```js
module.exports = {
  overrides: [{
    // Use exclude or include, but be sure not to transpile those two packages
    exclude: ["@babel/runtime", "core-js"],

    // Your normal config
    presets: ["@babel/preset-env"],
    plugins: ["@babel/plugin-transform-runtime"]
  }, {
    include: "@babel/runtime",
    
    plugins: [
      ["@babel/plugin-transform-runtime", {
        "helpers": false,
        "corejs": 3
      }]
    ]
  }]
};
```

**Comment by micopiira** [comment] 2020-02-07 21:09
I can't believe how hard was to find this. I found here from @vue/babel-preset-app source code.

Basically all I want to do is to: 

- Include only necessary polyfills for target environment using @babel/preset-env
- Transform the babel helpers into imports using @babel/plugin-transform-runtime

The problem is that the babel helpers themselves need polyfills when targeting IE 11 for example.

Thanks to this issue & @vue/babel-preset-app source code I somehow managed to get this to work using following configuration:

```
// babel.config.js
module.exports = {
  sourceType: 'unambiguous',
  overrides: [{
    exclude: [/@babel[\/|\\\\]runtime/],
    presets: [['@babel/preset-env', { useBuiltIns: 'usage', corejs: 3 }]],
    plugins: [
      ['@babel/plugin-transform-runtime', { version: '^7.8.4' }]
    ]
  },
  {
    include: [/@babel[\/|\\\\]runtime/],
    presets: [
      ['@babel/preset-env', {
        useBuiltIns: 'usage',
        corejs: 3
      }]
    ]
  }
  ]
};
```

```
webpack.config.js
module.exports = {
	entry: './src/index.js',
	mode: 'development',
	module: {
		rules: [
			{
				test: /\.m?js$/,
				use: 'babel-loader',
				exclude: file => /node_modules/.test(file) && !/@babel[\/|\\\\]runtime/.test(file)
			}
		]
	}
};
```

PLEASE let me know if you know a better way to achieve this.

**Comment by nicolo-ribaudo** [comment] 2020-02-07 21:11
Your config looks fine to me: if a dependency (`@babel/runtime`) uses modern features not supported by your target envs, it should be transpiled.

There were a few problems when transpiling the `typeof.js` helper from `@babel/runtime`, but they have been fixed in v7.8.4.

**Comment by micopiira** [comment] 2020-02-07 21:20
@nicolo-ribaudo Alright, thanks for your insights!

I also noticed that when setting `useESModules: true` on plugin-transform-runtime you can leave the `sourceType: 'unambiguous'` out. `useESModules: true`  seems to produce a slightly larger bundle than just using `sourceType: 'unambiguous'` . Which one should I use? Or both?

**Comment by nicolo-ribaudo** [comment] 2020-02-07 21:53
`useESModules: true` should provide a smaller output when using Rollup because it handles ES modules better than CJS.
Webpack 5 might have the same benefit because it concatenates ES modules.

However, if you don't use native ES modules it shouldn't make too much a difference anyway.

**Comment by micopiira** [comment] 2020-02-07 22:07
sourceType | @babel/plugin-transform-runtime useESModules | result
-- | -- | --
module | FALSE | errors
module | TRUE | 157KiB
unambiguous | FALSE | 154KiB
unambiguous | TRUE | 159KiB

Did some tests.. I'm using webpack 4. sourceType: 'unambiguous' + useEsModules: true seems to include both helpers/*.js and helpers/esm/*.js. 

So you should probably use `sourceType: 'module' + useESModules: true` OR `sourceType: 'unambiguous' + useESModules: false`

**Comment by nicolo-ribaudo** [comment] 2020-02-07 22:08
Probably they are both included because one of your dependencies already depends on the non-ESM version.

**Comment by micopiira** [comment] 2020-02-07 22:21
@nicolo-ribaudo I did not have any dependencies other than babel/webpack related. See here https://github.com/micopiira/babel-webpack-test 

But using when using `sourceType: 'module' + useESModules: true` OR `sourceType: 'unambiguous' + useESModules: false` the helpers are only included once. Only combination of `sourceType: 'unambiguous' + useEsModules: true` includes them twice.

**Comment by nicolo-ribaudo** [comment] 2020-03-13 17:56
I'm closing this issue, since it's possible to transpile `@babel/runtime` with `@babel/preset-env` to add polyfills.

**Closed by nicolo-ribaudo** 2020-03-13 17:57 UTC
Labels: i: enhancement
