### ISSUE TITLE
Something unexpected after re-export a TypeScript Type

### ISSUE THREAD

**Issue by realduolaf** [babel/babel#10856] opened 2019-12-11 08:12 UTC
## Bug Report

I don't know if this is a bug. I saw #10162. Maybe there's something wrong with my configuration. Other relevant information #10337 #10044 .

**Current Behavior**
Using @babel/plugin-transform-typescript@7.7.4 via @babel/preset-typescript@7.7.4, re-export a typescript type and get a `not found` warning in the browser console.

```
WARNING in b.ts 2:0-43
"export 'SidebarNavItem' was not found in './a'
```

**Input Code**

in `a.ts`:
```ts
export type SidebarNavItem = {a: number, b: string}
```
in `b.ts`:
```js
export { SidebarNavItem } from './a.ts
```

**Expected behavior/code**

No warning in the browser console.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

This is the configuration.

```js
const presets = [
  [
    '@babel/env',
    {
      targets: 'last 2 version, > 0.2%, not dead',
      useBuiltIns: 'entry',
      corejs: 3,
    },
  ],
  '@babel/preset-react',
  ['@babel/preset-typescript', { isTSX: true, allExtensions: true }],
];
const plugins = [
  '@babel/plugin-proposal-nullish-coalescing-operator',
];
module.exports = { presets, plugins };
```

**Environment**

```
 System:
    OS: macOS 10.15.1
  Binaries:
    Node: 13.1.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.12.1 - /usr/local/bin/npm
  Monorepos:
    Yarn Workspaces: 1.19.1
    Lerna: 3.19.0
  npmPackages:
    lerna: 3.19.0 => 3.19.0 
```

- Babel version(s): v7.7.4
- Node/npm version: Node 13/npm 6
- OS: OSX 10.15.1
- Monorepo: Lerna
- How you are using Babel: webpack babel-loader

**Comment by shrinktofit** [comment] 2019-12-12 05:42
As far as I know, this is a restriction of `@babel/plugin-transform-typescript`.

Why?

`@babel/plugin-transform-typescript` transform Typescript files by eliminating imported identifiers if this identifier is type-only used, just like tsc with options `isolatedModules` set to true. For example:
```ts
import { IOptions } from "whatever";
const options: IOptions = {};
```
The plugin sees that `IOptions` is type-only used. So it remove
```ts
import { IOptions } from "whatever";
```
from emitted file.

But within a re-export statement:
```ts
export { IOptions } from "whatever";
```
the plugin does not know whether `IOptions` is type-only used --- and it can not be eliminated --- it's exported. So this statement is emitted. But as you know, types are not included at emitted files. So the error occurred.

**Comment by nicolo-ribaudo** [comment] 2019-12-12 09:19
That's correct @shrinktofit. Btw, this you actually test it `tsc` with `isolatedModules` matches Babel's behavior? If you did, then this is the expected behavior.

**Comment by realduolaf** [comment] 2019-12-12 09:36
@shrinktofit  Thanks for your reply。 I know the reason. I know that Babel handles these types by ignoring type checking, but I think maybe there is a way to determine the actual type(type-only or common) of the variable being exported when exporting it?

**Comment by nicolo-ribaudo** [comment] 2019-12-12 09:38
It's not possible, because Babel works per-file and not across the whole dependencies graph.

For example, given this code:
```js
export { Animal } from "./animals";
```
is it a type-only or commonjs variable?

**Comment by realduolaf** [comment] 2019-12-12 10:19
@nicolo-ribaudo Oh I see. Thanks for your reply. And I'm a little curious that if it's possible to add some syntax or some settings in comments(like eslint ignore) as a plug-in to manually mark whether to export or not? Wouldn't that be weird?

**Comment by shrinktofit** [comment] 2019-12-13 02:11
>  And I'm a little curious that if it's possible to add some syntax or some settings in comments(like eslint ignore) as a plug-in to manually mark whether to export or not? Wouldn't that be weird?

If you must do that, you can write a plugin to export interfaces, types to `undefined` or any value just like https://github.com/babel/babel/issues/10337 suggested.

**Comment by shrinktofit** [comment] 2019-12-13 02:59
> Btw, this you actually test it `tsc` with `isolatedModules` matches Babel's behavior? 

Yes. With `isolatedModules` set, tsc does not allow reimporter an interface, or type:

![image](https://user-images.githubusercontent.com/28807867/70764134-8f4ef000-1d91-11ea-8bef-c11bc121d664.png)

**Comment by nicolo-ribaudo** [comment] 2019-12-13 13:29
Thanks @shrinktofit!

@realduolaf I'm closing this issue, since Babel's goal is to match TS's `--isolatedModules` option.
If you want, I suggest following @shrinktofit's advice (https://github.com/babel/babel/issues/10856#issuecomment-565270310)

**Closed by nicolo-ribaudo** 2019-12-13 13:29 UTC
Labels: i: bug, i: needs triage
