### ISSUE TITLE
retainLines doesn't work with class-properties-transform

### ISSUE THREAD

**Issue by kangax** [babel/babel#4920] opened 2016-11-30 20:18 UTC
Given this input:

```js
 class SourceMapTest {
   /* some comment */
   foo() {
     debugger;
   }
   bar() {
     alert(1);
   }
 }
```

"retainLines" produces correct output:

```js
SourceMapTest.prototype.
foo=function(){'use strict';
debugger;
};SourceMapTest.prototype.
bar=function(){'use strict';
alert(1);
};function SourceMapTest(){'use strict';}
```

However, with "class-properties-transform", "retainLines" no longer works correctly:

```js
class SourceMapTest {
 /* some comment */
 foo() {
   debugger;
 }
 bar = function() {
    alert(1);
  };
}
```

```js
function SourceMapTest(){'use strict';this.





bar=function(){
alert(1);
};}SourceMapTest.prototype.foo=function(){'use strict';debugger;};
```

Notice that `foo` is not at the correct line.

**Comment by fatcerberus** [comment] 2017-02-07 15:39
I've noticed there are a few constructs for which `retainLines` glitches out.  The ones I've found so far:
* Generator functions
* Classes with accessors (get/set): The methods are placed in the correct position, but the accessors get appended to the end instead of staying where they are in the source.

**Comment by loganfsmyth** [comment] 2017-03-02 18:08
I'm gonna close this.

I don't know that we'll remove it, but I'd absolutely consider `retainLines` deprecated. It is unlikely that we'll put try to fix these issues. Better to rely on sourcemaps if you need mappings back to the original source.

**Closed by loganfsmyth** 2017-03-02 18:08 UTC
Labels: bug, pkg: generator

**Comment by fatcerberus** [comment] 2017-03-02 18:15
> I don't know that we'll remove it, but I'd absolutely consider retainLines deprecated. It is unlikely that we'll put try to fix these issues. Better to rely on sourcemaps if you need mappings back to the original source.

The main reason I use `retainLines` over source maps is because source maps complicate breakpoints.  For example, if I set a breakpoint on one line and Babel converts it to two or more, what do I map it to?  Do you set multiple breakpoints?  And if the transpiler combines multiple source lines into one, that's even worse because the debugger can't differentiate between them.

**Comment by loganfsmyth** [comment] 2017-03-02 19:34
Fair point. I don't think I'd considered `retainLines` as an actual human debugging benefit, I've been under the impression that most people used it for piecing together different tooling systems.

I generally feel like the output of Babel is close enough that you can mentally map things back to the original source. Do you find that having the exact line numbers match up helps your manual debugging process?

**Comment by fatcerberus** [comment] 2017-03-02 20:04
Some background here: I'm the developer of a JS-based game engine, [miniSphere](https://github.com/fatcerberus/minisphere).  The JS engine I use, Duktape, only supports ES5, so I *need* to use Babel to support ES6.  Duktape has a built-in stepping debugger which is used by my SSJ debugger frontend , but location tracking granularity only goes down to the line-number level - I can't set breakpoints based on an arbitrary character range, for example (incidentally this also prevents me from being able to debug minified code).  So if Babel converts one line to multiple, or combines two lines into one, my tooling doesn't know where to put the breakpoint at.  `retainLines` solves that.

So I'm actually not against using source maps at all, in fact I think they're much more flexible.  It's just that given the limitations I'm currently working with, `retainLines` is pragmatically the better solution.

**Comment by fatcerberus** [comment] 2017-03-04 16:07
Re: human debugging: I also find the option useful for that.  If I distribute a test build to my beta tester and it produces a runtime error, the Error's `.lineNumber` (displayed on the error screen) can then be traced back to the original source line.  In that case I don't have the luxury of running under the debugger to apply a source map--I only have the reported error message to go on.

**Comment by loganfsmyth** [comment] 2017-03-07 20:08
Interesting point for the alternate environment debugging. That does sound annoying.

For the case of test builds, if you so desired, it would likely be pretty easy for you to build a sourcemap so that when you get errors from test builds, you could process them with the sourcemap for that build, outside duktape, to get the original positions.

I still think this is something we aren't realistically likely to get to ourselves, but I do think this makes me less motivated to remove `retainLines` as a feature. For cases where it's reasonable to keep the code in order, we could consider PRs to make the ordering better.

**Comment by inikulin** [comment] 2017-03-14 10:28
@loganfsmyth We've encountered multiple cases there source maps give incorrect position with `retainLines` disabled. And while you may run in some problems with `retainLines` it's still much better than without it.

**Comment by loganfsmyth** [comment] 2017-03-15 17:39
Please in the future file bugs for cases you run across. We can't know that there are sourcemap issues if you don't give us examples.

**Comment by inikulin** [comment] 2017-03-15 18:14
@loganfsmyth These are quite complex chunks of code and issues usually represented by incorrect error stack frames generated using [source-map-support package](https://github.com/evanw/node-source-map-support). Therefore, it will take a lot of effort for us to create small test cases and we are not even sure if the problem is in `babel` itself or in `source-map-support`. `retainLines` worked well for us, so we decided to no allocate resources on research at the time. Since now removal of `retainLines` is just a matter of time I guess we'll try to triage and report issues we've found.

**Comment by loganfsmyth** [comment] 2017-03-15 18:25
I think I was convinced above to stand down from trying to remove it for now. It's not code I love, but I was under the mistaken impression that people only used it for tooling that didn't have sourcemap support, rather than day-to-day dev.

That said, it absolutely does have low priority, so while I'll certainly take PRs that try to make it work better without compromising other functionality, it is unlikely that we'd get to those fixes ourselves.

**Comment by inikulin** [comment] 2017-03-15 19:13
@loganfsmyth we're planning to land a couple of fixes for minor `retainLines` issues we've encountered recently.

**Comment by inikulin** [comment] 2017-03-15 19:21
Also, I recall that I was surprised at the time by the statement in the docs that `retainLines` is more suitable when you don't use sourcemaps. Sourcemaps are usually not perfect when it comes to accuracy and retaining line numbers more likely will increase chances that they'll point to correct line in the source. With this in mind, we've turned on `retainLines`  which eventually fixed most source map issues for us.

**Comment by Zarel** [comment] 2018-04-01 19:41
My problem is that Node.js error messages and `error.stack` traces do not support source maps, which is why I've been looking into `retainLines`. What do other people use for that problem?

**Comment by loganfsmyth** [comment] 2018-04-02 02:24
@Zarel https://github.com/evanw/node-source-map-support
