### ISSUE TITLE
Incorrect indentation within `else if` block.

### ISSUE THREAD

**Issue by rhys-vdw** [babel/babel#2298] opened 2015-09-01 13:17 UTC
Just updated to 5.8.23 and noticed this in our diff:

Input [(context)](https://github.com/tgriesser/bookshelf/blob/72308871b5a114d96a7519c6a84ed8480285bf59/src/base/collection.js#L180-L185):
```js
    } else if (add) {
      if (!(model = this._prepareModel(attrs, options))) continue;
      toAdd.push(model);
      this._byId[model.cid] = model;
      if (model.id != null) this._byId[model.id] = model;
    }
```

Output [(context)](https://github.com/tgriesser/bookshelf/blob/72308871b5a114d96a7519c6a84ed8480285bf59/lib/base/collection.js#L186-L191):
```js
    } else if (add) {
        if (!(model = this._prepareModel(attrs, options))) continue;
        toAdd.push(model);
        this._byId[model.cid] = model;
        if (model.id != null) this._byId[model.id] = model;
      }
```

No changes in the source file (as far as I can tell).

Unfortunately I'm not sure how to check which version of Babel I was using previously as I just ran `npm update`. Somewhere between 5.5.8 and 5.8.23.

Thanks for the great work. :+1:

**Comment by sebmck** [comment] 2015-09-01 14:38
Duplicate of #2084.

**Closed by sebmck** 2015-09-01 14:38 UTC
