### ISSUE TITLE
Export is not defined

### ISSUE THREAD

**Issue by jj-choi** [babel/babel#10044] opened 2019-05-30 03:39 UTC
## Bug Report

**Current Behavior**
SyntaxError: Export 'Foo' is not defined 

**Input Code**
```js
interface Foo {}

export type { Foo }
```

**Expected behavior/code**
no error

**Babel Configuration (.babelrc, package.json, cli command)**
flow plugin

**Environment**
- Babel version(s): 7.4.5
- Node/npm version: Node 11.13 / npm 6.7

**Possible Solution**
flowParseInterfaceish() should call checkLVal() or scope.declareName()

**Comment by ksocha** [comment] 2019-05-31 07:23
I've encountered similar issue with `@babel/plugin-transform-typescript@7.4.5`. Everything works fine with `@babel/plugin-transform-typescript@7.4.4`

**Comment by JoshRobertson** [comment] 2019-05-31 19:26
I've also encountered this issue upgrading from 7.4.4 to 7.4.5

**Comment by tanhauhau** [comment] 2019-06-15 15:40
@ksocha @JoshRobertson could you guys explain more on the specific code that produces error in typescript?

I [couldn't replicate it](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=JYOwLgpgTgZghgYwgAgGIHt3IN4F8BQ-EAHgA7pRg5qbK5A&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=false&targets=&version=7.4.5&externalPlugins=%40babel%2Fplugin-transform-typescript%407.4.5)

**Comment by ksocha** [comment] 2019-06-15 20:43
@tanhauhau 

I've created a repo using `create-react-app` that replicates the issue: https://github.com/ksocha/typescript-plugin-issue

With 7.4.5, you'll see that exported function is undefined.
Works fine with 7.4.4.

You can change versions by modifying resolutions entry in package.json.

**Comment by JLHwung** [comment] 2019-07-15 00:07
@ksocha Thanks for the reproduction repo! However, I can not reproduce this issue with `@babel/plugin-transform-typescript` 7.5.2 on your repo. Looking to the [commit history](https://github.com/babel/babel/commits/master/packages/babel-plugin-transform-typescript), it should be related to #9944 but later it has been fixed on 7.5.0.

**Comment by boris-petrov** [comment] 2019-07-15 08:36
@JLHwung - did you manage to catch the issue? Because I have the same issue even on the latest `7.5.4` version.

**Comment by JLHwung** [comment] 2019-07-15 13:59
@boris-petrov I assume you mean the issue submitted by the OP. And yes, the issue can be reproduced.

If you mean the issue submitted by @ksocha, I could not reproduce on his repo.

**Comment by boris-petrov** [comment] 2019-07-15 14:01
@JLHwung - sorry, yes, I mean the original issue. Great, so we'll be expecting a fix soon, thanks!

**Closed** 2019-10-02 05:32 UTC
Labels: Has PR, area: flow, i: bug, i: regression, pkg: parser
