### ISSUE TITLE
Memory Leak: Babel-polyfill on IE11 and MS Edge

### ISSUE THREAD

**Issue by gyandeeps** [babel/babel#4523] opened 2016-09-16 02:49 UTC
Recently we started using babel and also babel polyfill for our project. While everything works great on chrome we started seeing some sort of memory leak on every refresh of the page. Now i have narrowed it down to `babel-polyfill` artifact.
### System setup
- OS - Windows 10
- Browser - IE11 (11.103) and Fancy new IE Edge (38.14393.0.0)
### Steps
- `babel-polyfill` - 6.13.0

``` html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>JS Bin</title>
  <script>
//<----- plz but babel-polfill's ./dist/polyfill.js code here ---!>
  </script>
</head>
<body>
  <div>test</div>
  <script>
  setTimeout(function(){
    location.reload();
  }, 1000);
  </script>
</body>
</html>
```

**Note: Above page gets refreshed every 1 sec**
### Result

![image](https://cloud.githubusercontent.com/assets/5554486/18573953/e9255e2e-7b8d-11e6-82f0-2dcb66e4e6df.png)

Memory is constantly rising over time. I also did a test run for 10 mins, same result it was rising all the time.
### Observations
- Doesn't happen in Chrome
- Based on a experiment i did on a different project, it turns out any kind of circular reference leads to such kind of leaks in IE. I will experiment more to make sure this point holds true. 
### Questions
- Is this a known issue?
- Has anyone seen/experienced this?

**Comment by stefanpenner** [comment] 2016-09-16 03:02
Given that you are reloading the page, it seems more likely that you are encountering a browser bug of some sort. Now it may be possible that the polyfill provided by core-js is triggering it, but the issue is most likely in IE11 itself. I have seen some leaks in earlier revisions of IE11, but those have been addressed in later patch versions. So let me recommend confirming you have the latest IE11. :)

**Comment by gyandeeps** [comment] 2016-09-16 03:03
Yes, 11.103.
Also, if i manually refresh still same results. Also it happens on Edge also.

**Comment by gyandeeps** [comment] 2016-09-20 20:30
Reported to Microsoft: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8992678/

**Comment by bjankord** [comment] 2016-09-22 15:14
Related: https://twitter.com/ericf/status/776141369874210816

**Comment by cmgurba** [comment] 2016-09-23 15:51
Do you have a screenshot of it maintaining steady memory levels on a site without babel-polyfill?  I added the looping script to a bare html page and experienced slower, yet still constant rise of memory usage until crash.

**Comment by gyandeeps** [comment] 2016-09-24 02:35
**UPDATE:**

Received a **confirmed** status on the issue.

**Comment by DrewML** [comment] 2016-10-17 02:41
@gyandeeps If may be worth logging an issue on the [core-js](https://github.com/zloirock/core-js) repository in case the maintainer(s) are interested in implementing a patch (if possible). If not, it may at least help out other `core-js` users to identify the problem (IE11 bug) quicker,

**Comment by nolanlawson** [comment] 2016-12-30 23:30
Hi folks, sorry for the delay! I updated the repro steps in [the Edge issue](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8992678/); turns out this is a problem in the F12 Dev Tools and _not_ in the browser itself. Note that F12 injects handlers into Edge/IE that only go away when you close the browser and fully re-open it, so that might be why it originally seemed like a non-F12 issue.

Feel free to leave this issue open, but know that I've reassigned it to the F12 team to take a look. :smiley:

**Comment by stefanpenner** [comment] 2017-01-03 23:03
@nolanlawson you rock!

I'm going to close this, as it is now in the very capable hands of the F12 team.

**Closed by stefanpenner** 2017-01-03 23:03 UTC

**Comment by jeffal** [comment] 2017-04-26 21:06
I suspect `require('core-js/modules/es6.function.name');` is the offender.
