### ISSUE TITLE
Decorators and parameters with parentheses wonkiness

### ISSUE THREAD

**Issue by raymond-h** [babel/babel#2098] opened 2015-07-27 23:20 UTC
Babel behaves weirdly when there are parameters containing parentheses:

```js
@doCoolThings( (banana) )
class What {

    render() {
      return blah;
    }
}
```

...Compiles to:

```js
// ...

var What = (function () {
  function What() { /* ... */ }
  
  What.prototype.render = function render() {
    return blah;
  };
  
  // ???
  return What;
})();
```

Note that there is no invocation of the decorator function inserted into the final code.

Removing the parentheses around the `banana` parameter in the decorator, however, fixes this:

```js
@doCoolThings( banana )
class What {

    render() {
      return blah;
    }
}
```

...Compiles to:

```js
// ...

var What = (function () {
  function What() { /* ... */ }

  What.prototype.render = function render() {
    return blah;
  };
  
  // Hooray, call of decorator!
  var _What = What;
  What = doCoolThings(banana)(What) || What;
  return What;
})();
```

If using an arrow function (like `(banana) => 55`), the effect is pretty much the same when the parentheses are present vs. non-present.

**Comment by jridgewell** [comment] 2015-07-27 23:28
Dupe of https://github.com/babel/babel/issues/2086?

**Comment by loganfsmyth** [comment] 2015-07-27 23:30
and #2088 #2090 #2093 #2094

**Closed by loganfsmyth** 2015-07-27 23:30 UTC

**Comment by seiyria** [comment] 2015-07-27 23:39
So all of the duplicates are closed, which issue is actually being used to track progress on this?

**Comment by loganfsmyth** [comment] 2015-07-27 23:45
See https://github.com/babel/babel/issues/2086
