### ISSUE TITLE
Re-exports hoisted above imports

### ISSUE THREAD

**Issue by jneuendorf** [babel/babel#6468] opened 2017-10-12 15:09 UTC
I have encountered something that's very likely a bug.
In the same module, the transpiled code for `export ... from ...` appears before the transpiled code for `import ...` in the output.
This scenario has already been asked [here](http://discuss.babeljs.io/t/re-exports-hoisted-above-imports/773) - unfortunately without an answer.
I think this is a bug because the 2 following snippets should be equivalent:

```js
import foo from 'foo';
export { default as bar } from 'bar';
```

```js
import foo from 'foo';
import bar from 'bar';
export { bar }
```

### Input Code

```js
import foo from 'foo';
export { default as bar } from 'bar';
```

see the [REPL](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=JYWwDg9gTgLgBAMwhRUIjgciRTBuAKAFMAPSWOAbzgBMiEBDAVwBt4GBnOAIwajgC-qdFl5R8QA&debug=false&circleciRepo=&evaluate=true&lineWrap=false&presets=es2015%2Ces2016%2Ces2017%2Creact%2Cstage-0%2Cstage-2&targets=&version=6.26.0)

### Babel Configuration (.babelrc, package.json, cli command)

Part of my `package.json`:

```js
{
  "devDependencies": {
    "babel-eslint": "^7.2.3",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-preset-react-native": "^4.0.0",
    "eslint": "^4.6.1",
    "eslint-plugin-react": "^7.3.0",
    "react-test-renderer": "16.0.0-alpha.12"
  },
  "scripts": {
    "start": "react-native start",
    "android": "react-native run-android",
    "ios": "react-native run-ios",
  },
  "dependencies": {
    "immutable": "^3.8.1",
    "prop-types": "^15.5.10",
    "react": "16.0.0-alpha.12",
    "react-native": "0.47",
    "react-navigation": "^1.0.0-beta.11",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-logger": "^3.0.6",
    "redux-promise": "^0.5.3",
    "redux-thunk": "^2.2.0"
  }
}
```

### Expected Behavior

The behavior should be equivalent to

```js
import foo from 'foo';
import bar from 'bar';
export { bar }
```

### Current Behavior

Currently the code gets executed as if it was written like this:

```js
export { default as bar } from 'bar';
import foo from 'foo';
```

`'bar'` is required before `'foo'` no matter what exactly is put between `export` and `from` (e.g. the problem also occurs for `export * from ...`).

### Context

I am exporting multiple moddules from an `index.js` file.
All exports depend on some code that must have been run.

```js
import "./this_code_must_be_run_before_the_exports"
export * from "./first"
export * from "./second"
```

### Your Environment

I am using babel with React Native.

| software         | version(s)
| ---------------- | -------
| Babel            | latest (https://babeljs.io/repl/)
| node             | 8.7.0
| npm              | 5.4.2
| Operating System | macOS 10.12.6

**Comment by jridgewell** [comment] 2017-10-19 21:21
/to @loganfsmyth, modules seem to be your area. 😉

**Comment by loganfsmyth** [comment] 2017-10-19 21:36
I believe this is a duplicate of https://github.com/babel/babel/issues/4493 which actually looks to have been closed incorrectly.

This should be fixed with https://github.com/babel/babel/pull/6230 on 7.x now with the module transform rewrite.

**Comment by loganfsmyth** [comment] 2017-10-19 21:37
The output of your code snippet on `master` is
```
"use strict";

var _interopRequireDefault = require("@babel/runtime/helpers/interopRequireDefault");

Object.defineProperty(exports, "__esModule", {
  value: true
});
Object.defineProperty(exports, "bar", {
  enumerable: true,
  get: function get() {
    return _bar.default;
  }
});

var _foo = _interopRequireDefault(require("foo"));

var _bar = _interopRequireDefault(require("bar"));
```
so things should load in the right order.

**Comment by jneuendorf** [comment] 2017-10-23 10:02
I will check this again (with my concrete code) once babel 7 is released stably. Thanks for the help 😄

**Comment by loganfsmyth** [comment] 2017-10-23 14:36
Alright, going to close this, but we can certainly re-open if there is still an issue.

**Closed by loganfsmyth** 2017-10-23 14:36 UTC
Labels: area: modules
