### ISSUE TITLE
Unknown option: retainLines

### ISSUE THREAD

**Issue by tontonskie** [babel/babel#1703] opened 2015-06-07 17:43 UTC
I'm using gulp-babel and it's showing me error 

Unknown option: retainLines

**Comment by sebmck** [comment] 2015-06-07 17:45
Full stack trace and babel version number please.

**Comment by sebmck** [comment] 2015-06-09 12:34
Closing due to lack of reproducible example.

**Closed by sebmck** 2015-06-09 12:34 UTC

**Comment by zyklus** [comment] 2015-08-20 10:49
Suggest re-opening:

```shell
➜  ~  babel --version
5.8.21 (babel-core 5.8.22)

➜  ~  babel --retainLines

  error: unknown option `--retainLines'
```

**Comment by sebmck** [comment] 2015-08-20 11:49
--retain-lines
