### ISSUE TITLE
[Bug]: Omitted spread properties are incorrectly hoisted when using computed properties with template strings

### ISSUE THREAD

**Issue by tidychips** [babel/babel#13430] opened 2021-06-07 14:42 UTC
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

```js
const example = (obj) => {
  const foo = 'foo';
  const { [`prefix_${foo}`]: _, ...rest } = obj;
};
```

[REPL Link](https://babeljs.io/repl/#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=MYewdgzgLgBApgDwIYFsAOAbOMC8MAUIARgFYCUuAfDAN4BQMMoksAZiCLjAOTsjcBuBk3DRaMANoADNACc4rAJYIA-gBIafAL5SAugC4YKgDQwAdBflitXYiSFahQA&debug=false&forceAllTransforms=true&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.14.4&externalPlugins=%40babel%2Fplugin-transform-typescript%407.14.4)

### Configuration

The copied config is a bit over complicated to reproduce the issue.  The repl link above has a minimal config that highlights the issue better.

```json
{
  "assumptions": {},
  "compact": false,
  "sourceMaps": true,
  "sourceType": "unambiguous",
  "cwd": "/Users/tidychips/repos/repo",
  "filename": "/Users/tidychips/repos/repo/path/to/file",
  "sourceFileName": "/Users/tidychips/repos/repo/path/to/file",
  "targets": {},
  "cloneInputAst": true,
  "babelrc": false,
  "configFile": false,
  "browserslistConfigFile": false,
  "passPerPreset": false,
  "envName": "development",
  "root": "/Users/tidychips/repos/repo",
  "rootMode": "root",
  "plugins": [
    [
      "[Function: function _default(_ref) {\n  var t = _ref.types;\n   ... ]",
      {
        "pure": false,
        "minify": false,
        "transpileTemplateLiterals": false
      }
    ],
    [
      "[Function: (api, options, dirname) => {\n    var _clonedApi2;\n ... ]",
      {
        "corejs": false,
        "helpers": true,
        "regenerator": true,
        "useESModules": false
      }
    ],
    [
      "[Function: (api, options, dirname) => {\n    var _clonedApi2;\n ... ]",
      {
        "legacy": true
      }
    ],
    [
      "[Function: (api, options, dirname) => {\n    var _clonedApi2;\n ... ]",
      {
        "loose": true
      }
    ],
    [
      "[Function: (api, options, dirname) => {\n    var _clonedApi2;\n ... ]",
      {
        "loose": true
      }
    ],
    [
      "[Function: (api, options, dirname) => {\n    var _clonedApi2;\n ... ]",
      {
        "loose": true
      }
    ],
    "[Function: (api, options, dirname) => {\n    var _clonedApi2;\n ... ]",
    "[Function: (api, options, dirname) => {\n    var _clonedApi2;\n ... ]",
    "[Function: function _default() {\n  let changed = [];\n  /**\n   ... ]"
  ],
  "presets": [
    [
      "[Function: (api, options, dirname) => {\n    var _clonedApi2;\n ... ]",
      {
        "modules": "commonjs",
        "targets": {
          "chrome": "73",
          "edge": "17",
          "firefox": "68",
          "ie": "11",
          "ios": "11",
          "safari": "11.1"
        },
        "useBuiltIns": "entry",
        "corejs": 3,
        "exclude": [
          "transform-typeof-symbol"
        ],
        "debug": false
      }
    ],
    [
      "[Function: (api, options, dirname) => {\n    var _clonedApi2;\n ... ]",
      {
        "development": true,
        "useBuiltIns": true
      }
    ],
    "[Function: (api, options, dirname) => {\n    var _clonedApi2;\n ... ]",
    "/Users/tidychips/repos/repo/node_modules/@m/babel-preset-companyname/src/index.js"
  ]
}
```

### Current and expected behavior

**Current Behavior:** The change made in https://github.com/babel/babel/pull/13384 will incorrectly hoist omitted template string properties to the top level scope of the file when they contain interpolations using locally scoped variables.  This causes the file to throw a `ReferenceError` when imported because the variable is not defined in the top level scope.

**Expected Behavior:** Do not hoist omitted keys when they depend on locally scoped variables

### Environment

```
  System:
    OS: macOS 10.15.7
  Binaries:
    Node: 12.22.1 - ~/.nvm/versions/node/v12.22.1/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.12 - ~/.nvm/versions/node/v12.22.1/bin/npm
  Monorepos:
    Yarn Workspaces: 1.22.10
    Lerna: 4.0.0
  npmPackages:
    jest: 26.6.3 => 26.6.3 
    lerna: 4.0.0 => 4.0.0 
```

**Comment by nicolo-ribaudo** [comment] 2021-06-07 14:54
The problem is that in the `else-if` branch of https://github.com/babel/babel/blob/4eda1c860507e84b44a718a39ce58cf45f7ccc6e/packages/babel-plugin-transform-destructuring/src/index.js#L226-L243 we hoist the computed keys if they are all literals.

As this issue shows, it is a wrong approach: we should only do that if we only have literals that do not reference any other variable. The easiest way to do so is probably to add a new variable `allPureLiterals`, and set it to `false` not only when we find a generic computed key, but also when we find a key that is a template literal with `> 0` child expressions.

It also needs to be fixed at https://github.com/babel/babel/blob/4eda1c860507e84b44a718a39ce58cf45f7ccc6e/packages/babel-plugin-proposal-object-rest-spread/src/index.js#L182.

**Comment by nicolo-ribaudo** [comment] 2021-06-07 15:06
@tidych As a workaround, you can manually extract the computed key:
```js
const k = `prefix_${foo}`;
const { [k]: _, ...rest } = obj;
```

**Comment by tony-go** [comment] 2021-06-07 15:07
✋ I'll be happy to give a try ^^

**Comment by jridgewell** [comment] 2021-06-07 19:16
Ugh, I hate that we called ``` `foo` ``` and ``` `foo${bar}` ``` "literals". They're a template _expressions_. TC39 actually rejected expanding string literals to include expression-less templates (eg, ``` const o = { `foo`: true } ``` isn't valid).

@tony-go: There are some related code locations at:
- https://github.com/babel/babel/blob/4eda1c860507e84b44a718a39ce58cf45f7ccc6e/packages/babel-plugin-transform-destructuring/src/index.js#L207-L208
- https://github.com/babel/babel/blob/4eda1c860507e84b44a718a39ce58cf45f7ccc6e/packages/babel-plugin-proposal-object-rest-spread/src/index.js#L103-L104

Be careful that you do not use `isPure` helper when checking the template, we since templates which reference constant values are "pure" but still unhoistable. Eg, https://astexplorer.net/#/gist/5f2607e8caf62da7d72bb1044c8f102b/0c0bdb994cc263ee0c9e2dcb54bc2cab3d39229b. Instead, we should just deopt if the template has _any_ expressions.

**Comment by tony-go** [comment] 2021-06-07 19:44
Hi Guys 👋 

Thanks a lot for your insights.

@jridgewell  Can you give me more details about:

> Instead, we should just deopt if the template has any expressions.

I'm not familiar with all terms (_deopt_) yet ^^

**Comment by jridgewell** [comment] 2021-06-07 20:31
Deopt means de-optimize. We currently have an optimization that omitted keys can be hoisted if they're `allLiteral`, but we need to add a de-optimization if we find that one of the "literal" keys is actually a template with an expression (these aren't really "literal").

So, essentially:

```
if (allLiteral && !hasTemplateExpression) {
  // optimize by hoisting
} else {
  // Do nothing, ie, deopt
}
```

**Comment by tony-go** [comment] 2021-06-11 06:31
Hi guys 👋 

Just to keep you informed that I'm currently working on the PR #13419 

An it's seems more complicated than we expected.

Hopefully @JLHwung helps me a lot ^^

_Note_: If you consider that i'm too slow, feel free to reassign it. 🤟

**Comment by nicolo-ribaudo** [comment] 2021-06-16 17:01
@lala7573 Do you want to work in this? Ideally we can release a fix in the next patch release.

**Comment by lala7573** [comment] 2021-06-17 14:25
@nicolo-ribaudo 
I just fix not to generate hoisted. As jridgewell mentioned, I add a new flag named `hasTemplateExpression`.
I'm thinking about another corner case... If it is ok, I'm going to make a new PR.

https://github.com/babel/babel/compare/main...lala7573:fix-13430

**Comment by nicolo-ribaudo** [comment] 2021-06-17 14:28
If there are only literals (either template or not) we don't need to call `babelHelpers.toPropertyKey`.

**Comment by lala7573** [comment] 2021-06-17 15:21
@nicolo-ribaudo 
Oh now I understand... I fix it. 
https://github.com/babel/babel/compare/main...lala7573:fix-13430

**Comment by nicolo-ribaudo** [comment] 2021-06-17 18:25
Please open a PR, it's easier to review and comment!

**Comment by jridgewell** [comment] 2021-06-18 02:30
This still needs to be fixed in object-rest-spread: https://github.com/babel/babel/blob/4eda1c860507e84b44a718a39ce58cf45f7ccc6e/packages/babel-plugin-proposal-object-rest-spread/src/index.js#L103-L104

[REPL](https://babeljs.io/repl/build/main#?browsers=ie%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABHARgKwKbQEoYM5QAUMAlIgN4BQiihVNNGAHhADYgAmGHANNQwG0ABgGsMATwAk5GAF8hAXQBciEHm64wAQwC23Pg0QA6EwAcATnFN5-sxAF5EUABYw8Ri1bwkA3JVmUQA&debug=false&forceAllTransforms=true&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.14.6&externalPlugins=)

**Closed** 2021-06-21 20:48 UTC
Labels: i: bug, i: regression
