### ISSUE TITLE
Babel very strange move comments

### ISSUE THREAD

**Issue by burashka** [babel/babel#5512] opened 2017-03-20 15:49 UTC
Babel very strange move comments: example, DojoDoc comments in function and info about copyright.

### Input Code
```js
// Available via the modified BSD license. See LICENSE for details.

import a from "a";

const ESC = 27;

var obj = {
  isValid: function(/*Boolean*/ /*===== isFocused =====*/) {
			return true;
		}
};
```

### Babel Configuration (.babelrc, package.json, cli command)
es2015 preset

### Expected Behavior
```js
// Available via the modified BSD license. See LICENSE for details.
"use strict";

var _a = require("a");

var _a2 = _interopRequireDefault(_a);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

var ESC = 27;

var obj = {
	isValid: function isValid(/*Boolean*/ /*===== isFocused =====*/){
		return true;
	}
};
```

### Current Behavior
```js
"use strict";

var _a = require("a");

var _a2 = _interopRequireDefault(_a);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

var ESC = 27; // Available via the modified BSD license. See LICENSE for details.

var obj = {
	isValid: function isValid() /*Boolean*/ /*===== isFocused =====*/{
		return true;
	}
};
```

### Your Environment
You can reproduce on your sandbox ("Try it out"): http://babeljs.io/repl/

**Comment by hzoo** [comment] 2017-03-20 15:53
Thanks for the report.

**Comment by kaicataldo** [comment] 2017-03-20 16:16
Comments are challenging because they can occur _anywhere_.  The way the current algorithm works, comments are marked as "leading" and "trailing" comments on nodes. This method works in that all comments are accounted for (i.e. no comments will be lost), but isn't very precise as far being able to calculate where the comment should go after transformation. 

This _might_ be made better by thinking of comments in the context of token lists (i.e. the comment originally occurred after this opening parens token so let's put it back in right after the opening parens token), but I think there will always be cases where the comments will be in the "incorrect" location.

For example, for the following code, given the following comment locations:
```js
function foo({ a = /* comment */ true }) {}
function foo({  /* comment */ a = true }) {}
function foo(/* comment */ {  a = true }) {}
function foo({  a = true /* comment */ }) {}
function foo({  a = true } /* comment */) {}
```

Where should the comments go in this transformed output for each respective comment location?
```js
function foo(_ref) {
  var _ref$a = _ref.a,
      a = _ref$a === undefined ? true : _ref$a;
}
```

When the output is so different from the input, it's really hard to know, and I'm not sure it's worth solving this problem right now. Would you mind explaining the situations where the comments in the transpiled output are necessary? Would love to understand why you think this should be prioritized.

**Comment by burashka** [comment] 2017-03-20 19:58
Thanks for your answer. We develops [UI Framework for APS Standard](http://doc.apsstandard.org/2.2/frontend/). It based on Dojo Toolkit and use [DojoDoc](http://dojotoolkit.org/reference-guide/1.10/developer/markup.html#developer-markup) for [auto-generate documentation](http://doc.apsstandard.org/2.2/frontend/widgets-api/w/aps-ActiveItem/).

DojoDoc have syntax: _attrToDom: function(/*String*/ attr, /*String*/  value){ or _attrToDom: function(/*String*/ /*== attr  ==*/){.

We transforms ES modules with ES2015+ features to AMD modules and build it with help Dojo Builder. Dojo Builder try generate documentation and crashes on moved comments.

**Comment by dmail** [comment] 2017-03-21 15:32
As #5503 demonstrates leading comments are messed up. I made PR #5504 to fix this issue and it works however comment output is still a bit messy.
The PR also contains tests that helps to understand where comments will be when a node is removed using `path.remove()`.

**Comment by danielo515** [comment] 2017-06-11 10:54
I have a similar issue with comments. My important comments are just headers. This means that I want my comments to stay on top of the code, and I want them to preserve the format.

In my case, funny things happens depending if the original code includes `"use strict"` or not.

For example, this code:

```js
/*\
title: $:/plugins/danielo515/tiddlypouch/config/single-db-config
type: application/javascript
module-type: library


@preserve

\*/

function dbConfig(name, remote) {
  if ( typeof name === 'object' ){
      remote = name.remote;
      name = name.name;
    }
  this.name = name;
}
```

Produces an unexpected output that breaks my headers:

```js
'use strict';

var _typeof = typeof Symbol === "function" && typeof Symbol.iterator === "symbol" ? function (obj) { return typeof obj; } : function (obj) { return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj; };

/*\
title: $:/plugins/danielo515/tiddlypouch/config/single-db-config
type: application/javascript
module-type: library


@preserve

\*/

function dbConfig(name, remote) {
  if ((typeof name === 'undefined' ? 'undefined' : _typeof(name)) === 'object') {
    remote = name.remote;
    name = name.name;
  }
  this.name = name;
}
```

BUT if I manually add `use strict` to the source code, then the expected output is generated:

input:

```js
/*\
title: $:/plugins/danielo515/tiddlypouch/config/single-db-config
type: application/javascript
module-type: library


@preserve

\*/

'use strict'
function dbConfig(name, remote) {
  if ( typeof name === 'object' ){
      remote = name.remote;
      name = name.name;
    }
  this.name = name;
}
```

Output:

```js
/*\
title: $:/plugins/danielo515/tiddlypouch/config/single-db-config
type: application/javascript
module-type: library


@preserve

\*/

'use strict';

var _typeof = typeof Symbol === "function" && typeof Symbol.iterator === "symbol" ? function (obj) { return typeof obj; } : function (obj) { return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj; };

function dbConfig(name, remote) {
  if ((typeof name === 'undefined' ? 'undefined' : _typeof(name)) === 'object') {
    remote = name.remote;
    name = name.name;
  }
  this.name = name;
}
```

Not sure if this is a feature or an unexpected behavior, but at least it allows me to save my comments, so please do not remove it. It will be also useful to document this.

Regards

**Comment by danielo515** [comment] 2017-06-11 10:59
wort mention that if you place your `use strict` inside an IIFE then the first unexpected output comes back. For example, modifying the previous code like this:

```js
/*\
title: $:/plugins/danielo515/tiddlypouch/config/single-db-config
type: application/javascript
module-type: library

@preserve

\*/

(function(){
'use strict'
function dbConfig(name, remote) {
  if ( typeof name === 'object' ){
      remote = name.remote;
      name = name.name;
    }
  this.name = name;
}})()
```

Will produce the previous unexpected output

**Comment by loganfsmyth** [comment] 2017-06-11 19:41
@danielo515 The case you're referring to could just as easily go the other way. If I had

```
/**
 * @param {string} p1 Some function param
 */
function fn(p1){}
```
then

```
/**
 * @param {string} p1 Some function param
 */
"use strict";

function fn(p1){}
```
would be the opposite of what you'd expect because the docs are meant to be attached to the function, not the top of the file.

I don't see a way for us the tell the difference between these two cases.

**Comment by danielo515** [comment] 2017-06-12 13:44
@loganfsmyth as you can see in my previous answer I found the way to workaround my problem. I was just specifying in which cases you get an output other than the desired. I'm fine about putting the `use strict` statement whenever makes sense to avoid this problem. I just wanted to make sure that this behavior is reported and also that it is not changed or removed.

Regards

**Comment by tilgovi** [comment] 2018-03-12 02:24
Maybe `@license` is a good heuristic for keeping a comment at the top? That's a common pattern.

**Comment by tilgovi** [comment] 2018-03-12 02:26
`@babel/generator` already handles `@license` specially.

**Comment by loganfsmyth** [comment] 2018-03-12 17:07
The issue is that there is no "top" to keep things attached to. Comments just get attached to the thing they are nearest to.

It's not a great system for keeping comment locations, but handling comments with anything more than a best-effort attempt is not something Babel has ever tried to do. It would likely require that we use a full concrete syntax tree instead of a general abstract syntax tree, and it would make transforms likely much more complex.

To me it sounds like the best solution would be to update the documentation generator to run on the original source files.

**Closed by loganfsmyth** 2018-03-12 17:07 UTC
Labels: area: comments

**Comment by danielo515** [comment] 2018-03-12 18:23
> To me it sounds like the best solution would be to update the documentation generator to run on the original source files.

That makes sense in the case your objective is generating documentation. But some projects require comments and we just want to use the latest javascript with them. 

Regards

**Comment by loganfsmyth** [comment] 2018-03-12 18:35
> some projects require comments

What kind of examples do you have in mind?

**Comment by tilgovi** [comment] 2018-03-12 18:39
I'll give you my example, though I'm sure I can find a workaround.

It feels most correct to me to keep my license header in every source file. Since these headers have `@license` they cannot be stripped by `--no-comments`. I could add the license header with a plugin but I cannot strip it. I'm stuck having either no headers in the files of my repo and proper headers in my built package, or having headers in my repo and sometimes duplicate headers in my built package.

I understand there is no logical top of the file to attach a comment to, but there is an implicit top that exists by inserting a comment before the first expression, I would think. It certainly seems like I could write a plugin that strips `@license` headers from input files and re-inserts them at the end of compilation. I might try to write such a plugin, but I wonder if that's not a common enough use case that it deserves to be handled out of the box.

**Comment by loganfsmyth** [comment] 2018-03-12 19:05
@tilgovi Here ya go: https://www.npmjs.com/package/babel-plugin-preserve-comment-header

**Comment by tilgovi** [comment] 2018-03-12 19:09
@loganfsmyth that's incredibly nice of you. Since you know this stuff in and out I guess that might have not a lot of effort for you, but I appreciate it deeply. Thanks for being amazing.

**Comment by loganfsmyth** [comment] 2018-03-12 19:16
No problem! I was gonna post it in a comment and then decided I might as well just publish it :D

**Comment by danielo515** [comment] 2018-03-14 08:13
Hello @loganfsmyth , [tyddlywiki](https://tiddlywiki.com/) is an example. It uses magic headers on the JS files to determine the type of module, its name etc. What I'm doing is including the `@preserve` annotation (which works with some uglifiers). Maybe your new-born plugin can take it in account as default ? 
Regards

**Comment by loganfsmyth** [comment] 2018-03-14 16:51
@danielo515 That is likely something that module can do. It is configurable so you should be able to just set `pattern: "@preserve"` as an option for the plugin.
