### ISSUE TITLE
transform-react-constant-elements causes "We don't know what to do with this node type."

### ISSUE THREAD

**Issue by jbrantly** [babel/babel#5369] opened 2017-02-24 02:04 UTC
### Input Code
```js
class A extends React.Component {
    render() {
        return <B />
    }
}

export class B extends React.Component {
    render() {
        return null
    }
}
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
    "plugins": [
        "transform-react-jsx",
        "transform-react-constant-elements"
    ]
}
```

### Expected Behavior
Should not error.

### Current Behavior
Errors with "We don't know what to do with this node type. We were previously a Statement but we can't fit in here?"

### Context
This seems to be a regression in 6.23.0 as the same code is transpiled into a working state with 6.22.0. My guess is that this was introduced in #5153.

Of note is that the code does transpile if the `export` is removed from the second class.

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.23.0
| node             | 6.9.4
| npm              | 3.10.10
| Operating System | Windows 10

cc @STRML

**Comment by STRML** [comment] 2017-02-24 12:36
Thanks @jbrantly, and thanks for the test case. We have a few issues we've seen in 6.23 - this is a tricky beast and includes some updates to `PathHoister` which are hitting a few edge cases, such as default params. I hope to have them resolved by the next minor.

**Comment by STRML** [comment] 2017-03-03 22:51
A minimal test case:

```jsx
class A {
    render() {
        return <B />
    }
}

export class B {}
```

The issue is that we're calling `path.insertAfter()` on the `export class B` `ClassDeclaration`, who's parent is an `ExportNamedDeclaration`, not the `Program`. Removing the `export` does not demonstrate the issue.

**Closed** 2017-05-01 19:41 UTC
Labels: area: react, Has PR
