### ISSUE TITLE
[4.7.8] for-of depends on Symbol which depends on runtime shims/"polyfill"

### ISSUE THREAD

**Issue by rsms** [babel/babel#1007] opened 2015-03-12 18:57 UTC
The `es6.forOf` transformer is enabled by default, yet code containing `for (x of y) ...` will not function unless the "polyfill" runtime library is enabled. This is due to the fact that for-of code generates use of Symbol, which is not provided by babel helpers, thus is undefined. The documentation does not mention this fact (http://babeljs.io/docs/learn-es6/#iterators-for-of) (no "Support via polyfill" note.)

**Suggestion:** Make forOf optional and add "Support via polyfill" note to documentation, or introduce "Symbol" inline helper to remove dependency on "polyfill."

> Note: [es6-transpiler](https://github.com/termi/es6-transpiler) does support for-of via inline helpers.

Example:

```js
for (x of y) {}
```

Generated: (note use of `Symbol.iterator`)

```js
"use strict";

var _iteratorNormalCompletion = true;
var _didIteratorError = false;
var _iteratorError = undefined;

try {
  for (var _iterator = y[Symbol.iterator](), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true) {
    x = _step.value;
  }
} catch (err) {
  _didIteratorError = true;
  _iteratorError = err;
} finally {
  try {
    if (!_iteratorNormalCompletion && _iterator["return"]) {
      _iterator["return"]();
    }
  } finally {
    if (_didIteratorError) {
      throw _iteratorError;
    }
  }
}
```

- Babel v 4.7.8
- Tested with Nodejs v0.10.36

**Comment by rsms** [comment] 2015-03-12 19:04
Theory: Babel was tested on nodejs >=0.11.15 (where Symbol was introduced) but hasn't been tested on older versions of nodejs. (e.g. latest Ubuntu (utopic) provides nodejs 0.10.25.)

**Comment by zloirock** [comment] 2015-03-12 19:30
[Hmm?](http://babeljs.io/docs/usage/caveats/#polyfills)

**Comment by neVERberleRfellerER** [comment] 2015-03-12 19:30
`for...of` requirements are clearly stated in caveats (http://babeljs.io/docs/usage/caveats/).

With the exception of inline helpers idea, duplicate of https://github.com/babel/babel/issues/935

**Comment by sebmck** [comment] 2015-03-13 02:09
> The documentation does not mention this fact (http://babeljs.io/docs/learn-es6/#iterators-for-of) (no "Support via polyfill" note.)

Yeah it should. A PR would be awesome!

> Make forOf optional and add "Support via polyfill" note to documentation

If you mean make it an optional transformers, that's completely out of the question. There's already notes about the polyfill being required to properly support all iterables and it's clearly listed in the caveats.

> or introduce "Symbol" inline helper to remove dependency on "polyfill."

To be completely spec compliant would mean an ungodly amount of boilerplate inserted into peoples code which isn't something I'm quite willing to do.

**Closed by sebmck** 2015-03-13 02:09 UTC

**Comment by rsms** [comment] 2015-03-13 03:53
All reasonable points. Though having the option to include individual polyfills would be great. Right now it seems the only options is to include _all_ polyfills or _none_. When making a nodejs app, that's no problem (small I/O perf hit probably disappears in the other work such a program would perform) but when making a website the ~70kB additional JavaScript is quite a mouthful. :smile:

**Comment by sebmck** [comment] 2015-03-13 04:00
@rsms I'm shifting everyone over to the runtime transformer, I've already made the helpers modular so they're only required if necessary and hopefully the polyfill will end up being modular too (see babel/ember-cli-babel#24 for more info).
