### ISSUE TITLE
[Bug] plugin-transform-block-scoping: Cannot read property 'bindings' of null

### ISSUE THREAD

**Issue by jamesqo** [babel/babel#7627] opened 2018-03-25 17:48 UTC
Choose one: is this a **bug report** or feature request?

Log:

```
james@LAPTOP-UP0DKQSC ~/code/winescan/Stopwatch
$ yarn test
yarn run v1.5.1
$ jest
FAIL __tests__\App.js
  ● Test suite failed to run

    TypeError: Cannot read property 'bindings' of null

      at Scope.moveBindingTo (node_modules/@babel/traverse/lib/scope/index.js:923:13)
      at BlockScoping.updateScopeInfo (node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:364:17)
      at BlockScoping.run (node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:330:12)
      at PluginPass.BlockStatementSwitchStatementProgram (node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:70:24)
      at newFn (node_modules/@babel/traverse/lib/visitors.js:223:21)
      at NodePath._call (node_modules/@babel/traverse/lib/path/context.js:64:19)
      at NodePath.call (node_modules/@babel/traverse/lib/path/context.js:38:17)
      at NodePath.visit (node_modules/@babel/traverse/lib/path/context.js:99:12)
      at TraversalContext.visitQueue (node_modules/@babel/traverse/lib/context.js:135:18)
      at TraversalContext.visitSingle (node_modules/@babel/traverse/lib/context.js:94:19)
```

### Input Code

```js
import 'react-native';
import React from 'react';
import App from '../App';

// Note: test renderer must be required after react-native.
import renderer from 'react-test-renderer';

it('renders correctly', () => {
  const tree = renderer.create(<App />).toJSON();
  expect(tree).toMatchSnapshot();
});
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": ["react-native"]
}
```

### Possible Solution

I did a bit of manual digging through the code. The problem is that [here](https://github.com/babel/babel/blob/a4795408b47e713aa2635d54197343be77e30f35/packages/babel-plugin-transform-block-scoping/src/index.js#L455), `parentScope` is null. `parentScope` is initialized [here](https://github.com/babel/babel/blob/a4795408b47e713aa2635d54197343be77e30f35/packages/babel-plugin-transform-block-scoping/src/index.js#L442). Over [here](https://github.com/babel/babel/blob/a4795408b47e713aa2635d54197343be77e30f35/packages/babel-plugin-transform-block-scoping/src/index.js#L387), where `updateScopeInfo` was called, we make some checks before calling the method to ensure that the parent is a function/program node.

It seems like the code in the last URL should be changed:

```diff
     // this is a block within a `Function/Program` so we can safely leave it be
-    if (t.isFunction(this.parent) || t.isProgram(this.block)) {
+    if (t.isFunction(this.parent) || t.isProgram(this.parent)) {
```

**Comment by ArtemGovorov** [comment] 2018-04-09 00:49
Here's a one liner to reproduce the issue. 

Running with `7.0.0-beta.44`:

```js
require('@babel/core').transform('let a', { filename: 'test.js', presets: ['react-native'] });
```

produces:
```
./node_modules/@babel/traverse/lib/scope/index.js:964
      scope.bindings[name] = info;
            ^

TypeError: Cannot read property 'bindings' of null
    at Scope.moveBindingTo (./node_modules/@babel/traverse/lib/scope/index.js:964:13)
    at BlockScoping.updateScopeInfo (./node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:364:17)
    at BlockScoping.run (./node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:330:12)
    at PluginPass.BlockStatementSwitchStatementProgram (./node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:70:24)
    at newFn (./node_modules/@babel/traverse/lib/visitors.js:243:21)
    at NodePath._call (./node_modules/@babel/traverse/lib/path/context.js:65:18)
    at NodePath.call (./node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (./node_modules/@babel/traverse/lib/path/context.js:100:12)
    at TraversalContext.visitQueue (./node_modules/@babel/traverse/lib/context.js:144:16)
    at TraversalContext.visitSingle (./node_modules/@babel/traverse/lib/context.js:104:19)
```

**Comment by existentialism** [comment] 2018-04-09 14:15
@ArtemGovorov your stack trace also hints at mixing v7 and v6:

> at Scope.moveBindingTo (./node_modules/**@babel/traverse**/lib/scope/index.js:964:13)

and 

>    at BlockScoping.updateScopeInfo (./node_modules/**babel-plugin-transform-es2015-block-scoping**/lib/index.js:364:17)

(Note the things in bold)

**Comment by Tauka** [comment] 2018-04-25 07:09
@existentialism Hi, I'm also having this issue, I have installed both versions in my `node_modules`, one  is `babel-plugin-transform-es2015-block-scoping` and another `@babel/plugin-transform-es2015-block-scoping`

But for some reason it prefers old plugin, and spits out the same error:
```
TypeError: Cannot read property 'bindings' of null
    at Scope.moveBindingTo (/Users/tauyekel/Documents/webprojects/bilim-media/zhastar-offline-instructor/node_modules/@babel/traverse/lib/scope/index.js:970:13)
    at BlockScoping.updateScopeInfo (/Users/tauyekel/Documents/webprojects/bilim-media/zhastar-offline-instructor/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:364:17)
    at BlockScoping.run (/Users/tauyekel/Documents/webprojects/bilim-media/zhastar-offline-instructor/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:330:12)
    at PluginPass.BlockStatementSwitchStatementProgram (/Users/tauyekel/Documents/webprojects/bilim-media/zhastar-offline-instructor/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:70:24)
    at newFn (/Users/tauyekel/Documents/webprojects/bilim-media/zhastar-offline-instructor/node_modules/@babel/traverse/lib/visitors.js:243:21)
    at NodePath._call (/Users/tauyekel/Documents/webprojects/bilim-media/zhastar-offline-instructor/node_modules/@babel/traverse/lib/path/context.js:65:18)
    at NodePath.call (/Users/tauyekel/Documents/webprojects/bilim-media/zhastar-offline-instructor/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/tauyekel/Documents/webprojects/bilim-media/zhastar-offline-instructor/node_modules/@babel/traverse/lib/path/context.js:100:12)
    at TraversalContext.visitQueue (/Users/tauyekel/Documents/webprojects/bilim-media/zhastar-offline-instructor/node_modules/@babel/traverse/lib/context.js:144:16)
    at TraversalContext.visitSingle (/Users/tauyekel/Documents/webprojects/bilim-media/zhastar-offline-instructor/node_modules/@babel/traverse/lib/context.js:104:19)
```

Is there any way to tell `babel-node` to use new plugin?

.babelrc
```
{
    "presets": ["env"]
}
```

| Dependency | Version |
| ------------ | --------------- |
| @babel/node |  7.0.0-beta.46 |
| @babel/core | 7.0.0-beta.46 |
| @babel/plugin-transform-block-scoping | 7.0.0-beta.46 |

**Comment by existentialism** [comment] 2018-04-25 16:45
@Tauka you'll want to use `@babel/preset-env` (env, which is babel-preset-env will load the old v6 versions)

**Comment by xtuc** [comment] 2018-05-04 15:58
@nicolo-ribaudo do we need to leave this open?

**Comment by PaijoRX** [comment] 2018-07-11 14:37
How to fixing the issue?

**Comment by sxyshirly** [comment] 2018-07-12 05:50
@existentialism Hi, I'm also having this issue and i'm a newer of babel. i feel confused with so many babel deps.
.babelrc 
{
    "presets": ["env"]
}
and the error still exists.
ERROR in ./src/App.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: Cannot read property 'bindings' of null
    at Scope.moveBindingTo (E:\node_modules\@babel\traverse\lib\scope\index.js:869:13)
    at convertBlockScopedToVar (E:\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:139:13)
    at PluginPass.VariableDeclaration (E:\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:26:9)
    at newFn (E:\node_modules\@babel\traverse\lib\visitors.js:193:21)
    at NodePath._call (E:\node_modules\@babel\traverse\lib\path\context.js:53:20)
    at NodePath.call (E:\node_modules\@babel\traverse\lib\path\context.js:40:17)
    at NodePath.visit (E:\node_modules\@babel\traverse\lib\path\context.js:88:12)
    at TraversalContext.visitQueue (E:\node_modules\@babel\traverse\lib\context.js:118:16)
    at TraversalContext.visitMultiple (E:\node_modules\@babel\traverse\lib\context.js:85:17)
    at TraversalContext.visit (E:\node_modules\@babel\traverse\lib\context.js:144:19)
 @ ./index.web.js 1:45-65
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./index.web.js
This issue has been bothering me for a long time, please help me, thank you very much!

**Comment by existentialism** [comment] 2018-07-12 21:49
@sxyshirly hard to tell without more info... but are you mixing babel v6 and v7 packages?

I'm noticing both `@babel/traverse` and `babel-plugin-transform-es2015-block-scoping`.

**Comment by sxyshirly** [comment] 2018-07-13 05:30
@existentialism yeah……I think i'm mixing the version of something. but I don't know how to updata my babel, I‘m totally newer and don't know where to start……. Actually i'm turn my app to h5, i use this guide: https://github.com/necolas/react-native-web/blob/master/packages/website/guides/getting-started.md

I carried out these command：
1. yarn add --dev babel-loader url-loader webpack webpack-cli webpack-dev-server
2. yarn install --dev babel-plugin-react-native-web
and then, error info told me that i didn't have @babel\traverse in my project, so i try to install this dep.
after all this, i carried out  ./node_modules/.bin/webpack-dev-server -d --config ./web/webpack.config.js --inline --hot --colors

at last, i get this issue

**Comment by sneko** [comment] 2018-07-13 20:09
@existentialism Hi! After changing `env` to `@babel/preset-env` I get this error:

```
info Building storybook ...
ERR! Failed to build the storybook
ERR! ./node_modules/@storybook/vue/dist/client/preview/NoPreview.vue?vue&type=style&index=0&lang=css
ERR! Module parse failed: Unexpected token (21:0)
ERR! You may need an appropriate loader to handle this file type.
ERR! |
ERR! |
ERR! | .nopreview_wrapper {
ERR! |   position: fixed;
ERR! |   display: flex;
ERR!  @ ./node_modules/@storybook/vue/dist/client/preview/NoPreview.vue 4:0-68
ERR!  @ ./node_modules/@storybook/vue/dist/client/preview/render.js
ERR!  @ ./node_modules/@storybook/vue/dist/client/preview/index.js
ERR!  @ ./node_modules/@storybook/vue/dist/client/index.js
ERR!  @ ./.storybook/config.js
ERR!  @ multi ./node_modules/@storybook/vue/dist/server/config/polyfills.js ./node_modules/@storybook/vue/dist/server/config/globals.js ./.storybook/config.js
ERR! ./node_modules/@storybook/vue/dist/client/preview/ErrorDisplay.vue?vue&type=style&index=0&lang=css
```

Do you think it's still related to babel?

**Comment by sxyshirly** [comment] 2018-07-19 08:12
I have installed this deps
    "@babel/core": "^7.0.0-beta.38",
    "@babel/node": "^7.0.0-beta.54",
    "@babel/plugin-check-constants": "^7.0.0-beta.38",
    "@babel/plugin-transform-block-scoping": "^7.0.0-beta.54",
    "@babel/preset-env": "^7.0.0-beta.54",
and modified .babelrc
 "presets": ["@babel/preset-env"]
i still get this issue……could anyone tell me why？

**Comment by existentialism** [comment] 2018-07-19 14:04
@sxyshirly you want to ensure all your v7 dependencies are using the exact same beta, so we recommend dropping the `^` and setting `@babel/*` to the same version.

**Comment by sxyshirly** [comment] 2018-07-24 03:37
@existentialism i modified it according to your suggestion：
"dependencies": {
    "antd-mobile": "2.1.10",
    "axios": "^0.18.0",
    "babel-runtime": "^6.26.0",
    "bluebird": "^3.5.1",
    "blueimp-md5": "^2.10.0",
    "crypto-js": "^3.1.9-1",
    "lodash": "^4.17.5",
    "lottie-react-native": "2.3.2",
    "moment": "^2.21.0",
    "prop-types": "^15.6.1",
    "react": "^16.4.1",
    "react-art": "^16.4.1",
    "react-dom": "^16.4.1",
    "react-native": "0.54.4",
    "react-native-code-push": "^5.3.2",
    "react-native-device-info": "^0.21.4",
    "react-native-fetch-blob": "git://github.com/wkh237/react-native-fetch-blob.git#0.10.9",
    "react-native-image-picker": "^0.26.7",
    "react-native-keyboard-aware-scroll-view": "^0.5.0",
    "react-native-svg": "^6.3.1",
    "react-native-web": "^0.8.9",
    "react-native-zip-archive": "^2.2.2",
    "react-navigation": "^1.5.8",
    "react-redux": "^5.0.7",
    "redux": "^3.7.2",
    "redux-saga": "^0.16.0",
    "reselect": "^3.0.1"
  },
  "devDependencies": {
    "@babel/core": "7.0.0-beta.38",
    "@babel/plugin-check-constants": "7.0.0-beta.38",
    "@babel/preset-env": "7.0.0-beta.38",
    "babel-cli": "^6.26.0",
    "babel-core": "7.0.0-bridge.0",
    "babel-eslint": "^8.2.1",
    "babel-jest": "^22.4.3",
    "babel-loader": "^7.1.5",
    "babel-plugin-import": "^1.6.3",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-flow": "^6.23.0",
    "babel-preset-react-native": "4.0.0",
    "babel-preset-stage-2": "^6.24.1",
    "commander": "^2.13.0",
    "eslint": "^4.16.0",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-plugin-filenames": "^1.2.0",
    "eslint-plugin-flowtype": "^2.42.0",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-react": "^7.6.1",
    "flow-bin": "^0.64.0",
    "jest": "22.1.4",
    "react-test-renderer": "16.2.0",
    "redux-logger": "^3.0.6",
    "url-loader": "^1.0.1",
    "webpack": "^4.16.2",
    "webpack-cli": "^3.1.0",
    "webpack-dev-server": "^3.1.5"
  },
  "jest": {
    "preset": "react-native-web"
  }
}
but i got a new bug……
ERROR in ./index.web.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: t(...).cloneNode is not a function
    at populatePlaceholders (E:\node_modules\@babel\core\node_modules\@babel\template\lib\populate.js:21:19)
    at arg (E:\node_modules\@babel\core\node_modules\@babel\template\lib\literal.js:37:53)
    at Function.ast (E:\node_modules\@babel\core\node_modules\@babel\template\lib\builder.js:56:29)
    at Object.helpers.interopRequireDefault (E:\node_modules\@babel\core\node_modules\@babel\helpers\lib\helpers.js:558:70)
    at fn (E:\node_modules\@babel\core\node_modules\@babel\helpers\lib\index.js:237:45)
    at loadHelper (E:\node_modules\@babel\core\node_modules\@babel\helpers\lib\index.js:240:40)
    at Object.getDependencies (E:\node_modules\@babel\core\node_modules\@babel\helpers\lib\index.js:263:21)
    at File.addHelper (E:\node_modules\@babel\core\lib\transformation\file\file.js:135:34)
    at PluginPass.addHelper (E:\node_modules\@babel\core\lib\transformation\plugin-pass.js:30:22)
    at PluginPass.exit (E:\node_modules\babel-plugin-transform-es2015-modules-commonjs\lib\index.js:513:119)
 @ multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-server.js ./index.web.js main[2]

**Comment by sxyshirly** [comment] 2018-07-24 13:47
@existentialism 
I have tried to modified my package.json, but the problem is still existing：
{

  "dependencies": {
    "antd-mobile": "2.1.10",
    "axios": "^0.18.0",
    "babel-core": "7.0.0-bridge.0",
    "babel-runtime": "^6.26.0",
    "bluebird": "^3.5.1",
    "blueimp-md5": "^2.10.0",
    "crypto-js": "^3.1.9-1",
    "lodash": "^4.17.5",
    "lottie-react-native": "2.3.2",
    "moment": "^2.21.0",
    "prop-types": "^15.6.1",
    "react": "^16.4.1",
    "react-art": "^16.4.1",
    "react-dom": "^16.4.1",
    "react-native": "0.54.4",
    "react-native-code-push": "^5.3.2",
    "react-native-device-info": "^0.21.4",
    "react-native-fetch-blob": "git://github.com/wkh237/react-native-fetch-blob.git#0.10.9",
    "react-native-image-picker": "^0.26.7",
    "react-native-keyboard-aware-scroll-view": "^0.5.0",
    "react-native-svg": "^6.3.1",
    "react-native-web": "^0.8.9",
    "react-native-zip-archive": "^2.2.2",
    "react-navigation": "^1.5.8",
    "react-redux": "^5.0.7",
    "redux": "^3.7.2",
    "redux-saga": "^0.16.0",
    "reselect": "^3.0.1"
  },
  "devDependencies": {
    "@babel/cli": "7.0.0-beta.38",
    "@babel/core": "7.0.0-beta.38",
    "@babel/node": "7.0.0-beta.38",
    "@babel/plugin-check-constants": "7.0.0-beta.38",
    "@babel/plugin-transform-block-scoping": "7.0.0-beta.38",
    "@babel/plugin-transform-runtime": "7.0.0-beta.38",
    "@babel/preset-env": "7.0.0-beta.38",
    "@babel/preset-stage-2": "7.0.0-beta.38",
    "babel-eslint": "^8.2.1",
    "babel-jest": "^22.4.3",
    "babel-loader": "7.0.0",
    "babel-plugin-import": "^1.6.3",
    "babel-plugin-react-native-web": "0.8.8",
    "babel-preset-flow": "7.0.0-beta.3",
    "babel-preset-react-native": "4.0.0",
    "commander": "^2.13.0",
    "eslint": "^4.16.0",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-plugin-filenames": "^1.2.0",
    "eslint-plugin-flowtype": "^2.42.0",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-react": "^7.6.1",
    "flow-bin": "^0.64.0",
    "jest": "22.1.4",
    "react-test-renderer": "16.2.0",
    "redux-logger": "^3.0.6",
    "url-loader": "^1.0.1",
    "webpack": "^4.16.2",
    "webpack-cli": "^3.1.0",
    "webpack-dev-server": "^3.1.5"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by existentialism** [comment] 2018-07-24 14:13
@sxyshirly with react-native, you have to lock/match your babel dependencies to the same version that its preset uses. `babel-preset-react-native@4` [uses babel v6](https://unpkg.com/babel-preset-react-native@4.0.0/package.json)... so if you want to use babel 7, you will need to upgrade that first, and then, as I mentioned, make sure to use the _exact_ same beta versions for other `@babel/*` deps.

**Comment by sxyshirly** [comment] 2018-07-24 15:55
@existentialism a new issue happened：

ERROR in ./index.web.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] E:\index.web.js: Requires Babel "^7.0.0-beta.41", but was loaded with "7.0.0-beta.38". You'll need to update your @babel/core version. (While processing: "E:\\node_modules\\babel-preset-react-native\\index.js$0")
    at throwVersionError (E:\node_modules\@babel\helper-plugin-utils\lib\index.js:63:11)
    at Object.assertVersion (E:\node_modules\@babel\helper-plugin-utils\lib\index.js:13:11)
    at _default (E:\node_modules\babel-preset-react-native\node_modules\@babel\plugin-transform-block-scoping\lib\index.js:55:7)
    at E:\node_modules\@babel\helper-plugin-utils\lib\index.js:19:12
    at E:\node_modules\@babel\core\lib\config\index.js:167:14
    at cachedFunction (E:\node_modules\@babel\core\lib\config\caching.js:40:17)
    at loadPluginDescriptor (E:\node_modules\@babel\core\lib\config\index.js:202:28)
    at E:\node_modules\@babel\core\lib\config\index.js:59:16
    at Array.map (<anonymous>)
    at recurseDescriptors (E:\node_modules\@babel\core\lib\config\index.js:58:36)
    at recurseDescriptors (E:\node_modules\@babel\core\lib\config\index.js:92:27)
    at loadConfig (E:\node_modules\@babel\core\lib\config\index.js:108:6)
    at transformSync (E:\node_modules\@babel\core\lib\transform-sync.js:13:36)
    at Object.transform (E:\node_modules\@babel\core\lib\transform.js:20:65)
    at transpile (E:\node_modules\babel-loader\lib\index.js:48:20)
    at E:\node_modules\babel-loader\lib\fs-cache.js:118:18
    at ReadFileContext.callback (E:\node_modules\babel-loader\lib\fs-cache.js:31:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:434:13)
 @ multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-server.js ./index.web.js main[2]

can I solve this problem without update  @babel/core？this is my index.web.js, why does it need Babel "^7.0.0-beta.41"？

// index.web.js
import { AppRegistry } from 'react-native';
import wallet from './src/app';
// register the app
AppRegistry.registerComponent('wallet', () => wallet);

**Comment by existentialism** [comment] 2018-07-24 16:00
@sxyshirly can you double check that you're using _exact_ (i.e. `7.0.0-beta.41`, not `^7.0.0-beta.41`) versions?

What version of `babel-preset-react-native` are you using? If it's 5.0.2, then you will want _all_ of your `@babel/*` deps to be `7.0.0-beta.47`.

**Comment by LuuLinhSon** [comment] 2018-07-25 04:19
@existentialism I have followed you but the problem always happens

backgage.json

"@babel/core": "7.0.0-beta.54",
    "@babel/plugin-transform-react-jsx": "7.0.0-beta.54",
    "@babel/preset-env": "7.0.0-beta.54",
    "@babel/preset-flow": "7.0.0-beta.54",
    "@babel/preset-react": "7.0.0-beta.54",
    "babel-core": "7.0.0-0",
    "babel-eslint": "^8.2.6",
    "babel-jest": "^23.4.0",
    "babel-plugin-add-module-exports": "^0.2.1",
    "babel-plugin-flow-react-proptypes": "^24.0.1",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "babel-preset-flow": "^7.0.0-beta.3",
    "babel-preset-jest": "^23.2.0",
    "babel-preset-react": "^7.0.0-beta.3",
    "babel-preset-react-native": "^5.0.2",
    "babel-preset-react-native-stage-0": "^1.0.1",
    "babel-preset-react-native-syntax": "^1.0.0",
    "enzyme": "^3.3.0",
    "enzyme-adapter-react-16": "^1.1.1",
    "eslint-plugin-flowtype": "^2.50.0",
    "husky": "^0.14.3",
    "identity-obj-proxy": "^3.0.0",
    "jest": "^23.4.1",
    "jest-enzyme": "^6.0.2",
    "lint-staged": "^7.2.0",
    "prettier": "^1.13.7",
    "react-addons-test-utils": "^15.6.2",
    "react-dom": "^16.4.1",
    "react-native-bundle-visualizer": "^1.3.0",
    "react-test-renderer": "^16.4.1",
    "snazzy": "^7.1.1",
    "standard": "^11.0.1"
  },
  "jest": {
    "preset": "react-native",
    "testMatch": [
      "<rootDir>/__tests__/**/*.js",
      "**/?(*.)(spec|test).js?(x)"
    ],
    "testPathIgnorePatterns": [
      "/node_modules/",
      "/node_modules/bugsnag-react-native",
      "/node_modules/rn-fetch-blob",
      "/node_modules/babel-preset-react-native",
      "/node_modules/react-native-keyboard-aware-scroll-view",
      "/node_modules/react-native-system-setting"
    ],
    "transformIgnorePatterns": [
      "node_modules/(?!react-native).+\\.js$",
      "node_modules/(?!(jest-)?react-native|rn-fetch-blob|redux-saga|tipsi-stripe|react-native-system-setting|native-base|react-native-keyboard-aware-scroll-view|react-navigation|bugsnag-react-native|static-container|native-base-shoutem-theme|@shoutem/animation|@shoutem/ui|tcomb-form-native|react-native-branch)",
      "/node_modules/(?!native-base)/"
    ],
    "globals": {
      "__DEV__": true
    },
    "transform": {
      "^.+\\.js$": "babel-jest",
      "^.+\\.jsx?$": "babel-jest"
    },
    "setupFiles": [
      "<rootDir>/__mocks__/branch.mock.js",
      "./node_modules/appcenter/test/AppCenterMock.js",
      "./node_modules/appcenter-crashes/test/AppCenterCrashesMock.js",
      "./node_modules/appcenter-analytics/test/AppCenterAnalyticsMock.js",
      "<rootDir>/node_modules/appcenter/test/AppCenterMock.js",
      "<rootDir>/node_modules/appcenter-crashes/test/AppCenterCrashesMock.js",
      "<rootDir>/node_modules/appcenter-analytics/test/AppCenterAnalyticsMock.js"
    ]
  },


**.babelrc**

{
  "sourceMaps": true,
  "presets": [
    "react-native", "flow",
    "@babel/preset-env",
    "@babel/preset-react"
  ],
  "env": {
    "production": {
      "plugins": ["transform-remove-console"]
    }
  }
}


**Error**
`Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    SyntaxError: /Users/macbook/Projects/noddier-mobile/node_modules/react-native/Libraries/Components/View/View.js: Unexpected token (23:12)

      21 | const requireNativeComponent = require('requireNativeComponent');
      22 |
    > 23 | import type {ViewProps} from 'ViewPropTypes';
         |             ^
      24 | import type {ViewChildContext} from 'ViewContext';
      25 |
      26 | export type Props = ViewProps;

      at Parser.raise (node_modules/@babel/parser/lib/index.js:3898:15)
      at Parser.unexpected (node_modules/@babel/parser/lib/index.js:5227:16)
      at Parser.expectContextual (node_modules/@babel/parser/lib/index.js:5195:41)
      at Parser.parseImport (node_modules/@babel/parser/lib/index.js:8379:12)
      at Parser.parseStatementContent (node_modules/@babel/parser/lib/index.js:7201:27)
      at Parser.parseStatement (node_modules/@babel/parser/lib/index.js:7120:17)
      at Parser.parseBlockOrModuleBlockBody (node_modules/@babel/parser/lib/index.js:7671:23)
      at Parser.parseBlockBody (node_modules/@babel/parser/lib/index.js:7658:10)
      at Parser.parseTopLevel (node_modules/@babel/parser/lib/index.js:7085:10)
      at Parser.parse (node_modules/@babel/parser/lib/index.js:8471:17)`

**Comment by existentialism** [comment] 2018-07-30 03:50
@LuuLinhSon

Have you tried switching "flow" in the presets section of your .babelrc to "@babel/preset-flow"?

You also have some redundant deps in your package.json (babel-preset-flow and @babel/preset-flow for instance).

**Comment by LuuLinhSon** [comment] 2018-07-31 07:49
Thank you I corrected the previous error. However, there is a new error

`Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel. (While processing preset: "/Users/macbook/Projects/noddier-mobile/node_modules/@babel/preset-flow/lib/index.js")`

**Comment by sxyshirly** [comment] 2018-08-02 01:31
@existentialism Thanks for your help! 
I have solved this issue a few days ago, and I can finally link to github today……
this is my suggestions:
1. Replace babel-preset-es2015 with @babel/preset-env
2. Try to update all of your babel plugins to babel 7 and make sure they have the same version 
3. If you used babel-preset-react-native, try to update your plugins to 7.0.0-beta.47
4. If you have some problem with babel-core@7.X.X, you can try to install babel-core@7.0.0-bridge.0
Thanks for all of your help!

**Comment by steinhaug** [comment] 2018-09-08 08:51
I am reading all this and I am trying to understand all the versions, but I can't seem to figure this correctly out. I installed babel like this:

```
# windows system
$ node -v
v8.11.1

$ npm -v
5.6.0

$ gulp -v
[10:48:28] CLI version 2.0.1
[10:48:28] Local version 4.0.0

# Babel 7 install
npm install --save-dev gulp-babel@next @babel/core
```

And this is what I got as error, same as the other. How exactly was I to fix this again?

```
TypeError: Cannot read property 'bindings' of null
    at Scope.moveBindingTo (D:\htdocs\easywebshop.no\node_modules\@babel\traverse\lib\scope\index.js:867:13)
    at BlockScoping.updateScopeInfo (D:\htdocs\easywebshop.no\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:364:17)
    at BlockScoping.run (D:\htdocs\easywebshop.no\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:330:12)
    at PluginPass.BlockStatementSwitchStatementProgram (D:\htdocs\easywebshop.no\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:70:24)
    at newFn (D:\htdocs\easywebshop.no\node_modules\@babel\traverse\lib\visitors.js:193:21)
    at NodePath._call (D:\htdocs\easywebshop.no\node_modules\@babel\traverse\lib\path\context.js:53:20)
    at NodePath.call (D:\htdocs\easywebshop.no\node_modules\@babel\traverse\lib\path\context.js:40:17)
    at NodePath.visit (D:\htdocs\easywebshop.no\node_modules\@babel\traverse\lib\path\context.js:88:12)
    at TraversalContext.visitQueue (D:\htdocs\easywebshop.no\node_modules\@babel\traverse\lib\context.js:118:16)
    at TraversalContext.visitSingle (D:\htdocs\easywebshop.no\node_modules\@babel\traverse\lib\context.js:90:19)

```

Not sure what I was doing I tried this:

```
npx nls why babel-plugin-transform-es2015-block-scoping
npx: installerte 1 på 2.29s
Path must be a string. Received undefined
npx: installerte 8 på 7.953s
C:\Users\PC\AppData\Roaming\npm-cache\_npx\23924\node_modules\nls\lib\nls

  Who required babel-plugin-transform-es2015-block-scoping:

  easywebshop.no > babel-preset-env > babel-plugin-transform-es2015-block-scoping@6.26.0

```

My .babelrc is:
```
{
  "presets": ["env"]
}
```

**Comment by nicolo-ribaudo** [comment] 2018-09-08 10:46
You should install `@babel/preset-env` and use it instead of `env`, because you are using Babel 7.
Also, you should replace `babel-cli` with `@babel/cli`.

**Comment by aligenc** [comment] 2018-12-05 06:48
the default react-native 0.57.7 version is creationg project.json file like this: 

`{
  "name": "ReactTestv057",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.6.1",
    "react-native": "0.57.7"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.50.0",
    "react-test-renderer": "16.6.1"
  },
  "jest": {
    "preset": "react-native"
  }
}`

And the .babelrc file is: 

`{
  "presets": ["module:metro-react-native-babel-preset"]
}
`
After setting babel like these, i fixed up problem.

**Comment by romenkova** [comment] 2019-05-15 13:50
I had this problem because of `babel-plugin-transform-es2015-block-scoping`. 
`npm ls  babel-plugin-transform-es2015-block-scoping`  -  info what package using this, in my case it was old version of` react-scripts`. Updating `react-scripts` solved the probem.

**Comment by nicolo-ribaudo** [comment] 2019-05-15 15:37
I'm closing this issue, since for everyone it was caused by mixing Babel 6 and 7.

**Closed by nicolo-ribaudo** 2019-05-15 15:37 UTC
Labels: i: bug
