### ISSUE TITLE
transform-class-properties with class extends not working

### ISSUE THREAD

**Issue by mcschnoo** [babel/babel#2885] opened 2015-11-06 22:49 UTC
export default class MyComponent {
        name = "test"
    }

works

    export default class MyComponent extends React.Component {
        name = "test"
    }

does not work
`'super.*' is not allowed before super()`

v6.1.2, .babelrc:

    {
        "presets": ["es2015", "stage-0", "react"]
    }

**Comment by GGAlanSmithee** [comment] 2015-11-06 23:53
Dupe of #2774, #2809 etc?

**Comment by loganfsmyth** [comment] 2015-11-07 00:43
Duplicate of https://github.com/babel/babel/issues/2775

**Closed by loganfsmyth** 2015-11-07 00:43 UTC
