### ISSUE TITLE
Unresolvable imports should throw a SyntaxError

### ISSUE THREAD

**Issue by invernizzie** [babel/babel#2599] opened 2015-10-26 20:05 UTC
From [ModuleDeclarationInstantiation( )](http://www.ecma-international.org/ecma-262/6.0/#sec-moduledeclarationinstantiation), step 12.d.iii., parsing **import.js** below should throw a SyntaxError.

**export.js**
```
export {definedExport} from './another-module'
```

**import.js**
```
import {
  undefinedExport,
  definedExport
} from './export'
```

However, it currently doesn't.

If someone confirms this issue, I might take a stab at a fix.

**Comment by lapanoid** [comment] 2015-10-26 20:36
I have the same thing http://stackoverflow.com/questions/33350209/how-to-have-static-error-when-importing-undefined

**Comment by thejameskyle** [comment] 2015-10-26 20:45
Duplicate of #2486

**Closed by thejameskyle** 2015-10-26 20:45 UTC
