### ISSUE TITLE
Cannot read property 'end' of null

### ISSUE THREAD

**Issue by LinusU** [babel/babel#8028] opened 2018-05-24 11:36 UTC
## Bug Report

**Current Behavior**

I'm getting the following error when trying to minify a large file outputted by TypeScript.

```
TypeError: dist/main.js: Cannot read property 'end' of null
    at _evaluate (node_modules/babel-traverse/lib/path/evaluation.js:160:58)
    at evaluate (node_modules/babel-traverse/lib/path/evaluation.js:65:17)
    at NodePath.evaluate (node_modules/babel-traverse/lib/path/evaluation.js:41:15)
    at evaluateIdentifier (node_modules/babel-helper-evaluate-path/lib/index.js:127:15)
    at evaluate (node_modules/babel-helper-evaluate-path/lib/index.js:19:12)
    at PluginPass.Expression (node_modules/babel-plugin-minify-constant-folding/lib/index.js:165:21)
    at PluginPass.newFn (node_modules/babel-traverse/lib/visitors.js:318:17)
    at newFn (node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (node_modules/babel-traverse/lib/path/context.js:48:17)
```

I've tracked it down to #4875 which introduces an if statement that compares `path.node.start` with `binding.path.node.end`. Note that one side is comparing a property on `path`, and the other on `binding.path`.

Changing the right-hand side to `path.node.end` seems to fix the issue.

**Input Code**
Unfortunately, I discovered this in a closed source repo...

**Expected behavior/code**
I expected the file to be minified and translated to ES2015.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": ["es2015", "minify"],
  "comments": false
}
```

```sh
babel dist/main.js --out-file dist/main.min.js
```

**Environment**
- Babel version(s): 6.26.0 (babel-core 6.26.0)
- Node/npm version: Node v10.0.0, npm v5.6.0
- OS: macOS 10.13.4
- Monorepo: no
- How you are using Babel: `cli`

**Possible Solution**
```diff
diff --git a/node_modules/babel-traverse/lib/path/evaluation.js b/node_modules/babel-traverse/lib/path/evaluation.js
index d608418..c05b833 100644
--- a/node_modules/babel-traverse/lib/path/evaluation.js
+++ b/node_modules/babel-traverse/lib/path/evaluation.js
@@ -156,7 +156,7 @@ function evaluate() {
         return deopt(binding.path);
       }
 
-      if (binding && path.node.start < binding.path.node.end) {
+      if (binding && path.node.start < path.node.end) {
         return deopt(binding.path);
       }
 
```

**Comment by LinusU** [comment] 2018-05-24 11:38
ping @boopathi, do you remember if having `path` vs. `binding.path` was intentional? ☺️

**Comment by boopathi** [comment] 2018-05-25 20:11
It should be `binding.path` as we are checking ref location vs the binding location.

I suppose this error is happening because the binding is removed(maybe?) that the `binding.path.node` is null.

**Comment by LinusU** [comment] 2018-05-25 23:07
I see... I was almost thinking that. Would it help to get the input file? It's quite large though since my build pipeline is just using webpack to produce a `main.js`, and then using babel only for minification and es5-ifying that large bundle.

Is there anything else I could do to try and reduce a minimal test case? 🤔

**Comment by tehkaiyu** [comment] 2018-10-13 08:27
I was running into the same issue but I managed to fix it by changing my `babel-preset-minify` version from `0.5.0` -> `0.3.0`

**Comment by zgr024** [comment] 2018-10-20 04:09
Same issue. Fixed by downgrading to 0.3.0 as well. Any update on a timeline for a fix? It's been a few months since any of the contributors commented on this issue.

**Comment by nicolo-ribaudo** [comment] 2018-10-20 07:07
Could you share an example to reproduce the bug?

**Comment by zgr024** [comment] 2018-10-21 16:34
.babelrc
```
{
  "presets": ["env", "stage-2"],
  "env": {
    "production": {
      "presets": ["minify"]
    }
  }
}
```

package.json
```
...
"scripts": {
    "build": "babel src -d build --source-maps inline",
    "build:dist": "NODE_ENV=production babel src -d dist",
    ...
},
"dependencies": {
    "@babel/core": "^7.0.0-beta.47",
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.3",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-minify": "^0.5.0",
    "babel-preset-stage-2": "^6.24.1",
    "babel-register": "^6.26.0"
    ...
}
```

$ npm run builld:dist

**Comment by liuxingbaoyu** [comment] 2023-11-11 13:44
Because this issue is out of date, I will close it.

**Closed by liuxingbaoyu** 2023-11-11 13:44 UTC
