### ISSUE TITLE
Babel 5.0 doc site?

### ISSUE THREAD

**Issue by eranimo** [babel/babel#2689] opened 2015-10-30 17:20 UTC
My organization is unable to upgrade to Babel 6 for a while. It would be nice to have the old docsite up at a different url so that people using older versions of Babel can make use of the docs.

**Comment by sebmck** [comment] 2015-10-30 17:22
See the README:

> For documentation and website issues please visit the <a href="https://github.com/babel/babel.github.io">babel.github.io</a> repo.

**Comment by sebmck** [comment] 2015-10-30 17:22
Also a duplicate of #2680.

**Closed by sebmck** 2015-10-30 17:22 UTC
