### ISSUE TITLE
Symbol used for the helper _instanceof even if the polyfill is not here

### ISSUE THREAD

**Issue by johanlajili** [babel/babel#2849] opened 2015-11-05 18:09 UTC
Hi everyone. I have a babel application, use to work fine, but ever since I updated to 6.0 it had had an issue. On android 4.2, my application was not working. I lookup and found the culprit, my line
```javascript 
if (assetToPreload instanceof Image) {
```
was replaced by a call to this function
```javascript 
function n(t, e) {
    return null != e && e[Symbol.hasInstance] ? e[Symbol.hasInstance](t) : t instanceof e
 }
```
namely the _instanceof helper in helpers.js
```javascript
var _instanceof = _babelTemplate2["default"]("\n  (function (left, right) {\n    if (right != null && right[Symbol.hasInstance]) {\n      return right[Symbol.hasInstance](left);\n    } else {\n      return left instanceof right;\n    }\n  });\n");
```

but you can see that this helper assume that Symbol exists, which might not be the case if you don't have the polyfill and are not on a recent browser.
replacing the helper by 
```javascript
var _instanceof = _babelTemplate2["default"]("\n  (function (left, right) {\n    if (right != null && window.Symbol && right[Symbol.hasInstance]) {\n      return right[Symbol.hasInstance](left);\n    } else {\n      return left instanceof right;\n    }\n  });\n");]
```
does the trick, but I'm don't have time to see the procedure to make a pull request.
Have a nice day.

**Comment by sebmck** [comment] 2015-11-07 00:55
Duplicate of #2745 and #2784.

**Closed by sebmck** 2015-11-07 00:55 UTC
