### ISSUE TITLE
@babel/preset-typescript not work in "overrides" of babel.config.js

### ISSUE THREAD

**Issue by zlv-thisF** [babel/babel#9843] opened 2019-04-10 07:21 UTC
## Bug Report

**Current Behavior**
![image](https://user-images.githubusercontent.com/24266156/55858256-cdac6380-5ba1-11e9-973d-3b733c5fca99.png)
write my webapck.config.babel.js in ES6, the @babe/preset-env i set  { **modules: false** } for tree shaking by webpack, so i use overrides option for commonjs support. In fact, "@babel/preset-env" in preset of overrides work just well as picture above, webpack run as expected. But if i add "@babel/preset-typescript" and **import some ts file** (eg. try add and test my self webpack plugin written in typescript ), webpack.config.babel.js cannot find my ts plugin module.

**Input Code**
babel.config.babel.js
```jsx
module.exports = {
  plugins: [
    ["babel-plugin-lodash"],
    ["@babel/plugin-syntax-dynamic-import"],
    ["@babel/plugin-proposal-decorators", { legacy: true }],
    ["@babel/plugin-proposal-class-properties", { loose: true }],
    ["babel-plugin-import", { libraryName: "antd", style: true }],
  ],
  presets: [
    ["@babel/preset-env", { useBuiltIns: "usage", modules: false }],
    ["@babel/preset-react"],
    ["@babel/preset-typescript"],
  ],
  overrides: [
    {
      test: ["./webpack/**/*"],
      presets: ["@babel/preset-env", "@babel/preset-typescript"],
    },
    {
      test: ["./plugins/**/*"],
      presets: ["@babel/preset-env", "@babel/preset-typescript"],
    },
  ],
};
```

**Expected behavior/code**
when my webpack.babel.babel.js import ts module, "@babel/preset-typescript" in overrides option of babel.config.js can work well.

**Environment**
- Babel version(s): 7.3.4
- Node/npm version: [e.g. Node 10.15.3/npm 6.4.1]
- OS: maxOS 10.14.2
- How you are using Babel: [`register`, `loader`, `core`, `@babel/preset-env`, `@babel/preset-typescript`]

**Additional context/Screenshots**
import my ts webpack plugin as below:
![image](https://user-images.githubusercontent.com/24266156/55859052-c8501880-5ba3-11e9-8209-332cefc0da7f.png)
![image](https://user-images.githubusercontent.com/24266156/55859065-d1d98080-5ba3-11e9-9155-305f31d8bcaf.png)
![image](https://user-images.githubusercontent.com/24266156/55859404-95f2eb00-5ba4-11e9-95db-7da5a5c988a5.png)

is there anything i missing or is it a bug ?

**Comment by nicolo-ribaudo** [comment] 2019-04-10 07:31
That error doesn't seem to be thrown by Babel. Did you configure webpack to also look for `.ts` extensions when resolving file names?

**Comment by zlv-thisF** [comment] 2019-04-10 07:51
@nicolo-ribaudo   thx for help!, i have resolve's alias in my webpack config;
![image](https://user-images.githubusercontent.com/24266156/55860908-d4d67000-5ba7-11e9-8dfe-5be76fb47b2a.png)

i write my ts plugin and export , but i dont have d.ts for my ts module,  error probably comes from here ?  i am new to TS..

**Comment by nicolo-ribaudo** [comment] 2019-04-10 07:56
> but i dont have d.ts for my ts module, error probably comes from here ?

No, .d.ts files aren't used by Babel/webpack.

Does it work if you do `"import SkeletonPlugin from "../plugins/skeletonPlugin.ts"`? (Or with the correct extension)

**Comment by nicolo-ribaudo** [comment] 2019-04-10 08:05
Oh, I initially misunderstood the issue.
What is the full stack trace of the error?
Does it work if you explicitly add `.ts` to the import? I think that it throws because `node` doesn't add the `.ts` extension when loading files.

**Comment by zlv-thisF** [comment] 2019-04-10 09:06
@nicolo-ribaudo  really sorry, i was busy something else;
right now i  add '.ts' to the import,  seems work , webpack **find my module**  and enter in to my plugin , however babel seems not compile my ts plugin file, cus my plugins throw error like below:
![image](https://user-images.githubusercontent.com/24266156/55866416-e2452780-5bb2-11e9-8432-736bb20de0d4.png)


![image](https://user-images.githubusercontent.com/24266156/55866396-db1e1980-5bb2-11e9-8496-ff068b4b43c1.png)

![image](https://user-images.githubusercontent.com/24266156/55866440-f0934380-5bb2-11e9-9df7-6cecba1a1212.png)

**Comment by nicolo-ribaudo** [comment] 2019-04-10 09:52
Could you create a small repository I can download to test the bug?

**Comment by zlv-thisF** [comment] 2019-04-10 12:13
@nicolo-ribaudo  https://github.com/zlv-thisF/test_plugin.git
here i write a demo can reproduce my issue,

**Comment by nicolo-ribaudo** [comment] 2019-04-10 16:52
The problem is that, since webpack sees that your config is a JS file, it will not tell Babel to also hook into the `require`ing of `.ts` files.

You have two options:
1) (easy) Rename `webpack.config.babel.js` to `webpack.config.babel.ts`
2) (robust) Create a JS file to manually tell Babel to run when importing ts files:
    - ```js
      // babel-entry.js
      require("@babel/register")({ extensions: [".ts"] });
      ```
    - Add as the _first_ line in your webpack config
      ```js
      import "./babel-entry.js";
      ```

**Comment by zlv-thisF** [comment] 2019-04-11 01:49
@nicolo-ribaudo  wow!  i will try that!!!!
Thanks for your patient and help. ~

**Closed** 2019-05-14 20:33 UTC
Labels: i: question
