### ISSUE TITLE
`class A extends () => {} {}` should not parse

### ISSUE THREAD

**Issue by cpojer** [babel/babel#2393] opened 2015-09-16 22:45 UTC
An arrow function as part of an extends clause requires parenthesis. This was changed before ES2015 became final, see http://wiki.ecmascript.org/doku.php?id=harmony%3Aspecification_drafts#january_20_2014_draft_rev_22

@gabelevi summarized the issue internally at FB:
1) After "extends" there is a LeftHandSideExpression: http://www.ecma-international.org/ecma-262/6.0/#sec-class-definitions
2) LeftHandSideExpression is a CallExpression or a NewExpression: http://www.ecma-international.org/ecma-262/6.0/#sec-left-hand-side-expressions
3) ArrowFunction is an AssignmentExpression: http://www.ecma-international.org/ecma-262/6.0/#sec-assignment-operators

**Comment by sebmck** [comment] 2015-09-16 22:55
Related (possible duplicate) of #2154 and #2118.

**Comment by michaelficarra** [comment] 2015-09-24 18:06
Agreed, this is a duplicate of #2154.

**Closed** 2015-09-24 18:09 UTC
Labels: bug, parser
