### ISSUE TITLE
@babel/plugin-transform-react-jsx: d(...) is not a function

### ISSUE THREAD

**Issue by Skn0tt** [babel/babel#12631] opened 2021-01-14 15:59 UTC
## Bug Report

I'm currently investigating https://github.com/blitz-js/babel-plugin-superjson-next/issues/29.
It occurs since Next.js updated @babel/plugin-transform-react-jsx to 7.12.10.

```
TypeError: /[...]/babel-plugin-superjson-repro/pages/index.js: d(...) is not a function
```

It's caused by this code:

```ts
export function getServerSideProps() {
  return {
    props: {
      date: new Date(),
    },
  };
}

export default function Home(props) {
  return <div>hello world {props.date instanceof Date ? "true" : "false"}</div>;
}
```

After being passed through `babel-plugin-superjson-next`, it looks like this:

```ts
import { withSuperJSONPage as _withSuperJSONPage } from 'babel-plugin-superjson-next/tools';
import { withSuperJSONProps as _withSuperJSONProps } from 'babel-plugin-superjson-next/tools';

export const getServerSideProps = _withSuperJSONProps(
  function getServerSideProps() {
    return {
      props: {
         date: new Date(),
      },
    };
  }
);

function Page({ products }) {
  return <div>hello world {props.date instanceof Date ? "true" : "false"}</div>;
}

export default _withSuperJSONPage(Page);
```

Interestingly, the error does not occur if you move the `export default` onto it's own line: https://github.com/blitz-js/babel-plugin-superjson-next/issues/29#issuecomment-760224611

- [x] I would like to work on a fix! (provided you give me a hint in the right direction, and this is indeed a bug on Babel's side)

**Current behavior**

Repro: [Skn0tt/babel-plugin-superjson-next-10.0.5-repro](https://github.com/Skn0tt/babel-plugin-superjson-next-10.0.5-repro)

> (FYI: Since Next bundles Babel, linking a local Babel package for debugging won't work.)

**Expected behavior**
I expected it not to crash.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**

Next.js 10.0.5, babel-plugin-superjson-next.

**Environment**

- Babel version(s): 7.12.10
- Node/npm version: occurs on multiple versions
- OS: occurs on multiple platforms
- Monorepo: no
- How you are using Babel: `webpack` / `next`

**Additional context**
I was able to track the error down to this line:

https://github.com/babel/babel/blob/6e9a174e7f70180a7ae7b7c01a2c988849666cf0/packages/babel-plugin-transform-react-jsx/src/create-plugin.js#L277

In my case, `name` is `"jsxs"`. So it tries to access `id/jsxs` from the plugin pass, which should have been defined here:

https://github.com/babel/babel/blob/6e9a174e7f70180a7ae7b7c01a2c988849666cf0/packages/babel-plugin-transform-react-jsx/src/create-plugin.js#L205

Since this is in `Program#enter`, this should have run before, but it didn't.

I'm out of ideas and would very much appreciate your thoughts ☺️

**Comment by JLHwung** [comment] 2021-01-14 20:53
@Skn0tt Thanks for the reproduction repo. That helps a lot!

The error is thrown from

https://github.com/babel/babel/blob/fec4a132adbddea725b2efdb5ac8ea948af3acf5/packages/babel-plugin-transform-react-jsx/src/create-plugin.js#L277

where `get` refers to `pass.get("@babel/plugin-react-jsx/id" + name)`.

It seems to be a duplicate of https://github.com/babel/babel/issues/12478, which has been fixed in `v7.12.11`.

https://github.com/vercel/next.js/blob/dc87a8436bd978a8cf9e605da171897400b19743/packages/next/package.json#L131

Can you update `@babel/core` to `v7.12.12` to see if this issue can be reproduced?

**Comment by JuanM04** [comment] 2021-01-14 21:21
Is it me or `@babel/core` only goes up to `v7.12.10`? [npm page](https://www.npmjs.com/package/@babel/core)

**Comment by nicolo-ribaudo** [comment] 2021-01-14 21:28
Actually, #12478 was only about files that don't contain any JSX originally but it's then injected by a separate plugin. Since `Page` in your example already contains JSX, it is probably something else :thinking:

**Comment by nicolo-ribaudo** [comment] 2021-01-14 21:39
@JuanM04 Are you sure that the error is thrown at that line?

I tried editing `node_modules/next/dist/compiled/babel/bundle.js`: if you grep for `function call(e,t,r)`, you'll find this code (minified):
https://github.com/babel/babel/blob/6e9a174e7f70180a7ae7b7c01a2c988849666cf0/packages/babel-plugin-transform-react-jsx/src/create-plugin.js#L276-L280

I tried adding a `throw new Error("d " + d)` as the first statement of that function and it correctly threw
```
Error: /babel-bugs/babel-plugin-superjson-next-10.0.5-repro/pages/index.js: d (e,t)=>e.get(`@babel/plugin-react-jsx/${t}`)
```

I then tried to use
```
if (typeof d !== "function") throw new Error("d " + d);
```

and it throws again `d(...) is not a function`, which means that it never enters inside that `if` statement, and thus `d` is always a function there.

**Comment by Skn0tt** [comment] 2021-01-14 21:41
`d` is always a function, but `d(...)` (the return value of d()) isn't. It should be some lazy-initialisation thing (https://github.com/babel/babel/blob/6e9a174e7f70180a7ae7b7c01a2c988849666cf0/packages/babel-plugin-transform-react-jsx/src/create-plugin.js#L205), but it's never defined as such.

**Comment by JLHwung** [comment] 2021-01-14 21:42
@nicolo-ribaudo 

Prettier helps
```
mv node_modules/next/dist/compiled/babel/bundle.js bundle.js 
npx prettier --write bundle.js 
mv bundle.js node_modules/next/dist/compiled/babel/bundle.js
```

**Comment by JLHwung** [comment] 2021-01-14 21:45
@JuanM04 Ahh my bad. I was meant for `@babel/plugin-transform-react-jsx` but looking on the `yarn.lock` of `next.js` it should be all good.

**Comment by nicolo-ribaudo** [comment] 2021-01-14 21:55
This is a `@babel/traverse` bug.
In the traversal spawned by https://github.com/blitz-js/babel-plugin-superjson-next/blob/9647e587a8c462b747e0cfde37d5fbf3de24e882/src/index.ts#L120, for some reason it's re-using the top-level visitors when vising the AST of the `Page` function.

@JuanM04 As a workaround (even if the bug is on our side), you can replace the two traversals in your plugin with a simple loop over `path.get("body")`. This is also better performance-wise, because it only iterates the top-level statements (where you could find export declarations) rather than the whole AST.

**Comment by Skn0tt** [comment] 2021-01-14 22:00
Thank you for your quick work on this! ❤️

I'll try out the loop-workaround. Can you estimate in which Babel version the @babel/traverse bug will be fixed (next patch / minor / major)?

**Comment by nicolo-ribaudo** [comment] 2021-01-14 22:03
It doesn't need to wait for a minor/major, but `@babel/traverse` bugs are so hard to fix that it might take a while.

This _might_ be fixed by https://github.com/babel/babel/pull/12634, which is an old branch I had locally and just pushed.

**Closed** 2023-07-05 13:44 UTC
Labels: i: bug, pkg: traverse, i: regression
