### ISSUE TITLE
Incorrect renaming issue

### ISSUE THREAD

**Issue by alexeyraspopov** [babel/babel#2345] opened 2015-09-09 10:56 UTC
I have code like this

```javascript
function A(value, bind, pull=bind) {
	return {
		bind: (a, b) => bind(value, a, b),
		pull: (a, b) => pull(value, a, b).valueOf()
	};
}
```

As you see, it has param `bind` and an object with `bind` method. and I want to use `bind` as a default param value for `pull`.

Babel [produces](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=true&playground=true&code=function%20A(value%2C%20bind%2C%20pull%3Dbind)%20%7B%0A%09return%20%7B%0A%09%09bind%3A%20(a%2C%20b)%20%3D%3E%20bind(value%2C%20a%2C%20b)%2C%0A%09%09pull%3A%20(a%2C%20b)%20%3D%3E%20pull(value%2C%20a%2C%20b).valueOf()%0A%09%7D%3B%0A%7D) the code which will throw an error because `bind` will be undefined for assigning it to `pull`

```javascript
"use strict";

var _temporalUndefined = {};

function _temporalAssertDefined(val, name, undef) { if (val === undef) { throw new ReferenceError(name + " is not defined - temporal dead zone"); } return true; }

function A(value, _bind) {
	var value = _temporalUndefined;
	var _bind = _temporalUndefined;
	var _pull = _temporalUndefined;
	value = arguments.length <= 0 || arguments[0] === undefined ? undefined : arguments[0];
	_bind = arguments.length <= 1 || arguments[1] === undefined ? undefined : arguments[1];
	_pull = arguments.length <= 2 || arguments[2] === undefined ? bind : arguments[2];

	return {
		bind: function bind(a, b) {
			return (_temporalAssertDefined(_bind, "_bind", _temporalUndefined) && _bind)(_temporalAssertDefined(value, "value", _temporalUndefined) && value, a, b);
		},
		pull: function pull(a, b) {
			return (_temporalAssertDefined(_pull, "_pull", _temporalUndefined) && _pull)(_temporalAssertDefined(value, "value", _temporalUndefined) && value, a, b).valueOf();
		}
	};
}
```

You can find a problem in these two lines

```javascript
	_bind = arguments.length <= 1 || arguments[1] === undefined ? undefined : arguments[1];
	_pull = arguments.length <= 2 || arguments[2] === undefined ? bind : arguments[2];
```

**Comment by qimingweng** [comment] 2015-09-10 04:10
Oh that's interesting, I wonder if this is in the specification. It seems like this wouldn't be expected behaviour, as 'bind' isn't defined at the time 'pull' is set to default to 'bind', but I can see how this feature is useful.

**Comment by qimingweng** [comment] 2015-09-10 04:11
You're probably better off explicitly assigning it though, something like:
```js
function A(value, bind, pull=bind) {
    if (pull === undefined) pull = bind;
    return {
        bind: (a, b) => bind(value, a, b),
        pull: (a, b) => pull(value, a, b).valueOf()
    };
}
```

**Comment by sebmck** [comment] 2015-09-10 04:11
@qimingweng Why would it be in the specification? This is a bug due to function name inference trying to rename a binding but not renaming all instances properly.

**Comment by qimingweng** [comment] 2015-09-10 04:17
@sebmck I may not understand the bug properly, but is
```
function name(a, b = a) {
}
```
valid?

**Comment by sebmck** [comment] 2015-09-10 04:17
@qimingweng That's valid. The bug is about one of the `bind` references not being remapped to `_bind`.

**Comment by qimingweng** [comment] 2015-09-10 04:46
:+1:

**Comment by bradencanderson** [comment] 2015-09-14 06:33
Not sure if this is related, but the way that babel is renaming bindings is a little flaky. This gets corrupted:

```js

**Comment by sebmck** [comment] 2015-09-14 06:34
It's not related. Open another issue please.

**Closed** 2015-09-14 16:36 UTC
Labels: bug, transformation
