### ISSUE TITLE
Unexpected token, expected "</>" by 7.0.0-beta.48

### ISSUE THREAD

**Issue by mts** [babel/babel#8049] opened 2018-05-25 10:16 UTC
> ### Edit by @nicolo-ribaudo
> To fix this problem, pass the `isTSX: true` option to the TypeScript plugin.

## Bug Report

**Current Behavior**
JSX code below is not parsed by `7.0.0-beta.48` since today although it is parsed no problem yesterday with `7.0.0-beta.47`

**Input Code**
```
ERROR in ./src/some.jsx
Module build failed: SyntaxError: src/some.jsx: Unexpected token, expected "</>" (24:16)

import React from 'react';
import ReactDOM from 'react-dom';
import {Provider} from "react-redux";
import {Router} from "react-router";

  22 |   return (
  23 |     <SomeProvider>
> 24 |       <Provider store={store} key="provider">
     |                 ^
  25 |         <Router history={history}>
  26 |           <Application/>
  27 |         </Router>
    at _class.raise (/Users/mts/some-site/node_modules/@babel/parser/lib/index.js:3858:15)
    at _class.unexpected (/Users/mts/some-site/node_modules/@babel/parser/lib/index.js:5187:16)
    at _class.expectRelational (/Users/mts/some-site/node_modules/@babel/parser/lib/index.js:5128:12)
    at _class.tsParseTypeAssertion (/Users/mts/some-site/node_modules/@babel/parser/lib/index.js:9212:12)
    at _class.parseMaybeUnary (/Users/mts/some-site/node_modules/@babel/parser/lib/index.js:10109:21)
    at _class.tsParseTypeAssertion (/Users/mts/some-site/node_modules/@babel/parser/lib/index.js:9213:30)
    at _class.parseMaybeUnary (/Users/mts/some-site/node_modules/@babel/parser/lib/index.js:10109:21)
    at _class.parseExprOps (/Users/mts/some-site/node_modules/@babel/parser/lib/index.js:5751:21)
    at _class.parseMaybeConditional (/Users/mts/some-site/node_modules/@babel/parser/lib/index.js:5723:21)
    at _class.parseMaybeAssign (/Users/mts/some-site/node_modules/@babel/parser/lib/index.js:5670:21)
    at _class.parseMaybeAssign (/Users/mts/some-site/node_modules/@babel/parser/lib/index.js:10096:87)
    at _class.parseParenAndDistinguishExpression (/Users/mts/some-site/node_modules/@babel/parser/lib/index.js:6411:28)
    at _class.parseExprAtom (/Users/mts/some-site/node_modules/@babel/parser/lib/index.js:6221:21)
    at _class.parseExprSubscripts (/Users/mts/some-site/node_modules/@babel/parser/lib/index.js:5865:21)
    at _class.parseMaybeUnary (/Users/mts/some-site/node_modules/@babel/parser/lib/index.js:5844:21)
    at _class.parseMaybeUnary (/Users/mts/some-site/node_modules/@babel/parser/lib/index.js:10111:54)
    at _class.parseExprOps (/Users/mts/some-site/node_modules/@babel/parser/lib/index.js:5751:21)
    at _class.parseMaybeConditional (/Users/mts/some-site/node_modules/@babel/parser/lib/index.js:5723:21)
    at _class.parseMaybeAssign (/Users/mts/some-site/node_modules/@babel/parser/lib/index.js:5670:21)
    at _class.parseMaybeAssign (/Users/mts/some-site/node_modules/@babel/parser/lib/index.js:10067:87)
    at _class.parseExpression (/Users/mts/some-site/node_modules/@babel/parser/lib/index.js:5623:21)
    at _class.parseReturnStatement (/Users/mts/some-site/node_modules/@babel/parser/lib/index.js:7430:28)
    at _class.parseStatementContent (/Users/mts/some-site/node_modules/@babel/parser/lib/index.js:7116:21)
    at _class.parseStatementContent (/Users/mts/some-site/node_modules/@babel/parser/lib/index.js:9813:58)
    at _class.parseStatement (/Users/mts/some-site/node_modules/@babel/parser/lib/index.js:7082:17)
    at _class.parseBlockOrModuleBlockBody (/Users/mts/some-site/node_modules/@babel/parser/lib/index.js:7629:23)
    at _class.parseBlockBody (/Users/mts/some-site/node_modules/@babel/parser/lib/index.js:7616:10)
    at _class.parseBlock (/Users/mts/some-site/node_modules/@babel/parser/lib/index.js:7605:10)
    at _class.parseFunctionBody (/Users/mts/some-site/node_modules/@babel/parser/lib/index.js:6862:24)
    at _class.parseArrowExpression (/Users/mts/some-site/node_modules/@babel/parser/lib/index.js:6814:10)
    at _class.parseExprAtom (/Users/mts/some-site/node_modules/@babel/parser/lib/index.js:6168:18)
    at _class.parseExprSubscripts (/Users/mts/some-site/node_modules/@babel/parser/lib/index.js:5865:21)
    at _class.parseMaybeUnary (/Users/mts/some-site/node_modules/@babel/parser/lib/index.js:5844:21)
    at _class.parseMaybeUnary (/Users/mts/some-site/node_modules/@babel/parser/lib/index.js:10111:54)
    at _class.parseExprOps (/Users/mts/some-site/node_modules/@babel/parser/lib/index.js:5751:21)
    at _class.parseMaybeConditional (/Users/mts/some-site/node_modules/@babel/parser/lib/index.js:5723:21)
```

```js
const client = (Application) => {
  return (
    <SomeProvider>
      <Provider store={ store } key="provider">
        <Router history={ history }>
          <Application/>
        </Router>
      </Provider>
    </SomeProvider>
  );
};
```

**Expected behavior/code**
`JSX gets properly parsed.`

**Babel Configuration (.babelrc, package.json, cli command)**
```
  "devDependencies": {
    "@babel/core": "7.0.0-beta.48",
    "@babel/plugin-syntax-decorators": "7.0.0-beta.48",
    "@babel/plugin-syntax-jsx": "7.0.0-beta.48",
    "@babel/plugin-syntax-object-rest-spread": "7.0.0-beta.48",
    "@babel/plugin-syntax-typescript": "7.0.0-beta.48",
    "@babel/plugin-transform-runtime": "7.0.0-beta.48",
    "@babel/plugin-transform-shorthand-properties": "7.0.0-beta.48",
    "@babel/preset-react": "7.0.0-beta.48",

  "dependencies": {
    "@babel/runtime": "7.0.0-beta.48",
```
```js
{
  test: /\.jsx?$/,
  exclude: /(node_modules)/,
  use: {
    loader: 'babel-loader',
    options: {
      presets: [
          '@babel/preset-react'
      ],
      babelrc: false,
      "plugins": [
        "@babel/plugin-syntax-typescript",
        "@babel/plugin-syntax-decorators",
        "@babel/plugin-syntax-jsx",
        "@babel/plugin-transform-runtime"
      ]
    }
  }
}
```

**Environment**
- Babel version(s): `7.0.0-beta.48`
- Node/npm version: node `v8.11.1`, npm `6.0.0`
- OS: MacOS Sierra 10.13.4
- Monorepo: yes
- How you are using Babel: `loader`

**Comment by xtuc** [comment] 2018-05-25 11:00
Interesting, we saw the same thing here https://github.com/babel/babel/pull/7996. cc @malbernaz could that be related?

**Comment by malbernaz** [comment] 2018-05-25 16:46
Yeah, it can be. @mts are you using fragments somewhere?

**Comment by mts** [comment] 2018-05-26 08:04
@malbernaz yes, I am using `React.Fragment` from React version `16.4.0`.

**Comment by calebeby** [comment] 2018-05-29 16:13
I am seeing this too, and I am not using fragments

**Comment by calebeby** [comment] 2018-05-29 16:13
https://github.com/Pigmice2733/scouting-frontend/pull/140

**Comment by malbernaz** [comment] 2018-05-30 23:35
I'm running into this to

**Comment by malbernaz** [comment] 2018-05-30 23:40
downgrading to version 47 worked for me.

**Comment by jdiprizio** [comment] 2018-05-31 14:54
I'm seeing the same issue as well and downgrading only `@babel/preset-react` to `7.0.0-beta.47` fixes the issue.

**Comment by rifler** [comment] 2018-06-04 12:56
worked again in `@babel/preset-react@7.0.0-beta.49`

**Comment by calebeby** [comment] 2018-06-07 00:07
I'm going to try and fix this issue

**Comment by calebeby** [comment] 2018-06-07 00:40
I am only observing this issue when I enable the typescript transform plugin. Are you all using the typescript plugin too?

**Comment by malbernaz** [comment] 2018-06-07 01:41
👍 there's probably something to do with ts and jsx syntax collapsing

**Comment by Kovensky** [comment] 2018-06-07 02:11
This seems to happen when the typescript syntax or transform plugin are used directly.

It seems that, currently, only the preset is capable of actually looking at the file extension and decide whether JSX or typescript parsing is enabled or disabled. It needs to do it because `.ts` files are not allowed to use JSX as it conflicts with the old-style angle bracket cast (`const y = <Foo>x;`).

A workaround for this would be to give `{ isTSX: true }` as an option to the syntax plugin, but this would also just enable `isTSX` on all files, even `.ts` files.

**Comment by mts** [comment] 2018-06-07 06:32
@calebeby I am using "@babel/plugin-syntax-typescript": "7.0.0-beta.48"

**Comment by jdiprizio** [comment] 2018-06-07 06:36
Can confirm that I do have typescript transform enabled and that it seems to have been caused by having React code in `.ts` files.

**Comment by bondparkerbond** [comment] 2018-08-09 17:36
I am running into a similar problem trying to upgrade my React-Native project to react 0.56 and babel 7. The RN docs specify using 7.0.0-beta.47, but I'm wondering if there is a newer version I can use instead since it only offers me .48 and higher when I try and upgrade.

**Comment by borisowsky** [comment] 2018-08-09 19:36
Just wondering, if is it okay to work with typescript like so:
Use `babel/preset-typescript@7.0.0-rc.0`, `babel/preset-react@7.0.0-rc.0`, so it works perfectly, but I also use `awesome-typescript-loader` before `babel-loader` to get type-checking while compilation?

**Comment by RomanGotsiy** [comment] 2018-08-17 12:27
This is still reproducible on `@7.0.0-rc.1`.

**Comment by nicolo-ribaudo** [comment] 2018-08-17 19:03
The typescript plugin ignores the `syntax-jsx` plugin because TypeScript itself handles `.ts` files and `.tsx` files differently: the same syntax is used to mean different things in those two kind of ts files. Babel needs to know if it is parsing `.ts` or `.tsx` module, and this can be specified using the `isTSX` option.

For example
```
var foo = <T>(arg: T) => { };
```
in a `.ts` file is totally fine, but in a `.tsx` file it will throw an exception as an unclosed JSX element.

These are possible configs that you may want to use:
```js
// Always use TypeScript + JSX
module.exports = {
  plugins: [
    ["@babel/plugin-syntax-typescript", { isTSX: true }]
  ]
};

// Use JSX in .tsx files, type casts in .ts files
module.exports = {
  overrides: [{
    test: /.ts$/,
    plugins: [
      "@babel/plugin-syntax-typescript"
    ]
  }, {
    test: /.tsx$/,
    plugins: [
      ["@babel/plugin-syntax-typescript", { isTSX: true }]
    ]
  }]
}

// Use JSX in .tsx and .jsx files, type casts in .ts files
module.exports = {
  overrides: [{
    test: /.ts$/,
    plugins: [
      "@babel/plugin-syntax-typescript"
    ]
  }, {
    test: /.tsx$/,
    plugins: [
      ["@babel/plugin-syntax-typescript", { isTSX: true }]
    ]
  }, {
    test: /.jsx$/,
    plugins: [
      "@babel/plugin-syntax-jsx"
    ]
  }]
}
```

**Comment by RomanGotsiy** [comment] 2018-08-18 08:49
@nicolo-ribaudo I don't think this issue should be closed.

While the proposed workaround may work it is absolutely not obvious. Lots of users will face the exact same issue and will spend hours investigating.

> Babel needs to know if it is parsing .ts or .tsx module, and this can be specified using the isTSX option.

How did this use to work in `7.0.0-beta.47` without specifying `isTSX` options? Maybe it can be fixed properly. I can give it a try.

In case there is no proper fix this has to be at least documented or some hints should be added to error message before closing this issue.

**Comment by nicolo-ribaudo** [comment] 2018-08-18 10:12
You are right, this needes to at least be well documented.

**Comment by Mouvedia** [comment] 2019-07-10 22:57
I am getting this similar error:
```
SyntaxError: …foo.tsx: Unexpected token, expected "</>/<=/>="

      109 |   render() {
      110 |     return (
    > 111 |       <picture innerHTML={`
          |                ^
```
Is this the same bug?

**Comment by nicolo-ribaudo** [comment] 2019-07-11 08:24
What's your config?

**Comment by Mouvedia** [comment] 2019-07-11 08:35
@nicolo-ribaudo right now it looks like that:

```
module.exports = function (api) {
  api.cache(false);

  return {
    presets: [
      ["@babel/preset-env"]
    ],
    plugins: [
      "@babel/plugin-transform-typescript",
      ["@babel/plugin-proposal-decorators", { "decoratorsBeforeExport": true }]
    ]
  };
};
```
…but I tried the typescript preset and many JSX and TS plugins.

**Comment by nicolo-ribaudo** [comment] 2019-07-11 08:50
You need the jsx plugin/preset.

**Comment by Mouvedia** [comment] 2019-07-11 09:06
@nicolo-ribaudo could you be more precise ?
Is it `@babel/preset-react` or `babel-plugin-jsx` or `@babel/plugin-syntax-jsx` or `@babel/plugin-transform-react-jsx or etc.

I tried them all BTW. There's probably some kind of trick that involves having the plugins in a particular order.

**Comment by nicolo-ribaudo** [comment] 2019-07-11 09:12
Either `@babel/preset-react` or `@babel/plugin-transform-react-jsx`.
I don't have time to look at it right now, but if you as on slack (https://slack.babeljs.io/) posting your full config someone might help you.

**Comment by Mouvedia** [comment] 2019-07-11 13:01
@nicolo-ribaudo I tried; no one's around.

**Comment by nicolo-ribaudo** [comment] 2020-03-22 14:50
Closing since this was a configuration issue.

**Closed by nicolo-ribaudo** 2020-03-22 14:50 UTC
Labels: area: jsx, i: docs, i: invalid configuration

**Comment by Mouvedia** [comment] 2020-03-22 16:12
> [You are right, this needes to at least be well documented.](https://github.com/babel/babel/issues/8049#issuecomment-414047405)

Is _this_ well documented? If so where?

**Comment by nicolo-ribaudo** [comment] 2020-03-22 16:49
In the plugin docs (https://babeljs.io/docs/en/babel-preset-typescript#istsx) it says that, without the `isTSX` option, angle brackets are parsed as typecasts and not as JSX elements.

**Comment by nicolo-ribaudo** [comment] 2020-03-22 17:06
I have closed this issue because currently it's the expected behavior, but I'm discussing with the team about changing this in Babel 8 (and let the `jsx` plugin alone control JSX parsing).
