### ISSUE TITLE
babel-node ES6 imports fail in REPL

### ISSUE THREAD

**Issue by tomxtobin** [babel/babel#1488] opened 2015-05-09 15:39 UTC
When using an ES6 import at the `babel-node` REPL, it fails.

Example sources:
```js
// foo.js
import bar from './bar'
console.log(bar)
```
```js
// bar.js
exports.baz = 1
```
`babel` generates the following code for `foo.js`:
```js
'use strict';

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { 'default': obj }; }

var _bar = require('./bar');

var _bar2 = _interopRequireDefault(_bar);

console.log(_bar2['default']);
```
Passing the generated code from `babel` to `iojs` works fine:
```
$ babel foo.js | iojs
{ baz: 1 }
```
If you run the same module by hand at the REPL, or pipe it in, it fails:
```
$ cat foo.js | babel-node
> import bar from './bar'
'use strict'
> console.log(bar)
repl:3
console.log(bar);
            ^
ReferenceError: bar is not defined
    at repl:3:13
    at Object.exports.runInThisContext (vm.js:54:17)
    at _eval (/home/tomxtobin/npm/lib/node_modules/babel/bin/_babel-node:54:13)
    at REPLServer.replEval (/home/tomxtobin/npm/lib/node_modules/babel/bin/_babel-node:136:14)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.<anonymous> (repl.js:309:12)
    at emitOne (events.js:77:13)
    at REPLServer.emit (events.js:166:7)
    at REPLServer.Interface._onLine (readline.js:208:10)
```
But if you pass the file as an argument to `babel-node` it works fine:
```
$ babel-node foo.js
{ bar: 1 }
```
If you keep everything in the REPL on the same line, it also works fine:
```
> import bar from './bar'; console.log(bar)
{ baz: 1 }
undefined
```
Versions:
```
$ babel --version
5.2.16
$ iojs --version
v2.0.0
```

**Comment by sebmck** [comment] 2015-05-09 15:40
Duplicate of #1264.

**Closed by sebmck** 2015-05-09 15:40 UTC

**Comment by tomxtobin** [comment] 2015-05-09 15:47
Crap, sorry. My eyes must've skipped right over the other issue when I checked. o_O

**Comment by sebmck** [comment] 2015-05-09 15:48
All good :smile:
