### ISSUE TITLE
Decorators ignored with Babel 6.0.15

### ISSUE THREAD

**Issue by lee-ellam** [babel/babel#2845] opened 2015-11-05 15:52 UTC
My .babelrc is below:

```
{
  'presets': ['react', 'stage-0', 'es2015']
}
```

If I move stage-0 preset after es2015, I get the same issue as #2801, if I leave it as above, decorators are ignored.

**Comment by sebmck** [comment] 2015-11-05 17:05
Duplicate of #2645.

**Closed by sebmck** 2015-11-05 17:05 UTC
