### ISSUE TITLE
Uncaught ReferenceError: _asyncToGenerator is not defined

### ISSUE THREAD

**Issue by self-coding-crab** [babel/babel#11667] opened 2020-06-03 17:32 UTC
Hi gents.

I am trying to build my react app which is running perfectly via 'npm start'.
Once I build, it shows such issue "Uncaught ReferenceError: _asyncToGenerator is not defined"

I did research on google and mostly they are saying it's related to babel-polyfill or transform-runtime.
Here's my babalrc

`{
  "presets": ["@babel/preset-env"],
  "plugins": [
    [
      "@babel/plugin-transform-runtime",
      {
        "absoluteRuntime": true,
        "corejs": false,
        "helpers": true,
        "regenerator": true,
        "useESModules": false,
        "version": "7.4.4"
      }
    ]
  ]
}`

After adding @babel/plugin-transform-runtime, I am still getting the same issue.

Here's the code block which produces an error.

function _init() {
    _init = _asyncToGenerator( /*#__PURE__*/_regeneratorRuntime.mark(function _callee(data) {
      var code, wasmModule;
      return _regeneratorRuntime.wrap(function _callee$(_context) {
        while (1) {
          switch (_context.prev = _context.next) {
            case 0:
              code = new Uint8Array(data.code);
              _context.next = 3;
              return WebAssembly.compile(code);

            case 3:
              wasmModule = _context.sent;
              memory = new WebAssembly.Memory({
                initial: data.init
              });
              i32 = new Uint32Array(memory.buffer);
              _context.next = 8;
              return WebAssembly.instantiate(wasmModule, {
                env: {
                  "memory": memory
                }
              });

            case 8:
              instance = _context.sent;

            case 9:
            case "end":
              return _context.stop();
          }
        }
      }, _callee);
    }));
    return _init.apply(this, arguments);
  }

Thanks

**Comment by self-coding-crab** [comment] 2020-06-03 18:25
@nicolo-ribaudo Thanks for your reply. What do you mean by input code?

**Comment by nicolo-ribaudo** [comment] 2020-06-03 18:25
The code in your app that Babel compiles to the one you posted

**Comment by self-coding-crab** [comment] 2020-06-03 18:26
async function build(wasmInitialMemory = 5000) {
    const groth16 = new Groth16();

    groth16.q = bigInt("21888242871839275222246405745257275088696311157297823662689037894645226208583");
    groth16.r = bigInt("21888242871839275222246405745257275088548364400416034343698204186575808495617");
    groth16.n64 = Math.floor((groth16.q.minus(1).bitLength() - 1)/64) +1;
    groth16.n32 = groth16.n64*2;
    groth16.n8 = groth16.n64*8;

    groth16.memory = new WebAssembly.Memory({initial:wasmInitialMemory});
    groth16.i32 = new Uint32Array(groth16.memory.buffer);

    const wasmModule = await WebAssembly.compile(groth16_wasm.code);

    groth16.instance = await WebAssembly.instantiate(wasmModule, {
        env: {
            "memory": groth16.memory
        }
    });

    groth16.pq = groth16_wasm.pq;
    groth16.pr = groth16_wasm.pr;

    groth16.pr0 = groth16.alloc(192);
    groth16.pr1 = groth16.alloc(192);

    groth16.workers = [];
    groth16.pendingDeferreds = [];
    groth16.working = [];

    let concurrency;

    if ((typeof(navigator) === "object") && navigator.hardwareConcurrency) {
        concurrency = navigator.hardwareConcurrency;
    } else {
        concurrency = 8;
    }

    function getOnMsg(i) {
        return function(e) {
            let data;
            if ((e)&&(e.data)) {
                data = e.data;
            } else {
                data = e;
            }

            groth16.working[i]=false;
            groth16.pendingDeferreds[i].resolve(data);
            groth16.processWorks();
        };
    }

    for (let i = 0; i<concurrency; i++) {

        if (inBrowser) {
            const blob = new Blob(["(", thread.toString(), ")(self);"], { type: "text/javascript" });
            const url = URL.createObjectURL(blob);

            groth16.workers[i] = new Worker(url);

            groth16.workers[i].onmessage = getOnMsg(i);

        } else {
            groth16.workers[i] = new NodeWorker("(" + thread.toString()+ ")(require('worker_threads').parentPort);", {eval: true});

            groth16.workers[i].on("message", getOnMsg(i));
        }

        groth16.working[i]=false;
    }

    const initPromises = [];
    for (let i=0; i<groth16.workers.length;i++) {
        const copyCode = groth16_wasm.code.buffer.slice(0);
        initPromises.push(groth16.postAction(i, {
            command: "INIT",
            init: wasmInitialMemory,
            code: copyCode

        }, [copyCode]));
    }

    await Promise.all(initPromises);

    return groth16;
}

This code is from node_modules/websnark/src/groth16.js

**Comment by nicolo-ribaudo** [comment] 2020-06-07 19:41
@self-coding-crab I tried compiling that code with that config but I couldn't reproduce the bug :thinking: 

Additionally, `.babalrc` isn't applied to `node_modules` when using `@babel/core` 7, so I don't even understand how it's possible that it is compiling `node_modules/websnark/src/groth16.js`.

**Comment by nicolo-ribaudo** [comment] 2021-02-01 01:44
Closing since I could not reproduce the bug.

If it's still present, please ping me and I can repoen.

**Closed by nicolo-ribaudo** 2021-02-01 01:44 UTC
Labels: i: bug, i: needs triage
