### ISSUE TITLE
Possibly unhandled rejection

### ISSUE THREAD

**Issue by iamkiran** [babel/babel#12290] opened 2020-10-30 20:06 UTC
## Bug Report
I'm compiling my angularJS code using the Babel  and later using Grunt to minifiy the angularjs code using ngAnnotate. when I start the server I'm getting unable to Possilbly unhanled rejection. 

```js
    UXController.js
       app.controller('UXController', function($window, $stateParams, $timeout, configs, $compile, $scope, service, d, m, c, 
		$interval, $ngConfirm, o, $rootScope) {
});
```

**Expected behavior**

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `.babelrc`

```js

{
  "presets": ["env"],
  "env": {
      "development" : {
        "compact": false
      }
    }

}

package.json : 
moving complied code from **static/js** files to **/static/babel/js** file after running **npm run build command**
"scripts": {

    "build": "babel static/js/ -d static/babel/js"
  },
```

**Environment**

```
 "@babel/cli": "^7.10.1",
    "@babel/core": "^7.10.2",
    "@babel/node": "^7.10.1",
    "@babel/polyfill": "^7.10.1",
    "@babel/preset-env": "^7.10.2",
    "@babel/preset-react": "^7.10.1",
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.3",
    "babel-loader": "^8.1.0",
    "babel-preset-env": "^1.7.0",
    "grunt": "^1.1.0",
    "grunt-babel": "^8.0.0",
    "grunt-contrib-clean": "^2.0.0",
    "grunt-contrib-concat": "^1.0.1",
    "grunt-contrib-copy": "^1.0.0",
    "grunt-contrib-cssmin": "^3.0.0",
    "grunt-contrib-uglify": "^4.0.1",
    "grunt-ng-annotate": "^4.0.0",
    "grunt-npm-install": "^0.3.1",
    "grunt-string-replace": "^1.3.1",
```

**Possible Solution**

**Additional context**

**Comment by iamkiran** [comment] 2020-10-30 20:14
when I noticed in the compiled babel file I could see the below code.

"use strict";


function _typeof(e){function t(e){return o.apply(this,arguments)}var o,n;function a(e){return n.apply(this,arguments)}return(_typeof="function"==typeof Symbol&&"symbol"===_typeof(Symbol.iterator)?(n=function(e){return void 0===e?"undefined":_typeof(e)},a.toString=function(){return n.toString()},a):(o=function(e){return e&&"function"==typeof Symbol&&e.constructor===Symbol&&e!==Symbol.prototype?"symbol":void 0===e?"undefined":_typeof(e)},t.toString=function(){return o.toString()},t))(e)}





app.controller("UXController",["$window","$stateParams","$timeout","configs","$compile","$scope","s","d","m","c","$interval","$ngConfirm","o","$rootScope",function($window,$stateParams,$timeout,c,$compile,$scope,s,d,m,c,$interval,$ngConfirm,o,$rootScope)

**Comment by JLHwung** [comment] 2020-10-30 20:17
Please provide a reproduction repo and the error message. "Possilbly unhanled rejection" is very abstract error whenever a promise is rejected with `.catch()`.

**Comment by iamkiran** [comment] 2020-10-30 20:33
Please are the logs which I have obtained from the browser console.


angular.1604086063034.min.js:14996 RangeError: Maximum call stack size exceeded
    at _typeof (UXController.1604086063034.min.js:1)
    at _typeof (UXController.1604086063034.min.js:1)
    at _typeof (UXController.1604086063034.min.js:1)
    at _typeof (UXController.1604086063034.min.js:1)
    at _typeof (UXController.1604086063034.min.js:1)
    at _typeof (UXController.1604086063034.min.js:1)
    at _typeof (UXController.1604086063034.min.js:1)
    at _typeof (UXController.1604086063034.min.js:1)
    at _typeof (UXController.1604086063034.min.js:1)
    at _typeof (UXController.1604086063034.min.js:1) "Possibly unhandled rejection: {}"
	
(anonymous) @ angular.1604086063034.min.js:14996
(anonymous) @ angular.1604086063034.min.js:11280
processChecks @ angular.1604086063034.min.js:17404
$digest @ angular.1604086063034.min.js:18535
$apply @ angular.1604086063034.min.js:18923
done @ angular.1604086063034.min.js:12777
completeRequest @ angular.1604086063034.min.js:13034
requestLoaded @ angular.1604086063034.min.js:12939
load (async)
(anonymous) @ angular.1604086063034.min.js:12922
sendReq @ angular.1604086063034.min.js:12722
serverRequest @ angular.1604086063034.min.js:12463
processQueue @ angular.1604086063034.min.js:17374
(anonymous) @ angular.1604086063034.min.js:17422
$digest @ angular.1604086063034.min.js:18535
$apply @ angular.1604086063034.min.js:18923
(anonymous) @ angular.1604086063034.min.js:20895
completeOutstandingRequest @ angular.1604086063034.min.js:6479
(anonymous) @ angular.1604086063034.min.js:6757
setTimeout (async)
Browser.self.defer @ angular.1604086063034.min.js:6755
timeout @ angular.1604086063034.min.js:20885
(anonymous) @ UXController.1604086063034.min.js:1
instantiate @ angular.1604086063034.min.js:5108
$controller @ angular.1604086063034.min.js:11153
(anonymous) @ angular.1604086063034.concat.js:14752
(anonymous) @ angular.1604086063034.min.js:1351
invokeLinkFn @ angular.1604086063034.min.js:10700
nodeLinkFn @ angular.1604086063034.min.js:10077
compositeLinkFn @ angular.1604086063034.min.js:9350
publicLinkFn @ angular.1604086063034.min.js:9215
lazyCompilation @ angular.1604086063034.min.js:9606
updateView @ angular.1604086063034.concat.js:14689
configUpdatedCallback @ angular.1604086063034.concat.js:14633
configureUIView @ angular.1604086063034.concat.js:10549
ViewService.sync @ angular.1604086063034.concat.js:10557
activateViews @ angular.1604086063034.concat.js:11193
invokeCallback @ angular.1604086063034.concat.js:6425
TransitionHook.invokeHook @ angular.1604086063034.concat.js:6430
(anonymous) @ angular.1604086063034.concat.js:6410
TransitionHook.runAllHooks @ angular.1604086063034.concat.js:6410
transitionSuccess @ angular.1604086063034.concat.js:8261
processQueue @ angular.1604086063034.min.js:17374
(anonymous) @ angular.1604086063034.min.js:17422
$digest @ angular.1604086063034.min.js:18535
$apply @ angular.1604086063034.min.js:18923
done @ angular.1604086063034.min.js:12777
completeRequest @ angular.1604086063034.min.js:13034
requestLoaded @ angular.1604086063034.min.js:12939
load (async)
(anonymous) @ angular.1604086063034.min.js:12922
sendReq @ angular.1604086063034.min.js:12722
serverRequest @ angular.1604086063034.min.js:12463
processQueue @ angular.1604086063034.min.js:17374
(anonymous) @ angular.1604086063034.min.js:17422
$digest @ angular.1604086063034.min.js:18535
$apply @ angular.1604086063034.min.js:18923
done @ angular.1604086063034.min.js:12777
completeRequest @ angular.1604086063034.min.js:13034
requestLoaded @ angular.1604086063034.min.js:12939
load (async)
(anonymous) @ angular.1604086063034.min.js:12922
sendReq @ angular.1604086063034.min.js:12722
serverRequest @ angular.1604086063034.min.js:12463
processQueue @ angular.1604086063034.min.js:17374
(anonymous) @ angular.1604086063034.min.js:17422
$digest @ angular.1604086063034.min.js:18535
$apply @ angular.1604086063034.min.js:18923
(anonymous) @ angular.1604086063034.min.js:28069
defaultHandlerWrapper @ angular.1604086063034.min.js:3780
eventHandler @ angular.1604086063034.min.js:3768

**Comment by iamkiran** [comment] 2020-10-30 20:40
Please find the logs which I have obtained from the browser logs.

angular.js:14996 RangeError: Maximum call stack size exceeded
    at _typeof (UXController.js:1)
    at _typeof (UXController.js:1)
    at _typeof (UXController.js:1)
    at _typeof (UXController.js:1)
    at _typeof (UXController.js:1)
    at _typeof (UXController.js:1)
    at _typeof (UXController.js:1)
    at _typeof (UXController.js:1)
    at _typeof (UXController.js:1)
    at _typeof (UXController.js:1) "Possibly unhandled rejection: {}"

(anonymous) @ angular.js:14996
(anonymous) @ angular.js:11280
processChecks @ angular.js:17404
$digest @ angular.js:18535
$apply @ angular.js:18923
done @ angular.js:12777
completeRequest @ angular.js:13034
requestLoaded @ angular.js:12939
load (async)
(anonymous) @ angular.js:12922
sendReq @ angular.js:12722
serverRequest @ angular.js:12463
processQueue @ angular.js:17374
(anonymous) @ angular.js:17422
$digest @ angular.js:18535
$apply @ angular.js:18923
(anonymous) @ angular.js:20895
completeOutstandingRequest @ angular.js:6479
(anonymous) @ angular.js:6757
setTimeout (async)
Browser.self.defer @ angular.js:6755
timeout @ angular.js:20885
(anonymous) @ UXController.js:1
instantiate @ angular.js:5108
$controller @ angular.js:11153
(anonymous) @ angular.1604086063034.concat.js:14752
(anonymous) @ angular.js:1351
invokeLinkFn @ angular.js:10700
nodeLinkFn @ angular.js:10077
compositeLinkFn @ angular.js:9350
publicLinkFn @ angular.js:9215
lazyCompilation @ angular.js:9606

I have attached angular js(https://code.angularjs.org/1.7.0/angular.js) which has been used in the project.

**Comment by iamkiran** [comment] 2020-10-30 20:42
> Please provide a reproduction repo and the error message. "Possilbly unhanled rejection" is very abstract error whenever a promise is rejected with `.catch()`.

I don't have privilege  to share the code here.

**Comment by nicolo-ribaudo** [comment] 2020-10-30 20:58
The problem is probably that you are transpiling `@babel/runtime` with itself. Can you try updating `@babel/core` to `^7.12.0` and running `BABEL_SHOW_CONFIG_FOR=./node_modules/@babel/runtime/helpers/typeof.js babel static/js/ -d static/babel/js`? (Assuming that `node_modules` is in the root of your project)

**Comment by iamkiran** [comment] 2020-10-30 22:23
I have updated the babel @babel/core to ^7.12.0 , except .babelrc I have not included any configuration file.

Also I am using **npm run build** command to transfer the transpiled file to destination.

**Comment by iamkiran** [comment] 2020-10-30 22:23
> The problem is probably that you are transpiling `@babel/runtime` with itself. Can you try updating `@babel/core` to `^7.12.0` and running `BABEL_SHOW_CONFIG_FOR=./node_modules/@babel/runtime/helpers/typeof.js babel static/js/ -d static/babel/js`? (Assuming that `node_modules` is in the root of your project)

I have updated the babel @babel/core to ^7.12.0 , except .babelrc I have not included any configuration file.

Also I am using npm run build command to transfer the transpiled file to destination.

**Comment by nicolo-ribaudo** [comment] 2021-02-01 01:29
I'm sorry I have to close this issue because it's impossible for us to reproduce it. If you manage to create a repository that shows the bug I'd be happy to reopen.

Btw, as I mentioned in https://github.com/babel/babel/issues/12290#issuecomment-719796020 make sure that all the `@babel/runtime`s and `@babel/core`s in your `node_modules` are at least `7.12.0`, and the problem in https://github.com/babel/babel/issues/12290#issuecomment-719774744 should go away.

**Closed by nicolo-ribaudo** 2021-02-01 01:29 UTC
Labels: i: bug, i: needs reproduction
