### ISSUE TITLE
Function.prototype.apply was called on WeakMap.prototype.get, which is a string and not a function

### ISSUE THREAD

**Issue by YuYongzhi** [babel/babel#13041] opened 2021-03-23 04:55 UTC
在小程序开发中出现如下错误
thirdScriptError
Function.prototype.apply was called on WeakMap.prototype.get, which is a string and not a function
TypeError: Function.prototype.apply was called on WeakMap.prototype.get, which is a string and not a function
    at callBoundIntrinsic (http://127.0.0.1:28624/appservice/common.js?t=wechat&s=1616474289115&v=65a0148353355bdadcf7fb665d91cd96:7458:41)

![image](https://user-images.githubusercontent.com/6104276/112094160-b7a0dd80-8bd5-11eb-9add-af8f07e51cf8.png)

在 package.json 中是如下引用的，
```
{
  "devDependencies": {
    "babel-plugin-lodash": "^3.2.11"
  }
}
```
在3月 22 日之前是可以正常运行的，包的依赖树是
```
├─┬ babel-plugin-lodash@3.3.4
│ ├─┬ @babel/helper-module-imports@7.12.13
```
但是在发布了[@babel/helper-module-imports-7.13.12](https://www.npmjs.com/package/@babel/helper-module-imports/v/7.13.12)之后，依赖树变成了
```
├─┬ babel-plugin-lodash@3.3.4
│ ├─┬ @babel/helper-module-imports@7.13.12
```
当前项目中 `package.json`中引用的 `webpack` 版本是
```
"devDependencies": {
    "webpack": "^3.8.1"
  }
```
实际 node_modules中的`webpack`版本是3.12.0。

请问如何解决？
是继续通过 package-lock.json 文件使用`@babel/helper-module-imports@7.12.13`，还是需要升级 webpack？

**Comment by nicolo-ribaudo** [comment] 2021-03-23 08:07
Is it possible that while updating Babel you also updated something else? Either a direct dependency, or an indirect one.

This error _seems_ completely unrelated to Babel, and it seems to be caused by something (maybe a third-party library you use) that overwrites `WeakMap.prototype.get` replacing it with a function.

**Comment by beside4ever** [comment] 2021-04-09 07:32
我这边也遇到了，你可以看下调用堆栈的源头是哪个包，我这里是qs的最新版导致的，回退到老版本可以暂时解决这个问题

**Comment by nicolo-ribaudo** [comment] 2021-04-09 08:06
@beside4ever If you add `console.log(WeakMap.prototype.get)` before calling `qs`, what does it log?

**Comment by nicolo-ribaudo** [comment] 2021-05-31 16:40
Closing as not reproducible.

Please create a repository I can run to reproduce the issue, so that we can verify if it's actually a Babel bug (and if it's still present), or if it's caused by something else!

**Closed by nicolo-ribaudo** 2021-05-31 16:40 UTC
Labels: Needs Info, i: needs reproduction
