### ISSUE TITLE
Invalid duplicate declaration

### ISSUE THREAD

**Issue by RafalFilipek** [babel/babel#2805] opened 2015-11-04 09:43 UTC
Babel 6.1.1 (babel-core 6.0.20)

```
class Foo {

  bar() {
    let bar = 2
    console.log(bar)
  }
}
```
```
./node_modules/.bin/babel test.js
```
```
TypeError: test.js: Duplicate declaration "bar"
  2 |
  3 |   bar() {
> 4 |     let bar = 2
    |         ^
  5 |     console.log(bar)
  6 |   }
  7 | }
    at File.buildCodeFrameError (***/node_modules/babel-core/lib/transformation/file/index.js:409:15)
    at Scope.checkBlockScopedCollisions (***/node_modules/babel-traverse/lib/scope/index.js:428:27)
    at Scope.<anonymous> (***/node_modules/babel-traverse/lib/scope/index.js:613:18)
    at Scope.registerBinding (***/node_modules/babel-traverse/lib/scope/index.js:627:8)
    at Scope.registerDeclaration (***/node_modules/babel-traverse/lib/scope/index.js:515:14)
    at Object.BlockScoped (***/node_modules/babel-traverse/lib/scope/index.js:165:28)
    at Object.newFn (***/node_modules/babel-traverse/lib/visitors.js:300:17)
    at NodePath._call (***/node_modules/babel-traverse/lib/path/context.js:72:18)
    at NodePath.call (***/node_modules/babel-traverse/lib/path/context.js:40:14)
    at NodePath.visit (***/node_modules/babel-traverse/lib/path/context.js:102:12)
```

IMO this code is 100% valid :)

**Comment by loganfsmyth** [comment] 2015-11-04 16:43
Duplicate of https://github.com/babel/babel/issues/2684

**Closed by loganfsmyth** 2015-11-04 16:43 UTC

**Comment by davewasmer** [comment] 2016-12-05 17:23
Still seeing this on 6.14, and the linked duplicate issue was closed and locked with no resolution mentioned. Could we reopen this issue or reopen & unlock #2684?

**Comment by hzoo** [comment] 2016-12-05 17:24
@davewasmer can you update babel to the latest (clear node_modules, etc) and post your config/versions, minimal code snippet, etc? If it's better you can make a new issue which has the template

**Comment by davewasmer** [comment] 2016-12-05 17:57
@hzoo thanks for the quick reply. Filed https://github.com/babel/babel/issues/4946
