### ISSUE TITLE
Babel class transform is not accurate

### ISSUE THREAD

**Issue by mjesun** [babel/babel#7848] opened 2018-05-01 22:07 UTC
There is a bug on the `class` transform, which does not match spec 1:1. When a constructor is not defined, the parent constructor should be called with `...args`, which means calling `Array.prototype[Symbol.iterator]` under the hood.

### Input Code

```js
Array.prototype[Symbol.iterator] = () => console.log('potato');
class Foo extends Error() {}
new Foo();
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

Tried with REPL, es2015 preset.

### Expected Behavior

`potato` should appear in the console.

### Current Behavior

`potato` does not appear in the console :( Essentially because no `Symbol.iterator` is pulled in.

### Possible Solution

Transform:

```js
(Foo.__proto__ || Object.getPrototypeOf(Foo)).apply(this, arguments)
```

Into:

```js
(Foo.__proto__ || Object.getPrototypeOf(Foo))(...args)
```

And let the spread/rest be recompiled to use the iterator.

### Context

See [an V8 issue](https://bugs.chromium.org/p/v8/issues/detail?id=7710&can=2&start=0&num=100&q=&colspec=ID%20Type%20Status%20Priority%20Owner%20Summary%20HW%20OS%20Component%20Stars&groupby=&sort=) for that. It's probably a very edge case anyway, but having the strict class transformer and the loose one, I'd expect the strict to be strict, not semi-loose :)

**Comment by loganfsmyth** [comment] 2018-05-01 22:33
Duplicate of https://github.com/babel/babel/issues/5147.

**Closed by loganfsmyth** 2018-05-01 22:33 UTC
