### ISSUE TITLE
retainLines does not work

### ISSUE THREAD

**Issue by adamziel** [babel/babel#2296] opened 2015-09-01 09:02 UTC
I have the following file:

file.js
```js
import $ from 'jquery';
```

I transform it as such:
```
babel --retainLines=true file.js
```

and the output is:
```js
'use strict';

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { 'default': obj }; }

var _jquery = require('jquery');

var _jquery2 = _interopRequireDefault(_jquery);

```

**Comment by adamziel** [comment] 2015-09-01 09:03
babel@5.8.23

**Comment by sebmck** [comment] 2015-09-01 09:23
Duplicate of #2092. Please search next time.

**Closed by sebmck** 2015-09-01 09:23 UTC

**Comment by prathamesh-sonpatki** [comment] 2015-09-01 09:42
@sebmck I think this issue is coming up because we have camel cased options here http://babeljs.io/docs/usage/options/. But it does not clearly explain that while using on command line we need to use the hyphenated versions.

**Comment by adamziel** [comment] 2015-09-01 09:48
@sebmck I saw that issue you linked to but I consider this a separate one (it is not related to the `export` behavior)

@prathamesh-sonpatki exactly!

**Comment by sebmck** [comment] 2015-09-01 09:49
@adamziel I linked to the wrong one initially but quickly edited my comment. This exact issue is #1703.
