### ISSUE TITLE
[Bug]: Fragments no longer work in mithril

### ISSUE THREAD

**Issue by pdfabbro** [babel/babel#15353] opened 2023-01-18 15:06 UTC
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

unfortunately I can't provide a repo as it's from my company's gitlab which is private

### Configuration file name

babel.config.js

### Configuration

```
module.exports = {
	presets: ["@babel/preset-env"],
	plugins: [
		"@babel/plugin-proposal-object-rest-spread",
		["babel-plugin-root-import", { rootPathSuffix: "src" }],
		[
			"@babel/plugin-transform-react-jsx",
			{
				pragma: "m",
				pragmaFrag: "'['"
			}
		]
	],
	sourceMaps: true,
	retainLines: true,
	env: {
		test: {
			plugins: ["@babel/plugin-transform-modules-commonjs"]
		}
	}
};
```

### Current and expected behavior

when upgrading from 7.19.0 to 7.20.7 my mithril application stops working.  I have followed the steps outlined on their page and it was workign previously https://mithril.js.org/jsx.html.  Note that I am using babel.config.js though, not .babelrc as they recommend.  The issue seems to be with how 7.20.7 is recognizing my fragments.  When I change them to divs the application no longer fails but doesn't render properly because I would have to modify all the CSS to handle all the new nested divs.

I can't seem to find a list of what was changed from 7.19.0 ti 7.20.7 or the steps involved to upgrade my application

### Environment

  System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.14.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @babel/plugin-proposal-object-rest-spread: ^7.20.7 => 7.20.7 
    @babel/plugin-transform-react-jsx: ^7.20.7 => 7.20.7         
    @babel/preset-env: ^7.20.2 => 7.20.2 
    babel-eslint: ^10.1.0 => 10.1.0 
    babel-jest: ^29.3.1 => 29.3.1
    babel-loader: ^9.1.2 => 9.1.2
    babel-plugin-root-import: ^6.6.0 => 6.6.0
    jest: ^29.3.1 => 29.3.1
    webpack: ^5.75.0 => 5.75.0

**Comment by liuxingbaoyu** [comment] 2023-01-18 18:01
Can you provide a repo to reproduce it?

**Comment by pdfabbro** [comment] 2023-01-18 18:05
Hi @liuxingbaoyu per my comment, unfortunately the repo is a company repo and I can't share it.

**Comment by liuxingbaoyu** [comment] 2023-01-18 18:10
Sorry for not noticing this.
https://github.com/babel/babel/pull/15047
A recent relevant change might be this one.
However, since there is no reproducible example, it is not sure whether the cause can be found.

**Comment by pdfabbro** [comment] 2023-01-18 18:13
No problem, thanks for the responses!  Do you see anything in my config file that maybe needs to be changed to handle this?

**Comment by liuxingbaoyu** [comment] 2023-01-18 18:41
No, I don't know much about jsx/react. Perhaps other members will have suggestions.

**Comment by JLHwung** [comment] 2023-01-18 19:33
> No problem, thanks for the responses! Do you see anything in my config file that maybe needs to be changed to handle this?

As a workaround, please specify `pragmaFrag: "["` when using Babel >= 7.20.7. Presumably, `pragmaFrag` should be something like `React.Fragment` (as a member expression) or `Fragment` (as an identifier). Passing a string literal `"'['"` is sort of uncharted territory. Anyway the breaking change here is never intended and I will try to restore it to the pre-7.20.7 behaviour.

```jsx
// Input
/* @jsxFrag '[' */
/* @jsx m */
<>Test</>;

// Output
// Before 7.20.7
m('[', null, "Test");
// After 7.20.7
m("'['", null, "Test");
```

**Comment by pdfabbro** [comment] 2023-01-18 19:46
Thank you!  I will try this tomorrow and let you know if it works

**Comment by pdfabbro** [comment] 2023-01-18 20:22
your suggestion of changing babel config to not have the quotes worked.  thank-you so much!

```
module.exports = {
	presets: ["@babel/preset-env"],
	plugins: [
		"@babel/plugin-proposal-object-rest-spread",
		["babel-plugin-root-import", { rootPathSuffix: "src" }],
		[
			"@babel/plugin-transform-react-jsx",
			{
				pragma: "m",
				pragmaFrag: "["
			}
		]
	],
	sourceMaps: true,
	retainLines: true,
	env: {
		test: {
			plugins: ["@babel/plugin-transform-modules-commonjs"]
		}
	}
};
```

**Comment by pygy** [comment] 2023-01-18 21:27
@JLHwung thanks for taking a look at this.

For context, canonical fragment representation in user code in Mithril is either just an array of vnodes, or a `m.fragment(hooks?, ...children)` (the default syntax for Mithril is hyperscript, but we also support JSX). Both syntaxes predate `React.Fragment` and the shorthand `<>` JSX support.

Our internal representation for fragments was a vnode with the string `'['` as a tag name, and for JSX compatibility, we added it to the public API (such that `m('[', ...)` works as intended after the Babel pass).

It was working with previous Babel versions, we didn't know it was by accident :-)

**Comment by pdfabbro** [comment] 2023-01-18 21:31
funny, I said to a colleague that I have a feeling that the mithril documentation was always wrong but it just happened to work previously by accident

**Comment by pygy** [comment] 2023-01-18 22:02
The thing is, I don't understand the semantics of the workaround.

What I understood of the pragma is that it would pass whatever expression it was given to`m()`, hence the quotes within the quotes.

The workaround syntax looks like it should produce a syntax error (e.g. Since `@jsx foo` and `@jsxFrag bar` gives `foo(bar, ...)`, I'd expect a bare `[` to produce `m([,...)`).

@JLHwung is the workaround guaranteed to work in the future?

**Comment by JLHwung** [comment] 2023-01-19 00:14
@pygy @pdfabbro The workaround will work before the next patch release. We will restore the behaviour so `pragmaFrag: "'['"` will work in the future Babel 7 release.

> the pragma is that it would pass whatever expression it was given to `m()`

This is an implementation detail and thus never an intended design goal. Currently, Babel treats `pragmaFrag:" React.Fragment"` as a member expression and generates `m(React.Fragment, ...)`, if `pragmaFrag` does not contain a `.`, Babel assumes it is a valid identifier name and create an identifier AST node from the given `pragmaFrag`. So internally `'['` is treated as an identifier and eventually printed as if it were an identifier, therefore you will see `'['` in the output. However, this approach will eventually _break_ in Babel 8 once we begin to verify the identifier names are actually valid.

In Babel 7.20.7 we first transform `<>...</>` to an JSXElement `<pragmaFrag>...</pragmaFrag>` and then re-use the JSX element transform. This approach works as long as `pragmaFrag` is a member expression or an identifier name, but apparently it will fail for `<'['>...</'['>`.

> Our internal representation for fragments was a vnode with the string '[' as a tag name, and for JSX compatibility, we added it to the public API (such that m('[', ...) works as intended after the Babel pass).

Would `mithril` consider migrating to the `automatic` runtime? Once finished, the new Babel config will be:

```js
[
  "@babel/plugin-transform-react-jsx", {
    importSource: "mithril/jsx-runtime",
    runtime: "automatic" // <-- This will be the Babel 8 default, users can remove it from their config
}]
```

For the example input
```jsx
<><div /></>;
```

The generated output will be
```js
import { jsx as _jsx, Fragment as _Fragment } from "mithril/jsx-runtime"
var x = _jsx(_Fragment, {
  children: _jsx("div", {})
});
// jsx can be a wrapper of `m` and Fragment can be the magic string `"["`
```

Pros here is that you don't have to leak internal implementation detail (`pragmaFrag` and `pragma`) to end users. All they need to know is there is a jsx-runtime handling every JSX concept. And this approach will work with Babel 7.9+ and Babel 8.

**Comment by pygy** [comment] 2023-01-19 09:27
Once we migrate to esm (Mithril still uses cjs right now), I'll add support for the new automatic runtime. As a stopgap, we can define `m.jsxFrag = '['`.

On your end, for backwards and forward compatibility, could you consider, for `@jsx foo` and `@jsxFrag bar`, to parse `foo` and `bar` as js expressions, and have the main JSX transform create a `foo(bar)` expression in one pass rather than having an dedicated fragment pass?

The documentation is terse, just gives an example of the transform, and nowhere states that the `jsxFrag` pragma is expected to be a valid JSX tag name. We understood it as being a JS expression...

**Comment by pygy** [comment] 2023-01-19 15:09
@JLHwung What is the story for keyed fragments in `automatic` mode? could `< key={}></>` become a thing?

**Comment by JLHwung** [comment] 2023-01-19 16:12
> What is the story for keyed fragments in `automatic` mode? could `< key={theKey}></>` become a thing?

This is a feature request for the jsx language, so it is a bit out of scope here. Please open a new issue to https://github.com/facebook/jsx. Once it is accepted by the JSX spec, Babel will support it asap.

> could you consider, for @jsx foo and @jsxFrag bar, to parse foo and bar as js expressions

The short syntax `<></>` is meant to be a [short-form JSX element](https://reactjs.org/docs/fragments.html#short-syntax), allowing expressions create discrepancy between the JSX element and fragment: You can't use an expression as an tag name but effectively you can inject any code (not only expression) via `pragmaFrag`. That said, we might consider supporting string literal as the only exemption.

> The documentation is terse, just gives an example of the transform, and nowhere states that the jsxFrag pragma is expected to be a valid JSX tag name.

Good point. I will open a docs PR later.

**Closed** 2023-01-20 18:24 UTC
Labels: i: bug, i: regression, area: jsx

**Comment by pygy** [comment] 2023-01-21 09:04
@JLHwung thanks for the revert. Would you consider adding "or a string" to the `@jsxFrag` requirements in the docs, in order to make it officially documented (and thus guarantee changing it is considered a semver major thing)?
