### ISSUE TITLE
@babel/parser@v7.12.1 could not parse typescript

### ISSUE THREAD

**Issue by HsuTing** [babel/babel#12197] opened 2020-10-16 03:32 UTC
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

- [REPL](https://babel.dev/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=JYOwLgpgTgZghgYwgAgApQPYAcDOAVATyxQG8AoZZYfKAVwgC5kAjDDAGwjhAG4LkoEEABNoTABT9KCABbB2wwSCYAlLgjAA6NYjABRTgFshYZAB9kOjdvX6jJgNoBdc8loiIMUBGEAaKchYmLhMJAC-_pQAlMgAvAB8lrY2ugYQxuB80nIKSqrJVnbpJq6FKRppGWDOru6iXiA-fGFkZAD0bcj1oMBgwBggZBAAHlgYUKYIAzimOADuvbJqHlBxyOLklNR4dBCRAkKiUPuy8opC-5pXQdg4ZGFM6LeExFH5uuVFVaUFtpWOLgsdU83mEcXi_G2u2QAH4DitxKdchdAsEcDEmEjzrwgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Cstage-2%2Ctypescript%2Cenv&prettier=false&targets=&version=7.12.1&externalPlugins=)

**Input Code**

```js
interface PropsType {
  isTrue: boolean;
  render: (
    children: React.ReactElement | React.ReactElement[] | undefined,
    props: {},
  ) => React.ReactElement;
  children: React.ReactElement | React.ReactElement[] | undefined;
}

// definition
export const switchRender = ({
  isTrue,
  render,
  children,
  ...props
}: PropsType): React.ReactElement | React.ReactElement[] | undefined =>
  isTrue ? render(children, props) : children;
```

Error:

```js

  14 |   children,
  15 |   ...props
> 16 | }: PropsType): React.ReactElement | React.ReactElement[] | undefined =>
     |              ^
  17 |   isTrue ? render(children, props) : children;

```

**Expected behavior**

Error should not be here.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
{
  presets: [
    [
      '@babel/env',
      {
        useBuiltIns: 'usage',
        corejs: 3,
      },
    ],
    '@babel/react',
    '@babel/preset-typescript',
  ],
  ...
}
```

**Environment**

```
System:
    OS: macOS 10.15.6
  Binaries:
    Node: 12.19.0 - /usr/local/opt/node@12/bin/node
    Yarn: 1.22.10 - ~/Desktop/work/meep-lerna/node_modules/.bin/yarn
    npm: 6.14.8 - /usr/local/opt/node@12/bin/npm
  Monorepos:
    Yarn Workspaces: 1.22.10
    Lerna: 3.22.1
  npmPackages:
    @babel/cli: ^7.7.0 => 7.12.1
    @babel/core: ^7.7.2 => 7.12.1
    @babel/plugin-proposal-class-properties: ^7.7.0 => 7.12.1
    @babel/plugin-proposal-decorators: ^7.7.0 => 7.12.1
    @babel/plugin-proposal-export-default-from: ^7.5.2 => 7.12.1
    @babel/plugin-proposal-nullish-coalescing-operator: ^7.7.4 => 7.12.1
    @babel/plugin-proposal-optional-chaining: ^7.6.0 => 7.12.1
    @babel/plugin-transform-runtime: ^7.6.2 => 7.12.1
    @babel/preset-env: ^7.7.1 => 7.12.1
    @babel/preset-react: ^7.7.0 => 7.12.1
    @babel/preset-typescript: ^7.7.2 => 7.12.1
    @babel/runtime: ^7.7.2 => 7.12.1
    babel-eslint: ^10.0.3 => 10.1.0
    babel-jest: ^24.9.0 => 24.9.0
    babel-loader: ^8.0.5 => 8.1.0
    babel-plugin-css-modules-transform: ^1.6.1 => 1.6.2
    babel-plugin-module-resolver: ^3.1.1 => 3.2.0
    babel-plugin-transform-imports: ^2.0.0 => 2.0.0
    eslint: ^6.7.2 => 6.8.0
    eslint-import-resolver-babel-module: ^5.0.0-beta.1 => 5.1.2
    jest: ^24.9.0 => 24.9.0
    lerna: ^3.19.0 => 3.22.1
    webpack: ^4.41.2 => 4.44.2
```
- Babel version(s): v7.12.1
- Node/npm version: Node 12.19.0/npm 6.14.8
- OS: OSX 10.15.6
- Monorepo: Lerna
- How you are using Babel: cli

**Possible Solution**

I think this bug is caused by #12183 

**Additional context**

**Comment by JLHwung** [comment] 2020-10-16 03:34
Duplicate of #12196

**Closed by JLHwung** 2020-10-16 03:34 UTC
Labels: i: bug, i: needs triage
