### ISSUE TITLE
Arrow-function default parameter not behaving as expected in MS Edge

### ISSUE THREAD

**Issue by Floriferous** [babel/babel#8759] opened 2018-09-24 14:31 UTC
## Bug Report

This React code here does not work on MS Edge, but does work on other browsers I tested (Chrome, Safari, Firefox):

```js
class App extends Component {
  state = { counter: 0 };

  handleClick = () => {
    this.setState({ counter: this.state.counter + 1 }, () => {
      console.log(this); // checkState is a function instead of arrow function in MS Edge,
      // leading to incorrect context, and crash when checking this
      this.checkState();
    });
  };

  checkState = (stuff = true) => {
    const { counter } = this.state;
    console.log('stuff', stuff);
    console.log('counter', counter);
  };

  render() {
    const { counter } = this.state;

    return (
      <div className="App">
        <button onClick={this.handleClick}>Click me {counter}</button>
      </div>
    );
  }
}
```

Here's a reproduction in a meteor app: https://github.com/Floriferous/ms-edge-arrow-default-param

Here's the .babelrc:
```json
{
  "presets": ["meteor", "@babel/preset-flow"],
  "plugins": [
    ["@babel/plugin-proposal-class-properties"]
  ]
}
```

The checkState arrow function is transformed into a function, because of the unsupported default param (I guess). And so `this` is not defined when `checkState` is called in the callback.

- Babel version(s): [ v7.1.0]
- Node/npm version: [Node 8/npm 5]
- OS: [OSX 10.13.6]
- Monorepo [e.g. yes]
- How you are using Babel: [Not sure]

**Comment by nicolo-ribaudo** [comment] 2018-09-25 16:50
I don't have MS Edge so I can't reproduce it, but
1) What error are you seeing in edge?
2) What is the output that Babel generates for that code?

**Comment by tducasse** [comment] 2019-03-20 00:21
Just encountered the same problem on Edge 17 (seemed to work on 18).
Basically says that `this` is `undefined`.

Basically, writing a function like this:
```js
class MyComponent extends React.Component {
  myFunc = (param = 'myValue') => {
    console.log(this); // undefined in Edge 17
    [...]
  }
}
```
transpiles to a normal function instead of an arrow function
```js
function () {
  let param = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : false;
  [...]
}
```

**Comment by nicolo-ribaudo** [comment] 2019-03-20 18:32
Could you post the full output for this code?
```js
class MyComponent extends React.Component {
  myFunc = (param = 'myValue') => {
    console.log(this); // undefined in Edge 17
  }
}
```

I get this working output:
```js
class MyComponent extends React.Component {
  constructor() {
    var _this;

    super(...arguments);
    _this = this;

    _defineProperty(this, "myFunc", function () {
      let param = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : 'myValue';
      console.log(_this); // undefined in Edge 17
    });
  }

}
```

**Comment by loganfsmyth** [comment] 2019-03-20 18:43
Is this potentially fixed in https://github.com/babel/babel/issues/8019? It could be the same issue where `_this = super()` ends up setting `_this` to `undefined`.

**Comment by tducasse** [comment] 2019-03-21 06:00
This is what I get:
```js
class MyComponent extends React.Component {
  constructor() {
    var _this;

    _this = super(...arguments);;

    _defineProperty(this, "myFunc", function () {
      let param = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : 'myValue';
      console.log(_this); // undefined in Edge 17
    });
  }
}
```

**Comment by nicolo-ribaudo** [comment] 2019-03-21 07:29
Which version are you using? It should be fixed by #8019, as Logan mentioned.

**Comment by tducasse** [comment] 2019-03-24 22:28
I am not entirely sure since I use Meteor v1.8...

**Comment by nicolo-ribaudo** [comment] 2019-03-24 23:14
You can check it by running `npx nls why @babel/traverse`.

**Comment by tducasse** [comment] 2019-03-24 23:28
Thanks!
Everything seems to be using `7.2.3`, except this one: `babel-eslint > @babel/traverse@7.0.0-beta.44`.

**Comment by nicolo-ribaudo** [comment] 2019-03-25 22:56
That shouldn't affect it :thinking:
Would you be able to create a repository which shows the issue?

**Comment by nicolo-ribaudo** [comment] 2019-03-25 22:58
Would you be able to create a repository which shows the issue? In the OP's example it's because the package-lock.json specifies Babel v7.1.0.

**Comment by nicolo-ribaudo** [comment] 2019-05-14 20:37
@tducasse Is this still an issue?

**Comment by tducasse** [comment] 2019-05-15 00:22
I have solved my problem by simply removing the arrow function that was causing it. Not sure it's still a problem, so feel free to close the issue 👍 
(Sorry for not being able to create a repo to show the issue)

**Comment by nicolo-ribaudo** [comment] 2019-05-15 05:36
Ok, I'm closing this since it should be fixed by https://github.com/babel/babel/issues/8019 :+1:
Probably for some reason Babel was picking up an old version of `@babel/traverse` in your project.

**Closed by nicolo-ribaudo** 2019-05-15 05:36 UTC
