### ISSUE TITLE
Invalid scoping in `for in` blocks.

### ISSUE THREAD

**Issue by ChALkeR** [babel/babel#833] opened 2015-02-19 14:41 UTC
**I did not check the specs on the scopes, but I am assuming that v8 behavior is correct and that in `for (let a of/in b)` part `b` should be outside of the `for` scope. This is how v8 does things. This is also how babel does things in `for of` blocks.**

=====
```javascript
"use strict";
var a = [[], [1, 2, 3]];
var i = 1;
for (let i in a[i]) {
    console.log(i);
}
```
is translated to
```javascript
"use strict";
var a = [[], [1, 2, 3]];
var i = 1;
for (var _i in a[_i]) {
    console.log(_i);
}
```
when it should be translated to
```javascript
"use strict";
var a = [[], [1, 2, 3]];
var i = 1;
for (var _i in a[i]) {
    console.log(_i);
}
```

===========
A similar (or the same) issue:
```javascript
"use strict";
{
  let i = [1, 2, 3];
}
for (let i in i) {
  console.log(i);
}
```
should have the same variable renames (not the same code) as in
```javascript
"use strict";
{
  let i = [1, 2, 3];
}
var i;
for (let i in i) {
  console.log(i);
}
```
but no variables are renamed in the first variant.

**Comment by fkling** [comment] 2015-02-19 17:25
I could be wrong here (the spec can be hard to read) but it looks to me that `b` should be evaluated in an environment where the bindings of `a` are declared:


> [13.6.4.11 Runtime Semantics: LabelledEvaluation](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-for-in-and-for-of-statements-runtime-semantics-labelledevaluation)
>
*IterationStatement* : <code>for ( <i>ForDeclaration</i> in <i>Expression</i> ) <i>Statement</i></code>
> 1. *Let keyResult* be the result of performing ForIn/OfHeadEvaluation(BoundNames of *ForDeclaration*, *Expression*, enumerate, *labelSet*).

In your example, "BoundNames of *ForDeclaration*" is `["i"]`.

[`ForIn/OfHeadEvaluation` is defined as](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-runtime-semantics-forin-div-ofheadevaluation-tdznames-expr-iterationkind-labelset):

> 
1. Let *oldEnv* be the running execution context’s LexicalEnvironment.
2. If *TDZnames* is not an empty List, then
  1. Assert: *TDZnames* has no duplicate entries.
  2. Let *TDZ* be NewDeclarativeEnvironment(*oldEnv*).
  3. For each string *name* in *TDZnames*, do
    1. Let *status* be *TDZ*.CreateMutableBinding(*name*, false).
    2. Assert: *status* is never an abrupt completion.
  4. Set the running execution context’s LexicalEnvironment to *TDZ*.
3. Let *exprRef* be the result of evaluating the production that is *expr*.

So it seems to be that *Expression* is evaluated in an environment with the bindings for `ForDeclaration`.

**Comment by ChALkeR** [comment] 2015-02-19 18:21
Just checked how does the Firefox js engine treat the above code samples, and it treats them the same as v8.

**Comment by sebmck** [comment] 2015-02-20 15:19
Current JavaScript engines aren't really a reliable reference, especially when it's completely broken in Firefox, see [this bugzilla issue](https://bugzilla.mozilla.org/show_bug.cgi?id=950547).

**Comment by sebmck** [comment] 2015-02-20 15:21
Yeah, I interpreted the spec exactly as you did @fkling. @ChALkeR I told you that this was expected behaviour when you bought it up in gitter.

Going to investigate this more to double check but unless you have spec citations that contradict this behaviour I'm going to close this.

**Comment by ChALkeR** [comment] 2015-02-20 15:51
Then the `for of` behaviour is unexpected.

**Comment by sebmck** [comment] 2015-02-20 15:53
I'm having trouble understanding what the specific issue is. Can you provide code examples and explanations?

**Comment by sebmck** [comment] 2015-02-20 15:57
I know you've already provided examples but those were for `for...in` now you're telling me the issue is actually in `for...of`?

**Comment by ChALkeR** [comment] 2015-02-20 15:59
Using babel, compare
```javascript
"use strict";
var a = [[], [1, 2, 3]];
var i = [1, 2, 3];
for (let i in a[i] || [0]) {
    console.log(i);
}
```
> 0

and
```javascript
"use strict";
var a = [[], [1, 2, 3]];
var i = 1;
for (let i of a[i] || [0]) {
    console.log(i);
}
```
> 1
2
3

**Comment by ChALkeR** [comment] 2015-02-20 16:10
@sebmck, I am telling that results of `for in` do not correspond with results of `for of`. One of them is incorrect. If you are right and in `for in` blocks babel behaves correctly (with both v8 and firefox behaving incorrectly), then the `for of` behavior in babel is incorrect.

**Comment by sebmck** [comment] 2015-02-20 16:56
Your code example and the actual output are correct. Your first example is equivalent to:

```javascript
for (var key in [0]) {
  key === "0";
}
```

and your second one equivalent to:

```javascript
var nums = [1, 2, 3];
for (var i = 0; i < nums.length; i++) {
  i; // 1, 2, 3
}
```

I'm not saying there's not an issue because there probably is because I have an outstanding scoping issue that I'm fixing right now that may be related?

**Comment by ChALkeR** [comment] 2015-02-20 17:01
Sorry, I made a mistake while I was typing the first code sample of those two.
I corrected it, could you re-check, please?

**Comment by fkling** [comment] 2015-02-20 17:38
Lets just look at [this simplified example](http://babeljs.io/repl/#?experimental=true&playground=true&evaluate=true&loose=false&spec=false&code=%22use%20strict%22%3B%0Avar%20i%20%3D%20%5B1%2C2%2C3%5D%3B%0Afor%20(let%20i%20of%20i)%20%7B%0A%20%20%20%20console.log(i)%3B%0A%7D):

```js
"use strict";
var i = [1,2,3];
for (let i of i) {
    console.log(i);
}
```

converts to

```
"use strict";
var i = [1, 2, 3];
for (var _iterator = i[Symbol.iterator](), _step; !(_step = _iterator.next()).done;) {
    var _i = _step.value;
    console.log(_i);
}
```

`var _iterator = i[Symbol.iterator]()` should be `var _iterator = _i[Symbol.iterator]()` instead or whatever, but it should not refer to `i`.

**Comment by ChALkeR** [comment] 2015-02-20 18:38
From the discussion at irc.mozilla.org#jsapi it looks like your reading of the spec is correct and that neither of `if` and `of` results are correct here: both thould just throw an expection due to TDZ and the binding is not being initialized at that point.

Without TDZ checks, any behaviour is wrong and there is nothing to fix here.

@fkling, @sebmck, could this be closed now?

**Comment by ChALkeR** [comment] 2015-02-20 19:13
https://bugzilla.mozilla.org/show_bug.cgi?id=1135167 — reported.

**Comment by sebmck** [comment] 2015-02-20 23:36
@ChALkeR Yup. Thanks for looking into this though! Better to be safe than sorry.

**Closed by sebmck** 2015-02-20 23:36 UTC
