### ISSUE TITLE
repl: imported modules are undefined on subsequent lines

### ISSUE THREAD

**Issue by premasagar** [babel/babel#2007] opened 2015-07-15 16:58 UTC
In the Babel repl, imported modules are available on the same line of code as the `import` statement, but the reference is lost on subsequent lines:

```js
> import route from './src/route'; typeof route === 'object'
true
> typeof route === 'object'
false
```

This problem doesn't take placing when `require`ing a module.
A workaround is to assign the module to a variable on the same line, or use `require`.

**Comment by sebmck** [comment] 2015-07-15 16:59
Duplicate of #1728, #1488 and #1264.

**Closed by sebmck** 2015-07-15 16:59 UTC

**Comment by premasagar** [comment] 2015-07-15 18:56
Sorry, don't know how I missed all of those.
