### ISSUE TITLE
Bug: Accessing this inside async/await returns undefined

### ISSUE THREAD

**Issue by adeelshahid** [babel/babel#6806] opened 2017-11-12 17:00 UTC
same as the issue #2765 

```js
const LockIcon = styled.img.attrs({
  src: loginImg,
})``

class Login extends React.Component {
  async onLogin() {
    console.log('this', this)
    try {
      const result = await Database.login()
    } catch (err) {
      console.log('err', err)
    }
  }

  render() {
    return isEmpty(this.props.user) ? <LockIcon onClick={this.onLogin} /> : null
  }
}
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)
```{
  "presets": [
    [
      "env",
      {
        "modules": false,
        "loose": true,
        "targets": {
          "uglify": true
        }
      }
    ],
    "react"
  ],
  "plugins": [
    "react-hot-loader/babel",
    "transform-object-rest-spread",
    "transform-function-bind",
    "transform-class-properties",
    "transform-decorators-legacy",
    "transform-runtime"
  ]
}
```

```js
{
  "your": { "config": "here" }
}
```

### Expected Behavior
This should point to Class instance. Even using *onLogin = async () => {}* returns undefined.

### Current Behavior
It returns undefined. Async functions should not change *this* context.

| software         | version(s)
| ---------------- | -------
| Babel            |  6.26.0
| node             | 8.7.0
| npm              | 4.6.1
| Operating System | Mac OSX High Sierra

**Comment by loganfsmyth** [comment] 2017-11-12 17:47
Your example is expected to fail, but the `onLogin = async () => {}` you mentioned should work. Are you sure it failed?

**Comment by Andarist** [comment] 2017-11-12 17:54
I've checked that it doesn't work, can be verified [here](https://deploy-preview-1460--babel.netlify.com/repl#?babili=false&browsers=&build=&builtIns=false&code_lz=MYewdgzgLgBAMiYBrAkqMMC8NoE8A2ApgCYB0AlgLYDmpAhlFAE4QAUA3gFAw5PABcMfCGrkwKGgBpOAXwCUAAwWdOwfHQgR4IsTEIAPKITDEtAJUJ1gUUgGEQlAA7hjsLj3AJRGbBtxhgGAAzAFcAqHJwVjkYdx4YdAgQIlJhalYAcigAC3IIDMkYHLy5bnjmXFiy-ITwaBgmQggQ_FhfAHc6clgAEQY6ACMNQlSdMGjqmBkEhmBsmFZCJiYYuJrE5JG0zKWmAr1l0pqZMpOyxpMl6KqaxqgQpgw8gFEnKFxWYohSRyYQR2-IQgSxiAH4YAAeBDINDgGDgWz4cjITDsL6kTxjaYAegAfDBBGAWvhTrIgA&debug=false&circleciRepo=&evaluate=false&lineWrap=true&presets=es2015-loose%2Ces2017%2Creact%2Cstage-0&targets=&version=7.0.0-beta.32)

**Comment by loganfsmyth** [comment] 2017-11-12 18:27
@Andarist If it's not an arrow function then that's expected. If it's an arrow it gets turned into `console.log('this', _this);` though which should work fine.

**Comment by Andarist** [comment] 2017-11-12 21:10
Non-arrow functions works though too, `this` is not rewritten but as the function gets attached to the instance (with `defineProperty`) it points to the instance. I guessed that async should behave the same.

[Example](https://deploy-preview-1460--babel.netlify.com/repl#?babili=false&browsers=&build=&builtIns=false&code_lz=MYGwhgzhAECyCeBhcVoG8BQ1oAcBOA9jtALzQBmArgHbAAuAlgdQBQCU6W20wzEBIAKYA6EAQDmLAOR0AFgwhSANNDkK2XAL5cuYPIQDuABULEy7UgD5O3HnwEixkmfMUq1EDdm3ZdEeLQmRKTQkAHAFDT0TNTQFpi2vNT8QqIS0h7Kqq5e0NqaQA&debug=false&circleciRepo=&evaluate=false&lineWrap=true&presets=es2015%2Ces2017%2Creact%2Cstage-0&targets=&version=7.0.0-beta.31)

**Comment by loganfsmyth** [comment] 2017-11-13 01:59
@Andarist The code sample in the issue is `<LockIcon onClick={this.onLogin} />` so it'll call `onLogin` with no context, which means binding is a requirement for it to work for the given usecase.

**Comment by Andarist** [comment] 2017-11-13 07:21
You are right, I've misread async's output and the `this` there points to the instance too.

**Comment by yakovenkoroman1993** [comment] 2018-01-19 04:43
I have the same problem. With async/await **console.log(this)** inside arrow function outputs **undefined** 
![image](https://user-images.githubusercontent.com/13461433/35135149-c32bc03e-fd0d-11e7-8a95-893f6d93d09e.png)

**Comment by eldyvoon** [comment] 2018-03-14 08:34
+1, doesn't work with react? I've this config in .babelrc

``["transform-runtime", {
      "polyfill": false,
      "regenerator": true
    }]``

**Comment by adeelshahid** [comment] 2018-03-14 09:17
@eldyvoon 

try the following process,

1. Bind async function inside the constructor.
2. Write async function as a normal function.

*Example*

```js
constructor(props) {
  super(props)
  this.asyncFunc = this.asyncFunc.bind(this)
}

async function asyncFunc() {
  try {
    const result = await window.fetch(...)
  } catch (e) {}
}
```

**Comment by eldyvoon** [comment] 2018-03-14 09:31
@adeelshahid why can't I use arrow function?  ``handleChange = async (e) => {}``

**Comment by adeelshahid** [comment] 2018-03-14 10:18
@eldyvoon babel transpilation doesn't correctly handle `this` referencing when using bind and async together. Therefore I offered a workaround.

**Comment by Kovensky** [comment] 2018-03-15 01:08
This [was a bug with react-hot-loader@3](https://github.com/gaearon/react-hot-loader/issues/391); it should be fixed with react-hot-loader@4.

**Comment by yakovenkoroman1993** [comment] 2018-03-17 04:38
This issue is reproduced in react-hot-loader 4. I checked it.

**Comment by eldyvoon** [comment] 2018-03-17 06:18
@yakovenkoroman1993 if you don't mind, just use arrow function in jsx and do `async urFunc() { console.log(this) }` it will work.

**Closed** 2018-03-17 15:43 UTC
