### ISSUE TITLE
ModuleNotFoundError: Module not found: Error: Can't resolve 'core-js/library/fn/object/define-property'

### ISSUE THREAD

**Issue by nuintun** [babel/babel#9734] opened 2019-03-21 10:16 UTC
## Bug Report

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  presets: [
    [
      '@babel/preset-env',
      {
        loose: true,
        modules: false,
        targets: { browsers: ['last 2 versions', 'Firefox ESR', '> 1%', 'ie >= 10', 'iOS >= 8', 'Android >= 4'] }
      }
    ]
  ],
  plugins: [
    '@babel/plugin-syntax-dynamic-import',
    ['@babel/plugin-proposal-decorators', { legacy: true }],
    ['@babel/plugin-transform-runtime', { useESModules: true }],
    ['@babel/plugin-proposal-class-properties', { loose: true }],
    ['@babel/plugin-proposal-object-rest-spread', { useBuiltIns: true }],
    ['import', { style: true, libraryName: 'antd', libraryDirectory: 'es', style: true }]
  ],
  env: {
    development: {
      presets: [['@babel/preset-react', { development: true, useBuiltIns: true }]]
    },
    production: {
      presets: [['@babel/preset-react', { useBuiltIns: true }]],
      plugins: [['transform-react-remove-prop-types', { removeImport: true }]]
    }
  }
};
```

**Environment**
- Babel version(s): 7.4.0
- Node/npm version: 11
- OS: Windows 10

Babel version(s): 7.3.4 is ok!

```
ModuleNotFoundError: Module not found: Error: Can't resolve 'core-js/library/fn/object/set-prototype-of' in 'D:\WORKSPACE\node_modules\babel-runtime\core-js\object'
    at factory.create (D:\WORKSPACE\node_modules\webpack\lib\Compilation.js:823:10)
    at factory (D:\WORKSPACE\node_modules\webpack\lib\NormalModuleFactory.js:397:22)
    at resolver (D:\WORKSPACE\node_modules\webpack\lib\NormalModuleFactory.js:130:21)
    at asyncLib.parallel (D:\WORKSPACE\node_modules\webpack\lib\NormalModuleFactory.js:224:22)
    at D:\WORKSPACE\node_modules\neo-async\async.js:2825:7
    at D:\WORKSPACE\node_modules\neo-async\async.js:6886:13
    at normalResolver.resolve (D:\WORKSPACE\node_modules\webpack\lib\NormalModuleFactory.js:214:25)
    at doResolve (D:\WORKSPACE\node_modules\enhanced-resolve\lib\Resolver.js:184:12)
    at hook.callAsync (D:\WORKSPACE\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (D:\WORKSPACE\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:15:1)
    at resolver.doResolve (D:\WORKSPACE\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:37:5)
    at hook.callAsync (D:\WORKSPACE\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (D:\WORKSPACE\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:15:1)
    at hook.callAsync (D:\WORKSPACE\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (D:\WORKSPACE\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:12:1)
    at resolver.doResolve (D:\WORKSPACE\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:42:38)
    at hook.callAsync (D:\WORKSPACE\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn42 (eval at create (D:\WORKSPACE\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:390:1)
    at resolver.doResolve (D:\WORKSPACE\node_modules\enhanced-resolve\lib\ModuleKindPlugin.js:23:37)
    at hook.callAsync (D:\WORKSPACE\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (D:\WORKSPACE\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:15:1)
    at hook.callAsync (D:\WORKSPACE\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn1 (eval at create (D:\WORKSPACE\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:24:1)
    at hook.callAsync (D:\WORKSPACE\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (D:\WORKSPACE\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:15:1)
    at resolver.doResolve (D:\WORKSPACE\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:37:5)
    at hook.callAsync (D:\WORKSPACE\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (D:\WORKSPACE\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:15:1)
    at hook.callAsync (D:\WORKSPACE\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (D:\WORKSPACE\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:12:1)
    at resolver.doResolve (D:\WORKSPACE\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:42:38)
    at hook.callAsync (D:\WORKSPACE\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn43 (eval at create (D:\WORKSPACE\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:402:1)
    at hook.callAsync (D:\WORKSPACE\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (D:\WORKSPACE\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:12:1)
    at resolver.doResolve (D:\WORKSPACE\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:42:38)
resolve 'core-js/library/fn/object/set-prototype-of' in 'D:\WORKSPACE\node_modules\babel-runtime\core-js\object'
  Parsed request is a module
  using description file: D:\WORKSPACE\node_modules\babel-runtime\package.json (relative path: ./core-js/object)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      looking for modules in D:\WORKSPACE\Assets\src
        using description file: D:\WORKSPACE\package.json (relative path: ./Assets/src)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: D:\WORKSPACE\package.json (relative path: ./Assets/src/core-js/library/fn/object/set-prototype-of)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              D:\WORKSPACE\Assets\src\core-js\library\fn\object\set-prototype-of doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              D:\WORKSPACE\Assets\src\core-js\library\fn\object\set-prototype-of.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              D:\WORKSPACE\Assets\src\core-js\library\fn\object\set-prototype-of.jsx doesn't exist
            as directory
              D:\WORKSPACE\Assets\src\core-js\library\fn\object\set-prototype-of doesn't exist
      looking for modules in D:\WORKSPACE\node_modules
        using description file: D:\WORKSPACE\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: D:\WORKSPACE\node_modules\core-js\package.json (relative path: ./library/fn/object/set-prototype-of)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              D:\WORKSPACE\node_modules\core-js\library\fn\object\set-prototype-of doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              D:\WORKSPACE\node_modules\core-js\library\fn\object\set-prototype-of.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              D:\WORKSPACE\node_modules\core-js\library\fn\object\set-prototype-of.jsx doesn't exist
            as directory
              D:\WORKSPACE\node_modules\core-js\library\fn\object\set-prototype-of doesn't exist
```

**Comment by nicolo-ribaudo** [comment] 2019-03-21 10:19
Are you sure you are only using Babel 7? `babel-runtime` (in your stack trace) is from Babel 6

**Comment by frlinw** [comment] 2019-03-21 11:30
v7.4.0 forced me to install core-js@3 and then my build includes some unecessary polyfill:
![image](https://user-images.githubusercontent.com/11896237/54749496-02498280-4bd5-11e9-8cd7-7ab3f06008df.png)
![image](https://user-images.githubusercontent.com/11896237/54749444-d4fcd480-4bd4-11e9-8b65-5c6c8011c426.png)

Which browser does not support toFixed these days ?

**Comment by nicolo-ribaudo** [comment] 2019-03-21 11:39
It should be `corejs: 3`, not `corejs: "core-js@3"`

**Comment by frlinw** [comment] 2019-03-21 11:53
@nicolo-ribaudo Ok for `corejs` option syntax, I saw it from another thread, it does not change anything
retested with minor browsers exclusion, the result is exactly the same
```
"browserslist": [
    ">1%",
    "not ie > 0",
    "not op_mini all",
    "not and_uc > 0"
  ]
```

**Comment by nicolo-ribaudo** [comment] 2019-03-21 12:06
Could you try passing `targets: ">1%, not ie > 0"` to the preset-env options? If ti fixes the problem, it's a separate issue: for some reason it isn't reading the `browserlist` config.

**Comment by frlinw** [comment] 2019-03-21 12:11
The result is still the same with preset-env `targets` option

**Comment by zloirock** [comment] 2019-03-21 12:15
@frlinw I don't see anything unnecessary in your output.

**Comment by frlinw** [comment] 2019-03-21 12:19
@zloirock I just wonder why there is, for example, es.number.to-fixed.js which I'm sure is supported by these browsers:
```
npx browserslist
and_chr 70
chrome 70
chrome 69
edge 17
firefox 63
ios_saf 12.0-12.1
ios_saf 11.3-11.4
safari 12
```

**Comment by zloirock** [comment] 2019-03-21 12:30
See [tests](https://github.com/zloirock/core-js/blob/v3.0.0/tests/compat/tests.js#L540-L549) and [results](https://github.com/zloirock/core-js/blob/v3.0.0/packages/core-js-compat/src/data.js#L510-L514) - seems it's buggy in Edge.

**Comment by frlinw** [comment] 2019-03-21 13:43
@zloirock I didn't know about this file, it makes sense know, thanks !

**Comment by nuintun** [comment] 2019-03-22 01:18
@nicolo-ribaudo 

My package settings:

```json
{
  "dependencies": {
    "@antv/data-set": "^0.10.2",
    "@nuintun/fetch": "^0.3.2",
    "antd": "^3.15.1",
    "bizcharts": "^3.4.5",
    "classnames": "^2.2.6",
    "clipboard": "^2.0.4",
    "es6-shim": "^0.35.5",
    "immutable": "^3.8.2",
    "memoize-one": "^5.0.0",
    "prop-types": "^15.7.2",
    "rc-animate": "^2.6.0",
    "rc-flex-store": "^0.13.7",
    "rc-queue-anim": "^1.6.12",
    "rc-tween-one": "^2.3.4",
    "react": "^16.8.4",
    "react-dom": "^16.8.4",
    "react-lazyload": "^2.5.0",
    "react-loadable": "^5.5.0",
    "react-quill": "^1.3.3",
    "react-router-dom": "^5.0.0",
    "throttle-debounce": "^2.1.0"
  },
  "devDependencies": {
    "@babel/core": "^7.4.0",
    "@babel/plugin-proposal-class-properties": "7.4.0",
    "@babel/plugin-proposal-decorators": "7.4.0",
    "@babel/plugin-proposal-object-rest-spread": "^7.4.0",
    "@babel/plugin-syntax-dynamic-import": "7.2.0",
    "@babel/plugin-transform-runtime": "^7.4.0",
    "@babel/preset-env": "^7.4.2",
    "@babel/preset-react": "^7.0.0",
    "@babel/runtime": "^7.4.2",
    "autoprefixer": "^9.5.0",
    "babel-loader": "^8.0.5",
    "babel-plugin-import": "^1.11.0",
    "babel-plugin-transform-react-remove-prop-types": "^0.4.24",
    "case-sensitive-paths-webpack-plugin": "^2.2.0",
    "clean-webpack-plugin": "^2.0.1",
    "css-hot-loader": "^1.4.4",
    "css-loader": "^2.1.1",
    "file-loader": "^3.0.1",
    "friendly-errors-webpack-plugin": "^1.7.0",
    "html-webpack-bom-plugin": "^0.0.2",
    "html-webpack-plugin": "^3.2.0",
    "koa": "^2.7.0",
    "koa-compress": "^3.0.0",
    "koa-webpack": "^5.2.2",
    "less": "^3.9.0",
    "less-loader": "^4.1.0",
    "mini-css-extract-plugin": "^0.5.0",
    "node-notifier": "^5.4.0",
    "optimize-css-assets-webpack-plugin": "5.0.1",
    "postcss": "^7.0.14",
    "postcss-loader": "^3.0.0",
    "progress-bar-webpack-plugin": "^1.12.1",
    "style-loader": "^0.23.1",
    "uglifyjs-webpack-plugin": "^2.1.2",
    "url-loader": "^1.1.2",
    "webpack": "^4.29.6",
    "webpack-cli": "^3.3.0"
  }
}
```

But old version is work well:

```json
{
  "dependencies": {
    "@antv/data-set": "^0.10.2",
    "@nuintun/fetch": "^0.3.2",
    "antd": "^3.15.1",
    "bizcharts": "^3.4.5",
    "classnames": "^2.2.6",
    "clipboard": "^2.0.4",
    "es6-shim": "^0.35.5",
    "immutable": "^3.8.2",
    "memoize-one": "^5.0.0",
    "prop-types": "^15.7.2",
    "rc-animate": "^2.6.0",
    "rc-flex-store": "^0.13.7",
    "rc-queue-anim": "^1.6.12",
    "rc-tween-one": "^2.3.4",
    "react": "^16.8.4",
    "react-dom": "^16.8.4",
    "react-lazyload": "^2.5.0",
    "react-loadable": "^5.5.0",
    "react-quill": "^1.3.3",
    "react-router-dom": "^5.0.0",
    "throttle-debounce": "^2.1.0"
  },
  "devDependencies": {
    "@babel/core": "7.3.4",
    "@babel/plugin-proposal-class-properties": "7.3.4",
    "@babel/plugin-proposal-decorators": "7.3.0",
    "@babel/plugin-proposal-object-rest-spread": "7.3.4",
    "@babel/plugin-syntax-dynamic-import": "7.2.0",
    "@babel/plugin-transform-runtime": "7.3.4",
    "@babel/preset-env": "7.3.4",
    "@babel/preset-react": "7.0.0",
    "@babel/runtime": "7.3.4",
    "autoprefixer": "^9.5.0",
    "babel-loader": "^8.0.5",
    "babel-plugin-import": "^1.11.0",
    "babel-plugin-transform-react-remove-prop-types": "^0.4.24",
    "case-sensitive-paths-webpack-plugin": "^2.2.0",
    "clean-webpack-plugin": "^2.0.1",
    "css-hot-loader": "^1.4.4",
    "css-loader": "^2.1.1",
    "file-loader": "^3.0.1",
    "friendly-errors-webpack-plugin": "^1.7.0",
    "html-webpack-bom-plugin": "^0.0.2",
    "html-webpack-plugin": "^3.2.0",
    "koa": "^2.7.0",
    "koa-compress": "^3.0.0",
    "koa-webpack": "^5.2.2",
    "less": "^3.9.0",
    "less-loader": "^4.1.0",
    "mini-css-extract-plugin": "^0.5.0",
    "node-notifier": "^5.4.0",
    "optimize-css-assets-webpack-plugin": "5.0.1",
    "postcss": "^7.0.14",
    "postcss-loader": "^3.0.0",
    "progress-bar-webpack-plugin": "^1.12.1",
    "style-loader": "^0.23.1",
    "uglifyjs-webpack-plugin": "^2.1.2",
    "url-loader": "^1.1.2",
    "webpack": "^4.29.6",
    "webpack-cli": "^3.3.0"
  }
}
```

**Comment by nicolo-ribaudo** [comment] 2019-03-22 07:19
Could you check what I asked in https://github.com/babel/babel/issues/9734#issuecomment-475175676? (Sorry for all the unrelated comments that might have made you miss that one)

**Comment by ZOXEXIVO** [comment] 2019-03-22 07:39
I have same issue and installing core-js@^2.4.0 fixed this

```
Module not found: Error: Can't resolve 'core-js/es6/array' in ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es6/date' in ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es6/function' in ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es6/map' in ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es6/math' in 
.....
```

**Comment by nuintun** [comment] 2019-03-22 08:01
@nicolo-ribaudo Thanks, I installing core-js@^2.6.5 fixed this.

But old version is work well without installing core-js, very strange.

**Comment by nicolo-ribaudo** [comment] 2019-03-22 08:31
@nuintun I think that because  Babel internally depended on core-js@2, so it was in you node modules and npm hoisted it to the top-level node_modules folder.

You can read an explanation of what is happening (why Babel internally upgrading a non-exposed dependency broke many packages) at https://github.com/parcel-bundler/parcel/issues/2819#issuecomment-475008861, keeping in mind that it was probably "fault" of a dependency of your project.

@ZOXEXIVO I have no idea about how "fetch as Google" works. If you have a lockfile, you can check which corejs version was installed and re-install exactly that one.

**Comment by nuintun** [comment] 2019-03-22 08:53
@nicolo-ribaudo OK, I will check my project，thanks ~

**Comment by nicolo-ribaudo** [comment] 2019-03-22 08:56
If you find which package requires core-js without specifying it in their dependencies, please report it to them!

**Comment by nicolo-ribaudo** [comment] 2019-03-25 22:59
@nuintun Did you find the problem?

**Comment by nuintun** [comment] 2019-03-26 03:48
@nicolo-ribaudo Not sure yet, but maybe caused by `antd`, `antd` required old version `babel-runtime`.

**Comment by nicolo-ribaudo** [comment] 2019-03-26 05:55
How much old? It should correctly have `core-js` in it's dependencies: https://unpkg.com/babel-runtime@6.26.0/package.json

**Comment by nuintun** [comment] 2019-03-26 07:56
@nicolo-ribaudo 
I have created a repository that you can try: https://github.com/nuintun/babel-issues

**Comment by nicolo-ribaudo** [comment] 2019-03-26 08:07
Thanks, I will check it later today :+1:

**Comment by pferreir** [comment] 2019-04-23 13:01
I've also bumped into this issue and installing `core-js^2` worked fine.

**Comment by Zory1** [comment] 2019-05-15 07:34
I had upgraded angular packages to their latest today, including @angular-devkit/core to 7.2.15.  The project wouldn't build, complaining that

`Module not found: Error: Can't resolve 'core-js/es7/reflect' in .../polyfills.ts`, 
and same for `angular-cli-files/models`.

Then I noticed that whenever it cannot find something in `core-js,` , it tries to locate it in either `core-js/es7` or in `core-js/es6`. 

The version installed in this project was core-js 3.0.1. It was in node_modules but instead of having folders es6 and es7 it just had folder called `core-js/es` and inside that folder were all the good things that compiler couldn't find, e.g. 'symbol, object, function, parse-int' etc.

So I went ahead and updated my polyfills.ts to use proper path - e.g. instead of 
`import 'core-js/es6/symbol';`
to use
`import 'core-js/es/symbol';`

This fixed it for `polyfills.ts` but it still failed to compile because `angular-cli-files` of `@angular-devkit/core` had the same issue. In its own files it had imports that were pointing to core-js/es6 and core-js/es7 folders which would not work with latest core-js, as it puts everything into one `core-js/es` folder. I figured it is better stop there and had uninstalled latest core-js version, verified cache and installed, as good people suggested here earlier, older version of core-js.

`npm uninstall core-js --save`
`npm cache verify`
`npm install core-js^2 --save-exact`

Kind of sad as core-js 3 seems to have many new good looking polyfills. There is a good thread in existing feature request #13954 at angular-cli repository [here](https://github.com/angular/angular-cli/issues/13954). Basically, you could use latest core-js but you would need to update your tsconfig.json. Some people argue that this might be not needed as angular 7 specifically relies on older version of core-js for its own reasons.

**Comment by satsuya0114** [comment] 2019-05-28 10:01
Have same issue.

It's totally about the antd node_modules. ( use babel-runtime 6.X but not > 7.0.0 ) 

so antd use core-js @2

You cannot use core-js @3 in the project that use babel 7 and antd at the same time. 

So when you want to upgrade your project version that has antd modules. You should use core-js@2

( Finally I  installed core-js^2.6.9 to fix this issue )

**Comment by otech47** [comment] 2019-06-03 19:11
```
npm uninstall @babel/polyfill --save &&
npm install @babel/polyfill --save
```
did the trick for me.

**Comment by snahmad** [comment] 2019-07-16 08:27
I am getting this

ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es7/reflect' in 'C:\Work\Actisense\W2K1\angular\webApp\src'
ERROR in ./node_modules/ngx-restangular/fesm5/ngx-restangular.js
Module not found: Error: Can't resolve 'core-js/fn/object' in 'C:\Work\Actisense\W2K1\angular\webApp\node_modules\ngx-restangular\fesm5'

**Comment by nicolo-ribaudo** [comment] 2019-07-16 10:26
It's a bug with `ngx-restangular`, which uses `core-js` (see the first lines of https://unpkg.com/ngx-restangular@4.0.1/fesm5/ngx-restangular.js) but doesn't specify it as a dependency (https://unpkg.com/ngx-restangular@4.0.1/package.json).

I'm closing this issue, since it is caused by a lot of packages which we don't control and which use `core-js` without specifying it in their deps.

**Comment by nicolo-ribaudo** [comment] 2019-07-16 10:26
in

**Closed by nicolo-ribaudo** 2019-07-16 10:26 UTC

**Comment by snahmad** [comment] 2019-07-16 11:23
ok, I guess I need to chase ngx-restangular to get fixed or workaround using old version of core-js. I did try older version of core-js, still same error. I think 2.4.1. still same issue.
