### ISSUE TITLE
TCO for void functions

### ISSUE THREAD

**Issue by impinball** [babel/babel#1572] opened 2015-05-19 07:37 UTC
Void functions are supposed to also be candidates for proper tail calls if and only if they are in a tail call position. Or, in other words, this should be TCO'd:

```js
// Returns undefined (void function)
function skipWhile(cond) {
  if (!hasNext() || cond(current, last)) return;
  move();
  skipWhile(cond);
}
```

Sadly, I had to do this for it to compile correctly:

```js
function skipWhile(cond) {
  if (!hasNext() || cond(current, last)) return;
  move();
  return skipWhile(cond);
}
```

Can this be fixed?

**Comment by sebmck** [comment] 2015-05-20 09:12
Not sure how this would be handled. Might just label this as "expected behaviour" unless there's some nice way to achieve this. You're just exploding functions into while loops which means that if `skipWhile` returned some other statement then it would also be returned. ie:

```javascript
function foo(bar) {
  if (bar) {
   return "wow";
 } else {
  foo(true);
 }
}
foo() === "wow"; // nooooooo
```

 cc @RReverser

**Comment by RReverser** [comment] 2015-05-20 10:16
@sebmck Agree. From my understanding, this is not a tail call (I might be misunderstanding the spec though).

The idea for tail calls in any language is that when `call` instruction can be safely replaced with adjusting stack pointer + `jmp` instruction so that instead of call we just continue executing statements from the next given function as if they were part of original one. Now, that means that `return` from that following function will behave as if it would be `return` in original function (it's result should be passed through and returned from original call).

This is not happening in just a call without `return` in JavaScript since in fact it's implicitly expanded from

```javascript
  skipWhile(cond);
}
```

into

```javascript
  skipWhile(cond);
  return undefined;
}
```

so that our call is not really the last instruction happening in function and thus call is not tail.

**Comment by RReverser** [comment] 2015-05-20 10:21
That said, of course Babel could optimize even things out of scope of ES6 spec like your example (`skipWhile(cond);`), explicit return of constants like `skipWhile(cond); return someConst;`, operations that can be chained without calling but with counting like `return !skipWhile(cond);` / `return -skipWhile(cond);` / ... and so on, so if someone willing to play with such specific optimizations - they are very welcome to send PRs! @impinball

**Comment by impinball** [comment] 2015-05-20 12:41
It appears to be in the ES6 spec. [(here, it may take a little reading)](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-tail-position-calls)

**Comment by RReverser** [comment] 2015-05-20 13:20
Of course, I was referring to the same section of spec which was also used when implementing tail recursion.

Please point to exact sentence so that we would be on the same page.

**Comment by impinball** [comment] 2015-05-22 06:38
@RReverser Actually, I take that back...I misunderstood that section. You are correct in that observation. I saw the *CallExpression* rule in 14.6.2.2, thinking that i implied it, but it's the *Statement: ExpresssionStatement* rule in 14.6.2.1 that marks it as not required. It's just surprising.

I will still say it would be a nice thing to have, though, although a simple extra `return` is only 8 more characters to type.

**Comment by impinball** [comment] 2015-05-22 06:40
But at the same time, @sebmck, you have a good point on it being a potential foot-gun. (IMHO, that kind of code is pretty bad in the first place)

**Closed** 2015-05-31 08:07 UTC
Labels: enhancement, spec compliancy

**Comment by loganfsmyth** [comment] 2015-05-31 08:41
@sebmck Are we sure this is actually addressable? There still would need to be some knowledge of depth so that return statements properly return `undefined, e.g.

```
function fn(i){
    if (i < 0) return 'done!!';

    fn(i - 1);
}
```

becomes

```
function foo(_x) {
  var _again = true;

  _function: while (_again) {
    var i = _x;
    _again = false;
    if (i < 0) return 'done!';
    _x = i - 1;
    _again = true;
    continue _function;
  }
}
```

it should technically only return `'done!'` if explicitly called with something less than 0, but now it will return it with any integer value. Because the tail call doesn't return, we'd need to keep track of the call depth to know whether the `return 'done!'` should return the string, or undefined.

**Comment by sebmck** [comment] 2015-05-31 08:43
I don’t understand. Can you provide a full code example? Not sure what you’re getting at.

**Comment by RReverser** [comment] 2015-05-31 08:43
@loganfsmyth Agree. Such transformations are pretty dangerous even if all footguns are addressable, and since they're also not spec-compliant, better to do in separate transformer if at all.

**Comment by sebmck** [comment] 2015-05-31 08:44
Tail call optimisation is already dangerous anyway since as you can see by #1480 it already breaks code in a pretty serious way.

**Comment by loganfsmyth** [comment] 2015-05-31 08:48
@sebmck For my example, with this new branch, `fn(2) === 'done!'`, which is incorrect, `fn(2) === undefined` because the function returns nothing when `i >= 0`.

Needing that extra call-stack depth info leads me to believe that this type of call shouldn't be TCOed.

**Comment by sebmck** [comment] 2015-05-31 08:50
> Needing that extra call-stack depth info leads me to believe that this type of call shouldn't be TCOed.




Yeah, see the discussion in 07a992e6d35014ac9b8d188a89a16a39ce105f4a which led to it being reverted in bdb3adfeea48fd0d01674c0ca32aa44cace54b0a.

**Comment by loganfsmyth** [comment] 2015-05-31 08:50
Yeah I saw, just figured I'd clarify :)
