### ISSUE TITLE
Constructor Uint8Array requires 'new'

### ISSUE THREAD

**Issue by stevenvachon** [babel/babel#5464] opened 2017-03-13 18:25 UTC
```js
class Buffer extends Uint8Array {
	constructor(input) {
		if (isString(input) === true) {
			input = utf8.encode(input);
		}
		super(input);
	}

	static from(input) {
		return new Buffer(input);
	}

	toString() {
		return utf8.decode(this);
	}
}

new Buffer([1,2,3]);
```

**Comment by loganfsmyth** [comment] 2017-03-13 18:26
Copying from https://github.com/babel/babel/issues/5458#issuecomment-286131672

Thanks for reporting! Unfortunately, http://babeljs.io/docs/usage/caveats/#classes, Babel has a limitation with extending native classes.

I think this would be a duplicate of #4480 and others?

**Closed by loganfsmyth** 2017-03-13 18:26 UTC

**Comment by stevenvachon** [comment] 2017-03-13 18:28
Ok, thank you.

**Comment by loganfsmyth** [comment] 2017-03-13 18:34
The plugin mentioned in Caveats should make it work for you.

**Comment by stevenvachon** [comment] 2017-03-13 19:15
Awesome!
