### ISSUE TITLE
Computed properties, loose, and generator/async function

### ISSUE THREAD

**Issue by assaf** [babel/babel#1313] opened 2015-04-20 17:36 UTC
This issue seems to occur only when using a computed property in generator/async function and running in loose mode:

```
function *foo() {
  return {
    ['x']: null
  };
}
```

Compiles to:

```
var marked0$0 = [foo].map(regeneratorRuntime.mark);
function foo() {
  return regeneratorRuntime.wrap(function foo$(context$1$0) {
    while (1) switch (context$1$0.prev = context$1$0.next) {
      case 0:
        return context$1$0.abrupt('return', (_ref = {}, _ref.x = null, _ref));

      case 1:
      case 'end':
        return context$1$0.stop();
    }
  }, marked0$0[0], this);
}
```

Note that `_ref` is used but never declared. With a regular function, this compiles correctly to:

```
function foo() {
  var _ref;

  return (_ref = {}, _ref.x = null, _ref);
}
```

PS I couldn't figure out how to add this as a test case. Adding to `fixtures/esnext/es6-computed-properties` seems like the right thing, but how do I get this to compile in loose mode?

Some guideline in `CONTRIBUTING.md` would help.

Also, can't `make test` figure out all the dependencies (that it needs to build `lib/acorn`)?

**Comment by sebmck** [comment] 2015-04-20 17:37
Duplicate of #1268.

**Closed by sebmck** 2015-04-20 17:37 UTC
