### ISSUE TITLE
node_modules\react-native\index.js: Cannot read property 'bindings' of null

### ISSUE THREAD

**Issue by mks-94** [babel/babel#12274] opened 2020-10-29 05:16 UTC
Please help me to solve this..?
package.json
------------------------
```
{
  "name": "xxxx",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "^16.3.0-alpha.1",
    "react-native": "^0.63.3",
    "react-vf-common": "file:../react-vf-common"
  },
  "devDependencies": {
    "@types/jest": "^22.2.2",
    "@types/react": "^16.0.41",
    "@types/react-native": "^0.52.19",
    "@types/react-test-renderer": "^16.0.1",
    "babel-jest": "22.4.3",
    "babel-preset-react-native": "^4.0.0",
    "jest": "22.4.3",
    "react-addons-test-utils": "^15.6.2",
    "react-native-mock": "^0.3.1",
    "react-native-typescript-transformer": "^1.2.3",
    "react-test-renderer": "^16.3.0-alpha.1",
    "ts-jest": "^22.4.2",
    "typescript": "^2.8.1"
  },
  "jest": {
    "preset": "react-native",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js"
    ],
    "transform": {
      "^.+\\.(js)$": "<rootDir>/node_modules/babel-jest",
      "\\.(ts|tsx)$": "<rootDir>/node_modules/ts-jest/preprocessor.js"
    },
    "testRegex": "(/__tests__/.*|\\.(test|spec))\\.(ts|tsx|js)$",
    "testPathIgnorePatterns": [
      "\\.snap$",
      "<rootDir>/node_modules/",
      "<rootDir>/lib/"
    ],
    "cacheDirectory": ".jest/cache"
  }
}

```

**Comment by AjayPoshak** [comment] 2020-10-29 08:38
I don't think this has anything to do with babel.

**Comment by nicolo-ribaudo** [comment] 2020-10-29 09:22
If this error is thrown by Babel (we use a `.bindings` property in some transforms), we'll need a stack trace and a reproducible example.

**Comment by nicolo-ribaudo** [comment] 2021-01-30 14:16
Closing since we cannot reproduce this issue.

**Closed by nicolo-ribaudo** 2021-01-30 14:16 UTC
Labels: i: enhancement, i: needs reproduction
