### ISSUE TITLE
babel-plugin-transform-es2015-parameters beta.

### ISSUE THREAD

**Issue by simonjoom** [babel/babel#6287] opened 2017-09-21 16:15 UTC
bug report:

With the new version supported loose mode i have got some trouble with prerender,

my application compiled with Loose: true work good on browser
But server side it's not working my prerender cannot see window.prerenderready=true 

seems window is lost when we use babel-plugin-transform-es2015-parameters in Loose mode

So i went back to babel-plugin-transform-es2015-parameters alpha.20 to let prerender do his work  

i guess the problem is inherent with transform-es2015-parameters loose mode 

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7.beta
| node             |  8.5
| npm              |  latest
| Operating System |

**Comment by loganfsmyth** [comment] 2017-09-21 16:32
You erased our issue template, it asks for Input Code for a reason. There is no way we can guess what the problem is, you need to give us an example that causes the problem.

**Comment by simonjoom** [comment] 2017-09-21 16:51
Unfortunately i cannot give an example easily 

it's inherent to prerender , i cannot show a part of code where it's happening,

I use window.prerenderready=false; in my main application.
This switch allow to say to prerender to wait till the rendering process is finish or not.


I use window.prerenderready=true;  in a code to say to prerender that he can take the output.

my code work well , but with loose mode it's seems that prerender cannot see the property prerenderready of object window 

to understand the use of prerenderready it's here: https://prerender.io/documentation/best-practices

**Comment by loganfsmyth** [comment] 2017-09-21 17:05
If this is an issue with the parameter transform, there must be some specific function in your code that is not being handled correctly. We need to know what function that is and what part of it is not transformed correctly. I don't necessarily need your real production code, but I'll need you to trim down your code to a small piece that reproduces the problem on its own. If you can't give production code, you can always write a new snippet of code that follows the same structure to reproduce the issue. You say you checked the compiled code, so you'll need to look at that and figure out what is being transformed incorrectly.

The details of `prerender` aren't particularly useful because that is not enough to recreate the problem.

> But server side it's not working my prerender cannot see window.prerenderready=true

is also confusing to me because there is no `window` object on a server in the first place, but I'd rather not focus on that.

**Comment by simonjoom** [comment] 2017-09-21 19:35
well , the function is not so specific, just create a simple application (SPA)
window.prerenderready=false; is in the main entry chunk and no function around (it's in top Level) 

to test it in same environment as me:
create a very simple SPA application 
In the global code of the entry point 
add window.prerenderready=false;  

Nota i use entry chunk with common chunk  
i use last web pack 3 

my web-pack config (simplified)
 entry: {
    main: ["babel-polyfill","main.js"]
vendor:["react"] //just add some lib
}
config.plugins.push(new webpack.optimize.CommonsChunkPlugin({
  name: 'vendor',
  chunks: ['main'],
  minChunks: Infinity
}));

devtool to false (no map)
parse it with babel 7 beta in loose mode then test to render it with prerender

You should to have the same bug as me , 

you should to have no timeout loop of prerender -> prerender finish successfully and it's a bug because you didn't define window.prerenderReady to true on a next line;  

So it's look like prerender don't see correctly window.prerenderReady

**Comment by nicolo-ribaudo** [comment] 2017-09-21 19:42
Hi, can you create a simple repository which can be downloaded to reproduce the bug? This would make it easier to debug and solve the issue.

**Comment by loganfsmyth** [comment] 2017-09-21 19:44
I want to get this fixed for you, but please try to appreciate this from my side. I have no clear instructions of how to reproduce this issue, I don't know anything about prerender, I don't even have a description of the bug you are reporting. Even if I got a setup working, I don't have a clear picture of what I'd be looking for. You're asking me to take what could end up being an hour or two to reproduce a bug, when you already know how to reproduce it. We're all volunteers, and it's not reasonable to ask us to do all that for you without a clear picture of what we'd even be looking for.

**Comment by simonjoom** [comment] 2017-09-21 19:46
ok i will do recreate this bug in my time  (i will recreate a simple SPA for it

**Comment by loganfsmyth** [comment] 2017-09-21 19:52
If that is what it will take then that'd be great. Usually it's possible to trim down the code to short examples of the input ES6 and the output ES5 to demonstrate what the incorrect transpiled output is, which would avoid needing an entire application to reproduce the issue though.

**Comment by jridgewell** [comment] 2017-09-22 23:03
This is likely caused by https://github.com/babel/babel/issues/6287.

**Comment by simonjoom** [comment] 2017-09-23 04:44
i guess you mean  this ?
https://github.com/babel/babel/pull/6274

**Comment by jridgewell** [comment] 2017-09-23 05:11
Lol, whoops.

**Comment by jridgewell** [comment] 2017-09-26 14:19
Closing this as likely fixed by #6274. This will be released with `7.0.0-beta.2`

**Closed by jridgewell** 2017-09-26 14:19 UTC
Labels: Needs Info

**Comment by simonjoom** [comment] 2017-10-01 05:44
I confirm beta.2 resolved my issue with prerender , working good now

**Comment by hzoo** [comment] 2017-10-02 02:06
Awesome
