### ISSUE TITLE
Add API to accept AST as source code input

### ISSUE THREAD

**Issue by impinball** [babel/babel#2429] opened 2015-09-24 05:32 UTC
Babel is already an insanely powerful tool as is, but being able to input an AST would allow people using other AST utilities outside of Babel (e.g. UglifyJS2) or even languages that generate ESTree ASTs (like the experimental [eslisp](https://github.com/anko/eslisp)) to plug in the output into Babel.

As for prior art, UglifyJS2 accepts its own AST as well as the ESTree AST.

I doubt it would be hard to do this, considering this would simply skip a step for the general algorithm (~~parse~~, transform, generate).

**Comment by jridgewell** [comment] 2015-09-24 14:23
Babel already has `transform.fromAst`.

**Comment by sebmck** [comment] 2015-09-24 14:40
Duplicate of #1122.

**Closed by sebmck** 2015-09-24 14:40 UTC

**Comment by impinball** [comment] 2015-09-24 23:20
Thanks. I wish it were documented, though (it doesn't appear to be).
