### ISSUE TITLE
Re-exports hoisted above imports

### ISSUE THREAD

**Issue by davewasmer** [babel/babel#4878] opened 2016-11-21 06:53 UTC
Given the following:

```
import foo from 'foo';
export { default as bar } from 'bar';
```

I would have expected `foo` to be loaded and evaluated _before_ `bar`, but Babel transpiles this to (somewhat simplified):

```
exports.bar = undefined;

var _bar = require('bar');

Object.defineProperty(exports, 'bar', {
  enumerable: true,
  get: function get() {
    return _interopRequireDefault(_bar).default;
  }
});

require('foo');
```

Note that `foo` is required _after_ `bar`.

The workaround is pretty simple:

```
import foo from 'foo';
import bar from 'bar';

export { bar }
```

But surprising nonetheless.

I posted this on the [discourse forums](https://discuss.babeljs.io/t/re-exports-hoisted-above-imports/773) before filing here.

Here's the issue [reproduced on the Babel site](http://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=latest%2Creact%2Cstage-2&code=import%20foo%20from%20'foo'%3B%0Aexport%20%7B%20default%20as%20bar%20%7D%20from%20'bar'%3B&experimental=false&loose=false&spec=false&playground=true).

### Input Code
```
import foo from 'foo';
export { default as bar } from 'bar';
```

### Babel Configuration
`babel-latest`

### Expected Behavior
The `'foo'` module should be loaded and evaluated first.

### Current Behavior
The re-exported `bar` is loaded and evaluated before `'foo'`, despite the reverse source order.

### Context
Trying to import babel-polyfill in an "index" type of file (i.e. a file that is entirely re-exports of other files).

**Comment by Kovensky** [comment] 2016-11-29 01:12
Circular dependencies are hard...

IIUC, if `'foo'` happens to circularly depend on your entry point, and should `bar` be an export of a hoisted declaration (e.g. `export function`), then the `bar` reexport _should_ be defined and valid in the circular reference...

**Comment by loganfsmyth** [comment] 2017-08-29 20:55
This looks to be a duplicate of https://github.com/babel/babel/issues/4356

**Closed by loganfsmyth** 2017-08-29 20:55 UTC
