### ISSUE TITLE
Multiple await statement cause hang

### ISSUE THREAD

**Issue by alinz** [babel/babel#2260] opened 2015-08-25 16:00 UTC
Everything was working on my app since `5.8.19`. After I upgraded to latest I found that the following code hands at second `await` statement.

`5.8.19` is working properly
`5.8.20` and above is not working anymore.

```js

function wait(delay) {
  return new Promise(resolve => {
    setTimeout(() => {
      resolve();
    }, delay);
  });
}

var test = async () => {
    try {
        await wait(1000);
        console.log('first wait is done');
        await wait(1000);
        console.log('second wait is done');
    } catch(e) {
        console.log(e);
    }
}

test();
```

Any suggestion thoughts?

**Comment by fkling** [comment] 2015-08-25 16:22
It works fine in the repl (which seems to be > 5.8.20): https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=true&spec=false&code=function%20wait(delay)%20%7B%0A%20%20return%20new%20Promise(resolve%20%3D%3E%20%7B%0A%20%20%20%20setTimeout(()%20%3D%3E%20%7B%0A%20%20%20%20%20%20resolve()%3B%0A%20%20%20%20%7D%2C%20delay)%3B%0A%20%20%7D)%3B%0A%7D%0A%0Avar%20test%20%3D%20async%20()%20%3D%3E%20%7B%0A%20%20%20%20try%20%7B%0A%20%20%20%20%20%20%20%20await%20wait(1000)%3B%0A%20%20%20%20%20%20%20%20console.log('first%20wait%20is%20done')%3B%0A%20%20%20%20%20%20%20%20await%20wait(1000)%3B%0A%20%20%20%20%20%20%20%20console.log('second%20wait%20is%20done')%3B%0A%20%20%20%20%7D%20catch(e)%20%7B%0A%20%20%20%20%20%20%20%20console.log(e)%3B%0A%20%20%20%20%7D%0A%7D%0A%0Atest()%3B&playground=true

**Comment by alinz** [comment] 2015-08-25 16:26
My app is based on react-native. I will investigate more. Thanks for feedback!

**Comment by sebmck** [comment] 2015-08-25 21:33
I can't confirm this but the only thing that could possibly be the cause is that regenerator was bumped to 0.8.35 (full diff [here](https://github.com/babel/babel/compare/v5.8.19...v5.8.20)). The only thing that changed for regenerator though was that a bunch of dependencies were updated. Can you put together a full repo in the [REPL](http://babeljs.io/repl)?

**Comment by sebmck** [comment] 2015-08-27 18:13
Any update @alinz?

**Comment by alinz** [comment] 2015-08-27 19:09
@sebmck I've been busy with something, I will do my best to give you a REPL by tomorrow!

**Comment by loganfsmyth** [comment] 2015-09-14 04:35
Gonna close this. Feel free to reopen if you can track down a repro case.

**Closed by loganfsmyth** 2015-09-14 04:35 UTC
