### ISSUE TITLE
Uncaught ReferenceError: _callee is not defined

### ISSUE THREAD

**Issue by jails** [babel/babel#9908] opened 2019-04-26 15:57 UTC
## Bug Report

**Current Behavior**
The transpilation result of generator functions is incomplete when a specific preset is enabled.

**Input Code**
The following code doesn't transpile correclty with the "firefox >= 45" preset enabled.

```js
class Plug {
  
  *[Symbol.iterator]() {
    yield 1;
    yield 2;
  }
}
```
The [generated output on the babel REPL](https://babeljs.io/repl/#?babili=false&browsers=Firefox%20%3E%3D%2045&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAEAKIFcDm0DeAoa1PQFQG0BlATwFsAjAexADoBLAFwFMAnMBylgXQAoBKNDizE6TEABNoARgDcQ6CLGSATHKwBfdJqA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.4.3&externalPlugins=) is referencing a `_callee` variable which is never defined.

**Expected behavior/code**
Some valid transpiled code.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
module.exports = function() {
  const presets = [
    [
      "@babel/preset-env",
      {
        "targets": {
          "firefox": "53"
        }
      }
    ]
  ];

  var config = {
    presets
  };

  return config;
};
```

**Environment**
- Babel version(s): 7.3.4
- Node/npm version: Node v10.15.3/npm 56.4.1
- OS: Ubunut 16.04
- Monorepo: ?
- How you are using Babel: cli

**Comment by nicolo-ribaudo** [comment] 2019-04-26 22:43
Duplicate of https://github.com/babel/babel/issues/9203, fixed by https://github.com/facebook/regenerator/pull/371

**Closed by nicolo-ribaudo** 2019-04-26 22:43 UTC
Labels: i: bug, i: needs triage
