### ISSUE TITLE
`interface` is a reserved word in node_modules

### ISSUE THREAD

**Issue by DrogoNevets** [babel/babel#9306] opened 2019-01-09 10:34 UTC
## Bug Report

**Current Behavior**
Babel works fine with all files in the `src/` directory and I can use the keyword `interface`

however when i try importing a ts class from `node_modules` I get the following error

```
ERROR in ./node_modules/workflow-engine/src/models/Document.ts
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: C:\projects\app-fixed-assets-disposal\node_modules\workflow-engine\src\models\Document.ts: interface is a reserved word in strict mode (8:0)
```

**Input Code**

```js
interface DocumentWorkflowCurrentState {
    position: number;
    name: string;
}
```

**Expected behavior/code**
It should transpile nicely and allow me to import the class and extend it

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": [
    "@babel/typescript",
    [
      "@babel/env",
      {
        "modules": false
      }
    ]
  ],
  "plugins": [
    "@babel/plugin-proposal-class-properties"
  ]
}
```

**Environment**
- Babel version(s): [e.g. v6.0.0, v7.0.0-beta.34]
- Node/npm version: 8.12.0
- How you are using Babel:`webpack-loader`

**Comment by cameron-martin** [comment] 2019-01-09 20:11
Most likely you have webpack configured to not run files in `node_modules` through babel-loader. Posting your webpack config would help.

**Comment by DrogoNevets** [comment] 2019-01-10 08:15
hi @cameron-martin sure thing, see below

```js
const path = require('path'),
    CaseSensitivePathsPlugin = require('case-sensitive-paths-webpack-plugin');

module.exports = {
    entry: './server.ts',
    mode: 'development',
    target: 'node',
    devtool: 'source-map',
    output: {
        filename: 'server.js',
        path: path.resolve(__dirname, 'dist')
    },
    plugins: [
        new CaseSensitivePathsPlugin()
    ],
    module: {
        rules: [
            {
                test: /\.ts?$/,
                use: ['babel-loader']
            },
        ]
    },
    resolve: {
        extensions: ['.tsx', '.ts', '.js']
    },
    optimization: {
        usedExports: true
    }
};
```

**Comment by cameron-martin** [comment] 2019-01-10 19:24
Do you have a babelrc file in `./node_modules/workflow-engine`?

**Comment by DrogoNevets** [comment] 2019-01-11 11:23
oooo interesting.....yes i do, but the `workflow-engine` project compiles fine

**Comment by cameron-martin** [comment] 2019-01-11 11:43
I'm wondering whether it's an issue with the new behaviour of [merging config files](https://babeljs.io/docs/en/config-files) in Babel 7.

**Comment by DrogoNevets** [comment] 2019-01-11 13:04
anyway to test it? I had that theory vaguely and tried writing a `babel.config.js` file but kinda completely broke the world!

**Comment by cameron-martin** [comment] 2019-01-11 13:05
Try removing the babelrc file in `./node_modules/workflow-engine/` then build?

**Comment by DrogoNevets** [comment] 2019-01-14 09:37
Sorry for delay, left laptop in the office. I have tried and alas, same issue......

**Comment by cameron-martin** [comment] 2019-01-14 15:23
I don't have any other ideas with the available information. If it's possible to create a repo which reproduces it and link it here then that would be of great help.

**Comment by TeamDman** [comment] 2019-03-02 16:49
Reproduction using a modified example from a different issue
https://babeljs.io/repl/build/7.0/#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=JYOwLgpgTgZghgYwgAgEJwF7IN4F8BQCANnAM6nIBiA9tTvssgEZxTIC8OuyZamDjQQIAW1AOYoAFAEp6g5EQhhkMAK5i4AggSA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=react%2Ctypescript&prettier=false&targets=&version=7.3.4

https://github.com/babel/babel/issues/6959#issuecomment-349193451

**Comment by nicolo-ribaudo** [comment] 2019-05-26 20:32
The problem is that `.babelrc` isn't applied to submodules (e.g. `node_modules`); you'll need `babel.config.js` for that.

I'm closing this issue as the next step for me would be to ask for a repository I can clone to reproduce the issue, but it was already asked a few months ago :stuck_out_tongue: https://github.com/babel/babel/issues/9306#issuecomment-454042918

---

@TeamDman That's a separate issue, we are working on it in the website repository.

**Closed by nicolo-ribaudo** 2019-05-26 20:32 UTC
Labels: i: bug, i: needs triage
