### ISSUE TITLE
"RangeError: Maximum call stack size exceeded" when copying resulting files with babel-cli

### ISSUE THREAD

**Issue by karlas** [babel/babel#7306] opened 2018-02-01 08:50 UTC
### Babel/Babylon Configuration (.babelrc, package.json, cli command)

.babelrc
```js
{
  "presets": [
    ["@babel/env", {
      "targets": { "node": "6.11.5" }
    }]
  ],
  "plugins": ["@babel/plugin-proposal-object-rest-spread"]
}
```
CLI Command

`babel 'functions/src' --out-dir 'functions/bundle' --copy-files --ignore 'functions/src/node_modules'
`

### Expected Behavior
After executing this command, resulting files were correctly copied at functions/bundle folder using beta.37

### Current Behavior
With beta.38 and beta.39, following error arises after processing last file

```
RangeError: Maximum call stack size exceeded
    at /Users/karlas/myapp/node_modules/@babel/cli/lib/babel/dir.js:71:56
    at write (/Users/karlas/myapp/node_modules/@babel/cli/lib/babel/dir.js:30:14)
    at handleFile (/Users/karlas/myapp/node_modules/@babel/cli/lib/babel/dir.js:66:5)
    at sequentialHandleFile (/Users/karlas/myapp/node_modules/@babel/cli/lib/babel/dir.js:89:5)
    at /Users/karlas/myapp/node_modules/@babel/cli/lib/babel/dir.js:94:9
    at /Users/karlas/myapp/node_modules/@babel/cli/lib/babel/dir.js:75:14
    at write (/Users/karlas/myapp/node_modules/@babel/cli/lib/babel/dir.js:30:14)
    at handleFile (/Users/karlas/myapp/node_modules/@babel/cli/lib/babel/dir.js:66:5)
    at sequentialHandleFile (/Users/karlas/myapp/node_modules/@babel/cli/lib/babel/dir.js:89:5)
    at /Users/karlas/myapp/node_modules/@babel/cli/lib/babel/dir.js:94:9
```

### Possible Solution
Check https://github.com/babel/babel/commit/26e4911eb22a75f6581febe0cedc245a683c55cb#diff-f93fbf6dce06b5cbf6cc65f5f7dac101

This is the last commit where this dir.js file was modified. Tags are beta.38 and beta.39 (the affected versions)

### Context
Just transpiling about 20 files to be used on Firebase Functions

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-beta.39
| node             |  8.9.3
| npm              |  5.5.1
| yarn              | 1.3.2
| Operating System | macOS High Sierra

**Comment by hzoo** [comment] 2018-02-01 15:51
also cc @loganfsmyth 😛

**Comment by loganfsmyth** [comment] 2018-02-01 16:48
This issue is almost certainly that this line needs to be wrapped in a `process.nextTick()`

https://github.com/babel/babel/blob/26e4911eb22a75f6581febe0cedc245a683c55cb/packages/babel-cli/src/babel/dir.js#L16

Marking as a good first issue.

**Comment by Tauka** [comment] 2018-02-01 17:47
Hello everyone, I would like to tackle this issue, if that's ok

**Comment by loganfsmyth** [comment] 2018-02-01 18:01
@Tauka Sure!

**Comment by Tauka** [comment] 2018-02-03 02:03
I was not able to reproduce this issue on my machine, it transpiles and copies all the files (i tried 160 files with 700mb node_modules in the folder) just fine

> The only difference with @karlas in dependency versions is that he has newer MacOS

| Dependency | Version |
| -------------| --------|
| Babel | 7.0.0-beta.39 |
| Babel-cli | 7.0.0-beta.39 |
| node | 8.9.3 |
| npm | 5.5.1 |
| OS | MacOS Sierra 10.12.4 |

**Comment by loganfsmyth** [comment] 2018-02-03 02:29
Would you be able to try it with a larger number of files? Two things to note:

* This may only happen with `--copy-files`
* This only happens if the files aren't 'compilable' so they'd have to be using --copy-files to copy a bunch of non-.js files.

So ideally make sure you're copying a large number of non-javascript files.

**Comment by Tauka** [comment] 2018-02-03 03:56
@loganfsmyth Thanks for the tips! 

Indeed, I was able to reproduce with large number of non-js files. And, as you predicted, `process.nextTick()` did the trick. PR is open now

**Closed** 2018-02-03 04:56 UTC
Labels: 7.x: regression, good first issue, help wanted

**Comment by karlas** [comment] 2018-02-12 18:53
I confirm it works with 7.0.0-beta.40 @Tauka Thx!
