### ISSUE TITLE
--copy-files doesn't preserve file permissions

### ISSUE THREAD

**Issue by olalonde** [babel/babel#2551] opened 2015-10-18 13:09 UTC
I'm using babel to compile src/ to lib/. I have `src/cli/somecli.js` which is `chmod u+x` but babel doesn't preserve that permission which means I can't do `./lib/cli/somecli.js` in bash. Would be nice if there was an option to tell babel to preserve that permission.

**Comment by sebmck** [comment] 2015-10-18 13:19
Duplicate of #1586.

**Comment by sebmck** [comment] 2015-10-18 17:38
Actually, may as well for 6.0 I guess.

**Comment by sebmck** [comment] 2015-10-18 18:05
Done in the `development` branch.

**Comment by olalonde** [comment] 2015-10-19 01:58
Thanks.

**Closed** 2015-10-20 02:30 UTC
