### ISSUE TITLE
@babel/core and babel-preset-current-node-syntax contain files with date older than 1980

### ISSUE THREAD

**Issue by BenoitAverty** [babel/babel#12501] opened 2020-12-14 10:09 UTC
## Bug Report

**Current behavior**

Babel contain some very old files.

To reproduce, install @babel/core and babel-preset-current-node-syntax on a fresh empty npm project, then run

```find ! -newermt 1981-01-01```

This gives the list of files older than January the first, 1980.

This is a problem when zipping the files because ZIP does not support timestamps that old. It happens, for example, when deploying an app to AWS

This seems to change based on the version of babel, for example, the latest babel-core has files from 1984 wheras the version used by @mdx-js has files from 1970.

Lastest `babel-preset-current-node-syntax` has some from before 1980.

**Possible Solution**

As a workaround, uses can run 
```find ! -newermt 1981-01-01 -exec touch {} \```
to fix the date. But it requires having diagnosed the problem.

**Comment by nicolo-ribaudo** [comment] 2020-12-14 10:29
Which version of those packages are you using? It should have already be fixed in both of them 🤔

**Comment by BenoitAverty** [comment] 2020-12-14 10:54
Hey !
Here is the dependencies in the package.json : 
```
"dependencies": {
    "@babel/core": "^7.12.10",
    "babel-preset-current-node-syntax": "^1.0.0"
  }
```

freshly installed with npm install.

**Comment by nicolo-ribaudo** [comment] 2020-12-14 11:03
This could be a regression caused by https://github.com/babel/babel/pull/12453

**Comment by JLHwung** [comment] 2020-12-14 21:00
The issue should be filed to https://github.com/nicolo-ribaudo/babel-preset-current-node-syntax

`@babel/core` 7.12.10 is not affected.

```
$ curl -s `npm view @babel/core dist.tarball` --output - | tar -tvf -
-rw-r--r--  0 0      0        1106 22 Jun  1984 package/LICENSE
-rw-r--r--  0 0      0         404 22 Jun  1984 package/README.md
(...)
```

```
$ curl -s `npm view babel-preset-current-node-syntax dist.tarball` --output - | tar -tvf -

-rw-r--r--  0 0      0        1095 31 Dec  1979 package/LICENSE
-rw-r--r--  0 0      0         794 31 Dec  1979 package/README.md
-rw-r--r--  0 0      0        1422 31 Dec  1979 package/package.json
-rw-r--r--  0 0      0        1865 31 Dec  1979 package/src/index.js
```

**Closed** 2020-12-15 13:08 UTC
Labels: i: bug, i: third party
