### ISSUE TITLE
Code with line comments breaks the code generators indentation

### ISSUE THREAD

**Issue by zertosh** [babel/babel#2084] opened 2015-07-27 00:29 UTC
In 5.8.9, this:

```js
if (a) {
  b(); // this comment breaks the code generators indentation
} else {
  c();
}
```

results in:

```js
"use strict";

if (a) {
  b(); // this comment breaks the code generators indentation
} else {
    c();
  }
```

**Comment by sebmck** [comment] 2015-07-27 00:40
It's due to some `indentOnComments` method, I dunno why it exists but going back it was introduced with this commit: c054ff7bbb8332a91c7ae1eb8cb0f46b4819093d Going back that far and reading my ancient (in relative terms!) code was an... interesting experience.

**Comment by sebmck** [comment] 2015-07-27 00:42
That comment is being attached to multiple nodes. No idea why.

**Comment by zertosh** [comment] 2015-07-27 00:47
comments are the worst. I just ran a diff on the entire SC app's post-babel output between v5.6.15 and v5.8.9, and it's happening all over the place.

**Comment by sebmck** [comment] 2015-07-27 01:30
I was kinda naughty and stole the comment attachment from esprima/estraverse/espree. I legitimately have no idea how it works because it's so spaghetti. Unless this is a blocker I'll try and implement my own comment attachment algo that's more straight forward in the next week or so. There's not really any reason that so many edge cases need to be handled and I have a few ideas for a comment attachment algorithm that's much more predictable and sane.

**Comment by zertosh** [comment] 2015-07-27 01:50
not a blocker, thanks for looking into it!

**Comment by danez** [comment] 2016-10-02 11:07
Cannot reproduce anymore, was probably fixed in 6.x

**Closed by danez** 2016-10-02 11:07 UTC
