### ISSUE TITLE
make `browser-polyfill.js` available via bower install

### ISSUE THREAD

**Issue by venil7** [babel/babel#1000] opened 2015-03-11 09:51 UTC
npm is generally used for serverside or dev-tools, while `browser-polyfill.js` is a browser dependency

**Comment by sebmck** [comment] 2015-03-11 10:33
Duplicate of #315.

**Closed by sebmck** 2015-03-11 10:33 UTC
Labels: duplicate

**Comment by venil7** [comment] 2015-03-11 11:49
thanks, should have searched before posted anew issue.
but it was such a good issue number.

**Comment by thejameskyle** [comment] 2015-03-11 17:18
1,000th Issue :tada: ... duplicate :disappointed:

**Comment by sebmck** [comment] 2015-03-12 00:12
@thejameskyle Better a duplicate than a bug :stuck_out_tongue:

**Comment by yanghuabei** [comment] 2015-09-10 08:50
I met this problem too. So I made a reposity for browser polyfill and keep update with babel. You can fint it here.  https://github.com/yanghuabei/babel-browser-support

**Comment by thejameskyle** [comment] 2015-09-10 17:21
Since Babel won't ever be adding support for bower, I would suggest not using a separate package as it's pretty much guaranteed to fall out of date almost immediately. I suggest you find a way to consume the package via npm.

**Comment by venil7** [comment] 2015-09-12 22:10
Babel won't ever support bower... This stubborness is annoying, the community clearly needs an official bower package.I  guess best approach is to show maintainers the need for it, by commenting on this thread, voting on this issue, etc. to persuade them to add this functionality.

**Comment by sebmck** [comment] 2015-09-12 22:11
Not supporting it ever, sorry. It encourages bad habits and this is a sentiment shared by a lot of people in the community.
