### ISSUE TITLE
Feature request: babel api -> get used configuration

### ISSUE THREAD

**Issue by aight8** [babel/babel#5364] opened 2017-02-23 07:18 UTC
I want to access the used/generated babel configuration. Especially which presets includes which plugins exactly.

PS: I get option-manager work, the ONLY problem is that plugins which presets uses, are anonymous functions. Normally the **key** prop reference to the full path. Plugins included by presets have a dynamical incrementef name something with "$"

How this ensures to avoid duplication plugins?
Is there any way to get some hints of those kind of plugins, so i can list it in a kind debug output?

**Comment by loganfsmyth** [comment] 2017-02-25 19:22
Seems like this is mostly a duplicate of your other bug https://github.com/babel/babel/issues/5374 since options include plugins.

**Closed** 2017-02-25 19:40 UTC
Labels: tag: new feature
