### ISSUE TITLE
Parsing error when using @babel/plugin-proposal-decorators

### ISSUE THREAD

**Issue by pirix-gh** [babel/babel#8758] opened 2018-09-24 14:27 UTC
## Bug Report

**Current Behavior**
Babel parser gets confused when using decorators.

**Additional context/Screenshots**
```js
    Module parse failed: Can not use keyword 'await' outside an async function (86:8)
    You may need an appropriate loader to handle this file type.
    |       key: "t",
    |       value: function value() {
    >         await this.s();
    |       }
    |     }, {
     @ ./src/index.js 7:13-40
```

As you can see `await this.s()` is within an `async` so there should be no problem.
Remove the decorator then the problem is gone immediately.

**Input Code**
```js

function decorator(Class) {
     return function (...args) {
          return new Class(...args);
     }
}

@decorator
class Test {
     constructor(props) {
     }

     async t() {
          await this.s()
     }

     async s() {
     }
}

new Test();
```

**Expected behavior/code**
This is supposed to compile just fine.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
module.exports = function (api) {
     //console.log('----------------------------test-------------------------');
     api.cache(true);

     const presets = [
          ['@babel/preset-env'],
     ];

     const plugins = [
          ['@babel/plugin-transform-runtime'],
          ['@babel/plugin-proposal-decorators', {decoratorsBeforeExport: false}],
          ['@babel/plugin-proposal-class-properties'],
     ];

     return {
          presets: presets,
          plugins: plugins,
     };

};
```

**Environment**
- Babel version(s): 7.1.0
- Node/npm version: [Node 8.12 / NPM 6.4.1]
- OS: [Ubuntu 16.04 LTS]
- How you are using Babel: ['cli', 'webpack']

**Comment by nicolo-ribaudo** [comment] 2018-09-24 15:01
Duplicate of #8737, fixed by #8742

**Closed by nicolo-ribaudo** 2018-09-24 15:01 UTC
