### ISSUE TITLE
Incorrect receiver when defining static class fields

### ISSUE THREAD

**Issue by gsathya** [babel/babel#6764] opened 2017-11-07 17:49 UTC
> Choose one: is this a bug report or feature request?

bug
### Input Code

```js
class X {
  static a = 1;
  static b = this.a;
}

console.log(X.b);
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

stage3,stage2

### Expected Behavior

1
### Current Behavior

undefined

### Your Environment

[REPL](https://babeljs.io/repl/build/master#?babili=false&browsers=&build=&builtIns=false&code_lz=MYGwhgzhAEAa0G8BQ1oQC5nQS2NM0AvNAIwDcKamOeARkdOgBbYQB0YFAvkksAPYA7CPxABTNiH4BzABSw2tAJRkgA&debug=false&circleciRepo=&evaluate=true&lineWrap=false&presets=stage-2%2Cstage-3&targets=&version=7.0.0-beta.31)

**Comment by loganfsmyth** [comment] 2017-11-07 18:01
Good find, definitely a bug.

Duplicate of https://github.com/babel/babel/issues/5222 in this case.

**Closed by loganfsmyth** 2017-11-07 18:01 UTC
Labels: i: bug, Spec: Class Fields
