### ISSUE TITLE
decorator transpilation doesn't work when the es6.classes transformer is blacklisted

### ISSUE THREAD

**Issue by dlmanning** [babel/babel#2280] opened 2015-08-29 04:50 UTC
Example:

``` js
@extendo
class A {
  foo () {
    return () => 'bar';
  }
}

function extendo (target) {
  return class B extends target {
    bar () {
      return () => 'baz'
    }
  };
}
```

Under `babel foo.js --optional="es7.decorators"` the class declaration becomes:

``` js
var A = (function () {
  function A() {
    _classCallCheck(this, _A);
  }

  _createClass(A, [{
    key: 'foo',
    value: function foo() {
      return function () {
        return 'bar';
      };
    }
  }]);

  var _A = A;
  A = extendo(A) || A;
  return A;
})();
```

Using `babel foo.js --optional="es7.decorators" --blacklist="es6.classes"` we get:

``` js
@extendo
class A {
  foo() {
    return function () {
      return 'bar';
    };
  }
}
```

This looks like the es7.decorator transform requires the es6.class tranform to work. Is this intended behavior? Thanks for your time!

**Comment by sebmck** [comment] 2015-08-29 06:35
Yeah, it's intended behaviour. To quote from #1713:

> You can't blacklist the `es6.classes` transformer if you want to use decorators. It's counter intuitive to use native class with decorators since you'd need to desugar classes excessively in order to get proper decorator semantics which means you'd get... the same behaviour as transpiling classes with decorators.

Thanks!

**Comment by justinfagnani** [comment] 2015-09-28 14:19
@sebmck I'm interested in re-opening one of the decorators w/o the class transform bugs to discuss more. The decorators proposal defines de-sugaring for both ES6 and ES5, so it should be possible to perform the ES6 transformation in isolation.

**Comment by sebmck** [comment] 2015-09-28 14:21
> so it should be possible to perform the ES6 transformation in isolation.

Yeah I know. It's just architecturally tricky if they're done in a modular fashion. I'm considering putting them in the same transformer/plugin but behind options for v6. More than happy to reopen an issue for discussion, although this will definently be addressed in v6.

**Comment by justinfagnani** [comment] 2015-09-28 14:27
Whatever works best for you of course.

I'm basically just interested in a "7to6" (or maybe 16to15?) transpile, as I expect others will be too, so having just decorators, class properties, and type annotations work would be ideal.

**Comment by sebmck** [comment] 2015-09-28 14:27
Reopening then. Will close once I've done the appropriate work for 6.0.

**Comment by justinfagnani** [comment] 2015-09-28 14:30
Thanks. BTW, are you planning a 6.0 label for tracking?

**Comment by sebmck** [comment] 2015-09-28 14:31
Yeah there's a milestone. Although I've yet to triage all of it into it. I'll likely plow through most of the issues pretty quickly though. I'm hoping to resolve all currently opened bugs too.

**Comment by hzoo** [comment] 2016-12-14 21:37
Going to merge this into https://github.com/babel/babel/issues/2645 - right now we only have https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy to match 5.x and we need to modify to the latest spec which may take a while.

**Closed by hzoo** 2016-12-14 21:37 UTC
