### ISSUE TITLE
React's new jsx-runtime incompatible with preset-typescript

### ISSUE THREAD

**Issue by maraisr** [babel/babel#12245] opened 2020-10-24 05:56 UTC
When using the new jsx-runtime method through preset-react, Babel insists React be defined when coupled with preset-typescript. 

https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html

tsconfig is set to preserve jsx.

Happy to provide a repro.

**Comment by nicolo-ribaudo** [comment] 2020-11-02 12:20
Could you provide an example? I cannot reproduce it with this one:
```js
const input = `
<Foo />
`;

const out = babel.transformSync(input, {
  configFile: false,
  sourceType: "module",
  presets: [
    presetTypescript,
    [presetReact, { runtime: "automatic" }],
  ],
  filename: "demo.tsx"
});
```

**Comment by ranisalt** [comment] 2021-01-30 00:29
```js
const babel = require('@babel/core')
const presetReact = require('@babel/preset-react')
const pluginTypescript = require('@babel/plugin-transform-typescript')

const out = babel.transformSync('<Foo />', {
  configFile: false, 
  sourceType: 'module',
  presets: [
    [presetReact, { runtime: "automatic" }],
  ],
  plugins: [
    pluginTypescript,
  ],
});
```

outputs

```
Uncaught [SyntaxError: unknown: Unexpected token, expected "," (1:5)

> 1 | <Foo />
    |      ^
] {
  loc: Position { line: 1, column: 5 },
  pos: 5,
  code: 'BABEL_PARSE_ERROR'
}
```

**Comment by nicolo-ribaudo** [comment] 2021-01-30 14:00
@ranisalt TypeScript only allows JSX in `.tsx` files. You need to pass the `isTSX` option:

```js
const out = babel.transformSync('<Foo />', {
  configFile: false,
  sourceType: 'module',
  presets: [
    [presetReact, { runtime: "automatic" }],
  ],
  plugins: [
    [pluginTypescript, { isTSX: true }],
  ],
});
```

If you use the TS preset, you can just pass to Babel the name of the file you are transforming:
```js
const out = babel.transformSync('<Foo />', {
  configFile: false,
  sourceType: 'module',
  filename: 'input.tsx',
  presets: [
    [presetReact, { runtime: "automatic" }],
    presetTypescript,
  ],
  plugins: [
  ],
});
```

I'm now closing this issue, since @maraisr didn't provide a reproduction for the original bug report.

**Closed by nicolo-ribaudo** 2021-01-30 14:00 UTC
Labels: i: bug, i: needs reproduction
