### ISSUE TITLE
A var name that is also a parameter name should not initialize parameter's value to undefined

### ISSUE THREAD

**Issue by Jeff-Mott-OR** [babel/babel#2828] opened 2015-11-05 01:01 UTC
function returnX(x, f = function () { return x }) {
        var x;
        return x;
    }
    returnX(42);

In Firefox, this produces 42. In babel, this produces undefined.

In the [ECMAScript spec for FunctionDeclarationInstantiation](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-functiondeclarationinstantiation), item 28 > f > i > 4/5, if a var name is also a parameter name, then it should get the parameter's value, even when the parameters have expressions (that is, default values).

**Comment by loganfsmyth** [comment] 2015-11-05 01:06
Duplicate of https://github.com/babel/babel/issues/2471.

**Closed by loganfsmyth** 2015-11-05 01:06 UTC
