### ISSUE TITLE
'this' is not allowed before super()' – error when combining arrow functions and property initializers

### ISSUE THREAD

**Issue by deepakjois** [babel/babel#2809] opened 2015-11-04 13:13 UTC
```
babel --version
6.1.1 (babel-core 6.0.20)
```

.babelrc
```
{
  'presets': ['es2015', 'stage-0', 'react']
}
```

EmptyComponent.jsx
```
class EmptyComponent extends React.Component {
  constructor() {
    super()
  }

  nextStep = (e) => {
    e.preventDefault()
    this.saveValues()
  }
}
```

Running babel:
```
$ babel src/app/components/EmptyComponent.jsx
SyntaxError: src/app/components/EmptyComponent.jsx: 'this' is not allowed before super() (This is an error on an internal node. Probably an internal error)
undefined
```

However, this compiles successfully (just removed the `this.saveValues()` invocation)
```
class EmptyComponent extends React.Component {
  constructor() {
    super()
  }

  nextStep = (e) => {
    e.preventDefault()
  }
}
```

**Comment by vladmiller** [comment] 2015-11-04 13:29
Have the same issue when running unittests with mocha

```
// mocha.opts
--compilers js:babel-core/register
```

**Comment by heikkilamarko** [comment] 2015-11-04 16:40
I am facing this problem as well.

**Comment by ben-ng** [comment] 2015-11-04 17:43
i'm facing this problem too

**Comment by fkling** [comment] 2015-11-04 18:01
Duplicate of #2774 .

**Comment by Ahn1** [comment] 2015-11-05 11:47
There is a workaround for now:

Instead of:
```
export default class Helloextends React.Component {
  render () {
    super.render();
    return (<div></div> )
  }
}
```

use:
```
class Hello extends React.Component {
  render () {
    super.render();
    return (<div></div> )
  }
}

export default Hello;
```

Worked for me..

**Closed** 2015-11-09 00:16 UTC
Labels: pending triage
