### ISSUE TITLE
`new anonymous class extends NativeClass` works in browser, but babel generates code that does not

### ISSUE THREAD

**Issue by chee** [babel/babel#5458] opened 2017-03-13 14:40 UTC
(with a built-in class, or indeed a class defined using the native `class` syntax)

### Input Code
```js
const headers = new class extends Headers {}
```

### Link to repl
[babel repl](http://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015&targets=&browsers=&builtIns=false&code=const%20headers%20%3D%20new%20class%20extends%20Headers%20%7B%7D&experimental=false&loose=false&spec=false&playground=true)

### Expected Behavior
generate code that works, as the input code does in browser

### Current Behavior
the generated code does not work (says `Constructor Headers requires 'new')

### Context
i just need to add a couple of methods in one place to a class that's already defined as a class (and as such requires new).

**Comment by hzoo** [comment] 2017-03-13 14:55
http://babeljs.io/docs/usage/caveats/#classes, babel has a limitation with extending native classes

I think this would be a duplicate of https://github.com/babel/babel/issues/4480 and others?

**Closed by hzoo** 2017-03-13 14:55 UTC
Labels: duplicate
