### ISSUE TITLE
[babel-generator] Generated code doesn’t match with source with input source-maps

### ISSUE THREAD

**Issue by alloy** [babel/babel#5408] opened 2017-03-03 00:11 UTC
### Input Code

I’ve put up a repo [here](https://github.com/alloy/test-source-maps-with-typescript-through-babel)

The relevant code is [here](https://github.com/alloy/test-source-maps-with-typescript-through-babel/blob/bd5423e52030ba4837be817a28b458b9a047d32c/index.js#L17-L25)

### Expected Behavior

I would have expected the source-map from babel-generator to map from the original TypeScript source to the generated JS.

### Current Behavior

The source-map doesn’t appear to have any relation to the original code.

Here are some examples of the code looked-up through the source-maps:

```
 Original: import * as React fr
Transform: var React=require("
 Generate: "use strict";

 Original: function MyComponent
Transform: function MyComponen
 Generate:  require("react");
```

As you can see, the transform step does a good job of mapping to the original code, but the generate step just produces something completely different.

### Context

I’m trying to use TypeScript for our React Native project and have inline source-maps propagate properly through Babel. I would prefer to not write the intermediate JS (produced by `tsc`) to disk.

I’m not sure if I’m doing something wrong, if this has to do with how React Native uses transform and the generator, or if there’s a bug with `babel-generator`.

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.23.1
| node             | 6.2.1
| npm              | 4.1.1
| Operating System | macOS 10.12.2

**Comment by loganfsmyth** [comment] 2017-03-03 00:54
Assuming I'm understanding fully, I think this may be the expected, if frustrating, behavior. `babel-generator` outputs a sourcemap that maps to the sourcecode that was parsed to create the AST and does not take input sourcemaps into account. Currently they are merged inside `babel-core` in https://github.com/babel/babel/blob/7.0/packages/babel-core/src/transformation/file/index.js#L364, so if you want to generate the code from the AST yourself, you'd have to reimplement that merging logic.

I could see the benefit of moving this logic, so I'm happy to have this as a feature request if you'd like. Not sure it would be a high priority for the core team to implement though.

**Comment by alloy** [comment] 2017-03-03 10:39
Ah yes! This works: https://github.com/alloy/test-source-maps-with-typescript-through-babel/commit/a2982c8fe47eed4a0cf4a012a84411b191e854aa

I was stepping through all the code looking for when the input and output maps of the generated code got merged and could only find it indeed in the transform step, glad I decided to ask.

So if I understand you correctly you’re suggesting to extract `mergeSourceMap` into a standalone utility function? If so, could you just point me to where you would want to have it? I’ll try to make a PR for it.

**Comment by loganfsmyth** [comment] 2017-03-03 16:55
I think it would be reasonable to move `mergeSourceMap` into `babel-generator` so people could more easily do what you are trying to do.

**Comment by loganfsmyth** [comment] 2017-03-14 01:06
A similar issue was just raised in https://github.com/aspnet/JavaScriptServices/issues/739#issuecomment-286289838. In that usecase, people are expecting the AST locations to take the original sourcemap locations into account. 

Given that, an alternative would be to actually delete `mergeSourceMap` entirely and have either babylon or babel-core ensure that the AST locations map to the original file content, so that the final map generated by `babel-generator`, and Babel's output AST, would have the correct position data already.

I'm fine with that as a solution as long as there's no loss of information.

**Comment by dan-j** [comment] 2017-07-21 07:04
I think I came across a similar issue while trying to write a jest preprocessor for TS -> Babel and getting code coverage right.

I ended up not passing inputSourceMap into babel, and using [source-map-merge]() to merge the source maps outputted by the TS compiler and babel respectively.

Perhaps babel should use this module for merging input source maps rather than it's own merge code? From debugging the issue before I resorted to `source-map-merge` the merge code inside babel is here:

https://github.com/babel/babel/blob/master/packages/babel-core/src/transformation/file/index.js#L368

**Comment by DrMiaow** [comment] 2017-11-09 03:48
+1 for resolving this please.

My issue is that Babel is not merging with source-maps from previous steps in my transformation chain, it appears to simply generate its own source-map from the input, which seems to be the problem everyone else is having.

My workaround, for now, is to set retainLines: true,  sourceMap: false and after transforming using Babel I copy the *.map files from the previous step to feed into the next step. 

Not ideal, but does the job.

**Comment by PabloZaiden** [comment] 2018-01-15 20:00
Any news on this?

**Comment by fbartho** [comment] 2019-07-25 01:00
We're super invested in this, because it means that our bugsnags don't map back to the original TypeScript lines in our react-native source code :(

**Comment by fbartho** [comment] 2020-02-07 07:59
Is there any way to solve this?

**Comment by dlebedynskyi** [comment] 2021-08-30 16:57
Any update on this issue?

**Comment by dan-j** [comment] 2021-08-31 22:47
> Any update on this issue?

I doubt there is, I've no need for Babel in my current role and won't find the time to contribute (I just got the notification because I've previously commented).

If nothing much has changed in 4 years, my comment is my suggestion on fixing the issue: https://github.com/babel/babel/issues/5408#issuecomment-316922155, however I have no real idea whether or not that comment is applicable anymore.

If a maintainer can comment and approve of the idea then it may be worth you implementing the fix and contributing it back?

**Comment by shaunlebron** [comment] 2022-10-06 23:23
Hello, my employer has asked me to help solve this, if possible.

We require this feature downstream in Metro ([parallel issue here](https://github.com/facebook/metro/issues/104)).

Can a maintainer answer some questions?

1. Does this issue imply that [`inputSourceMap: true`](https://babeljs.io/docs/en/options#inputsourcemap) isn’t actually working?
2. Is [PR #12471](https://github.com/babel/babel/pull/12471) intended to fix this?
3. Is it possible for an outsider to help with this, or to catch up on domain knowledge to help?

Thank you.  Hoping we can help solve this five-year-old issue!

**Comment by liuxingbaoyu** [comment] 2022-10-06 23:40
Yes, `inputSourceMap` is currently invalid in `babel-generator`.
#12471 I don't think it can solve your problem.
Exactly this is in my plan, but I can't promise.

ref: https://github.com/babel/babel/pull/15022#issuecomment-1270655897

**Comment by shaunlebron** [comment] 2022-10-07 17:15
Thank you @liuxingbaoyu!  Are you saying `babel-core` already does correct source map merging with `inputSourceMap: true`?  (I actually don’t see Metro passing this option to babel-core in their repo…)

**Comment by liuxingbaoyu** [comment] 2022-10-07 20:04
Yes, as in the OP's reproduced code. `babel/core` is merging source maps. So this is just an enhancement and shouldn't be blocking.

**Closed** 2023-02-18 17:36 UTC
Labels: pkg: generator, i: enhancement, area: sourcemaps
