### ISSUE TITLE
IIFE as a default export was broken from v5.0.7 to v5.5.6

### ISSUE THREAD

**Issue by pygy** [babel/babel#1755] opened 2015-06-15 13:49 UTC
Between ~~v5.0.0~~v5.0.7 and v5.5.6 (inclusive), the following code was compiled to nothing at all:

```JavaScript
// export_Default_IIFE.js
export default (function(){return "default export"})();
```

I couldn't find any related issues or change log entry, so I suppose that the breakage and fix happened under the radar...

I'm willing to submit a PR with a test case. I see

https://github.com/babel/babel/tree/master/test/core/fixtures/transformation/es6.modules-system/exports-default

and 

https://github.com/babel/babel/tree/master/test/core/fixtures/transformation/es6.modules-common/exports-default

Are there other relevant tests?

**Comment by sebmck** [comment] 2015-06-15 13:51
It compiles fine for me. What error are you actually seeing?

**Comment by sebmck** [comment] 2015-06-15 13:51
Also what options are you using etc? Need more information to reproduce.

**Comment by pygy** [comment] 2015-06-15 14:09
My bad, it starts at `v5.0.7`

No options, no error, just a blank file:

```Bash
$ npm install babel@5.0.7 # till 5.5.6
$ babel export_default_IIFE.js

$
```
With `v5.0.6` and `v5.5.7` I get the expected output. To be honest, I only tested a few versions in between.

**Comment by sebmck** [comment] 2015-06-15 14:11
I'm trying to replicate this and I can't.

```sh
$ babel test.js
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});

exports["default"] = (function () {
  return "default export";
})();

module.exports = exports["default"];
```

Do you have any `.babelrc` files that could be interfering?

**Comment by pygy** [comment] 2015-06-15 14:14
None. This is in a freshly created blank directory.

**Comment by sebmck** [comment] 2015-06-15 14:15
Node version?

**Comment by pygy** [comment] 2015-06-15 14:16
Good point: v0.10.33

**Comment by sebmck** [comment] 2015-06-15 14:21
Even on 0.10.33 I can't reproduce this:

```
$ nvm install 0.10.33
######################################################################## 100.0%
Now using node v0.10.33
$ node_modules/.bin/babel test.js
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});

exports["default"] = (function () {
  return "default export";
})();

module.exports = exports["default"];
```

**Comment by pygy** [comment] 2015-06-15 14:23
That's puzzling...

What Babel version did you try?

**Comment by sebmck** [comment] 2015-06-15 14:23
5.5.8

**Comment by pygy** [comment] 2015-06-15 14:24
It was fixed as of 5.5.7

My point was that it broke and got fixed without you noticing...

**Comment by sebmck** [comment] 2015-06-15 14:25
Why did you open an issue then if it's already fixed?

**Comment by pygy** [comment] 2015-06-15 14:26
Because I couldn't find any reference to it ever existing. If it breaks again you won't detect it.

**Comment by pygy** [comment] 2015-06-15 14:27
Note that the version range was included in the initial report (if a bit off).

**Comment by sebmck** [comment] 2015-06-15 14:34
Sorry, I was just a bit confused because the README says:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">slack channel</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

And I mistook this for a current bug report.

It _could_ have been commit 4061bea528541d7935c068f569ec79ded9cbcb6f that inadvertently fixed this because it's the only commit in that version range that touches module transforming but there's nothing obvious that would have effected it.

Closing this as it's not a current bug report. Feel free to PR additional tests though :smile:

**Closed by sebmck** 2015-06-15 14:34 UTC

**Comment by pygy** [comment] 2015-06-15 14:35
Are there more places where tests should be added (beside the ones I point out in the first file?)

**Comment by sebmck** [comment] 2015-06-15 14:36
[test/core/fixtures/transformation/es6.modules-amd/exports-default](https://github.com/babel/babel/tree/master/test/core/fixtures/transformation/es6.modules-amd/exports-default) and [test/core/fixtures/transformation/es6.modules-umd/exports-default/](https://github.com/babel/babel/blob/master/test/core/fixtures/transformation/es6.modules-umd/exports-default/actual.js).

**Comment by pygy** [comment] 2015-06-15 14:37
forking...
