### ISSUE TITLE
v7 plugin-proposal-class-properties transform flow type annotation to undefined

### ISSUE THREAD

**Issue by allex** [babel/babel#8417] opened 2018-08-03 07:32 UTC
## Bug Report

**Current Behavior**

`@babel/plugin-proposal-class-properties` transform flow type annotation to a property assigning undefined.

this may caught statement order unexpected error.

**Input Code**

```js
let code = `
class B {}
class Logger extends B {
  log: {
    error: boolean
  }
  silent: boolean
  log = {
    error: true
  }
  get silent(): boolean {
    return this._silent;
  }
  set silent(val: boolean) {
    this._silent = !!val;
    if (!this.log) {
      throw new Error('#log should not be nil.')
    }
    Object.keys(this.log).forEach(k => { /* do something... */  })
  }
  constructor() {
    super()
  }
}
`

let r = require("@babel/core").transform(code, {
  "presets": [ "@babel/preset-flow" ],
  "plugins": [
    [ "@babel/plugin-proposal-class-properties", { "loose": true } ]
  ]
})
console.log(r.code)
```

ouput =>

```js
class B {}

class Logger extends B {
  get silent() {
    return this._silent;
  }

  set silent(val) {
    this._silent = !!val;

    if (!this.log) {
      throw new Error('#log should not be nil.')   // <----- will throw if the annotation property assigning undefined
    }

    Object.keys(this.log).forEach(k => { /* do something... */ });
    });
  }

  constructor() {
    super();
    this.log = void 0;  <<<<<----
    this.silent = void 0; <<<<<---- with setter defined.
    this.log = {
      error: true
    };
  }
}
```

**Expected behavior/code**

```js
class B {}

class Logger extends B {
  get silent() {
    return this._silent;
  }

  set silent(val) {
    this._silent = !!val;

    if (!this.log) {
      throw new Error('#log should not be nil.')
    }

    Object.keys(this.log).forEach(k => { /* do something... */ });
  }

  constructor() {
    super();
    this.log = {
      error: true
    };
  }

}
```

**Environment**
- Babel version(s): [e.g. v6.0.0, v7.0.0-beta.55]
- Node/npm version: [e.g. Node 8/npm 5]
- OS: [e.g. OSX 10.13.4]
- Monorepo [e.g. yes/no/Lerna]
- How you are using Babel: `js`

**Possible Solution**

Should strip the `ClassProperty` type of `TypeAnnotation`.

**Comment by davidstritzl** [comment] 2018-08-09 13:30
I came across this issue using react-native 0.56 and babel v7.0.0-beta.47 as well. In my case, an instance property gets overwritten with `void 0` after already being set by the base class constructor.  While I'm not sure that this is the best solution for solving this issue, I fixed the issue for my case by adding [a line from the 6.x branch](https://github.com/babel/babel/blob/6.x/packages/babel-plugin-transform-class-properties/src/index.js#L88) that skips initialisation for all unset instance properties. Here is the patch I used for beta.47:
```javascript
--- a/node_modules/@babel/plugin-proposal-class-properties/lib/index.js
+++ b/node_modules/@babel/plugin-proposal-class-properties/lib/index.js
@@ -197,6 +197,7 @@ var _default = (0, _helperPluginUtils().declare)((api, options) => {
           if (propNode.static) {
             staticNodes.push(buildClassProperty(ref, propNode, path.scope, state));
           } else {
+            if (!propNode.value) continue;
             instanceBody.push(buildClassProperty(_core().types.thisExpression(), propNode, path.scope, state));
           }
         }
```

**Comment by EyMaddis** [comment] 2018-08-10 12:41
I wonder if that behavior was intentionally left out, but based on the comments I would assume that this is not spec compliant and a regression.

**Comment by davidstritzl** [comment] 2018-08-10 14:17
If I understand the proposal correctly, as in the current implementation, instance fields without initialiser should indeed be initialised with `undefined` ([link](https://tc39.github.io/proposal-class-fields/#sec-define-field)). However, it seems that the initialisation of the instance fields should happen before the body of the constructor is executed ([link](https://tc39.github.io/proposal-class-fields/#[[construct]])), which is not what is happening here, but I'm not sure if it is even possible to correctly emulate this behaviour.

**Comment by nicolo-ribaudo** [comment] 2018-08-14 07:09
The current class fields proposal defines class properties before the costructor is run for base classes, and right after calling `super()` for derived classes.
I couldn't find any reference in the Flow documentation about a deviation from this behavior, so I think that Babel is transpiling your code correctly.

**Comment by kdawgwilk** [comment] 2018-08-20 20:28
I am running into this issue and adding the line suggested by @davidstritzl did indeed fix the runtime issues I was seeing but I am worried this is not the right solution.  Would this be okay to have as a temp fix until a patch is released?

**Comment by loganfsmyth** [comment] 2018-08-20 20:45
The newer version of the class fields proposal considers lack of an initializer to mean that the property is defined with a value of `undefined`. In non-`loose` mode, we use `Object.defineProperty`, so it would not trigger setters that exist on the prototype, but since you've opted into `loose` mode, that behavior has been disabled.

I'm not sure there's a course of action for us here. 

It seems like the base of the confusion here is the re-declaration of the types. Given the original
```
class Logger extends B {
  log: {
    error: boolean
  }
  silent: boolean
  log = {
    error: true
  }
  get silent(): boolean {
    return this._silent;
  }
  set silent(val: boolean) {
    this._silent = !!val;
    if (!this.log) {
      throw new Error('#log should not be nil.')
    }
    Object.keys(this.log).forEach(k => { /* do something... */  })
  }
  constructor() {
    super()
  }
}
```
it would be more consistent to do
```
class Logger extends B {
  log: { error: boolean } = {
    error: true
  }
  get silent(): boolean {
    return this._silent;
  }
  set silent(val: boolean) {
    this._silent = !!val;
    if (!this.log) {
      throw new Error('#log should not be nil.')
    }
    Object.keys(this.log).forEach(k => { /* do something... */  })
  }
  constructor() {
    super()
  }
}
```
by including the type of `log` in the declaration itself, and skip re-declaring `silent`, since it's already declared anyway.

**Comment by simonkberg** [comment] 2018-08-23 11:26
Another example where this breaks is when you add typings for legacy react context:

```js
class A extends Component<P> {
  context: Context
  fooBar: FooBar = this.context.fooBar // TypeError: Cannot read property 'fooBar' of undefined
}

class B extends Component<P> {
  context: Context
  fooBar: FooBar

  constructor(props: P, context: C) {
    super(props, context)

    this.fooBar = this.context.fooBar // TypeError: Cannot read property 'fooBar' of undefined
  }
}
```

But you can work around it by re-assigning class properties you have added types for:

```jsx
class A extends Component<P> {
  context: Context = this.context
  fooBar: FooBar = this.context.fooBar
}

class B extends Component<P> {
  context: Context
  fooBar: FooBar

  constructor(props: P, context: C) {
    super(props, context) // this is not enough, the class property will be re-assigned to `void 0``

    this.context = context
    this.fooBar = context.fooBar
  }
}
```

**Comment by c0d3m3nt0r** [comment] 2018-08-23 14:28
I'm having this issue too while running `jest`, in particular with example files like: https://github.com/facebook/react-native/blob/master/Libraries/Animated/src/createAnimatedComponent.js, in where type definition and declaration is being made with flow.
If you have a look at the file pointed above, you will find:
```
class AnimatedComponent extends React.Component<Object> {
    // ...
    _component: any;
    _invokeAnimatedPropsCallbackOnMount: boolean = false;
    _prevComponent: any;
    _propsAnimated: AnimatedProps;
    _eventDetachers: Array<Function> = [];
    _setComponentRef: Function;
    // ...
    constructor(props: Object) {
        super(props);
        this._setComponentRef = this._setComponentRef.bind(this);
    }
    // ...
    _setComponentRef(c) {
        this._prevComponent = this._component;
        this._component = c;
    }
    // ...
}
```
As you can see, some of the property type definitions have default values too, as for example `_invokeAnimatedPropsCallbackOnMount`, but, lets focus on `_setComponentRef`, which is a function. If you keep looking at the code below, in particular the class `constructor()` method:
```
_setComponentRef(c) {
   this._prevComponent = this._component;
   this._component = c;
}
```
The method `_setComponentRef` is being defined later on `AnimatedComponent` source code, but, at the time this file gets compiled by babel, and `@babel/preset-flow` is applied, `_setComponentRef` gets initialized with `void 0`, it does't matter `loose: true` or `loose: false`, in the end its value will be `void 0`. Having that in mind, if you now set focus in `AnimatedComponent` constructor method:
```
constructor(props: Object) {
   super(props);
   this._setComponentRef = this._setComponentRef.bind(this);
}
```
At the time `this._setComponentRef = this._setComponentRef.bind(this);` runs, `this._setComponentRef` has been set with `void 0`, which causes:
```
TypeError: Cannot read property 'bind' of undefined

      at new bind (node_modules/react-native/Libraries/Animated/src/createAnimatedComponent.js:39:53)
      at constructClassInstance (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:3530:18)
      at updateClassComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5227:7)
      at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5907:14)
      at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7949:12)
      at workLoop (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7980:24)
      at renderRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8020:7)
      at performWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8592:22)
      at performWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8527:7)
      at performSyncWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8499:3)
```
It seems something in the process is ignoring `_setComponentRef` definition later in the code, and only stays with  `_setComponentRef: Function`, which is indeed translated into `_setComponentRef = void 0` because it does not specify any default value, but in the end this is not correct, because it should have been initialized to the method definition `_setComponentRef(c) { ... }` that is located later in the code, as displayed above.

If I remove `_setComponentRef: Function;` at the top of `AnimatedComponent` the error disappears, because `_setComponentRef` gets initialized as expected, pointing to the method defined later in the code.

Any thoughts?

Thanks.

**Comment by loganfsmyth** [comment] 2018-08-23 17:47
@simonkberg 

I think `context: Context = this.context` is the way to go if you need to declare properties that are actually declared on parent classes.


@c0d3m3nt0r

> If I remove _setComponentRef: Function; at the top of AnimatedComponent the error disappears, 

What's the motivation for declaring it twice in this context? It's already declared on the type by the `_setComponentRef(c) { ... }` declaration anyway, so doing `_setComponentRef: Function` in fact discards information like the number of and types of the parameters, and the return value.

**Comment by c0d3m3nt0r** [comment] 2018-08-24 15:41
@loganfsmyth, I totally agree, perhaps it is a question that needs to be answered by the react team, due to that code comes from their codebase. Although, @davidstritzl patch makes the issue to go away, I think your point makes sense for me.

**Comment by oriSomething** [comment] 2018-08-28 12:55
Hey, the behaviour of converting fields of type annotations to `void 0`, breaks code bases that uses **Iimmutable.js** with Flow annotations.
because:
```js
class A extends Record({ x: number }) {
  x: number;
}

// become
class A extends Record({ x: number }) {
  constructor(...args) {
    super(...args);
    _defineProperty(this, "x", void 0);
  }
}

// Or in loose mode, it become
class A extends Record({ x: number }) {
  constructor(...args) {
    super(...args);
    this.x = void 0
  }
}
```

**Comment by allex** [comment] 2018-08-28 16:54
yes, I'm also prefer to strip these annotations without initial value.
below diffs is my localized fixes:

```diff
--git a/packages/babel-plugin-proposal-class-properties/src/index.js b/packages/babel-plugin-proposal-class-properties/src/index.js
index 3c333fdd3..30a0dd6a1 100644
--- a/packages/babel-plugin-proposal-class-properties/src/index.js
+++ b/packages/babel-plugin-proposal-class-properties/src/index.js
@@ -366,6 +366,9 @@ export default declare((api, options) => {

         let p = 0;
         for (const prop of props) {
+          // Check property is an type annotation, and skip it
+          if (prop.has("typeAnnotation")) continue;
+
           if (prop.node.static) {
             staticNodes.push(buildClassProperty(t.cloneNode(ref), prop, state));
           } else if (prop.isPrivate()) {
```

**Comment by loganfsmyth** [comment] 2018-08-28 17:08
@oriSomething As mentioned, you'd have to change those to `x: number = this.x` unfortunately.

**Comment by aliceriot** [comment] 2018-08-28 18:31
I'm currently working through upgrading to Babel 7, and I'm dealing with a similar issue to what @c0d3m3nt0r described above. I have a React component, with a class method, where I bind the class method to `.this` in the constructor. It looks more or less like this:

```js
class Editor extends React.Component<Props, State> {
  dispatchTransaction: Function
  constructor(props: Props) {
    super(props)
    ...
    this.dispatchTransaction = this.dispatchTransaction.bind(this)
  }

  dispatchTransaction() {
    ...
  }
}
```

This passes Flow, but the problem described in this issue is causing `this.dispatchTransaction` to be `undefined` when the `constructor` is executed, so I can't call `.bind` and get on my merry way. If I remove the annotation for `dispatchTransaction` then `this.dispatchTransaction` is no longer set to `undefined`, so the method can be bound in the constructor as normal

I need to use a normal method here instead of an arrow function, which I normally do, because I need to be able to mock out this method on the prototype before I mount the component in my tests. I also need to have some sort of Flow annotation for `dispatchTransaction` for reasons described here: https://github.com/facebook/flow/issues/5874. Basically, if you don't have that annotation you'll get this Flow error:

```
Cannot assign this.dispatchTransaction.bind(...) to this.dispatchTransaction because property dispatchTransaction is not writable.
```

The workaround for now is this ugly thing:

```js
constructor(props: Props) {
  super()
  ;(this: any).dispatchTransaction = this.dispatchTransaction.bind(this)
}
```

Anyway, I'm not sure if that helps or hinders clarity on what's going on here! But it seems to me that Flow annotations breaking code which previously worked fine (and is valid JS) isn't correct behavior. But, if anyone knows of a better way to address this issue, I'm all ears - I'm going to go with the `;(this: any)` hack for now.

Thanks!

**Comment by loganfsmyth** [comment] 2018-08-28 18:50
@aliceriot Would you be able to do
```
class Editor extends React.Component<Props, State> {
  dispatchTransaction: Function = this.dispatchTransaction.bind(this);
  
  constructor(props: Props) {
    super(props);
  }
}
```
to sidestep the issue?

**Comment by aliceriot** [comment] 2018-08-28 18:58
ah, that does indeed work! thank you! :ok_hand:

**Comment by nicolo-ribaudo** [comment] 2018-08-30 06:52
FIY, I have opened https://github.com/facebook/flow/issues/6811

**Comment by lxcid** [comment] 2018-09-01 13:03
I resolved it as described in 

https://github.com/facebook/react-native/issues/20150#issuecomment-417858270

**Comment by CrabDude** [comment] 2018-10-15 20:48
So, as much as this is personally annoying, b/c our existing codebase was written based on the existing Flow transform (i.e., no initial `undefined` value), it does appear the current babel@7 treatment is [spec](https://tc39.github.io/proposal-class-fields/#sec-define-field) compliant (emphasis added):

>5. If initializer is not empty, then
>    a. Let initValue be ? Call(initializer, receiver).
>6. Else, **let initValue be undefined.**

This sort of potential conflict comes with the territory of pre-spec transpilation and supra/meta-language constructs (i.e., Flow).

However, it raises the issue that there is, at least FWICT, now no suitable means to add a class property flow annotation except through a flow comment (which I would prefer to avoid if possible)... The conflict is unfortunate, but I don't think it's reasonable to break from language compliance in favor of flow compliance. Flow will necessarily have to evolve/change to address this edge case.

See other discussion here: #8762 https://github.com/babel/babel/pull/8584 https://github.com/facebook/flow/issues/6811

**Comment by lupka** [comment] 2019-03-02 21:36
You guys saved my ass. God bless.

**Comment by robinvw1** [comment] 2019-10-24 18:48
Wow, I just literally spent 5 hours figuring out why my react-native iOS app was not doing any network request. It just didn't resolve or reject. Kudo's for the people [here](https://github.com/facebook/react-native/issues/20405) mentioning that `@babel/plugin-proposal-class-properties` is the dealbreaker.

**Comment by nicolo-ribaudo** [comment] 2020-03-17 09:32
This is fixed by https://github.com/babel/babel/pull/11178, which allows you to use `declare` in front of class fields to mark then as type-only and thus don't initialize them to `undefined`.

**Closed by nicolo-ribaudo** 2020-03-17 09:32 UTC
