### ISSUE TITLE
[Bug]: Updating @babel/core from 7.17.8 to 7.17.9 caused code to be transpiled incorrectly..

### ISSUE THREAD

**Issue by jasonk** [babel/babel#14520] opened 2022-05-03 15:59 UTC
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

I tried to reproduce this in the REPL, but 7.17.10 isn't an option there and that's the only version where I've seen this happen.

### Configuration file name

babel.config.js

### Current and expected behavior

I have this simple method that produces a `get` function that will be used to build an accessor.  It' simple enough that up through 7.17.8 it came out of the transpiler with only whitespace changes:
```js
makeGetter() {
  const wrapper = this;
  return function get() { return wrapper.getInfo( this ); };
}
```
After updating `@babel/core` from `7.17.8` to `7.17.10` it's getting transpiled to this:
```js
  makeGetter() {
    return function get() {
      return this.getInfo(this);
    };
  }
```

### Environment

`@babel/core` - `7.17.10`
`node v16.14.0`

**Comment by jasonk** [comment] 2022-05-03 16:04
After some additional testing I've determined this actually started with `@babel/core` `7.17.9` although it still occurs in `7.17.10` as well.

**Comment by JLHwung** [comment] 2022-05-03 17:13
It seems to me duplicate of https://github.com/babel/minify/issues/1028. Did you use `babel-minify` plugins?

**Closed** 2022-05-12 13:52 UTC
Labels: i: needs triage
