### ISSUE TITLE
Don't mangle symbol names when transforming ES6 module syntax

### ISSUE THREAD

**Issue by jamietre** [babel/babel#2597] opened 2015-10-26 15:18 UTC
When babel transforms ES6 module format into CommonJS format, the variable names become mangled, e.g.
   
    import _ from 'underscore'

becomes

    var _underscore = require('./underscore')
    var _underscore2 = _interopRequireDefault(_underscore)

.. _underscore is only used once, and `_underscore2` is now the module (almost - see below). This makes debugging difficult since the source maps at present do not support symbol name mapping, and may not for some time: see https://code.google.com/p/chromium/issues/detail?id=327092

The benefits of using ES6 module format go away pretty quickly when they come at the consequence of effective debugging. While I guess you can sort of "know" that they get transmogrified into "_variablename2", the gui tools in the debugger don't work, and it just makes it harder to work with the code.

Probably related: every reference to a default import within the code now refers to

    _underscore2["default"]

... I can't think why the symbol wouldn't be defined as the property referenced inline up front, same as the original import statement, rather than requiring all the references in code to be de-optimized this way.

I assume this all has to do with some implementation detail of the module transformation process, and I imagine if it was easy not to do this, then it wouldn't already :) But it would be a big help to fix it -  it's kind of a showstopper for switching to ES6 module format.

**Comment by loganfsmyth** [comment] 2015-10-26 15:55
This is a duplicate of https://github.com/babel/babel/issues/2596 among others.

This behavior is necessary for the code to behave like real ES6 code would. Otherwise imports and exports would not behave according to the spec. The have to live-update, which they would not with your approach.

Unfortunately this is a fact of life until Crome has better support for more complex mappings, as your said.

The only other approach right now would be to consider using SystemJS modules instead, since their structure allows them to avoid this mangling. Since CommonJS exists already, there's no other way to get the live-binding behavior.

**Comment by jamietre** [comment] 2015-10-26 16:13
Sorry for the dup - I was surprised to not find a similar issue but I guess I was searching on the wrong terms!

Thanks for explaining. Has some kind of compromise been considered, e.g. an option to simply allow live-update to not work while preserving symbol names? 

I have to use CommonJS because we are living in a commonjs world here; it won't work to have some modules in another format. So if I can't live without good debugging, then my only choice is to use CommonJS syntax anyway. So having an option to just transform to something that's no worse than if I had written in in CommonJS in the first place at least lets me write code in a futureproof syntax. 

In our current environment every module is precompiled anyway. Any consumer would assume it only works like a CommonJS module.

**Comment by sebmck** [comment] 2015-10-28 04:05
> Has some kind of compromise been considered, e.g. an option to simply allow live-update to not work while preserving symbol names?

This would break semantics and is not something we're willing to support. Feel free to look through the issue @loganfsmyth linked and related ones.

**Closed** 2015-10-28 04:04 UTC

**Comment by mightyiam** [comment] 2017-06-12 04:50
Is this an issue with source maps or with implementation of source maps? Link to any issues, please?

**Comment by abirmingham** [comment] 2017-07-10 19:23
What are folks doing in the meantime? I'm surprised more people aren't vocal about this issue - must be that others don't live in the console as much as I do :)

**Comment by jamietre** [comment] 2017-07-10 19:28
I created an alternate version of `babel-plugin-transform-es2015-modules-commonjs` that doesn't mangle symbols at the expense of not permitting dynamic bindings: 

https://github.com/jamietre/babel-plugin-transform-es2015-modules-commonjs-simple

I haven't kept my promise to keep it up to date with the official transform, but last  checked it still works fine for most purposes (if you don't write any code that mutates bindings). It will absolutely break your code if you use dynamic bindings so I'd strongly recommend only using it in local dev environments.

**Comment by abirmingham** [comment] 2017-07-10 19:36
@jamietre that's great. It looks like Chrome may now support symbol binding mapping though? See [here](https://bugs.chromium.org/p/chromium/issues/detail?id=327092).

**Comment by jamietre** [comment] 2017-07-10 20:01
@abirmingham Yeah - I've been following that bug (for years ;) and the fact that it showed up in Canary kind of contributed to my laziness in keeping the transform up to date. I am still a bit confused how that will just magically start working without symmetric changes to the code that's generating the source maps, though. But either way this is definitely still a thing in practice, and  presumably will affect LTS versions of Node for years to come... :(
