### ISSUE TITLE
Throws away comments from empty catch statement

### ISSUE THREAD

**Issue by nkt** [babel/babel#1904] opened 2015-07-02 14:46 UTC
This code:
```js
try {
  foo();
} catch(e) {
  // do nothing
}
```
Compiles to this:
```js
"use strict";

try {
  foo();
} catch (e) {}

// do nothing
```
It's ok at all, except eslint. It's affecting `no-empty` rule.

**Comment by sebmck** [comment] 2015-07-02 14:52
Duplicate of #758.

**Closed by sebmck** 2015-07-02 14:52 UTC

**Comment by nkt** [comment] 2015-07-02 14:55
@sebmck As I see all relative issues have been closed, but problem still exists.

**Comment by sebmck** [comment] 2015-07-02 15:07
Because it's a wont/cantfix.

On Thursday, 2 July 2015, Nikita Gusakov <notifications@github.com> wrote:

> @sebmck <https://github.com/sebmck> As I see all relative issues have
> been closed, but problem still exists.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/1904#issuecomment-118058688>.
>


-- 
Sebastian McKenzie
