### ISSUE TITLE
Parse private class properties with Flow types

### ISSUE THREAD

**Issue by jamiebuilds** [babel/babel#8140] opened 2018-06-10 03:20 UTC
Flow already supports this syntax:

```js
class Thing {
  #prop1: string;
  #prop2: string = value;
}
```

cc @jridgewell since you implemented private properties

**Comment by wtgtybhertgeghgtwtg** [comment] 2018-06-11 03:43
I've been getting by with
```
class Thing {
  #prop1;
  #prop2 = value;
}
```
and then having the types inferred from assignment, since `prettier` and `eslint` error out otherwise, but, yeah, it's sub-optimal.  Would this be a `babylon` issue, then?

**Comment by jamiebuilds** [comment] 2018-06-11 17:41
babylon has been moved from a separate repo into the babel monorepo.

**Comment by C4Phone** [comment] 2018-06-15 03:13
Hi, I'm new to this community so please correct me if I'm wrong. I tried to reproduce the issue but cannot see any actual problem when trying to use babel to transpile your typescript code.

I tried compiling your script using this babel start kit: clarkdave/babel-typescript-starter@3f16d3186953b181f9f0215ace5cc9a35cf9dd89. And babel was able to:

1. Compile  ``` class Thing {   abc: string;   def: string="ggg"; } ```  To  ``` let Thing = class Thing {   def = "ggg"; }; //# sourceMappingURL=test.js.map ```
2. Find a type error if I try to compile:   ``` class Thing {   abc: string;   def: string=123; } ```  Below is babel's output:  ``` lib/test.ts(3,3): error TS2322: Type '123' is not assignable to type 'string'.  3   def: string=123;     ~~~~~~~~~~~~~~~~ error Command failed with exit code 1. ```

So it appears to me that babel is now able to parse the type information you wanted. Could you be more specific on what your expected output from babel is and how the actual output differs from your expectation? 

Thank you!

**Comment by C4Phone** [comment] 2018-06-15 03:46
I did find the following issue when using the flow version of babel starter kit from omimo/es6-flow-starter@edc8cae70a63ea2405d60316ef34bf5e3eeb43d4.

Babel compiled the following code without finding out about the type error of assigning 123 to a string.

```
class Thing {
  abc: string;
  def: string = 123;
}

console.log('hello');
```

Here is the resulting code:

```
'use strict';

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

var Thing = function Thing() {
  _classCallCheck(this, Thing);

  this.def = 123;
};

console.log('hello');
```

However, I am not sure what the expected output is.

**Comment by nicolo-ribaudo** [comment] 2018-06-15 07:20
The problem is with private properties (with `#` before the name), which are engaged by the `classProperties` parser plugin.

**Comment by nicolo-ribaudo** [comment] 2019-03-01 00:31
PR merged.

**Closed by nicolo-ribaudo** 2019-03-01 00:31 UTC
Labels: Has PR, Spec: Class Fields, area: flow, i: bug
