### ISSUE TITLE
There has been a problem with the installation recently.

### ISSUE THREAD

**Issue by consolejs** [babel/babel#10997] opened 2020-01-13 08:46 UTC
## Bug Report

There was a problem after the recent reinstallation, and I got the following error:

```js
[!] (plugin babel) Error: Package exports for '/Users/xxx/abc/node_modules/@babel/helper-compilation-targets' do not define a '.' subpath
src/index.js
Error: Package exports for '/Users/xxx/abc/node_modules/@babel/helper-compilation-targets' do not define a '.' subpath
```

**Environment**

- Babel version(s): v7.8.0
- Node/npm version: Node 13.0.1/npm 6.12.0
- OS:  OSX 10.11.6
- Monorepo: no
- How you are using Babel: cli

**Comment by consolejs** [comment] 2020-01-13 10:30
> ## Bug Report
> There was a problem after the recent reinstallation, and I got the following error:
> 
> ```js
> [!] (plugin babel) Error: Package exports for '/Users/xxx/abc/node_modules/@babel/helper-compilation-targets' do not define a '.' subpath
> src/index.js
> Error: Package exports for '/Users/xxx/abc/node_modules/@babel/helper-compilation-targets' do not define a '.' subpath
> ```
> 
> **Environment**
> 
> * Babel version(s): v7.8.0
> * Node/npm version: Node 13.0.1/npm 6.12.0
> * OS:  OSX 10.11.6
> * Monorepo: no
> * How you are using Babel: cli


I have removed all node related files from my computer, then reinstall nodejs.
Problem solved. :joy:

Thank you very much!！

**Comment by rajasekarm** [comment] 2020-01-13 11:16
Closing this issue, Since the reporter mentioned it is solved.

**Closed by rajasekarm** 2020-01-13 11:16 UTC
Labels: i: bug, i: needs triage

**Comment by gre** [comment] 2020-01-16 08:52
In fact this is a bug in last version that i can constantly reproduce with Node 13, https://github.com/babel/babel/commit/e7961a08a839b0bfe2c5a08f2e1c7e3d436af144 so we will need a new patch version to address this

**Comment by nicolo-ribaudo** [comment] 2020-01-16 08:56
As a workaround, you can upgrade to Node.js 13.6

**Comment by apmitchell** [comment] 2020-01-27 23:09
@nicolo-ribaudo how can I pull the patched version, if upgrading node isn't an option?

**Comment by nsdevaraj** [comment] 2020-01-28 04:54
Same issue in termux

**Comment by juanmait** [comment] 2020-01-28 20:11
Same error using babel-loader and webpack. It won't compile.

**Comment by nicolo-ribaudo** [comment] 2020-01-28 20:12
We are going to release a new version in a few days.

**Comment by AmberCode** [comment] 2020-01-29 09:31
Not sure it it helps for you, but we had the same issue and it looks like it runs fine with node v12.14.1 and npm v6.13.4.

**Comment by Matheus1714** [comment] 2020-01-29 18:53
My jest-enzyme tests were failed because this error. I change the node and npm versions for node v12.13.1 and npm 6.12.1 using nvm v12.13.1. My tests ran correctly after that.

**Comment by Expertweblancer** [comment] 2020-01-29 19:42
After I upgraded the latest node version (13.7), It works well
Thanks

**Comment by nicolo-ribaudo** [comment] 2020-01-30 12:45
v7.8.4 has been released.

(The fix is line 9 of https://unpkg.com/browse/@babel/helper-compilation-targets@7.8.4/package.json)

**Comment by MilanBgd** [comment] 2020-02-02 12:09
I had the same issue. I updated to the last Node version (13.7) with Homebrew and it works well. Thanks guys!
