### ISSUE TITLE
Babel can not resolve plugins in parent folder with yarn workspaces

### ISSUE THREAD

**Issue by zyklus** [babel/babel#6342] opened 2017-09-29 19:54 UTC
See https://github.com/yarnpkg/yarn/issues/4503 for the issue filed against yarn, but there is discussion there that yarn is not responsible so I'm opening one here as well.

In short, yarn workspaces can cause babel-plugins to be installed outside of the project root so babel is unable to resolve them properly.  It's arguable that babel should look above the project root in other `node_modules` folders for plugins.

**Comment by loganfsmyth** [comment] 2017-09-29 20:07
Can you add a descriptive example of what directory structure isn't working, and how you've configured Babel?

**Comment by loganfsmyth** [comment] 2017-10-23 20:22
Closing since we don't have any way to address this without a working example. Happy to reopen if we get that.

**Closed by loganfsmyth** 2017-10-23 20:22 UTC
Labels: Needs Info

**Comment by matiasfh** [comment] 2018-01-31 20:44
@loganfsmyth I think that the issue that I just found can be related.

I have a monorepo project using yarn workspaces with the following structure:

|-- package.json
|-- packages
|---- shared
|------ components
|------ utils
|---- web
|------ app
|------ otherPackage

The app package is the main entry of the whole app and you fire up that with `nextjs` using `$(npm bin)/next packages/web/app/src` to allow next to find the `pages`  folder.

inside `packages/web/app/src` next will found `.babelrc` and `next.config.js`

The `.babelrc` file is

```
{
   "presets":[
      "next/babel",
      "react-app"
   ],
   "plugins":[
      [
         "emotion",
         {
            "sourceMap":true,
            "autoLabel":true
         }
      ],
      "syntax-dynamic-import",
      [
         "import-inspector",
         {
            "serverSideRequirePath":true
         }
      ],
      "transform-flow-strip-types"
   ],
   "env":{
      "test":{
         "plugins":[
            "transform-react-jsx-source"
         ]
      },
      "production":{
         "plugins":[
            [
               "emotion",
               {
                  "hoist":true
               }
            ]
         ]
      }
   }
}
```

The main page of the package `app`  is importing a component from `packages/shared/components` (this package is called like `@org/styleguide`) as `import { ComponentA } from '@org/styleguide'`. This package is just source code (es5) with a main entry that export everything that is shared.

When running next, an error arise related with transpilation.
`SyntaxError: Unexpected token import` in the file that is been imported by `app`

So, as far as I understand:
1. next is building the app using the local `.babelrc` file that is available in `packages/web/app/src`
2. `babel-loader` is only transpiling the code that belongs to that folder and nothing that comes from outside get's tranpiled.

Is there any solution (even if it's hacky) for something like this? or is this the expected behavior of babel-loader and is more a problem for nextjs guys?

**Comment by HHogg** [comment] 2018-02-08 00:20
We've also encountered this issue (though there is a super simple work around). 

With the following yarn workspaces/lerna structure...

```
/.babelrc
/packages/babel-plugin-transform-do-something
```

Inside the root of the projects .babelrc file, these **do not work**... 


```
{
  "plugins": [
    "@packageScope/babel-plugin-transform-do-something",
    "@packageScope/transform-do-someting"
  ]
}
```

However this **does work**...


```
{ 
  "plugins: [
    "./packages/babel-plugin-transform-do-something",
  ]
}
```

It's not a major issue, but with libraries like eslint and stylelint and a very similar situation where the lint configuration are packages also, those config do work with the workspace/packages/module naming like so ... 

```
// .eslintrc
{
  "extends": ["@packageScope/eslint-config-something"],
}

// .stylelintrc
{
  "extends": "@packageScope/stylelint-config-something"
}
```

**Comment by zvictor** [comment] 2018-02-22 13:25
@matiasfh my nextjs project has a different structure, but it also faces an issue with `next/babel` combined with yarn workspaces. Nextjs runs fine, but when I try to run tests from ava it can't find the preset.

> Is there any solution (even if it's hacky) for something like this?

for now I am defining `{ presets: ['@ava/stage-4', '../node_modules/next/babel'] }` in testing mode.

I wonder, though, who should we report this to. Nextjs, babel or yarn? 😅
