### ISSUE TITLE
Async self-executing named function is transpiled wrong

### ISSUE THREAD

**Issue by droooney** [babel/babel#8963] opened 2018-11-02 11:53 UTC
## Bug Report

**Current Behavior**
The following code throws an error that `bar` is not defined (no error in babel@6).

**Input Code**

```js
async function foo() {
  await (async function bar() {
    await bar();
  })();
}

foo();
```

**Expected behavior**
The code inside an async self-executing named function is able to refer to the function by name.

**Babel Configuration (.babelrc)**

```json
{
  "presets": [
    ["@babel/env", {
      "modules": "cjs",
      "useBuiltIns": "entry"
    }],
    "@babel/typescript",
    "@babel/react"
  ]
}
```

**Environment**
- Babel version(s): @babel/core@7.1.2, @babel/preset-env@7.1.0, @babel/preset-typescript@7.1.0, @babel/preset-react@7.0.0
- Node/npm version: node v10.10.0, npm@6.4.1
- OS: OSX 10.13.6
- Monorepo: no
- How you are using Babel: webpack (loader) / parcel

**Possible Solution**
This is probably caused by asyncToGenerator / regenerator. `bar` is eventually located not inside `bar` itself and the function `bar` is not transpiled into a function declaration (this was in babel@6 and therefore there was no error present), but rather is still a function expression.

**Comment by nicolo-ribaudo** [comment] 2018-11-04 22:17
Note: to debug this issue, only use the async-to-generators plugin (so that we don't use regenerator which adds a lot of noise).

**Comment by nicolo-ribaudo** [comment] 2018-11-04 22:41
Duplicate of #8783.

**Closed by nicolo-ribaudo** 2018-11-04 22:41 UTC
Labels: Spec: Async Functions, i: bug
