### ISSUE TITLE
for..await on async iterator fails

### ISSUE THREAD

**Issue by boopathi** [babel/babel#4639] opened 2016-10-01 20:48 UTC
### Input Code

```js
require("babel-polyfill");
async function* foo() {
  yield "foo";
}
async function bar() {
  for await(let f of foo()) console.log(f);
}
bar().catch(console.log);
```

### Babel Configuration (.bablerc, package.json, cli command)

```js
{
  "presets": ["stage-3"]
}
```

### Expected Behavior

Should print `foo` to console

### Current Behavior

Errors out with `iterator[Symbol.iterator] is not a function` - where it is correct for an asyncgenerator function which contains a Symbol.asyncIterator. But Symbol.asyncIterator is undefined for below given reason

### Possible Solution

The `require("babel-polyfill")` gets pushed to bottom and the definition of `_asyncGenerator` (which is an IIFE and requires Symbol.asyncIterator) is before this require Statement and this doesn't get called - `AsyncGenerator.prototype[Symbol.asyncIterator] = `. Maybe, polyfill in asyncGenerator function if Symbol.asyncIterator is undefined? or instead of IIFE, delay exec on first use ?.

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.17.0
| node             | 6
| npm              |
| Operating System |

**Comment by hzoo** [comment] 2016-10-01 21:10
If i'm not mistaken, http://babeljs.io/docs/usage/polyfill/ You normally need to import the polyfill at the entry point to make sure it loads first (or use import) - might be a bug with hoisting too

**Comment by hzoo** [comment] 2016-10-01 21:15
Oh, actually you don't even need polyfill to run this?

**Comment by boopathi** [comment] 2016-10-01 21:22
Yeah, this error is only when we have a single file and we require polyfill in the same file. So I think this issue is not critical and you can close if needed.

Without the polyfill, `Symbol.asyncIterator` is undefined, and it will result in the same error `iterable[Symbol.iterator] is not a function` - and this will happen only when using `for..await`.

**Comment by hzoo** [comment] 2016-10-01 21:27
I tried the code snippet on node 6.3.0 and I get `foo` without errors?

**Comment by boopathi** [comment] 2016-10-01 22:11
That should be because you tried it with babel-node? I tried it with separate transpiled files. 
Also, doesn't babel-node auto require polyfill ?

**Comment by hzoo** [comment] 2016-10-01 22:59
Ah you're totally right I forgot it did

**Comment by klimashkin** [comment] 2016-10-02 04:37
When I try this code with `6.17.0`
```
async function genAnswers() {
  const stream = [Promise.resolve(1), Promise.resolve(2)];
  for await (const val of stream) {
    console.log(val);
  }
}
genAnswers();
```
I get this webpack error:
`Module not found: Error: Cannot resolve module 'babel-runtime/helpers/asyncIterator'`

**Comment by klimashkin** [comment] 2016-10-02 04:51
^^^ This error appears if `transform-runtime` plugin is added

**Comment by danez** [comment] 2016-10-02 15:23
Seems we did not release `babel-runtime`. So everytime we change `babel-helpers` we also need to  rerelease `babel-runtime` I think.

**Comment by hzoo** [comment] 2016-10-02 19:35
Oh you're right - it's because we are using only-explicit-updates in lerna as well. Yep that makes sense

**Comment by hzoo** [comment] 2016-10-03 16:04
Our recommendation is to require in a separate file or to use `import` syntax which should hoist - but maybe we can do something better here

**Comment by hzoo** [comment] 2016-10-05 13:52
Ok will close this one (unless someone thinks it's something we need to address).

Will track runtime issue in https://github.com/babel/babel/issues/4671

**Closed by hzoo** 2016-10-05 13:52 UTC
Labels: bug

**Comment by OliverJAsh** [comment] 2017-01-17 09:24
I'm able to reproduce this with Babel 6.18.0, same code as above
