### ISSUE TITLE
babel7 + vue 2.5.x + webapcak 4x const / let not changge

### ISSUE THREAD

**Issue by lilingling3** [babel/babel#9358] opened 2019-01-18 05:37 UTC
.babelrc
{
"presets": [
[
"@babel/preset-env",
{
"modules": false,
"targets": {
"browsers": ["> 1%", "last 2 versions", "not ie <= 8"]
}
}
]
],
"plugins": [
"@babel/plugin-proposal-object-rest-spread",
"@babel/plugin-transform-runtime",
"@babel/plugin-syntax-dynamic-import",
"@babel/plugin-syntax-import-meta",
[
"@babel/plugin-proposal-decorators",
{
"legacy": true
}
],
"@babel/plugin-proposal-class-properties",
"@babel/plugin-proposal-json-strings",
"@babel/plugin-proposal-function-sent",
"@babel/plugin-proposal-export-namespace-from",
"@babel/plugin-proposal-numeric-separator",
"@babel/plugin-proposal-throw-expressions",
"@babel/plugin-transform-arrow-functions",
"@babel/plugin-transform-block-scoping",
"@babel/plugin-transform-classes"
]
}

webpack
image
image

**Comment by zeyi2018** [comment] 2019-01-19 14:44
"browsers": ["> 1%", "last 2 versions", "not ie <= 8"]

这配置啥意思？

是说你要求 Babel 支持到这些浏览器，而这些浏览器已经支持原生 let & const 语法。所以 Babel 不去编译这两个语法。

**Comment by uni-zheng** [comment] 2019-01-19 14:52
```
"browsers": ["> 1%", "last 2 versions", "not ie <= 8"]
```

This config mean Babel will compile code for those most latest browsers which has supported let or const.

这配置啥意思？

是说你要求 Babel 支持到这些浏览器，而这些浏览器已经支持原生 let & const 语法。所以 Babel 不去编译这两个语法。

**Comment by danez** [comment] 2019-03-18 05:03
Duplicate of #9357

**Closed by danez** 2019-03-18 05:03 UTC
Labels: i: needs triage, i: question
