### ISSUE TITLE
[Bug]: @babel/traverse 7.17.10 will remove this assign

### ISSUE THREAD

**Issue by SoloJiang** [babel/babel#14525] opened 2022-05-05 07:19 UTC
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```javascript
var Icestore = /** @class */ (function () {
  function Icestore(config) {
      var _this = this;
      // preStore: middleware, model hooks
      this.forEachPlugin('middleware', function (middleware) {
          _this.config.redux.middlewares.push(middleware);
      });
  }

  return Icestore;
}());
```

## Current

```javascript
var Icestore = /** @class */ (function () {
  function Icestore(config) {

      // preStore: middleware, model hooks
      this.forEachPlugin('middleware', function (middleware) {
          this.config.redux.middlewares.push(middleware);
      });
  }

  return Icestore;
}());
```

## Expected

```javascript
var Icestore = /** @class */ (function () {
  function Icestore(config) {
      var _this = this;
      // preStore: middleware, model hooks
      this.forEachPlugin('middleware', function (middleware) {
          _this.config.redux.middlewares.push(middleware);
      });
  }

  return Icestore;
}());
```

### Environment

@babel/traverse 7.17.10

I rollbacked to 7.17.9, it worked.

**Comment by JLHwung** [comment] 2022-05-05 12:04
Can you post the Babel config? Specifically, are you using [babel-plugin-minify-dead-code-elimination](https://github.com/babel/minify/tree/master/packages/babel-plugin-minify-dead-code-elimination)?

**Comment by JLHwung** [comment] 2022-05-05 12:47
Duplicate of https://github.com/babel/minify/issues/1028.

**Closed by JLHwung** 2022-05-05 12:47 UTC
Labels: i: needs triage
