### ISSUE TITLE
[Bug]: traversal of ts ast would cause variable conflict bug

### ISSUE THREAD

**Issue by imtaotao** [babel/babel#14436] opened 2022-04-08 03:39 UTC
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

Origin code is ts file

```ts
import React from 'react';
import { ConfigProviderProps } from './interface';
export declare const ConfigContext: React.Context<ConfigProviderProps>;
declare function ConfigProvider(baseProps: ConfigProviderProps): JSX.Element;
declare namespace ConfigProvider {
    var ConfigContext: React.Context<ConfigProviderProps>;
    var displayName: string;
}
export default ConfigProvider;
export declare const ConfigConsumer: React.Consumer<ConfigProviderProps>;
export { ConfigProviderProps };
```

```js
const ast = parser.parse(code, {
    sourceType: 'module',
    plugins: ['jsx', 'typescript'],
});

traverse(ast, {
  ...
})
```

When I use `@babel/traverse` to traverse, there will be a variable (`ConfigContext`) conflict error, but this is the ts type declaration.

### Current and expected behavior

Should not throw an error

### Environment

nodeJs version: v16.10.0 

"@babel/parser": "^7.16.4",
 "@babel/traverse": "^7.15.4",

**Comment by imtaotao** [comment] 2022-04-08 03:42
Maybe add configuration without generating variable scope.

**Comment by nicolo-ribaudo** [comment] 2022-04-08 09:47
> Maybe add configuration without generating variable scope.

You can set `noScope: true` in the second parameter of `traverse`.

**Comment by nicolo-ribaudo** [comment] 2022-04-08 17:46
Duplicate of #13112

**Comment by nicolo-ribaudo** [comment] 2022-04-08 17:47
@imtaotao This bug is already tracked at https://github.com/babel/babel/issues/13112 (and we already have a PR for it, we just need to revive it), so I'm closing this!

**Comment by nicolo-ribaudo** [comment] 2022-04-08 17:47
Duplicate of https://github.com/babel/babel/issues/13112

**Closed by nicolo-ribaudo** 2022-04-08 17:47 UTC
Labels: i: bug, i: needs triage
