### ISSUE TITLE
Duplicate declaration

### ISSUE THREAD

**Issue by JetLua** [babel/babel#9267] opened 2019-01-02 06:14 UTC
## Bug Report

The following code cannot be compiled when using `@babel/plugin-proposal-private-methods`.
Output: `Duplicate declaration "i"`.

```js
class A {
  #a() {
    const i = 9
  }

  #b() {
    const i = 8
  }
}
```

**Comment by Ateiri** [comment] 2019-01-27 15:49
Same problem in my example, also originally raised ticket in `babel-eslint`

`no-undef` problem of `babel-eslint` + name collision bug.
https://github.com/babel/babel-eslint/issues/746

My PR example reproduce problem:
https://github.com/Ateiri/your-own-game-engine/pull/9

**Comment by nicolo-ribaudo** [comment] 2019-02-01 17:43
If anyone wants to work on this, the problem is that we haven't aliased private methods to `Scopable` in `@babel/types` (you can check that we did it for other function kinds).
When updating that package, you should only edit the files inside `definitions/` and then run `make build` to generate the updated helper functions :wink:

**Comment by gverni** [comment] 2019-02-04 11:42
Hi @nicolo-ribaudo I tried adding `Scopable` as you suggested, but I still have the same issue. I created https://github.com/gverni/babel/pull/1 on my fork (to avoid _polluting_ this repo). Am i doing something wrong?

**Comment by gverni** [comment] 2019-02-04 14:05
Thanks @nicolo-ribaudo for your help and your patience. I created #9453. 

I was thinking alternatively we could instead add: 

`  inherits: "ClassMethod",`

to `ClassPrivateMethod` and only add the `Private` alias:

```javascript
defineType("ClassPrivateMethod", {
  .... 
  inherits: "ClassMethod",
  visitor: [
     ...
  ],
  aliases: ["Private"],
```

I tried and it seems to work, but I'm not sure if there are any side effects to that (as you can guess, this is my first contribution to babel)

**Comment by nicolo-ribaudo** [comment] 2019-02-04 14:09
I don't think that it would be safe, because `aliases` aren't merged: https://github.com/babel/babel/blob/9eb010da5010f4d05468707bbb3bdee42d09f752/packages/babel-types/src/definitions/utils.js#L191

**Closed** 2019-02-04 15:19 UTC
Labels: Has PR, Spec: Private Methods, claimed, i: bug

**Comment by Ateiri** [comment] 2019-02-04 16:51
@nicolo-ribaudo but it's not a private property, it's private method, right? (function prototype) So, it could have declarations inside. For example one private method could have instructions to invoke another private method.
Moreover, I think it should be possible for private properties also if their value are functions.
