### ISSUE TITLE
[Bug]: transform-classes: incorrect output with JSX tagName

### ISSUE THREAD

**Issue by Bowen7** [babel/babel#14842] opened 2022-08-10 07:35 UTC
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

```js
class App extends React.Component {
    constructor(props) {
        super(props);
        this.Test = function () {
            return <>123</>;
        };
    }
    customerRender = () => {
        console.log(this.Test);
        return <this.Test />;
    };
    render() {
        return <div>{this.customerRender()}</div>;
    }
}
```

### Configuration file name

.babelrc

### Configuration

```json
{
    "presets": [
        ["@babel/preset-env", { "modules": false }],
        "@babel/preset-react",
        "@babel/preset-flow",
        ["@babel/preset-typescript", { "allowNamespaces": true }]
    ],
    "plugins": [
        "@babel/plugin-transform-runtime",
        ["@babel/plugin-proposal-decorators", { "legacy": true }]
    ]
}
```

### Current and expected behavior

Current: as [babel playground](https://babeljs.io/repl/#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=false&spec=false&loose=true&code_lz=MYGwhgzhAECCAO9oFMAeAXZA7AJjASsmMOgHQDCA9gLbyVbbrQDeAUNB9MPROgE4BXEpT4AKeH0rwIAShbtOiiAPjIxEqbIDcCxR3QALAJYRSAFWS9oAXmgAzAVhJH60UXLZ6v0PsnQC-LGgAHgA-AEYAJgBmYIB6UJ1vaABfJM4U3S4BXho1Qlw1Gzc5a1D5ZO4sCEoQZFIQSgBzUUMTc0t0GXSvX39AkLbTCysEntTx30KxDyzFPoCg4JwjADdQ5iHSYBz0PL4CnDV3FPiV9fHMlKA&debug=false&forceAllTransforms=true&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=true&sourceType=module&lineWrap=true&presets=env%2Creact%2Cflow&prettier=false&targets=&version=7.18.12&externalPlugins=&assumptions=%7B%7D)
the output is:
```js
// ...
var App = /*#__PURE__*/function (_React$Component) {
  _inheritsLoose(App, _React$Component);

  function App(props) {
    var _this;

    _this = _React$Component.call(this, props) || this;

    _this.customerRender = () => {
      console.log(_this.Test);
      return <this.Test />;
    };

    _this.Test = function () {
      return <>123</>;
    };

    return _this;
  }

  var _proto = App.prototype;

  _proto.render = function render() {
    return <div>{this.customerRender()}</div>;
  };

  return App;
}(React.Component);
```
`this.Test` in `console.log` will transform to `_this.Test`, but `this.Test` in JSX tagName will not change(still without `_` prefix).
So `this.Test` in JSX tagName will be undefined.
React will throw an error: `React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined.`.

Expected: `this.Test` in JSX tagName is defined.

### Environment

- System:
    OS: macOS 12.2
- Binaries:
    Node: 14.19.2
    Yarn: 1.22.15
    npm: 6.14.17
- npmPackages:
    @babel/core: ^7.18.6 => 7.18.6
    @babel/plugin-proposal-class-properties: ^7.0.0 => 7.18.6
    @babel/plugin-proposal-decorators: ^7.0.0 => 7.18.6
    @babel/plugin-proposal-export-namespace-from: ^7.0.0 => 7.18.6
    @babel/plugin-proposal-function-sent: ^7.0.0 => 7.18.6
    @babel/plugin-proposal-json-strings: ^7.0.0 => 7.18.6
    @babel/plugin-proposal-numeric-separator: ^7.0.0 => 7.18.6
    @babel/plugin-proposal-throw-expressions: ^7.0.0 => 7.18.6
    @babel/plugin-syntax-dynamic-import: ^7.0.0 => 7.8.3
    @babel/plugin-syntax-import-meta: ^7.0.0 => 7.10.4
    @babel/plugin-transform-runtime: ^7.0.0 => 7.18.6
    @babel/preset-env: ^7.0.0 => 7.18.6
    @babel/preset-flow: ^7.0.0 => 7.18.6
    @babel/preset-react: ^7.0.0 => 7.18.6
    @babel/preset-typescript: ^7.18.6 => 7.18.6
    babel-eslint: ^10.0.3 => 10.1.0
    babel-jest: ^28.1.3 => 28.1.3
    babel-loader: ^8.0.0 => 8.2.5
    eslint: ^7.1.0 => 7.32.0
    webpack: ^5.40.0 => 5.73.0

**Comment by nicolo-ribaudo** [comment] 2022-08-13 09:53
We already have a PR for this (https://github.com/babel/babel/pull/12279): the problem is that it's not clear, when reading the JSX spec, how this should behave: according to the spec the `this` in the JSX element name is _not_ a "`this` expression".

As a workaround, you can do something like `const { Test } = this; return <this.Test />;`

**Comment by nicolo-ribaudo** [comment] 2022-08-13 09:55
Duplicate of https://github.com/babel/babel/issues/11806

**Closed by nicolo-ribaudo** 2022-08-13 09:55 UTC
Labels: area: react, i: bug
