### ISSUE TITLE
Babel 7: Uncaught ReferenceError after transpiling a module

### ISSUE THREAD

**Issue by Steve06** [babel/babel#8940] opened 2018-10-29 09:47 UTC
My Chrome extension project uses the Chrome-Promise module from https://github.com/tfoxy/chrome-promise/blob/master/chrome-promise.js in order to promisify Chrome API's callback-style functions.

Transpiling the project with Babel 6 has always worked fine. Recently I moved to Babel 7. Since then, when I allow the chrome-promise.js file to be transpiled by Babel, this results in a "Uncaught ReferenceError: ChromePromise is not defined" error when running the extension. The program works well when I leave chrome-promise.js as is, untranspiled.

Here is an excerpt of my webpack config js file:
```
module.exports = {
  mode: 'production',
  entry: {
    cs: ['./build/cs.js'],
    bg: ['./build/bg.js'],
    popup: ['./build/popup.js'],
    chromepromise: ['./build/chromepromise.js']
  },
  output: {
    path: path.join(__dirname, 'build'),
    filename: '[name].js'
  },
  module: {
    rules: [{ 
      test: /\.js$/, 
      exclude: [/node_modules/],
      loader: "babel-loader" 
    }]
  },
```

and one of my package.json with the Babel settings:
```
{
  "name": "Test_CRX",
  "version": "1.0.0",
  "main": "cs.js",
  "scripts": {
    "build": "node build",
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "description": "",
  "dependencies": {
    "@babel/runtime": "^7.1.2",
    "archiver": "^3.0.0",
    "babel-polyfill": "^6.26.0",
    "babel-regenerator-runtime": "^6.5.0",
    "chrome-promise": "^3.0.1",
    "terser": "^3.10.1"
  },
  "devDependencies": {
    "@babel/core": "^7.1.2",
    "@babel/plugin-proposal-decorators": "^7.1.2",
    "@babel/plugin-proposal-function-bind": "^7.0.0",
    "@babel/plugin-transform-modules-umd": "^7.1.0",
    "@babel/plugin-transform-regenerator": "^7.0.0",
    "@babel/plugin-transform-runtime": "^7.1.0",
    "@babel/preset-env": "^7.1.0",
    "@babel/preset-react": "^7.0.0",
    "babel-loader": "^8.0.4",
    "babel-plugin-add-module-exports": "^1.0.0",
    "shelljs": "^0.8.1",
    "terser-webpack-plugin": "^1.1.0",
    "uglifyjs-webpack-plugin": "^2.0.1",
    "webpack": "^4.20.2",
    "webpack-cli": "^3.1.2"
  },
  "babel": {
    "presets": [
      [
        "@babel/env",
        {
          "targets": {
            "chrome": 60
          }
        }
      ],
      "@babel/react"
    ],
    "plugins": [
    ]
  }
}
```

Note: although I use Terser to minify the JS code, the error still occurs when I deactivate it. I posted this question on StackOverflow with no reaction.

**Comment by loganfsmyth** [comment] 2018-10-29 14:44
Is there a repository where we can see a runnable example?

**Comment by Steve06** [comment] 2018-10-29 14:46
No, not really, except that the original post contains a link to the repository of the problematic chrome-promise.js

**Comment by loganfsmyth** [comment] 2018-10-29 14:49
Would you be able to make one for us? It generally makes it dramatically easier to reproduce and track down the cause of issues.

**Comment by ijm87102** [comment] 2018-10-29 14:54
Test

**Comment by Steve06** [comment] 2018-10-29 15:18
Alright, I'll do my best to make one and post it here, probably tmr.

**Comment by Steve06** [comment] 2018-10-30 13:00
Alright, I created a compact repo illustrating the issue, together with instructions, on https://github.com/Steve06/chrome-promise-babel-7-issue-repo

**Comment by Steve06** [comment] 2018-10-31 19:33
@loganfsmyth Have you had any chance to look at the repo yet?

**Comment by liuxingbaoyu** [comment] 2023-11-11 13:42
Because this isue is out of date, I will close it.

**Closed by liuxingbaoyu** 2023-11-11 13:42 UTC
