### ISSUE TITLE
how can we be sure that all of the @babel/* packages we have installed are compatible with each other?

### ISSUE THREAD

**Issue by jedwards1211** [babel/babel#12569] opened 2020-12-29 19:27 UTC
I'm trying to debug a heady issue with babel-plugin-flow-runtime and in the process, I'm trying to make sure my `@babel/*` packages are up-to-date.

Annoyingly, many packages are at version `7.12.10`, and some are at `7.12.12`, but some are only at `7.12.1`.  Right now in my `package.json` I have:

```js
    "@babel/cli": "^7.12.10",
    "@babel/core": "^7.12.10",
    "@babel/node": "^7.12.10",
    "@babel/plugin-proposal-class-properties": "^7.12.1",
    "@babel/plugin-proposal-decorators": "^7.12.10",
    "@babel/plugin-transform-runtime": "^7.12.10",
    "@babel/preset-env": "^7.12.10",
    "@babel/preset-flow": "^7.12.1",
    "@babel/preset-react": "^7.12.10",
    "@babel/register": "^7.12.10",
```

How can I verify that all of these packages are expected to work together?  Compared to `typescript`, which is just one package, I feel like I'm standing on a house of cards.

I mean, obviously I've ideally gotten the latest version of each of these installed, but I still feel less secure than if it were a monolithic package.

I'm seeing weird behavior with this `babel-plugin-flow-runtime` issue where calling `path.parentPath.get(path.listKey)` (i.e. getting the Program body array path) within an `ImportDeclaration` `enter` visitor prevents the `exit` visitor from getting called.  But so far I haven't been able to distill it down to a simple repro.  It's hard to feel confident that the issue is coming from something `babel-plugin-flow-runtime` does and not from some unintended combination of `@babel/*` packages.

**Comment by JLHwung** [comment] 2020-12-30 22:59
The latest versions of every package should work together because in each patch version we only release those _changed_ packages. 

> many packages are at version 7.12.10, and some are at 7.12.12, but some are only at 7.12.1.

That means no changes happen from `@babel/foo` 7.12.1 to `@babel/foo` 7.12.12.

**Comment by jedwards1211** [comment] 2020-12-30 23:36
@JLHwung what if we have to pin certain versions that are behind latest though?  To work around a regression?

**Comment by JLHwung** [comment] 2020-12-31 00:49
@jedwards1211 As user one can pin `@babel/some-package` to certain version. As maintainer we try our best to fix regressions and it will be released in next patch/minor releases, depending on the release schedule.

**Comment by jedwards1211** [comment] 2020-12-31 01:53
But there's no way to be sure a pinned version will work correctly with other packages unless we research and install the versions of all the packages that were latest on a given date, right?  That's much harder to do than just installing an old version of `typescript`, for example.  It's also harder to bisect which babel package is causing the issue when something stops working on a fresh install, than if we just had a single package to bisect versions of.

**Comment by nicolo-ribaudo** [comment] 2020-12-31 13:07
Our goal is to make every version compatible with every other version: updating a single package shouldn't break anything.

Sometimes we accidentally introduce incompatibilities, but when it happens we fix them.

**Comment by JLHwung** [comment] 2021-02-03 14:58
Closing this as there are no action items and OP's question is answered.

**Closed by JLHwung** 2021-02-03 14:58 UTC
Labels: i: question
