### ISSUE TITLE
[Bug]: Code generated by Babel for decorated static accessors throws SyntaxError in Firefox

### ISSUE THREAD

**Issue by SirPepe** [babel/babel#16379] opened 2024-03-25 10:15 UTC
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@rollup/plugin-babel

### Input code

https://babeljs.io/repl#?browsers=last%203%20versions%2C%20not%20dead&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABAEwKYTgJwIZVQYQBtsBnEgCim0wHNUoAaRDMPADygEpEBvAKAC-fPqEiwEKdFlyoAghAioyWStTqNmCdl16DhAATQYceIqRJ8IxMogAqSqLsSJDUk3IVKSWRCSqwIRGxPZUxEYDg4RABeRAAWACYAbj0-AHo0xAA-RABlAE9WbDYAUUxMLAAuRExUYFRayFREKCjwI2Ja5EQAB0wYADcZcJhUQm6fAFt6AAs4boBiWSA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.24.3&externalPlugins=%40babel%2Fplugin-proposal-decorators%407.24.0&assumptions=%7B%7D

```js
function decorateClass(target, context) {
}

function decorateAccessor(target, context) {
}

@decorateClass
class Test {
  @decorateAccessor static accessor foo = 42;
}

// > SyntaxError: reference to undeclared private field or method #A
```

### Configuration file name

`babel.config.mjs`

### Configuration

```js
/* eslint-env node */

const config = {
  presets: [
    ["@babel/preset-env", {}],
    ["@babel/preset-typescript", { allowDeclareFields: true }],
    // See https://github.com/babel/babel/issues/16373#issuecomment-2013163733
  ],
};

if (process.env.NODE_ENV === "test") {
  config.plugins = [
    [
      "@babel/plugin-proposal-decorators",
      {
        version: "2023-11",
      },
    ],
  ];
}

export default config;
```

### Current and expected behavior

Current behavior: with `targets` set to `last 3 versions, not dead`, the generated code throws a syntax error in Firefox. This may be a Firefox problem rather than a Babel problem. Tested with Firefox 124.0.1 (64-bit) and Nightly 126.0a1 (2024-03-24) (64-bit).

Expected behavior: no syntax error in any browser

### Environment

- System:
    - OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
- Binaries:
    - Node: 20.11.0 - ~/.volta/tools/image/node/20.11.0/bin/node
    - npm: 10.2.4 - ~/.volta/tools/image/node/20.11.0/bin/npm
- npmPackages:
    - @babel/cli: ^7.22.5 => 7.24.1 
    - @babel/core: ^7.22.1 => 7.24.3 
    - @babel/plugin-proposal-decorators: ^7.22.3 => 7.24.1 
    - @babel/preset-env: ^7.22.4 => 7.24.3 
    - @babel/preset-typescript: ^7.21.5 => 7.24.1 
    - eslint: ^8.41.0 => 8.57.0

**Comment by JLHwung** [comment] 2024-03-25 15:08
Yes, I am almost sure that this is a FF bug, both JSC and V8 work as expected.

Here is a minimal test case without any Babel helpers or the decorator boilerplates. It should print `42`, currently it throws on FF but works on both JSC and V8:
```js
let capturedPrivateAccess;
class A {
  static #x = 42;
  static [class B {
    static {
      capturedPrivateAccess = (t) => t.#x
    }
  }];
}
console.log(capturedPrivateAccess(A))
```
It seems to me FF somehow marks the whole computed key as if it were defined in the outer scope, this is convenient for the functional context variables such as `this` and `super`, but not the case for private environment where the `#x` should have been resolved. 

Per spec [RS:ClassDefinitionEvaluation](https://tc39.es/ecma262/#sec-runtime-semantics-classdefinitionevaluation), the private environment is set in step 13 and the ClassElementEvaluation is in step 25.

**Comment by nicolo-ribaudo** [comment] 2024-03-25 15:15
I'll ask today to a friend at Firefox, otherwise I'll open one.

Wdyt about creating a bugfix plugin for this, given that because of our decorators transform it might be common?

**Comment by nicolo-ribaudo** [comment] 2024-03-25 15:20
An even minimal example is
```js
let capturedPrivateAccess;
class A {
  static #x = 42;
  static [(class {}, capturedPrivateAccess = (t) => t.#x)];
}
console.log(capturedPrivateAccess(A))
```
the class in the computed key is needed, but the private access doesn't need to be inside the class

**Comment by liuxingbaoyu** [comment] 2024-03-25 15:20
```js
class A {
  static #x = 42;
  static [class B {
    static {
      () => B.#x;
    }
  }];
}
```
There seems to be another difference here, this code throws in Firefox but not in Chrome.

**Comment by nicolo-ribaudo** [comment] 2024-03-25 15:21
Ugh that seems to be a Chrome bug then, it should throw.

**Comment by JLHwung** [comment] 2024-03-25 15:25
> Wdyt about creating a bugfix plugin for this, given that because of our decorators transform it might be common?

Good idea, though I haven't figured out how to workaround this bug except transforming the whole class.

**Comment by nicolo-ribaudo** [comment] 2024-03-25 15:28
It seems like wrapping the computed key in an IIFE works:
```js
let capturedPrivateAccess;
class A {
  static #x = 42;
  static [(() => (class {}, capturedPrivateAccess = () => A.#x))()];
}
console.log(capturedPrivateAccess())
```

**Comment by nicolo-ribaudo** [comment] 2024-03-25 15:43
Fun fact :stuck_out_tongue: In Babel 7.21, compiling this code to es2015:
```js
let capturedPrivateAccess;
class A {
  static #x = 42;
  static [(class {}, capturedPrivateAccess = () => A.#x)];
}
console.log(capturedPrivateAccess());
```
would then at runtime throw an error about `A` being in TDZ.

**Comment by JLHwung** [comment] 2024-03-25 15:58
> Fun fact 😛 In Babel 7.21, compiling this code to es2015:
> 
> ```js
> let capturedPrivateAccess;
> class A {
>   static #x = 42;
>   static [(class {}, capturedPrivateAccess = () => A.#x)];
> }
> console.log(capturedPrivateAccess());
> ```
> 
> would then at runtime throw an error about `A` being in TDZ.

Yes, that is another bug, our current classTDZVisitor blindly forbids any class binding references in the computed key.

**Comment by JLHwung** [comment] 2024-03-25 16:00
> It seems like wrapping the computed key in an IIFE works:
> 
> ```js
> let capturedPrivateAccess;
> class A {
>   static #x = 42;
>   static [(() => (class {}, capturedPrivateAccess = () => A.#x))()];
> }
> console.log(capturedPrivateAccess())
> ```

Great, and we will have to check whether it is an async/generator and emit other IFEs likewise.

**Comment by nicolo-ribaudo** [comment] 2024-03-26 13:59
Even smaller reproduction, from Firefox folks :)
```js
class A {
  static #x = 42;
  static [class {}];
} 
```
This throws in Firefox.

**Comment by nicolo-ribaudo** [comment] 2024-03-26 14:02
This code on the other hand works:
```js
class A {
  static [class A {}];
  static #x = 42;
}
```

Maybe this hints at a better fix than wrapping in an IIFE :thinking:

**Comment by nicolo-ribaudo** [comment] 2024-03-27 18:42
SpiderMonkey just merged a fix for this, but let's still implement a workaround plugin for all the existing Firefox version. @JLHwung do you want to work on it since you are fixing other decorator bugs, or should I do it?

**Comment by JLHwung** [comment] 2024-03-27 20:04
> SpiderMonkey just merged a fix for this, but let's still implement a workaround plugin for all the existing Firefox version. @JLHwung do you want to work on it since you are fixing other decorator bugs, or should I do it?

Thank you. The bugfix is your idea, go ahead, meanwhile I will be kept busy by a few other decorators bugs.

**Closed** 2024-03-31 08:44 UTC
Labels: i: browser bug
