### ISSUE TITLE
Late import when a async generator function is in global scope

### ISSUE THREAD

**Issue by mohsen1** [babel/babel#2095] opened 2015-07-27 20:05 UTC
[From here:](https://babeljs.slack.com/archives/general/p1438027027001390)

Hey folks, I think this is a bug. When using ES7 async/await, if I require `"babel/polyfill"`, it's going to be used before polyfill is required  (`regeneratorRuntime.mark`).

Following code:

```js
'use strict';

import {} from 'babel/polyfill';
import fs from 'fs';

async function* foo () {
  console.log('foo');
}

async function* bar () {
  console.log('bar');
}
```
Will be transpiled to 

```js
'use strict';

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { 'default': obj }; }

var marked0$0 = [foo, bar].map(regeneratorRuntime.mark);

require('babel/polyfill');

var _fs = require('fs');

var _fs2 = _interopRequireDefault(_fs);

function foo() {
  return regeneratorRuntime.async(function foo$(context$1$0) {
    while (1) switch (context$1$0.prev = context$1$0.next) {
      case 0:
        console.log('foo');

      case 1:
      case 'end':
        return context$1$0.stop();
    }
  }, marked0$0[0], this);
}

function bar() {
  return regeneratorRuntime.async(function bar$(context$1$0) {
    while (1) switch (context$1$0.prev = context$1$0.next) {
      case 0:
        console.log('bar');

      case 1:
      case 'end':
        return context$1$0.stop();
    }
  }, marked0$0[1], this);
}
```
as you can see, the require statement in line 7 comes too late.

**Comment by cels** [comment] 2015-07-27 21:02
Just this minute I wanted to file this myself :)
Same problem here with 'normal' generator functions.

**Comment by sebmck** [comment] 2015-07-28 00:14
Duplicate of #832.

**Closed by sebmck** 2015-07-28 00:14 UTC

**Comment by loganfsmyth** [comment] 2015-07-28 00:16
@sebmck I 100% agree this would be a dup if it were `require('babel/polyfill');` but since it is `import 'babel/polyfill';`, shouldn't that be hoisted above function declarations?

**Comment by sebmck** [comment] 2015-07-28 00:17
@loganfsmyth `regenerator` does it's own internal mangling of hoisting which makes it hard to have extremely finegrain control over it.
