### ISSUE TITLE
No "exports" main resolved in @babel/helper-compilation-targets/package.json

### ISSUE THREAD

**Issue by Drogglbecher** [babel/babel#11216] opened 2020-03-05 15:15 UTC
## Bug Report
**Current Behavior**
Since an update to node 13.10.1 I have a problem while building an application with `babel-loader`:
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main resolved in node_modules/@babel/helper-compilation-targets/package.json
```

**Expected behavior/code**
It should build correctly

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
const baseConfig = {
  presets: [
    [
      '@babel/preset-env',
      {
        useBuiltIns: 'entry',
        corejs: 3,
      },
    ],
    '@babel/preset-react',
    '@babel/preset-flow',
    '@babel/preset-typescript',
  ],
  plugins: [
    'react-hot-loader/babel',
    'babel-plugin-styled-components',
    ['@babel/plugin-proposal-class-properties', { loose: true }],
    '@babel/plugin-syntax-dynamic-import',
    isTesting && 'babel-plugin-dynamic-import-node-babel-7',
  ].filter(Boolean),
};

module.exports = {
  sourceType: 'unambiguous',
  ...baseConfig,
  plugins: [
    'idx',
    '@babel/plugin-syntax-import-meta',
    '@babel/plugin-proposal-json-strings',
    [
      '@babel/plugin-proposal-decorators',
      {
        legacy: true,
      },
    ],
    '@babel/plugin-proposal-function-sent',
    '@babel/plugin-proposal-export-namespace-from',
    '@babel/plugin-proposal-numeric-separator',
    '@babel/plugin-proposal-optional-chaining',
    '@babel/plugin-proposal-throw-expressions',
    'babel-plugin-macros',
    [
      require.resolve('babel-plugin-module-resolver'),
      {
        root: ['./'],
        alias: {
          'react-router-dom': './packages/components/Router',
          '@@react-router-dom': './node_modules/react-router-dom',
        },
      },
    ],
  ],
  env: {
    test: {
      plugins: [
        ...baseConfig.plugins,
        '@babel/plugin-transform-modules-commonjs',
      ],
    },
  },
};

```

**Environment**
```
  System:
    OS: macOS Mojave 10.14.6
  Binaries:
    Node: 13.10.1 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.14.2 - /usr/local/bin/npm
  Monorepos:
    Yarn Workspaces: 1.22.0
  npmPackages:
    @babel/core: ^7.8.3 => 7.8.3
    @babel/plugin-proposal-class-properties: ^7.8.3 => 7.8.3
    @babel/plugin-proposal-decorators: ^7.8.3 => 7.8.3
    @babel/plugin-proposal-export-namespace-from: ^7.8.3 => 7.8.3
    @babel/plugin-proposal-function-sent: ^7.8.3 => 7.8.3
    @babel/plugin-proposal-json-strings: ^7.8.3 => 7.8.3
    @babel/plugin-proposal-numeric-separator: ^7.8.3 => 7.8.3
    @babel/plugin-proposal-optional-chaining: ^7.8.3 => 7.8.3
    @babel/plugin-proposal-throw-expressions: ^7.8.3 => 7.8.3
    @babel/plugin-syntax-dynamic-import: ^7.8.3 => 7.8.3
    @babel/plugin-syntax-import-meta: ^7.8.3 => 7.8.3
    @babel/preset-env: ^7.8.3 => 7.8.3
    @babel/preset-flow: ^7.8.3 => 7.8.3
    @babel/preset-react: ^7.8.3 => 7.8.3
    @babel/preset-typescript: ^7.8.3 => 7.8.3
    babel-eslint: ^10.0.3 => 10.0.3
    babel-loader: ^8.0.6 => 8.0.6
    babel-plugin-idx: ^2.4.0 => 2.4.0
    babel-plugin-lodash: ^3.3.4 => 3.3.4
    babel-plugin-macros: ^2.8.0 => 2.8.0
    babel-plugin-module-resolver: ^4.0.0 => 4.0.0
    babel-plugin-styled-components: ^1.10.7 => 1.10.7
    eslint: ^6.8.0 => 6.8.0
    jest: ^25.1.0 => 25.1.0
    webpack: ^4.41.5 => 4.41.5
```

**Possible Solution**
[snowpack](https://github.com/pikapkg/snowpack) resolved the error like [this](https://github.com/pikapkg/snowpack/commit/7de9470a515113ec495472909208c42e59241830). Maybe this could work here too.

---
Edits by @JLHwung 

**Solution**
This is a regression in Node.js. If you hit this issue from search engines, please choose _one_ of the following solutions
1) update `@babel` deps to v7.8.7
2) use Node < 13.9
3) wait until nodejs/node#32107 is fixed! (Probably in the next Node.js patch release).

**Comment by JLHwung** [comment] 2020-03-05 16:21
I can not reproduce this error on my local environments (macOS + Node.js 13.10.1). However I do notice that if `package.json/exports/` is changed to something like
```
"exports": {
    "foo": "./lib/index.js"
  },
```
It will throw exactly the same error as you posted. Can you check if the `node_modules/@babel/helper-compilation-targets/package.json` is same as https://unpkg.com/browse/@babel/helper-compilation-targets@7.8.7/package.json ?

**Comment by Drogglbecher** [comment] 2020-03-05 16:32
Ah, ok, in version 7.8.3 of babel we have
```
{
  "name": "@babel/helper-compilation-targets",
  "version": "7.8.3",
  "author": "The Babel Team (https://babeljs.io/team)",
  "license": "MIT",
  "description": "Engine compat data used in @babel/preset-env",
  "repository": "https://github.com/babel/babel/tree/master/packages/babel-helper-compilation-targets",
  "main": "lib/index.js",
  "exports": false,
  "publishConfig": {
    "access": "public"
  },
  "keywords": [
    "babel",
    "babel-plugin"
  ],
  "dependencies": {
    "@babel/compat-data": "^7.8.1",
    "browserslist": "^4.8.2",
    "invariant": "^2.2.4",
    "levenary": "^1.1.0",
    "semver": "^5.5.0"
  },
  "peerDependencies": {
    "@babel/core": "^7.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.8.3",
    "@babel/helper-plugin-test-runner": "^7.8.3"
  },
  "gitHead": "a7620bd266ae1345975767bbc7abf09034437017"
}
```

The `exports: false` could be the thing here.

**Comment by nicolo-ribaudo** [comment] 2020-03-05 16:34
Yeah, we fixed it in 7.8.4. Although, `exports: false` should work starting with Node 13.2 :thinking: (The fix was for Node 13.1-13.2)

**Comment by JLHwung** [comment] 2020-03-05 16:58
Let the issue stay open for a while as people upgrading to latest node with babel 7.8.3 will be constantly bothered by this issue. I have also filed an issue on node.js: https://github.com/nodejs/node/issues/32107

**Comment by BassemN** [comment] 2020-03-05 19:03
I'm getting the same error so after updating to node v13.10.1 so I switched back to node LTS v12.16.1 and the error gone. I hope this issue fixed soon.

**Comment by BassemN** [comment] 2020-03-05 19:19
I fixed this issue by removing the `node_modules` directory and `package-lock.json` file then run `npm install` to fresh install all packages then the issue was fixed.

**Comment by mluce194** [comment] 2020-03-10 08:47
I had this issue when trying to run gatsby develop. I tried doing some of the things listed above but nothing worked.

**Comment by nicolo-ribaudo** [comment] 2020-03-10 08:58
What is your `@babel/helper-compilation-targets` version?

**Comment by mluce194** [comment] 2020-03-10 13:12
It is 7.8.3

**Comment by comoser** [comment] 2020-03-10 16:34
> I fixed this issue by removing the `node_modules` directory and `package-lock.json` file then run `npm install` to fresh install all packages then the issue was fixed.

This indeed works, with just a few package version updates the gatsby projects can be built again

**Comment by mluce194** [comment] 2020-03-11 08:58
Thanks, it worked! (I had tried re-installing node before but I really had to do npm install to solve this issue)

**Comment by olafChao** [comment] 2020-03-11 11:24
> I fixed this issue by removing the `node_modules` directory and `package-lock.json` file then run `npm install` to fresh install all packages then the issue was fixed.

This works for me!!! Thanks

**Comment by nicolo-ribaudo** [comment] 2020-03-11 14:37
This is a regression i Node.js. If the workaround we released in 7.3.3 doesn't work for you, please either use Node < 13.9 or wait until https://github.com/nodejs/node/issues/32107 is fixed! (Probably in the next Node.js patch release).

**Comment by wilson-manyoma** [comment] 2020-03-11 17:47
Thanks a lot, this error was driving me crazy!

**Comment by henryejemuta** [comment] 2020-03-12 15:34
> I fixed this issue by removing the `node_modules` directory and `package-lock.json` file then run `npm install` to fresh install all packages then the issue was fixed.

Works like champ! Thanks @BassemN

**Comment by nonoesp** [comment] 2020-03-13 17:03
> I fixed this issue by removing the `node_modules` directory and `package-lock.json` file then run `npm install` to fresh install all packages then the issue was fixed.

This fixed it for me. Thanks @BassemN!

**Comment by nicolo-ribaudo** [comment] 2020-03-13 17:27
Node 13.11 has been released!

**Closed by nicolo-ribaudo** 2020-03-13 17:27 UTC
Labels: area: upstream, i: bug

**Comment by Showcase-Joz** [comment] 2020-03-31 18:15
> I fixed this issue by removing the `node_modules` directory and `package-lock.json` file then run `npm install` to fresh install all packages then the issue was fixed.

lovin life....thanks

**Comment by fwextensions** [comment] 2020-05-04 00:33
FWIW, this still happened with babel 7.8.3 and node 13.12, so updating to node >= 13.11 doesn't seem sufficient.  Updating babel to 7.9.6 fixes it, though.

**Comment by groverpankaj** [comment] 2020-05-05 00:36
> Yeah, we fixed it in 7.8.4. Although, `exports: false` should work starting with Node 13.2 🤔 (The fix was for Node 13.1-13.2)

Thanks for this post. I changed the babel package from 7.8.3 to 7.8.4 and did npm installed. This fixed the issue.

**Comment by rodrigopaco1986** [comment] 2020-05-05 19:07
> I fixed this issue by removing the `node_modules` directory and `package-lock.json` file then run `npm install` to fresh install all packages then the issue was fixed.

This worked for me. Babel 7.8.3

**Comment by JamesSingleton** [comment] 2020-05-26 17:21
Interesting, just started getting this on Node 12.17.0 which was released today.

**Comment by vramana** [comment] 2020-05-27 06:39
@JamesSingleton Upgrading the packages to 7.10 fixed the issue for me.

**Comment by kinjalparmar** [comment] 2020-06-04 10:54
For me it simply worked by doing :
**npm i @babel/helper-compilation-targets**

**Comment by abugi** [comment] 2020-06-08 00:51
> I fixed this issue by removing the `node_modules` directory and `package-lock.json` file then run `npm install` to fresh install all packages then the issue was fixed.

Works 100%

**Comment by JohnnyFun** [comment] 2020-06-11 14:11
I tried deleting my node_modules and package-lock.json, but was still getting the error. I ended up just re-cloning my repo and that worked. So...not sure what was up, but fwiw...

**Comment by garrettw** [comment] 2020-06-18 15:53
The latest Node LTS version has this issue too. I had to go back to <12.17.0 to get around it. See [this comment](https://github.com/kufu/smarthr-ui/pull/804#issuecomment-644710849)

**Comment by Alonski** [comment] 2020-08-13 14:32
Can a fix please be made in a new v12 LTS?

**Comment by bupy7** [comment] 2020-10-16 10:35
I just have upgraded `@babel/` packages, removed `node_modules` and reinstalled its. After everything is ok.

**Comment by amkayondo** [comment] 2020-12-06 13:00
> I fixed this issue by removing the `node_modules` directory and `package-lock.json` file then run `npm install` to fresh install all packages then the issue was fixed.

This worked for me
