### ISSUE TITLE
Babel Returns the ES6 Source File

### ISSUE THREAD

**Issue by alexbooker** [babel/babel#2714] opened 2015-11-01 00:26 UTC
#### What I expect to happen:

Given the following file:

```javascript
// Polygon.js

class Polygon {  
  constructor(height, width) {
    this.height = height;
    this.width = width;
  }

  get area() {
    return this.calcArea()
  }

  calcArea() {
    return this.height * this.width;
  }
}
```

I would expect the command *`babel Polygon.js`* to emit ES5-compatible code.

#### What _actually_ happens:

The same ES6 file is returned, unmodified.

There are no errors to report.

#### Other

- I installed `babel` and then `babel-cli` globally. I tried on Node 4.2.1 and Node 0.12.7. I am running on Ubuntu 15.04.
- I got the above code example from [_this tutorial_](http://www.programwitherik.com/what-is-babel-the-javascript-compiler/). 
- This problem is not specific to the _Polygon.js_ example above. I used that as an example. I tried `babel` with numerous stand-alone scripts (including ones _without_ classes) and the problem persists.

**Comment by loganfsmyth** [comment] 2015-11-01 00:27
Duplicate of https://github.com/babel/babel/issues/2692.

**Closed by loganfsmyth** 2015-11-01 00:27 UTC

**Comment by loganfsmyth** [comment] 2015-11-01 00:28
The tutorial is for Babel 5.x, version 6.x was released on Thursday.

**Comment by alexbooker** [comment] 2015-11-01 00:31
_Blargh_... 

Thanks @loganfsmyth.

**Comment by alexbooker** [comment] 2015-11-01 00:39
Could be nice to emit a warning to the console if this is a common mistake.

**Comment by loganfsmyth** [comment] 2015-11-01 00:40
Some of this still needs some figuring out, yeah :) If you're just starting out, it may be easier to do 5.x for another few days til we smooth things out.

**Comment by alexbooker** [comment] 2015-11-01 00:44
@loganfsmyth [*I'm well ahead of you*](https://github.com/alexbooker/sequelize-context/blob/master/package.json#L29) but thanks, mate!
