### ISSUE TITLE
Uncaught SyntaxError:  Use of const in strict mode  /sattic/js/main.chunk.js 199:1  SyntaxError :Use of const in strict mode

### ISSUE THREAD

**Issue by yjwyjw520520** [babel/babel#12711] opened 2021-01-29 02:43 UTC
Uncaught SyntaxError:  Use of const in strict mode  /sattic/js/main.chunk.js 199:1  SyntaxError :Use of const in strict mode

**Comment by yjwyjw520520** [comment] 2021-02-01 07:41
whywhywhy

**Comment by yjwyjw520520** [comment] 2021-02-01 07:42
can you help  help me   i  alway online

**Comment by nicolo-ribaudo** [comment] 2021-02-01 21:09
1. Is this error caused by Babel? If not, this is not the right place to ask since here we only track Babel issues.
2. If you think that this is caused by Babel, can you post your configuration, your input code, and the wrong output code?

**Comment by yjwyjw520520** [comment] 2021-02-02 09:06
> 1. 这是Babel造成的错误吗？如果没有，这不是问的正确地方，因为这里我们仅跟踪Babel问题。
> 2. 如果您认为这是由Babel引起的，是否可以发布您的配置，输入代码和错误的输出代码？



我创建了一个 create-react-app 运行在android5.0上面 出现这个问题 高版本的android没有出现这个问题 有的人说 是 node_modules/webpack-dev-server/client/index.js 这里没有编译 我需要手动编译 我不知道怎么配置
我创建了一个  create-react-app  运行在android5.0上面 出现这个问题  高版本的android没有出现这个问题   有的人说 是 node_modules/webpack-dev-server/client/index.js 这里没有编译  我需要手动编译  我不知道怎么配置 
I created a create react app to run on Android 5.0. This problem does not appear in the higher version of Android. Some people say it is node_ modules/webpack-dev-server/client/ index.js There is no compilation here. I need to compile manually. I don't know how to configure it

**Comment by yjwyjw520520** [comment] 2021-02-02 09:07
This is mine package.json

{
  "name": "cra-test",
  "version": "0.1.0",
  "private": true,
  "homepage": "./",
  "files": [
    "./ie9.js",
    "./ie11.js",
    "./jsdom.js",
    "./stable.js"
  ],
  "dependencies": {
    "@babel/polyfill": "^7.12.1",
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "@types/jest": "^26.0.15",
    "@types/node": "^12.0.0",
    "@types/react": "^16.9.53",
    "@types/react-dom": "^16.9.8",
    "babel-eslint": "^10.1.0",
    "core-js": "^3.8.3",
    "es5-shim": "^4.5.15",
    "object-assign": "^4.1.1",
    "promise": "^8.1.0",
    "raf": "^3.4.1",
    "react": "^17.0.1",
    "react-app-polyfill": "^2.0.0",
    "react-dom": "^17.0.1",
    "react-scripts": "4.0.1",
    "regenerator-runtime": "^0.13.7",
    "typescript": "^4.0.3",
    "vconsole": "^3.4.0",
    "web-vitals": "^0.2.4",
    "whatwg-fetch": "^3.5.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "start:dev": "webpack serve",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      "ie > 8",
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version",
      "not ie <= 8",
      "Android >= 5"
    ]
  },
  "devDependencies": {
    "@babel/cli": "^7.12.10",
    "@babel/core": "^7.12.10",
    "@babel/parser": "^7.12.11",
    "@babel/plugin-transform-runtime": "^7.12.10",
    "@babel/preset-env": "^7.12.11",
    "@babel/preset-stage-0": "^7.8.3",
    "@babel/preset-typescript": "^7.12.7",
    "babel-loader": "^8.2.2",
    "babel-plugin-transform-es2015-modules-commonjs": "^6.26.2",
    "babel-plugin-transform-remove-strict-mode": "^0.0.2",
    "babel-polyfill": "^6.26.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    "customize-cra": "^1.0.0",
    "es6-promise": "^4.2.8",
    "react-app-rewired": "^2.1.8"
  }
}

**Comment by yjwyjw520520** [comment] 2021-02-02 09:08
> 1. Is this error caused by Babel? If not, this is not the right place to ask since here we only track Babel issues.
> 2. If you think that this is caused by Babel, can you post your configuration, your input code, and the wrong output code?


I'm looking forward to your reply

**Comment by fedeci** [comment] 2021-02-03 22:53
Hi @yjwyjw520520 can you provide a reproduction repo, please?

**Comment by yjwyjw520520** [comment] 2021-02-04 01:24
Can you make it clear




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "babel/babel"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月4日(星期四) 上午6:53
收件人:&nbsp;"babel/babel"<babel@noreply.github.com&gt;;
抄送:&nbsp;"yjw"<1424800753@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [babel/babel] Uncaught SyntaxError:  Use of const in strict mode  /sattic/js/main.chunk.js 199:1  SyntaxError :Use of const in strict mode (#12711)





 
Hi @yjwyjw520520 can you provide a reproduction repo, please?

**Comment by JLHwung** [comment] 2021-02-04 02:23
> Can you make it clear

我們需要一個最小可復現倉庫(reproduction repo)：當你遇到一個問題的時候，思考如何最小的步驟讓錯誤「Uncaught SyntaxError: Use of const in strict mode /sattic/js/main.chunk.js 199:1 SyntaxError :Use of const in strict mode」出現，隔離排除其他干擾，創造一個獨立的倉庫。

如果沒有可復現倉庫，那麼你與我們之間會有巨大的溝通成本，我們不知道你的配置，只有你有第一手信息。

關於如何提出一個 issue，請閱讀 https://zhuanlan.zhihu.com/p/52370003 儘管這篇文章是關於Egg.js的，很大程度上它對GitHub上面所有的開源項目都有指導意義：你需要花時間去提一個問題，而不是把錯誤日誌複製粘貼然後求助。

**Comment by yjwyjw520520** [comment] 2021-02-04 02:27
> > Can you make it clear
> 
> 我們需要一個最小可復現倉庫(reproduction repo)：當你遇到一個問題的時候，思考如何最小的步驟讓錯誤「Uncaught SyntaxError: Use of const in strict mode /sattic/js/main.chunk.js 199:1 SyntaxError :Use of const in strict mode」出現，隔離排除其他干擾，創造一個獨立的倉庫。
> 
> 如果沒有可復現倉庫，那麼你與我們之間會有巨大的溝通成本，我們不知道你的配置，只有你有第一手信息。
> 
> 關於如何提出一個 issue，請閱讀 https://zhuanlan.zhihu.com/p/52370003 儘管這篇文章是關於Egg.js的，很大程度上它對GitHub上面所有的開源項目都有指導意義：你需要花時間去提一個問題，而不是把錯誤日誌複製粘貼然後求助。

thanks！

**Comment by yjwyjw520520** [comment] 2021-02-05 01:24
> > Can you make it clear
> 
> 我們需要一個最小可復現倉庫(reproduction repo)：當你遇到一個問題的時候，思考如何最小的步驟讓錯誤「Uncaught SyntaxError: Use of const in strict mode /sattic/js/main.chunk.js 199:1 SyntaxError :Use of const in strict mode」出現，隔離排除其他干擾，創造一個獨立的倉庫。
> 
> 如果沒有可復現倉庫，那麼你與我們之間會有巨大的溝通成本，我們不知道你的配置，只有你有第一手信息。
> 
> 關於如何提出一個 issue，請閱讀 https://zhuanlan.zhihu.com/p/52370003 儘管這篇文章是關於Egg.js的，很大程度上它對GitHub上面所有的開源項目都有指導意義：你需要花時間去提一個問題，而不是把錯誤日誌複製粘貼然後求助。



Can you solve it

**Comment by JLHwung** [comment] 2021-02-24 19:58
Closing due to lack of reproducible repo. If you come up with such repo, feel free to reopen this issue and we are happy to help!

**Closed by JLHwung** 2021-02-24 19:58 UTC
Labels: Needs Info
