### ISSUE TITLE
babel 7 b45+ errors out on class properties

### ISSUE THREAD

**Issue by bugzpodder** [babel/babel#8062] opened 2018-05-28 06:00 UTC
## Bug Report

**Current Behavior**
```
    throw new Error("We don't know what to do with this node type. " + "We were previously a Statement but we can't fit in here?");
    ^

Error: We don't know what to do with this node type. We were previously a Statement but we can't fit in here?
    at NodePath.insertBefore (node_modules/@babel/traverse/lib/path/modification.js:57:11)
    at PluginPass.Class (node_modules/@babel/plugin-proposal-class-properties/lib/index.js:475:14)
    at newFn (node_modules/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call (node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (node_modules/@babel/traverse/lib/context.js:146:19)
    at Function.traverse.node (node_modules/@babel/traverse/lib/index.js:94:17)
```

**Input Code**

```js
import React from "react";

export class App extends React.Component {
  constructor(props) { super(props); }
  f = () => { const { props } = this; }
  static g = () => null;

  render() { return null; }
}
```

**Expected behavior/code**
Errors out in babel 7 b45+, works in babel 77 b44.
Also, babel is very preculiar when repoing this error.  if you try to change the code a little bit more, eg removing f or g, removing export call, remove constructor or contents of f etc etc the error probably  goes away.

**Babel Configuration (.babelrc, package.json, cli command)**
./node_modules/.bin/babel-node src/index.js 

```js
"@babel/core": "7.0.0-beta.49",
    "@babel/preset-env": "7.0.0-beta.49",
    "@babel/preset-react": "7.0.0-beta.49",
    "@babel/node": "7.0.0-beta.49",
    "@babel/runtime": "7.0.0-beta.49",
```
```
{
  "presets": [
    "@babel/env",
    "@babel/preset-react",
  ],
  "plugins": ["@babel/plugin-proposal-class-properties"]
}
```
**Environment**
- Babel version(s): v7.0.0-beta.49
- Node/npm version:  Node 8.9.3/npm 6
- OS:  OSX 10.13.4
- Monorepo no
- How you are using Babel: cli

**Possible Solution**

**Additional context/Screenshots**
works in babel 7 b44

**Comment by loganfsmyth** [comment] 2018-05-28 06:31
Duplicate of #7177

**Closed** 2018-05-28 06:33 UTC

**Comment by Timer** [comment] 2018-05-29 12:53
Is this really a duplicate of #7177? #7177 seems to be more concerned with plugin ordering, specifically the decorator plugin (which we're not using here).
