### ISSUE TITLE
Error: We don't know what to do with this node type...

### ISSUE THREAD

**Issue by tihonove** [babel/babel#8033] opened 2018-05-24 16:44 UTC
## Bug Report

**Current Behavior**
Error while compile:
```
$ babel index.js
Error: We don't know what to do with this node type. We were previously a Statement but we can't fit in here?
    at NodePath.insertBefore (C:\workspace\babel-bug-report\node_modules\@babel\traverse\lib\path\modification.js:55:11)
    at PluginPass.Class (C:\workspace\babel-bug-report\node_modules\@babel\plugin-proposal-class-properties\lib\index.js:257:14)
    at newFn (C:\workspace\babel-bug-report\node_modules\@babel\traverse\lib\visitors.js:237:21)
    at NodePath._call (C:\workspace\babel-bug-report\node_modules\@babel\traverse\lib\path\context.js:65:20)
    at NodePath.call (C:\workspace\babel-bug-report\node_modules\@babel\traverse\lib\path\context.js:40:17)
    at NodePath.visit (C:\workspace\babel-bug-report\node_modules\@babel\traverse\lib\path\context.js:100:12)
    at TraversalContext.visitQueue (C:\workspace\babel-bug-report\node_modules\@babel\traverse\lib\context.js:142:16)
    at TraversalContext.visitSingle (C:\workspace\babel-bug-report\node_modules\@babel\traverse\lib\context.js:102:19)
    at TraversalContext.visit (C:\workspace\babel-bug-report\node_modules\@babel\traverse\lib\context.js:182:19)
    at Function.traverse.node (C:\workspace\babel-bug-report\node_modules\@babel\traverse\lib\index.js:106:17)
```

**Input Code**
Repo: https://github.com/tihonove/babel-bug-report

```js
export class Foo {
    static bar = {};
    constructor(b) {}
    foo = b => b;
}
```

**Babel Configuration (.babelrc, package.json, cli command)**

.babelrc:
```js
{
    "presets": [
        "@babel/es2015"
    ],
    "plugins": [
        "@babel/proposal-class-properties"
    ]
}
```

command:
```
yarn babel index.js
```

**Environment**
- Babel version(s): v7.0.0-beta.47
- Node/npm version: v8.6.0/5.3.0
- OS: Windows 10
- Monorepo: yes
- How you are using Babel: cli or loader

**Comment by loganfsmyth** [comment] 2018-05-28 06:32
Duplicate of #7177

**Closed by loganfsmyth** 2018-05-28 06:32 UTC
Labels: Has PR, i: bug
