### ISSUE TITLE
babel 7 ecmascript 7 configuration

### ISSUE THREAD

**Issue by m-korkut** [babel/babel#9054] opened 2018-11-21 13:28 UTC
how use babel 7 version into ecmascript 7 configuration  ?

example my ->  .babelrc --> 
```json
{
"plugins":[
   //.....
               ],
  "presets": [
     "@babel/env",
     "@babel/flow",
    "@babel/preset-react"
                    ]
 }
```

**Comment by nicolo-ribaudo** [comment] 2018-11-22 08:02
If by "ECMAScript 7 configuration" you mean that you want to transform ECMAScript 7 (2016) to ECMAScript 5, your configuration is already ok.

**Comment by xtuc** [comment] 2018-11-22 09:08
This reminds me about https://github.com/babel/babel/issues/6613, it would be usefull for this kind of use-cases.

**Comment by nicolo-ribaudo** [comment] 2019-03-26 23:58
Closing as a duplicate of #6613. Targeting a specific ECMAScript version isn't supported yet.

**Closed by nicolo-ribaudo** 2019-03-26 23:58 UTC
Labels: i: question
