### ISSUE TITLE
plugin-proposal-class-properties breaks Immutable's Record getter methods

### ISSUE THREAD

**Issue by miguel-guedes** [babel/babel#8762] opened 2018-09-24 16:10 UTC
## Bug Report

**Current Behavior**
Unable to use `Immutable.Record`'s getter methods.

**Input Code**
```sh
mkdir /tmp/test && cd /tmp/test && npm init
npm i -S @babel/cli @babel/core @babel/preset-env @babel/preset-flow @babel/plugin-proposal-class-properties immutable@4.0.0-rc.10
```

(save the following as `main.js`)
```js
// @flow

import Immutable from "immutable";

class T extends Immutable.Record({ items: Immutable.List() }) {
  items: Immutable.List<number>;
}

console.log(new T().items, new T().get("items"));
```

**Expected behavior/code**
The expected behavior is for the generated code to not break getter methods on `Immutable.Record` attributes. `main.js` (above) works as expected when compilation is carried out as given below:
```sh
./node_modules/.bin/babel --no-babelrc --presets @babel/env --presets @babel/flow main.js|node
```

... which produces:
```
List [] List []
```
(`new T().items` getter works)

However, when the proposal-class-properties plugin is used, the getter on the `Immutable.Record` instance no longer works:

```sh
./node_modules/.bin/babel --no-babelrc --presets @babel/env --presets @babel/flow --plugins @babel/plugin-proposal-class-properties main.js|node
```

Produces:
```
undefined List []
```

**Babel Configuration (.babelrc, package.json, cli command)**

No `.babelrc` used. `package.json` below:

```js
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "main.js",
  "directories": {
    "test": "test"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@babel/cli": "^7.1.0",
    "@babel/core": "^7.1.0",
    "@babel/plugin-proposal-class-properties": "^7.1.0",
    "@babel/preset-env": "^7.1.0",
    "@babel/preset-flow": "^7.0.0",
    "immutable": "^4.0.0-rc.10"
  }
}
```

**Environment**
- Babel version(s): v7.1.0
- Node/npm version: Node 8.12.0
- OS: Linux
- Monorepo: N/A
- How you are using Babel: cli

**Possible Solution**
N/A

**Additional context/Screenshots**
N/A

**Comment by miguel-guedes** [comment] 2018-09-25 13:57
Pinging @nicolo-ribaudo for issue triage.

**Comment by nicolo-ribaudo** [comment] 2018-09-25 14:07
The problem is that, per the current proposal, these two codes are equivalent:
```js
class Foo {
  a;
}

class Foo {
  a = undefined;
}
```

For this reason, Babel compiles your code as if it was
```js
// @flow

import Immutable from "immutable";

class T extends Immutable.Record({ items: Immutable.List() }) {
  items: Immutable.List<number> = undefined; // <-- Look, "undefined" here
}

console.log(new T().items, new T().get("items"));
```

I reported this discrepancy between flow and js but I didn't get any response by the flow team (https://github.com/facebook/flow/issues/6811). In the meanwhile, you can workarounf the problem by writing that type annotation using a flow comment:
```js
class T extends Immutable.Record({ items: Immutable.List() }) {
  /*:: items: Immutable.List<number>; */
}
```

I'm closing this issue as a duplicate of https://github.com/babel/babel/issues/8417.

**Closed by nicolo-ribaudo** 2018-09-25 14:07 UTC

**Comment by miguel-guedes** [comment] 2018-09-25 14:41
Found this much nicer workaround by @lxcid: https://github.com/facebook/react-native/issues/20150#issuecomment-417858270

Thanks for the reply @nicolo-ribaudo and for helping me solving this issue! :+1:
