### ISSUE TITLE
imports don't work in babel-node CLI

### ISSUE THREAD

**Issue by RReverser** [babel/babel#1728] opened 2015-06-10 19:40 UTC
When I perform
```javascript
import stuff from './stuff';
```
in babel-node CLI, it silently works but trying to access `stuff` on the following lines throws a `ReferenceError: stuff is not defined`.

**Comment by sebmck** [comment] 2015-06-10 19:57
Duplicate of #1488 and #1264.

**Closed by sebmck** 2015-06-10 19:57 UTC

**Comment by RReverser** [comment] 2015-06-10 20:21
Well, those are closed, so I didn't search through them :P

Why are you saying there is no way to do this? Usual workaround I use is just `var stuff  = require('./stuff')` which works and which I expect `import` in CLI to do for me.

**Comment by sebmck** [comment] 2015-06-10 20:21
Because you need access to the entire source in order to replace references for live bindings/circular dependencies.

**Comment by RReverser** [comment] 2015-06-10 20:23
Can't you "remember" what was last assigned to values by names? Or REPL doesn't allow to share state between commands?

**Comment by sebmck** [comment] 2015-06-10 20:25
You'd have to store a bunch of state and it'd be transformer-specific. Another one that isn't handled is reassigning constants. Architecturally it's tricky too because you don't have access to the entire scope tree either so you need to save it somewhere and then pass it between transforms and it's just a PITA.

**Comment by RReverser** [comment] 2015-06-10 20:26
Yeah I know, but reassigning constants is somewhat less critical than modules not working at all :/ Would you mind if I'd look into it?

**Comment by sebmck** [comment] 2015-06-10 20:28
I'd consider it to be on the same level. Feel free to look into it (you could probably have an option to pass `babel.transform().metadata.modules` back into `babel.transform` and then deserialise it) but it'll probably end up being really hacky for little benefit and not worth the additional complexity just to support one of many possible cases.

**Comment by RReverser** [comment] 2015-06-10 20:30
Yeah, I just want to see if there is a way to do this with relatively small changes to cover minimal functionality. You know, another pair of eyes.
