### ISSUE TITLE
For variable-scoping, incorrect?

### ISSUE THREAD

**Issue by syranide** [babel/babel#10027] opened 2019-05-25 06:44 UTC
## Bug Report

**Current Behavior**
`Duplicate declaration "x"` is thrown for the below code, this does not happen when natively run by e.g. Chrome. See @kzc's comments below for clarification of the ECMA specification where it's also shown that the Bable behavior is incorrect.

This does not matter in itself, it doesn't make sense to write this code. However, e.g. Terser correctly treats them as different scopes and reuses variable names as below if it sees that the for-variable is not used (this mostly happens when using `.entries()` and you at some point stop referencing key or value). This makes it fragile to import some pre-minified code in projects, especially as the error does not show up until it is transpiled by Babel, the code works on its own.

**Input Code**
```js
for (let x of [1]) {
  let x=1;
}
```

**Expected behavior/code**
`x` should be shadowed and the code should compile. Again, see @kzc's comments below for exact expected behavior.

**Environment**
Easily replicated in the Babel repl (online), 7.4.0, use es2015 or preset-env.

https://babeljs.io/repl/#?babili=false&browsers=ie%20%3E%3D%2011&build=&builtIns=false&spec=false&loose=true&code_lz=GYewTgBAFANgpgFwgDwiYEDaBGAugSggG8AoCCeJZAXmwG4SBfIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=env&prettier=false&targets=&version=7.4.5&externalPlugins=

**Possible Solution**
Do not throw the error, the code should compile.

**Comment by kzc** [comment] 2019-05-31 21:17
[13.7.5.1](https://www.ecma-international.org/ecma-262/6.0/#sec-for-in-and-for-of-statements-static-semantics-early-errors) Static Semantics: Early Errors

...
```
IterationStatement :
    for ( ForDeclaration in Expression ) Statement
    for ( ForDeclaration of AssignmentExpression ) Statement
```
* It is a Syntax Error if the BoundNames of ForDeclaration contains "let".
* **It is a Syntax Error if any element of the BoundNames of ForDeclaration also occurs in the VarDeclaredNames of Statement.**
* It is a Syntax Error if the BoundNames of ForDeclaration contains any duplicate entries.
---

I think the operative word is [`VarDeclaredNames`](https://www.ecma-international.org/ecma-262/6.0/#sec-variable-statement-static-semantics-vardeclarednames).

I don't have babel installed, but `acorn@6.1.1` and Node appear to be in agreement with the spec:

```
$ echo 'for(let x of[1]){let x=2}' | acorn >/dev/null && echo ok
ok
$ echo 'for(var x of[1]){let x=2}' | acorn >/dev/null && echo ok
ok
$ echo 'for(var x of[1]){var x=2}' | acorn >/dev/null && echo ok
ok
$ echo 'for(let x of[1]){var x=2}' | acorn >/dev/null && echo ok
Identifier 'x' has already been declared (1:21)
```
```
$ echo 'for(let x of[1]){let x=2}console.log(typeof x!="undefined"?x:"-")' | node
-
$ echo 'for(var x of[1]){let x=2}console.log(typeof x!="undefined"?x:"-")' | node
1
$ echo 'for(var x of[1]){var x=2}console.log(typeof x!="undefined"?x:"-")' | node
2
$ echo 'for(let x of[1]){var x=2}console.log(typeof x!="undefined"?x:"-")' | node
[stdin]:1
for(let x of[1]){var x=2}console.log(typeof x!="undefined"?x:"-")
                       ^
SyntaxError: Identifier 'x' has already been declared
```

As far as minifiers go, they operate on the garbage-in/garbage-out principle. They should generate code that produces the same result when run.

**Comment by syranide** [comment] 2019-06-01 07:33
@kzc Interesting, thank you! I'll bring up this issue with terser instead then.

**Comment by syranide** [comment] 2019-06-01 07:44
Oh wait, this is also a bug in Babel then, isn't it. As babel actually fails when the variable is declared as e.g. `let` in both For and Statement. Which if I'm understanding you correctly, is valid.

**Comment by kzc** [comment] 2019-06-01 12:45
If Babel errors out on `for(let x of[1]){let x=1}` then it's probably a Babel bug. 

Generally if code runs on V8 (Chrome/Node) and Firefox then it's valid. Safari has had (and may still have) a number of scope related bugs.

**Comment by syranide** [comment] 2019-06-01 13:11
@kzc Yeah bable does error on it, see below. Thank you again.

https://babeljs.io/repl/#?babili=false&browsers=ie%20%3E%3D%2011&build=&builtIns=false&spec=false&loose=true&code_lz=GYewTgBAFANgpgFwgDwiYEDaBGAugSggG8AoCCeJZAXmwG4SBfIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=&prettier=false&targets=&version=7.4.5&externalPlugins=

**Comment by kzc** [comment] 2019-06-01 14:21
FWIW the Babel 7.4.5 repl link above did not produce the (incorrect) syntax error for `for(let x of[1]){let x=1}` on my Chrome and Firefox browsers until the `es2015` or `es2015-loose` preset was manually selected.

The `es2016` and `es2017` presets correctly do not produce the syntax error.

**Comment by syranide** [comment] 2019-06-01 18:19
@kzc Sorry, I unclicked everything and it still showed the error for some reason. But when I refreshed now it would no longer show. The link below reproduces it, it uses preset-env (which is recommended). I'm guessing the transform only exists in es2015, when you activate that the error appears.

https://babeljs.io/repl/#?babili=false&browsers=ie%20%3E%3D%2011&build=&builtIns=false&spec=false&loose=true&code_lz=GYewTgBAFANgpgFwgDwiYEDaBGAugSggG8AoCCeJZAXmwG4SBfIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=env&prettier=false&targets=&version=7.4.5&externalPlugins=

**Comment by kzc** [comment] 2019-06-01 19:15
The bug appears to be in [babel-plugin-transform-for-of](https://github.com/babel/babel/blob/eae7a333166eb76ed7e66f50efb7902fda4b247b/packages/babel-plugin-transform-for-of/src/index.js). In the repl disable all presets and only enable that specific plugin. Not much code there. Should be easy for someone to isolate.

**Comment by kzc** [comment] 2019-06-01 19:59
This is amusing... in the Babel REPL if you disable all presets and **only** enable these two plugins **in this specific order** it will work correctly for `for(let x of[1]){let x=1}`:

* transform-block-scoping
* transform-for-of

If the order of these plugins is reversed it will produce the incorrect syntax error.

Note the [order](https://github.com/babel/babel/blob/eae7a333166eb76ed7e66f50efb7902fda4b247b/packages/babel-preset-env/data/plugin-features.js#L32-L75) of the plugins in `babel-preset-env`.

I imagine a lot testing will be required if the order of the plugins in these presets are changed. Something else may inadvertently break.

**Comment by syranide** [comment] 2019-06-01 20:43
@kzc Interesting results! Although without looking at the code I would speculate that the reason it works is because `transform-for-of` incorrectly sets up the scope (or such) and it is `transform-block-scoping` that then trips on the duplicate variables.

Because as we saw before, the code will compile just fine without any presets/plugins, because the AST parser still supports all the features, but it's the transforms that have the logic and emits the error. Thus, I would speculate that the order isn't really a fix, it just makes it not trip.

Anyway, ignore me, I just find this interesting :)

**Comment by kzc** [comment] 2019-06-01 21:48
Sure, it could be fixed in transform-for-of with some duplication of work or additional dependencies, but plugin reordering might be a legitimate fix as well. This isn't the first time plugin order has been an issue: #8128.

Perhaps babel plugins could each have an optional ordering hint of some kind (plugins that must be run before and/or after this plugin) and the plugins could be topologically sorted before use with warnings if a constraint is violated. At the very least it'd reduce the number of bug reports like this one.

**Comment by kzc** [comment] 2019-06-01 21:49
Sure, it could be fixed in `transform-for-of` with some duplication of work or additional dependencies, but plugin reordering might be a legitimate fix as well. This isn't the first time plugin order has been an issue: #8128.

Perhaps babel plugins could each have an optional ordering hint of some kind (plugins that must be run before and/or after this plugin) and the plugins could be topologically sorted before use with warnings if a constraint is violated. At the very least it'd reduce the number of bug reports like this one.

**Comment by overlookmotel** [comment] 2021-05-01 13:12
This appears to be duplicate of #8839.

**Comment by liuxingbaoyu** [comment] 2022-10-30 09:30
Seems to have been fixed, feel free to open an issue if the problem persists.

**Closed by liuxingbaoyu** 2022-10-30 09:30 UTC
Labels: i: bug, pkg: traverse (scope)
