### ISSUE TITLE
Error in babel typeof transform, IE10

### ISSUE THREAD

**Issue by limerickgds** [babel/babel#5760] opened 2017-05-22 13:32 UTC
### Input Code
```js
function Target(target){
        var errMsg = '';
       if (typeof target != 'object'){
            errMsg = 'target error - target itself must be window object';
        }
        if(errMsg){
            throw new Error(errMsg);
        }
        this.target = target;
}

// get iframe
var ifr = document.getElementsByTagName('iframe')[0];
// create messager target
var msg = new Target(ifr.contentWindow);
```
after babel transform
```js
var _typeof = typeof Symbol === "function" && typeof Symbol.iterator === "symbol" ? function (obj) { return typeof obj; } : function (obj) { return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj; };

function Target(target) {
    var errMsg = '';
    if ((typeof target === 'undefined' ? 'undefined' : _typeof(target)) != 'object') {
        errMsg = 'target error - target itself must be window object';
    }
    if (errMsg) {
        throw new Error(errMsg);
    }
    this.target = target;
}
```

### Current Behavior
when i use IE11.
```
SCRIPT5：Access is denied  // iframe.contentWindow.constructor
```

### Possible Solution
fixe [helpers.typeof](https://github.com/babel/babel/blob/master/packages/babel-helpers/src/helpers.js#L8).

### Your Environment
| software         | version(s)
| ---------------- | -------
| Babel            |  6.10.4
| node             |  6.10.0
| npm              |  3.10.10
| Operating System |  macOS 10.12.4

**Comment by hzoo** [comment] 2017-05-22 15:03
It is possible to get a more clear error message? Do you have a Symbol polyfill?

**Comment by Kovensky** [comment] 2017-06-07 04:41
This is a duplicate of #5432.

The problem is that the `typeof` helper looks into the `.constructor` property, but no properties are accessible in the `contentWindow` if it is not same-origin.

I wonder if this could be solved by using `instanceof` instead? It could break in cross-Realm situations, but hopefully nobody is passing `symbol`s around in IE10 Workers...

**Comment by existentialism** [comment] 2017-06-16 15:09
Let's continue discussion in #5432!

**Closed by existentialism** 2017-06-16 15:09 UTC
Labels: duplicate
