### ISSUE TITLE
Compilation error "Support for the experimental syntax 'classProperties' isn't currently enabled" despite having the plugin installed when using linked packages

### ISSUE THREAD

**Issue by wojtekmaj** [babel/babel#8667] opened 2018-09-10 17:10 UTC
## Bug Report

**Current Behavior**

I have the following tree (simplified)

```
-/test
--.babelrc
--some-test-file.js
-.babelrc
-some-file.js
```

If I run `babel` through cli in `/`, it compiles flawlessly.

Here's the catch: `/` is a linked package, which `/test`, another project (test suite for said package), is using (uncompiled version of it, so I wouldn't have to worry about hot module reloading).

Now, both `/` and `/test` have `@babel/plugin-proposal-class-properties` in their `.babelrc` configs.

When I run Webpack in test suite, I get the following error on a file from `/` package:

```sh
ERROR in ../src/Page.jsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: C:\Users\wojte\Projekty\react-pdf\src\Page.jsx: Support for the experimental syntax 'classProperties' isn't currently enabled (38:9):
```

**Input Code**
- REPL or Repo link if applicable:

    * Clone: https://github.com/wojtekmaj/react-pdf/tree/babel-7
    * `yarn`
    * `cd test`
    * `yarn`
    * `yarn start`

Please note that `master` branch runs on Babel 6. I did not have this issue before. It's stopping me from doing the upgrade.

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

Babel should have read `.babelrc` from `/` package and use it for parsing the file from `/`.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
// `.babelrc in `/`

{
  "presets": [
    "@babel/env",
    "@babel/react"
  ],
  "plugins": [
    "@babel/transform-runtime",
    "@babel/proposal-class-properties"
  ]
}

// `.babelrc in `/test`
{
  "presets": [
    [
      "@babel/env",
      {
        "modules": false
      }
    ],
    "@babel/react"
  ],
  "plugins": [
    "@babel/transform-runtime",
    "@babel/proposal-class-properties"
  ]
}
```

**Environment**
- Babel version(s): 7.0.0
- Node/npm version: 10.4.0/6.4.1
- OS: Windows 10
- Monorepo: ?
- How you are using Babel: `loader`

**Comment by wojtekmaj** [comment] 2018-09-10 17:36
I have tried altering my `babel-loader` options, but setting `root: '../'` didn't work for me, it got me this error instead:

```sh
ERROR in ./index.jsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: C:\Users\wojte\Projekty\react-pdf\test\index.jsx: Unexpected token (9:4)

   7 | const render = (Component) => {
   8 |   ReactDOM.render(
>  9 |     <StrictMode>
     |     ^
  10 |       <AppContainer>
  11 |         <Component />
  12 |       </AppContainer>
```

**Comment by nicolo-ribaudo** [comment] 2018-09-10 21:59
Can you share a reproduction for the issue? I tried using wojtekmaj/react-pdf#270 but I get this output:
```js

```

**Comment by wojtekmaj** [comment] 2018-09-11 07:50
That's odd, my CI tests have passed the tests perfectly. Perhaps you're running the tests not from `/` directory? Anyways, that's not the command I'd focus on right now.

**Comment by nicolo-ribaudo** [comment] 2018-09-11 08:08
What is the correct command to reproduce the issue?

**Comment by nicolo-ribaudo** [comment] 2018-09-12 16:29
The problem is that in `test/Test.jsx` you are importing untranspiled files:
```js
// eslint-disable-next-line import/no-unresolved
import { Document, Outline, Page } from 'react-pdf/src/entry.webpack';
// eslint-disable-next-line import/no-unresolved
import 'react-pdf/src/Page/AnnotationLayer.css';
```

Synce they are imported from `node_modules`, they are not handled by Babel because you are explicitly excluding them in your webpack config.

**Comment by wojtekmaj** [comment] 2018-09-15 20:13
I'm afraid it still does not work. I think that your initial suggestion that `babel-loader` simply does not run is not true, as the error comes from `babel-loader` and the file that should be loaded by it.

babel, or babel-loader simply does not recognize which `.babelrc` to use and **uses none**. Why do I think so? We're getting this error:

```
SyntaxError: C:\Users\wojte\Projekty\react-pdf\src\Outline.jsx: Support for the experimental syntax 'classProperties' isn't currently enabled (22:9):

  20 |
  21 | export class OutlineInternal extends PureComponent {
> 22 |   state = {
     |         ^
  23 |     outline: null,
  24 |   }
  25 |

Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation.
```

and it just happens that both `/.babelrc` and `/test/.babelrc` contain `"@babel/proposal-class-properties"` in `"plugins"` section!

At the end of the error I quoted above, there's this stack:

```
 @ ../src/entry.webpack.js 4:0-26 17:0-42
 @ ./Test.jsx
 @ ./index.jsx
 @ multi ./index
```

so it looks like Babel properly resolved the symlink path. This gave me an idea that maybe `babelRcRoots` should have also been resolved:

```js
      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        loader: 'babel-loader',
        options: { babelrcRoots: ['.', '../'] }, // <-- this line fixed it!
      },
```

and tada! It worked.

But I still think I shouldn't have needed to manually point babelrc roots for it.

**Comment by andreechristian** [comment] 2018-09-25 21:33
Wow! @wojtekmaj, you saved my day. I've spent the last 2 hours figuring this out. Waiting for a permanent fix for this. 🎉

**Comment by The-Code-Monkey** [comment] 2018-10-19 06:35
@andreechristian @wojtekmaj Where does that section of code go, in my package.json if so where?

**Comment by byronluk** [comment] 2018-10-19 15:03
@The-Code-Monkey That'll go into your webpack config. https://webpack.js.org/loaders/babel-loader/

**Comment by The-Code-Monkey** [comment] 2018-10-19 15:10
@byronluk I'm using the default one from CRA and never really touched them before does it need to go in all of them or if i did a new on at the bottom would that fix it?

**Comment by swetajain** [comment] 2019-02-26 11:05
Hi,

I am facing the same issue.
My bablerc file:

{

  "plugins": [
			
			 ["@babel/plugin-proposal-class-properties",{"loose": true}],
			  ["@babel/plugin-proposal-decorators",{ "decoratorsBeforeExport": false}]
				],
	"presets": ["@babel/preset-env","@babel/preset-react"]
}

Package,JSON


{
    "name": "helloworld",
    "displayName": "HelloCordova",
    "version": "1.0.0",
    "description": "A sample Apache Cordova application that responds to the deviceready event.",
    "main": "index.js",
    "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1"
    },
    "author": "Apache Cordova Team",
    "license": "Apache-2.0",
    "dependencies": {
        "cordova-browser": "^5.0.4",
        "cordova-plugin-whitelist": "^1.3.3",
        "nvestproductnew": "0.0.5",
        "react": "^16.8.3",
        "react-dom": "^16.8.3",
        "uniq": "^1.0.1",
        "watchify": "^3.11.1"
    },
    "cordova": {
        "plugins": {
            "cordova-plugin-whitelist": {}
        },
        "platforms": [
            "browser"
        ]
    },
    "devDependencies": {
        "@babel/core": "^7.3.4",
        "@babel/plugin-proposal-class-properties": "^7.3.3",
        "@babel/plugin-proposal-decorators": "^7.3.0",
        "@babel/plugin-transform-runtime": "^7.2.0",
        "@babel/preset-env": "^7.3.4",
        "@babel/preset-react": "^7.0.0",
        "babelify": "^10.0.0"
    },
    "browserify": {
        "transform": [
            [
                "babelify",
                {
                    "presets": [
                        "@babel/preset-env",
                        "@babel/preset-react",
                    ]
                }
            ]
        ]
    }
}


Please let me know if I am missing something.

**Comment by nicolo-ribaudo** [comment] 2019-02-26 11:30
What is your exact full error and your directory structure_ Do you have symlinked folders?

**Comment by mattvick** [comment] 2019-03-02 12:09
I had a similar issue and solved this by deleting the `.babelrc` file:

```
// .babelrc
{
  "presets": ["module:metro-react-native-babel-preset"]
}
```

Then adding a `babel.config.js` file:

```
// babel.config.js
module.exports = {
  presets: ["module:metro-react-native-babel-preset"]
}
```

**Comment by nicolo-ribaudo** [comment] 2019-05-07 15:35
The original poster has solved their issue. @swetajain if you still have this problem, please open a new issue or (better) ask in out slack channel.

**Closed** 2019-05-07 15:34 UTC
