### ISSUE TITLE
TypeError: Cannot create property '_blockHoist' on string

### ISSUE THREAD

**Issue by denniskortsch** [babel/babel#9809] opened 2019-04-02 13:44 UTC
## Bug Report

**Current Behavior**
Trying to run `babel-node` on a node server leads to `TypeError: Cannot create property '_blockHoist' on string 'decorateMutate'` where `decorateMutate` is a function that is exported like that: `export const decorateMutate = () => {}`. It is  the same issue with a lot of exports throughout the code base.
After some refactoring to find error source I get `TypeError: Cannot create property '_blockHoist' on string 'default'` sometimes. Depending on the type of import/export...
```js
node_modules/.bin/babel-node ./src/server/start.js
@babel/preset-env: `DEBUG` option

Using targets:
{
  "node": "10.12"
}

Using modules transform: auto

Using plugins:
  syntax-async-generators { "node":"10.12" }
  syntax-object-rest-spread { "node":"10.12" }
  syntax-json-strings { "node":"10.12" }
  syntax-optional-catch-binding { "node":"10.12" }

Using polyfills: No polyfills were added, since the `useBuiltIns` option was not set.
node_modules/@babel/helper-module-transforms/lib/index.js:146
    header._blockHoist = 3;
                       ^

TypeError: Cannot create property '_blockHoist' on string 'decorateMutate'
    at statements.forEach.header (node_modules/@babel/helper-module-transforms/lib/index.js:146:24)
    at Array.forEach (<anonymous>)
    at ensureStatementsHoisted (node_modules/@babel/helper-module-transforms/lib/index.js:145:14)
    at PluginPass.exit (node_modules/@babel/plugin-transform-modules-commonjs/lib/index.js:197:65)
    at newFn (node_modules/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call (node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (node_modules/@babel/traverse/lib/path/context.js:97:8)
    at TraversalContext.visitQueue (node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (node_modules/@babel/traverse/lib/context.js:146:19)
    at Function.traverse.node (node_modules/@babel/traverse/lib/index.js:94:17)
    at traverse (node_modules/@babel/traverse/lib/index.js:76:12)
    at transformFile (node_modules/@babel/core/lib/transformation/index.js:88:29)
    at runSync (node_modules/@babel/core/lib/transformation/index.js:45:3)
    at transformSync (node_modules/@babel/core/lib/transform.js:43:38)
    at Object.transform (node_modules/@babel/core/lib/transform.js:22:38)
    at compile (node_modules/@babel/register/lib/node.js:73:20)
    at compileHook (node_modules/@babel/register/lib/node.js:102:12)
    at Module._compile (node_modules/pirates/lib/index.js:93:29)
    at Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Object.newLoader [as .js] (node_modules/pirates/lib/index.js:104:7)
```

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": [
    "@babel/preset-flow",
    ["@babel/preset-env", {
      "debug": true,
      "loose": false,
      "targets": {
        "node": true
      }
    }]
  ],
  "plugins": [["@babel/plugin-proposal-object-rest-spread", { "loose": true, "useBuiltIns": true }]]
}
```

**Environment**
- Babel version(s): 
```
"@babel/core": "^7.4.0",
"@babel/node": "^7.2.2",
"@babel/preset-env": "^7.4.2",
"@babel/preset-flow": "^7.0.0",
"@babel/plugin-proposal-object-rest-spread": "^7.4.0"
```
- Node/npm version: 10.12
- OS: OSX 10.14.4
- Monorepo: yarn workspace
- How you are using Babel: babel-node 

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

We are migrating from earlier babel version. The previous babel config was:
```
"presets": ["react", ["es2015"], "stage-0", "flow"],
  "plugins": [ "transform-decorators-legacy", "transform-runtime"]
```

**Comment by lishine** [comment] 2020-01-05 13:00
I have similar error
```
module.exports = {
	sourceMaps: "both",
	presets: [
		[
			'@babel/preset-env',
			{
				targets: {
					node: 'current',
				},
			},
		],
	],
	plugins: [
		[
			'module-resolver',
			{
				root: ['./src'],
			},
		],
		'@babel/plugin-proposal-optional-chaining',
		'@babel/plugin-proposal-export-default-from',
	],
}

```

node v8.16.2

package.json
```
		"@babel/cli": "7.7.0",
		"@babel/core": "7.7.2",
		"@babel/node": "7.7.0",
		"@babel/plugin-proposal-export-default-from": "7.5.2",
		"@babel/plugin-proposal-optional-chaining": "7.7.4",
		"@babel/preset-env": "7.7.1",
		"babel-eslint": "10.0.3",
		"babel-plugin-module-resolver": "3.2.0",
		"babel-plugin-transform-define": "2.0.0",
		"babel-register": "^6.26.0",
```
.babelrc.js
```
module.exports = {
	sourceMaps: "both",
	presets: [
		[
			'@babel/preset-env',
			{
				targets: {
					node: 'current',
				},
			},
		],
	],
	plugins: [
		[
			'module-resolver',
			{
				root: ['./src'],
			},
		],
		'@babel/plugin-proposal-optional-chaining',
		'@babel/plugin-proposal-export-default-from',
	],
}
```

**Comment by liuxingbaoyu** [comment] 2022-11-29 13:37
Since it's been a long time, I can't reproduce this issue, so I will close it, if the problem persists please open a new issue.

**Closed by liuxingbaoyu** 2022-11-29 13:37 UTC
Labels: i: bug, i: needs triage
