### ISSUE TITLE
browser.js and browser.min.js are empty files version 6.0.15

### ISSUE THREAD

**Issue by NetanelBasal** [babel/babel#2734] opened 2015-11-02 06:51 UTC
I installed with npm the babel-core and this files are empty, i need them for system js.

**Comment by sebmck** [comment] 2015-11-02 07:12
Duplicate of #2635. Please search before reporting issues in the future. Also Babel 6 wont even work with SystemJS so you'll need to use a 5.x version.

**Closed by sebmck** 2015-11-02 07:12 UTC
