### ISSUE TITLE
Super call in bound class method can't be transpiled

### ISSUE THREAD

**Issue by philippotto** [babel/babel#5104] opened 2017-01-13 20:13 UTC
I have `transform-class-properties` enabled, but `super` calls in bound class methods do not work (webpack aborts transpilation).

### Input Code
[Repl](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&code=class%20B%20%7B%0A%20%20c()%20%7B%0A%20%20%20%20%0A%20%20%7D%0A%7D%0A%0Aclass%20Works%20extends%20B%20%7B%0A%09c()%20%7B%0A%20%20%20%20super.c()%3B%0A%20%20%7D%0A%7D%0A%0Aclass%20Fails%20extends%20B%20%7B%0A%09c%20%3D%20()%20%3D%3E%20%7B%0A%20%20%20%20super.c()%3B%0A%20%20%7D%0A%7D&experimental=true&loose=false&spec=false)
```js
class B {
  c() {
    
  }
}

class Works extends B {
  c() {
    super.c();
  }
}

class Fails extends B {
  c = () => {
    super.c();
  }
}
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  presets: [
    ["env", {
      "targets": {
        "browsers": [
          "last 3 Chrome versions",
          "last 3 Firefox versions",
          "last 2 Edge versions",
          "last 1 Safari versions",
          "last 1 iOS versions"
        ]
      },
      "exclude": [
        "transform-regenerator"
      ]
    }],
    "react",
  ],
  plugins: [
    "transform-async-to-generator",
    "transform-class-properties",
    "transform-flow-strip-types",
  ]
}

```

### Expected Behavior
It should transpile successfully and make the super call.

### Current Behavior
Webpack aborts transpilation.

### Possible Solution
As a workaround, I currently use `SuperClassName.prototype.methodName.call(this);` instead of `super.methodName()` as a work around. I think the transpiler could generate exactly the same?

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.21.0
| node             | 5.10.1
| npm              | 3.8.3
| Operating System | Win10

**Comment by toddself** [comment] 2017-01-16 17:22
You aren't calling `super()` in the constructor for the classes you're extending:

```js
class B {
  c() {
    
  }
}

class Works extends B {
  constructor () {
    super()
  }
  
	c() {
    super.c();
  }
}

class Fails extends B {
  constructor () {
    super()
  }
	c = () => {
    super.c();
  }
}
```

**Comment by philippotto** [comment] 2017-01-17 14:33
By the way, the workaround I provided does not work if the method in the super class is also bound with a fat arrow. I'm not even sure if this should be possible, but in CoffeeScript it was, which is why I'm dealing with this right now.

**Comment by motiz88** [comment] 2017-02-13 06:19
For anyone wondering - `super` in a class property initializer should indeed work per the [current proposal](https://tc39.github.io/proposal-class-public-fields/#runtime-semantics-class-public-field-definition-evaluation), as also noted [here](https://github.com/tc39/tc39-notes/blob/master/es7/2016-07/jul-27.md#conclusionresolution-8).

@philippotto Hopefully clarifying nitpick: These aren't "bound methods", they're instance properties initialized with arrow function expressions. So, by design, they don't appear on the prototype and aren't accessible via `super`.

**Comment by loganfsmyth** [comment] 2017-04-28 17:34
I filed the parser bug so once that is fixed we can check back and see if any other transformer logic is needed.

**Comment by rjhilgefort** [comment] 2017-09-12 20:07
@loganfsmyth Would you mind dropping a link to the issue you filed so we can follow along?

Any updates on this in general?

**Comment by existentialism** [comment] 2017-09-12 20:14
@rjhilgefort the babylon link is actually right above (https://github.com/babel/babylon/issues/498), and a fix was landed here https://github.com/babel/babylon/issues/498

**Comment by nicolo-ribaudo** [comment] 2018-04-03 12:13
This bug has been fixed - https://github.com/babel/babylon/pull/499

**Closed by nicolo-ribaudo** 2018-04-03 12:13 UTC
Labels: Spec: Class Fields, i: bug
