### ISSUE TITLE
async/await arrow expressions are broken when rest parameters are used

### ISSUE THREAD

**Issue by helios1138** [babel/babel#2256] opened 2015-08-24 13:45 UTC
test case:
```js
function test(a) {
  return a * 2;
}

var cb = async (...args) => await test(...args);

cb(123)
  .then((result) => console.log(result))
  .catch((e) => console.error(e));
```

expected result: `246`
actual result: `NaN`

for example, http://babeljs.io/docs/advanced/transformers/other/bluebird-coroutines/ in this case do work as expected

**Comment by sebmck** [comment] 2015-08-24 13:52
Duplicate of #1882.

**Closed by sebmck** 2015-08-24 13:52 UTC
