### ISSUE TITLE
Destructuring assignment left-hand side allows parens

### ISSUE THREAD

**Issue by sebmck** [babel/babel#9899] opened 2019-04-25 05:28 UTC
## Bug Report

**Current Behavior**

`babel-parser` accepts the following but should not.

**Input Code**

```js
[(a = 1)] = t;
[([b])] = t;
```

**Expected behavior/code**

It should error.

**Comment by nicolo-ribaudo** [comment] 2019-05-26 20:23
This is probably a duplicate of https://github.com/babel/babel/issues/8796

**Closed** 2019-12-10 01:29 UTC
Labels: i: bug, pkg: parser
