### ISSUE TITLE
_objectWithoutProperties number computed properties

### ISSUE THREAD

**Issue by iddan** [babel/babel#7689] opened 2018-04-07 21:49 UTC
Choose one: is this a bug report or feature request? Bug report

### Input Code
https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=MYewdgzgLgBATiA7jAvDALAbgFCkrUAGwFcBbMVGAJh2wHo6YAREAUwjFkRDgGtsAbgEM4MAN4wA2gkQBdAFzipRMmAUwA-gBoYAOn1hWADygAlJDAC-O_bsMmAyq1iXKY7AEh0i9zD8wPKkUoOGJWLWx_KwjLHDwIEEJWXUIQAHMACnszJB1spygASloGGAB1Hl4IbEERJWkkdQlJFXJ1bT0DYxzka067boKrN09vcUj_QODQ8Im_a2xY3HAEpJT0rO7zRDzB52KgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&lineWrap=true&presets=es2015%2Ces2016%2Ces2017%2Creact%2Cstage-0%2Cstage-1%2Cstage-2%2Cstage-3&prettier=false&targets=&version=6.26.0&envVersion=

**Doesn't Work**
```js
const { [row]: { [column]: _, ...nextRow }, ...nextSet } = {
	4: {
    	2: true,
    },
};
console.log(nextRow, nextSet);
```

**Work**

Same code as above:
```js
const { [row]: { [column]: _, ...nextRow }, ...nextSet } = {
	4: {
    	2: true,
    },
};
console.log(nextRow, nextSet);
```

```json
{
   "presets": ["react-app"]
}
```

### Expected Behavior
Computed numeric properties to be transformed before omitted

### Current Behavior
Requires to manually transform computed numeric properties to strings before omitting 

### Possible Solution
Computed numeric properties to be transformed to strings before omitted automatically

### Context
I was surprised to discover a spread operation to work as expected

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  ^7.0.0-beta.38
| node             | v9.9.0
| npm              | 5.5.1
| Operating System | macOS 10.12.6

**Comment by xtuc** [comment] 2018-04-12 13:00
I edited your issue to add the "Same code as above" mention. I passed 5 minutes to find the differences and they aren't actually. Or is that not intentional?

**Comment by iddan** [comment] 2018-04-13 16:28
Sorry, I can't see the history of my issue but what happened is that when I wrapped the numeric keys with `String()` they worked because Babel doesn't translate numeric keys to strings as it should.

**Comment by nicolo-ribaudo** [comment] 2018-04-13 17:08
It looks like this issue is a duplicate of https://github.com/babel/babel/issues/6341

**Closed by nicolo-ribaudo** 2018-04-13 17:08 UTC
