### ISSUE TITLE
Line breaks in import modules

### ISSUE THREAD

**Issue by dubert** [babel/babel#2116] opened 2015-07-29 15:31 UTC
First off: 
`react-native@0.8.0`
`babel@5.8.19`
`babel-core@5.8.19`

Why can't I do this?

```js
import React, {
  Component,
  View,
  Navigator,
  Text,
} from 'react-native'
```
It gives me the error: `Requiring unknown module "react-native".`

Both of these work fine: 
```js
import React, { Component, View, Navigator, Text } from 'react-native'

import React from 'react-native'
import {
  Component,
  View,
  Navigator,
  Text,
} from 'react-native'
```

I spent 30 minutes tweaking every setting in my `.babelrc` but it doesn't make a difference. Why do line breaks just magically bork it?

**Comment by sebmck** [comment] 2015-07-29 15:33
> Why can't I do this?

As far as I can see, you can:

```javascript
import React, {
  Component,
  View,
  Navigator,
  Text,
} from 'react-native'
```

produces the **exact(( same code as:

```javascript
import React, { Component, View, Navigator, Text } from 'react-native'
```

**Comment by keithamus** [comment] 2015-07-29 15:49
If you look closely @dubert your second example doesnt have a comma after React. 

```js
import React { Component, View, Navigator, Text } from 'react-native'
```
and
```js
import React, {
  Component,
  View,
  Navigator,
  Text,
} from 'react-native'
```

Are different, because the second one has a comma: `React,`

**Comment by sebmck** [comment] 2015-07-29 15:49
@keithamus That's probably just a typo, it would produce a syntax error, now way it can result in the error they're getting.

**Comment by keithamus** [comment] 2015-07-29 15:50
I thought as much but if there's small errors in the issue report, maybe its worth double checking if there is a typo in actual code.

**Comment by dubert** [comment] 2015-07-29 15:56
I doubled-checked, it's not a typo in the code. It's just a typo in the comment.

**Comment by sebmck** [comment] 2015-07-29 15:57
Can you put together a repro case? There's nothing obvious from the code snippets provided as they compile to the same code.

**Comment by dubert** [comment] 2015-07-29 15:57
Sure! Give me a few minutes.

**Comment by dubert** [comment] 2015-07-29 16:08
https://github.com/dubert/babel-test

**Comment by pushrax** [comment] 2015-08-09 20:24
I'm also running into this with React Native, haven't had a chance to dig in yet but hopefully will tomorrow.

**Comment by sebmck** [comment] 2015-09-01 04:25
Closing due to lack of reproducible example.

**Closed by sebmck** 2015-09-01 04:25 UTC

**Comment by sebmck** [comment] 2015-09-01 04:26
Wait no you did provide a reproducible example. The problem is almost certainly in `react-native`. cc @amasad for the package. It looks like the method of extracting module sources does not pick up this specific case. IIRC it uses a regex? It needs to handle trailing commas.

**Comment by dubert** [comment] 2015-09-01 14:17
So this is not an issue with Babel, it's an issue with React-Native?

**Comment by sebmck** [comment] 2015-09-01 14:30
@dubert Yes.

**Comment by dizlexik** [comment] 2015-09-02 21:14
Just ran into this issue myself. Please link to the issue on the react-native repo when you create it over there.

**Comment by lanceharper** [comment] 2015-09-22 17:17
FWIW, if anyone else runs into issue, it is related to react native's module extraction as mentioned. Unless it gets addressed in the official repo, you'll need to fork and update https://github.com/facebook/react-native/blob/master/packager/react-packager/src/DependencyResolver/replacePatterns.js#L13 to:

```javascript
exports.IMPORT_RE = /(\bimport\s+(?:[^'"]+\s+from\s+)??)(['"])([^'"]+)(\2)/g;
```

**Comment by dizlexik** [comment] 2015-09-22 17:31
Here's an issue (facebook/react-native#1939) and a pull request (facebook/react-native#1940) regarding this over on the official repo.
