### ISSUE TITLE
[@babel/cli] Maximum call stack size exceeded when transpiling a large number of files

### ISSUE THREAD

**Issue by SamyPesse** [babel/babel#7284] opened 2018-01-27 13:44 UTC
After upgrading to babel 7, the command to transpile a directory, that worked well in the same project with Babel 6 is failing with a `Maximum call stack size exceeded` after transpiling **369 files**.

The command executed is:

```
babel --copy-files --ignore '**/__tests__/*.js,node_modules' --out-dir ./functions ./modules
```

When executed on a subset of the the folder, it works well. It seems to be an issue with the number of files being transpiled.

### Stack trace

(The stack trace changes with the number of files being transpilled).

```
RangeError: Maximum call stack size exceeded
    at normalizeStringPosix (path.js:78:30)
    at Object.normalize (path.js:1193:12)
    at Object.join (path.js:1228:18)
    at getDest (<project>/node_modules/@babel/cli/lib/babel/dir.js:57:26)
    at <project>/node_modules/@babel/cli/lib/babel/dir.js:70:20
    at write (<project>/node_modules/@babel/cli/lib/babel/dir.js:30:14)
    at handleFile (<project>/node_modules/@babel/cli/lib/babel/dir.js:66:5)
    at sequentialHandleFile (<project>/node_modules/@babel/cli/lib/babel/dir.js:89:5)
    at <project>/node_modules/@babel/cli/lib/babel/dir.js:94:9
    at <project>/node_modules/@babel/cli/lib/babel/dir.js:75:14
```

### Babel Configuration

```js
{
    "presets": [
        ["@babel/env", {
            "targets": {
                "node": "6.11.5"
            }
        }],
        "@babel/flow",
        "@babel/react"
    ],
    "plugins": [
        "@babel/plugin-proposal-object-rest-spread",
        "@babel/plugin-proposal-class-properties",
        "transform-decorators",
        [ "module-resolver", {
            "alias": {
                "@gitbook": "./modules",
                "aphrodite": "aphrodite/no-important"
            },
            "cwd": "babelrc"
        }]
    ],
    "ignore": [
        "modules/node_modules/**/*",
        "modules/styleguide/icons/*.js"
    ]
}
```

**Comment by loganfsmyth** [comment] 2018-03-05 05:43
Looks like a duplicate of https://github.com/babel/babel/issues/7306 which has been fixed.

**Closed by loganfsmyth** 2018-03-05 05:43 UTC
