### ISSUE TITLE
[Bug]: Support for the experimental syntax 'jsx' isn't currently enabled when building react native app by react-scripts

### ISSUE THREAD

**Issue by Safnaj** [babel/babel#13920] opened 2021-11-02 16:09 UTC
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/eslint-parser

### Input code

package.json

```
{
  "name": "du-ui-toolkit-example",
  "description": "Example app for du-ui-toolkit",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "build:ios": "react-native bundle --entry-file='index.tsx' --bundle-output='./ios/main.jsbundle' --dev=false --platform='ios'",
    "start": "react-native start",
    "web:start": "react-scripts start",
    "web:build": "react-scripts build"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.15.8",
    "@react-native-community/hooks": "^2.6.0",
    "@react-navigation/native": "^6.0.4",
    "@react-navigation/native-stack": "^6.2.2",
    "eslint-plugin-eslint-comments": "^3.2.0",
    "react": "16.13.1",
    "react-dom": "^17.0.2",
    "react-native": "0.63.4",
    "react-native-color-matrix-image-filters": "^5.2.10",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-reanimated": "^2.2.2",
    "react-native-restart": "0.0.22",
    "react-native-safe-area-context": "^3.1.9",
    "react-native-screens": "^3.8.0",
    "react-native-svg": "^12.1.1",
    "react-native-text-gradient": "^0.1.7",
    "react-native-vector-icons": "^8.1.0",
    "react-native-web": "^0.17.5",
    "react-scripts": "^4.0.3"
  },
  "devDependencies": {
    "@babel/core": "^7.12.10",
    "@babel/plugin-transform-react-jsx": "^7.16.0",
    "@babel/preset-env": "^7.16.0",
    "@babel/preset-react": "^7.16.0",
    "@babel/runtime": "^7.12.5",
    "babel-plugin-module-resolver": "^4.0.0",
    "metro-react-native-babel-preset": "^0.64.0"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

### Configuration file name

babel.config.js

### Configuration

```js
const path = require('path');
const pak = require('../package.json');

module.exports = {
  "presets": ["@babel/preset-react", "@babel/preset-env"],
  "plugins": ["@babel/plugin-transform-react-jsx"]
};
```

### Current and expected behavior

```
../node_modules/react-native-elements/dist/avatar/Accessory.js
SyntaxError: /Users/safnaj/Documents/Arimac/du-ui-toolkit-test/node_modules/react-native-elements/dist/avatar/Accessory.js: Support for the experimental syntax 'jsx' isn't currently enabled (19:13):

  17 | const Accessory = (_a) => {
  18 |     var { size = 10, style, underlayColor = '#000', onPress, onLongPress, source } = _a, props = __rest(_a, ["size", "style", "underlayColor", "onPress", "onLongPress", "source"]);
> 19 |     return (<TouchableHighlight style={[
     |             ^
  20 |         styles.accessory,
  21 |         {
  22 |             width: size,

Add @babel/preset-react (https://git.io/JfeDR) to the 'presets' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-jsx (https://git.io/vb4yA) to the 'plugins' section to enable parsing.
```

### Environment

```
System:
    OS: macOS 11.5.1
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 7.16.0 - /usr/local/bin/npm
  npmPackages:
    eslint: ^7.2.0 => 7.32.0 
    jest: ^27.2.5 => 27.2.5 
    react-native: ^0.66.0 => 0.66.0 
```

**Comment by JLHwung** [comment] 2021-11-03 00:11
The error is thrown from the react-native-elements. As I can see your project uses `react-scripts` to build a react native app. The Create React App community [recommends](https://github.com/facebook/create-react-app#react-native) using `expo` to build a react-native app. Consider re-generate your project from expo.

**Comment by Safnaj** [comment] 2021-11-03 04:53
> The error is thrown from the react-native-elements. As I can see your project uses `react-scripts` to build a react native app. The Create React App community [recommends](https://github.com/facebook/create-react-app#react-native) using `expo` to build a react-native app. Consider re-generate your project from expo.

I am actually porting the react native elements to web using `react-native-web`. So using react-native script to run only in the web. Is there anything to do with the webpack ?

**Comment by nicolo-ribaudo** [comment] 2021-11-03 09:46
I'm confused by the error: are you linting your `node_modules`? Or are you getting the error when using something different from `@babel/eslint-parser`?

**Comment by Safnaj** [comment] 2021-11-03 12:08
This is my folder structure and i am not linting `node_modules`.
If i can exclude `node_modules` from the rules checking the syntax, it will be fixed i think.

<img width="291" alt="Screenshot 2021-11-03 at 5 24 19 PM" src="https://user-images.githubusercontent.com/37530024/140055466-54edbed0-bde6-4293-b96f-2d39566f4753.png">

**Comment by nicolo-ribaudo** [comment] 2021-11-03 12:55
Can you share a repository that reproduces the issue? It's strange because that error is coming when parsing a file in `node_modules`, but if you are not linting them I don't know why `@babel/eslint-parser` would try to parse them.

**Comment by Crameriver** [comment] 2021-12-26 11:21
Hello i've been experiencing the exact same issue trying to do the same thing (porting react-native elements to react-native-web), my set up is also extremely similar,  did you @Safnaj or somebody else found a fix for this ?

**Comment by Safnaj** [comment] 2021-12-26 12:42
> Hello i've been experiencing the exact same issue trying to do the same thing (porting react-native elements to react-native-web), my set up is also extremely similar, did you @Safnaj or somebody else found a fix for this ?

Not yet !!

**Comment by nicolo-ribaudo** [comment] 2021-12-26 16:14
A repository that I can use to reproduce the issue will help understanding what's going on!

**Comment by Safnaj** [comment] 2021-12-26 19:26
> A repository that I can use to reproduce the issue will help understanding what's going on!

in my case its our company project. I am unable to share due to the policies. If @Crameriver don't have any restrictions he can share.

**Comment by liuxingbaoyu** [comment] 2022-09-23 14:04
I'll close it due to long periods of inactivity, feel free to open it if the problem persists.

**Closed by liuxingbaoyu** 2022-09-23 14:04 UTC
Labels: area: third party
