### ISSUE TITLE
Class property transform fails with "We don't know what to do with this node type"

### ISSUE THREAD

**Issue by joeporpeglia** [babel/babel#7843] opened 2018-04-30 23:08 UTC
This is a bug report

### Input Code

The following code produces an error:
```js
export class Test {
  static staticProp = {};
  constructor(props) {
    console.log(props);
  }
  log = (props) => {
    console.log(props.msg);
  };
}
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [
    ["@babel/stage-1", { "decoratorsLegacy": true }]
  ]
}

```

### Expected Behavior

Babel should successfully compile the code. Works with babel 6 in the REPL: https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=usage&code_lz=KYDwDg9gTgLgBAYwDYEMDOa4BVhvgbwCg448UYBLBUmcqgBSgjDgF458BfAbmMQgB2eKAFcEMaAAowTMGgCUHPiQSC0EJMAB0SCAHNpshbxKc-uvWziHmCtgD4lJFWo3aLNuVoC2aPfJM4HkJOIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&lineWrap=false&presets=stage-1&prettier=false&targets=&version=6.26.0&envVersion=1.6.2

### Current Behavior

Babel fails to compile with the following error:
```
Error: We don't know what to do with this node type. We were previously a Statement but we can't fit in here?
    at NodePath.insertAfter (/path/to/project/node_modules/@babel/traverse/lib/path/modification.js:154:11)
    at PluginPass.Class (/path/to/project/node_modules/@babel/plugin-proposal-class-properties/lib/index.js:267:14)
    at newFn (/path/to/project/node_modules/@babel/traverse/lib/visitors.js:243:21)
    at NodePath._call (/path/to/project/node_modules/@babel/traverse/lib/path/context.js:65:18)
    at NodePath.call (/path/to/project/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/path/to/project/node_modules/@babel/traverse/lib/path/context.js:100:12)
    at TraversalContext.visitQueue (/path/to/project/node_modules/@babel/traverse/lib/context.js:144:16)
    at TraversalContext.visitSingle (/path/to/project/node_modules/@babel/traverse/lib/context.js:104:19)
    at TraversalContext.visit (/path/to/project/node_modules/@babel/traverse/lib/context.js:185:19)
    at Function.traverse.node (/path/to/project/node_modules/@babel/traverse/lib/index.js:106:17)
```

### Possible Solution

Not sure, but it's interesting that either of the following adjustments can be used to work around the issue:
```diff
// Use different identifiers for constructor arg and `log` arg
export class Test {
  static staticProp = {};
  constructor(props) {
    console.log(props);
  }
- log = (props) => {
+ log = (p) => {
-   console.log(props.msg);
+   console.log(p.msg);
  };
}
```

```diff
// Export the class separate from its declaration
-export class Test {
+class Test {
  static staticProp = {};
  constructor(props) {
    console.log(props);
  }
  log = (props) => {
    console.log(props.msg);
  };
}
+
+export { Test };
```

### Context

Trying to use what I _think_ is compliant with the current proposals, but have to follow one of the provided workarounds instead.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            | 7.0.0-beta.46 
| Babylon          | 
| node             | 8.6.0
| npm              | yarn 1.5.1
| Operating System | mac OS

**Comment by loganfsmyth** [comment] 2018-05-28 06:03
Duplicate of #7177

**Closed** 2018-05-28 06:34 UTC
Labels: 7.x: regression
