### ISSUE TITLE
[Bug]: [7.16.10] [target:node:12] Class fields are not enabled

### ISSUE THREAD

**Issue by jlowcs** [babel/babel#14188] opened 2022-01-20 15:26 UTC
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

With the following configuration:

```js
module.exports = (api) => {
	api.cache(false);

	return {
		sourceType: 'unambiguous',
		presets: [
			[
				'@babel/preset-env',
				{
					useBuiltIns: 'entry',
					corejs: 3,
					loose: false,
					targets: { node: '12' },
				},
			],
			'@babel/preset-typescript',
		],
	};
};
```

And a simple file like this one:

```ts
export class Test {
	private foo: unknown = {};
}
```

Compilation fails:

![image](https://user-images.githubusercontent.com/3777724/150366693-489e2783-da75-47d1-aae4-19dbffa99a5a.png)

### Configuration file name

babel.config.js

### Configuration

```js
module.exports = (api) => {
	api.cache(false);

	return {
		sourceType: 'unambiguous',
		presets: [
			[
				'@babel/preset-env',
				{
					useBuiltIns: 'entry',
					corejs: 3,
					loose: false,
					targets: { node: '12' },
				},
			],
			'@babel/preset-typescript',
		],
	};
};
```

### Current and expected behavior

The following file should compile, but I'm getting an error:

```ts
export class Test {
	private foo: unknown = {};
}
```

![image](https://user-images.githubusercontent.com/3777724/150366693-489e2783-da75-47d1-aae4-19dbffa99a5a.png)

### Environment

  System:
    OS: macOS 11.6.2
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  npmPackages:
    @babel/cli: ^7.16.8 => 7.16.8 
    @babel/core: ^7.16.10 => 7.16.10 
    @babel/node: ^7.16.8 => 7.16.8 
    @babel/parser: ^7.16.10 => 7.16.10 
    @babel/plugin-syntax-import-meta: ^7.10.4 => 7.10.4 
    @babel/plugin-transform-runtime: ^7.16.10 => 7.16.10 
    @babel/preset-env: ^7.16.10 => 7.16.10 
    @babel/preset-react: ^7.16.7 => 7.16.7 
    @babel/preset-typescript: ^7.16.7 => 7.16.7 
    @babel/register: ^7.16.9 => 7.16.9 
    @babel/runtime: ^7.16.7 => 7.16.7 
    @babel/traverse: ^7.16.10 => 7.16.10 
    babel-jest: ^27.4.6 => 27.4.6 
    babel-loader: ^8.2.3 => 8.2.3 
    babel-plugin-styled-components: ^2.0.2 => 2.0.2 
    eslint: ^8.7.0 => 8.7.0 
    jest: ^27.4.7 => 27.4.7 
    webpack: ^4.46.0 => 4.46.0 

### Additional context

Might be related to https://github.com/babel/babel/pull/14169?

Changing the target to node 14 or 16 fixes the issue, but that opens another can of worms for me...

**Comment by nicolo-ribaudo** [comment] 2022-01-20 15:28
Could you check if `@babel/preset-env` 7.16.11 fixes this bug?

**Comment by jlowcs** [comment] 2022-01-20 15:55
For reference, here's what the previous version of babel returns:

![image](https://user-images.githubusercontent.com/3777724/150374105-c02067a0-caa7-41ca-bc76-4565fdeb1fd4.png)

**Comment by JLHwung** [comment] 2022-01-20 16:04
> And that results in an error when using webpack 4 and babel-loader.

Webpack 4 does not support ES2022, you need to upgrade to webpack 5 or always enable `@babel/plugin-proposal-class-properties`.

**Comment by jlowcs** [comment] 2022-01-20 16:06
Oh, right, apparently node 12 [does support private class fields](https://thecodebarbarian.com/nodejs-12-private-class-fields.html).

I guess explicit `@babel/plugin-proposal-class-properties` is the way to go until we have the bandwidth to migrate to webpack 5.

**Comment by jlowcs** [comment] 2022-01-20 16:09
thank you both

**Comment by nicolo-ribaudo** [comment] 2022-01-20 16:14
I'm closing this issue since Babel now produces code that it still valid according to your targets, even if this might look like a regression (because it throws with webpack 4).

We might introduce a `webpack: X` target in the future, but for now yes I suggest enabling `@babel/plugin-proposal-class-properties` explicitly!

**Closed by nicolo-ribaudo** 2022-01-20 16:14 UTC
Labels: i: bug, i: regression

**Comment by jlowcs** [comment] 2022-01-20 16:55
> We might introduce a webpack: X target in the future

I love that idea!
