### ISSUE TITLE
.default is not a valid Plugin property

### ISSUE THREAD

**Issue by rodrigopavezi** [babel/babel#8563] opened 2018-08-28 07:29 UTC
## Bug Report

**Current Behavior**
When building my electron app with latest babel it will throw the following error:

ERROR in ./src/renderer/index.js
  Module build failed (from ./node_modules/babel-loader/lib/index.js):
  Error: [BABEL] /Users/rodrigopavezi/selfkey/github/Identity-Wallet/src/renderer/index.js: .default is not a valid Plugin property
      at Object.keys.forEach.key (/Users/rodrigopavezi/selfkey/github/Identity-Wallet/node_modules/@babel/core/lib/config/validation/plugins.js:52:56)
      at Array.forEach (<anonymous>)
      at validatePluginObject (/Users/rodrigopavezi/selfkey/github/Identity-Wallet/node_modules/@babel/core/lib/config/validation/plugins.js:50:20)
      at instantiatePlugin (/Users/rodrigopavezi/selfkey/github/Identity-Wallet/node_modules/@babel/core/lib/config/full.js:209:55)
      at cachedFunction (/Users/rodrigopavezi/selfkey/github/Identity-Wallet/node_modules/@babel/core/lib/config/caching.js:33:19)
      at loadPluginDescriptor (/Users/rodrigopavezi/selfkey/github/Identity-Wallet/node_modules/@babel/core/lib/config/full.js:200:10)
      at config.plugins.reduce (/Users/rodrigopavezi/selfkey/github/Identity-Wallet/node_modules/@babel/core/lib/config/full.js:69:20)
      at Array.reduce (<anonymous>)
      at recurseDescriptors (/Users/rodrigopavezi/selfkey/github/Identity-Wallet/node_modules/@babel/core/lib/config/full.js:67:38)
      at loadFullConfig (/Users/rodrigopavezi/selfkey/github/Identity-Wallet/node_modules/@babel/core/lib/config/full.js:108:6)
      at process.nextTick (/Users/rodrigopavezi/selfkey/github/Identity-Wallet/node_modules/@babel/core/lib/transform.js:28:33)
      at _combinedTickCallback (internal/process/next_tick.js:131:7)
      at process._tickCallback (internal/process/next_tick.js:180:9)
   @ multi (webpack)-dev-server/client?http://localhost:9080 (webpack)/hot/dev-server.js css-hot-loader/hotModuleReplacement ./src/renderer/index.js renderer[3]

**Input Code**
Repo: https://github.com/SelfKeyFoundation/Identity-Wallet  

**Expected behavior/code**
It should build the app and run it normally as it working on version 7.0.0-beta.47

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
	"presets": [
		[
			"@babel/preset-env",
			{
				"targets": {
					"node": "current"
				}
			}
		],
		"@babel/preset-react"
	],
	"plugins": [
		"@babel/plugin-proposal-class-properties"
	]
}
```

**Environment**
- Babel version(s): [v7.0.0]
- Node/npm version: [Node 8/yarn 1.9.4]
- OS: [OSX]
- How you are using Babel: [`loader`]

Cheers

**Comment by loganfsmyth** [comment] 2018-08-28 08:00
Would you be able to provide a branch that reproduces the issue?

**Comment by rodrigopavezi** [comment] 2018-08-28 08:37
@loganfsmyth sure, if you checkout `dev` branch and delete yarn.lock. Then run the following:

- yarn install-all
- yarn dev

That should show the issue. So the only thing changed is the babel version I reckon, which breaks the build.

Cheers

**Comment by loganfsmyth** [comment] 2018-08-28 18:47
Alright, looks like this is something `electron-webpack` would have to fix in. On https://github.com/electron-userland/electron-webpack/blob/504b8f64eca28437ec78b334f9f9f2e245a6b0e1/packages/electron-webpack/src/configurators/js.ts#L14 it should have a `.default` after the `require()`

**Comment by rodrigopavezi** [comment] 2018-08-28 21:09
@loganfsmyth Thanks for taking a look at it. I just created an issue on electron-webpack. Cheers

**Comment by JLHwung** [comment] 2020-06-30 20:52
Closing as the downstream issue has been fixed.

**Closed by JLHwung** 2020-06-30 20:52 UTC
Labels: area: downstream
