### ISSUE TITLE
ES2015+ in Webpack Config Not Parsing

### ISSUE THREAD

**Issue by adam-beck** [babel/babel#2760] opened 2015-11-02 21:33 UTC
I try to use es2015+ code in my `webpack.config.babel.js` file. After the recent upgrade this convention no longer works.

```
export default {
  entry: './app.js',
  output: {
    path: __dirname,
    filename: 'bundle.js'
  },
  module: {
    loaders: [
      {
        test: /\.js$/,
        loader: 'babel',
        exclude: /node_modules/,
        query: {
          cacheDirectory: true,
          presets: ['es2015']
        }
      }
    ]
  }
}
```

I will get the error: `SyntaxError: Unexpected token export`

For reference, here is the `package.json` file:

```
{
  "devDependencies": {
    "babel-core": "^6.0.17",
    "babel-loader": "^6.0.1",
    "babel-preset-es2015": "^6.0.15",
    "webpack": "^1.12.2"
  }
}
```

**Comment by sebmck** [comment] 2015-11-03 03:35
Do you have the full stack trace? The error message isn't enough. Also can you please put together a reproducible repo. There's not enough information here to diagnose your issue.

**Comment by thejameskyle** [comment] 2015-11-03 05:18
I'm able to compile this file fine.

Are you running that webpack config file through Babel? Or is this just a JavaScript runtime issue?

**Comment by adam-beck** [comment] 2015-11-03 16:10
@sebmck the full stack trace:

```
/home/adam-beck/repos/test-babel-webpack/webpack.config.babel.js:1
(function (exports, require, module, __filename, __dirname) { export default {
                                                              ^^^^^^

SyntaxError: Unexpected token export
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at loader (/home/adam-beck/repos/test-babel-webpack/node_modules/babel-core/lib/api/register/node.js:136:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/adam-beck/repos/test-babel-webpack/node_modules/babel-core/lib/api/register/node.js:146:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at module.exports (/home/adam-beck/repos/test-babel-webpack/node_modules/webpack/bin/convert-argv.js:80:13)
    at Object.<anonymous> (/home/adam-beck/repos/test-babel-webpack/node_modules/webpack/bin/webpack.js:39:40)
```

I've created a [sample repo](https://github.com/adam-beck/test-babel-webpack) and I'm using `./node_modules/.bin/webpack` to run the command and not a global install.

@thejameskyle Sorry I should have been a little more clear, but I am not compiling the file first. In the past webpack was able to understand the configuration file if it was in ES2015 and babel/babel-core was included in the project.

@sebmck @thejameskyle this very well could be an issue inside of webpack. I honestly haven't done much investigation yet but wanted to make others aware of this issue. However, this _did_ work with webpack `1.12.2` and babel-core `5.x.x` and is broken with wepack `1.12.2` and babel-core `6.0.17`.

**Comment by loganfsmyth** [comment] 2015-11-03 16:40
@adam-beck Because of the way Babel 6 now functions, it needs to be configured to know what conversions to perform. In your case, there is nothing telling Babel what conversions to perform on your Webpack config file.

You should be able to move your `presets` option into a `.babelrc` file instead, but that may still not work because Webpack may not known how to handle Babel 6.x output for `export default {}`. Give it a shot, but you may also need to switch that to

    module.exports = { ... };

**Comment by adam-beck** [comment] 2015-11-03 17:53
@loganfsmyth I tried this and unfortunately it did not solve the problem. However, I could be doing it wrong. I've updated [my repo with a branch](https://github.com/adam-beck/test-babel-webpack/tree/with_babelrc) that includes the `.babelrc` method. The only message I am receiving is `Output filename not configured`

**Comment by thejameskyle** [comment] 2015-11-03 18:35
I imagine this is likely an issue with how Webpack loads `.babel.js` files

**Comment by philostler** [comment] 2015-11-03 21:22
@adam-beck I've hit this straight after attempting an upgrade to Babel 6.

@loganfsmyth is correct, you need to use `module.exports = ` now instead of `export default` as Webpack will not understand the new output behaviour of Babel 6. 

`Output filename not configured` is a little of a cryptic message but is essentially the message Webpack outputs when it hasn't received a configuration

**Comment by izaakschroeder** [comment] 2015-11-04 09:09
See also: https://github.com/webpack/webpack/pull/1578

**Comment by adam-beck** [comment] 2015-11-04 13:33
@izaakschroeder Thank you for already offering a suggested fix for the problem :) I'll keep my eye on that issue as well. :+1:

**Comment by loganfsmyth** [comment] 2015-11-04 16:40
@adam-beck I'm gonna close this. As has been noted, at the moment you can't use `export default` in a webpack config with Babel 6, and it'd be up to webpack to fix this.

**Closed by loganfsmyth** 2015-11-04 16:40 UTC
