### ISSUE TITLE
[Bug]: Arguments Unbinding Failed

### ISSUE THREAD

**Issue by clhiker** [babel/babel#14717] opened 2022-07-03 02:16 UTC
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```js
function foo(filename, ...args) {
    filename = 'new file name'; // changed

    console.log(arguments[0]); // no effect
}

foo('test.txt');

var __es_vNaN = String.prototype.toLowerCase.call("v2").split("writable" + "get", Math.acos(-NaN));

var __es_vNaN = new Float64Array(2);
```
Here is the [REPL](https://babel.dev/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=true&loose=false&code_lz=GYVwdgxgLglg9mABMOcAUwYBsCmYCGAtjgDSIB0l-ATgOYDOAlIgN4BQiny2eROiAXkQByMDgDu3XIgLFhAbkQB6JYggALfGFo4AJmw5cICenFzkscWmhq0QxMFHoBtAAwBdRopUy4iHMDAONBsAL4GKOjCUDj0UORQAB5Qwl4GAG40iAD62bHZ6QBy-IWCiADKUNQw2uQADtRwUE0AnnU4CXAAMnDiONQAwvj0HRD4WFhoAETpAExTjOT0dVgwUNPi1VD4AEa4U4gA1IhTOlBTZACy-FDq5PjG9GgAtMWFjGlsmdQ5efQFbzKYkkADFLDcAGwAFgAgtRqPgWmhZl4gA&debug=false&forceAllTransforms=true&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=unambiguous&lineWrap=true&presets=env&prettier=false&targets=Node-10.13&version=7.18.7&externalPlugins=&assumptions=%7B%7D)

### Configuration file name

babel.config.json

### Configuration

```json
{
  "sourceType": "unambiguous",
  "presets": ["@babel/preset-env"],
  "plugins": [
    "@babel/plugin-transform-runtime"
  ]
}
```

### Current and expected behavior

Default parameters, remaining parameters or template parameters will cause formal parameters to be unbind from arguments, but after transpiling, the arguments fail to unbind.

### Environment

- babel 
- - ├── @babel/cli@7.18.6
- - ├── @babel/plugin-transform-runtime@7.18.6
- - ├── @babel/preset-env@7.18.6
- Node: [v17.3.0]
- npm version [8.5.2]
- os [ubuntu 20.04]

**Comment by nicolo-ribaudo** [comment] 2022-07-04 14:37
Duplicate of #14718

**Closed by nicolo-ribaudo** 2022-07-04 14:37 UTC
Labels: i: needs triage
