### ISSUE TITLE
transform-async-to-generator not working in preset-2017 for arrow functions

### ISSUE THREAD

**Issue by Morglod** [babel/babel#6729] opened 2017-11-02 16:13 UTC
async arrow functions looses `this` context

eg in this case:
```js
class Test {
  constructor() {
    someService.get().then(async () => {
      this.foo = 'tada';
    })
  }
}
```

**Comment by nicolo-ribaudo** [comment] 2017-11-02 16:44
Which babel version are you using?

**Comment by hzoo** [comment] 2017-11-02 17:43
If you remove the issue template we have no idea what the issue is, you didn't specify your config or version. However it looks like this is fixed in master (v7 beta) so going to close

**Closed by hzoo** 2017-11-02 17:43 UTC
