### ISSUE TITLE
Babel works locally but fails on GitLab CI

### ISSUE THREAD

**Issue by gandatandya** [babel/babel#11636] opened 2020-05-28 04:49 UTC
Hello, I am using Serverless Framework and GitLab CI to deploy my react-app

I am able to build deploy from my machine, but when setting it up on GitLab CI, I got the following error:
'loose' mode configuration must be the same for both @babel/plugin-proposal-class-properties and @babel/plugin-proposal-private-methods

This error does not appear on my local machine, so I am not sure what's going on.
I also don't have plugin-proposal-private-methods anywhere in package.json, so I am not sure which babel package depends on it.

Here is my package.json

`"devDependencies": {
    "@babel/core": "^7.6.4",
    "@babel/plugin-proposal-class-properties": "^7.5.5",
    "@babel/plugin-transform-react-jsx": "^7.3.0",
    "@babel/plugin-transform-runtime": "^7.6.2",
    "@babel/runtime": "^7.6.3",
    "babel-preset-nano-react-app": "^0.1.0",
    "cssnano": "^4.1.10",
    "parcel-bundler": "^1.11.0",
    "parcel-plugin-clean-dist": "0.0.6"
  },
  "babel": {
    "presets": [
      "nano-react-app"
    ],
    "plugins": [
      [
        "@babel/plugin-proposal-class-properties",
        {
          "loose": true
        }
      ],
      [
        "@babel/plugin-transform-react-jsx",
        {
          "pragmaFrag": "React.Fragment"
        }
      ]
    ]
  }
}`

Thanks for the help in advance!
Ganda

**Comment by JLHwung** [comment] 2020-05-28 15:23
Duplicate of #11622

**Closed by JLHwung** 2020-05-28 15:23 UTC
Labels: i: bug, i: needs triage
