### ISSUE TITLE
ES6 export default not working with SystemJS

### ISSUE THREAD

**Issue by davegomez** [babel/babel#3072] opened 2015-11-15 22:02 UTC
I have been trying to use a full ES6 webpack configuration file using Babel 6 but it seems that `export default` if in fact not exporting anything.

I named my config file webpack.config.babel.js and this is the code:

```
import path from 'path';
import HtmlwebpackPlugin from 'html-webpack-plugin';

const ROOT_PATH = path.resolve(__dirname);
const APP_PATH = path.resolve(ROOT_PATH, 'app');
const BUILD_PATH = path.resolve(ROOT_PATH, 'build');

export default {
  entry: APP_PATH,

  output: {
    path: BUILD_PATH,
    filename: 'bundle.js'
  },

  plugins: [
    new HtmlwebpackPlugin({
      title: 'React Kanban App'
    })
  ]
};
```

Every time I run webpack I just get the webpack options list and a message saying `Output filename not configured.`, but If I change the expression to `module.exports = { ... }` everything works fine.

My `.babelrc` file is like this:

```
{
  "presets": [
    "es2015",
    "react"
  ]
}
```

And my dependencies are:

```
"devDependencies": {
    "babel-core": "^6.1.21",
    "babel-preset-es2015": "^6.1.18",
    "babel-preset-react": "^6.1.18",
    "webpack": "^1.12.6"
  }
```

I can't figure out what is going on here, is this a bug?

**Comment by loganfsmyth** [comment] 2015-11-15 22:05
Duplicate of https://github.com/babel/babel/issues/2760.

Looks like the webpack fix just landed: https://github.com/webpack/webpack/pull/1578 so the next version of webpack should support it. Until then, you'll need to use `module.exports = `.

**Closed by loganfsmyth** 2015-11-15 22:05 UTC
