### ISSUE TITLE
Trailing commas in object literals create incorrect whitespace

### ISSUE THREAD

**Issue by thejameskyle** [babel/babel#1569] opened 2015-05-18 21:11 UTC
```js
let obj = {
  foo: 'foo',
  bar: 'bar'
};
// outputs:
let obj = {
  foo: 'foo',
  bar: 'bar'
};
```
but:
```js
let obj = {
  foo: 'foo',
  bar: 'bar',
};
// outputs:
let obj = {
  foo: 'foo',
  bar: 'bar' };
```

This is a super critical high-priority bug, I'm super angry at you @sebmck. Why are you destroying my life? I hate you with every cell in my body and hope that you get hit by a bus. :trollface:

**Comment by sebmck** [comment] 2015-05-18 21:12
Duplicate of #1304.

**Closed by sebmck** 2015-05-18 21:12 UTC
Labels: super high critical blocker omg wtf
