### ISSUE TITLE
[Bug]: Cannot read properties of undefined (reading 'addHelper') 

### ISSUE THREAD

**Issue by SidneyLann** [babel/babel#15994] opened 2023-09-23 11:30 UTC
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

https://github.com/SidneyLann/taro-test-repo.git

### Configuration file name

babel.config.js

### Configuration

const { mergeConfig } = require('metro-config')
const { getMetroConfig } = require('@tarojs/rn-supporter')

module.exports = (async function (){
  return mergeConfig({ 
  // custom your metro config here
  // https://facebook.github.io/metro/docs/configuration
    resolver: {}
  }, await getMetroConfig())
})()

### Current and expected behavior

compile successfully. no "Cannot read properties of undefined (reading 'addHelper') "

### Environment

 System:
    OS: Windows 10 10.0.22621
  Binaries:
    Node: 20.3.1 - D:\DEV\nodejs\node.EXE
    Yarn: 1.22.19 - D:\DEV\nodejs\yarn.CMD
    npm: 9.6.7 - D:\DEV\nodejs\npm.CMD
  npmPackages:
    @babel/core: ^7.22.20 => 7.22.20
    @babel/runtime: ^7.22.15 => 7.22.15
    babel-preset-taro: 3.6.16 => 3.6.16
    eslint: ^8.12.0 => 8.46.0
    react-native: ^0.70.1 => 0.70.13
    webpack: ^5.88.2 => 5.88.2

### Additional context

reproduce steps:
1. cd to project folder
2. yarn
3. yarn build:rn --platform android 
4. compile error occor:
D:\DEV\git\repo_test\taro-test>yarn build:rn --platform android
yarn run v1.22.19
$ taro build --type rn --platform android
👽 Taro v3.6.16

                Welcome to Metro v0.72.4
              Fast - Scalable - Integrated

error node_modules\@tarojs\rn-supporter\entry-file.js: D:\DEV\git\repo_test\taro-test\node_modules\@tarojs\rn-supporter\entry-file.js: Cannot read properties of undefined (reading 'addHelper').
TypeError: D:\DEV\git\repo_test\taro-test\node_modules\@tarojs\rn-supporter\entry-file.js: Cannot read properties of undefined (reading 'addHelper')
    at wrapInterop (D:\DEV\git\repo_test\taro-test\node_modules\@babel\helper-module-transforms\src\index.ts:208:3)
    at PluginPass.call (D:\DEV\git\repo_test\taro-test\node_modules\@babel\plugin-transform-modules-commonjs\src\index.ts:255:28)
    at call (D:\DEV\git\repo_test\taro-test\node_modules\@babel\core\node_modules\@babel\traverse\src\visitors.ts:292:14)
    at NodePath._call (D:\DEV\git\repo_test\taro-test\node_modules\@babel\core\node_modules\@babel\traverse\src\path\context.ts:35:20)
    at NodePath.call (D:\DEV\git\repo_test\taro-test\node_modules\@babel\core\node_modules\@babel\traverse\src\path\context.ts:20:17)
    at NodePath.visit (D:\DEV\git\repo_test\taro-test\node_modules\@babel\core\node_modules\@babel\traverse\src\path\context.ts:112:8)
    at TraversalContext.visitQueue (D:\DEV\git\repo_test\taro-test\node_modules\@babel\core\node_modules\@babel\traverse\src\context.ts:144:16)
    at TraversalContext.visitSingle (D:\DEV\git\repo_test\taro-test\node_modules\@babel\core\node_modules\@babel\traverse\src\context.ts:108:19)
    at TraversalContext.visit (D:\DEV\git\repo_test\taro-test\node_modules\@babel\core\node_modules\@babel\traverse\src\context.ts:176:19)
    at traverseNode (D:\DEV\git\repo_test\taro-test\node_modules\@babel\core\node_modules\@babel\traverse\src\traverse-node.ts:40:17)
    at traverse (D:\DEV\git\repo_test\taro-test\node_modules\@babel\core\node_modules\@babel\traverse\src\index.ts:82:15)
    at transformFile (D:\DEV\git\repo_test\taro-test\node_modules\@babel\core\src\transformation\index.ts:124:15)
    at transformFile.next (<anonymous>)
    at run (D:\DEV\git\repo_test\taro-test\node_modules\@babel\core\src\transformation\index.ts:48:12)
    at run.next (<anonymous>)
    at D:\DEV\git\repo_test\taro-test\node_modules\@babel\core\src\transform-ast.ts:34:20
    at Generator.next (<anonymous>)
    at evaluateSync (D:\DEV\git\repo_test\taro-test\node_modules\gensync\index.js:251:28)
    at fn (D:\DEV\git\repo_test\taro-test\node_modules\gensync\index.js:89:14)
    at stopHiding - secret - don't use this - v1 (D:\DEV\git\repo_test\taro-test\node_modules\@babel\core\src\errors\rewrite-stack-trace.ts:99:14)
    at transformFromAstSync (D:\DEV\git\repo_test\taro-test\node_modules\@babel\core\src\transform-ast.ts:77:59)
    at Object.transform [as nextTransformer] (D:\DEV\git\repo_test\taro-test\node_modules\metro-react-native-babel-transformer\src\index.js:199:20)
    at Object.transform (D:\DEV\git\repo_test\taro-test\node_modules\@tarojs\rn-transformer\src\index.ts:44:18)
    at D:\DEV\git\repo_test\taro-test\node_modules\@tarojs\rn-supporter\src\taroTransformer.ts:59:51
    at Generator.next (<anonymous>)
info Run CLI with --verbose flag for more details.
Done in 128.15s.

D:\DEV\git\repo_test\taro-test>

**Comment by liuxingbaoyu** [comment] 2023-11-10 22:05
Duplicate of https://github.com/babel/babel/issues/15752

**Closed by liuxingbaoyu** 2023-11-10 22:05 UTC
Labels: i: needs triage
