### ISSUE TITLE
Property right of AssignmentExpression expected node to be of a type ["Expression"] but instead got null

### ISSUE THREAD

**Issue by moafim** [babel/babel#8284] opened 2018-07-07 06:05 UTC
## Bug Report

**Current Behavior**
React-Native App on Both iOS and Android got the Error:
bundling failed: TypeError: Property right of AssignmentExpression expected node to be of a type ["Expression"] but instead got null

**Input Code**
```js
{
  "name": "customer",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "rnpm": {
    "assets": [
      "app/resources/style/font/vazir/latin/src",
      "app/resources/style/font/vazir/farsi/src",
      "app/resources/style/font/iransans/latin/src",
      "app/resources/style/font/iransans/farsi/src"
    ]
  },
  "dependencies": {
    "jsc-android": "^224109.0.0",
    "mobx": "^5.0.3",
    "mobx-react": "^5.2.3",
    "numeral": "^2.0.6",
    "react": "16.4.1",
    "react-native": "0.56.0",
    "react-native-collapsible": "^0.12.0",
    "react-native-swiper": "^1.5.13",
    "react-navigation": "^2.6.2"
  },
  "devDependencies": {
    "babel-jest": "^23.2.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.5",
    "babel-preset-react-native": "^5.0.2",
    "jest": "23.3.0",
    "react-test-renderer": "16.4.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

```js
error: bundling failed: TypeError: Property right of AssignmentExpression expected node to be of a type ["Expression"] but instead got null
    at Object.validate (/Users/milad/Documents/ide/react-native/beauty/customer/node_modules/@babel/types/lib/definitions/utils.js:130:13)
    at validate (/Users/milad/Documents/ide/react-native/beauty/customer/node_modules/@babel/types/lib/validators/validate.js:17:9)
    at builder (/Users/milad/Documents/ide/react-native/beauty/customer/node_modules/@babel/types/lib/builders/builder.js:46:27)
    at Object.AssignmentExpression (/Users/milad/Documents/ide/react-native/beauty/customer/node_modules/@babel/types/lib/builders/generated/index.js:229:31)
    at /Users/milad/Documents/ide/react-native/beauty/customer/node_modules/babel-plugin-transform-decorators-legacy/lib/index.js:75:22
    at Array.map (<anonymous>)
    at applyEnsureOrdering (/Users/milad/Documents/ide/react-native/beauty/customer/node_modules/babel-plugin-transform-decorators-legacy/lib/index.js:72:53)
    at PluginPass.ClassExpression (/Users/milad/Documents/ide/react-native/beauty/customer/node_modules/babel-plugin-transform-decorators-legacy/lib/index.js:210:38)
    at newFn (/Users/milad/Documents/ide/react-native/beauty/customer/node_modules/@babel/traverse/lib/visitors.js:237:21)
```

**Expected behavior/code**
Run App As Before

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": ["react-native"],
  "plugins": ["transform-decorators-legacy"]
}
```

**Environment**
- Babel version(s): v7.0
- Node/npm version: Node 10.1.0 / npm 6.1.0
- OS: OSX 10.13.5
- Monorepo yes
- How you are using Babel: loader

**Possible Solution**
I don't have any suggestions

**Additional context/Screenshots**
No Screenshots

**Comment by loganfsmyth** [comment] 2018-07-07 06:23
Would you be able to provide a sample file that reproduces the issue?

**Comment by moafim** [comment] 2018-07-07 06:31
@loganfsmyth Unfortunately I can't

**Comment by loganfsmyth** [comment] 2018-07-07 06:35
You don't necessarily need to provide your actual production code, but you could trim it down to figure out exactly what decorator is causing the issue, then you could make an example without your original code.

**Comment by moafim** [comment] 2018-07-07 06:39
@loganfsmyth I think it's about ` "babel-plugin-transform-decorators-legacy": "^1.3.5"`
```js
@inject('stores')
@observer
class ServiceScreen extends Component {
  @observable gender = this.props.stores.gender;

  constructor(props) {
    super(props);
  }

```

**Comment by loganfsmyth** [comment] 2018-07-07 06:39
Hmm actually, I didn't see that you'd edited the original issue to be specific to Babel 7.x. On Babel 7's beta, `babel-plugin-transform-decorators-legacy` is not the right thing to use, as noted here: https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy#babel--7x My guess would be that if you use the `@babel` plugin, it'll work.

**Comment by moafim** [comment] 2018-07-07 06:48
@loganfsmyth I've install ` "@babel/plugin-proposal-decorators": "^7.0.0-beta.52"` then change `.babelrc`'s `"plugin"` attribute to `"plugins": [["@babel/plugin-proposal-decorators", { "legacy": true }]]` but the Error stills yet.

**Comment by thientnc-ibl** [comment] 2018-07-09 08:02
@loganfsmyth 
you MUST use exactly version `"@babel/plugin-proposal-decorators": "7.0.0-beta.47"`. The `7.0.0-beta.47` is same as the version of `@babel/core` that is used by react-native 0.56. Besides, you MUST install `"babel-preset-react-native": "5.0.1"` as react-native 0.56 upgrade instruction
<img width="758" alt="screen shot 2018-07-09 at 3 01 26 pm" src="https://user-images.githubusercontent.com/32632979/42438021-065d5eb0-8389-11e8-82d1-048ef1ed0a8e.png">

**Comment by jjd314** [comment] 2018-07-18 10:57
@moafim I don't know if this will apply in your case, but I was getting the same error, with all the dependencies in my package.json at the latest versions (7.0.0-beta.54 for the babel stuff, 5.0.2 for babel-preset-react-native, etc.).  When I ran `babel --version`, though, it said `7.0.0-beta.54 (@babel/core 7.0.0-beta.47)`.  I added an explicit dependency on @babel/core, and things started working.

**Comment by existentialism** [comment] 2018-07-18 14:08
@jjd314 re: babylon, it was renamed to @babel/parser in beta.48

**Comment by swcisel** [comment] 2018-07-22 03:18
@jjd314 Thank you for helping me (finally) successfully update to 0.56!

**Comment by moafim** [comment] 2018-07-28 15:00
@jjd314 Would you be able to `.babelrc` and `package.json` files?

**Comment by jjd314** [comment] 2018-07-29 14:01
@moafim Here they are.  I'm not sure what state they are in currently, because I tried some more stuff after my last post.  I hope they help.

package.json
```
{
  "name": "BrokenBabel",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "@babel/core": "^7.0.0-beta.54",
    "@babel/plugin-proposal-decorators": "^7.0.0-beta.54",
    "@babel/plugin-transform-classes": "^7.0.0-beta.54",
    "@babel/register": "^7.0.0-beta.54",
    "react": "16.4.1",
    "react-native": "0.56.0"
  },
  "devDependencies": {
    "babel-jest": "23.4.0",
    "babel-preset-react-native": "^5",
    "jest": "23.4.1",
    "react-test-renderer": "16.4.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

.babelrc
```
{
    "presets": ["react-native"],
    "plugins": [
        ["@babel/plugin-proposal-decorators", { "legacy": true }]
    ]
}
```

**Comment by existentialism** [comment] 2018-07-30 03:30
@jjd314 you must make sure your `@babel/*` deps match the versions being used by the react-native preset _exactly_ (pin the version by removing the caret).

In the case of `babel-preset-react-native@5.0.2`, you must use beta.47...

**Comment by jjd314** [comment] 2018-07-30 11:14
@existentialism Thanks, but the problem is that the decorators don't work in 47.  Forcing it to 54 gets the decorators working, but I hit other problems.  It looks like plugin-transform-classes is generating the _inherits calls for subclasses before doing pushBody(), which generates _createClass, which overrides the prototype.  The effect is that any properties and methods defined in the subclass are lost.  The immediate symptom is that I get a red box complaining that my component does not define render.  I'm just waiting now for react-native to catch up to the latest babel, and hoping that everything gets resolved.

**Comment by existentialism** [comment] 2018-07-30 12:51
@jjd314 cool, just wanted to clarify since a lot of RN users are having issues with the beta version mismatch stuff!

**Comment by thientnc-ibl** [comment] 2018-07-31 03:58
@jjd314 . If you are using RN 0.56 with decorator plugin, you should go to this work aground, #20150. I hope it can help.

**Comment by PrsRares** [comment] 2018-07-31 06:54
No changes? Did someone actually resolve this?

**Comment by thientnc-ibl** [comment] 2018-07-31 08:27
@PrsRares , Did you try my suggestion? it is posted at [https://github.com/facebook/react-native/issues/20150](https://github.com/facebook/react-native/issues/20150)

**Comment by PrsRares** [comment] 2018-07-31 08:36
@thientnc-ibl  Ijust found out that they cant resolve this issue, so they will release 0.57 a little earlier and will be fixed, its a problem on windows only from what i was reading. Look here https://github.com/facebook/react-native/issues/19953

**Comment by alexxsanchezm** [comment] 2018-08-01 21:35
@PrsRares I think you are totally wrong, this is not only a windows problem, it happens on macOs too.

**Comment by thathexa** [comment] 2018-08-30 06:02
I installed RN today so I have version 0.56. Wanting to create a new app that uses MobX, tried doing exactly what @liranh85 did, but I still get the following error:
```
TypeError: Property right of AssignmentExpression expected node to be of a type ["Expression"] but instead got null
```
So... This is really frustrating. Already spent a day on it. As far as I understand, the problem is that this version of `@babel/plugin-proposal-decorators` simply doesn't work, and any later version is not supported by this version of RN. Does that mean we just have to wait for the next RN release?

**Comment by schumannd** [comment] 2018-08-31 21:17
@thathexa in the exact same boat atm. If you find any solution please tell me.

**Comment by schumannd** [comment] 2018-09-01 07:56
I found the solution in another issue: https://github.com/babel/babel/issues/7831

before:

```
{
  "presets": ["react-native"],
  "plugins": [
    "transform-decorators-legacy"
  ]
}

```

after:

```
{
  "presets": ["react-native"],
  "plugins": [
    ["@babel/plugin-proposal-decorators", {
      "legacy": true
    }],
  ]
}

```

**Comment by thathexa** [comment] 2018-09-01 16:47
I can confirm that this you can use MobX with decorators in RN 0.56 with `@babel/plugin-proposal-decorators` with `legacy: true` AS LONG AS the `@babel/plugin-proposal-decorators` version is the EXACT SAME as the rest of the `@babel/*` packages (version `7.0.0-beta.47` for RN 0.56.0). Just note that in order to use MobX version 5 you must force update `jsc-android` as explained [here](https://github.com/react-community/jsc-android-buildscripts#how-to-use-it-with-my-react-native-app).

Also it seems that even if you get MobX 5 to work, you can't use the `@computed` decorator for some reason (if you have further insight on this problem please comment on my issue mobxjs/mobx#1708)

**Comment by Janealter** [comment] 2018-09-18 11:36
package.json
```
"@babel/core": "7.0.0-beta.47",
"@babel/helpers": "7.0.0-beta.47",
"@babel/parser": "7.0.0-beta.48",
"@babel/plugin-proposal-decorators": "7.0.0-beta.47",
"@babel/preset-env": "7.0.0-beta.47",
"@babel/preset-flow": "7.0.0-beta.47",
"@babel/preset-react": "7.0.0-beta.47",
"babel-preset-react-native": "5.0.2"
```

.babelrc
```
{
  "presets": ["react-native"],
  "plugins": [["@babel/plugin-proposal-decorators", { "legacy": true }]]
}
```

I getting error `bundling failed: TypeError: Cannot read property 'addHelper' of undefined
` What other dependencies are needed for babel 7 with React Native?

**Comment by jdnichollsc** [comment] 2019-03-26 23:26
any update of this issue guys?

**Comment by nicolo-ribaudo** [comment] 2019-03-26 23:29
Doesn't https://github.com/babel/babel/issues/8284#issuecomment-425826321 work for you?

**Comment by jdnichollsc** [comment] 2019-03-28 07:43
Nothing, we have RN 0.56, so we need to update before to try that solution :/

**Comment by darkowic** [comment] 2019-05-07 05:49
If you still encounter the problem - **make sure that all your dependencies using babel are upgraded and do not use babel beta < 47**. In my case, there was a problem with `@svgr/webpack===2.0.0` which was using babel version `beta.37`. Upgrade solved the issue.

Thank you @jjd314!

**Comment by nicolo-ribaudo** [comment] 2019-05-07 14:59
Thank you to everyone who suggested how to solve this problem. I'm closing this now since it is working with the last versions of the various packages.

**Closed by nicolo-ribaudo** 2019-05-07 14:59 UTC
