### ISSUE TITLE
IE11 /10 Polyfill not working.

### ISSUE THREAD

**Issue by OverseePublic** [babel/babel#6554] opened 2017-10-25 19:14 UTC
My entry point app.js has 

> import 'babel-polyfill'

However when I open IE and type in the following code in console, it fails.

var a = () => '';

It does not recognize arrow function. Why isn't polyfill working?

Once polyfill works correctly, I should be able to type arrow function, etc in console right?

For any other modules linked via node_modules, should they also gain ES6 feature?

**Comment by keithamus** [comment] 2017-10-25 20:43
Hi @OverseePublic thanks for the issue.

Polyfill only adds functionality of features that an be implemented in ES5 code, for example `Array.prototype.fill`. Arrow functions require a whole new syntax which cannot be polyfilled, they have to be transpiled. [Here is an article about what a polyfill is defined as](https://remysharp.com/2010/10/08/what-is-a-polyfill), [while wikipedia has an article about what a transpiler is](https://en.wikipedia.org/wiki/Source-to-source_compiler). 

So by calling `import 'babel-polyfill'` you will not be able to use arrow functions, you will need to _transpile_ that code before it is run in the browser.

We should close this issue - because it is not a bug within Babel, it is not something we can fix. (@babel/babel this issue can be closed).

**Closed** 2017-10-25 20:46 UTC
