### ISSUE TITLE
After upgrading to the latest version of babel, I get an error:  t(...).isPlaceholder is not a function

### ISSUE THREAD

**Issue by julienw** [babel/babel#10588] opened 2019-10-22 12:51 UTC
## Bug Report

**Current Behavior**
After upgrading to latest babel packages, I get this error:
```
{ TypeError: /home/julien/travail/git/perf.html/src/index.js: t(...).isPlaceholder is not a function
    at placeholderVisitorHandler (/home/julien/travail/git/perf.html/node_modules/@babel/core/node_modules/@babel/template/lib/parse.js:81:11)
    at traverseSimpleImpl (/home/julien/travail/git/perf.html/node_modules/@babel/core/node_modules/@babel/template/node_modules/@babel/types/lib/traverse/traverse.js:27:14)
    at Object.traverse (/home/julien/travail/git/perf.html/node_modules/@babel/core/node_modules/@babel/template/node_modules/@babel/types/lib/traverse/traverse.js:21:3)
    at parseAndBuildMetadata (/home/julien/travail/git/perf.html/node_modules/@babel/core/node_modules/@babel/template/lib/parse.js:65:7)
    at buildLiteralData (/home/julien/travail/git/perf.html/node_modules/@babel/core/node_modules/@babel/template/lib/literal.js:53:35)
    at literalTemplate (/home/julien/travail/git/perf.html/node_modules/@babel/core/node_modules/@babel/template/lib/literal.js:20:7)
    at Function.ast (/home/julien/travail/git/perf.html/node_modules/@babel/core/node_modules/@babel/template/lib/builder.js:52:42)
    at Object.ast (/home/julien/travail/git/perf.html/node_modules/@babel/core/node_modules/@babel/helpers/lib/helpers.js:26:42)
    at fn (/home/julien/travail/git/perf.html/node_modules/@babel/core/node_modules/@babel/helpers/lib/index.js:248:30)
    at loadHelper (/home/julien/travail/git/perf.html/node_modules/@babel/core/node_modules/@babel/helpers/lib/index.js:251:40) code: 'BABEL_TRANSFORM_ERROR' }
```

**Input Code**
```js
import something from 'something';
```
with such .babelrc:
```json
{
  presets: [
    "@babel/preset-env"
  ]
}
```

**Environment**
- Babel version(s): core is 7.6.4, template is 7.6.0, types is 7.6.3
- Node/npm version: node v10.16.3
- OS: Linux
- Monorepo: no
- How you are using Babel: cli in this case, but the problem happened first with my webpack configuration

Note:
I use yarn and I took care that the subdependencies where the problem seems to happen (types, template, core) used latest version.

**Comment by JLHwung** [comment] 2019-10-22 13:30
The `@babel/*` dependencies are not flatten to the root level, as a workaround, please run
```
npm --depth 9999 update @babel/types
```

**Comment by julienw** [comment] 2019-10-22 13:41
I did the same process manually before filing the bug (thanks for the tool, much easier!). So I still have it after running the same process with the tool. I also did it for @babel/core and @babel/template.
_but_ I don't have the problem when doing it on everything. So likely one of the other modules is the problem.

And now I can't reproduce anymore, probably because my `node_modules` is in a better shape :)
Ths isn't really encouraging that a same pair package.json/yarn.lock doesn't bring the same node_modules :/

**Comment by JLHwung** [comment] 2019-10-22 14:01
If the shape of `node_modules` are changed by `yarn`, `yarn.lock` must also be changed otherwise it is a bug.

`yarn-deduplicate` writes the new `yarn.lock` but does not touch `node_modules`. And I assume you have run `yarn` after that. So the `yarn.lock` must experience the following process
```
old version  ===>  yarn update  ===>  yarn-deduplicate
( good )            ( bad )              ( good )  
```

Could you share the `yarn.lock` of the first `(good)` and `(bad)`? You may also DM me on slack. We would like to make sure if there is anything wrong on babel's side.

**Comment by julienw** [comment] 2019-10-22 14:02
Actually I could reproduce again by 1/ switching to master and running `yarn install`, then 2/ switching to my branch and running `yarn install`.

By using yarn-deduplicate on various babel packages I could determine that the problem was with `@babel/code-frame`. Does that mean that some other babel package should upgrade to a newer version of that package?

**Comment by julienw** [comment] 2019-10-22 15:10
1. [before upgrade](https://github.com/babel/babel/files/3756531/yarn.lock.txt)
2. [bad when installing on top of the previous one, good when installing on top of the next one](https://github.com/babel/babel/files/3756513/yarn.lock.txt). You'll see that I upgraded more than just babel stuff here. It's a bit strange that I don't get the same behavior depending on which previous yarn.lock we had, but maybe not that strange because `package.json` changes too between 1 and 2 (but not between 2 and 3)
3. [always good](https://github.com/babel/babel/files/3756497/yarn.lock.txt), after deduplicating `@babel/code-frame` only.

This is the main difference between the 2nd and the 3rd:
```diff
-"@babel/code-frame@^7.0.0":
-  version "7.0.0"
-  resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.0.0.tgz#06e2ab19bdb535385559aabb5ba59729482800f8"
-  integrity sha512-OfC2uemaknXr87bdLUkWog7nYuliM9Ij5HUcajsVcMCpQrcLmtxRbVFTIqmcSkSeYRBFBRxs2FiUqFJDLdiebA==
-  dependencies:
-    "@babel/highlight" "^7.0.0"
-
-"@babel/code-frame@^7.5.5":
+"@babel/code-frame@^7.0.0", "@babel/code-frame@^7.5.5":
   version "7.5.5"
   resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.5.5.tgz#bc0782f6d69f7b7d49531219699b988f669a8f9d"
   integrity sha512-27d4lZoomVyo51VegxI20xZPuSHusqbQag/ztrBC7wegWoQ1nLREPVSKSW8byhTlzTKyNE4ifaTA6lCp7JjpFw==
   dependencies:
     "@babel/highlight" "^7.0.0"
```
(plus yarn-deduplicate and its dependencies obviously)

Hope that helps!

**Comment by JLHwung** [comment] 2019-10-22 15:29
@nicolo-ribaudo In [7.5.5](https://github.com/babel/babel/commit/0407f034f09381b95e9cabefbf6b176c76485a43#diff-3941fc777f15b5b85aacb9c9b51a94daR36), `@babel/core` bumps `@babel/code-frame` dependencies to `^7.5.5`, but `@babel/template` remain the dependency on `^7.0.0` because there is no change in `@babel/template`.

This dependency inconsistency results in nested dependencies. Should we also bump the version of dependents of `lerna changed`?

**Comment by JLHwung** [comment] 2019-10-22 16:41
@julienw What's the version of `@babel/types` in `./node_modules/@babel/core/node_modules/@babel/template/node_modules/@babel/types/package.json`? If it is exactly 7.6.x, then `isPlaceholder` is well defined and it may be caused by uninitialized commonjs module, otherwise it should be a bug of yarn.

**Comment by julienw** [comment] 2019-10-22 16:52
I get 7.3.0 for that one.

**Comment by julienw** [comment] 2019-10-22 16:53
I agree that it could be a bug of yarn because we don't get the same setup with the same package.json/yarn.lock depending the environment we come from...

**Comment by nicolo-ribaudo** [comment] 2019-10-22 21:45
> @nicolo-ribaudo In 7.5.5, @babel/core bumps @babel/code-frame dependencies to ^7.5.5, but @babel/template remain the dependency on ^7.0.0 because there is no change in @babel/template.

This dependency inconsistency results in nested dependencies in node_modules. Should we also bump the version of dependents of lerna changed?

If it will make it less likely to have problems like this, then yes :+1:

**Comment by JLHwung** [comment] 2019-11-15 02:37
Closing this as it can not be consistently reproduced. 😔

**Closed by JLHwung** 2019-11-15 02:37 UTC
Labels: i: bug
