### ISSUE TITLE
Public class properties are not transformed with babel-env preset targeting latest Chrome, and shippedProposals enabled

### ISSUE THREAD

**Issue by Malgalad** [babel/babel#12718] opened 2021-01-30 00:46 UTC
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

- [REPL](https://babeljs.io/repl#?browsers=last%201%20Chrome%20versions&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAEBiD29oG8BQ1oFsCmAXAFvACbQC80AFAJRkB8KAvgNzrSsAOATvO9p7gE8y0AOQAjMJxEsGQA&debug=false&forceAllTransforms=false&shippedProposals=true&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=true&targets=&version=7.12.12&externalPlugins=) does not transform class fields without explicitly adding plugin `@babel/plugin-proposal-class-properties`. 

**Expected behavior**

Since the `targets` field is `last 1 Chrome versions`, and public class fields [are supported](https://caniuse.com/mdn-javascript_classes_public_class_fields) in last _15_ Chrome versions, as well as FF, I expect that code should not cause problems.

**Environment**

- Babel version(s): v7.12.0
- Node/npm version: Node 15.5/npm 7.3
- OS: Ubuntu 16.04
- Monorepo: no
- How you are using Babel: `webpack`

**Comment by nicolo-ribaudo** [comment] 2021-01-30 13:31
I can reproduce this bug using `@babel/standalone` (which is used by the REPL), but not using `@babel/cli` or `babel-loader` (that I assume you are using, since you are using webpack).

**Comment by nicolo-ribaudo** [comment] 2021-01-30 13:47
I have bisected and this bug in `@babel/standalone` has been fixed by https://github.com/babel/babel/pull/12651.

`shippedProposals` at line 101833 of [`babel.js`](https://unpkg.com/browse/@babel/standalone@7.12.12/babel.js) should be a reference to line 90430, but the declaration at line 90430 was shadowed by line 101782.

I'm closing this issue since it is fixed on `main`, the fix will be released in the next version.

**Closed by nicolo-ribaudo** 2021-01-30 13:47 UTC
Labels: i: bug, pkg: standalone
