### ISSUE TITLE
Self-calling arrow functions no longer work

### ISSUE THREAD

**Issue by ScottKaye** [babel/babel#2880] opened 2015-11-06 20:15 UTC
In Babel 5, it was possible to do this:

```
() => {
    console.log("test");
}();
```

However, this is no longer possible in Babel 6 - it gives an "unexpected token" error.  Instead, I have to wrap the function as an expression:

```
(() => {
    console.log("test");
})();
```

I'm transpiling with the following Gulp task:

```
var gulp = require("gulp");
var browserify = require("browserify");
var buffer = require("vinyl-buffer");
var source = require("vinyl-source-stream");
var sourcemaps = require("gulp-sourcemaps");

gulp.task("js", function() {
	var bundler = browserify("src/app.js")
				.transform("babelify", {
					presets: ["es2015"]
				});

	return bundler.bundle()
		.on("error", function(err) {
			console.error(err);
			this.emit("end");
		})
		.pipe(source("app.js"))
		.pipe(buffer())
		.pipe(sourcemaps.init({ loadMaps: true }))
		.pipe(sourcemaps.write("./"))
		.pipe(rename("dist/app.js"))
		.pipe(gulp.dest("./"));
});
```

This script works fine with everything else, as long as I wrap my self-calling arrow functions in brackets.  Is this intentional, or is this a regression?

**Comment by loganfsmyth** [comment] 2015-11-06 20:20
Duplicate of https://github.com/babel/babel/issues/2847

**Closed by loganfsmyth** 2015-11-06 20:20 UTC
