### ISSUE TITLE
Only partial transpilation when trying to transpile angular2

### ISSUE THREAD

**Issue by cburgdorf** [babel/babel#867] opened 2015-02-22 20:42 UTC
This is more or less a follow up to https://github.com/babel/babel/issues/817

I'm trying to get babel to work with Angular2 (without AtScript, which is supposed to work) and I'm not yet sure whether this issue is a problem with babel, angular2 or me ;)

But since @sebmck was so kind to give me the right pointers I first try to resolve it here. I'm happy to close and reopen in the angular repository if it turns out not to be an issue with babel.

So, the problem I'm seeing is that after transpilation I still have ES6 code in my transpiled file that is supposed to be ES5 only.

![bildschirmfoto 2015-02-22 um 21 24 55](https://cloud.githubusercontent.com/assets/521109/6320344/b70827de-bada-11e4-9c5f-7bf12244118a.png)

Obviously that leads to the browser yelling at me with:

>Uncaught SyntaxError: Unexpected reserved word

I don't get any errors on the CLI when gulp runs which is why I'm feeling a little lost with the debugging.

**Steps to reproduce**

1. Fork https://github.com/cburgdorf/ng2-app

2. run `npm install && gulp watch`

3. open browser and find the described error in the console

If I comment this code from `app.js`

```

import {bootstrap,
  Component,
  Decorator,
  Template,
  NgElement} from '../node_modules/angular2/angular2';
```

It works without issues (printing my name to the console). So in general the transpilation works, but once I include angular2 I run into this error.

I'm happy for any pointers.

**Comment by sebmck** [comment] 2015-02-22 21:46
Looks like angular are shipping raw dependencies. I'm not sure if there's a way to fix this as it's inside `node_modules` and I don't think there's a way for you to make browserify transform anything inside it.

**Comment by cburgdorf** [comment] 2015-02-22 21:49
Sorry, I'm not following. What do you mean with "raw dependencies". It's all straight ES6 code exposing modules. The files should all be there. Where is the difference to the modules that I write outside of `node_modules`?

**Comment by sebmck** [comment] 2015-02-22 21:51
All the files in `node_modules` are expected to be already transpiled, in this case angular isn't. Browserify specifically doesn't touch `node_modules` as there's no reason to.

**Comment by cburgdorf** [comment] 2015-02-22 21:58
Ah, I see. Ok, I moved it out.

I'm running into new errors now ;)

```
Error: Parsing file /Users/cburgdorf/Documents/hacking/ng2-app/angular2/src/change_detection/parser/ast.es6: Defining 'eval' in strict mode (36:22)
Error: Unexpected token
Error: Line 20: Unexpected token = while parsing /Users/cburgdorf/Documents/hacking/ng2-app/node_modules/angular2/src/core/zone/vm_turn_zone.es6 while parsing file: /Users/cburgdorf/Documents/hacking/ng2-app/node_modules/angular2/src/core/zone/vm_turn_zone.es6
```

So, the first error is complaining about this class [defining an `eval` method](https://github.com/cburgdorf/ng2-app/blob/master/angular2/src/change_detection/parser/ast.es6#L13).

Is this intended behavior? Shouldn't it be totally legit to name a method `eval`?

**Comment by sebmck** [comment] 2015-02-22 22:13
> Shouldn't it be totally legit to name a method eval?

Not in strict mode it's not. I guess you could disable strict mode in Babel with `{ blacklist: ["useStrict"] }`, I don't recommend it but there probably isn't another way. I can't seem to find the source of  `angular2/src/core/zone/vm_turn_zone.es6` in the angular repo so I'm having trouble debugging that.

**Comment by cburgdorf** [comment] 2015-02-23 08:18
Thanks again for your help!

>Not in strict mode

I didn't know that. I'll create an issue in the angular repository to start a discussion about changing the name here.

>I guess you could disable strict mode in Babel

[Tried that](https://github.com/cburgdorf/ng2-app/blob/master/gulpfile.js#L29), didn't work. Still running into the same error. Am I doing it wrong?

>I can't seem to find the source `of angular2/src/core/zone/vm_turn_zone.es6`

The source should be [here](https://github.com/cburgdorf/ng2-app/blob/master/angular2/src/core/zone/vm_turn_zone.es6) in my repo and also [here](https://github.com/angular/angular/blob/master/modules/angular2/src/core/zone/vm_turn_zone.es6) in the actual angular repository.

**Comment by sebmck** [comment] 2015-02-23 09:23
> Tried that, didn't work. Still running into the same error. Am I doing it wrong?

Hm, that should work. Try disabling the `spec.functionName` transformer too.

> The source should be here in my repo and also here in the actual angular repository.

Seems to parse just [fine](http://babeljs.io/repl/#?experimental=true&playground=true&evaluate=true&loose=false&spec=false&code=import%20%7BList%2C%0A%20%20ListWrapper%2C%0A%20%20StringMapWrapper%7D%20from%20'angular2%2Fsrc%2Ffacade%2Fcollection'%3B%0Aimport%20%7BnormalizeBlank%2C%0A%20%20isPresent%2C%0A%20%20global%7D%20from%20'angular2%2Fsrc%2Ffacade%2Flang'%3B%0Aexport%20class%20VmTurnZone%20%7B%0A%20%20constructor(%7BenableLongStackTrace%7D)%20%7B%0A%20%20%20%20this._nestedRunCounter%20%3D%200%3B%0A%20%20%20%20this._onTurnStart%20%3D%20null%3B%0A%20%20%20%20this._onTurnDone%20%3D%20null%3B%0A%20%20%20%20this._onErrorHandler%20%3D%20null%3B%0A%20%20%20%20this._outerZone%20%3D%20global.zone%3B%0A%20%20%20%20this._innerZone%20%3D%20this._createInnerZone(this._outerZone%2C%20enableLongStackTrace)%3B%0A%20%20%7D%0A%20%20initCallbacks(%7BonTurnStart%2C%0A%20%20%20%20onTurnDone%2C%0A%20%20%20%20onScheduleMicrotask%2C%0A%20%20%20%20onErrorHandler%7D%20%3D%20%7B%7D)%20%7B%0A%20%20%20%20this._onTurnStart%20%3D%20normalizeBlank(onTurnStart)%3B%0A%20%20%20%20this._onTurnDone%20%3D%20normalizeBlank(onTurnDone)%3B%0A%20%20%20%20this._onErrorHandler%20%3D%20normalizeBlank(onErrorHandler)%3B%0A%20%20%7D%0A%20%20run(fn)%20%7B%0A%20%20%20%20return%20this._innerZone.run(fn)%3B%0A%20%20%7D%0A%20%20runOutsideAngular(fn)%20%7B%0A%20%20%20%20return%20this._outerZone.run(fn)%3B%0A%20%20%7D%0A%20%20_createInnerZone(zone%2C%20enableLongStackTrace)%20%7B%0A%20%20%20%20var%20vmTurnZone%20%3D%20this%3B%0A%20%20%20%20var%20errorHandling%3B%0A%20%20%20%20if%20(enableLongStackTrace)%20%7B%0A%20%20%20%20%20%20errorHandling%20%3D%20StringMapWrapper.merge(Zone.longStackTraceZone%2C%20%7BonError%3A%20function(e)%20%7B%0A%20%20%20%20%20%20%20%20%20%20vmTurnZone._onError(this%2C%20e)%3B%0A%20%20%20%20%20%20%20%20%7D%7D)%3B%0A%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20errorHandling%20%3D%20%7BonError%3A%20function(e)%20%7B%0A%20%20%20%20%20%20%20%20%20%20vmTurnZone._onError(this%2C%20e)%3B%0A%20%20%20%20%20%20%20%20%7D%7D%3B%0A%20%20%20%20%7D%0A%20%20%20%20return%20zone.fork(errorHandling).fork(%7B%0A%20%20%20%20%20%20beforeTask%3A%20()%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20this._beforeTask()%3B%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20afterTask%3A%20()%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20this._afterTask()%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D)%3B%0A%20%20%7D%0A%20%20_beforeTask()%20%7B%0A%20%20%20%20this._nestedRunCounter%2B%2B%3B%0A%20%20%20%20if%20(this._nestedRunCounter%20%3D%3D%3D%201%20%26%26%20this._onTurnStart)%20%7B%0A%20%20%20%20%20%20this._onTurnStart()%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20_afterTask()%20%7B%0A%20%20%20%20this._nestedRunCounter--%3B%0A%20%20%20%20if%20(this._nestedRunCounter%20%3D%3D%3D%200%20%26%26%20this._onTurnDone)%20%7B%0A%20%20%20%20%20%20this._onTurnDone()%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20_onError(zone%2C%20e)%20%7B%0A%20%20%20%20if%20(isPresent(this._onErrorHandler))%20%7B%0A%20%20%20%20%20%20var%20trace%20%3D%20%5BnormalizeBlank(e.stack)%5D%3B%0A%20%20%20%20%20%20while%20(zone%20%26%26%20zone.constructedAtException)%20%7B%0A%20%20%20%20%20%20%20%20trace.push(zone.constructedAtException.get())%3B%0A%20%20%20%20%20%20%20%20zone%20%3D%20zone.parent%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20this._onErrorHandler(e%2C%20trace)%3B%0A%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20throw%20e%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A%0A%2F%2F%23%20sourceMappingURL%3D%2FUsers%2Ftbosch%2Fprojects%2Fangular2%2Fmodules%2Fangular2%2Fsrc%2Fcore%2Fzone%2Fvm_turn_zone.map%0A%0A%2F%2F%23%20sourceMappingURL%3D.%2Fvm_turn_zone.map) so I'm not sure what the problem is there.

**Comment by cburgdorf** [comment] 2015-02-23 11:07
>Try disabling the `spec.functionName` transformer too

You mean like [that](https://github.com/cburgdorf/ng2-app/blob/master/gulpfile.js#L29)? Still running into the eval error :-/

**Comment by sebmck** [comment] 2015-02-23 11:08
Just realised you're putting the blacklist in the wrong spot. Replace:

```javascript
.transform(babelify)
```

with

```javascript
.transform(babelify.configure({
  blacklist: ["useStrict", "spec.functionName"]
}))
```

**Comment by cburgdorf** [comment] 2015-02-23 11:30
Mmmh, it's weird, it seems as if I have to configure the [`extensions` in the one place and the `blacklist` in the other](https://github.com/cburgdorf/ng2-app/blob/master/gulpfile.js#L28-L37).

If I just move everything (except the `debug`), I'm back to the problem where it won't recognize the `es6` files.

The eval bug is gone now, but there`s a new `Unexpected token` message above the `vm_turn_zone.es6`thingy :-/
```
Error: Unexpected token
Error: Line 20: Unexpected token = while parsing /Users/cburgdorf/Documents/hacking/ng2-app/node_modules/angular2/src/core/zone/vm_turn_zone.es6 while parsing file: /Users/cburgdorf/Documents/hacking/ng2-app/node_modules/angular2/src/core/zone/vm_turn_zone.es6
```

**Comment by cburgdorf** [comment] 2015-02-23 13:35
As a side note as @caitp noted in the other ticket it seems that naming methods `eval` should actually be allowed and it's a Chrome bug that it wasn't https://code.google.com/p/v8/issues/detail?id=1984

**Comment by sebmck** [comment] 2015-02-23 22:43
I'm not quite sure where the message

```
Error: Line 20: Unexpected token = while parsing /Users/cburgdorf/Documents/hacking/ng2-app/node_modules/angular2/src/core/zone/vm_turn_zone.es6 while parsing file: /Users/cburgdorf/Documents/hacking/ng2-app/node_modules/angular2/src/core/zone/vm_turn_zone.es6
```

is coming from as it's definently not from babel.

**Comment by caitp** [comment] 2015-02-23 23:03
that looks like the v8 unexpected_token message

**Comment by sebmck** [comment] 2015-02-25 02:38
Closing this as all the issues related to Babel seem to have been resolved. If you need anymore help feel free to ask in the [gitter room](http://gitter.im/babel/babel), thanks!

**Closed by sebmck** 2015-02-25 02:38 UTC

**Comment by cburgdorf** [comment] 2015-03-04 10:07
>why v8 is trying to parse the raw vm_turn_zone script, beats me =)

I'd really like to understand how V8 is involved in this transpilation process at all.
