### ISSUE TITLE
Default parameters susceptible to redefining the value of undefined

### ISSUE THREAD

**Issue by ditam** [babel/babel#2037] opened 2015-07-19 14:11 UTC
Given the following code:

    var undefined = 1;
    function undefinedTester(number=2){ console.log(number); }
    undefinedTester(1);

The transpiler output (checked on the [babelJs website REPL](https://babeljs.io/repl)) is:

    "use strict";
    var undefined = 1;
    function undefinedTester() {
      var number = arguments.length <= 0 || arguments[0] === undefined ? 2 : arguments[0];
     console.log(number);
    }
    undefinedTester(1);

This transpiled code logs `2`, when it should be logging `1`.
SpiderMonkey's current implementation (checked in Firefox 39.0) logs `1`, so it is not affected by the redefined `undefined` value. 

*I cannot pinpoint the relevant part in the spec, but I assume FF39 to be compliant. (Please link me to the relevant parts of the spec if this is not the case.)*

**Suggested fix**: to aquire the correct result, the transpiled code should be using

    typeof arguments[0] === 'undefined'
style undefined-checks.

**Comment by sebmck** [comment] 2015-07-19 23:12
It's a tricky problem on how well protected the output code could be from someone messing with builtins. I'm leaning more towards just adding this as a caveat. The only reason someone would be assigning `undefined` would be a malicious one, and there's nothing we can do about someone overriding instance builtins that Babel is desugaring to for other transforms. If you want to protect against this in your applications then there's the [spec.undefinedToVoid](https://babeljs.io/docs/advanced/transformers/spec/undefined-to-void/) transformer that replaces references to `undefined` with `void 0`.

**Comment by ditam** [comment] 2015-07-20 05:02
> The only reason someone would be assigning undefined would be a malicious one

I disagree, it can also be accidental. (["Never attribute to malice that which is adequately explained by stupidity."](https://en.wikipedia.org/wiki/Hanlon%27s_razor))

Regardless, this is less a question of usefulness, and more one of spec compliance. I *assume* when the spec talks about undefined values being passed, it doesn't mean values equaling the value of `undefined` in the current scope, but the actual special type undefined. Firefox seems to have the same understanding.

**Comment by sebmck** [comment] 2015-07-20 10:54
> I disagree, it can also be accidental. (["Never attribute to malice that which is adequately explained by stupidity."](https://en.wikipedia.org/wiki/Hanlon%27s_razor))

I don't see how, and linking to Wikipedia articles on logical fallacies isn't really helpful.

> I *assume* when the spec talks about undefined values being passed, it doesn't mean values equaling the value of `undefined` in the current scope, but the actual special type undefined

Yeah, it does.

The issue is that if it's protected for in this scenario then all the other transforms need to accommodate for this too. You're basically arguing for enabling the [spec.undefinedToVoid](https://babeljs.io/docs/advanced/transformers/spec/undefined-to-void/) transformer by default.

**Comment by thejameskyle** [comment] 2015-09-23 08:34
Closing this as wontfix. Contribs feel free to reopen this.

**Closed by thejameskyle** 2015-09-23 08:34 UTC
