### ISSUE TITLE
Template strings transpile incorrectly

### ISSUE THREAD

**Issue by ljharb** [babel/babel#2033] opened 2015-07-18 18:45 UTC
The following:
```js
`${foo}`
```
[transpiles](http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=%60%24%7Bfoo%7D%60) to:
```js
"" + foo;
```

However, concatenating to an empty string actually calls `valueOf`, not `toString`, and as such is not correct. See the following JS:
```js
var x = { toString: function () { return NaN; }, valueOf: function () { return Infinity; }};
[x.toString(), x + '', String(x)]
/* note that only the third item is both a string, and the toString value */
```

It should transpile to:
```js
String(foo)
```

**Comment by sebmck** [comment] 2015-07-18 18:47
Duplicate of #1065 and also see the optional [es6.spec.templateLiterals](https://babeljs.io/docs/advanced/transformers/es6/spec-template-literals/) transformer.

**Closed by sebmck** 2015-07-18 18:47 UTC

**Comment by ljharb** [comment] 2015-07-18 18:49
Ah, thanks, i didn't see the other issue. I'm glad the optional transformer is there, but imo that should be default, since the default case is not going to be using template strings in a tight loop - I'd rather see incorrectness+performance be opt-in than the way it is right now.

**Comment by ljharb** [comment] 2015-07-18 18:50
In other words, correctness is more important than performance, and for the few who care, they'll be able to figure out how to turn on any relevant options to increase performance at the cost of known spec violations.
