### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by smartgru** [babel/babel#15656] opened 2023-05-26 16:09 UTC
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

Error occurring after installed latest [@babel/core](https://www.npmjs.com/package/@babel/core/v/7.22.0)

### Configuration file name

babel.config.js

### Current and expected behavior

Getting error 

> Cannot find module '@babel/plugin-proposal-private-property-in-object'

### Environment

- Babel version: latest (7.22.0)
- Node: 16
- yarn v1.22.19
- Mac OS Venutura / Ubuntu 22.0.4

### Possible solution

It's working fine after I installed `@babel/plugin-proposal-private-property-in-object` .

`yarn add @babel/plugin-proposal-private-property-in-object --dev`

### Additional context

Seems the latest release 7.22.0 has an issue.
It was working properly until few hours ago.

**Comment by nicolo-ribaudo** [comment] 2023-05-26 16:17
Duplicate of https://github.com/babel/babel/issues/15655

**Closed by nicolo-ribaudo** 2023-05-26 16:17 UTC
Labels: i: needs triage
