### ISSUE TITLE
State Mismanagement in Tail Call Elimination loops

### ISSUE THREAD

**Issue by ds300** [babel/babel#1938] opened 2015-07-07 09:57 UTC
Have a look at this:
```javascript
function foo (a, b) {
  if (b) {
    return foo(b);
  } else {
    return a;
  }
}
```

One would expect `foo("Michael", "Jackson")` to evaluate to "Jackson", yes? Yes. Except it doesn't. Rather, the function never returns and your computer probably heats up a little. 

A quick look at the compiled code shows what the problem is:

```javascript
function foo(_x, _x2) {
  var _again = true;

  _function: while (_again) {
    var a = _x,
        b = _x2;               // (1)
    _again = false;

    if (b) {                   // (2)
      _x = b;                  // (3)
      _again = true;
      continue _function;
    } else {
      return a;
    }
  }
}
```
At `(3)` we simulate the tail call `foo(b)` by setting `_x` to `b` and jumping back to the start of the loop. Only problem is, `_x2` is still the same value as `b` so `(1)` is a noop on the second go round. Obviously this means that `(2)` evaluates true and we just keep spinning like that.

Solution: Reset all parameters, not just the ones passed to the tail call. Unless, perhaps, you can be certain they (the unpassed parameters) won't be dereferenced again, but that seems like difficult logic to implement for very little performance gain.

But wait! There's more!

```javascript
function foo (a, b) {
  if (arguments.length == 2) {
    return foo(() => console.log(a, b));
  } else {
    return a;
  }
}

foo("Michael", "Jackson")();
```

Can you guess what this prints? No cheating now...

Yes that's right! It prints something like:

```
function () { return console.log(a, b); } Jackson
```

This is because the lambda closes over `a`, but `a` is promptly reset by the TCE loop from "Michael" to the lambda itself.

Solution?: check for parameters being closed over with the resulting closure escaping the scope of the current TCE loop iteration. Surround them with an extra closure or `with` or something? Not sure what would be performant.

![](http://i.imgur.com/wZQHMuZ.jpg)

Sorry I couldn't resist.

**Comment by sebmck** [comment] 2015-07-07 10:00
First should be an easy fix, second one is a duplicate of #1480.

**Comment by ds300** [comment] 2015-07-07 10:03
Whoops, apologies. My search-fu failed me. Should I edit the issue to remove the second bit?

**Comment by sebmck** [comment] 2015-07-07 10:13
Nah it's all good. Thanks for the detailed report!

**Closed** 2015-07-07 10:13 UTC
