### ISSUE TITLE
Computed property names don't work with class properties syntax

### ISSUE THREAD

**Issue by jayphelps** [babel/babel#2323] opened 2015-09-04 21:40 UTC
I found this https://github.com/babel/babel/issues/1655 but it was closed without a real answer and it links to a [spec doc](https://gist.github.com/jeffmo/054df782c05639da2adb) that people ask about it in the comments but I do not see anyone answering why it's omitted in the spec.

```js
const first = Symbol();
const second = Symbol();

class Foo {
  // This works
  [first]() {}
  // This does not
  [second] = {};
}
```

```
repl: Unexpected token (6:11)
  4 | class Foo {
  5 |   [first]() {}
> 6 |   [second] = {};
    |            ^
  7 | }
```
[REPL](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&playground=true&code=const%20first%20%3D%20Symbol()%3B%0Aconst%20second%20%3D%20Symbol()%3B%0A%0Aclass%20Foo%20%7B%0A%20%20%5Bfirst%5D()%20%7B%7D%0A%20%20%5Bsecond%5D%20%3D%20%7B%7D%3B%0A%7D&stage=0)

Cc/ @jeffmo

**Comment by zloirock** [comment] 2015-09-04 21:49
AFAIK this proposal not supports computed properties.
```
ClassPropertyInitializer : 
  IdentifierName = AssignmentExpression ;
```
[comment](https://gist.github.com/jeffmo/054df782c05639da2adb#gistcomment-1406269), [spec](http://www.ecma-international.org/ecma-262/6.0/#sec-identifier-names)

**Comment by sebmck** [comment] 2015-09-04 22:01
@zloirock is correct. Duplicate of #2312.

**Closed by sebmck** 2015-09-04 22:01 UTC
