### ISSUE TITLE
Problem with async generators

### ISSUE THREAD

**Issue by vtambourine** [babel/babel#2755] opened 2015-11-02 19:35 UTC
I have a problem running async/await code in babel 6 environment.
Here is problematic code:

```js
require('babel-polyfill');

function getValues() {
  return Promise.resolve([1,2,3,4]);
}

async function foo() {
  var values = await getValues();
  console.log(values);
}
```

I expect it to write `[1, 2, 3, 4]` in the console. However, it results in error:
```
$ babel-node test.js
TypeError: Object.setPrototypeOf called on null or undefined
    at Function.setPrototypeOf (native)
    at runtime.mark (/Users/benjamin/.nvm/versions/node/v4.1.1/lib/node_modules/babel-cli/node_modules/babel-polyfill/node_modules/regenerator/runtime.js:111:14)
    ...
```

I tried to precompile it and run by `node` itself. This results in different error:
```
$ node test-transpiled.js
/Users/benjamin/Projects/test-transpiled.js:4
  var _marked = [foo].map(regeneratorRuntime.mark);
                          ^

ReferenceError: regeneratorRuntime is not defined
    at /Users/benjamin/Projects/test-transpiled.js:4:27
    ...
```

My environments are: `babel 6.0.15 (babel-core 6.0.16)`, `node v4.1.1`.

**Comment by mattstyles** [comment] 2015-11-03 11:21
The `regeneratorRuntime` is included with `babel-polyfill`

**Comment by AhmadZuhdi** [comment] 2015-11-03 11:42
i have the same issue,

es2015 code :
```javascript
import 'babel-polyfill'

function getData(){
  return new Promise((rosolve) => {
    setTimeout(() => {
      resolve(['this', 'is', 'data'])
    }, 1000)
  })
}

async function loadData(){
  var data = await getData()
  console.log(data)
}
```

the problem is in the compiled code :
```javascript
var loadData = (function () {
  var _marked = [loadData].map(regeneratorRuntime.mark);

  var ref = _asyncToGenerator(function loadData() {
    var data;
    return regeneratorRuntime.wrap(function loadData$(_context) {
      while (1) switch (_context.prev = _context.next) {
        case 0:
          _context.next = 2;
          return getData();

        case 2:
          data = _context.sent;

          console.log(data);

        case 4:
        case 'end':
          return _context.stop();
      }
    }, _marked[0], this);
  });

  return function loadData() {
    return ref.apply(this, arguments);
  };
})();

require('babel-polyfill');

function _asyncToGenerator(fn) { return function () { var gen = fn.apply(this, arguments); return new Promise(function (resolve, reject) { var callNext = step.bind(null, "next"); var callThrow = step.bind(null, "throw"); function step(key, arg) { try { var info = gen[key](arg); var value = info.value; } catch (error) { reject(error); return; } if (info.done) { resolve(value); } else { Promise.resolve(value).then(callNext, callThrow); } } callNext(); }); }; }

function getData() {
  return new Promise(function (rosolve) {
    setTimeout(function () {
      resolve(['this', 'is', 'data']);
    }, 1000);
  });
}
//# sourceMappingURL=test.js.map
```

the `regeneratorRuntime` is called before `babel-polyfill` required

versions : 
- babel 6.0.15 (babel-core 6.0.16) with plugins : `syntax-async-functions` and presets : `es2015, stage-0`
- babel-polyfill 6.0.16

**Comment by ritz078** [comment] 2015-11-03 21:24
Same problem with me.

**Comment by kyrylkov** [comment] 2015-11-04 07:09
Should be merged to https://github.com/babel/babel/issues/2744

**Comment by zloirock** [comment] 2015-11-05 05:50
Looks like duplicate #2744.

**Closed by zloirock** 2015-11-05 05:50 UTC
