### ISSUE TITLE
@babel/preset-env useBuiltIns cause exports is not defined

### ISSUE THREAD

**Issue by wangtao0101** [babel/babel#7463] opened 2018-03-01 07:52 UTC
babel version beta.40
babelrc config 
```
"presets": [
        ["@babel/preset-env", {
            "targets": {
                "browsers": ["last 2 versions", "ie >= 10"],
            },
            "useBuiltIns": "usage",
        }],
        "@babel/preset-react",
    ],
```
babel will generate code:
```
/*! no exports provided */
/*! all exports used */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
Object.defineProperty(__webpack_exports__, "__esModule", { value: true });
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0_core_js_modules_es6_object_set_prototype_of__ = __webpack_require__(/*! core-js/modules/es6.object.set-prototype-of */ "./node_modules/core-js/modules/es6.object.set-prototype-of.js");
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0_core_js_modules_es6_object_set_prototype_of___default = __webpack_require__.n(__WEBPACK_IMPORTED_MODULE_0_core_js_modules_es6_object_set_prototype_of__);



Object.defineProperty(exports, "__esModule", {
  value: true
});
```

It cause error `Uncaught (in promise) ReferenceError: exports is not defined.`

If i remove useBuiltIns
babel will generate code:
```
/*! dynamic exports provided */
/*! all exports used */
/***/ (function(module, exports, __webpack_require__) {

"use strict";


Object.defineProperty(exports, "__esModule", {
  value: true
});
```
It is right but without harmony

**Comment by loganfsmyth** [comment] 2018-03-01 07:59
This is a duplicate of #7457.

**Closed by loganfsmyth** 2018-03-01 07:59 UTC
