### ISSUE TITLE
JSX source maps create gray lines in chrome sources panel

### ISSUE THREAD

**Issue by aldendaniels** [babel/babel#1318] opened 2015-04-21 19:13 UTC
This seems to affect any no-op lines such as empty lines or comments.

@hbrls observed that this issue affects both [reactify](https://github.com/andreypopp/reactify) and babel: http://stackoverflow.com/questions/29650951/what-are-these-grey-lines-in-the-chrome-sources-panel.

**EXAMPLE**
![screen shot 2015-04-21 at 2 10 53 pm](https://cloud.githubusercontent.com/assets/4658558/7260522/4320d630-e830-11e4-9aba-6156ad5f9ddd.png)

It's also possible this is a Browserify issue.

**Comment by sebmck** [comment] 2015-04-21 19:38
Doubt it's a browserify issue, it'd just be that mapping weren't being
added for blank lines and comments. Is there any reason they should be?
Doesn't seem like that big of an issue.

On Tuesday, 21 April 2015, Alden Daniels <notifications@github.com> wrote:

> This seems to affect any no-op lines such as empty lines or comments.
>
> @hbrls <https://github.com/hbrls> observed that this issue affects both
> reactify <https://github.com/andreypopp/reactify> and babel:
> http://stackoverflow.com/questions/29650951/what-are-these-grey-lines-in-the-chrome-sources-panel
> .
>
> *EXAMPLE*
> [image: screen shot 2015-04-21 at 2 10 53 pm]
> <https://cloud.githubusercontent.com/assets/4658558/7260522/4320d630-e830-11e4-9aba-6156ad5f9ddd.png>
>
> It's also possible this is a Browserify issue.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/1318>.
>


-- 
Sebastian McKenzie

**Comment by loganfsmyth** [comment] 2015-04-21 19:44
I always just assumed this was on purpose. Why bother mappings lines that don't contain any code?

**Comment by aldendaniels** [comment] 2015-04-21 20:09
@sebmck - Yep - that was my uninformed guess as to what was going on.

The gray lines in Chrome are a bit of an eyesore, but that's really the only issue. 

If it's an easy change to include everything (comments, blank links, etc.) in the source map, then I'd suggest doing so simply for the aesthetics of it. The extra bytes aren't a problem since source maps shouldn't be deployed in production.

Feel free to close if you don't think it's worth the trouble.

**Comment by JaRail** [comment] 2015-04-21 22:21
What about other no-op cases, such as dead code removal? Would
```
if (false) {}
```
show as gray?

**Comment by sebmck** [comment] 2015-04-21 22:22
Since no mappings exist for it, yes.

**Comment by JaRail** [comment] 2015-04-21 22:45
Okay. I was mostly curious. I can't think of a specific case where this would be a problem. I've been trying to think of a case where chaining multiple build tools might have issue with this but I don't really see any. Maybe a case where babel passes through a comment that has meaning to the next tool? eg

/* some interesting custom class annotation */
class ....

Then the next tool in the chain can't reference that comment in the source map since babel isn't outputting a mapping..

**Comment by sebmck** [comment] 2015-04-21 22:46
No "transformation" (and other) tooling doesn't rely on source maps though.

**Comment by JaRail** [comment] 2015-04-21 22:51
Not the transformation itself. I just mean that the final source map can't refer back to the original code since babel didn't output anything for that.

Maybe I add some custom macro.

/* INCLUDE('somefile.js') */

(ignoring that you'd want that before babel :) )

You wouldn't be able to map the contents of the file back to that line of the original source.

(I don't think any of this is particularly important. I'm just brainstorming on the issue.)

**Comment by sebmck** [comment] 2015-04-21 22:53
Comments are still included in the output so I'm not sure how comments mappings not being included is relevant?

**Comment by JaRail** [comment] 2015-04-21 22:57
Say
A -> B
produces a B.js.map file

B - > C consumes both B.js and B.js.map (to continue referencing original code)

If the comment isn't mapped in B.js.map, you can't reference the original comment location in C.js.map.

**Comment by sebmck** [comment] 2015-04-21 23:00
I don't see how comment source map mappings not existing is problematic?

**Comment by JaRail** [comment] 2015-04-21 23:08
I won't lose any sleep over it. Source maps are, at most, a dev productivity enhancement. But I do think the correct behavior is to output a full source map without gaps. I'm personally still 100% okay with a won't fix (or by design if you disagree).

**Comment by hbrls** [comment] 2015-04-22 02:07
@JaRail I was not feeling uncomfortable with the grey lines. If you check my edit of that stackoverflow post, the grey lines sometimes make the break points not work. More frustratingly, I cannot reproduce that behavior with a test case. I just experienced it in my real project from time to time.

And @aldendaniels I changed from reactify to babelify and back to reactify again. If I disabled that sourcemap, the whole thing works. I'd like to use es6 as soom as possible, so I'd like to join the discussion here.

**Comment by sebmck** [comment] 2015-04-24 16:11
So I don't see any point in adding mappings for comments and newlines. It'd add some really wonky source map logic internally for tangible benefits. Thanks everyone for the discussion!

@hbrls 

> the grey lines sometimes make the break points not work.

I doubt this is due to the grey lines and likely due to some wonky mappings being generated. If you manage to get a reproducible test case I'll happy look at it.

**Closed by sebmck** 2015-04-24 16:11 UTC
