### ISSUE TITLE
Invalid output resulting in ReferenceErrors with plugin-proposal-optional-chaining

### ISSUE THREAD

**Issue by felixfbecker** [babel/babel#12026] opened 2020-09-01 18:04 UTC
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

When a nested optional chaining expression is found inside a parameter position (a parameter default value, or default value inside an object or array destructuring), a `var` declaration is added to the function body. That variable declaration is not in effect when evaluating parameter default values and causes a `ReferenceError` in strict mode when the function is called.

- [REPL](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=OQVwzgpgBGAuBOBLAxrYAoZB7AdnKWARgFZQC8UA3gL6a74BmWW5UAFAA4CG8XAtqyLEAdB3hYOARgD8o8RwBMASnIA-KuihRseLABsIwvVgDmnHvyXpaTLGyVA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2%2Cenv&prettier=false&targets=&version=7.11.5&externalPlugins=)

To repro, you can use the Babel CLI to compile the code below and run it with Node: `babel test.js | node`. Error output:

```
const foo = (param = (_obj$prop = obj.prop1) === null || _obj$prop === void 0 ? void 0 : _obj$prop.prop2) => {
                                ^

ReferenceError: _obj$prop is not defined
    at foo ([stdin]:5:33)
    at [stdin]:11:1
    at Script.runInThisContext (vm.js:132:18)
    at Object.runInThisContext (vm.js:315:38)
    at Object.<anonymous> ([stdin]-wrapper:10:26)
    at Module._compile (internal/modules/cjs/loader.js:1256:30)
    at evalScript (internal/process/execution.js:98:25)
    at internal/main/eval_stdin.js:29:5
    at Socket.<anonymous> (internal/process/execution.js:211:5)
    at Socket.emit (events.js:326:22)
```

**Input Code**

```js
'use strict'
const obj = {}
const foo = (param = obj.prop1?.prop2) => {
  console.log(param)
}
foo()
```

**Output Code**

```js
'use strict';

const obj = {};

const foo = (param = (_obj$prop = obj.prop1) === null || _obj$prop === void 0 ? void 0 : _obj$prop.prop2) => {
  var _obj$prop;

  console.log(param);
};

foo();
```

**Expected behavior**
Should not throw a `ReferenceError`, should log `undefined` to the console.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

See REPL link above, or just add the `plugin-proposal-optional-chaining` (doesn't matter whether loose or not, happens in both modes)
```js
{
  "plugings": [
    "@babel/plugin-proposal-optional-chaining"
  ]
}
```

**Environment**
- Babel version(s): 7.11.5
- Node/npm version: v14.7.0
- OS: macOS
- Monorepo: [e.g. yes/no/Lerna]
- How you are using Babel: CLI for repro

**Comment by JLHwung** [comment] 2020-09-01 18:28
Duplicate of #11166.

**Closed by JLHwung** 2020-09-01 18:28 UTC
Labels: i: bug, i: needs triage
