### ISSUE TITLE
Inconsistent helpers transformation in some cases

### ISSUE THREAD

**Issue by wKich** [babel/babel#6001] opened 2017-07-24 08:27 UTC
## Bug

For some reasons `transform-es3-property-literals` don't apply for helper function `_interopRequireDefault`. I try to figure out what this happen, and  I think that `NodePath` for this function has `contexts` field with one context element that don't have queue and function `_getQueueContexts` return context without queue. So `maybeQueue` don't have queue in which path node can be pushed.

### Input Code

```js
import A from 'a';

class B {};

() => {};
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "plugins": [
    "transform-es3-property-literals",
    ["transform-es2015-arrow-functions", { "spec": true }],
    "transform-es2015-modules-commonjs",
    "transform-es2015-classes"
  ]
}
```

### Expected Behavior

```js
// ...
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { 'default': obj }; }
// ...
```

### Current Behavior

```js
// ...
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
// ...
```

### Possible Solution

If I declare arrow function before class, then transformation applied correctly. In babel@7 (after 7.0.0-alpha.10) issue is not reproduced.

I can fix this to modify condition in `_getQueueContexts` to get right contexts with queue, but I think that problem is somewhere deeper.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.25.0
| node             |  6.11.1
| npm              |  3.10.10
| Operating System | OSX 10.12.6

**Comment by wKich** [comment] 2017-07-24 08:53
I have another example with same behavior:

### Input code
```js
import A from 'a'

export class B extends A {}

class C {
  c(x) { return { ...(x ? { x } : {}) } }
}
```

### Babel Configuration (.babelrc, package.json, cli command)
```js
{
  "plugins": [
    "transform-object-rest-spread",
    "transform-proto-to-assign",
    "transform-es3-property-literals",
    ["transform-es2015-modules-commonjs", { "loose": true }],
    "transform-es2015-classes"
  ]
}
```

**Comment by peey** [comment] 2017-07-24 17:24
Related to https://github.com/babel/babel/issues/5876

**Comment by jridgewell** [comment] 2017-07-24 18:42
Yup, dupe of #5876. Thank you for the investigation, though!

**Closed by jridgewell** 2017-07-24 18:42 UTC

**Comment by wKich** [comment] 2017-07-25 03:06
I don't think so. If you think that I want to say that helpers not transpiling, that's not true. I want to say, that visitors of plugins applied on helpers function, but it's behavior inconsistent. And if you transpile with es3 plugin you get working bundle on output, but sometimes it breaks.

**Comment by jridgewell** [comment] 2017-07-25 04:30
Yup, it's because they're not requeued consistently. The linked pull request will requeue them always, allowing all plugins to run over injected helpers.

**Comment by wKich** [comment] 2017-07-25 07:54
You mean #5743?

**Comment by jridgewell** [comment] 2017-07-25 15:45
Yah. Sorry, I thought I included that in the comment. 😬
