### ISSUE TITLE
Decorators with arrow functions with parens around the return value disappear

### ISSUE THREAD

**Issue by ide** [babel/babel#2103] opened 2015-07-28 08:08 UTC
I've got a little React component with a decorator that is created with an arrow function. With a fairly recent release of Babel, the decorator appears to be completely removed:

```js
@connect(data => ({ account: data.account }))
class C extend React.Component {
}
```

Changing the arrow function fixes the issue as a workaround:

```js
@connect(data => { return { account: data.account }; })
class C extend React.Component {
}
```

It's fine with other arrow functions like this:
```js
data => 1
data => []
```

So something about the parens is causing the issue.

**Comment by sebmck** [comment] 2015-07-28 08:10
Duplicate of #2086, #2088, #2090, #2093, #2094, and #2099. This has since been fixed in 5.8.12.

**Comment by ide** [comment] 2015-07-28 08:16
I am using 5.8.12. I'm seeing this issue both in my generated code and with babel-eslint (getting a warning that says the decorator is unused), and under node_modules I see this:

```
$ npm list | grep babel
│ ├─┬ babel@5.8.12
│ ├─┬ babel-core@5.8.12
```

These are the config options I'm using:

```js
{
    retainLines: true,
    compact: true,
    comments: false,
    whitelist: [
      'es6.arrowFunctions',
      'es6.blockScoping',
      'es6.classes',
      'es6.destructuring',
      'es6.parameters',
      'es6.properties.computed',
      'es6.properties.shorthand',
      'es6.spread',
      'es6.templateLiterals',
      'es7.trailingFunctionCommas',
      'es7.objectRestSpread',
      'flow',
      'react',
      'react.displayName',
      "es6.constants",
      "es6.modules",
      "es7.asyncFunctions",
      "es7.classProperties",
      "es7.decorators",
      "regenerator",
    ],
    sourceMaps: false
  }
```

**Comment by sebmck** [comment] 2015-07-28 08:20
Might be a different issue then, apologies for preemptively closing. Will try and look into it.

**Comment by vasa-chi** [comment] 2015-07-28 10:33
Another error case:
```javascript
@decorator(function(x) {
  return {some: x.map((a) => a)}
})
class C {
}
```

proudces:

```javascript
"use strict";

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

var C = function C() {
  _classCallCheck(this, C);
};
```

https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=%40dec(function(x)%20%7B%0A%20%20return%20%7Bsome%3A%20x.map((a)%20%3D%3E%20a)%7D%0A%7D)%0Aclass%20C%20%7B%0A%20%20%0A%7D

**Comment by sebmck** [comment] 2015-07-28 10:35
It's the same case. It's the presence of parentheses in a decorator. You can fix this by using the `--non-standard` flag, `{ "nonStandard": false }` which disables the flow parser plugin which is the source of these issues.

**Comment by vasa-chi** [comment] 2015-07-28 11:05
@sebmck can I disable only Flow? I'm using React...

**Comment by sebmck** [comment] 2015-07-28 12:41
This was actually fixed via #2087 just into the wrong branch so when I pushed out a new release it didn't include it. I've pushed out 5.8.13 that fixes this. Sorry for the delay.

**Closed by sebmck** 2015-07-28 12:41 UTC

**Comment by vasa-chi** [comment] 2015-07-28 12:55
@sebmck thanks!

**Comment by giogonzo** [comment] 2015-07-28 15:22
@sebmck npm publish ?

**Comment by sebmck** [comment] 2015-07-28 15:23
@giogonzo 

> I've pushed out 5.8.13 that fixes this

**Comment by giogonzo** [comment] 2015-07-28 15:29
Oh, babylon. Thanks!

**Comment by ide** [comment] 2015-07-28 19:45
@sebmck Thanks so much for the quick fix! Babel and babel-eslint are working great.

**Comment by sebmck** [comment] 2015-07-28 20:03
Don't thank me, I just messed up the publish. :blush: @loganfsmyth was the one who did the fix.

**Comment by happypoulp** [comment] 2015-08-11 11:00
Hi,
I am having the same issue and I am using babel 5.8.21:
```
$ npm list | grep babel
├─┬ babel@5.8.21
├─┬ babel-core@5.8.22
```
I saw in comments above that 5.8.13 fix this issue but when looking at the package.json of babel 5.8.21, I see:

```
  "dependencies": {
    "babel-core": "^5.6.21",
```

Is this normal? Did I miss the correct way to have patch of 5.8.13?

Thanks!

**Comment by yuchi** [comment] 2015-08-25 21:14
```js
@deco
class X {}
```

results in ([see in the repl](http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=%40deco%0Aclass%20X%20%7B%7D))

```js
"use strict";

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

var X = (function () {
  function X() {
    _classCallCheck(this, _X);
  }

  var _X = X;
  X = deco(X) || X;
  return X;
})();
```

notice how is `X = deco(X) || X;` instead of `_X = deco(_X) || _X;`.
