### ISSUE TITLE
v6: Constructing a class with optional parameters, invoked from a property doesn't work

### ISSUE THREAD

**Issue by kripod** [babel/babel#2881] opened 2015-11-06 20:57 UTC
./models/player.js:

``` js
export default class Player {
  get id() {
    return this._id;
  }

  constructor(id = null) {
    this._id = id;
  }
}
```

./application.js:

``` js
import Player from './models/player';

export default class Application {
  static get Player() {
    return Player;
  }
}
```

./index.js:

``` js
import Application from './application';

// Both of these throw an exception which says that the argument 'id' is not 
// defined in the constructor of Player
let player1 = new Application.Player();
let player2 = new Application.Player(1);
```

**Comment by kripod** [comment] 2015-11-07 07:58
Notice that whether I change ./models/player.js to:

``` js
export default class Player {
  get id() {
    return this._id;
  }

  constructor(id) {
    this._id = id;
  }
}
```

Then index.js works fine.

**Comment by thejameskyle** [comment] 2015-11-12 08:53
Unable to reproduce: https://github.com/thejameskyle/__babel-bug-2881

@kripod if you can fork that repo and make a simple test case we can reopen this.

**Comment by kripod** [comment] 2015-11-13 19:07
@thejameskyle https://github.com/thejameskyle/__babel-bug-2881/pull/1

**Comment by thejameskyle** [comment] 2015-11-13 19:16
Okay, this appears to only be an issue with `babel-core/register` for some reason.

I've updated the example repo: https://github.com/thejameskyle/__babel-bug-2881

**Comment by thejameskyle** [comment] 2015-11-13 19:16
ping @sebmck

**Comment by danez** [comment] 2016-10-02 13:18
I just tried reproducing with node 6 and 0.10 and couldn't. So going to close it.

**Closed by danez** 2016-10-02 13:18 UTC
