### ISSUE TITLE
[Babel 7] [Typescript] Exported Interfaces from an import are kept in the generated JS code

### ISSUE THREAD

**Issue by manrueda** [babel/babel#8361] opened 2018-07-22 20:05 UTC
## Bug Report

**Current Behavior**
If the Typescript code exports an interfaces that was imported from other module, that interface reference is kept in the Javascript code after transpilation.

**Input Code**

File A:
```typescript
export interface ExportedInterface {
  value: string
}
```

File B:
```typescript
import { ExportedInterface } from './file-a';
export { ExportedInterface }

export function test(): ExportedInterface {
  return { value: '1' };
}
```

**Expected behavior/code**
The result code should not keep reference of that interface because is a type.

```js
export function test() {
  return {
    value: '1'
  };
}
```

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  presets: [
    ['@babel/preset-env', { modules: false }],
     '@babel/preset-typescript',
  ],
}
```

**Environment**
- Babel version(s): v7.0.0-beta.54
- Node/npm version: Node 10.5.0/npm 6.2.0
- OS: OSX 10.13.5
- Monorepo no
- How you are using Babel: cli (but is the same with loader)

**Possible Solution**
Looks like the here is a comment in the code that could be related to this issue: https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-typescript/src/index.js#L52

**Additional context/Screenshots**
The generated code currently is the following one:

File A:
```js
// No error, the file is generated empty
```

File B:
```js
import { IInterface } from './test-sub';
export { IInterface };
export function test() {
  return {
    value: '1'
  };
}
```

**Comment by nicolo-ribaudo** [comment] 2018-07-23 06:58
What if it isn't an interface but a class? Since Babel works per-file and not per-project, it can't know.

**Comment by ManRueda** [comment] 2018-07-23 12:59
Works with classes. But the example that i showed is a simplified version. In my real life problem that interface comes from an external package (npm) so i don't have access to change it to a class.

**Comment by nicolo-ribaudo** [comment] 2018-07-23 15:12
How does typescript handle it with the `--isolatedModules` flags? Ideally we should match that behavior.

**Comment by ManRueda** [comment] 2018-07-23 16:16
Yeah that case is not supported by typescript, it gives this error: `Cannot re-export a type when the '--isolatedModules' flag is provided.`.

What makes sense if the modules are treated in an isolated way.

I will have to find another way to structure and export my types.

**Comment by dfreeman** [comment] 2018-07-26 16:35
One option might be to do something like this so it's syntactically clear that `ExportedInterface` is only a type:

```ts
import * as FileA from './file-a';
export type ExportedInterface = FileA.ExportedInterface;

export function test(): ExportedInterface {
  return { value: '1' };
}
```

**Comment by tajo** [comment] 2018-07-31 14:03
I think I'm running into the same problem and @dfreeman's workaround works.

```ts
// fileA.ts
export interface ExportedInterface { }
```

```ts
// fileB.ts
import { ExportedInterface } from './fileA';

export { ExportedInterface };
```

Webpack complains that `ExportedInterface` can't be found in `./fileA`. `tsc` is happy.

This makes happy both:

```ts
// fileB.ts
import * as  FileA from './fileA';

export type ExportedInterface = FileA.ExportedInterface;
export { ExportedInterface };
```

**Comment by Retsam** [comment] 2018-09-07 19:05
I'm having this issue as well.  It's particularly troublesome because I've got a package that exports only types: it doesn't have a main file.  (It's being used to share data contracts between our front-end and back-end)

Unfortunately, since the import remains in the code, this blows up either at unit-test runtime (attempts to require a file that doesn't exist), or at webpack compile time.  (Bundler can't find that file, either)

---

Additionally, I've been having circular reference issues, and things getting imported sooner than expected, and I believe this also stems from type imports being left in the code.  

Ideally, I think `@babel/plugin-transform-typescript` could detect if a given import is only ever used for types, and remove them.  That may eliminate import side-effects, but I'm pretty sure it's equivalent to the TS behavior.  It doesn't matter if the thing being imported is a `class`, if it's only ever used in type annotations, it's not necessary to import.

**Comment by TroySchmidt** [comment] 2018-10-09 16:42
I can confirm that I have this issue using TypeScript and re-exporting interfaces as well.

**Comment by milesj** [comment] 2018-10-10 21:43
Importing types, and then re-exporting them from another file is *not allowed* in Babel, and will never work. You'll need to restructure your application to work around this.

**Comment by TroySchmidt** [comment] 2018-10-10 22:10
That is very unfortunate.  The use case is that I create a folder to encapsulate the API calls from the React web app into a single folder.  All the interfaces for interacting with the API are in that folder organized into various files.  To make using this API in the React app easier, I think import and export those from an ```index.ts``` file.  This means I can then do things like ```import { Todo } from 'api'``` and not care about what specific folder that came from.  This is common practice with many libraries as well like @material-ui.  
[Material-UI library type re-export](https://github.com/mui-org/material-ui/blob/master/packages/material-ui/src/index.js)

**Comment by sebinsua** [comment] 2018-10-10 22:37
It is possible to re-export values though and in fact Material UI uses Babel to do so.

However, it's impossible to re-export types in Babel, since (as the GitHub issue shows) it will cause these types to end up within the JavaScript output and this shall cause runtime errors.

Babel transpiling TypeScript should be treated as if you are in `--isolatedModules` mode and in fact it is [recommended that you switch this on within `tsconfig.json`](https://blogs.msdn.microsoft.com/typescript/2018/08/27/typescript-and-babel-7/) in order to get relevant warnings.

I don't think it would be possible for Babel to determine whether an import is a type or a value without it having read the underlying types files.

Of course, technically if there were a way to temporarily strip lines with pure TypeScript exports before running them through Babel that would work. I've done this on one of my own projects [using a rollup plugin to automatically remove lines which I prefixed with a particular comment](https://www.npmjs.com/package/rollup-plugin-re). That worked but it is a hack.

**Comment by milesj** [comment] 2018-10-10 23:30
@TroySchmidt What about this? `export * from './types`.

**Comment by TroySchmidt** [comment] 2018-10-22 14:49
@milesj That does seem to work.  So I will continue down that path.  TypeScript classes could include additional functionality with methods on them.  But these are used to define the interfaces of the JSON data that is loaded from the api.  Using interface made sure that someone doesn't accidentally try to add class style functions and expect those to work.

**Comment by sorenhoyer** [comment] 2018-11-03 17:10
We're always creating a `types.ts` file as close as it makes sense in the folder hierarchy anyways. So doing like @milesj suggested above seems like commonsense anyways. I like being a little more explicit though (instead of `import *`), so explicit named exports from `./types` also works of course:

**root/src/utils/types.ts:**

export interface InterfaceA {}
export interface InterfaceB {}

**root/src/utils/index.ts:**

export {
  InterfaceA,
  InterfaceB,
} from './types';

**root/index.ts:**

export {
  InterfaceA,
  InterfaceB,
} from 'utils/index.ts';

So I see it more like TypeScript is trying to "educate" you once again, rather than seeing it as a limitation.

**Comment by sorenhoyer** [comment] 2018-11-03 21:50
@tajo , like @milesj mentioned, instead of importing types and then re-exporting, simply do `export { ExportedInterface } from './fileA';`

@TroySchmidt importing types and then re-exporting shouldn't be an issue for the use case that you're describing. 

Back to the use case in the topic. 

In general I don't consider it a good practice to import a type/interface/something, use it and then (re-)export it from that same file. That sounds like some real spaghetti code.

Here's what I consider a better way of structuring your code, with emphasis on types.

If you have a folder per React component, you could have one file `/components/MyComponent/types.ts` within that folder for types, where you declare and export types (and nothing more) that are only relevant to that specific component. 
If the components are simple, you may not want to dedicate an entire folder for it, and decide only to have it in a file `/components/MyComponent.tsx`. In that case you may have your "types" file in `/components/types.ts` and have all your different components' types within that single types file. 
If the types are more generic, move them to another types file, one or more levels up, in the folder hierarchy, until on a level where all the relevant parts of your app is able to import and access it. 
Lastly if types.ts turns to big and you need to abstract it even further you can turn the types.ts file into a folder and break it out into multiple files `/types/SomeKindOfTypes.ts`, which again may or may not be wired up in a `/types/index.ts` file (up to you).

This way of organizing your types is of course not tied to React, but can be used for all purposes:

**root/src/utils/types.ts:**

```
export interface InterfaceA {}
export interface InterfaceB {}
```

**root/src/utils/index.ts:**

```
export {
  InterfaceA,
  InterfaceB,
} from './types';
```

**root/index.ts:**

```
export {
  InterfaceA,
  InterfaceB,
} from './src/utils';
```

**Comment by klimashkin** [comment] 2018-11-13 06:52
@sorenhoyer but `root/src/utils/index.ts` might want to use interfaces from `root/src/utils/types.ts` before reexporting them. Otherwise why would they need to be declared under that folder?

**Comment by klimashkin** [comment] 2018-11-13 18:49
@dfreeman Can I somehow reexport `enum` like in your example?
```
import * as FileA from './file-a';
export type ExportedInterface = FileA.ExportedInterface;

export function test(): ExportedInterface {
  return { value: '1' };
}
```

**Comment by ColCh** [comment] 2018-12-25 20:41
@tajo and other interested

for this source file with reexport

```tsx
export { greet } from './Hello';

import * as HelloModule from './Hello';
export type GreetArgs = HelloModule.GreetArgs;
alert('REEXPORT');
```

such file is generated

```js
webpackHotUpdate("main",{

/***/ "./src/Greet-reexport.ts":
/*!*******************************!*\
  !*** ./src/Greet-reexport.ts ***!
  \*******************************/
/*! exports provided: greet */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var _Hello__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./Hello */ "./src/Hello.ts");
/* harmony reexport (safe) */ __webpack_require__.d(__webpack_exports__, "greet", function() { return _Hello__WEBPACK_IMPORTED_MODULE_0__["greet"]; });


alert('REEXPORT');

/***/ })

})
//# sourceMappingURL=main.fa092eff35ed08dde4dd.hot-update.js.map
```

it seems that babel completely stripped it from the source

I event can't find `GreetArgs` in the JS bundle file nor imported module (`import * as FooModule`)

tested on newly created project with CRA

Yup, this is a hack, but we can refactor our code later to remove type reexports

**Comment by axross** [comment] 2019-02-20 06:32
What we talked about here is just hacks....

**Comment by jackmellis** [comment] 2019-03-04 09:50
This is 100% preventing us from using the typescript preset, we really need a solution here.

We're also trying to use this with rollup and as a result rollup is getting really quite cross with non-existent imports.

**Comment by milesj** [comment] 2019-03-04 18:33
@jackmellis It will never be fixed unless Babel relies on TS' compiler, which I doubt will happen. You'll simply have to change how you import/export. For example.

```
// types.ts
export Foo = string;
export Bar = number;

// index.ts
export * from './types';
```

```
// Foo.ts
export interface FooOptions {}

export default Foo<FooOptions> {}

// index.ts
export * from './Foo';
export { default as Foo } from './Foo';
```

The trick is to use `export *` since it's dynamic.

**Comment by nicolo-ribaudo** [comment] 2019-03-04 19:01
Our goal is match typescript's `--isolatedModules` option, so this is working as intended. Babel doesn't have multi-file support and it isn't possible to properly implement with the current architecture.

**Comment by jackmellis** [comment] 2019-03-04 20:17
This is a real shame, if we won’t/can’t fix this I’ll have to go back to other, less ideal methods.

**Comment by ndelangen** [comment] 2019-04-27 18:41
So this is maybe a dumb idea, but I figure I bring it up regardless.

What if instead of removing the exports of types, we leave them in the output, but their value is `undefined`?

**Comment by ndelangen** [comment] 2019-05-06 12:11
I'd like to give this above suggestion a try myself, is there anyone who would be able to assist me?

**Comment by ndelangen** [comment] 2019-05-17 23:40
@nicolo-ribaudo did you perhaps consider my suggestion?

**Comment by hbroer** [comment] 2019-05-19 14:35
looks like i can't use babel for transpiling typescript. ^^ 

```
export {IMyService} from "./my-service";
export {IMyOtherService} from "./my-other-service";
```
results in 
```
WARNING in ./src/services/index.ts 5:0-53
"export 'IMyOtherService' was not found in './my-other-service'
[...]
WARNING in ./src/services/index.ts 4:0-42
"export 'IMyService' was not found in './my-service'
[...]
```

The only way to work around this would be to move the interfaces to the index file. And i think we should not need to talk about that solution. ^^ The re-exports in that index file are there to simplify imports and to make more clear that someone imports the class (which is not listet in the index) and not the inferface, what is restricted. (DI)

A real solution would be, because babel gives a shit on type checking, that babel removes the types before parsing the imports. Babel does not need the types, but i do, and tsc does too:

```
import {IMyService} from "services";

class MyServiceMock implements IMyService {}
```
should get 
```
class MyServiceMock {}
```

This can be done if you restrict implementing from a class. Give me a `implementOnlyFromInterface` flag and i am fine. Btw. this should be the default behavior: only interfaces should be implemented.  This is ment for project typescript sources, not its external dependencies.

**Comment by Retsam** [comment] 2019-05-20 14:59
@hbroer I'm not sure you understand the problem.  Your last example is already how babel works: any imports that aren't used outside of type annotations (e.g. `implements`) are removed.  

The issue is code like this:

```ts
export { Foo } from "foo";
```

Since babel operates on a per-file basis, there's no way for it to determine whether `Foo` is a type or a value.  So yes, everyone agrees that "babel removes the types before parsing the imports" as you say, but there's seemingly no easy way to handle this problem.

**Comment by hbroer** [comment] 2019-05-20 18:08
Yes i think i got it. Babel ist mit the tool i can work with and i need to stay with tsc. That was a short experiment for me ;)

**Comment by gavar** [comment] 2019-09-30 23:35
having file like, works well:
```ts
export interface Interface {}
export {}
```

`export {}` tricks babel as if it was exporting something.
I'm wondering how to do that automatically as part of plugin.

**Comment by tajo** [comment] 2019-10-01 00:40
@gavar Oh, that's a neat workaround. Should be pretty straightforward to add this into the ts plugin.

**Comment by drewlustro** [comment] 2019-10-01 00:47
Yeah, that is pretty neat @gavar. Silly me wrote a codemod to transform everything to `export type ...`

**Comment by gavar** [comment] 2019-10-01 13:16
I've made a very simple plugin for that, it doesn't have it's own module, but feel free to copy.

https://github.com/gavar/webpackery/blob/master/registry/babel-configurer/src/inject-empty-exports.ts

```ts
import { NodePath, PluginObj } from "@babel/core";
import { TemplateBuilder } from "@babel/template";
import { ExportDeclaration, ExportNamedDeclaration, Program, Statement } from "@babel/types";

interface Babel {
  template: TemplateBuilder<Statement>;
}

interface State {
  filename: string;
}

/**
 * Adds stub `export { }` when module does not have any actual exports.
 */
export function InjectEmptyExports(babel: Babel): PluginObj<State> {
  const stub = babel.template("export { }")();
  return {
    visitor: {
      Program(root: NodePath<Program>, state: State) {
        const filename = state.filename.split("\\").join("/");
        if (filename.endsWith(".d.ts")) return;
        if (filename.includes("/node_modules/")) return;

        // check if any node is actual export declaration
        let empty = true;
        root.traverse({
          ExportDeclaration(path: NodePath<ExportDeclaration>) {
            if (empty)
              empty = isTypeDeclaration(path.node);
          },
        });

        // add empty exports definition
        if (empty)
          root.node.body.push(stub);
      },
    },
  };
}

function isTypeDeclaration(node: ExportDeclaration) {
  if (node.type === "ExportNamedDeclaration")
    switch (node.declaration.type) {
      case "TSTypeAliasDeclaration":
      case "TSInterfaceDeclaration":
        return true;
    }
}
```

**Comment by craigkovatch** [comment] 2019-10-30 00:15
I am facing a somewhat opposite issue trying to get React Styleguidist with `react-docgen-typescript` and `react-scripts` to *ignore* exported interfaces, because I get a bunch of errors like this: `Attempted import error: 'ButtonProps' is not exported from './components/Button/Button'.`

Apologies for the tangent of a comment, but I want to leave a breadcrumb here for anyone else who comes here while googling with this issue. The trick of using e.g. `export * from './components/Button/Button` worked for me. And specifically I created a parallel entry point just for Styleguidist so that it wouldn't mess with my actual library exports.

**Comment by drcmda** [comment] 2020-01-23 09:32
Here's another solution that neither needs a plugin nor export *, which for us wasn't feasible:

before

```jsx
export { BuerliState } from './store/states/buerli'
```

after

```jsx
import { BuerliState as BS } from './store/states/buerli'
export type BuerliState = BS
```

**Comment by sebinsua** [comment] 2020-01-23 13:05
It looks like the real fix will be using ["type-only imports and exports"](https://devblogs.microsoft.com/typescript/announcing-typescript-3-8-beta/#type-only-imports-exports) in the next version of TypeScript (3.8).

However, that won't stop people from accidentally importing types using normal imports and exports and potentially breaking a build output transpiled with Babel.

I wish there was a way of switching off the ability to import and export types using normal JavaScript syntax? /cc @DanielRosenwasser 

If there can't be a `tsconfig.json` option perhaps a Lint rule could be written.

**Comment by vkrol** [comment] 2020-01-23 13:31
@sebinsua 
> I wish there was a way of switching off the ability to import and export types using normal JavaScript syntax?

See `importsNotUsedAsValues` option https://devblogs.microsoft.com/typescript/announcing-typescript-3-8-beta/#type-only-imports-exports.

**Comment by nicolo-ribaudo** [comment] 2020-01-24 21:55
This will be fixed in the next minor version: you will be able to use `export type { Interface }`.

**Comment by benmvp** [comment] 2020-03-04 01:49
> This will be fixed in the next minor version: you will be able to use `export type { Interface }`.

@nicolo-ribaudo has that minor version been released?

**Comment by nicolo-ribaudo** [comment] 2020-03-04 09:13
Not yet. You can watch https://github.com/babel/babel/pull/11171 to ge notified when it's released.

**Comment by benmvp** [comment] 2020-03-05 03:31
> Not yet. You can watch #11171 to ge notified when it's released.

That would explain things. Thanks so much!

**Closed** 2020-03-16 21:58 UTC
Labels: area: typescript
