### ISSUE TITLE
Destructuring a property and assigning it to a local variable does break when inlined in an if-statement

### ISSUE THREAD

**Issue by ca057** [babel/babel#7852] opened 2018-05-02 06:38 UTC
**Describe the bug**
Destructuring a property from an object and assigning the property to a local variable with the same name does not work when inlined in an if-statement, but only when surrounded by curly braces.

**Input Code**

We used the following code for a long time without any errors, but since the update to the latest react native version this code does not compile anymore:
```js
const foo = {
	bar: 10,
}

let bar = 0;

if (foo) ({ bar } = foo); // throws an error (see stacktrace below)

console.log(bar); // should print 10
```

This can easily be fixed by surrounding the desctructuring/assignment with curly braces:
```js
const foo = {
	bar: 10,
}

let bar = 0;

if (foo) {
  ({ bar } = foo);
}

console.log(bar); // prints 10 
```

Is this intended, as the previously used syntax is not valid or is this a bug?

### Babel Configuration (.babelrc, package.json, cli command)

The project is a React Native project, the bundling process is started with `node node_modules/react-native/local-cli/cli.js start`. In addition to the configuration of React Native (v0.55.3), we use the following local babel configuration:

```js
{
  "plugins": [
    ["module-resolver", { "root": ["./src"] }],
    "idx"
  ],
  "presets": ["react-native"]
}
```

**Expected behavior/code**
The code should get compiled without any errors.

**Environment**
- Babel version(s): The babel-generator mentioned in the stack trace is version 6.26.1
- Node/npm version: Node v10.0.0/npm 5.8.0
- OS: OSX 10.13.4
- Monorepo: yes
- How you are using Babel: [e.g. `cli`, `register`, `loader`]

**Additional context/Screenshots**

The stack trace:
```
error: bundling failed: TypeError: Cannot read property 'type' of null
    at find (path/to/my/app/node_modules/babel-generator/lib/node/index.js:92:21)
    at needsWhitespace (path/to/my/app/node_modules/babel-generator/lib/node/index.js:115:19)
    at needsWhitespaceBefore (path/to/my/app/node_modules/babel-generator/lib/node/index.js:131:10)
    at Generator._printNewline (path/to/my/app/node_modules/babel-generator/lib/printer.js:467:11)
    at Generator.printJoin (path/to/my/app/node_modules/babel-generator/lib/printer.js:364:32)
    at Generator.printSequence (path/to/my/app/node_modules/babel-generator/lib/printer.js:420:17)
    at Generator.BlockStatement (path/to/my/app/node_modules/babel-generator/lib/generators/base.js:43:10)
    at path/to/my/app/node_modules/babel-generator/lib/printer.js:298:23
    at Buffer.withSource (path/to/my/app/node_modules/babel-generator/lib/buffer.js:168:5)
```

**Comment by existentialism** [comment] 2018-05-03 01:48
@ca057 thanks for the issue report! I couldn't reproduce this locally with both a vanilla babel project with your config or a (admittedly contrived) react-native project.

Any chance you can create a small repo that reproduces the problem?

**Comment by ca057** [comment] 2018-05-03 06:45
Hey @existentialism ,

yes - I was able to create a repo reproducing the problem (should have done that from the beginning - sorry):

You can find the working code with the old React Native version (and its babel dependencies) on the [master branch](https://github.com/ca057/babel7852/tree/master) and the "broken" code after the upgrade to the newest React Native version on the ["broken-update" branch](https://github.com/ca057/babel7852/tree/broken-update).

**Comment by ca057** [comment] 2018-05-03 07:12
I made a short test: The additional babel configuration we use in our repo does not influence the issue described above. That means: A raw React Native project should be enough to reproduce the issue (working with react-native v0.51.0, broken with react-native v0.55.0).

I set up two new branches for the test, you can find them here:
* [working master, raw react-native project without additional babel configuration](https://github.com/ca057/babel7852/tree/master-without-additional-babelrc)
* [broken branch with react-native updated, raw project without additional babel configuration](https://github.com/ca057/babel7852/tree/broken-update-without-additional-babelrc)

**Comment by liuxingbaoyu** [comment] 2023-11-11 13:48
Because this issue is out of date, I will close it.

**Closed by liuxingbaoyu** 2023-11-11 13:48 UTC
