### ISSUE TITLE
tranforming of object

### ISSUE THREAD

**Issue by bonegollira** [babel/babel#824] opened 2015-02-18 15:27 UTC
hi.

Thank you for using bebel. I have a question.
After I used bable, my code changed from

```
var obj = {
  // key wrapped '
  'key': "value"
};
```

to

```
var obj = {
  // ' is rejected
  key: "value"
};
```

Almost all transform is ok.
But to change from `'key'` to `key` is not ok for me.
I want the result to be `'key' -> 'key'`, so I want to keep `'key'` as it.
In order to do it, what I should do?

**Comment by sebmck** [comment] 2015-02-18 21:22
Duplicate of #821, blacklist the `es3.propertyLiterals` transformer.

**Closed by sebmck** 2015-02-18 21:22 UTC
