### ISSUE TITLE
Use useBuiltIns: usage cause white screen in ios9.3

### ISSUE THREAD

**Issue by Chang1ng** [babel/babel#10340] opened 2019-08-15 06:43 UTC
## Bug Report

**Current Behavior**
I use the "useBuiltIns": "usage" option in .babelrc file.But cause white screen in ios9.3 version,but ios10+ version is normal.

**Input Code**
- My config is :

```js
{
  "presets": [
      [
          "@babel/preset-env",
          {
              "modules": false,
              "targets": {
                  "browsers": [
                      "iOS >= 9.3",
                      "android >= 67"
                  ]
              },
              "useBuiltIns": "usage",
              "corejs": 3,
              // "exclude": ["es.promise"],
          }
      ]
  ],
  "plugins": [
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-syntax-import-meta",
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-proposal-json-strings",
    [
        "@babel/plugin-proposal-decorators",
        {
            "legacy": true
        }
    ],
    "@babel/plugin-proposal-function-sent",
    "@babel/plugin-proposal-export-namespace-from",
    "@babel/plugin-proposal-numeric-separator",
    "@babel/plugin-proposal-throw-expressions",
  ]
}

```

**Expected behavior/code**
I  want to use the usage option, it can reduce the file size.

**Babel Configuration (.babelrc)**

```js
"presets": [
      [
          "@babel/preset-env",
          {
              "modules": false,
              "targets": {
                  "browsers": [
                      "iOS >= 9.3",
                      "android >= 67"
                  ]
              },
              "useBuiltIns": "usage",
              "corejs": 3,
              // "exclude": ["es.promise"],
          }
      ]
]
```

**Environment**
- Babel version(s): [7.4.5]
- Node/npm version: [Node 8.12.0/npm 6.4.1]
- OS: [e.g. IOS9.3]
- How you are using Babel: [`webpack/babel-loader`]

**Possible Solution**
Use `useBuiltIns:entry` instead of `usage`

**Additional context/Screenshots**
Maybe is 'es.promise' cause this, because i add config: `"exclude": ["es.promise"]`, this ios9.3 is normal.

**Comment by nicolo-ribaudo** [comment] 2019-08-15 06:49
This is probably a duplicate of https://github.com/zloirock/core-js/issues/615

Could you ensure that `core-js` in your dependencies is 3.2.1?

**Comment by Chang1ng** [comment] 2019-08-15 07:58
> This is probably a duplicate of [zloirock/core-js#615](https://github.com/zloirock/core-js/issues/615)
> 
> Could you ensure that `core-js` in your dependencies is 3.2.1?

"core-js": "3.1.4",

**Comment by nicolo-ribaudo** [comment] 2019-08-15 08:18
Try updating it to 3.2.1

**Comment by Chang1ng** [comment] 2019-08-15 08:52
> Try updating it to 3.2.1

I tried it, No way.
I use 'usage' option in other two projects is normal. It was so strange. 
![image](https://user-images.githubusercontent.com/6593784/63084085-f5ab3980-bf7c-11e9-8cec-bf8fb40f6418.png)

**Comment by JLHwung** [comment] 2019-09-03 23:03
Could you attach the error stack trace?

**Comment by nicolo-ribaudo** [comment] 2021-02-01 02:04
I'm closing this issue, since
1. it seems caused by `core-js`
2. without a stack trace it's impossible to understand what's going on

**Closed by nicolo-ribaudo** 2021-02-01 02:04 UTC
Labels: i: bug, i: needs triage
