### ISSUE TITLE
babel-preset-es2015 generating failing code for es6 mixin

### ISSUE THREAD

**Issue by nikosandronikos** [babel/babel#5285] opened 2017-02-09 10:21 UTC
### Input Code
See https://github.com/nikosandronikos/babel-issue for a minimal test case

The following construct results in class `A` having no methods on it's prototype when built with babel-preset-es2015.
```js
const MixinName = superclass => class extends superclass {
	constructor() {
		super();
		this.name = 'Zorg';
	}

	getName() {
		return this.name;
	}
}

class A extends MixinName(Object) {
	constructor() {
		super();
	}

	setName(n) {
		this.name = n;
	}
}

const a = new A();
console.log(`Hi ${a.name}.`);
console.log(`Bye ${a.getName()}.`);
```

### Babel Configuration (.babelrc, package.json, cli command)
No .babelrc.
package.json and other configuration available at repository linked above.

### Expected Behavior
The following output is expected:
```
Hi Zorg.
Bye Zorg.
```

### Current Behavior
Actual output observed is:
```
Hi Zorg.
/Users/nikos/code/babel-issue/build/main.js:56
console.log('Bye ' + a.getName() + '.');
                       ^

TypeError: a.getName is not a function
    at Object.<anonymous> (/Users/nikos/code/babel-issue/build/main.js:56:24)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:449:3

```

### Possible Solution
I've only been playing with Babel for a couple of days so I may be way off, but it looks to me like the issue is with the `_inherits(_class, _superclass);` line of the MixinName definition.
Changing this to `_inherits(MixinName, _superclass);` appears to solve the issue.

### Context
Trying to use a nice method of defining mixins that is available in ES6.

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  3.8.9
| node             | 6.2.0
| npm              | 3.8.9
| Operating System | Reproducible on Mac OS, Win 7, and Win 10

**Comment by nicolo-ribaudo** [comment] 2017-09-10 12:30
The problem is that you pass `Object` to the mixin, and Babel doesn't support extending primitives. To get the same behavior, you can use `MixinName(class {})`.

I'm closing this as a duplicate of #4480

**Closed by nicolo-ribaudo** 2017-09-10 12:30 UTC
