### ISSUE TITLE
The transform-runtime plugin doesn't handle classes

### ISSUE THREAD

**Issue by jkroso** [babel/babel#2860] opened 2015-11-06 02:56 UTC
```js
#! /usr/bin/env node
const babel = require('babel-core')

babel.transform('class A {}', {
  presets: [
    require('babel-preset-es2015')
  ],
  plugins: [
    require('babel-plugin-transform-runtime')
  ]
})
```

Generates this error:

```
TypeError: unknown: Property callee of CallExpression expected node to be of a type ["Expression"] but instead got null
    at Object.validate (/Users/jkroso/Projects/js/6-5/node_modules/babel-types/lib/definitions/index.js:97:13)
    at validate (/Users/jkroso/Projects/js/6-5/node_modules/babel-types/lib/index.js:267:9)
    at Object.builder (/Users/jkroso/Projects/js/6-5/node_modules/babel-types/lib/index.js:243:7)
    at PluginPass.exit (/Users/jkroso/Projects/js/6-5/node_modules/babel-plugin-transform-es2015-modules-commonjs/lib/index.js:401:98)
    at newFn (/Users/jkroso/Projects/js/6-5/node_modules/babel-traverse/lib/visitors.js:233:27)
    at NodePath._call (/Users/jkroso/Projects/js/6-5/node_modules/babel-traverse/lib/path/context.js:72:18)
    at NodePath.call (/Users/jkroso/Projects/js/6-5/node_modules/babel-traverse/lib/path/context.js:44:17)
    at NodePath.visit (/Users/jkroso/Projects/js/6-5/node_modules/babel-traverse/lib/path/context.js:108:8)
    at TraversalContext.visitQueue (/Users/jkroso/Projects/js/6-5/node_modules/babel-traverse/lib/context.js:151:16)
    at TraversalContext.visitSingle (/Users/jkroso/Projects/js/6-5/node_modules/babel-traverse/lib/context.js:111:19)
```

**Comment by hzoo** [comment] 2015-11-06 03:04
Hmm I cannot reproduce? Maybe check your versions, or try babel-doctor

**Comment by jkroso** [comment] 2015-11-06 03:59
Oh yea I was running version `6.1.2` of the transform and `6.0.14` of babel-core. After bringing them both up to `6.1.2` it worked. Thanks for looking at it

**Comment by hzoo** [comment] 2015-11-06 04:07
Ok cool closing then

**Closed by hzoo** 2015-11-06 04:07 UTC
