### ISSUE TITLE
@babel/parser es6

### ISSUE THREAD

**Issue by elgs** [babel/babel#14426] opened 2022-04-06 06:25 UTC
### 💻

- [ ] Would you like to work on this feature?

### What problem are you trying to solve?

I want to use @babel/parser in Deno or browser without any build tools.

### Describe the solution you'd like

Provide ES6 version of @babel/parser.

### Describe alternatives you've considered

No.

**Comment by nicolo-ribaudo** [comment] 2022-04-06 08:38
`@babel/parser` is currently fully es6 compatible.

I'm assuming that you are asking for an ESM version (ECMAScript Modules), as opposed to the current CJS one (CommonJS modules). In that case, this is a duplicate of #11701 and it will be fixed in Babel 8!

**Comment by nicolo-ribaudo** [comment] 2022-04-06 08:39
Duplicate of #11701

**Closed by nicolo-ribaudo** 2022-04-06 08:38 UTC
Labels: i: enhancement, i: needs triage

**Comment by elgs** [comment] 2022-04-06 08:51
Thank you thank you thank you @nicolo-ribaudo! I am very excited to know that we will see it in a specific version.

I want to be able to run Javascript in browsers without any build tools. Build tools like Webpack should only do fancy things like tree shaking or minification (is this a word?). It should never be a dependency without which my project won't run, in my opinion.
