### ISSUE TITLE
Extending from Error behaves differently from other base classes

### ISSUE THREAD

**Issue by ianwremmel** [babel/babel#5524] opened 2017-03-22 17:25 UTC
### Input Code
```js
function assert(holds, message) {
  if (!holds) {
    throw new Error(message || `Assertion does not hold`);
  }
}

class A {}
class FromA extends A {
  constructor(...args) {
    super(...args)
    assert(this.constructor.name === `FromA`, `the constructor of FromA should be "FromA" and is ${this.constructor.name}`);
  }
}

class FromError extends Error {
  constructor(...args) {
    super(...args)
    assert(this.constructor.name === `FromError`, `the constructor of FromError should be "FromError" and is ${this.constructor.name}`);
  }
}

const a = new FromA();
const e = new FromError();
```
[REPL Link](
https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015&targets=&browsers=&builtIns=false&code=function%20assert(holds%2C%20message)%20%7B%0A%20%20if%20(!holds)%20%7B%0A%20%20%20%20throw%20new%20Error(message%20%7C%7C%20%60Assertion%20does%20not%20hold%60)%3B%0A%20%20%7D%0A%7D%0A%0Aclass%20A%20%7B%7D%0Aclass%20FromA%20extends%20A%20%7B%0A%20%20constructor(...args)%20%7B%0A%20%20%20%20super(...args)%0A%20%20%20%20assert(this.constructor.name%20%3D%3D%3D%20%60FromA%60%2C%20%60the%20constructor%20of%20FromA%20should%20be%20%22FromA%22%20and%20is%20%24%7Bthis.constructor.name%7D%60)%3B%0A%20%20%7D%0A%7D%0A%0Aclass%20FromError%20extends%20Error%20%7B%0A%20%20constructor(...args)%20%7B%0A%20%20%20%20super(...args)%0A%20%20%20%20assert(this.constructor.name%20%3D%3D%3D%20%60FromError%60%2C%20%60the%20constructor%20of%20FromError%20should%20be%20%22FromError%22%20and%20is%20%24%7Bthis.constructor.name%7D%60)%3B%0A%20%20%7D%0A%7D%0A%0Aconst%20a%20%3D%20new%20FromA()%3B%0Aconst%20e%20%3D%20new%20FromError()%3B)

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [
    "es2015"
  ]
}
```

### Expected Behavior
When extending from `Error`, the new class's `this.constructor.name` should be the new class's name.

### Current Behavior
When extending from `Error`, the new class's `this.constructor.name` is `Error`

### Context
I'm currently using https://github.com/ianwremmel/extend-error (which has its own set of issues) to create subclassed Errors. Stringifying with the error name is very helpful for a debug process (in particular, subclassing for each http response code). In order to make that work, something like

```js
class Exception extends Error {
  constructor(...args) {
    super(...args)
    this.name = `Exception`
  }
}
console.log(new Exception(`blarg`));
```
will produce `[Exception: blarg]`. Ideally, I would be able to use `this.name = this.constructor.name` instead of `this.name = \`Exception\``.

### Your Environment
I've mostly been debugging this in the repl, but my local environment is:

| software         | version
| ---------------- | -------
| Babel            |  6.22.1
| node             | 7.2.0
| npm              | 3.10.9
| Operating System | macOs Sierra

**Comment by loganfsmyth** [comment] 2017-03-22 17:29
Seems like a duplicate of https://github.com/babel/babel/issues/5496, https://github.com/babel/babel/issues/5284, and many others.

Have you explored the plugin mentioned in https://babeljs.io/docs/usage/caveats/#classes ?

**Comment by ianwremmel** [comment] 2017-03-22 17:34
thanks for responding so quickly! i thought i did all the proper research before opening this, but clearly I haven't had enough coffee yet. https://github.com/loganfsmyth/babel-plugin-transform-builtin-extend looks like it'll do exactly what I need.

**Closed** 2017-03-22 17:38 UTC
