### ISSUE TITLE
[babelrc][babel-node][plugin] Local plugin breaks babel-node (babelRelayPlugin)

### ISSUE THREAD

**Issue by BerndWessels** [babel/babel#2529] opened 2015-10-13 01:23 UTC
Hello
It seems that having a local plugin in the `.babelrc` breaks babel-node.

This is my `.babelrc` file:

    {
      "stage": 0,
      "env": {
        "development": {
          "plugins": ["./build/babelRelayPlugin", "react-transform"],
          "sourceMaps": "inline",
          "optional": [
              "runtime",
              "es7.decorators",
              "es7.classProperties"
            ],
          "extra": {
            "react-transform": {
              "transforms": [{
                "transform": "react-transform-hmr",
                "imports": ["react"],
                "locals": ["module"]
              }, {
                "transform": "react-transform-catch-errors",
                "imports": ["react", "redbox-react"]
              }]
            }
          }
        }
      }
    }

And this is my local `./build/babelRelayPlugin`:

    var getbabelRelayPlugin = require('babel-relay-plugin');
    var schema = require('../data/schema.json');

    module.exports = getbabelRelayPlugin(schema.data);

This results in the following error:

    > babel-node ./devServer.js
    
    C:\Users\bwessels.SPENDV\Documents\WebstormProjects\react-transform-boilerplate\node_modules\babel-core\lib\transformation\file\plugin-manager.js:164
          throw new TypeError(messages.get("pluginNotTransformer", name));
          ^
    
    TypeError: The plugin "./build/babelRelayPlugin.js" didn't export a Plugin instance
        at PluginManager.validate (C:\Users\bwessels.SPENDV\Documents\WebstormProjects\react-transform-boilerplate\node_modules\babel-core\lib\transformation\file\plugin-manager.js:164:13)
        at PluginManager.add (C:\Users\bwessels.SPENDV\Documents\WebstormProjects\react-transform-boilerplate\node_modules\babel-core\lib\transformation\file\plugin-manager.js:213:10)
        at File.buildTransformers (C:\Users\bwessels.SPENDV\Documents\WebstormProjects\react-transform-boilerplate\node_modules\babel-core\lib\transformation\file\index.js:237:21)
        at new File (C:\Users\bwessels.SPENDV\Documents\WebstormProjects\react-transform-boilerplate\node_modules\babel-core\lib\transformation\file\index.js:139:10)
        at Pipeline.transform (C:\Users\bwessels.SPENDV\Documents\WebstormProjects\react-transform-boilerplate\node_modules\babel-core\lib\transformation\pipeline.js:164:16)
        at Object.transformFileSync (C:\Users\bwessels.SPENDV\Documents\WebstormProjects\react-transform-boilerplate\node_modules\babel-core\lib\api\node.js:137:37)
        at compile (C:\Users\bwessels.SPENDV\Documents\WebstormProjects\react-transform-boilerplate\node_modules\babel-core\lib\api\register\node.js:132:20)
        at normalLoader (C:\Users\bwessels.SPENDV\Documents\WebstormProjects\react-transform-boilerplate\node_modules\babel-core\lib\api\register\node.js:199:14)
        at Object.require.extensions.(anonymous function) [as .js] (C:\Users\bwessels.SPENDV\Documents\WebstormProjects\react-transform-boilerplate\node_modules\babel-core\lib\api\register\node.js:216:7)
        at Module.load (module.js:355:32)

The only way I found to fix this is moving my local `babel-relay-plugin` into the `node_modules` folder and make it like being a complete package. That works but I would rather be able to use local plugins in my `.babelrc` file.

Any ideas how to fix this?

Thank you
Bernd

**Comment by sebmck** [comment] 2015-10-13 01:25
Duplicate of #2443.

**Closed by sebmck** 2015-10-13 01:25 UTC

**Comment by BerndWessels** [comment] 2015-10-13 01:27
Hi @sebmck
I feel really stupid, but I don't see what the fix in #2443 is.
Can you explain the fix here - I believe lots of people might run into this problem.
Thank you
Bernd

**Comment by jmm** [comment] 2015-10-13 02:10
@BerndWessels It hasn't been fixed yet. #2443 is an open issue that's tracking it. If it does get fixed it'll probably be in v6.

**Comment by BerndWessels** [comment] 2015-10-13 02:13
OK, thank you.

**Comment by BerndWessels** [comment] 2015-10-13 19:48
Until this issue is fixed you can use this [babel-relay-plugin-loader](https://github.com/BerndWessels/babel-relay-plugin-loader) I made to get around this particular problem.

Cheers
Bernd
