### ISSUE TITLE
async-to-generator loses `super` inside generator

### ISSUE THREAD

**Issue by leebenson** [babel/babel#4533] opened 2016-09-20 13:12 UTC
**Config:**

```
{
  "presets": [
    "node6",
    "stage-1"
  ],
  "plugins": [
    "babel-plugin-transform-async-to-generator",
    "babel-plugin-syntax-async-functions"
  ]
}
```

**Code:**

```js
class A {
  log() {
    return new Promise(resolve => {
      setTimeout(function () {
        console.log('should print after 1 second');
        resolve();
      }, 1000);
    });
  }
}

class B extends A {
  async log() {
    await super.log();
  }
}

const b = new B;
b.log();
```

**Expected:**

Should dump `should print after 1 second` to screen

**Actual:**

> yield super.log();
            ^^^^^
SyntaxError: 'super' keyword unexpected here

**Issue:**

The issue is that an `await` statement is wrapped like this...

```js
let B = class B extends A {
  log() {
    return _asyncToGenerator(function* () {
      yield super.log(); // <--- `super` loses its context
    })();
  }
};
```

This fixes it:

```js
let B = class B extends A {
  log() {
    const fn = super.log.bind(this);
    return _asyncToGenerator(function*() {
      yield fn.call();
    })();
  }
};
```

**Comment by loganfsmyth** [comment] 2016-09-24 05:02
Definitely a bug. Duplicate of https://github.com/babel/babel/issues/3930

**Closed by loganfsmyth** 2016-09-24 05:02 UTC
