### ISSUE TITLE
[typescript] can't parse async arrow function has Promise.all

### ISSUE THREAD

**Issue by tsulatsitamim** [babel/babel#9688] opened 2019-03-15 03:57 UTC
## Bug Report

**Current Behavior**
I have an anonymous generic async arrow function which contain Prmose.all, it work fine when try to compile using tsc but fail using babel. Probably related to #9086 . I try to create REPL bellow.

**Input Code**
- [REPL](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBAhjAvPCBPMwYB4AqA-ACgBM4o4AuGHASkoAUAnEAWwEsIBTXPJHxl9hwB0DDhBAAbAG4dipONQBQoSLABGSFOkzc5ZSjgDaAXVox-bTrhM9EPAN6KYMFdBgAPTXADucVrAtBITgJCQInZxgSMiFmOAAHAk87cyZLYVFxaVl3amoAbgilZ1EoAFcGMA9FAF9FDnd4kAZYV1avNAxsfD0KKjNAq3xeVIFOETFJGV7qIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=typescript&prettier=false&targets=&version=7.3.4)

It need plugin tranform typescript

```js
const a = async <T>(data: T): Promise<T> => Promise.resolve(data)
const b = async <T>(data: T[]): Promise<T[]> => {
  const x = await Promise.all(
    data.map(x => Promise.resolve(x));
  )
  return x
}
export const c = async <T>(data: T): Promise<T> => Promise.resolve(data)
```

it will compile if I comment c function

**Expected behavior/code**
It works with tsc so it should work with babel too.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
 {
  "presets": [
    ["@babel/env", {
      "targets": {
        "node": true
      }
    }],
    "@babel/typescript"
  ],
  "plugins": [
    ["module-resolver", {
      "root": ["./src"],
      "alias": {
        "@": "./src"
      },
      "extensions": [".js", ".ts", ".tsx"]
    }],
    "@babel/proposal-class-properties",
    "@babel/proposal-object-rest-spread"
  ]
}
}
```

**Environment**
- Babel version(s): v7.3.4
- Node/npm version: node v10.15.1 / npm 6.4.1
- OS: v10.15.1
- Monorepo: yes
- How you are using Babel: cli

**Possible Solution**
Probably related to #9086 

this is my first issue report in my history, i'm sorry if i made any mistake.

**Comment by nicolo-ribaudo** [comment] 2019-03-15 06:23
This is a duplicate of https://github.com/babel/babel/issues/9560. It will be fixed in the next release 😉

**Closed by nicolo-ribaudo** 2019-03-15 06:23 UTC
Labels: i: bug, i: needs triage
