### ISSUE TITLE
Trampolining? Can cause invalid js expecting block scopes to be hoisted

### ISSUE THREAD

**Issue by togakangaroo** [babel/babel#2433] opened 2015-09-26 18:13 UTC
I have the following options blacklisted

	    "blacklist": [
	      'regenerator',
	      'es6.constants',
	      'es6.forOf',
	    ]

Specifically - since I'm using chrome, no need to transform the supported const keyword.

I wrote a function that looks like this:

	const getValue = (model, propertyPath) => {
		if(!propertyPath || propertyPath == '*')
			return model
		if(_.isUndefined(model) || model === null)
			return model //No such model, should this be an error?
		if(model.hasOwnProperty(propertyPath))
			return model[propertyPath]
		const [head, ...tail] = (propertyPath||'').split('.')
		if(!head)
			return undefined; //Property does not exist, Maybe should be an error? 
		return getValue(model[head], tail.join('.'))
	}

which compiles into

				const getValue = function getValue(_x8, _x9) {
					var _again = true;

					_function: while (_again) {
						var model = _x8,
						    propertyPath = _x9;
						_split = _split2 = head = tail = undefined;
						_again = false;

						if (!propertyPath || propertyPath == '*') return model;
						if (_.isUndefined(model) || model === null) return model; //No such model, should this be an error?
						if (model.hasOwnProperty(propertyPath)) return model[propertyPath];

						var _split = (propertyPath || '').split('.');

						var _split2 = _toArray(_split);

						const head = _split2[0];

						const tail = _split2.slice(1);

						if (!head) return undefined; //Property does not exist, Maybe should be an error?
						_x8 = model[head];
						_x9 = tail.join('.');
						_again = true;
						continue _function;
					}
				};

Note that at the top, we assign undefined to `tail` but it's only declared by `const` further down. Since `const` is block scoped this will break.

**Comment by sebmck** [comment] 2015-09-26 18:22
Duplicate of #2401.

**Closed by sebmck** 2015-09-26 18:22 UTC
