### ISSUE TITLE
path.hub.getScope is not a function

### ISSUE THREAD

**Issue by jacargentina** [babel/babel#8530] opened 2018-08-24 17:42 UTC
## Bug Report

I've just updated deps from 7.0.0-rc.1 to 7.0.0-rc.2

Now my react native app is not compiling its js.

```
Metro Bundler ready.

Loading dependency graph...
Loading dependency graph, done.
error: bundling failed: TypeError: path.hub.getScope is not a function
    at PluginPass.JSXOpeningElement (/Users/javiercastro/git/iResucito/node_modules/@babel/plugin-transform-react-jsx-source/lib/index.js:67:32)
    at newFn (/Users/javiercastro/git/iResucito/node_modules/@babel/traverse/lib/visitors.js:237:21)
    at NodePath._call (/Users/javiercastro/git/iResucito/node_modules/@babel/traverse/lib/path/context.js:65:20)
    at NodePath.call (/Users/javiercastro/git/iResucito/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/javiercastro/git/iResucito/node_modules/@babel/traverse/lib/path/context.js:100:12)
    at TraversalContext.visitQueue (/Users/javiercastro/git/iResucito/node_modules/@babel/traverse/lib/context.js:142:16)
    at TraversalContext.visitSingle (/Users/javiercastro/git/iResucito/node_modules/@babel/traverse/lib/context.js:102:19)
    at TraversalContext.visit (/Users/javiercastro/git/iResucito/node_modules/@babel/traverse/lib/context.js:182:19)
    at Function.traverse.node (/Users/javiercastro/git/iResucito/node_modules/@babel/traverse/lib/index.js:106:17)
```

**Comment by loganfsmyth** [comment] 2018-08-24 17:45
Most likely this is because at least some of the packages you're using are still rc.1 or older. Since you're on react-native, that's almost certainly the case, since RN itself is what's loading and calling `@babel/core`, so it would need to update to the newer RC for things to work.

**Comment by jacargentina** [comment] 2018-08-24 17:59
This are my updated deps. I've just removed node_modules, and npm install. No luck.

<img width="862" alt="captura de pantalla 2018-08-24 a la s 14 58 38" src="https://user-images.githubusercontent.com/517228/44599975-4e068b80-a7ae-11e8-9fc8-2ed99b9e929e.png">

**Comment by loganfsmyth** [comment] 2018-08-24 18:03
The issue is that Metro doesn't use the `@babel/core` you've installed, it uses the one it has in https://github.com/facebook/metro/blob/041c4eaa1977862c5db8bceeb5028f17bc2aa631/packages/metro/package.json#L16

**Comment by wliupier88** [comment] 2018-08-25 06:41
Same issue here. Any solutions for this issue?

**Comment by nicolo-ribaudo** [comment] 2018-08-25 10:02
If you are using yarn, you can set the version of the `@babel/core` used by your dependency using [`resolutions`](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) (:warning: Since beta versions can contain breaking changes, this might not work)

Otherwise you must use the same version used by your dependency.

**Comment by nicolo-ribaudo** [comment] 2018-08-28 12:44
This should be fixed by https://github.com/facebook/metro/pull/233

**Comment by AlexBrasileiro** [comment] 2018-09-04 22:05
Hey people, I have this issue for React Native on iOS (development) and after a lot of tests I fixed that way:

1) On **./node_modules/metro** I delete the folder _node_modules_ 

2) On package.json (on metro folder) I change `"@babel/core": "7.0.0-beta.56"` for  `"@babel/core": "7.0.0"`

3) `npm install` (on metro folder)

4) On projectFolder -> `rm -f .git/index.lock`

And the React Native on iOS Simulator with Metro and Live Reload works perfect again.

**Comment by nicolo-ribaudo** [comment] 2018-09-05 06:49
It will be fixed in the next metro version

**Closed** 2022-10-30 08:59 UTC
