### ISSUE TITLE
babel-node does not load config babel.config.json

### ISSUE THREAD

**Issue by ReFruity** [babel/babel#12843] opened 2021-02-21 23:43 UTC
## Bug Report

**Current behavior**

When I try to execute babel using `package.json` or `npx babel-node --config-file "./babel.config.json" src/server.js`, it does not load config. Even if config has syntax errors babel starts successfully.

Interestingly, if I start REPL via `npx babel-node` it loads only default config disregarding `--config-file` option entirely.

**Expected behavior**

Babel loads config file

**Babel Configuration**
- Filename: `babel.config.json`

```json
{
  "plugins": [
    [
      "module-resolver", {
        "root": ["./src"],
        "alias": {
          "services": "./services",
          "util": "./util"
        }
      }
    ]
  ]
}

```

**Environment**

- Babel version(s): 7.12.17 (core), 7.12.17 (node)
- Node/npm version: 12.18.0, 14.12.0, 14.15.5
- OS: macOS 10.15.7

**Comment by joealden** [comment] 2021-02-22 18:47
@ReFruity one thing I noticed in your comment:

> `--config-file "./babel-config.json"`
> Filename: `babel.config.json`

Note the different between the `-` and `.` in the filenames specified.

**Comment by ReFruity** [comment] 2021-02-22 19:00
@joealden 
> Note the different between the `-` and `.` in the filenames specified.
This is just a typo, edited it, thank you

**Comment by JLHwung** [comment] 2021-03-02 13:49
Can you attach the output of `npx babel-node --version`?

**Comment by marko-knoebl** [comment] 2021-04-18 15:31
I found this issue because I had the same problem.

Turns out for me it was #11108 - I had `"type": "module"` specified in my package.json

As suggested over there, I really think `"type": "module"` should throw for now instead of proceeding silently. It was really hard to find the root cause of this issue.

**Comment by nicolo-ribaudo** [comment] 2023-07-05 11:05
Closing since there is no actionable reproduction.

**Closed by nicolo-ribaudo** 2023-07-05 11:05 UTC
Labels: i: bug, Needs Info, i: needs reproduction
