### ISSUE TITLE
Elvis/existential operator? 

### ISSUE THREAD

**Issue by naholyr** [babel/babel#855] opened 2015-02-21 20:21 UTC
I know this is out of spec, but it would be very nice to add support for Elvis operator in playground. 

```js
object?.property // object && object.property
foo?() // foo && foo() 
```

**Comment by naholyr** [comment] 2015-02-21 20:22
I'll try to make a PR but I'm afraid the learning curve before contributing is a bit high yet ^^

**Comment by sebmck** [comment] 2015-02-21 23:46
Duplicate of babel/acorn-babel#9. Happy for this to be submitted via a PR, a good reference would be @jridgewell's addition of the "mallet operator" via babel/acorn-babel#17 and #516, thanks!

**Closed by sebmck** 2015-02-21 23:46 UTC
Labels: duplicate

**Comment by chocolateboy** [comment] 2015-02-22 16:54
@naholyr FYI: the safe navigation operator and the Elvis operator are not the same:

#### [Safe navigation operator](http://groovy.codehaus.org/Operators#Operators-SafeNavigationOperator(?.))

```groovy
foo?.bar?.baz
```

#### [Elvis operator](http://groovy.codehaus.org/Operators#Operators-ElvisOperator(?:))

```groovy
foo ?: bar
```

P.S. If the [sweet.js interop](https://github.com/babel/babel/issues/568#issuecomment-72569776) plans ever come to fruition, the latter (haven't tried the former) is quite easy to [implement in sweet.js](https://gist.github.com/chocolateboy/67226b9bc0c948c1f1de).

**Comment by naholyr** [comment] 2015-02-22 19:07
Yep, my bad for the name. Don't open issues or PR too late when too tired
:P it's been discussed as "existential operator" in es6 but never drafted
if I remember well

Le dim. 22 févr. 2015 17:54, chocolateboy <notifications@github.com> a
écrit :

**Comment by lolmaus** [comment] 2015-07-27 12:01
What's the status on this? The reference to babel/acorn-babel#9 is broken.

**Comment by Erid** [comment] 2015-08-20 14:08
The ES draft is still being discussed and I think there's no implementation of the existential operator yet on Babel, I believe the best road would be to build a plugin... The [plugin documentation](https://babeljs.io/docs/advanced/plugins/) is a WIP though, but maybe with some help we can manage to build one.

**Comment by jmm** [comment] 2015-08-20 14:25
@lolmaus @Erid This is not coming to `babel` per se, and it's not possible to do it via plugin right now because it would require access to the parsing phase and plugins only have access to the transformation phase. That may happen eventually, but it's not slated for the next major (see https://github.com/babel/babel/issues/2168 "syntax extensions"). If this ever became standardized it would be implemented via plugin (an "official" one or otherwise), because by then all transformers will be out of `babel` core. See also https://esdiscuss.org/topic/existential-operator-null-propagation-operator.

**Comment by bramus** [comment] 2017-01-30 22:15
Earlier today/this week [this feature – named “Null Propgation Operator” – was promoted to `stage-1` by the TC39 Committee](https://ecmascript-daily.github.io/ecmascript/2017/01/30/ecmascript-proposals-status).

I guess that makes this request re-open for consideration?

**Comment by xtuc** [comment] 2017-01-31 11:07
@bramus there is already babel/babylon#328.

**Comment by hzoo** [comment] 2017-06-28 01:39
merged https://github.com/babel/babel/pull/5813 (will be in the next v7 alpha release)
