### ISSUE TITLE
Class properties: read only without initial assignments

### ISSUE THREAD

**Issue by stefanr** [babel/babel#1269] opened 2015-04-15 09:26 UTC
I get the following error

```
Cannot assign to read only property 'foo' of [object Object]
```

... with this class

```js
class Test {
  foo: number;
  constructor() {
    this.foo = 42;
  }
}
```

... whereas this works fine

```js
class Test {
  foo: number = 23;
  constructor() {
    this.foo = 42;
  }
}
```

I think in both cases the class should be created with

```js
_createClass(Test, [{
    key: "foo",
    value: undefined,
    enumerable: true
  }]);
```

... in the first case `value: undefined` is missing which seems to result in a read only property.

**Comment by jridgewell** [comment] 2015-04-15 14:16
Dupe of https://github.com/babel/babel/pull/1256?

**Comment by sebmck** [comment] 2015-04-15 17:07
Looks like it. Please upgrade to 5.1.9. Thanks!

**Closed by sebmck** 2015-04-15 17:07 UTC
