### ISSUE TITLE
ES2015 Class works wrong with instanceof after transpilation

### ISSUE THREAD

**Issue by MaxGenash** [babel/babel#6264] opened 2017-09-18 15:16 UTC
### Input Code
I have the next code:

```js
class ThrottleError extends Error {
  constructor() {
    super();

    this.name = 'ThrottleError';
    this.message = 'Too many function call';

    if (Error.captureStackTrace) {
      Error.captureStackTrace(this, ThrottleError);
    } else {
      this.stack = new Error().stack;
    }
  }
}

try {
  const e = new ThrottleError();
  throw e;
} catch (error) {
  console.log('error instanceof ThrottleError = ', error instanceof ThrottleError);
}
```

### Expected Behavior
When I run the above code in the console of Google Chrome v58 or node.js v8.5 I get the next output, which is expected behavior:
`error instanceof ThrottleError =  true`

### Current Behavior
After transpilation the above code becomes the next:
```js
function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

function _possibleConstructorReturn(self, call) { if (!self) { throw new ReferenceError("this hasn't been initialised - super() hasn't been called"); } return call && (typeof call === "object" || typeof call === "function") ? call : self; }

function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function, not " + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }

let ThrottleError = function (_Error) {
  _inherits(ThrottleError, _Error);

  function ThrottleError() {
    _classCallCheck(this, ThrottleError);

    var _this = _possibleConstructorReturn(this, (ThrottleError.__proto__ || Object.getPrototypeOf(ThrottleError)).call(this));

    _this.name = 'ThrottleError';
    _this.message = 'Too many function call';

    if (Error.captureStackTrace) {
      Error.captureStackTrace(_this, ThrottleError);
    } else {
      _this.stack = new Error().stack;
    }
    return _this;
  }

  return ThrottleError;
}(Error);

try {
  const e = new ThrottleError();
  throw e;
} catch (error) {
  console.log('error instanceof ThrottleError = ', error instanceof ThrottleError);
}
```
When I run the transpiled code it in the console of Google Chrome v58 or node.js v8.5 I get the next output:
`error instanceof ThrottleError =  false`

So it seems that **transpilation of ES2015 Classes in this case works wrong**!

### Possible Solution
After the transpilation, the code should be consistent with smth like the next (1):

```js
function ThrottleError() {
  Error.call(this);

  this.name = 'ThrottleError';
  this.message = 'Too many function call';

  if (Error.captureStackTrace) {
    Error.captureStackTrace(this, ThrottleError);
  } else {
    this.stack = new Error().stack;
  }
}

ThrottleError.prototype = Object.create(Error.prototype);
ThrottleError.prototype.constructor = ThrottleError;
```

### Babel Configuration
At the moment the bug is reproduced in the browser at http://babeljs.io/repl/

Also, my configuration for running in node.js is:
**.babelrc**:
```js
{
  "plugins": ["transform-es2015-classes"]
}
```

**package.json**:
```js
{
  "name": "test",
  "version": "0.0.1",
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.0",
    "babel-plugin-transform-es2015-classes": "^6.24.1"
  }
}
```
_________

Fix it plz cuz due to the bug I have to explicitly use the old syntax (1) in my src code in this case. 😊

**Comment by loganfsmyth** [comment] 2017-09-18 16:26
Duplicate of https://github.com/babel/babel/issues/5524

**Closed by loganfsmyth** 2017-09-18 16:26 UTC
