### ISSUE TITLE
Method argument with default value messes with shadowed import in other methods

### ISSUE THREAD

**Issue by nlepage** [babel/babel#5973] opened 2017-07-19 13:31 UTC
Steps to reproduce :
- Declare an import `import xxx from 'xxx'`
- Declare an ES6 class
- Declare a method with an argument shadowing the import and having a default value : `foo(xxx = 'default') { ... }`
- Declare a second method using the import

### Input Code
```js
import bar from './bar'

class Foo {
  foo(bar = 'Default bar') {}

  logImportedBar() {
    console.log(bar)
  }
}

const foo = new Foo()
foo.logImportedBar()
```

Also see my [repo with a simple example reproducing the issue](https://github.com/nlepage/babel-bug-shadowing).

### Babel Configuration
.babelrc :
```js
{
  "presets": ["env"]
}
```

### Expected Behavior
The second method should access the imported value correctly as it is not shadowed in its scope.

### Current Behavior
The second method yields a ReferenceError on the imported value :
```
ReferenceError: bar is not defined
    at Foo.logImportedBar
```

### Possible Solution
In the generated code, the second method should contain `console.log(_bar2.default)` instead of `console.log(bar)`.

### Your Environment
| software         | version(s)
| ---------------- | -------
| Babel            | v6.24.1
| node             | v8.1.3
| yarn              | v0.27.5
| Operating System | Linux 4.11.9-1-ARCH x86_64

**Comment by nicolo-ribaudo** [comment] 2017-09-25 14:15
Duplicate of #4209

**Closed by nicolo-ribaudo** 2017-09-25 14:15 UTC
Labels: i: bug
