### ISSUE TITLE
Ignoring code blocks via comment in source

### ISSUE THREAD

**Issue by codemakerlive** [babel/babel#2363] opened 2015-09-11 23:21 UTC
Is there a way to toggle babel via comments within code?

E.g:
```
// code for babel to transpile...

/*babel: disable */
   // "MASSIVE" inlined 3rd party library here...
/*babel: enable */

// code for babel to transpile...
```

**Comment by sebmck** [comment] 2015-09-11 23:22
Duplicate of #670, #2097 and similar to #2188.

**Comment by codemakerlive** [comment] 2015-09-11 23:22
My bad. Thanks for the pointers.

**Closed by sebmck** 2015-09-11 23:22 UTC
