### ISSUE TITLE
Transformer for just "runtime helper aliasing"

### ISSUE THREAD

**Issue by syranide** [babel/babel#2059] opened 2015-07-23 13:02 UTC
As far as I can tell the `runtime` transform is all-or-nothing, all I'm interested in is getting rid of the redundant helpers inlined into every module, but it seems I can't have that without also the "risk" of getting dependencies on the other runtimes (notably `core-js`).

Have I missed something or would it not make sense to have a separate transform for just this? They seem to have rather separate concerns from my perspective (avoid redundant helper code vs add dependencies for optional features).

**Comment by jmm** [comment] 2015-07-23 13:19
Hmm, it sounds like the [External helpers](http://babeljs.io/docs/advanced/external-helpers/) option is meant for this use case, but is globally polluting by default. What you're saying does make sense to me, but I'd also like to hear what the reasoning is for the current design.

**Comment by syranide** [comment] 2015-07-23 13:25
Oh I had overlooked that option, that worked great!

This still seems like a curious design decision to me, but I'm no longer directly affected.

**Comment by sebmck** [comment] 2015-07-23 13:34
Duplicate of #2001 and #1233. Also related is #1429. Thanks! :blush:

**Closed by sebmck** 2015-07-23 13:34 UTC

**Comment by syranide** [comment] 2015-07-23 15:06
@sebmck My bad! Perhaps it would be beneficial to have this hinted at in http://babeljs.io/docs/usage/runtime/ then :)

**Comment by sebmck** [comment] 2015-07-23 15:08
@syranide All good! Should have noted that once #1833 happens we'll have a way to customise transformers to remove behaviour like this.

**Comment by jmm** [comment] 2015-07-23 15:12
> Should have noted that once #1833 happens we'll have a way to customise transformers to remove behaviour like this.

:+1: That's what I was thinking -- wondering if perhaps external helpers could just be consolidated into a parameterized `runtime` plugin. Figured I should study it a bit before bringing it up though.

**Comment by sebmck** [comment] 2015-07-23 15:15
@jmm: Oh yeah, that'd definently be cool. Removing options in favor of plugins would definently be a great idea. There'd need to be some way to replace the helper addition behaviour but once that's done then there'll be a lot of flexibility in what plugins can do.

**Comment by jmm** [comment] 2015-07-24 18:21
@sebmck 
> Oh yeah, that'd definently be cool. Removing options in favor of plugins would definently be a great idea.

Ok, cool.

> There'd need to be some way to replace the helper addition behaviour but once that's done then there'll be a lot of flexibility in what plugins can do.

Do you mean the behavior of adding them to the global?

**Comment by sebmck** [comment] 2015-07-24 18:22
@jmm As in, providing some additional API that plugins can use to intercept helper addition.

**Comment by jmm** [comment] 2015-07-24 19:08
@sebmck Ok, thanks. I think I'll need to look at how it actually works currently to totally get it, but I'm sure your comments will be a huge help in understanding the situation.
