### ISSUE TITLE
TypeError: Cannot read property 'range' of null

### ISSUE THREAD

**Issue by askart** [babel/babel#10999] opened 2020-01-13 12:39 UTC
## Bug Report

- [ ] I would like to work on a fix!

**Current Behavior**
```
TypeError: Cannot read property 'range' of null
Occurred while linting ...\..\index.vue:66
    at OffsetStorage.setDesiredOffset (...\node_modules\eslint\lib\rules\indent.js:340:45)
    at ...\node_modules\eslint\lib\rules\indent.js:1358:29
    at Array.forEach (<anonymous>)
    at Object.TemplateLiteral [as listener] (...\node_modules\eslint\lib\rules\indent.js:1350:34)
    at ...\node_modules\eslint\lib\rules\indent.js:1596:55
    at Array.forEach (<anonymous>)
    at Program:exit (...\node_modules\eslint\lib\rules\indent.js:1596:26)
    at ...\node_modules\eslint\lib\linter\safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (...\node_modules\eslint\lib\linter\safe-emitter.js:45:38)
```

**Input Code**
```js
function compFunc(componentName) {
  let component = () => import(`components/${componentName}`)
}
compFunc("component-name")
```

**Expected behavior/code**
No issues found by eslint or eslint rule name.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `.babelrc`

```js
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "node": "current",
          "esmodules": true
        },
        "useBuiltIns": "usage",
        "corejs": 3,
      }
    ]
  ],
  "plugins": [
    [
      "@babel/plugin-transform-runtime",
      {
        "corejs": 3,
      }
    ],
    "@babel/plugin-syntax-import-meta",
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-proposal-json-strings",
    [
      "@babel/plugin-proposal-decorators",
      {
        "legacy": true
      }
    ],
    "@babel/plugin-proposal-function-sent",
    "@babel/plugin-transform-modules-commonjs",
    "@babel/plugin-proposal-export-namespace-from",
    "@babel/plugin-proposal-export-default-from",
    "@babel/plugin-proposal-numeric-separator",
    "@babel/plugin-proposal-throw-expressions"
  ]
}
```

- Filename: `package.json`

```json
{
    "dependencies": {
        "@babel/runtime": "7.8.0",
        "@babel/runtime-corejs3": "7.8.0",
        "core-js": "3.6.3",
        "vue": "2.6.11",
    },
    "devDependencies": {
        "@babel/core": "7.8.0",
        "@babel/plugin-proposal-class-properties": "7.8.0",
        "@babel/plugin-proposal-decorators": "7.8.0",
        "@babel/plugin-proposal-export-default-from": "7.8.0",
        "@babel/plugin-proposal-export-namespace-from": "7.8.0",
        "@babel/plugin-proposal-function-sent": "7.8.0",
        "@babel/plugin-proposal-json-strings": "7.8.0",
        "@babel/plugin-proposal-numeric-separator": "7.8.0",
        "@babel/plugin-proposal-throw-expressions": "7.8.0",
        "@babel/plugin-syntax-import-meta": "7.8.0",
        "@babel/plugin-transform-modules-commonjs": "7.8.0",
        "@babel/plugin-transform-runtime": "7.8.0",
        "@babel/preset-env": "7.8.2",
        "babel-eslint": "10.0.3",
        "babel-loader": "8.0.6",
        "eslint": "6.8.0",
        "eslint-loader": "3.0.3",
        "eslint-plugin-vue": "6.1.2",
        "webpack": "4.41.5"
    },
}
```

- Filename: `.eslintrc`

```js
{
  parserOptions: {
    "parser": "babel-eslint",
    "ecmaVersion": 2017,
    "sourceType": "module",
    "allowImportExportEverywhere": false,
    "codeFrame": false
  },
  extends: [
    "eslint:recommended",
    "plugin:vue/essential",
    "plugin:vue/strongly-recommended",
    "plugin:vue/recommended",
  ],
  rules: {
    "vue/no-side-effects-in-computed-properties": "off",
    "vue/no-reserved-keys": "warn",
    "vue/require-prop-types": "warn",
    "vue/name-property-casing": "warn",
    "vue/max-attributes-per-line": "off",
    "vue/require-v-for-key": "warn",
    "vue/valid-v-for": "warn",
    "vue/no-parsing-error": "warn",
    "vue/no-v-html": "off",
    "vue/order-in-components": "warn",
    "vue/attributes-order": "warn",
    "vue/html-indent": "warn",
    "vue/component-name-in-template-casing": ["warn", "kebab-case", {
      "ignores": []
    }],
    "vue/html-closing-bracket-spacing": ["warn", {
      "startTag": "never",
      "endTag": "never",
      "selfClosingTag": "never"
    }],
    "vue/no-template-shadow": "off",
    "vue/no-use-v-if-with-v-for": "off",
    "no-process-env": "off",
    "no-unused-vars": ["warn", {"args": "none", "ignoreRestSiblings": true}],
    "no-undef": "error",
    "no-redeclare": "warn",
    "no-empty": ["warn", { "allowEmptyCatch": true }],
    "no-console": "warn",
    "quotes": ["warn", "double", {"allowTemplateLiterals": true}],
    "comma-spacing": ["warn", {"before": false, "after": true}],
    "indent": ["warn", 2],
    "object-curly-spacing": ["warn", "never"],
    "key-spacing": "warn",
    "array-bracket-spacing": "warn",
    "block-spacing": ["warn", "never"],
    "func-call-spacing": ["warn", "never"],
    "require-atomic-updates": "off",
  },
  env: {
    "browser": true,
    "node": true,
    "amd": true,
  }
}
```

**Environment**

```
  System:
    OS: Windows 10 10.0.18363
  Binaries:
    Node: 12.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.12.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    babel-eslint: 10.0.3 => 10.0.3
    babel-loader: 8.0.6 => 8.0.6
    eslint: 6.8.0 => 6.8.0
    webpack: 4.41.5 => 4.41.5
```

**Possible Solution**
temporarily modify .eslintrc "indent" rule
`"indent": ["warn", 2, {"ignoredNodes": ["TemplateLiteral"]}],`

**Comment by nicolo-ribaudo** [comment] 2020-01-13 17:26
Thanks for the report. We are still tracking ESLint-related issues in the `babel/babel-eslint` repository, so I'm closing this as a duplicate of https://github.com/babel/babel-eslint/issues/799

**Closed by nicolo-ribaudo** 2020-01-13 17:26 UTC
Labels: i: bug, i: needs triage
