### ISSUE TITLE
Autobinding in babel 6.0

### ISSUE THREAD

**Issue by rtm7777** [babel/babel#2774] opened 2015-11-03 08:47 UTC
Hello, I found that autobinding in classes are not work after update to 6.0

    'this' is not allowed before super() (This is an error on an internal node. Probably an internal error)

.babelrc

    {
        "presets": [
            "react",
            "es2015",
            "stage-0"
        ]
    }

Is it expected behavior?
Thanks!

**Comment by mattstyles** [comment] 2015-11-03 10:23
Its nothing to do with 6.0, `super()` before `this` has been a requirement for quite some time. It also makes sense.

**Comment by janpieterz** [comment] 2015-11-03 10:30
I encounter the same but am 100% sure super gets called as the first thing in the constructor.

With me this happens when using property initializers, so for example:
``` js
  changeAccessGroup = (accessGroupId) => {
    this.setState({
      accessGroup: accessGroupId
    });
  }
```

If I remove that method it compiles, but then it forces be to specifically bind this to the method, which I'd prefer not to. It seems like somehow the transform-class-properties doesn't work anymore (which replaced es7.classProperties as far as I know).
Configuration:
``` js
    b.transform('babelify', {
        presets:["stage-0", "es2015", "react"],
        plugins: ["transform-class-properties"]
    });
```

**Comment by rtm7777** [comment] 2015-11-03 13:49
Yes, `super()` is a first call in constructor.
And code is equal.
Example of code: https://github.com/rtm7777/rozklad_cdtu/blob/master/web/js/components/tasks/tasksDepartmentSelector.js?ts=2
After removing methods on 33 and 38 lines, compiling successful

**Comment by sebmck** [comment] 2015-11-03 15:10
Can someone please provide some example input code? It's impossible to debug this without it.

**Comment by rtm7777** [comment] 2015-11-03 15:15
@sebmck https://github.com/rtm7777/rozklad_cdtu/blob/master/web/js/components/tasks/tasksDepartmentSelector.js?ts=2

On lines 33 and 38

**Comment by binbinfrog** [comment] 2015-11-03 15:35
@sebmck 
just wrote a simple app to show what happened

the component:
```
import React from 'react';

class Test extends React.Component {
    constructor(props){
        super(props);
    }

    static defaultPorps = {
        username:"apple"
    }

    render(){
        //there is nothing wrong about this "this.click"
        return(
            <div>
                <button onClick={this.click}>say hi</button>
            </div>
        )
    }

    click = (evt) =>{
        /*
          ** this would not build because of these "this" here
          ** message says:
          ** 'this' is not allowed before super() (This is an error on an internal node. Probably an internal error)
         */
        this.setState({username:"orange"});
        alert(this.state.username);

        //this works fine
        alert("hi");
    }
}

export default Test;
```
the index.js:
```
import React from 'react';
import ReactDOM from 'react-dom';
import Test from './test';
ReactDOM.render(
    <Test />,
    document.getElementById('content')
);

**Comment by janpieterz** [comment] 2015-11-03 15:36
@sebmck I just made a super small example: https://github.com/janpieterz/BabelClassPropertiesTest

**Comment by binbinfrog** [comment] 2015-11-03 16:04
@janpieterz 
I found "this" can be used in constructor, so I move the function uses "this" into the constructor, then it works properly. But now the code looks like this:
```
constructor(props){
        super(props);
        this.state = {
            username:props.username
        }
        this.click = (evt) =>{
            this.setState({username:"orange"});
            
            /*
             * however, this console.log still output old data
             * when this click function is triggered for the first time
             */
            console.log(this.state.username);
        }
    }
```
I don't like the way it looks.

**Comment by mattstyles** [comment] 2015-11-03 16:57
yes, if you have a poke through the babel transpiled code, it is basically the same thing.

If you remove the refs to `this` from your function then babel will succeed in transpilation, and you’ll see the class props either manually appended within the constructor function (in loose mode) or using a version of Object.defineProp.

There have been a few fixes regarding classes, class props and modules already in the last day or 2, I dont think it'll take too long to iron this one out either.

**Comment by JohnyDays** [comment] 2015-11-04 01:09
@binbinfrog That is not related to babel, react batches setState calls, so you need to check it asynchronously

**Comment by mattstyles** [comment] 2015-11-04 10:01
@JohnyDays @binbinfrog that second bit about the checking `state` after setting it should be removed from this issue, its nothing to do with the babel class props transform.

**Comment by andrewjtait** [comment] 2015-11-04 13:23
I'm having similar issues, particularly following the example in the docs for arrow functions and auto-binding - http://babeljs.io/blog/2015/06/07/react-on-es6-plus/#arrow-functions

the example being...

```js
class PostInfo extends React.Component {
  handleOptionsButtonClick = (e) => {
    this.setState({showOptionsModal: true});
  }
}
```

and I get the error `'this' is not allowed before super() (This is an error on an internal node. Probably an internal error)`

I am using the presets `es2015`, `stage-0` and `react`.

**Comment by deepakjois** [comment] 2015-11-04 13:23
Looks like this is the same issue as #2809 . I provided a minimal reproduction of the error there as well. Basically, I am encountering the same thing that @janpieterz seems to encounter as well.

This broke my existing React build. I was just following the suggestion in this blogpost:
http://babeljs.io/blog/2015/06/07/react-on-es6-plus/

> Luckily, by combining two ES6+ features – arrow functions and property initializers – opt-in binding to the component instance becomes a breeze

**Comment by ben-ng** [comment] 2015-11-04 18:28
i'm running into this although i'm not using property initializers.

has anyone found a workaround?

**Comment by calitek** [comment] 2015-11-04 19:40
The workaround for now seems to be to forgo arrow functions that have a 'this'.

**Comment by Rukenshia** [comment] 2015-11-05 16:13
Im not using React but have to face the same issue.

Example Code:
```javascript
//src/test.js
export default class Something extends SomethingElse {
  constructor() {
    super();

    (() => {
      this.notWorking = true;
    })();
  }
}
```

build command:
`babel src --out-dir ./ --presets es2015 --plugins transform-es2015-modules-commonjs`

**Comment by 321ckatz123** [comment] 2015-11-05 21:56
I just upgraded to the 6.1.2 version of Babel and getting a similar error. This worked with 5.8.29 (without a .babelrc and plugins, however). I don't think any of the workarounds mentioned would work, so for helping debug, I am adding the relevant code to here and closing the other.

**SyntaxError:** .../Book.jsx: 'this' is not allowed before super() (This is an error on an internal node. Probably an internal error):

**.babelrc file**
```
{
  "presets": ["es2015", "react"]
}
```

**Book.jsx**
```
import React, {PropTypes} from 'react';

export default class Book extends React.Component {
  constructor(props) {
    super(props);
    this.state = {read: props.read};
  }

  handleChange() {
    this.setState({
      read: !this.state.read
    });

    this.props.onReadBook(this.state.read);
  }

  render() {
    return (
        <tr>
          <td>{this.props.title}</td>
          <td><input type='checkbox' checked={this.state.read} onChange={() => this.handleChange()}/></td>
        </tr>
    );
  }
}
Book.propTypes = {
  title: PropTypes.string.isRequired,
  read: PropTypes.bool.isRequired,
  onReadBook: PropTypes.func.isRequired
};
```

**Relevant package.json**
```
"dependencies": {
    "babel-core": "6.1.2",
    "babel-preset-react": "6.1.2",
    "babel-preset-es2015": "6.1.2",
    ...
}
```

**Comment by janpieterz** [comment] 2015-11-05 22:06
@321ckatz123 have you tried the following, for a temporary fix? Without somehow binding the this to the function, your handleChange method will never get access to the right context. The auto properties way does this for itself, but as far as I know, without using that, you always had to add the .bind(this) for custom methods in the constructor.

```js
constructor(props) {
    super(props);
    this.state = {read: props.read};
    this.handleChange = this.handleChange.bind(this);
  }
```

**Comment by happypoulp** [comment] 2015-11-05 22:25
I am reproducing this issue even without using `this` at all:

```es6
// file: issue-export-class.js
export default class MyClass extends Object { }
```

```
bash $ ./node_modules/.bin/babel-node issue-export-class.js
/Users/me/Codes/babel6/node_modules/babel-core/lib/transformation/file/index.js:546
      throw err;
      ^

SyntaxError: /Users/me/Codes/babel6/issue-export-class.js: 'this' is not allowed before super() (This is an error on an internal node. Probably an internal error)
...
```

I use babel 6.1.2 with preset 'es2015'.

**Comment by 321ckatz123** [comment] 2015-11-05 22:44
@janpieterz, I have not, but this way did work before upgrading, so unless I was relying on a bug or unintended consequence on the older version (which, honestly, is entirely possible) I don't know why that would cause this error message. I am calling super in the constructor before any usage of this, and if this wasn't bound correctly (so the function wouldn't work), I would assume that would be more of a runtime issue when trying to execute said function (which I did actually run into before using Redux).

**Comment by ju1ius** [comment] 2015-11-08 11:46
Given the following input:
```js
class Foo {}

class Bar extends Foo {
    doit = stuff => {
        return this;
    }
}
```
Using Babel 5,
```sh
babel --version
> 5.8.29 (babel-core 5.8.33)
babel --stage=1 test-arrow-class-props.js
```
Ouputs the following expected code:
```js
// babel helpers omitted for brevity

var Foo = function Foo() {
    _classCallCheck(this, Foo);
};

var Bar = (function (_Foo) {
    _inherits(Bar, _Foo);

    function Bar() {
        var _this = this;

        _classCallCheck(this, Bar);

        _get(Object.getPrototypeOf(Bar.prototype), "constructor", this).apply(this, arguments);

        this.doit = function (stuff) {
            return _this;
        };
    }

    return Bar;
})(Foo);
```

Using Babel 6:
```sh
./node_modules/.bin/babel --version
> 6.1.2 (babel-core 6.1.2)
./node_modules/.bin/babel --presets=es2015,stage-1 test-arrow-class-props.js
> SyntaxError: test-arrow-class-props.js: 'this' is not allowed before super() (This is an error on an internal node. Probably an internal error)
> undefined
```

**Comment by bkonkle** [comment] 2015-11-09 18:51
I'm experiencing the same issue, and as with others my configuration works fine in Babel 5.

My component:

```javascript
import React from 'react'

export default class Dashboard extends React.Component {

  render() {
    return <h1>Welcome to my component!</h1>
  }

}
```

My dead simple smoke test:

```javascript
import chai, {expect} from 'chai'
import jsxChai from 'jsx-chai'
import Dashboard from 'components/ecosystems/dashboard'

chai.use(jsxChai)

describe('smoke test', () => {
  it('works', () => {
    expect(Dashboard).to.be.jsx
  })
})
```

The error:

```
SyntaxError: /Users/myUser/code/myProject/src/components/ecosystems/dashboard/index.jsx: 'this' is not allowed before super() (This is an error on an internal node. Probably an internal error)
    at File.buildCodeFrameError (/Users/myUser/code/myProject/node_modules/babel-core/lib/transformation/file/index.js:409:15)
```

My .babelrc:

```javascript
{
  "presets": ["es2015-loose", "react"],
  "plugins": ["transform-class-properties"]
}
```

**Comment by thejameskyle** [comment] 2015-11-09 19:20
Closing this in favor of https://github.com/babel/babel/issues/2942 because there's been to much distracting comments in this issue.

**Closed by thejameskyle** 2015-11-09 19:20 UTC
Labels: pending triage
