### ISSUE TITLE
Plugin not found if not under cwd 

### ISSUE THREAD

**Issue by vbraun** [babel/babel#9273] opened 2019-01-03 11:41 UTC
## Bug Report

**Current Behavior**

I've installed babel in a separate directory `/tools`, which is not where my project lives. Trying to run babel fails with 
~~~~
$ /tools/babel source.ts 
{ Error: Cannot find module '@babel/plugin-proposal-class-properties' from '/my/project'
    at Function.module.exports [as sync] (/tools/lib/node_modules/@babel/core/node_modules/resolve/lib/sync.js:58:15)
    at resolveStandardizedName (/tools/lib/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
    at resolvePlugin (/tools/lib/node_modules/@babel/core/lib/config/files/plugins.js:54:10)
    at loadPlugin (/tools/lib/node_modules/@babel/core/lib/config/files/plugins.js:62:20)
    at createDescriptor (/tools/lib/node_modules/@babel/core/lib/config/config-descriptors.js:155:9)
    at items.map (/tools/lib/node_modules/@babel/core/lib/config/config-descriptors.js:110:50)
    at Array.map (<anonymous>)
    at createDescriptors (/tools/lib/node_modules/@babel/core/lib/config/config-descriptors.js:110:29)
    at createPluginDescriptors (/tools/lib/node_modules/@babel/core/lib/config/config-descriptors.js:106:10)
    at plugins (/tools/lib/node_modules/@babel/core/lib/config/config-descriptors.js:41:19) code: 'MODULE_NOT_FOUND' }
~~~~

**Expected behavior/code**

Babel should just load the plugins from where babel is installed, and not override the module resolution base dir with cwd. I don't understand why you would want that, ever. If there is a use case (is there?) then at least catch and try again without overriding the base dir.

**Babel Configuration (.babelrc, package.json, cli command)**

My .babelrc is just 
~~~~
{
    "presets": [
        "@babel/env",
        "@babel/preset-typescript"
    ],
    "plugins": [
        "@babel/plugin-proposal-class-properties",
        "@babel/plugin-proposal-object-rest-spread"
    ]
}
~~~~
and all required packages are installed under `/tools`

**Environment**
- Babel version(s): 7.2.0
- Node/npm version: Node v10.12.0, npm 6.4.1
- OS: Fedora 29 x86_64
- How you are using Babel: cli

**Possible Solution**

Plugins load fine if, in `resolveStandardizedName`, I replace
~~~
        resolve.sync(name, { basedir: dirname });
~~~
with
~~~
        resolve.sync(name);
~~~
Note that dirname is set to cwd (as absolute path), and there does not seem to be a way to override it from `.babelrc`.

**Comment by chenhaihong** [comment] 2019-01-22 13:45
Is there any way to edit or override the default cwd? Maybe a option in  webpack.config,js? 
I read the code, but i can not find any way to edit it.

**Comment by samueldr** [comment] 2019-04-25 20:19
Confirmed to be an issue with 7.4.3 still.

This issue breaks out-of-tree builds considering the tree structure:

```
out/
my-app/
```

where `build` is a script calling webpack correctly:

```
cd ../out/
../my-app/bin/build
```

The same build when `cd`'d at the root of `my-app` works. Out-of-tree builds should not be an obscure feature.

Relying on the CWD to resolve node modules goes against the behaviour of both `node` and `browserify/resolve`.

The CWD pollution seems to be coming from (at least) both these places:

 * https://github.com/babel/babel/blob/ca639b426213ba947dc89373ddcbe5461c33afc0/packages/babel-core/src/config/item.js#L34
 * https://github.com/babel/babel/blob/e85faec47d5d3ef940b7a85d48fa24e6e1cc32ab/packages/babel-core/src/config/files/plugins.js#L91-L95

Here is the relevant trace:

```
    ERROR in ./app/index.js
    Module build failed (from ./node_modules/babel-loader/lib/index.js):
    Error: Cannot find module '@babel/plugin-[...]' from '[...]/out-of-tree'
        at Function.module.exports [as sync] ([...]/my-app/node_modules/resolve/lib/sync.js:58:15)
>       at resolveStandardizedName ([...]/my-app/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
>       at resolvePlugin ([...]/my-app/node_modules/@babel/core/lib/config/files/plugins.js:54:10)
>       at loadPlugin ([...]/my-app/node_modules/@babel/core/lib/config/files/plugins.js:62:20)
>       at createDescriptor ([...]/my-app/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
        at items.map ([...]/my-app/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
        at Array.map (<anonymous>)
        at createDescriptors ([...]/my-app/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
        at createPluginDescriptors ([...]/my-app/node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
        at alias ([...]/my-app/node_modules/@babel/core/lib/config/config-descriptors.js:63:49)
        at cachedFunction ([...]/my-app/node_modules/@babel/core/lib/config/caching.js:33:19)
        at plugins.plugins ([...]/my-app/node_modules/@babel/core/lib/config/config-descriptors.js:28:77)
        at mergeChainOpts ([...]/my-app/node_modules/@babel/core/lib/config/config-chain.js:319:26)
        at [...]/my-app/node_modules/@babel/core/lib/config/config-chain.js:283:7
        at buildRootChain ([...]/my-app/node_modules/@babel/core/lib/config/config-chain.js:68:29)
        at loadPrivatePartialConfig ([...]/my-app/node_modules/@babel/core/lib/config/partial.js:85:55)
        at Object.loadPartialConfig ([...]/my-app/node_modules/@babel/core/lib/config/partial.js:110:18)
        at Object.<anonymous> ([...]/my-app/node_modules/babel-loader/lib/index.js:140:26)
        at Generator.next (<anonymous>)
        at asyncGeneratorStep ([...]/my-app/node_modules/babel-loader/lib/index.js:3:103)
        at _next ([...]/my-app/node_modules/babel-loader/lib/index.js:5:194)
        at [...]/my-app/node_modules/babel-loader/lib/index.js:5:364
        at new Promise (<anonymous>)
        at Object.<anonymous> ([...]/my-app/node_modules/babel-loader/lib/index.js:5:97)
        at Object._loader ([...]/my-app/node_modules/babel-loader/lib/index.js:220:18)
        at Object.loader ([...]/my-app/node_modules/babel-loader/lib/index.js:56:18)
        at Object.<anonymous> ([...]/my-app/node_modules/babel-loader/lib/index.js:51:12)
```

I wouldn't know how to create a test case quickly within your testing framework, but I can slap up a test script quickly if you want an automated test to test the behaviour.

**Comment by loganfsmyth** [comment] 2019-04-25 20:53
@samueldr Babel only uses the working directory when it has no other way of knowing what directory to use. You can pass `cwd: __dirname` in your `babel-loader` options give it a specific working directory for the cases when it has no way of knowing.

**Comment by samueldr** [comment] 2019-04-25 21:34
This is a regression, imo, as with babel in the 6 series, verified with 6.26, it could resolve fine without somehow falling back to the CWD.

In addition, testing with node and browserify/resolve confirms this goes against the default behaviour of how node resolves modules. This breaks the expectation of how resolving node modules works.

**Comment by loganfsmyth** [comment] 2019-04-25 21:53
@samueldr  It's not a regression because it was a purposeful decision. 

> In addition, testing with node and browserify/resolve confirms this goes against the default behaviour of how node resolves modules. This breaks the expectation of how resolving node modules works.

Node/browserify have a specific file that is explicitly doing the importing and thus always have a specific location to resolve relative to. When Babel plugins are referenced within a `.babelrc` or a `babel.config.js` Babel resolves the plugins consistently relative to those files, with the goal of being as close to Node as possible. If a plugin is passed some other way, the question is then what path do we resolve relative to? Babel 6 resolved these relative to the file being compiled, but it was a frequent pain point for users. The path of the file being compiled is also entirely optional, leading to cases where Babel's behavior would dramatically change depending on whether the argument was provided.

Relying on the file being compiled does not make sense in the context of what Babel is trying to do because the file being compiled is not logically tied to the path of Babel's plugins. Consider the case of
```
someLibrary/
  index.js
someApplication/
  index.js
  package.json # importing 'someLibrary'
  node_modules/
    babel-plugin-...
```
if the user compiling their application wants to run a plugin on `someLibrary/index.js` how would they do so? It is important that an application compiling all of its dependencies be able to apply plugins to all files. If plugins were resolved relative to the file, it would be extremely hard to do without ugly hacks (as it was in Babel 6).

**Comment by samueldr** [comment] 2019-04-25 22:20
There may be some confusion brought in addition from `babel-loader`'s use, but I expect that the webpack project root (named [`context`](https://webpack.js.org/configuration/entry-context#context)) be the project root, and things to resolve accordingly, even when doing out of tree builds.

When adding `context` to a webpack build, I would expect `babel-loader` to configure babel to work under the same context, otherwise there is a kind of split personality developing, where parts of the application is being build from where the context is set, and part is affected from CWD.

Maybe the issue (for me at least) lies in babel-loader? I guess it is preferable to open an issue there?

From the `context` documentation:

> The base directory, an absolute path, **for resolving** entry points and **loaders** from configuration.

I would assume that where loaders are resolved, plugins for the loaders would too.

**Comment by loganfsmyth** [comment] 2019-04-25 22:28
That sounds reasonable, though I can't say I'm familiar with that option. Would you be up for filing an issue on `babel-loader`?

**Comment by nicolo-ribaudo** [comment] 2019-08-19 07:47
I'm closing this issue, since Logan excellently explained the reason behind this behavior.

I'll also add that, if anyone wants to override the default resolution algorithm, they can:

```js
// babel.config.js

module.exports = {
  plugins: [
    loadWithCustomAlgorithm("@babel/plugin-proposal-class-properties")
  ]
};

function loadWithCustomAlgorithm(pluginName) {
}
```

**Closed by nicolo-ribaudo** 2019-08-19 07:47 UTC
Labels: i: bug, i: needs triage

**Comment by vbraun** [comment] 2019-08-19 09:30
Is the implementation of `loadWithCustomAlgorithm` missing? this just exports `plugins: [undefined]`, I don't understand how that could work. Is that documented somewhere so I can read up on it?

**Comment by nicolo-ribaudo** [comment] 2019-08-19 09:33
Yeah sorry. If you don't want Babel's default algorithm, you can provide any algorithm you want.
In your case it would probably be implemented like this:

```js
function loadWithCustomAlgorithm(pluginName) {
  return require.resolve(pluginName, { basedir: "/tools" });
}
```
