### ISSUE TITLE
Let declaration in for loop is not properly scoped when initialization uses same identifier

### ISSUE THREAD

**Issue by TennySky** [babel/babel#5459] opened 2017-03-13 15:07 UTC
Sorry for my poor English~
My project dependencies are:
```
 "devDependencies": {
    "babel-core": "^6.24.0",
    "babel-loader": "^6.4.0",
    "babel-preset-env": "^1.2.1",
    "babel-preset-es2015": "^6.24.0",
    "html-webpack-plugin": "^2.28.0",
    "webpack": "^2.2.1",
    "webpack-dev-server": "^2.4.1"
  }
```
And the webpack.config.js  has a loader :
```
     test: /\.(js|jsx)/,
     use: "babel-loader?presets[]=env",
     exclude: /(node_modules|idea)/
```
the code:
```
for (let i = 0; i < 3; console.log(i),i++) {
            let i = "abc";
            console.log(i);
}
```
expected result:
```
abc
0
abc
1
abc
2
```
but output
```
abc
abc
```
Is that a BUG?

**Comment by alxpy** [comment] 2017-03-13 15:42
Hmm, as for me, it's normal behavior

**Comment by alxpy** [comment] 2017-03-13 15:45
Hmm, as for me, I think this code should throw something like "Duplicate declaration"...

**Comment by alxpy** [comment] 2017-03-13 15:47
Hmm, as for me, I think this code should throw something like "Duplicate declaration"...

**Comment by aaronang** [comment] 2017-03-13 15:55
@TennySky Thank you for reporting this. I think it is a bug because the code works in Chrome and would indeed output:

```
abc
0
abc
1
abc
2
```

Although, I would argue that you could just change the variable name 😛

**Comment by TennySky** [comment] 2017-03-14 05:44
@aaronang  thanks for your answer and argument, It was only a Test Code when I learning ES6 language from [here](http://es6.ruanyifeng.com/#docs/let)

**Comment by TennySky** [comment] 2017-03-14 05:53
@alxpy I agree with you!
```javascript
for(let i = 0; i < 3; i++) {
     let j = "abc";
}
```
ask for me, I think the variable i and j should be in same code scope.

**Comment by aaronang** [comment] 2017-03-15 04:12
Reproduction: https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015&targets=Node-6&browsers=%3E%202%25&builtIns=false&code=for%20(let%20i%20%3D%200%3B%20i%20%3C%203%3B%20console.log(i)%2C%20i%2B%2B)%20%7B%0A%20%20let%20i%20%3D%20%22abc%22%3B%0A%20%20console.log(i)%3B%0A%7D&experimental=false&loose=false&spec=false&playground=true

**Comment by anubhav7495** [comment] 2017-03-31 12:01
Compilation result from `Typescript` compiler:
```
for (var i = 0; i < 3; console.log(i), i++) {
    var i_1 = "abc";
    console.log(i_1);
}
```
This works as expected.
I would like to work on this issue, can somebody point me in the right direction?

**Comment by nicolo-ribaudo** [comment] 2017-09-25 14:11
This is a duplicate of #4351

**Closed by nicolo-ribaudo** 2017-09-25 14:11 UTC
Labels: i: bug
