### ISSUE TITLE
v6.1.4, Require Hook, Error: Cannot find module 'babel-runtime/helpers/interop-require-default'

### ISSUE THREAD

**Issue by XuJinNet** [babel/babel#3003] opened 2015-11-12 06:16 UTC
Update to v6.1.4, require("babel-core/register") is not work:
Error: Cannot find module 'babel-runtime/helpers/interop-require-default'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (xxxx\koa_test\node_modules\babel-register\lib\node.js:5:30)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

**Comment by jonathanong** [comment] 2015-11-12 06:32
seeing this too.

```
Error: Cannot find module 'babel-runtime/helpers/interop-require-default'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/jong/Workspace/vacation/vacation-api-docs/node_modules/babel-register/lib/node.js:5:30)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/jong/Workspace/vacation/vacation-api-docs/node_modules/babel-core/register.js:2:18)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/jong/Workspace/vacation/vacation-api-docs/lib/index.js:3:1)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/jong/Workspace/vacation/vacation-api-docs/lib/__tests/index.js:3:1)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /Users/jong/Workspace/vacation/vacation-api-docs/node_modules/mocha/lib/mocha.js:216:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/jong/Workspace/vacation/vacation-api-docs/node_modules/mocha/lib/mocha.js:213:14)
    at Mocha.run (/Users/jong/Workspace/vacation/vacation-api-docs/node_modules/mocha/lib/mocha.js:453:10)
    at Object.<anonymous> (/Users/jong/Workspace/vacation/vacation-api-docs/node_modules/mocha/bin/_mocha:393:18)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3
```

i've noticed that it's been renamed to camel case:

![screen shot 2015-11-11 at 10 31 48 pm](https://cloud.githubusercontent.com/assets/643505/11112051/0aed86a2-88c4-11e5-86a1-f0699ee5e158.png)

**Comment by sebmck** [comment] 2015-11-12 06:38
Duplicate of #2989. Please search before opening an issue.

**Closed** 2015-11-12 06:40 UTC
