### ISSUE TITLE
Parsing error: Cannot read property '0' of undefined 

### ISSUE THREAD

**Issue by LikeWuXiang** [babel/babel#12374] opened 2020-11-19 08:21 UTC
## Bug Report

**Input Code**

```js
import { isDevEnv, isStableEnv, getDevUrl, getStableUrl } from '@dian/app-utils'
```

**EsLint Report**

```js
 eslint:cli CLI args: [ '--debug', 'src/components/approval-process/common/env-url.js' ] +0ms
  eslint:cli Running on files +4ms
  eslint:ignore-pattern Create with: [ IgnorePattern { patterns: [ '/**/node_modules/*' ], basePath: '/Users/liam/dian/honor', loose: false } ] +0ms
  eslint:ignore-pattern   processed: { basePath: '/Users/liam/dian/honor', patterns: [ '/**/node_modules/*' ] } +2ms
  eslint:ignore-pattern Create with: [ IgnorePattern { patterns: [ '/**/node_modules/*' ], basePath: '/Users/liam/dian/honor', loose: false } ] +1ms
  eslint:ignore-pattern   processed: { basePath: '/Users/liam/dian/honor', patterns: [ '/**/node_modules/*' ] } +0ms
  eslint:file-enumerator Start to iterate files: [ 'src/components/approval-process/common/env-url.js' ] +0ms
  eslint:file-enumerator File: /Users/liam/dian/honor/src/components/approval-process/common/env-url.js +0ms
  eslint:ignore-pattern Create with: [ IgnorePattern { patterns: [ '/**/node_modules/*' ], basePath: '/Users/liam/dian/honor', loose: false }, IgnorePattern { patterns: [ '**/*.min.js', 'coverage/**', 'node_modules/**', 'vendor/**' ], basePath: '/Users/liam/dian/honor', loose: false }, IgnorePattern { patterns: [ 'node_modules/*', 'public/*', 'build/*', 'assets/*', 'src/containers/data/inlet/index.js', 'src/containers/shop/create/create_.js', 'src/containers/shop/detail/index.js', 'src/components/pre-dui/list', 'src/containers/a/replaceBD/ChannelAllot.js' ], basePath: '/Users/liam/dian/honor', loose: true } ] +1s
  eslint:ignore-pattern   processed: { basePath: '/Users/liam/dian/honor', patterns: [ '/**/node_modules/*', '**/*.min.js', 'coverage/**', 'node_modules/**', 'vendor/**', 'node_modules/*', 'public/*', 'build/*', 'assets/*', 'src/containers/data/inlet/index.js', 'src/containers/shop/create/create_.js', 'src/containers/shop/detail/index.js', 'src/components/pre-dui/list', 'src/containers/a/replaceBD/ChannelAllot.js' ] } +1ms
  eslint:ignore-pattern Check {
  filePath: '/Users/liam/dian/honor/src/components/approval-process/common/env-url.js',
  dot: false,
  relativePath: 'src/components/approval-process/common/env-url.js',
  result: false
} +2ms
  eslint:cli-engine Lint /Users/liam/dian/honor/src/components/approval-process/common/env-url.js +0ms
  eslint:linter Linting code for /Users/liam/dian/honor/src/components/approval-process/common/env-url.js (pass 1) +0ms
  eslint:linter Verify +0ms
  eslint:linter With ConfigArray: /Users/liam/dian/honor/src/components/approval-process/common/env-url.js +1ms
  eslint:linter Parsing error: Cannot read property '0' of undefined
  eslint:linter TypeError: Cannot read property '0' of undefined
    at Object.getGetterSetterExpectedParamCount (/Users/liam/dian/honor/node_modules/@babel/parser/lib/index.js:7300:37)
    at Object.checkGetterSetterParams (/Users/liam/dian/honor/node_modules/@babel/parser/lib/index.js:10925:29)
    at Object.parseObjectMethod (/Users/liam/dian/honor/node_modules/@babel/parser/lib/index.js:10945:12)
    at Object.parseObjectMethod (/Users/liam/dian/honor/node_modules/@babel/parser/lib/index.js:986:24)
    at Object.parseObjPropValue (/Users/liam/dian/honor/node_modules/@babel/parser/lib/index.js:10986:23)
    at Object.parseObjPropValue (/Users/liam/dian/honor/node_modules/@babel/parser/lib/index.js:6996:11)
    at Object.parsePropertyDefinition (/Users/liam/dian/honor/node_modules/@babel/parser/lib/index.js:10910:10)
    at Object.parseObjectLike (/Users/liam/dian/honor/node_modules/@babel/parser/lib/index.js:10802:25)
    at Object.parseExprAtom (/Users/liam/dian/honor/node_modules/@babel/parser/lib/index.js:10332:23)
    at Object.parseExprAtom (/Users/liam/dian/honor/node_modules/@babel/parser/lib/index.js:958:22) +533ms
  eslint:linter Generating fixed text for /Users/liam/dian/honor/src/components/approval-process/common/env-url.js (pass 1) +0ms
  eslint:source-code-fixer Applying fixes +0ms
  eslint:source-code-fixer shouldFix parameter was false, not attempting fixes +0ms
  eslint:file-enumerator Complete iterating files: ["src/components/approval-process/common/env-url.js"] +2s
  eslint:cli-engine Linting complete in: 1987ms +535ms

/Users/liam/dian/honor/src/components/approval-process/common/env-url.js
  0:0  error  Parsing error: Cannot read property '0' of undefined

```

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js 
module.exports = {
  presets: [
    ['@dian/babel-preset', {
      typescript: true,
    }],
  ],
  plugins: [
    [require.resolve('babel-plugin-import'), { libraryName: 'antd-mobile', libraryDirectory: 'lib', style: true }, 'antd-mobile'],
    ['webpack-chunkname', {
      getChunkName (imported) {
        return imported.replace(/(\W+)|(\.js$)/g, '~')
      },
    }],
  ],
}
```

**Environment**

```

```
- Babel version(s): [ ^7.10.4 ]
- Node/npm version: [ Node v12.13.0/npm 6.12.0 ]
- OS: [ OSX 10.15.7 ]
- Monorepo: [ no ]
- How you are using Babel: [ `loader` ]

**Comment by JLHwung** [comment] 2020-11-19 20:19
Can you post `src/components/approval-process/common/env-url.js`? Babel parser throws on this file.

Is this issue reproducible on Babel 7.12?

**Comment by nicolo-ribaudo** [comment] 2021-01-30 14:17
Closing since we cannot reproduce this issue.

**Closed by nicolo-ribaudo** 2021-01-30 14:17 UTC
Labels: i: bug, i: needs reproduction
