### ISSUE TITLE
ReferenceError: dataGlobal is not defined ???

### ISSUE THREAD

**Issue by elissaioskon** [babel/babel#7649] opened 2018-04-01 14:49 UTC
i use webpack that use babel and i have an express server that is compiled from es6 with webpack nice.After add async await to my code there is an error regeneratorRuntime is not defined. After adding babel-polyfill as first line of the expressjs code i have an error ReferenceError: dataGlobal is not defined.
I also tried transform-runtime plugin but i have the same error.Any idea?

**Comment by xtuc** [comment] 2018-04-01 16:50
The `dataGlobal is not defined` error isn't caused by Babel, but likely your application code.

**Comment by elissaioskon** [comment] 2018-04-01 18:39
Finally it was my fault. I hadnt enable retain line and the bundle from webpack didnt show me the original line in code for the error. Thanks for the answer.

**Comment by xtuc** [comment] 2018-04-01 18:50
No worries! I'm closing this.

**Closed by xtuc** 2018-04-01 18:50 UTC
Labels: Needs Info, i: invalid

**Comment by loganfsmyth** [comment] 2018-04-02 03:04
@elissaioskon FYI `retainLines` isn't something I'd recommend. If you want real locations, best to rely on sourcemaps.
