### ISSUE TITLE
Problems building an older version (like 5.0.6)

### ISSUE THREAD

**Issue by jmm** [babel/babel#1643] opened 2015-05-28 19:36 UTC
I just tried building v5.0.6 and unfortunately it was a pretty gross experience (I didn't get past `make bootstrap`). It looks like the problem is that it depended on a submodule `babel/regenerator-babel` repo that was just deleted at some point, poof, vanished into thin air. After going down this rabbit hole to figure out what was going on, I manually cloned `facebook/regenerator` in its place and that got me a bit further, but after running `make build-core` and `make test` I get test failures, which I assume is from using the wrong `regenerator` dependency.

Is it really a good idea to just delete a repo like that that's a build dependency of a previous version of the package?

Is there something we can do to make building a previous version work? Is there some reason that repo couldn't go back online?

Please don't take this as overly negative. I appreciate all the great work on this project and the reason I'm trying to build this in the first place is to contribute.

Thanks

**Comment by sebmck** [comment] 2015-05-28 19:44
Why are you building such an old version? People were depending on that package/repo even with the explicit "don't use this unless you're me" message which is why it was deleted in the first place.

**Comment by jmm** [comment] 2015-05-28 19:48
I'm trying to debug something that changed around that time. I'm really not sure that people inappropriately depending on a repo is a good reason to break the ability to build previous versions of this package.

**Comment by sebmck** [comment] 2015-05-28 19:50
Sure. I'm not willing to support any older versions though. That's just the way it is, sorry. Unsure what the actual question here is?

**Comment by jmm** [comment] 2015-05-28 20:06
I think it's pretty ridiculous that I can't *build* the version of the project from a couple months ago, but if that's going to be the case please note that in the CONTRIBUTING doc so people can save their time.

> such an old version
>
> I'm not willing to support any older versions though.

It's the same major version and it's from less than 2 months ago. So what does this mean, you can only expect to be able to build the latest patch version? HEAD? Whatever it means, please document it.

**Comment by sebmck** [comment] 2015-05-28 20:18
Come on dude, seriously? Stop being so hostile. You actually **can** build it, it's just that `make bootstrap` is trying to pull a git submodule that doesn't exist, you replaced it with `facebook/regenerator` and it worked, great. I'm sorry I wasted your time I guess? I know there's a lot missing from the docs and I really wish there was enough time to do everything but when I've explicitly asked for contributors (#1347) and gotten no new core contributors (although I'm **extremely** appreciative of people like @loganfsmyth etc who have stepped up to take on managing/resolving issues), then you really can't complain about lack of whatever.

**Comment by jmm** [comment] 2015-05-28 20:41
> Come on dude, seriously? Stop being so hostile.

I'm not being hostile. 

> You actually can build it, it's just that `make bootstrap` is trying to pull a git submodule that doesn't exist, you replaced it with `facebook/regenerator` and it worked, great.

Since I'm doing this in the first place to contribute, the time that I'm devoting to working on this would be more effective not spent on figuring that out. And as I explained, that resulted in failing tests (and who knows what other problems that aren't caught by tests), which defeats the purpose for me.

> I'm sorry I wasted your time I guess?

Wouldn't you prefer that people working on this be able to spend the time in more meaningful ways?

> I know there's a lot missing from the docs and I really wish there was enough time to do everything but when I've explicitly asked for contributors (#1347) and gotten no new core contributors (although I'm *extremely* appreciative of people like *@loganfsmyth* etc who have stepped up to take on managing/resolving issues), then you really can't complain about lack of whatever.

On a scale of 1-100 of complaining that goes on in issue reports (with 100 being the most), I'm "complaining" at like a level of 2. I asked for this to be documented so that anyone who does want to contribute (including myself) can spend the time on more important things. I read #1347 earlier today and I'm interested in contributing, hence why I was trying to build the project to debug a problem. If it helps you I'll PR the documentation I requested if you would be so kind as to elaborate your policy for me:

> So what does this mean, you can only expect to be able to build the latest patch version? HEAD?

Thanks for all of your work.

**Comment by gaearon** [comment] 2015-05-29 13:06
Babel is moving extremely fast, and has 21 open vs 1,333 closed issues. This is **extremely** good open/close ratio for an open source project, especially with a single person doing most of the bugfixes and features.

This would not be possible without extreme efforts from @sebmck focusing on today's version, instead of versions from months ago. If there is a bug in an older version you're trying to debug, you're just better off trying the new version instead, and if the bug is there too, please report it, and it will be fixed.

Mishaps like this may occur, but I can hardly imagine a situation in which manually building an old version makes more sense than just updating. Can you please clarify your use case?

>I asked for this to be documented so that anyone who does want to contribute (including myself) can spend the time on more important things.

Where would you prefer this to be documented? If you see a sensible place for it, please submit a PR. It doesn't seem to be that common of a problem though (can you find other issues about this?)

**Comment by gaearon** [comment] 2015-05-29 13:14
>I think it's pretty ridiculous that I can't build the version of the project from a couple months ago, but if that's going to be the case please note that in the CONTRIBUTING doc so people can save their time.

I agree it's a good idea to clarify this in `CONTRIBUTING`. Something like

>Babel moves fast. Only the latest release is guaranteed to build correctly.
>Older releases are not officially supported. If you attempt to build them, do that at your own risk.

What do you think? @sebmck

**Comment by sebmck** [comment] 2015-05-29 13:34
@gaearon I guess. I'm not arguing that nerfing that repo was a good idea, I'm just not sure why you'd want to build or use an older version. Knowing that something was introduced in whatever version isn't very helpful, espscially since the code has undergone significant architectural changes to accommodate the performance requirements of specific people and organisations.

**Closed** 2015-05-29 13:50 UTC

**Comment by jmm** [comment] 2015-05-29 15:27
@gaearon 
> Babel is moving extremely fast, and has 21 open vs 1,333 closed issues. This is **extremely** good open/close ratio for an open source project, especially with a single person doing most of the bugfixes and features.
> 
> This would not be possible without extreme efforts from @sebmck focusing on today's version, instead of versions from months ago. If there is a bug in an older version you're trying to debug, you're just better off trying the new version instead, and if the bug is there too, please report it, and it will be fixed.

That's all well and good and understood and appreciated. But keep in mind this whole issue revolves around A) deleting a repo and B) not mentioning in `CONTRIBUTING` that you can only expect to build the latest release.

> Mishaps like this may occur, but I can hardly imagine a situation in which manually building an old version makes more sense than just updating. Can you please clarify your use case?

Debugging. Between consecutive patch releases of the package, in which significant changes were introduced. I was going to begin by building v5.0.6 and running the tests from v5.0.7 (or more likely probably just from the next commit).

> It doesn't seem to be that common of a problem though (can you find other issues about this?)

I'm going to have to answer your question with a question: is anyone else showing up to try to solve these issues?:

https://github.com/babel/babelify/issues/81
https://github.com/substack/brfs/issues/39


> I agree it's a good idea to clarify this in `CONTRIBUTING`

Thank you. But, it's buried right now. It would be much more useful as the first thing in the **Developing** section.

@sebmck 
> I'm not arguing that nerfing that repo was a good idea

Then why not restore it?

> Knowing that something was introduced in whatever version isn't very helpful, espscially since the code has undergone significant architectural changes to accommodate the performance requirements of specific people and organisations.

You probably have a better approach to solving the issues I referenced above, so maybe I should just leave them alone and work on something else.

**Comment by gaearon** [comment] 2015-05-29 15:47
>I'm going to have to answer your question with a question: is anyone else showing up to try to solve these issues?:

To be honest I don't understand how they are related to this issue. I have probably missed your point :-)

>That's all well and good and understood and appreciated. But keep in mind this whole issue revolves around A) deleting a repo

I think we already reached the understanding that the repo being deleted does not happen every day, and there were special circumstances around it (it was not meant to be depended upon, but people started to). And that Babel is not willing to support building old versions because that might slow the project. (Dependencies might get incompatible updates, for example.)

> and B) not mentioning in CONTRIBUTING that you can only expect to build the latest release.

>But, it's buried right now. It would be much more useful as the first thing in the Developing section.

Please submit a PR to fix it then :-). Again, I don't see any other issues related to building old versions.

>Debugging. Between consecutive patch releases of the package, in which significant changes were introduced. I was going to begin by building v5.0.6 and running the tests from v5.0.7 (or more likely probably just from the next commit).

Debugging Babel? Why? Does it produce a buggy output or crash? File an issue. Are you maintaining a fork? Please help me understand the use case. :-(

**Comment by jmm** [comment] 2015-05-29 18:02
@gaearon 
> To be honest I don't understand how they are related to this issue. I have probably missed your point :-)

My point actually is that if I could've just built v5.0.6 we wouldn't even be having this conversation :) I'd be going about trying to solve the problem I'm trying to solve independently, the way I choose to go about it.

> how they are related to this issue
> ...
> Debugging Babel? Why? Does it produce a buggy output or crash?

Input:
```js
import fs from 'fs';

fs.readFileSync('whatever');
```

Output (last line) babel@5.0.6:
```js
fs.readFileSync('whatever');
```

Output (last line) babel@5.0.7:
```js
_fs2['default'].readFileSync('whatever');
```

You can see how this change in output could conceivably affect a tool that does static analysis (like brfs)? Perhaps that won't even prove to be relevant, but that's where I chose to start.

> File an issue

There's already an issue. On babelify. I linked to it: https://github.com/babel/babelify/issues/81

> Are you maintaining a fork?

No.

> Please help me understand the use case. :-(

I'm just going to work on other stuff and let you guys handle babel/babelify/issues/81 however you want.

**Comment by sebmck** [comment] 2015-05-29 18:07
That's not a bug at all and is completely intentional behaviour. See #1337.

**Comment by jmm** [comment] 2015-05-29 18:11
@sebmck 
> That's not a bug at all and is completely intentional behaviour. See #1337.
I'm well aware. I read that thread yesterday. I never said it's a bug.
