### ISSUE TITLE
Proposal: split optional 'runtime' into 'runtime.helpers' and 'runtime.polyfill'

### ISSUE THREAD

**Issue by fengb** [babel/babel#2417] opened 2015-09-23 05:42 UTC
I'm currently using **babelify** to transform my source code + global shimming **babel-core/browser-polyfill.js** through a vendor file.

I noticed redefinitions of _createClass [et al] and the docs mentioned to use `{ optional: 'runtime' }`, but this has the unfortunate side effect of also including **regenerator/core-js**, extending the dev build time.

It would be nice if I can define `{ optional: 'runtime.helpers' }` and have it include only the helpers.

**Comment by sebmck** [comment] 2015-09-23 16:07
Duplicate of #2059, #2001 and #1233.

**Closed by sebmck** 2015-09-23 16:07 UTC
Labels: enhancement
