### ISSUE TITLE
"optional": ["runtime"] does not shim Array.prototype functions

### ISSUE THREAD

**Issue by Nutelac** [babel/babel#2215] opened 2015-08-15 13:00 UTC
I have following config in package.json:
```json
...
"babel": {
  "optional": [
    "runtime"
  ]
},
...
```

which should add `Promise` and other classes. If I understand it correctly, it should also shim `Array.protoype functions`.

Unfortunatelly, it does not work:
```javascript
console.log(Promise) // Object
console.log(Array.prototype.find) // undefined
console.log(Array.find)) // Object
```

Why `Array.prototype.find` is undefined. Is there something what I missed? Thank you.

**Comment by loganfsmyth** [comment] 2015-08-15 14:52
Duplicate of https://github.com/babel/babel/issues/892.

Currently `runtime` only supports transforming things that can be picked up by statically analyzing the code. `foo.find()` could be an array, or could be a normal function, and Babel can't know at compile time which it is. Generally when using `runtime` people avoid using new ES6 `.prototype` functions.

In the future, questions are better asked in Slack or SO. From the README:

>  For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

**Closed by loganfsmyth** 2015-08-15 14:52 UTC
