### ISSUE TITLE
Decorator error: "Cannot set property" when no set action has been performed

### ISSUE THREAD

**Issue by gsklee** [babel/babel#1499] opened 2015-05-11 15:52 UTC
See [demo code](http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&playground=false&code=function%20autobind(target%2C%20key%2C%20descriptor)%20%7B%0A%20%20var%20fn%20%3D%20descriptor.value%3B%0A%20%20delete%20descriptor.value%3B%0A%20%20delete%20descriptor.writable%3B%0A%20%20descriptor.get%20%3D%20function%20()%20%7B%0A%20%20%20%20return%20this%5Bkey%5D%20%3D%20fn.bind(this)%3B%0A%20%20%7D%3B%0A%7D%0A%0Aclass%20Person%20%7B%0A%20%20first%20%3D%20%22Sebastian%22%3B%0A%20%20last%20%3D%20%22McKenzie%22%3B%0A%0A%20%20%40autobind%0A%20%20getFullName()%20%7B%0A%20%20%20%20return%20%60%24%7Bthis.first%7D%20%24%7Bthis.last%7D%60%3B%0A%20%20%7D%0A%7D%0A%0Aconsole.log(new%20Person().getFullName())%3B) which was taken straight from the blog post.

**Comment by sebmck** [comment] 2015-05-11 15:54
Duplicate of #1350 and #1310.

**Closed by sebmck** 2015-05-11 15:54 UTC
