### ISSUE TITLE
ERROR in ./src/main.js 

### ISSUE THREAD

**Issue by tanjinrong123** [babel/babel#8633] opened 2018-09-05 13:02 UTC
webpack-dev-server --inline --hot --open --port 8888
Module build failed (from ./node_modules/babel-loader/lib/index.js): Error: .plugins[1][1] must be an object, false, or undefined

**Comment by nicolo-ribaudo** [comment] 2018-09-05 13:05
Can you also provide your webpack config, your package.json and the complete error stack trace?

**Comment by tanjinrong123** [comment] 2018-09-05 13:28
[error.txt](https://github.com/babel/babel/files/2352914/error.txt)
@nicolo-ribaudo

**Comment by nicolo-ribaudo** [comment] 2018-09-05 14:11
The problem is that you ae using both Babel 6 and Babel 7, which are not compatible. You should choose one or the other.

**Comment by tanjinrong123** [comment] 2018-09-06 07:52
@.babelrc
{
"presets":["@babel/preset-env","stage-0"],
  "plugins":["@babel/plugin-transform-runtime",["component", [
    {
      "libraryName": "mint-ui",
      "style": true
    }
  ]]]
} @nicolo-ribaudo

**Comment by nicolo-ribaudo** [comment] 2018-09-06 08:01
`stage-0` is a Babel 6 preset. In Babel 7, you should replace it with the plugins you are actually using.

If you are not sure of what plugins you need, I suggest removing `stage-0` and building your project: Babel will throw a nice error with the name of the plug-in it needs.

**Comment by nicolo-ribaudo** [comment] 2019-05-07 15:32
Closing is this is causes by Babel 6 plugins being used with Babel 7.

**Closed by nicolo-ribaudo** 2019-05-07 15:32 UTC

**Comment by ooxiongoo** [comment] 2019-07-26 21:18
I have same issue, but mine is already Babel 7
