### ISSUE TITLE
npm install --save-dev @babel/parser

### ISSUE THREAD

**Issue by olee2002** [babel/babel#8844] opened 2018-10-11 16:33 UTC
Ok-Hyuns-MacBook-Pro:client olee$ npm install --save-dev @babel/parser
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/parser@^7.1.3
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@babel/traverse'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/olee/.npm/_logs/2018-10-11T16_32_17_220Z-debug.log

**Comment by benflodge** [comment] 2018-10-11 16:35
Duplicate of https://github.com/babel/babel/issues/8843

**Closed** 2018-10-11 16:36 UTC

**Comment by nikolas** [comment] 2018-10-11 16:39
@olee2002 @hzoo here's a temporary workaround: in your package.json, specify:

```
  "devDependencies": {
    "@babel/parser": "7.1.2",
    "@babel/traverse": "7.1.0",
```

I'd put this in the original issue (#8843) but discussion is locked.

**Comment by hzoo** [comment] 2018-10-11 16:41
yeah that would work. I'll mention it, thanks
