### ISSUE TITLE
do you still need transform runtime with this plugin?

### ISSUE THREAD

**Issue by kelly-tock** [babel/babel#13188] opened 2021-04-20 22:16 UTC
the examples have both. i'm currently having an issue where I upgraded core-js to 3, and it seems like transform-runtime is switching the order of things. I went down a rabbit hole of tracing circular dependencies, but found none. I did the first example of this, and took out transform runtime as well and the page I was having issues with is now fixed. 

old config:
```
module.exports = function buildPreset(context, options) {
  const env = process.env.BABEL_ENV || process.env.NODE_ENV || 'development';

  const plugins = [
    'babel-plugin-lodash',
    '@babel/plugin-proposal-class-properties',
    '@babel/plugin-proposal-export-namespace-from',
    '@babel/plugin-proposal-function-sent',
    '@babel/plugin-proposal-json-strings',
    '@babel/plugin-proposal-numeric-separator',
    '@babel/plugin-proposal-throw-expressions',
    '@babel/plugin-syntax-import-meta',
    '@babel/plugin-transform-runtime',
    '@babel/plugin-proposal-nullish-coalescing-operator',
    '@babel/plugin-proposal-optional-chaining',
  ];

  const isCommonJs = !!(options && options.modules === 'commonjs');

  if (env !== 'test' && !isCommonJs) {
    plugins.push(
      [
        'babel-plugin-import',
        {
          libraryName: '@material-ui/core',
          // Use "'libraryDirectory': ''," if your bundler does not support ES modules
          libraryDirectory: 'esm',
          camel2DashComponentName: false,
        },
        'core',
      ],
      [
        'babel-plugin-import',
        {
          libraryName: '@material-ui/icons',
          // Use "'libraryDirectory': ''," if your bundler does not support ES modules
          libraryDirectory: 'esm',
          camel2DashComponentName: false,
        },
        'icons',
      ],
      [
        'babel-plugin-import',
        {
          libraryName: 'ui/icons',
          // Use "'libraryDirectory': ''," if your bundler does not support ES modules
          libraryDirectory: '',
          camel2DashComponentName: false,
        },
        'uiicons',
      ]
    );
  }

  const presetEnvOptions = {
    loose: false,
    modules: false,
    useBuiltIns: 'usage',
    spec: false,
    corejs: 2,
    bugfixes: false,
    ...options,
  };

  const presets = [
    ['@babel/preset-env', presetEnvOptions],
    [
      '@babel/preset-react',
      {
        runtime: 'automatic',
      },
    ],
    '@babel/preset-typescript',
  ];

  if (env === 'production') {
    plugins.push(
      '@babel/plugin-transform-react-constant-elements',
      '@babel/plugin-transform-react-inline-elements'
    );
  }

  return {
    presets: presets,
    plugins: plugins,
  };
};

```

new config:

```
module.exports = function buildPreset(context, options) {
  const env = process.env.BABEL_ENV || process.env.NODE_ENV || 'development';

  const plugins = [
    'babel-plugin-lodash',
    '@babel/plugin-proposal-class-properties',
    '@babel/plugin-proposal-export-namespace-from',
    '@babel/plugin-proposal-function-sent',
    '@babel/plugin-proposal-json-strings',
    '@babel/plugin-proposal-numeric-separator',
    '@babel/plugin-proposal-throw-expressions',
    '@babel/plugin-syntax-import-meta',
    '@babel/plugin-proposal-nullish-coalescing-operator',
    '@babel/plugin-proposal-optional-chaining',
    [
      'polyfill-corejs3',
      {
        method: 'usage-global',
      },
    ],
  ];

  const isCommonJs = !!(options && options.modules === 'commonjs');

  if (env !== 'test' && !isCommonJs) {
    plugins.push(
      [
        'babel-plugin-import',
        {
          libraryName: '@material-ui/core',
          // Use "'libraryDirectory': ''," if your bundler does not support ES modules
          libraryDirectory: 'esm',
          camel2DashComponentName: false,
        },
        'core',
      ],
      [
        'babel-plugin-import',
        {
          libraryName: '@material-ui/icons',
          // Use "'libraryDirectory': ''," if your bundler does not support ES modules
          libraryDirectory: 'esm',
          camel2DashComponentName: false,
        },
        'icons',
      ],
      [
        'babel-plugin-import',
        {
          libraryName: 'ui/icons',
          // Use "'libraryDirectory': ''," if your bundler does not support ES modules
          libraryDirectory: '',
          camel2DashComponentName: false,
        },
        'uiicons',
      ]
    );
  }

  const presets = [
    '@babel/preset-env',
    [
      '@babel/preset-react',
      {
        runtime: 'automatic',
      },
    ],
    '@babel/preset-typescript',
  ];

  if (env === 'production') {
    plugins.push(
      '@babel/plugin-transform-react-constant-elements',
      '@babel/plugin-transform-react-inline-elements'
    );
  }

  return {
    presets: presets,
    plugins: plugins,
  };
};
```

is that the intended migration?

**Comment by nicolo-ribaudo** [comment] 2021-04-21 12:46
I moved this to the main Babel repo since it seems to be caused by many plugins interacting together in the wrong way.

If you disable `@babel/plugin-transform-react-constant-elements`, do you still see the error?

**Comment by kelly-tock** [comment] 2021-04-21 14:01
```
import { Box, FormControlLabel, FormHelperText, FormLabel } from '@material-ui/core';
import { Formik, FormikProps } from 'formik';
import { LocalTime } from 'js-joda';
import { makeStyles } from '@material-ui/core/styles';
import Button from 'ui/Button';
import Dialog from 'ui/Dialog';
import DialogActions from 'ui/DialogActions';
import DialogContent from 'ui/DialogContent';
import DialogForm from 'ui/DialogForm';
import DialogTitle from 'ui/DialogTitle';
import FormRadiobuttonGroup from 'ui/FormRadiobuttonGroup';
import GoodLocalTimeInput from 'shared/components/inputs/GoodLocalTimeInput';
import Radio from 'ui/Radio';
import React from 'react';

export interface RollingReleaseFormData {
  rollingReleaseDays: number;
  rollingReleaseTime: string;
}

// For conversion between data types for rollingReleaseDays
interface RollingReleaseFormDataInternal {
  rollingReleaseDays: string;
  rollingReleaseTime: string;
}

interface Props {
  open: boolean;
  rollingReleaseDays: number;
  rollingReleaseTime: ReduxFormFields<string>;
  title: string;
  onClose(): void;
  onUpdateAvailability(data: RollingReleaseFormData): void;
}

const useFormLabelStyles = makeStyles((theme) => ({
  formLabelRoot: {
    color: theme.colors.textBase,
    fontFamily: theme.font.medium,
    fontSize: theme.typography.pxToRem(18),
    lineHeight: 1.33,
    marginBottom: theme.spacing(1),
  },
  formHelperTextRoot: {
    marginTop: 0,
  },
}));

const RollingReleaseModal = ({
  open,
  rollingReleaseDays,
  rollingReleaseTime,
  title,
  onClose,
  onUpdateAvailability,
  ...rest
}: Props) => {
  const onUpdate = (values: RollingReleaseFormDataInternal) => {
    onUpdateAvailability({
      rollingReleaseDays: parseInt(values.rollingReleaseDays),
      rollingReleaseTime: rollingReleaseTime.value,
    });
  };
  const classes = useFormLabelStyles();
  return (
    <Formik
      initialValues={{
        rollingReleaseDays: rollingReleaseDays.toString(),
        rollingReleaseTime: rollingReleaseTime.value,
      }}
      onSubmit={onUpdate}
    >
      {(formikProps: FormikProps<RollingReleaseFormDataInternal>) => (
        <Dialog
          aria-labelledby="rolling-release-dialog-title"
          open={open}
          onClose={onClose}
          {...rest}
        >
          <DialogForm>
            <DialogTitle id="rolling-release-dialog-title">{title}</DialogTitle>
            <DialogContent>
              <Box mb={2}>
                <FormRadiobuttonGroup
                  name="rollingReleaseDays"
                  label="Automatic availability window"
                  helperText="Number of days your guests will be able to make reservations in the future."
                >
                  <FormControlLabel value="30" control={<Radio />} label="30 Days" />
                  <FormControlLabel value="60" control={<Radio />} label="60 Days" />
                  <FormControlLabel value="90" control={<Radio />} label="90 Days" />
                </FormRadiobuttonGroup>
              </Box>
              <fieldset>
                <FormLabel classes={{ root: classes.formLabelRoot }} component="legend">
                  Release Time
                </FormLabel>
                <GoodLocalTimeInput
                  field={rollingReleaseTime}
                  incrementsInMinutes={60}
                  minLocalTimeInclusive={LocalTime.of(0)}
                  maxLocalTimeInclusive={LocalTime.of(23)}
                />
                <FormHelperText classes={{ root: classes.formHelperTextRoot }}>
                  The time that the window will extend to the following day.
                </FormHelperText>
              </fieldset>
            </DialogContent>
            <DialogActions>
              <Button variant="text" size="large" color="secondary" onClick={onClose}>
                Cancel
              </Button>
              <Button type="submit" size="large">
                Update availability
              </Button>
            </DialogActions>
          </DialogForm>
        </Dialog>
      )}
    </Formik>
  );
};

export default RollingReleaseModal;
```

**Comment by kelly-tock** [comment] 2021-04-21 14:36
disabling that setting unblocks the page that that dialog is on!!!!

**Comment by kelly-tock** [comment] 2021-04-21 14:36
I also updated all versions of plugins to latest just as FYI.

**Comment by kelly-tock** [comment] 2021-04-21 14:37
webpack 5 latest as well with latest babel-loader.

**Comment by kelly-tock** [comment] 2021-04-21 16:04
wondering if I should run without that plugin for the time being.

**Comment by nicolo-ribaudo** [comment] 2021-04-21 16:07
That plugin is a performance optimization (it basically avoids re-constructing the JSX representation of constant JSX elements), but it's not used by everyone (I think for example Facebook itself doesn't use it), so it's safe to disable it if it until the problem is fixed.

**Comment by kelly-tock** [comment] 2021-04-21 16:08
noticing in my yarn lock that this got bumped up:
@babel/helper-hoist-variables@7.13.0 -> 7.13.16, maybe something there?

**Comment by kelly-tock** [comment] 2021-04-21 16:11
thanks for all your help on this BTW!!!

**Comment by nicolo-ribaudo** [comment] 2021-04-21 16:14
Could you try using the last version of `@babel/plugin-transform-react-constant-elements`? In 7.13.0 we made different changes that fixed many bugs related to variables ordering, but looking at your output it seems like you are using an older version.

**Comment by kelly-tock** [comment] 2021-04-21 16:38
Hm, thought I bumped everything, lemme double check!

**Comment by kelly-tock** [comment] 2021-04-21 16:43
You meant latest right?

**Comment by kelly-tock** [comment] 2021-04-21 17:15
i'm at 7.13.13 in my preset, but in my project I see 2 versions, 7.10.4(used by storybook, and an svg tool we use), and 7.13.13. maybe I need a yarn resolutions or regenerate lock file?

**Comment by kelly-tock** [comment] 2021-04-21 17:24
ugh, regenerating my lock file brought it back inline with the latest, and now that screen is working. I should have tried that trick as well!!!!

**Comment by nicolo-ribaudo** [comment] 2021-04-21 17:51
Good! If you are using Yarn 2, you can run `yarn dedupe` next time to update them in `yarn.lock`.

Just to be sure I'm understanding correctly, you can now build your app without removing any plugin, just by using the last version? (If yes, I'm going to close this issue as "already fixed")

**Comment by kelly-tock** [comment] 2021-04-21 17:56
yes, we can close. and you mean latest :)

**Closed** 2021-04-21 18:00 UTC
