### ISSUE TITLE
browser.js doesn't exist in the babel-core package!

### ISSUE THREAD

**Issue by bokisa12** [babel/babel#2961] opened 2015-11-10 16:15 UTC
When I download the babel-core package (npm install --save-dev babel-core), I can't find the browser.js file inside the node_modules/babel-core/ folder.

**Comment by hzoo** [comment] 2015-11-10 16:17
Duplicate of https://github.com/babel/babel/issues/2819 and others - there's a `babel-browser` package now

**Closed by hzoo** 2015-11-10 16:17 UTC
Labels: duplicate

**Comment by bokisa12** [comment] 2015-11-10 16:25
Thanks!

**Comment by bokisa12** [comment] 2015-11-10 16:25
Well, they should update their Browser Usage page, then: https://babeljs.io/docs/usage/browser/ .

**Comment by hzoo** [comment] 2015-11-10 16:26
Ok can you make an issue in the https://github.com/babel/babel.github.io repo?

**Comment by bokisa12** [comment] 2015-11-10 17:07
Made it: https://github.com/babel/babel.github.io/issues/559
