### ISSUE TITLE
Strict mode reserved words aren't detected in certain cases

### ISSUE THREAD

**Issue by jayphelps** [babel/babel#2202] opened 2015-08-12 04:30 UTC
It should always be [an early syntax error](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-identifiers-static-semantics-early-errors), but currently passes through babel without issue, only to error in compliant JS runtimes. These are the two cases I can find. Might be more.

> *Identifier*  **:**  *IdentifierName*  **but not**  *ReservedWord*
* It is a Syntax Error if this phrase is contained in strict mode code and the StringValue of *IdentifierName* is: `"implements"`, `"interface"`, `"let"`, `"package"`, `"private"`, `"protected"`, `"public"`, `"static"`, or `"yield"`.

[REPL](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&playground=true&code=%22use%20strict%22%3B%0A%0Aprivate%3B%0A%0Aclass%20Foo%20%7B%0A%20%20%40private%0A%20%20bar()%20%7B%7D%0A%7D&stage=0)
```js
private;

class Foo {
  @private
  bar() {}
}
```

**Comment by shakaIsReal** [comment] 2016-09-20 09:09
@jayphelps Hi, I currently have issues with filenames. Babel doesn't seem to compile files containing any of your "reserved words". For example I've got file `getPublicKey.js`, not matter what I did, having the word `public` (capital or camel case) it didn't compile it! And no warnings!? This should be fixed ASAP. Talking code wise "reserved keyword" are fine. But not for filenames...

**Comment by danez** [comment] 2016-09-20 09:18
The original issue is resolved as babylon is now throwing Syntax Errors for reserved words.

@jayphelps I cannot reproduce this. Just used this and it worked fine: `babel getPublicKey.js --out-file script-compiled.js`

**Closed by danez** 2016-09-20 09:18 UTC

**Comment by shakaIsReal** [comment] 2016-09-20 18:21
@danez thanks, actually the I had an issue with `--ignore node_modules,public`!!! `public` was the problem, it's regex! So I changed it to `--ignore node_modules/*,public/*` so it's invoked for folders only :)
