### ISSUE TITLE
Decorators are broken in 6.x

### ISSUE THREAD

**Issue by alexbyk** [babel/babel#2727] opened 2015-11-01 21:37 UTC
I tried several combinations. Nothing works:
```javascript
function decorator(Class) { return Class; }

@decorator
class B { }
```

```json
{
  "presets": ["es2015", "stage-0"],
  "plugins": [ "transform-decorators", "syntax-decorators"]
}
```

result (decorator just silently ignored):
```javascript
...
var B = function B() {
  _classCallCheck(this, B);
};
```

with this order: ``` ["stage-0", "es2015"]```
it throws an error ```TypeError: src/mxn/decorators.func.test.js: Property right of AssignmentExpression expected node to be of a type ["Expression"] but instead got "Decorator"```

**Comment by sebmck** [comment] 2015-11-01 22:05
Duplicate of #2645.

**Closed by sebmck** 2015-11-01 22:05 UTC
