### ISSUE TITLE
Option for node environment

### ISSUE THREAD

**Issue by leebyron** [babel/babel#1935] opened 2015-07-07 01:03 UTC
The node environment has an important quirk that changes how parsing should be done: the document is actually wrapped in a function.

This code is illegal to run in a browser, but legal to run in node.

```js
if (Date.now() > 1445410800000) {
  return;
}
console.log("Back to the Future 2 is relevant");
```

Babel should have a flag like `--node` to distinguish this, and the `babel-node` cli should have this on by default.

**Comment by loganfsmyth** [comment] 2015-07-07 01:54
Babel treats all parsed code as an ES6 Module, and modules are top-level entries, they have no function wrapper, so `return`ing inside one is not allowed, and allowing it would mean that you have an invalid ES6 module.

**Comment by leebyron** [comment] 2015-07-07 01:59
I understand that. The problem is when `babel-node` encounters a file that was perhaps not intended to be babelified and uses this node-ism. Then you get noisy parse errors.

**Comment by loganfsmyth** [comment] 2015-07-07 02:02
This type of thing is the indented use of the `ignore` option then, so you can tell babel what files to skip processing.

**Comment by leebyron** [comment] 2015-07-07 02:12
the `ignore` option doesn't seem to be doing the job.

Example in question:

```
> babel-node --ignore node_modules -- node_modules/.bin/isparta cover --report html node_modules/.bin/_mocha -- $npm_package_options_mocha

Transformation error; return original code
{ [SyntaxError: /Users/leebyron/src/graphql-js/node_modules/mocha/bin/_mocha: 'return' outside of function (392:2)]
  pos: 9902,
  loc: { line: 392, column: 2 },
  raisedAt: 9908,
  _babel: true,
  codeFrame: '  390 |   \u001b[32m}\u001b[39m\u001b[34m\u001b[1m)\u001b[22m\u001b[39m\u001b[1m;\u001b[22m\n  391 | \n> 392 |   \u001b[36mreturn\u001b[39m\u001b[1m;\u001b[22m\n      |   ^\n  393 | \u001b[32m}\u001b[39m\n  394 | \n  395 | \u001b[90m// load\u001b[39m' }
```

Shouldn't `--ignore node_modules` have suggested `babel-node` ignore the `_mocha` file it's choking on?

**Comment by loganfsmyth** [comment] 2015-07-07 02:20
Ah good to know, should have just reported that :) That could be a regression then, since I know the behavior of ignore has had some changes recently. @sebmck can probably add a bit more.

**Comment by leebyron** [comment] 2015-07-07 02:23
Also reported here https://github.com/douglasduteil/isparta/issues/47 for good measure

**Comment by loganfsmyth** [comment] 2015-07-07 03:04
Given my comment over there, this seems more like an issue with `isparta`/`istanbul` that with `babel`, so I'm going to close this. Feel free to re-open if that changes though.

**Closed by loganfsmyth** 2015-07-07 03:04 UTC
