### ISSUE TITLE
ERROR in ./src/index.js Module build failed (from ./node_modules/babel-loader/lib/index.js):

### ISSUE THREAD

**Issue by itzik415** [babel/babel#9775] opened 2019-03-27 17:15 UTC
I deconstructed my Create-React-App with Webpack 4 & Babel 7. The first time I ran the command "npm run build" it worked and created a new build folder. Now after the first time I am trying to run the command again and I am getting the error blow.

ERROR in ./src/index.js Module build failed (from ./node_modules/babel-loader/lib/index.js):

I searched for the solution but all I could find was babel versions discrepancy in Package.json file, something that I don't seem to have.

**Comment by nicolo-ribaudo** [comment] 2019-03-27 17:46
Duplicate of https://github.com/babel/babel/issues/9776

**Closed by nicolo-ribaudo** 2019-03-27 17:46 UTC
Labels: i: bug, i: needs triage
