### ISSUE TITLE
Execution order with async functions/then isn' the same with the origin code

### ISSUE THREAD

**Issue by MondoGao** [babel/babel#8938] opened 2018-10-29 03:32 UTC
## Bug Report

**Current Behavior**

Compiled code's execution order with async functions isn' the same with the origin code. More detail below.

Origin:
![image](https://user-images.githubusercontent.com/3753893/47627957-f863ac00-db6d-11e8-8da3-99b06e39bdbb.png)

Compiled:
![image](https://user-images.githubusercontent.com/3753893/47627961-fef22380-db6d-11e8-9c41-b34f0275bd15.png)

**Input Code**
- [REPL or Repo link if applicable](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=IYZwngdgxgBAZgV2gFwJYHsI1JKBGACgEoYBvAKBhikxGRgAcYBebcaAJmMsYDpkAFgFMIBYiwB81WugA2Q3rPQBzAgHIcnGHjoxBItUSI9gAd2Cp6DHjQgg5Cpao3soHbHGRCATtnOXDcgBfcnJNWEQUDCxwrhIKKlt7eUUVdVjAkLDXQmMIIVMYAAVvdABbVBAhAm8hZIA3IUkyGxkUp3UObwATRlKKqpgBYAhu-W9AqlqG6uMgon5hUXFmKQTpOwdU5y7ehn7Kpp16fQhMoiA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=6.26.0&envVersion=)

```js
async function async1() {
  const p = async2()
  p.then(() => console.log('async2 1st then'))
  await p
  console.log('async2 after await')
}

async function async2() {
  console.log('async2')
}

async1()
new Promise(resolve => {
  console.log('2rd promise handler')
  resolve()
}).then(() => {
  console.log('2rd promise 1st then')
})
```

**Expected behavior/code**

The above code should behave exactly the same, as in Chrome 71+:
![image](https://user-images.githubusercontent.com/3753893/47627886-9efb7d00-db6d-11e8-8cab-0b2fc80f3d89.png)

**Environment**
- Babel version(s): 6.26.0
- Node/npm version: Node 11
- Chrome: 71

**Additional context/Screenshots**

The behavior was inconsistent in older versions of node and chrome, but now they seem to be aligned.

**Comment by nicolo-ribaudo** [comment] 2018-10-30 22:06
@babel-bot Move to facebook/regenerator

**Comment by nicolo-ribaudo** [comment] 2018-10-30 22:13
If anyone wants to fix this bug, it is probably a problem with the `_asyncToGenerator` helper. I suggest debugging this by only enabling `@babel/plugin-transform-async-to-generator`, since `regenerator` (used by the presets) adds a lot of noise.

**Comment by nicolo-ribaudo** [comment] 2018-11-18 21:35
I think that the current Babel implementation is correct per the current spec, but it needs to be updated as soon as https://github.com/tc39/ecma262/pull/1250 is merged.

**Comment by nicolo-ribaudo** [comment] 2018-11-18 22:00
NOTE: If anyone wants to work on this issue, please consider also https://github.com/tc39/ecma262/pull/1250.

**Comment by pnowak** [comment] 2019-03-07 19:39
Strange thing, but in Chrome 72 expected behavior was changed and behave just like complied code: ```
async2
2rd promise handler
async2 1st then
async2 after await
2rd promise 1st then```

On Firefox 64 is like expected.

**Comment by jridgewell** [comment] 2019-03-07 19:45
Because the spec removed the extra tick when awaiting native promises, Babel's behavior is the correct behavior. Fixed for free!

**Comment by zloirock** [comment] 2019-03-07 19:58
I think that makes sense to add a test for this behavior to `compat-table`.

**Comment by nicolo-ribaudo** [comment] 2019-05-14 20:40
As Justin mentioned, this is correct now.

**Closed by nicolo-ribaudo** 2019-05-14 20:40 UTC
Labels: Spec: Async Functions, i: bug
