### ISSUE TITLE
preset-react v7 build error

### ISSUE THREAD

**Issue by caub** [babel/babel#6945] opened 2017-12-01 14:11 UTC
Mentioning this error I have, since I haven't found it in issues, while trying to update babel to use [jsx fragments](https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html)

I'm using a valid webpack config, running webpack fails with:
```
ERROR in ./app/index.js
Module build failed: TypeError: Cannot read property 'throwIfNamespace' of undefined (While processing preset: "/home/caub/dev/projX/node_modules/@babel/preset-react/lib/index.js")
    at _default (/home/caub/dev/projX/node_modules/@babel/plugin-transform-react-jsx/lib/index.js:15:36)
```

.babelrc
```json
{
	"presets": [
		"@babel/preset-react",
		[
			"@babel/preset-env",
			{
				"targets": {
					"browsers": ["last 2 versions", "not ie > 0", "not Android > 0"]
				}
			}
		]
	]
}
```

package.json
```json
"@babel/core": "^7.0.0-beta.32",
"@babel/preset-env": "^7.0.0-beta.32",
"@babel/preset-react": "^7.0.0-beta.32",
"@babel/preset-stage-3": "^7.0.0-beta.32",
```

| software         | version(s)
| ---------------- | -------
| Babel            |  @7.0.0-beta.32
| node             | 9.2
| npm              | 5.5.1
| Operating System |  Linux

**Comment by stephen-last** [comment] 2017-12-01 14:29
This could be the same issue as one I submitted earlier:  https://github.com/babel/babel/issues/6944

Does your error stack trace mention:

`node_modules\babel-core\lib\transformation\file\options\option-manager.js`..?

**Comment by hzoo** [comment] 2017-12-01 14:33
Probably because it's only in a later version of `@babel/core` that options are passed. Something in node_modules is requiring an old babel-core.

**Comment by caub** [comment] 2017-12-01 14:55
full stack trace:

```
ERROR in ./app/index.js
Module build failed: TypeError: Cannot read property 'throwIfNamespace' of undefined (While processing preset: "/home/caub/dev/projX/node_modules/@babel/preset-react/lib/index.js")
    at _default (/home/caub/dev/projX/node_modules/@babel/plugin-transform-react-jsx/lib/index.js:15:36)
    at Function.memoisePluginContainer (/home/caub/dev/projX/node_modules/babel-core/lib/transformation/file/options/option-manager.js:113:13)
    at Function.normalisePlugin (/home/caub/dev/projX/node_modules/babel-core/lib/transformation/file/options/option-manager.js:146:32)
    at /home/caub/dev/projX/node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/home/caub/dev/projX/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/home/caub/dev/projX/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at /home/caub/dev/projX/node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:14
    at /home/caub/dev/projX/node_modules/babel-core/lib/transformation/file/options/option-manager.js:323:22
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/home/caub/dev/projX/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/home/caub/dev/projX/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/home/caub/dev/projX/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/home/caub/dev/projX/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/home/caub/dev/projX/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/home/caub/dev/projX/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/home/caub/dev/projX/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/home/caub/dev/projX/node_modules/babel-loader/lib/index.js:50:20)
    at Object.module.exports (/home/caub/dev/projX/node_modules/babel-loader/lib/index.js:175:20)
 @ multi ./app/index.js ./app/index.scss
```

**Comment by hzoo** [comment] 2017-12-01 14:57
at Pipeline.transform (/home/caub/dev/projX/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/home/caub/dev/projX/node_modules/babel-loader/lib/index.js:50:20)

babel-loader is using babel-core not `@babel/core`, you'll have to use `babel-loader@8.0.0-beta.0` because it's a breaking change for us otherwise to switch from `@babel/core` and `babel-core`. although we could try the bridge package still

**Comment by caub** [comment] 2017-12-01 14:57
ah ok, thanks perfect, I'll let you close maybe

**Comment by stephen-last** [comment] 2017-12-01 15:05
I'm using `babel-loader@8.0.0-beta.0` already... 

Currently searching for other deps that may use `babel-core`...

**Comment by hzoo** [comment] 2017-12-01 15:50
> because the article said

What article?

**Comment by caub** [comment] 2017-12-01 15:54
The one linked in first message

**Comment by hzoo** [comment] 2017-12-01 15:56
Yeah that was true until we switched to scoped packages. Like I said before, `babel-loader` v7 had a peerDep on `babel-core` which is what causes the error. We can't just do a patch version because that would break everyone so we made it a v8 change.

**Comment by existentialism** [comment] 2017-12-01 15:59
@caub we recognize it's confusing, but just to be clear, jsx fragment syntax (as the article states) requires Babel 7. You will need to use `babel-loader@8.x`, however, for the reasons @hzoo just mentioned.

**Comment by stephen-last** [comment] 2017-12-01 16:20
Should using `webpack.config.babel.js` still work with babel 7..?

Does doing this still look for `babel-loader`..?

I'm getting `SyntaxError: Unexpected token import`.

**Comment by hzoo** [comment] 2017-12-02 14:08
Closing since the issue is that people are using `babel-loader` v7 which uses `babel-core` not `@babel/core`.

webpack.config.babel.js also uses `babel-core` which is probably why it doesn't work.

I found out about https://github.com/js-cli/js-interpret/pull/47 which gulp/webpack uses to do babel-register/`@babel/register`. It was updated recently

**Closed by hzoo** 2017-12-02 14:08 UTC

**Comment by caub** [comment] 2017-12-02 15:47
Thanks yes babel-loader ^8.0.0-beta.0 worked fine, it build fine
The only remaining points is to add better support for eslint and editors for fragments

```jsx
const f = (
  <>
    <span>test</span>
    <div>
      foo
    </div>
  </>
)
```

**Comment by mnpenner** [comment] 2018-01-23 18:43
I still can't get React to work with Babel 7. Here's what I've got:

package.json

```json
  "devDependencies": {
    "@babel/cli": "^7.0.0-beta.38",
    "@babel/core": "^7.0.0-beta.38",
    "@babel/plugin-proposal-class-properties": "^7.0.0-beta.38",
    "@babel/plugin-proposal-function-bind": "^7.0.0-beta.38",
    "@babel/plugin-proposal-object-rest-spread": "^7.0.0-beta.38",
    "@babel/plugin-syntax-jsx": "^7.0.0-beta.38",
    "@babel/plugin-transform-react-display-name": "^7.0.0-beta.38",
    "@babel/plugin-transform-react-jsx": "^7.0.0-beta.38",
    "@babel/plugin-transform-react-jsx-self": "^7.0.0-beta.38",
    "@babel/plugin-transform-react-jsx-source": "^7.0.0-beta.38",
    "@babel/preset-env": "^7.0.0-beta.38",
    "autoprefixer": "^7.2.5",
    "babel-loader": "^8.0.0-beta.0",
    "file-loader": "^1.1.6",
    "lodash": "^4.17.4",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-hot-loader": "^3.1.3",
    "styled-components": "^3.0.2",
    "svg-url-loader": "^2.3.1",
    "url-loader": "^0.6.2",
    "webpack": "^3.10.0",
    "webpack-dev-server": "^2.11.1"
  }
```

.babelrc

```json
{
  "plugins": [
    "@babel/plugin-proposal-object-rest-spread",
    "@babel/plugin-syntax-jsx",
    "@babel/plugin-transform-react-jsx",
    "@babel/plugin-transform-react-display-name",
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-proposal-function-bind"
  ],
  "presets": [
    [
      "env",
      {
        "targets": {
          "browsers": "last 2 chrome versions"
        }
      }
    ]
  ],
  "compact": false,
  "env": {
    "development": {
      "plugins": [
        "react-hot-loader/babel",
        "@babel/plugin-transform-react-jsx-self",
        "@babel/plugin-transform-react-jsx-source"
      ]
    }
  }
}
```

And the error:

```
NODE_ENV=development npx webpack-dev-server
Cannot read property 'useBuiltIns' of undefined
```

**Comment by caub** [comment] 2018-01-23 19:03
see my comment just above with `babel-core@7.0.0-bridge.0`

**Comment by daviddelusenet** [comment] 2018-03-14 11:19
My Jest setup was throwing the ` Cannot read property 'throwIfNamespace' of undefined` error. 

Installing `babel-core` with the `npm i -D babel-core@7.0.0-bridge.0` command solved it for me. 

Now I'm just wondering: what did this install fix?

Thanks!

**Comment by loganfsmyth** [comment] 2018-03-14 16:53
Yes using `babel-core@7.0.0-bridge.0` is required for `babel-jest` with Babel 7 because we renamed the package to `@babel/core` and Jest expects `babel-core`. The bridge package just passes through to `@babel/core`.

**Comment by daviddelusenet** [comment] 2018-03-15 08:43
@loganfsmyth thanks for the explanation!
