### ISSUE TITLE
Compiler bug when use for..of with System.js modules

### ISSUE THREAD

**Issue by Gerhut** [babel/babel#1956] opened 2015-07-09 12:08 UTC
This [gist](https://gist.github.com/Gerhut/0a5b94f81b84617ac23c) records my input file & output files when using `common` and `system` module option.

In [Line 31 of output-common.js](https://gist.github.com/Gerhut/0a5b94f81b84617ac23c#file-output-common-js-L31), it compiles 'for (let b of a())' to
```js
for (var _iterator = a()[Symbol.iterator](), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true)
```

But in [Line 37 of output-system.js](https://gist.github.com/Gerhut/0a5b94f81b84617ac23c#file-output-system-js-L37), it compiles to 
```js
for (_iterator; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true)
```
without initialize of `_iterator`, lead to a `Cannot read property 'next' of undefined()` error.

My Babel compiler version is 5.6.14

Thank you for your work.

**Comment by sebmck** [comment] 2015-07-09 12:10
Duplicate of #1929 that was fixed via #1936.

**Closed by sebmck** 2015-07-09 12:10 UTC
