### ISSUE TITLE
browser-polyfill.js should be released as a bower package

### ISSUE THREAD

**Issue by MetaMemoryT** [babel/babel#1281] opened 2015-04-16 18:06 UTC
This would improve support for build processes that use https://www.npmjs.com/package/main-bower-files

**Comment by sebmck** [comment] 2015-04-16 18:08
Duplicate of #315.

**Closed by sebmck** 2015-04-16 18:08 UTC

**Comment by rainabba** [comment] 2017-04-15 00:08
"It encourages bad habits (among other reasons)" (from one of the multiple issues opened regarding this).

Why? If my alternative is to npm install and then concat, why does it matter if I'm using NPM or bower from  your perspective? My standard is to use bower from client-side code so I'd prefer bower, but ultimately you're not encouraging OR dissuading this use by denying these requests and locking issues. 

The locking of issues where this is being discussed (reasonably and productively) is frustrating itself.
