### ISSUE TITLE
@babel/preset-env fails to polyfill IE11 for debug module, version 4

### ISSUE THREAD

**Issue by qiulang** [babel/babel#10707] opened 2019-11-14 04:02 UTC
## Bug Report

I created a simple app to demo this problem(using vue-cli), https://github.com/qiulang/IE11
If I use[ debug module](https://github.com/visionmedia/debug) v3, IE11 can correctly show the page. But if I use v4 IE shows a blank page.

I don't know where I did wrong but I suspect this is a bug.

**Input Code**

Check https://github.com/qiulang/IE11/blob/master/src/main.js
Just import debug module

**Babel Configuration (.babelrc, package.json, cli command)**

Check here for babel setting  https://github.com/qiulang/IE11/blob/master/babel.config.js

```js
"@babel/preset-env",
      {
        useBuiltIns: "entry",
        debug: true,
        corejs: 3,
        modules: false,
        targets: {
          chrome: "68",
          ie: "11"
        }
      }
```

**Environment**

```
~ ➤ vue info

Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  Binaries:
    Node: 10.13.0 - /usr/local/bin/node
    Yarn: 1.12.1 - /usr/local/bin/yarn
    npm: 6.6.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 78.0.3904.97
    Firefox: 70.0.1
    Safari: 13.0.3
  npmGlobalPackages:
    @vue/cli: 4.0.5
```

**Additional context/Screenshots**

From here socketio/socket.io-client#1328 (comment) it said

> This happened after updating debug from v3 to v4 which uses spread operator in its distributable.

But why does babel fail to polyfill that ?

**Comment by JLHwung** [comment] 2019-11-14 15:19
> But why does babel fail to polyfill that ?

By default babel does not transpile the third party codes in `node_modules`. You may add the `ignore` config to `babel.config.js` if you would like to transpile `debug` module:
```
ignore: /node_modules\/(?!debug)/
```

**Comment by qiulang** [comment] 2019-11-15 01:41
@JLHwung I tried that but it did not work. Actually vue has a [transpileDependencies 
 setting](https://cli.vuejs.org/config/#transpiledependencies) did the same and you can see I set that in my [pakage.json](https://github.com/qiulang/IE11/blob/master/package.json) 

But anyway I sei ignore as you said. But I got the same error in IE 11

```
SCRIPT1002: Syntax error
chunk-vendors.js (4887,1)

/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

eval("/* WEBPACK VAR INJECTION */(function(process) {/* eslint-env browser */\n\n/**\n * This is the web browser implementation of `debug()`.\n */\n\nexports.log = log;

```

The **no static exports found** error. But if I switch to debug 3.2.5 it works.

That is why I suspect it maybe a bug.

**Comment by JLHwung** [comment] 2019-11-15 02:34
In https://github.com/qiulang/IE11/blob/master/package.json#L55, consider to revise it to
```js
"transpileDependencies": [
      "debug"
    ]
```
since `debug` offers a [`browsers` field](https://github.com/visionmedia/debug/blob/master/package.json#L50) and `debug/index` would not match any file.

**Comment by qiulang** [comment] 2019-11-15 03:30
No I have to use "debug/index" otherwise I will get the error message (I have hit this problem many times!)

"export 'debug' was not found in 'debug'“ 

```
WARNING  Compiled with 1 warnings                                                                   

 warning  in ./src/main.js

"export 'default' (imported as 'debug') was not found in 'debug'


  App running at:
  - Local:   http://localhost:8081/ 
  - Network: http://10.0.0.132:8081/
```

and even chrome can open the page, with 

```
Uncaught ReferenceError: exports is not defined
    at Module.eval (browser.js?34eb:7)
    at eval (browser.js:195)
    at Module../node_modules/debug/src/browser.js (chunk-vendors.js:2808)
    at __webpack_require__ (app.js:786)
    at fn (app.js:151)
    at eval (main.js:12)
    at Module../src/main.js (app.js:1085)
    at __webpack_require__ (app.js:786)
    at fn (app.js:151)
    at Object.1 (app.js:1099)
```

**Comment by qiulang** [comment] 2019-11-15 03:32
But anyway I had changed to add ignore in babel.config.js (and delete transpileDependencies) so I think it is not the reason

**Comment by JLHwung** [comment] 2019-11-15 04:08
The `transpileDependencies` setting is necessary otherwise `babel-loader` will not feed `debug/src/*.js` to babel. The `ignore` config is not necessary because `babel-loader` is now in charge of what should be processed.

The error `ReferenceError: exports is not defined` is thrown from https://github.com/visionmedia/debug/blob/608fca962b34e2bda841db9a4416bab6b4a62803/src/browser.js#L7, which should be considered a bug of `debug` because browser does not ship CommonJS `exports`.

As a workaround, you can instruct babel to process `debug/**/*.js`. The trick here is to use `overrides` options since we have to process commonjs exports, which is different from app codes.

```js
overrides: [{
  test: "./node_modules/debug/**/*.js",
  presets: [
    ["@babel/preset-env", { modules: "commonjs", /* other options */ }]
  ]
}]
```

**Comment by qiulang** [comment] 2019-11-15 04:37
Hi I just can't make it work for IE 11, still SCRIPT1002: Syntax error

Can you take a look at my change https://github.com/qiulang/IE11/commit/83313413d5750698d4a6908c73048922f4264de5
to see if I have done anything wrong ?

**Comment by JLHwung** [comment] 2019-11-16 01:51
> Can you take a look at my change qiulang/IE11@8331341 to see if I have done anything wrong ?

Yep, see https://github.com/qiulang/IE11/commit/83313413d5750698d4a6908c73048922f4264de5#r35974825

**Comment by qiulang** [comment] 2019-11-17 04:17
Hi, with your help I finally made it work for IE 11. Thanks you very much!

But I still have some questions:
 
**1. Do I need to` import "core-js";` in my main.js or not ?**

If I do not import it, babel complains "Import of core-js was not found."

>  WAIT  Compiling...                                                                                  
> 
> 10% building 0/1 modules 1 active ...es/eslint-loader/index.js??ref--13-0!/Users/qiulang/Dev/ie11/src/main.js
> [/Users/qiulang/Dev/ie11/src/main.js] Import of core-js was not found.

But IE still shows my page correctly.

What confused me more is if I` import "@babel/polyfill"` instead of `import "core-js"` (as many articles I googled) babel said **Please remove the direct import of `core-js`**

> `@babel/polyfill` is deprecated. Please, use required parts of `core-js`
>   and `regenerator-runtime/runtime` separately
> 
>   When setting `useBuiltIns: 'usage'`, polyfills are automatically imported when needed.
>   Please remove the direct import of `core-js` or use `useBuiltIns: 'entry'` instead.

**2. Should I set `modules:false` or  `modules: auto` in `"@babel/preset-env"` ?**
I find either one works, but I also remember I read some articles saying webpack expect it to be false.

I read though this https://github.com/babel/babel-loader/issues/521 and still don't get a clue

**3. Do I need ["@vue/cli-plugin-babel/preset"](https://cli.vuejs.org/migrating-from-v3/#vue-cli-plugin-babel-vue-babel-preset-app) or not ?** It seems to work when I do not add it in presets array

**Comment by nicolo-ribaudo** [comment] 2019-11-17 08:53
`module: auto` means "whatever Babel's caller wants". Since webpack wants ES modules, in this case auto and false are the same thing.

**Comment by Qix-** [comment] 2019-11-19 15:36
> which should be considered a bug of debug because browser does not ship CommonJS exports.

53 million downloads a week and 1 user has a problem with their bundler != a bug in `debug`. I already get a bunch of spam over there, I don't need any more fuel added to that fire.

Most bundlers for the browser support CJS bundling. It's either that or we move to ESM exports at `debug` which will cause a horde of angry users with `"debug": "*"` in their package.json files blaming me for breaking their apps.

It's one of those situations where I need to pick my battles. `debug` does not have a bug w.r.t how it exports things - there is nothing actionable there.

**Comment by nicolo-ribaudo** [comment] 2019-11-19 23:23
Note that the suggested configuration can be modified to tell Babel that `debug` already uses CommonJS:
```json5
overrides: [{
  test: "./node_modules/debug/**/*.js",
  sourceType: "script",
  presets: [
    ["@babel/preset-env", { /* other options */ }]
  ]
}]
```

**Comment by christophermiles** [comment] 2019-12-04 05:11
> **1. Do I need to` import "core-js";` in my main.js or not ?**
> 
> If I do not import it, babel complains "Import of core-js was not found."

> What confused me more is if I` import "@babel/polyfill"` instead of `import "core-js"` (as many articles I googled) babel said **Please remove the direct import of `core-js`**
> 
> > `@babel/polyfill` is deprecated. Please, use required parts of `core-js`
> > and `regenerator-runtime/runtime` separately
> > When setting `useBuiltIns: 'usage'`, polyfills are automatically imported when needed.
> > Please remove the direct import of `core-js` or use `useBuiltIns: 'entry'` instead.
> 
> **2. Should I set `modules:false` or `modules: auto` in `"@babel/preset-env"` ?**
> I find either one works, but I also remember I read some articles saying webpack expect it to be false.
> 
> I read though this [babel/babel-loader#521](https://github.com/babel/babel-loader/issues/521) and still don't get a clue
> 
> **3. Do I need ["@vue/cli-plugin-babel/preset"](https://cli.vuejs.org/migrating-from-v3/#vue-cli-plugin-babel-vue-babel-preset-app) or not ?** It seems to work when I do not add it in presets array

@qiulang Did you get answer to any of these questions? Especially question 1? I am struggling with something similar and am finding the documentation extremely confusing and contradictory.

**Comment by qiulang** [comment] 2019-12-04 07:23
@chadhietala sadly no, or I will have closed my issue :(

**Comment by qiulang** [comment] 2019-12-04 07:25
@christophermiles sadly no, or I will have closed my issue :(

**Comment by 0xEther** [comment] 2020-01-31 08:44
I am having the exact same problem as described. The debug package is not compiling in babel to rid it of those arrow functions and `let` declarations. Breaks the application in IE11.

**Comment by nicolo-ribaudo** [comment] 2020-01-31 09:23
What's your config?

**Comment by 0xEther** [comment] 2020-01-31 11:12
The issue I had was the use of debug as a dependency in the socket.io-client module. Updated to 1.6.0 and it resolved.

Have also since read that downgrading to debug@3.2.6 works.

**Comment by Qix-** [comment] 2020-01-31 11:40
Downgrading is not a solution. Are you building node modules too? Or just your own code?

**Comment by 0xEther** [comment] 2020-02-01 12:49
Just my own code; I attempted everything under the sun to transpile debug down to ES2015 and nothing worked.

**Comment by Qix-** [comment] 2020-02-01 17:51
I'm still entirely confused. `debug` doesn't do anything special with how it exports functions.

This needs an official Babel response - I can't debug vague bug reports, sorry guys. 

Please keep in mind - most issues with `debug` aren't specific to `debug` - it's just that it's one of the most used packages on npm, and thus one of the first things people see when they have bad configurations. I have said it a thousand times but nobody seems to listen: **`debug` does _nothing_ special when it comes to exports.**

**Comment by dominiczaq** [comment] 2020-02-01 18:13
Yep. The problem reported in this issue is connected with not transpiling whole node modules. Even if the export of debug was changed, you're going to get the same error from different package.

To transform whole node modules instead of just your app change .babelrc to babel.config.js and configure your webpack accordingly.

Apart from fixing this issue you'll have more flexibility in how you ship your apps (i.e. prepare different bundles for modern and old browsers)

**Comment by nicolo-ribaudo** [comment] 2020-02-02 10:17
I agree that this is not a `debug` bug, but a problem with how Babel has been configured.

If you configure Babel to transpile node modules but it still isn't working, please provide a minimal repository I can clone to investigate.

Since the original one has been fixed by @JLHwung I'm going to close this issue, but feel free to attach a reproduction here.

**Closed by nicolo-ribaudo** 2020-02-02 10:17 UTC
Labels: i: question
