### ISSUE TITLE
Decorators && Imports && Hygiene

### ISSUE THREAD

**Issue by joehannes** [babel/babel#1192] opened 2015-04-07 21:13 UTC
As described in the gitter.im channel [7. April 2015 16:12 Uhr](https://gitter.im/babel/babel?at=55243a3438224c543c15dbc4) ...
Summary:
The @Annotation doesn't receive hygiene treatment such as other vars do on actually pointing to an import ...

**Comment by sebmck** [comment] 2015-04-07 21:16
Not sure I understand the issue. Can you please provide code examples?

**Comment by loganfsmyth** [comment] 2015-04-07 21:38
From his gitter post:

```
import { Service, DataService } from "joehannes/ng-harmony";

@Service()
export class MyService extends DataService {}
```

becomes

```
var _Service$DataService = require("joehannes/ng-harmony");

var MyService = (function (_DataService) {
  function MyService() {
    _classCallCheck(this, MyService);

    if (_DataService != null) {
      _DataService.apply(this, arguments);
    }
  }

  _inherits(MyService, _DataService);

  exports.MyService = MyService = Service()(MyService) || MyService;
  return MyService;
})(_Service$DataService.DataService);

exports.MyService = MyService;
```

The `Service` decorator call is called as `Service()`, but it should be `_Service$DataService.Service()`. The module transpiling logic isn't renaming the decorator.

**Comment by sebmck** [comment] 2015-04-07 21:42
Update to 3.0.10. Duplicate of #1167.

**Closed by sebmck** 2015-04-07 21:42 UTC
