### ISSUE TITLE
`for of` loop transpiles to ES6 (Not compatible with safari/IE10)

### ISSUE THREAD

**Issue by pik** [babel/babel#2654] opened 2015-10-30 04:47 UTC
So Babel is compiling a `for of` loop into code that uses Symbol - which is an [ES6 specific feature](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Symbol#Browser_compatibility). Example: 

```
for (let i of x) {
  console.log(i)
}
```

Babel output:
```
"use strict";

var _iteratorNormalCompletion = true;
var _didIteratorError = false;
var _iteratorError = undefined;

try {
  for (var _iterator = x[Symbol.iterator](), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true) {
    var i = _step.value;

    console.log(i);
  }
} catch (err) {
  _didIteratorError = true;
  _iteratorError = err;
} finally {
  try {
    if (!_iteratorNormalCompletion && _iterator["return"]) {
      _iterator["return"]();
    }
  } finally {
    if (_didIteratorError) {
      throw _iteratorError;
    }
  }
}
```

**Comment by AgentME** [comment] 2015-10-30 04:55
Certain Babel features require the [polyfill](https://babeljs.io/docs/usage/polyfill/) or the [runtime transform](https://webcache.googleusercontent.com/search?q=cache:XKCui6xrfpoJ:https://babeljs.io/docs/usage/runtime/+) (which seems to no longer be documented?) to be used.

**Comment by sebmck** [comment] 2015-10-30 04:59
Duplicate of #711, #1574, #1679, #1913, #2619. Please search before opening an issue.

**Closed by sebmck** 2015-10-30 04:59 UTC
