### ISSUE TITLE
Can't find variable: Symbol

### ISSUE THREAD

**Issue by edravis** [babel/babel#1574] opened 2015-05-19 15:15 UTC
Running this piece of code on Babeljs (abstracted):
```
for(var el of arr)
    do()
```

Throws the following error:
`[Error] ReferenceError: Can't find variable: Symbol`

Using Safari 8.0.6

Chrome is ok
Firefox is ok

**Comment by sebmck** [comment] 2015-05-19 15:17
Duplicate of #711.

**Closed by sebmck** 2015-05-19 15:17 UTC
