### ISSUE TITLE
'super.*' is not allowed before super() when using static props with spread operator

### ISSUE THREAD

**Issue by wkornewald** [babel/babel#3009] opened 2015-11-12 10:22 UTC
Please try compiling this file:
https://github.com/tomchentw/react-google-maps/blob/master/src/Polygon.js

I think the problematic part is this:
```
export default class Polygon extends Component {
  static propTypes = {
    // Uncontrolled default[props] - used only in componentDidMount
    ...polygonDefaultPropTypes,
    // Controlled [props] - used in componentDidMount/componentDidUpdate
    ...polygonControlledPropTypes,
    // Event [onEventName]
    ...polygonEventPropTypes,
  }
  // .......
}
```

I use --presets es2015,react,stage-2 --plugins transform-class-properties to compile and get this error:

```
SyntaxError: react-google-maps/Polygon.js: 'super.*' is not allowed before super() (This is an error on an internal node. Probably an internal error)
undefined
```

**Comment by leyyinad** [comment] 2015-11-12 14:45
I got the same and just figured that it seems to work when you put the `export default` separately, like eg.

```javascript
class Polygon extends Component {
  //...
}
export default Polygon;
```

Why is that?

**Comment by leyyinad** [comment] 2015-11-12 14:54
This seems to be a known issue, see #2700.

**Comment by sebmck** [comment] 2015-11-12 21:59
Duplicate of #2942.

**Closed by sebmck** 2015-11-12 21:59 UTC
