### ISSUE TITLE
[Bug]: After upgrading to babel-plugin-transform-react-constant-elements  v7.17.6 our application has stopped working correctly

### ISSUE THREAD

**Issue by budarin** [babel/babel#14363] opened 2022-03-15 19:42 UTC
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

```md
It is difficult to cite the code of the entire application and it is unclear at what point the failure occurs
```

### Configuration file name

babel.config.js

### Configuration

```js
const coreJsVer = require('./coreJsVer');
const isTesting = process.env.NODE_ENV === 'test';
const isDev = process.env.NODE_ENV !== 'production';

module.exports = function (api) {
    api.cache.using(() => process.env.NODE_ENV);

    return {
        comments: true,
        presets: [
            [
                '@babel/preset-env',
                {
                    loose: true,
                    debug: false,
                    modules: isTesting ? 'commonjs' : false,
                    corejs: {
                        version: coreJsVer,
                        proposals: true,
                    },
                    useBuiltIns: 'usage',
                    bugfixes: true,
                },
            ],
            [
                '@babel/preset-react',
                {
                    useBuiltIns: true,
                    runtime: 'automatic',
                    development: isDev,
                },
            ],
            '@babel/typescript',
        ],
        plugins: ['./lazyComponentBabelPlugin.js', 'preval'],
        env: {
            production: {
                plugins: [
                    'babel-plugin-transform-imports',
                    'babel-plugin-react-local',
                    // '@babel/plugin-transform-react-constant-elements',
                ],
                ignore: ['**/*.test.tsx', '**/*.test.ts', '__snapshots__', '__tests__'],
            },
            development: {
                plugins: [],
                ignore: ['**/*.test.tsx', '**/*.test.ts', '__snapshots__', '__tests__'],
            },
            test: {
                ignore: ['__snapshots__'],
            },
        },
    };
};
```

### Current and expected behavior

After updating the plugin, navigation in the application with react-router with code splitting stopped working

If you disable the plugin, everything works fine

### Environment

- "@babel/core": "^7.17.7"
- Node v16.9.0
- Yarn 1.22.15
- OS: any
- Monorepo: no

**Comment by nicolo-ribaudo** [comment] 2022-03-15 20:07
Unfortunately it's quite hard to understand what's the bug, we need an example or a repository we can clone to reproduce it. Which was the previous `@babel/plugin-transform-react-constant-elements` version you were using?

**Comment by budarin** [comment] 2022-03-16 08:33
previous working version was 7.16.7

I'll try to create repo for demonstrating the bug

**Comment by noahnu** [comment] 2022-04-05 13:07
We're seeing this as well where our app stopped working correctly after upgrading from 7.16.7 to 7.17.6 for @babel/plugin-transform-react-constant-elements. I'm still investigating on our side to try get a reliable reproduction, however from what I've seen, I _think_ a component is getting the wrong prop value (or the prop value is getting stale somehow).

I assume it's a regression from https://github.com/babel/babel/pull/12975, but I don't understand the PR well enough to identify what could be causing the broken behaviour. I'll post an update if I can determine the exact failure case.

**Comment by nicolo-ribaudo** [comment] 2022-04-05 14:50
Yes, it's likely to be caused by that PR but I'm not sure about what in that PR could cause this bug.

Unfortunately without a reproduction test we cannot really revert the PR and re-land it fixed, because we would just risk re-introducing the bug.

That PR should only change the behavior of functions passed as props, if that may help tracking down the component that is affected by this bug.

**Comment by budarin** [comment] 2022-04-15 14:32
Here is the [demo ](https://github.com/budarin/plugin-transform-react-constant-elements-bug )with the bug

**Comment by nicolo-ribaudo** [comment] 2022-04-15 14:44
Thank you!

**Comment by nicolo-ribaudo** [comment] 2022-05-06 21:48
It took a while, but thanks to your repository I found the bug :partying_face:

**Comment by nicolo-ribaudo** [comment] 2022-05-06 21:58
This code:
```jsx
function RoutesComponent() {
  return (
    <Routes>
      {(c) => {
        {
          const Component = c;
          return <Component />;
        }
      }}
    </Routes>
  );
}
```
is transformed to this:
```jsx
var _Component;

function RoutesComponent() {
  return (
    <Routes>
      {(c) => {
        {
          const Component = c;
          return _Component || (_Component = <Component />);
        }
      }}
    </Routes>
  );
}
```

which is wrong because `Component` might change and thus it shouldn't be cached.

**Comment by Slapbox** [comment] 2022-05-16 18:08
Mentioning this as a bug/breaking change in the broken versions would be hugely helpful even though it's apparently fixed now. I spent a full day tracking down this bug.

**Comment by Slapbox** [comment] 2022-05-16 18:14
Also, is there an ETA for #14536 to be published? This is a pretty serious bug if pushed to production which irreversibly corrupts data in our app.

**Comment by nicolo-ribaudo** [comment] 2022-05-16 19:39
Fix published

**Comment by Slapbox** [comment] 2022-05-17 19:29
`7.17.12` works for us so I guess that there are multiple underlying issues here. We're going to continue using `7.16.x` to be safe though.

**Comment by Slapbox** [comment] 2022-08-03 21:52
@budarin is this issue still affecting you? We've been hesitant to upgrade again for fear of re-introducing a critical flaw that does irreversible damage to user's data, but I haven't seen anyone else mention they're still having trouble.

**Comment by budarin** [comment] 2022-08-03 22:50
@Slapbox 

The problem is still actual - you can see by updating the dependencies of the demo project

**Comment by Slapbox** [comment] 2022-08-03 22:58
@nicolo-ribaudo do you have any thoughts on resolving this? Babel has always been reliable for us until this issue began, and so far it's already sapped more than an entire day's work for us, and it would be far far worse had we pushed it to production before discovering the bug.

**Comment by JLHwung** [comment] 2022-08-04 00:28
@Slapbox Can you provide a reproduction repo so we can take a look? It would be great if you can come up with a minimal reproducible examples like Nicolò did in https://github.com/babel/babel/issues/14363#issuecomment-1120040006.

**Comment by Slapbox** [comment] 2022-08-04 00:47
Thanks for the reply @JLHwung. Presumably @budarin's repro should work: https://github.com/budarin/plugin-transform-react-constant-elements-bug

It doesn't break our app, as far as I know - but it's that "as far as I know" that's troubling to us, because it took me nearly a month to even notice the subtle bug this plugin introduced for us last time.

Additionally, it can be quite difficult to create a repro for an error in a transpiler, much less a minimally reproducible one - unless you're pretty well versed in what the transpiler is doing, as @nicolo-ribaudo as the \#3 contributor presumably is.

**Comment by nicolo-ribaudo** [comment] 2022-08-04 07:23
That repository was the one I trimmed down to get my example above (which has been fixed): is that demo repository still affected by the bug?

(I'm on vacation so I cannot test it myself for a while)

**Comment by nicolo-ribaudo** [comment] 2022-08-04 07:25
If that repository still has the bug, it's enough for us. I'm on vacation until the end of next week, but I'll then take a look again at this.

**Closed** 2022-08-04 21:28 UTC
Labels: area: react, i: bug, i: regression

**Comment by JLHwung** [comment] 2022-08-05 14:43
Fixed in `@babel/plugin-transform-react-constant-elements` 7.18.12

**Comment by budarin** [comment] 2022-08-05 16:45
Thanks! 💥💥💥
