### ISSUE TITLE
Cannot read property 'buildError' of undefined when using `path.buildCodeFrameError`

### ISSUE THREAD

**Issue by nicojs** [babel/babel#11889] opened 2020-07-29 20:22 UTC
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

When using the programmatic API, babel always throws an error when I use `path.buildCodeFrameError`.

**Input Code**

A simple example:

```js
const { parseAsync, traverse } = require('@babel/core');

async function demo() {
  const parsed = await parseAsync('foo.bar()', { sourceFileName: 'foo.js' });
  traverse(parsed, {
    enter(path) {
      path.buildCodeFrameError('some error');
    }
  })
}

demo().catch(console.error);
```

**Expected behavior**
I would expect an awesomely formatted code frame error.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
_none_

**Environment**

```

  System:
    OS: Windows 10 10.0.19041
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @babel/core: ^7.9.6 => 7.10.4
    @babel/generator: ^7.9.6 => 7.10.4
    @babel/parser: ^7.9.6 => 7.10.4
    @babel/plugin-proposal-decorators: ^7.8.3 => 7.10.4
    @babel/preset-react: ^7.9.4 => 7.10.4
    @babel/preset-typescript: ^7.9.0 => 7.10.4
    babel-plugin-transform-decorators-legacy: ^1.3.5 => 1.3.5
```

**Comment by JLHwung** [comment] 2020-07-29 21:12
Duplicate of #11350.

**Closed by JLHwung** 2020-07-29 21:12 UTC
Labels: i: bug, i: needs triage

**Comment by nicojs** [comment] 2020-07-30 06:07
Thanks @JLHwung ! I looked at that issue, but wasn't sure since it specified estree specifically. I was also confused with `File`, since my AST was also of type `file`. I now see the AST `file` is different from the `File` class.

For anyone interested, this does work:

```js
const { File, parseAsync, traverse } = require('@babel/core');

async function demo() {
  const code = 'foo.bar()';
  const filename = 'foo.js';
  const ast = await parseAsync(code, { sourceFileName: filename });
  const file = new File({ filename }, { code, ast });
  traverse(file.ast, {
    enter(path) {
      throw path.buildCodeFrameError('some error');
    }
  })
}

demo().catch(console.error);
```
