### ISSUE TITLE
_interopRequireWildcard breaks on nodejs cases

### ISSUE THREAD

**Issue by theKashey** [babel/babel#10577] opened 2019-10-19 04:40 UTC
## Bug Report

> The bug was introduced by #10161, v7.5.5 is confirmed to work

**Current Behavior**
- Given a code `import * as isNode from 'detect-node';` (TypeScript syntax)
- Compiles to es5 code `const isNode = require('detect-node')` (again TypeScript)
- Parcel bundler then compiles es2015 code to the following
```js
const isNode = _interopRequireWildcard(require('detect-node'));
```

The result would be __correct__, however, internally it uses `WeakMap` based cache, and by some reason, expects any module to be resolved to an object.

https://github.com/babel/babel/blob/master/packages/babel-helpers/src/helpers.js#L623-L626
```js
var cache = _getRequireWildcardCache();
    if (cache && cache.has(obj)) {
      return cache.get(obj);
    }
```

`require('detect-node')` resolves to `true` or `false`

A clear and concise description of the behavior.

**Input Code**
```js
_interopRequireWildcard(false); // throws
```

**Expected behavior/code**
```js
_interopRequireWildcard(false) === false
_interopRequireWildcard(42) === 42
_interopRequireWildcard(function) === function (!!)
```
> `import * as cx from 'classnames';` is also not working, even at 7.5.5

**Possible Solution**
Many "object like" structures are not "WeakMapable", however - `typeof value === 'object'` would be more than enought.

**Comment by jridgewell** [comment] 2019-10-19 04:58
Closing as a dupe of https://github.com/babel/babel/issues/10561, PR at https://github.com/babel/babel/pull/10574.

**Closed by jridgewell** 2019-10-19 04:59 UTC
Labels: i: bug, i: needs triage

**Comment by jridgewell** [comment] 2019-10-19 05:04
Sorry for being brief. This was an excellent bug report, and thank you for filling it!

**Comment by theKashey** [comment] 2019-10-19 06:29
No worries. 
But I've added a [comment](https://github.com/babel/babel/pull/10574#issuecomment-544107112) to PR for the case `module.exports = function`
