### ISSUE TITLE
babel-node reports error with transform-runtime when reexporting all named properties from an es6 module

### ISSUE THREAD

**Issue by CMCDragonkai** [babel/babel#6522] opened 2017-10-21 06:35 UTC
The transform-runtime plugin results in errors when doing catch-all reexporting (`export * from 'something';`).

### Input Code

package.json:

```
"plugins": ["transform-runtime"]
```

Say you have 3 files:

a.js:

```
const a = 1;
export { a };
```

b.js:

```
export * from './a.js';
```

c.js:

```
import a from './b.js';
```

The result from running `babel-node` is: 

```
import _Object$defineProperty from 'babel-runtime/core-js/object/define-property';
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:588:28)
    at loader (/home/cmcdragonkai/Projects/js-virtualfs/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/cmcdragonkai/Projects/js-virtualfs/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
```

I'm using babel-plugin-transfrom-runtime at 6.23.0 and babel-runtime at 6.26.0.

**Comment by nicolo-ribaudo** [comment] 2017-10-21 11:05
Babel 7 has a bunch of fixes related to this kind of bugs. Can you test if it works with version 7.0.0-beta.3?

**Comment by loganfsmyth** [comment] 2017-10-23 20:09
Yeah, this is a duplicate of https://github.com/babel/babel/issues/2877 which is fixed in 7.x

**Closed by loganfsmyth** 2017-10-23 20:09 UTC
