### ISSUE TITLE
Potential bug: const declaration getting hoisted?

### ISSUE THREAD

**Issue by sc0ttyd** [babel/babel#2359] opened 2015-09-11 10:55 UTC
If I understand things correctly, under ES6, the second line should raise a referenceError due to x not yet having been declared.

```
"use strict";
let b = x; // should throw a referenceError
console.log('b: ', b);
b = 2;
const x = 'a';
```
Running this through Babel, I get no referenceError. But the following code does raise a referenceError:

```
"use strict";
let b = x; // throws a referenceError
console.log('b: ', b);
b = 2;
```

**Comment by sebmck** [comment] 2015-09-11 14:04
Duplicate of #2253 and #2254.

**Closed by sebmck** 2015-09-11 14:04 UTC
