### ISSUE TITLE
@babel/preset-env doesn't read .browserslistrc file (still works using targets option)

### ISSUE THREAD

**Issue by gremo** [babel/babel#12721] opened 2021-01-30 09:25 UTC
It seems that `@babel/preset-env` doesn't read the `.browserslistrc` anymore. 

FIle `.browserslistrc`:

```
defaults
not ie 11
not ie_mob 11
```

When I run `npm run babel -- assets/js/app.js` with the following test file:

```js
document.addEventListener('DOMContentLoaded', () => {
  // DOM ready
  [1, 2, 3].forEach(n => console.log(n));
});
```
Output uses the targets is empty:

> babel "assets/js/app.js"
>
>@babel/preset-env: `DEBUG` option
>
>Using targets:
>{}

However, It still works if I use the `targets` option in  `.babelrc`.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `.babelrc`

```js
{
  "presets": [
    ["@babel/preset-env", {
      "corejs": 3,
      "useBuiltIns": "usage",
      "bugfixes": true,
      "modules": false,
      "debug": true
    }]
  ]
}
```

**Environment**

```
  System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 12.18.4 - C:\Program Files\nodejs\node.EXE       
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @babel/cli: ^7.12.10 => 7.12.10
    @babel/core: ^7.12.10 => 7.12.10
    @babel/preset-env: ^7.12.11 => 7.12.11
    babel-eslint: ^10.1.0 => 10.1.0
    eslint: ^7.18.0 => 7.18.0
```
- Babel version(s): 7.12.10 (@babel/core 7.12.10)
- Node/npm version: v12.18.4
- OS: Windows 10 x64
- How you are using Babel: CLI

**Comment by nicolo-ribaudo** [comment] 2021-01-30 13:53
The problem is that for backward compatibility reasons, if you don't specify a `targets` option, Babel will tell to browserslist "Hey, `defaults` means 'transform everything' instead of your usual 'defaults' browsers".

This is tracked by https://github.com/babel/babel/issues/9962, and it will be fixed by https://github.com/babel/babel/pull/12616 (we might merge that PR soon, but the fix will only work starting from Babel 8).

**Closed by nicolo-ribaudo** 2021-01-30 13:53 UTC
Labels: i: bug, i: needs triage

**Comment by gremo** [comment] 2021-02-02 08:08
Thanks @nicolo-ribaudo, so what's the proposed solution/workaround? Do you know which 7.x.x version introduced the problem?

**Comment by nicolo-ribaudo** [comment] 2021-02-02 14:44
This problem has been present since `babel-preset-env` 1.x.
As a workaround, you can copy your browser's list query into your Babel config.

**Comment by gremo** [comment] 2021-02-02 16:33
@nicolo-ribaudo sorry for bother you again but I'm pretty sure that some older project of mine works without problem.

Is the problem only related to the `defaults` keyword be present?

**Comment by nicolo-ribaudo** [comment] 2021-02-02 19:42
Yes, it's "default" that means "every possible browser version" when Babel reads it from the browserslistrc file.
