### ISSUE TITLE
latest Babel types is not published

### ISSUE THREAD

**Issue by stalniy** [babel/babel#4609] opened 2016-09-29 15:14 UTC
I tried to reinstall my dependencies today and received this error 
```sh
pm WARN optional SKIPPING OPTIONAL DEPENDENCY: babel-traverse@^6.16.0 (node_modules/babel-template/node_modules/babel-traverse):
npm WARN notarget SKIPPING OPTIONAL DEPENDENCY: No compatible version found: babel-traverse@^6.16.0
npm WARN notarget SKIPPING OPTIONAL DEPENDENCY: Valid install targets:
npm WARN notarget SKIPPING OPTIONAL DEPENDENCY: 6.15.0, 6.14.0, 6.13.0, 6.12.0, 6.11.4, 6.10.4, 6.9.0, 6.8.0, 6.7.6, 6.7.5, 6.7.4, 6.7.3, 6.7.2, 6.7.0, 6.6.5, 6.6.4, 6.6.3, 6.6.2, 6.6.0, 6.5.0, 6.5.0-1, 6.4.5, 6.3.26, 6.3.25, 6.3.24, 6.3.21, 6.3.19, 6.3.17, 6.3.16, 6.3.15, 6.3.14, 6.3.13, 6.3.2, 6.2.4, 6.2.0, 6.1.20, 6.1.18, 6.1.17, 6.1.4, 6.1.2, 6.0.20, 6.0.19, 6.0.18, 6.0.17, 6.0.16, 6.0.14, 6.0.2
npm WARN notarget SKIPPING OPTIONAL DEPENDENCY: 
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
npm ERR! node v6.0.0
npm ERR! npm  v3.10.8
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: babel-types@^6.16.0
npm ERR! notarget Valid install targets:
npm ERR! notarget 6.15.0, 6.14.0, 6.13.0, 6.11.1, 6.10.2, 6.10.0, 6.9.1, 6.9.0, 6.8.1, 6.8.0, 6.7.7, 6.7.2, 6.7.0, 6.6.5, 6.6.4, 6.6.0, 6.5.2, 6.5.1, 6.5.0, 6.5.0-1, 6.4.5, 6.4.3, 6.4.1, 6.4.0, 6.3.24, 6.3.21, 6.3.20, 6.3.18, 6.3.17, 6.3.14, 6.3.13, 6.3.0, 6.2.4, 6.2.3, 6.2.0, 6.1.18, 6.1.17, 6.1.4, 6.1.2, 6.0.19, 6.0.18, 6.0.17, 6.0.15, 6.0.14, 6.0.13, 6.0.12, 6.0.2
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'babel-template'
npm ERR! notarget 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/stse/projects/concrete/tasks-mobile/npm-debug.log
stse:~/projects/concrete/tasks-mobile$ npm i
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
npm ERR! node v6.0.0
npm ERR! npm  v3.10.8
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: babel-traverse@^6.16.0
npm ERR! notarget Valid install targets:
npm ERR! notarget 6.15.0, 6.14.0, 6.13.0, 6.12.0, 6.11.4, 6.10.4, 6.9.0, 6.8.0, 6.7.6, 6.7.5, 6.7.4, 6.7.3, 6.7.2, 6.7.0, 6.6.5, 6.6.4, 6.6.3, 6.6.2, 6.6.0, 6.5.0, 6.5.0-1, 6.4.5, 6.3.26, 6.3.25, 6.3.24, 6.3.21, 6.3.19, 6.3.17, 6.3.16, 6.3.15, 6.3.14, 6.3.13, 6.3.2, 6.2.4, 6.2.0, 6.1.20, 6.1.18, 6.1.17, 6.1.4, 6.1.2, 6.0.20, 6.0.19, 6.0.18, 6.0.17, 6.0.16, 6.0.14, 6.0.2
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'babel-template'
npm ERR! notarget 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/stse/projects/concrete/tasks-mobile/npm-debug.log
```

So, new `babel-template` module depends on 
```sh
    "babel-traverse": "^6.16.0",
    "babel-types": "^6.16.0",
```
but the latest version of that modules on npmjs.org are 6.15.0 but the latest version of `babel-template` is 6.16 (which points to non-existing version).

**Comment by hzoo** [comment] 2016-09-29 15:17
It's definetely published: https://unpkg.com/babel-types/

Duplicate of https://github.com/babel/babel/issues/4598

```
npm view babel-types dist-tags
{ latest: '6.16.0' }
```

'6.16.0': '2016-09-28T19:39:07.889Z'

**Closed** 2016-09-29 15:59 UTC
