### ISSUE TITLE
transform-decorators not working in babel 6

### ISSUE THREAD

**Issue by Mosho1** [babel/babel#2691] opened 2015-10-30 19:29 UTC
This:

    @decorator
    class Classy{}

Transpiles into:

    "use strict";

    function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

    var Classy = function Classy() {
      _classCallCheck(this, Classy);
    };

Using `.babelrc`:

    {
      "presets": ["es2015"],
      "plugins": ["transform-decorators"]
    }

**Comment by thejameskyle** [comment] 2015-10-30 19:34
Duplicate of #2645

**Closed by thejameskyle** 2015-10-30 19:34 UTC
