### ISSUE TITLE
@babel/standalone 7.13.2 version bug

### ISSUE THREAD

**Issue by weieyuan** [babel/babel#12862] opened 2021-02-23 07:08 UTC
@babel/standalone update to 7.13.2 version will get this error:
![image](https://user-images.githubusercontent.com/16069074/108811851-fe0c1800-75e8-11eb-8ffc-d80411de57b0.png)

**Comment by nicolo-ribaudo** [comment] 2021-02-23 13:45
@weieyuan I cannot reproduce this in the REPL, which uses `@babel/standalone`: https://babeljs.io/repl/version/7.13.4#?browsers=firefox%2030&build=&builtIns=false&spec=false&loose=false&code_lz=IY0KAgbBTAXACW0DOCC88AUBKeaB88A3gL5A&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=env&prettier=false&targets=&version=7.13.4&externalPlugins=

Could you provide an example that reproduces the error? :pray:

**Comment by weieyuan** [comment] 2021-02-25 13:42
@nicolo-ribaudo thanks for you reply，i now use 7.12.18 version and this error  disappear

**Comment by JLHwung** [comment] 2021-02-25 15:29
Duplicate of #12907.

**Closed by JLHwung** 2021-02-25 15:29 UTC
Labels: Needs Info, i: bug, i: needs triage, i: regression
