### ISSUE TITLE
[Bug]: Cannot find module './data/corejs3-shipped-proposals.json （unresolved）

### ISSUE THREAD

**Issue by lhbxs** [babel/babel#15599] opened 2023-04-29 13:34 UTC
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@rollup/plugin-babel

### Input code

Cannot find module './data/corejs3-shipped-proposals.json'

### Current and expected behavior

Cannot find module './data/corejs3-shipped-proposals.json'

### Environment

7.21.5

**Comment by JLHwung** [comment] 2023-04-29 13:41
Duplicate of #15597

**Closed by JLHwung** 2023-04-29 13:41 UTC
Labels: i: needs triage
