### ISSUE TITLE
Another let issue 

### ISSUE THREAD

**Issue by mnowik** [babel/babel#2389] opened 2015-09-16 20:17 UTC
I have an issue using let.

Here is my code:
```javascript
if (a === b ) {
  let defaultReturnAddress = {};
  let returnAddress = _this.get('currentUser.address');
  ...
}
if (defaultReturnAddress) {...}
```

Here is the translation using ember-cli-babel@5.1.5
```javascript
if (a === b ) {
  var _defaultReturnAddress = {};
  var returnAddress = _this.get('currentUser.address');
  ...
}
if (defaultReturnAddress) {...}
```

It seems to be linked to this error on babel https://github.com/babel/babel/issues/166.
This error was closed a while ago. However, it seems to be a Babel issue.

**Comment by sebmck** [comment] 2015-09-16 20:18
What's the issue here? `let` is block scoped, it seems to be having correctly. What output are you expecting?

**Comment by mnowik** [comment] 2015-09-16 21:12
The if block is a scope by itself ?
I would have except ```var defaultReturnAddress```

**Comment by sebmck** [comment] 2015-09-16 21:14
`let` is called a block scoped variable so yeah `let` is bound to it. Closing as this isn't an issue and is expected behaviour.

**Closed by sebmck** 2015-09-16 21:14 UTC
