### ISSUE TITLE
Babel parses and removes sourceMappingURL from input

### ISSUE THREAD

**Issue by also** [babel/babel#9790] opened 2019-03-29 16:11 UTC
## Bug Report

**Current Behavior**

I have some code that generates JavaScript files and includes the string `//# sourceMappingURL=`. Babel appears to remove this string and the remainder of the line before parsing.

**Input Code**

```js
const comment = `//# sourceMappingURL=${path.basename(
  sourceMapFilename
)}`
```

[Babel REPL](https://babeljs.io/en/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBKC28CmZYF4YAMD02DEMEIArgE7BICyAhgA60CWYA5gKoBKAMmgCQDetalAAWAOgBG1CCmrIAFACgYhEuSp0AYgwA2M5AoCUAX0xA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=&prettier=false&targets=&version=7.4.2)

**Output Code**

```js
const comment = `
  sourceMapFilename
)}`;
```

**Expected behavior/code**

`//# sourceMappingURL=` should not have special meaning inside of a template literal, and should be included in the generated output

```js
const comment = `//# sourceMappingURL=${path.basename(sourceMapFilename)}`;
```

**Babel Configuration (.babelrc, package.json, cli command)**

None, see REPL link.

**Environment**
- Babel version(s): v7.4.2
- How you are using Babel: repl

**Comment by also** [comment] 2019-03-29 17:55
Disabling [`inputSourceMaps`](https://babeljs.io/docs/en/options#inputsourcemap) works around this bug.

**Comment by nicolo-ribaudo** [comment] 2019-03-30 13:01
Does the source map specified by sourceMapFilename exist on the disk? If not, I believe that Babel is doing the best it could do: since it can't load the input source map, it can't generate a correct new source map. In this case, it is better to have the output code not linked to a source map rather than to a totally broken one.

**Comment by loganfsmyth** [comment] 2019-03-30 19:46
@nicolo-ribaudo I think you misread this one. We're removing the comment-like content of a JS string, which is not right.

The logic for stripping `sourceMappingURL` must not verify that it's in a file-end comment token, and instead just look for the string itself.

@also Seems reasonable for us to fix this. For now I'd split the string into two pieces and concatenate with `+` so we don't match the comment string, e.g.

```
const comment = `//# ` + `sourceMappingURL=${path.basename(
```

**Comment by tanhauhau** [comment] 2019-03-31 09:31
I found out that this is caused by this line:
https://github.com/babel/babel/blob/master/packages/babel-core/src/transformation/normalize-file.js#L68
```js
debug("discarding un-loadable file input sourcemap");
code = convertSourceMap.removeMapFileComments(code);
```
so apparently we tried to remove `//#sourceMappingURL=` via regex, without aware that it's contained within a string literal, maybe we should not remove the comment if we couldn't load the source map, and remove it from the ast if it is part of the comment?

**Comment by nicolo-ribaudo** [comment] 2019-03-31 09:59
It needs to be fixed in the `convert-source-map` package.

**Closed** 2019-08-14 15:05 UTC
Labels: i: bug
