### ISSUE TITLE
running tests on master gives an error

### ISSUE THREAD

**Issue by lukeapage** [babel/babel#1072] opened 2015-03-23 22:11 UTC
I've been trying to get the repo setup.. but running tests I get this error

```
  687) transformation/validation undeclared variable check undeclared:
     TypeError: object is not a function
      at transform (C:\git\babel\lib\babel\transformation\index.js:18:14)
      at run (C:\git\babel\test\_transformation-helper.js:74:14)
      at runTask (C:\git\babel\test\_transformation-helper.js:145:13)
      at Function._throws (assert.js:290:5)
      at Function.assert.throws (assert.js:316:11)
      at runTest (C:\git\babel\test\_transformation-helper.js:157:20)
      at Context.callback (C:\git\babel\test\_transformation-helper.js:170:20)
      at callFn (C:\git\babel\node_modules\mocha\lib\runnable.js:266:21)
      at Test.Runnable.run (C:\git\babel\node_modules\mocha\lib\runnable.js:259:7)
      at Runner.runTest (C:\git\babel\node_modules\mocha\lib\runner.js:387:10)
      at C:\git\babel\node_modules\mocha\lib\runner.js:470:12
      at next (C:\git\babel\node_modules\mocha\lib\runner.js:312:14)
      at C:\git\babel\node_modules\mocha\lib\runner.js:322:7
      at next (C:\git\babel\node_modules\mocha\lib\runner.js:257:23)
      at C:\git\babel\node_modules\mocha\lib\runner.js:284:7
      at done (C:\git\babel\node_modules\mocha\lib\runnable.js:222:5)
      at callFn (C:\git\babel\node_modules\mocha\lib\runnable.js:277:7)
      at Hook.Runnable.run (C:\git\babel\node_modules\mocha\lib\runnable.js:259:7)
      at next (C:\git\babel\node_modules\mocha\lib\runner.js:268:10)
      at Object._onImmediate (C:\git\babel\node_modules\mocha\lib\runner.js:289:5)
      at processImmediate [as _immediateCallback] (timers.js:330:15)

```

**Comment by lukeapage** [comment] 2015-03-23 22:17
I tried debugging but weirdly it doesn't stop on the error.. so just hoping you know what the problem might be,,,

**Comment by sebmck** [comment] 2015-03-23 22:17
What steps did you take to setup everything up? And what's your node/iojs version?

**Comment by lukeapage** [comment] 2015-03-24 07:24
I had manually done a git sumodule init and update and then manually npm installed all vendors and root. I was starting with `make test-cov` but then got the same error for `make test`.
I've just tried deleting all node_modules and running `make bootstrap`, then `make watch-core`, cancelling out once compiled, then `make test` and same result.

Windows & cygwin. Node v0.10.25

**Comment by lukeapage** [comment] 2015-03-24 07:29
Ok, I installed node v0.12.2 and I get the same error...

**Comment by sebmck** [comment] 2015-03-24 09:47
It's probably Windows.

**Comment by sebmck** [comment] 2015-03-25 02:55
Running the following (as dictated by [CONTRIBUTING.md](https://github.com/babel/babel/blob/master/CONTRIBUTING.md)) in a Windows VM with [gow](https://github.com/bmatzelle/gow) works without a problem.

```sh
$ git clone https://github.com/babel/babel
$ cd babel
$ make bootstrap
$ make test
```

**Comment by sebmck** [comment] 2015-03-25 02:57
Closing this due to irreproducibility and it not being a bug. Also as per the [README](https://github.com/babel/babel#readme):

> For questions and support please visit the [gitter room](https://gitter.im/babel/babel) before creating an issue.

Thanks!

**Closed by sebmck** 2015-03-25 02:57 UTC

**Comment by lukeapage** [comment] 2015-03-25 07:14
Sorry for wasting your time then, I'll delete and try again and continue investigating.

**Comment by sebmck** [comment] 2015-03-25 07:18
@lukeapage No worries at all. Check out the gitter room if you need any help as debugging over GitHub issues is pretty painful.
