### ISSUE TITLE
a bug?

### ISSUE THREAD

**Issue by zhangenming** [babel/babel#8676] opened 2018-09-11 12:51 UTC
## Bug Report

**Current Behavior**
A clear and concise description of the behavior.

**Input Code**
- REPL or Repo link if applicable:

https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=FACgZgrgdgxgLgSwPZRADwDQAIxYLxYgCU-AfFmiQN7BZYBuAhgE4UDctDLWAnvu5zT8ATBzrMApnAjMoWANqZe2MMQC6HAL5EQARiJA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=6.26.0&envVersion=

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

chrome69 &FF61 [2, 1, 1]
babel [2,1,2]

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "your": { "config": "here" }
}
```

**Environment**
- Babel version(s): [e.g. v6.0.0, v7.0.0-beta.34]
- Node/npm version: [e.g. Node 8/npm 5]
- OS: [e.g. OSX 10.13.4, Windows 10]
- Monorepo [e.g. yes/no/Lerna]
- How you are using Babel: [e.g. `cli`, `register`, `loader`]

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by nicolo-ribaudo** [comment] 2018-09-13 14:47
Duplicate of https://github.com/babel/babel/issues/2471.

**Closed by nicolo-ribaudo** 2018-09-13 14:47 UTC
