### ISSUE TITLE
babel/register causes node to SyntaxError if any node_modules return outside of function

### ISSUE THREAD

**Issue by AgentME** [babel/babel#1398] opened 2015-04-30 23:27 UTC
It seems like an update in one of babel's dependencies recently broke this. As far as I know, babel shouldn't be trying to parse stuff under node_modules like this.

```javascript
//test.js
require('babel/register');
require('gulp-util');
```

```
$ npm i babel gulp-util
...
$ node test.js

/private/tmp/node_modules/babel/node_modules/babel-core/lib/babel/helpers/parse.js:80
    throw err;
          ^
SyntaxError: /private/tmp/node_modules/gulp-util/node_modules/beeper/index.js: 'return' outside of function (9:1)
   7 | 	process.argv.indexOf('--beep=false') !== -1) {
   8 | 	module.exports = function () {};
>  9 | 	return;
     |  ^
  10 | }
  11 | 
  12 | function beep() {
    at Parser.pp.raise (/private/tmp/node_modules/babel/node_modules/babel-core/lib/acorn/src/location.js:73:13)
    at Parser.pp.parseReturnStatement (/private/tmp/node_modules/babel/node_modules/babel-core/lib/acorn/src/statement.js:247:74)
    at Parser.pp.parseStatement (/private/tmp/node_modules/babel/node_modules/babel-core/lib/acorn/src/statement.js:77:19)
    at Parser.parseStatement (/private/tmp/node_modules/babel/node_modules/babel-core/lib/acorn/plugins/flow.js:631:22)
    at Parser.pp.parseBlock (/private/tmp/node_modules/babel/node_modules/babel-core/lib/acorn/src/statement.js:387:21)
    at Parser.pp.parseStatement (/private/tmp/node_modules/babel/node_modules/babel-core/lib/acorn/src/statement.js:93:19)
    at Parser.parseStatement (/private/tmp/node_modules/babel/node_modules/babel-core/lib/acorn/plugins/flow.js:631:22)
    at Parser.pp.parseIfStatement (/private/tmp/node_modules/babel/node_modules/babel-core/lib/acorn/src/statement.js:241:26)
    at Parser.pp.parseStatement (/private/tmp/node_modules/babel/node_modules/babel-core/lib/acorn/src/statement.js:75:19)
    at Parser.parseStatement (/private/tmp/node_modules/babel/node_modules/babel-core/lib/acorn/plugins/flow.js:631:22)
```

**Comment by sebmck** [comment] 2015-04-30 23:30
Fuck, looks like a regression. Fixed as of 5.2.1. Please let me know if you run into anymore issues, thanks!

**Closed** 2015-04-30 23:30 UTC

**Comment by mdouglass** [comment] 2015-04-30 23:38
Ha, was just writing up a bug report on this as you fixed it.  

I noticed a related issue if you used the options block to the require hook (https://babeljs.io/docs/usage/require/).  The ignore/only there now seem to require arrays too because of the changes in util.ignore.

**Comment by sebmck** [comment] 2015-04-30 23:39
@mdouglass It uses [util.arrayify](https://github.com/babel/babel/blob/master/src/babel/util.js#L81) so it should allow a bunch of stuff. Apparently regexes aren't one of them though :/

**Comment by mdouglass** [comment] 2015-05-01 00:26
@sebmck thanks that fixed it for me.  Appreciate the quick releases!
