### ISSUE TITLE
babel-preset-env dosen't polyfill es.array.iterator in IE11

### ISSUE THREAD

**Issue by VIGDXX** [babel/babel#10140] opened 2019-06-28 09:22 UTC
## Bug Report

**Current Behavior**
Unhandled promise rejection TypeError:traget is not iterable!

**Input Code**

**Expected behavior/code**

**Environment**
- Babel version(s): 7.4.5

**Possible Solution**

**Additional context/Screenshots**

**other**
I have seen the same problem [7395](https://github.com/babel/babel/issues/7395)
and the pr [7400](https://github.com/babel/babel/pull/7400)

but it didn't solve the problem.

![image](https://user-images.githubusercontent.com/25626094/60332069-95f6d000-99c8-11e9-9779-9819f81d7ef9.png)
I build  my project with webpack ,i fix it as the picture show

[9872](https://github.com/babel/babel/issues/9872#thread-subscription-status)

**Comment by VIGDXX** [comment] 2019-06-28 09:41
![](https://user-images.githubusercontent.com/25626094/60333487-c724cf80-99cb-11e9-8e04-394138d30b2d.png)

[see it](https://babeljs.io/docs/en/babel-plugin-syntax-dynamic-import)

**Comment by nicolo-ribaudo** [comment] 2019-06-30 19:56
What is your configuration?

**Comment by VIGDXX** [comment] 2019-07-01 01:55
this is my .babelrc  and browserslist
```
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "useBuiltIns": "usage",
      }
    ]
  ],
  "plugins": [
    "@babel/plugin-syntax-dynamic-import"
  ]
}
```
```
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
```

**Comment by nicolo-ribaudo** [comment] 2019-07-01 07:27
Ok, since you are using "usage" we also need to see the line of code which should need the polyfill, to understand why Babel doesn't load it.

**Comment by VIGDXX** [comment] 2019-07-01 09:06
importing an component dynamically in vue-router
```
const Home = () => import('@/pages/home/index');
```

**Comment by zloirock** [comment] 2019-07-01 09:30
It's a duplicate of #9872.

**Comment by chenjiahan** [comment] 2020-01-08 10:56
Wrote a small plugin to add `array.iterator` polyfill automatically: 

Repo: [babel-plugin-dynamic-import-polyfill](https://github.com/chenjiahan/babel-plugin-dynamic-import-polyfill).

### Example

#### In

```js
import('./foo');
```

#### Out

```js
import "core-js/modules/es.object.to-string";
import "core-js/modules/es.promise";
import "core-js/modules/es.array.iterator"; // <- Added by plugin

import('./foo');
```

### Installation

```bash
npm install --save-dev babel-plugin-dynamic-import-polyfill
```

### Usage

.babelrc

```json
{
  "plugins": ["babel-plugin-dynamic-import-polyfill"]
}
```

**Comment by nicolo-ribaudo** [comment] 2021-01-31 22:59
Closing because of https://github.com/babel/babel/issues/10140#issuecomment-507190307

**Closed by nicolo-ribaudo** 2021-01-31 22:59 UTC
Labels: i: duplicate
