### ISSUE TITLE
Cannot have `const` inside a method with the same name as the method.

### ISSUE THREAD

**Issue by tadeuzagallo** [babel/babel#2834] opened 2015-11-05 10:30 UTC
It fails with `"<name>" is read-only`.

Sample code:

```js
class A {
  b() {
    const b = 1;
  }
}
```

**Comment by hzoo** [comment] 2015-11-05 15:17
Whole error is `SyntaxError: index.js: "b" is read-only (This is an error on an internal node. Probably an internal error. Location has been estimated.)`

Don't know if it's related to https://github.com/babel/babel/issues/2684 which is a similar error but with let

**Comment by venil7** [comment] 2015-11-06 11:13
Guessing it's a duplicate of ~~#2805~~ and #2684

**Comment by thejameskyle** [comment] 2015-11-10 04:14
> Don't know if it's related to #2684 which is a similar error but with let

Different error, but likely the same issue related to either `Scope` or the class transform.

**Closed** 2016-09-07 20:12 UTC
