### ISSUE TITLE
npm ERR! notarget No matching version found for @babel/compat-data@^7.13.15.

### ISSUE THREAD

**Issue by saswat3115** [babel/babel#13127] opened 2021-04-09 05:59 UTC
![image](https://user-images.githubusercontent.com/14299682/114135370-c6ea8f80-9926-11eb-8215-cac95178b480.png)

**Comment by fedeci** [comment] 2021-04-09 06:04
Duplicate of #13124

**Comment by saswat3115** [comment] 2021-04-09 06:09
@fedeci how to resolve this now ? I am unable to do npm install in react app

**Comment by fedeci** [comment] 2021-04-09 07:13
Have you tried `npm ci`?

**Comment by nicolo-ribaudo** [comment] 2021-04-09 07:59
Unfortunately there is nothing we can do about this: once the package is published, it's npm or the proxies between you and npm that need to give you the package.

If you still have this problem, please contact the npm support.

**Closed by nicolo-ribaudo** 2021-04-09 07:59 UTC
Labels: i: npm cache
