### ISSUE TITLE
[Bug]: TypeError: Error while loading config - yield* (intermediate value) is not iterable

### ISSUE THREAD

**Issue by mrtnzlml** [babel/babel#13462] opened 2021-06-14 13:58 UTC
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```js
// doesn't apply
```

### Configuration file name

.babelrc.js

### Configuration

`.babelrc.js`:

```js
module.exports = {
  presets: ['@adeira/babel-preset-adeira'],
  plugins: ['babel-plugin-fbt', 'babel-plugin-fbt-runtime', 'relay'],
};
```

`babel.config.js` in a monorepo root:

```js
function isWebpack(caller) {
  // https://github.com/babel/babel-loader
  return !!(caller && caller.name === 'babel-loader');
}

module.exports = function (api) {
  api.assertVersion(7);

  return {
    presets: [
      [
        '@adeira/babel-preset-adeira',
        {
          target: api.caller(isWebpack) ? 'js-esm' : 'js',
        },
      ],
    ],
    babelrcRoots: [
      '.', // keep the root as a root
      './src/*', // also consider all packages and load their .babelrc files.
    ],
  };
};
```

### Current and expected behavior

We have one project in a monorepo (using `yarn workspaces`) which has its own `.babelrc.js` and there is also one main Babel config in the monorepo root `babel.config.js`. We attempted to add Jest tests to this project and they mostly work fine (when we do not touch other part of the monorepo). However, once in a while they start failing with the following error (commonly when we edit unrelated part of the monorepo - doesn't even have to touch the subdirectory at all):

```text
    TypeError: /home/runner/work/universe/universe/src/abacus-kochka/.babelrc.js: Error while loading config - /home/runner/work/universe/universe/src/abacus-kochka/.babelrc.js: Error while loading config - yield* (intermediate value)(intermediate value)(intermediate value)(intermediate value) is not iterable

      at loadOneConfig (../../node_modules/@babel/core/lib/config/files/configuration.js:146:37)
          at loadOneConfig.next (<anonymous>)
      at buildRootChain (../../node_modules/@babel/core/lib/config/config-chain.js:82:51)
          at buildRootChain.next (<anonymous>)
      at loadPrivatePartialConfig (../../node_modules/@babel/core/lib/config/partial.js:101:62)
          at loadPrivatePartialConfig.next (<anonymous>)
      at loadFullConfig (../../node_modules/@babel/core/lib/config/full.js:55:46)
          at loadFullConfig.next (<anonymous>)
      at Function.<anonymous> (../../node_modules/@babel/core/lib/config/index.js:34:43)
```

You can see the issue described above in this PR: https://github.com/adeira/universe/pull/2538/checks?check_run_id=2820151437 (it affects every Node.js version the same).

Strangelly, it affects only this project but I cannot figure out how is it different. I didn't find anything unusual about it.

Expected behavior is that Babel should not fail (at least not so mysteriously).

### Environment

```text
  System:
    OS: macOS 11.4
  Binaries:
    Node: 16.3.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.16.0 - /usr/local/bin/npm
  Monorepos:
    Yarn Workspaces: 1.22.10
  npmPackages:
    @babel/cli: ^7.14.5 => 7.14.5 
    @babel/core: ^7.14.5 => 7.14.5 
    @babel/eslint-parser: ^7.14.5 => 7.14.5 
    babel-jest: ^27.0.2 => 27.0.2 
    babel-loader: ^8.2.2 => 8.2.2 
    eslint: ^7.28.0 => 7.28.0 
    jest: ^27.0.4 => 27.0.4 
```

**Comment by nicolo-ribaudo** [comment] 2021-06-14 15:08
How can I reproduce the error? I tried running `yarn && yarn test-only` in that PR but it doesn't fail.

**Comment by nicolo-ribaudo** [comment] 2021-06-14 15:12
Oh I see it failing now, but it's inconsistent.

**Comment by nicolo-ribaudo** [comment] 2021-06-14 15:33
This might be a Jest bug.

Since V8's `yield* (intermediate value)(intermediate value)(intermediate value)(intermediate value)` is quite cryptic, I replaced line 146 of https://unpkg.com/browse/@babel/core@7.14.5/lib/config/files/configuration.js with this code:
```js
  const it = _gensync().all(names.map(filename => readConfig(_path().join(dirname, filename), envName, caller)));
  const configs = yield* it;
```
this better revealed the problem: it now throws that `_gensync().all` is not a function.

I thus replaced it with this:
```js
  try {
    var it = _gensync().all(names.map(filename => readConfig(_path().join(dirname, filename), envName, caller)));
  } catch (e) {
    // console.log("GENS", typeof _gensync().all);
    e.message += " (" + Object.getOwnPropertyNames(require("gensync")).join(",") + ")";
    throw e;
  }
  const configs = yield* it;
```

And it now logs `Error while loading config - _gensync(...).all is not a function ()`. Since `require("gensync")` is a function with some static properties, I would have expected `Error while loading config - _gensync(...).all is not a function (length,name,prototype,all,race)`. For some reason that require call is returning an empty object, as if it didn't evaluate the `gensync` module.

I _think_ this is a Jest bug because Jest completely replaces `require`'s implementation.

**Comment by mrtnzlml** [comment] 2021-09-28 21:24
I think it is still valid, yes, because I didn't have time to report it any further (to Jest) or try to fix it yet. 🙈

**Comment by nicolo-ribaudo** [comment] 2021-09-28 21:36
@KShivendu I assigned this to you, but it might be quite hard to debug sine:
- the error doesn't happen consistently
- it could be a bug in Jest and not in Babel

This issue can either be fixed in Babel, or reduced to a reproduction without Babel and reported to Jest.

**Comment by tbergq** [comment] 2021-09-30 07:19
I saw this issue again today, so It does still exist.

**Comment by tbergq** [comment] 2021-09-30 07:26
I got the error on my local machine, but the same commit passed on the CI, so yes, it doesn't happen consistently.

**Comment by tbergq** [comment] 2021-09-30 08:30
Delete node modules, clear yarn cache and run jest with `--no-cache` made it work on my local machine again.

**Comment by liuxingbaoyu** [comment] 2023-03-14 19:09
Looks outdated, I'll close it.

**Closed by liuxingbaoyu** 2023-03-14 19:09 UTC
Labels: i: bug, help wanted, pkg: core

**Comment by mrtnzlml** [comment] 2023-03-15 10:54
@liuxingbaoyu Thanks! I haven't seen this issue for a while. 😎
