### ISSUE TITLE
TypeError: Cannot read property 'suppressDeprecationMessages' of undefined

### ISSUE THREAD

**Issue by wforney** [babel/babel#1992] opened 2015-07-13 18:48 UTC
Getting this when we updated jspm loader today.

**Comment by sebmck** [comment] 2015-07-13 18:49
Are you on the latest version of Babel?

**Comment by wforney** [comment] 2015-07-13 19:13
We are using 5.6.19 according to this...

err  TypeError: Cannot read property 'suppressDeprecationMessages' of undefined
         at Logger.deprecate (file:C:/Sources/Blossor/Blossor.Web/jspm_packages/npm/babel-core@5.6.19/browser.js:10421:23)
         at OptionManager.normaliseOptions (file:C:/Sources/Blossor/Blossor.Web/jspm_packages/npm/babel-core@5.6.19/browser.js:10957:18)
         at OptionManager.init (file:C:/Sources/Blossor/Blossor.Web/jspm_packages/npm/babel-core@5.6.19/browser.js:11000:10)
         at File.initOptions (file:C:/Sources/Blossor/Blossor.Web/jspm_packages/npm/babel-core@5.6.19/browser.js:9680:75)
         at new File (file:C:/Sources/Blossor/Blossor.Web/jspm_packages/npm/babel-core@5.6.19/browser.js:9667:22)
         at Pipeline.transform (file:C:/Sources/Blossor/Blossor.Web/jspm_packages/npm/babel-core@5.6.19/browser.js:15032:16)
         at C:\Sources\Blossor\Blossor.Web\node_modules\jspm\node_modules\systemjs-builder\compilers\es6.js:125:31
         at tryCatchReject (C:\Sources\Blossor\Blossor.Web\node_modules\jspm\node_modules\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.src.js:1183:30)
         at runContinuation1 (C:\Sources\Blossor\Blossor.Web\node_modules\jspm\node_modules\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.src.js:1142:4)
         at Fulfilled.when (C:\Sources\Blossor\Blossor.Web\node_modules\jspm\node_modules\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.src.js:930:4)
         at Pending.run (C:\Sources\Blossor\Blossor.Web\node_modules\jspm\node_modules\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.src.js:821:13)
         at Scheduler._drain (C:\Sources\Blossor\Blossor.Web\node_modules\jspm\node_modules\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.src.js:97:19)
         at Scheduler.drain (C:\Sources\Blossor\Blossor.Web\node_modules\jspm\node_modules\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.src.js:62:9)

**Comment by sebmck** [comment] 2015-07-13 19:15
This is jspm/jspm-cli#809 and should be able to be fixed by upgrading everything to the latest.

**Comment by wforney** [comment] 2015-07-13 21:11
Well, I ran this and it is still broken... am I missing something?
C:\Sources\Blossor\Blossor.Web>jspm install npm:babel-core --latest

Then I get this error on bundling...

err  TypeError: Cannot read property 'suppressDeprecationMessages' of undefined
         at Logger.deprecate (file:C:/Sources/Blossor/Blossor.Web/jspm_packages/npm/babel-core@5.6.20/browser.js:10446:23)
         at OptionManager.normaliseOptions (file:C:/Sources/Blossor/Blossor.Web/jspm_packages/npm/babel-core@5.6.20/browser.js:10982:18)
         at OptionManager.init (file:C:/Sources/Blossor/Blossor.Web/jspm_packages/npm/babel-core@5.6.20/browser.js:11025:10)
         at File.initOptions (file:C:/Sources/Blossor/Blossor.Web/jspm_packages/npm/babel-core@5.6.20/browser.js:9705:75)
         at new File (file:C:/Sources/Blossor/Blossor.Web/jspm_packages/npm/babel-core@5.6.20/browser.js:9692:22)
         at Pipeline.transform (file:C:/Sources/Blossor/Blossor.Web/jspm_packages/npm/babel-core@5.6.20/browser.js:15057:16)
         at C:\Sources\Blossor\Blossor.Web\node_modules\jspm\node_modules\systemjs-builder\compilers\es6.js:125:31
         at tryCatchReject (C:\Sources\Blossor\Blossor.Web\node_modules\jspm\node_modules\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.src.js:1183:30)
         at runContinuation1 (C:\Sources\Blossor\Blossor.Web\node_modules\jspm\node_modules\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.src.js:1142:4)
         at Fulfilled.when (C:\Sources\Blossor\Blossor.Web\node_modules\jspm\node_modules\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.src.js:930:4)
         at Pending.run (C:\Sources\Blossor\Blossor.Web\node_modules\jspm\node_modules\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.src.js:821:13)
         at Scheduler._drain (C:\Sources\Blossor\Blossor.Web\node_modules\jspm\node_modules\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.src.js:97:19)

**Comment by jmm** [comment] 2015-07-13 21:25
@wforney Please mark up code in your posts.

**Comment by wforney** [comment] 2015-07-14 00:01
Ok, after updating everything under the sun and dumping my cache a few hundred times it started working. :)

**Comment by nvivo** [comment] 2015-07-14 11:35
Tried updating multiple times and still having the same issue.

**Comment by guybedford** [comment] 2015-07-14 11:57
Apparently downgrading from 5.6.20 to 5.5.5 fixed the issue for @nvivo. Could this be a regression in Babel?

**Comment by sebmck** [comment] 2015-07-14 12:21
I hope not, I'll reopen until I've had a chance to look into it and confirm.

**Comment by guybedford** [comment] 2015-07-14 12:23
@OrKon posted the following in the jspm chat:

﻿﻿I have the same problem. it looks like a workaround is to change the browser.js:10445 to the following:

```javascript
  Logger.prototype.deprecate = function deprecate(msg) {
    msg = this._buildMessage(msg);

    // already seen this message
    if (seenDeprecatedMessages.indexOf(msg) >= 0) return;

    // make sure we don't see it again
    seenDeprecatedMessages.push(msg);

    console.error(msg);
  };
```

looks like a babel issue
i.e. in this statement if (this.file.opts.suppressDeprecationMessages) return; opts are not always present

**Comment by nvivo** [comment] 2015-07-14 12:26
It looks like [here](https://github.com/babel/babel/blob/master/src/babel/transformation/file/logger.js#L50) `opts` is undefined.

Maybe just replace:

```js
if (this.file.opts.suppressDeprecationMessages) return;
```

for 
```js
if (this.file.opts && this.file.opts.suppressDeprecationMessages) return;
```

But should `opts` be undefined there?

**Closed** 2015-07-15 11:17 UTC
