### ISSUE TITLE
bug: Can't resolve '@babel/runtime/helpers/esm/extends [7.13.0 to 7.13.5]

### ISSUE THREAD

**Issue by merlinpatt** [babel/babel#12881] opened 2021-02-23 17:25 UTC
## Bug Report

**Current behavior**

When the `Run server` step runs in this [GitHub Actions Build](https://github.com/paypal/paypal-messaging-components/runs/1962511800), this error is given:

`ModuleNotFoundError: Module not found: Error: Can't resolve '@babel/runtime/helpers/esm/extends'`

This currently happens with `@babel/runtime` from `7.13.0` to `7.13.5`.

**Current Fix**
I was able to resolve this by install @babel/runtime` as a devDependency and forcing it to stay at `7.12.18`. This can be seen in this [GitHub Actions Build](https://github.com/paypal/paypal-messaging-components/runs/1963289658)

**Environment**

```
  System:
    OS: macOS 10.15.7
  Binaries:
    Node: 12.20.1 - ~/.nvm/versions/node/v12.20.1/bin/node
    npm: 6.14.10 - ~/.nvm/versions/node/v12.20.1/bin/npm
  npmPackages:
    @babel/register: ^7.10.4 => 7.12.13 
    babel-eslint: ^10.0.1 => 10.1.0 
    babel-jest: ^25.1.0 => 25.5.1 
    babel-plugin-module-resolver: ^4.0.0 => 4.1.0 
    eslint: ^6.8.0 => 6.8.0 
    eslint-import-resolver-babel-module: ^5.1.2 => 5.2.0 
    jest: ^26.1.0 => 26.6.3 
    webpack: ^4.32.0 => 4.46.0 
```

**Additional context**
I'm not sure but I think this may be related to #12880.

**Comment by nicolo-ribaudo** [comment] 2021-02-23 17:30
This might be fixed by https://github.com/babel/babel/pull/12877

**Comment by nicolo-ribaudo** [comment] 2021-02-23 17:46
Can you check if v7.13.6 of `@babel/runtime` fixes this?

**Comment by merlinpatt** [comment] 2021-02-23 17:55
Unfortunately it did not fix it.

**Comment by akshay-kr** [comment] 2021-02-23 18:00
I am also facing the same issue. Updating `@babel/runtime` version to `v7.13.6` did not work but forcing to stay on `7.12.18` fixed the issue.

**Comment by nicolo-ribaudo** [comment] 2021-02-23 18:00
In `@babel/runtime/helpers/extends` there is an `index.js` file, so I'm not sure how something could not resolve it :thinking:

**Comment by nicolo-ribaudo** [comment] 2021-02-23 18:04
Oh I think I know the problem

**Comment by nicolo-ribaudo** [comment] 2021-02-23 18:12
I accidentally pushed the fix to `main` rather than to a PR: https://github.com/babel/babel/commit/cfdbdc0d1c0f061b9633b04d85b54892e01cdd4d

The problem is that we had export maps like `"./helpers/esm/*: "./helpers/esm/*.js"` which don't work in every tool, so we also had `"./helpers/esm/: "./helpers/esm/"` as a fallback.
However, the fallback doesn't specify the `.js` extension, so it fails in some tools.

I fixed it by explicitly listing all the exports of the `esm` folder.

**Comment by fengxinming** [comment] 2021-02-24 04:32
`.mjs` may not be resolved in some reasons，please @nicolo-ribaudo change `_index.mjs` to `_index.js`

**Comment by nicolo-ribaudo** [comment] 2021-02-24 08:52
Sorry I forgot to release the fix, doing it now: https://github.com/babel/babel/actions/runs/595458532

**Comment by tianleiwufeng** [comment] 2021-02-24 09:59
![image](https://user-images.githubusercontent.com/13955666/108983442-d6d94780-76c9-11eb-9481-1fd7e9a903f3.png)
i face the same question with v7.13.7,my outer babel version is v6,while some package use v7

**Comment by nicolo-ribaudo** [comment] 2021-02-24 10:04
That seems unrelated, please open a new issue with a link to a GitHub repository I can download to reproduce the error.

**Comment by beiifeng** [comment] 2021-02-24 10:15
> That seems unrelated, please open a new issue with a link to a GitHub repository I can download to reproduce the error.

1.
![image](https://user-images.githubusercontent.com/18087934/108985579-2c165880-76cc-11eb-8fc9-a698f0c3745d.png)

2.
![image](https://user-images.githubusercontent.com/18087934/108985703-4b14ea80-76cc-11eb-9ded-6b5f089e3920.png)

**Comment by nicolo-ribaudo** [comment] 2021-02-24 10:20
> please open a new issue with a link to a GitHub repository I can download to reproduce the error.

This is the important part: without it I don't know what's the issue.

From the first screenshot you posted it seems like that file is exporting a string, but it's clearly _not_ exporting a string in the second screenshot.

**Comment by tianleiwufeng** [comment] 2021-02-24 10:26
i guess babel v6 compile v7.13.x into
![image](https://user-images.githubusercontent.com/13955666/108987009-c1feb300-76cd-11eb-8457-e8cf8adc5b24.png)

**Comment by beiifeng** [comment] 2021-02-24 10:26
> > please open a new issue with a link to a GitHub repository I can download to reproduce the error.
> 
> This is the important part: without it I don't know what's the issue.
> 
> From the first screenshot you posted it seems like that file is exporting a string, but it's clearly _not_ exporting a string in the second screenshot.

first screenshot:
we think it will import an function from _"@babel/runtime/helpers/esm/slicedToArray"_  , but got an file content with base64.

second screenshot:
if i change _export { default } from "../slicedToArray/_index.mjs"_  to  _export { default } from "../slicedToArray/index.js"_  , it will be ok.

**Comment by nicolo-ribaudo** [comment] 2021-02-24 10:28
I see, but why is it loading that file as base64? That doesn't make sense in any runtime or bundler I know of.

**Comment by beiifeng** [comment] 2021-02-24 10:34
> I see, but why is it loading that file as base64? That doesn't make sense in any runtime or bundler I know of.
> 
> index.mjs is a normal JavaScript esm file.

yeah, maybe wrong config/env...   or old version of webpack.

**Comment by beiifeng** [comment] 2021-02-24 10:35
i will making repository with sample for reproduce .

**Comment by long-zhuge** [comment] 2021-02-24 10:52
> > That seems unrelated, please open a new issue with a link to a GitHub repository I can download to reproduce the error.
> 
> 
> ![image](https://user-images.githubusercontent.com/18087934/108985579-2c165880-76cc-11eb-8fc9-a698f0c3745d.png)
> 
> 
> ![image](https://user-images.githubusercontent.com/18087934/108985703-4b14ea80-76cc-11eb-9ded-6b5f089e3920.png)

the project package.json add `@Babel/core`, `@Babel/runtime`, `@Babel/runtime-corejs3` is `7.12.X`. The problem of error reporting has been solved temporarily

**Comment by nicolo-ribaudo** [comment] 2021-02-24 11:03
Could it be https://github.com/facebook/create-react-app/issues/5234? It seems like a create-react-app bug.

**Comment by beiifeng** [comment] 2021-02-24 12:51
resolved.

_why is it loading that file as base64_  :  **url-loader**. It build-in roadhog.

solution:
add webpack.config.js as 
```js
module.exports = config => {
  config.module.rules.forEach(item => {
    if (item.loader && item.loader.indexOf('url-loader') > -1) {
      item.exclude.push(/\.mjs$/);
    }
  });
  return config;
};
```

thanks

**Comment by paulashwin** [comment] 2021-02-24 13:09
We are getting this below error after upgrading babel from `7.12.x` to `7.13.x`. Any idea to resolve would be of much help.

```js
Uncaught Error: Could not find module `@babel/runtime/helpers/defineProperty/_index.mjs` imported from `@babel/runtime/helpers/esm/defineProperty`
    at missingModule (loader.js:247)
    at findModule (loader.js:258)
    at Module.findDeps (loader.js:168)
    at findModule (loader.js:262)
    at Module.findDeps (loader.js:168)
    at findModule (loader.js:262)
    at Module.findDeps (loader.js:168)
    at findModule (loader.js:262)
    at requireModule (loader.js:24)
    at tests-suffix.js:1
```

**Comment by nicolo-ribaudo** [comment] 2021-02-24 13:23
@paulashwin If the `@babel/runtime/helpers/esm/defineProperty.js` file looks like this: https://unpkg.com/browse/@babel/runtime@7.13.7/helpers/esm/defineProperty.js
and if `@babel/runtime/helpers/defineProperty/_index.mjs` exists, then it's a bug in whatever tool/bundler is throwing that error 🤔

**Comment by nicolo-ribaudo** [comment] 2021-02-24 14:12
I'm closing this issue, since:
1) The original bug report has been fixed.
2) @beiifeng fixed the webpack config problem (which is caused by a roadhog or af-webpack bug, where it loads some JS files as URLs)
3) @tianleiwufeng solved the problem (https://github.com/babel/babel/issues/12888#issuecomment-785016029), which was again caused by a wrong webpack config that transformed `.mjs` files to strings rather than handling them as js
4) @paulashwin's error is completely different. Please open a new issue with a repository I can clone to reproduce the bug.

**Closed** 2021-02-24 14:16 UTC
Labels: i: bug, i: needs triage

**Comment by paztis** [comment] 2021-02-24 17:44
freshly installed @babel/runtime v7.13.7
I crash my typescript builds (4.2.2)

it is due to 
helpers/extends/index.js badly generated code
seems there's inner module.exports in the function declaration

```
function _extends() {
  module.exports = _extends = Object.assign || function (target) {
    for (var i = 1; i < arguments.length; i++) {
      var source = arguments[i];

      for (var key in source) {
        if (Object.prototype.hasOwnProperty.call(source, key)) {
          target[key] = source[key];
        }
      }
    }

    return target;
  };

  module.exports["default"] = module.exports, module.exports.__esModule = true;
  return _extends.apply(this, arguments);
}

module.exports = _extends;
module.exports["default"] = module.exports, module.exports.__esModule = true;
```
works correctly when I change the content of index.js file with the content of _index.mjs
```
export default function _extends() {
  _extends = Object.assign || function (target) {
    for (var i = 1; i < arguments.length; i++) {
      var source = arguments[i];

      for (var key in source) {
        if (Object.prototype.hasOwnProperty.call(source, key)) {
          target[key] = source[key];
        }
      }
    }

    return target;
  };

  return _extends.apply(this, arguments);
}
```

**Comment by nicolo-ribaudo** [comment] 2021-02-24 18:34
@paztis What bundler are you using?

**Comment by paztis** [comment] 2021-02-24 18:37
typescript (tsc)
But here it is parsing a javascript file that be transpiled with babel (class extends transpilation) .

It was not failing until I upgrade to babel 7.13. Any changes on your side in the source code of this file ?

**Comment by nicolo-ribaudo** [comment] 2021-02-24 18:41
> Any changes on your side in the source code of this file?

This file is new, the previous versions were https://unpkg.com/browse/@babel/runtime@7.12.0/helpers/extends.js and https://unpkg.com/browse/@babel/runtime@7.12.0/helpers/esm/extends.js. I _think_ #12883 will fix your error, but I cannot be sure without knowing what is throwing the error (Node.js? Webpack? another bundler? tsc itself when typechecking?)

**Comment by paztis** [comment] 2021-02-24 18:42
Tsc itself

Le mer. 24 févr. 2021 à 19:41, Nicolò Ribaudo <notifications@github.com> a
écrit :

**Comment by JLHwung** [comment] 2021-02-24 18:43
Can you provide a reproduction repo?

**Comment by paztis** [comment] 2021-02-24 18:46
Hard for me. We've got a n enormous private repo that was working fine and sudently crashes.
Here is the ts config file:

```
{
  "compilerOptions": {
    "jsx": "react-jsx"
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "node",
    // Process & infer types from .js files.
    "allowJs": true,
    "maxNodeModuleJsDepth": 3,
    // Enable strictest settings like strictNullChecks & noImplicitAny.
    "strict": false,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    // "noImplicitThis": true,
    "isolatedModules": false, // Disallow features that require cross-file information for emit.
    "esModuleInterop": true, // Import non-ES modules as default imports.
    "skipLibCheck": true, // Do not validate the dependencies definitions
    "experimentalDecorators": true,
    "suppressImplicitAnyIndexErrors": true,
    // resolution of dependencies/
    "resolveJsonModule": true,
    "baseUrl": "."
  }
}
```

With allowJs option it processes the us files also.
Typescript version is 4.2.2

**Comment by paztis** [comment] 2021-02-24 18:47
I also create a defect in typescript: https://github.com/microsoft/TypeScript/issues/42942#issuecomment-785271007

**Comment by paztis** [comment] 2021-02-24 20:39
here is a repo where I reproduce the defect
https://codesandbox.io/s/twilight-sound-ll66d?file=/tsconfig.json

Locally, with the same code I've the error, but don't know why not on codeSandbox

**Comment by nicolo-ribaudo** [comment] 2021-02-24 21:05
If you can only reproduce it locally, maybe try deleting `node_modules` and reinstalling it :thinking:

**Comment by paztis** [comment] 2021-02-24 21:31
no I create from scratch specific repo and always reproduce it
Try toi create also the same repo locally and you will see

It contains only 4 files: package.json, tsConfig.json, src/index.ts and src/js/problematicFile.js
Do npm install (or yarn install), then npm run build

**Comment by nicolo-ribaudo** [comment] 2021-02-24 21:39
It's possible that this will be fixed by https://github.com/babel/babel/commit/6a471decc3f4b5aef54dfca596e3f6d3843c8cf6 in the next release, but I'm not 100% sure because I cannot reproduce the error when I download that codesandbox example :frowning_face:

**Comment by paztis** [comment] 2021-02-24 22:15
ok I've update the codeSandbox: https://codesandbox.io/s/twilight-sound-ll66d
I was setting **index.js** instead of **index.ts**

you can test in now it fails everywhere


when will be the next release ?
any way to test it ?

**Comment by nicolo-ribaudo** [comment] 2021-02-24 22:22
Ok, I can reproduce the error. However, I now understand that it will not be fixed in the next Babel release because this is 100% a TypeScript bug.

**Comment by burritoIand** [comment] 2021-02-28 20:55
just hit this in my project using [ember-cli-babel@7.24.0](https://github.com/babel/ember-cli-babel/tree/v7.24.0) that uses `@babel/runtime: ^7.12.0` and resolves to 7.13.X
```
Error: Could not find module `@babel/runtime/helpers/initializerDefineProperty/_index.mjs` imported from `@babel/runtime/helpers/esm/initializerDefineProperty`
```

**Comment by nicolo-ribaudo** [comment] 2021-03-01 10:30
@burritoIand That isn't a Babel bug. Whatever bundler Ember is using, it probably configured to ignore files ending in `mjs`.

However, we might stop using `.mjs` to workaround this bundler/configuration bug: https://github.com/babel/babel/pull/12919

**Comment by burritoIand** [comment] 2021-03-01 22:02
> @burritoIand That isn't a Babel bug. Whatever bundler Ember is using, it probably configured to ignore files ending in `mjs`.
> 
> However, we might stop using `.mjs` to workaround this bundler/configuration bug: #12919

@nicolo-ribaudo ok great thanks!
