### ISSUE TITLE
Unnecessary  require with transform runtime? 

### ISSUE THREAD

**Issue by ibreathebsb** [babel/babel#8675] opened 2018-09-11 12:38 UTC
## Problem

My target environment is chrome 67, but still `corejs/promise` is required.

## Config

**package.json**

```json

{
  "name": "play-with-babel",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "@babel/cli": "^7.0.0",
    "@babel/core": "^7.0.0",
    "@babel/plugin-transform-runtime": "^7.0.0",
    "@babel/preset-env": "^7.0.0"
  },
  "dependencies": {
    "@babel/runtime": "^7.0.0",
    "@babel/runtime-corejs2": "^7.0.0"
  }
}

```
**babel.config.js**

```js
"use strict";

module.exports = function (api) {
  const env = api.env()
  const envOpts = {
    loose: true,
    modules: false,
    useBuiltIns: 'usage',
    targets: {
      chrome: "67"
    },
    debug: true
  }
  const config = {
    sourceType: "script",
    comments: false,
    presets: [
      ["@babel/preset-env", envOpts]
    ],
    plugins: [
      ["@babel/plugin-transform-runtime", {
        corejs: 2 //  <= avoid polluting global environment
      }]
    ]
  };
  return config;
};

```
## Input 

```js
const p = Promise.resolve(1)
```

## Output

```js
// as you can see,  **const** is not transformed which is correct

// but promise should not be imported right?

var _Promise = require("@babel/runtime-corejs2/core-js/promise"); 

const p = _Promise.resolve(1);
```

**Comment by ishen7** [comment] 2018-12-18 13:07
I have the same problem，when i use `exclude:['es6.promise']`,but it still include `promise` from `core-js`

### Config
```js
// .babelrc.js
module.exports = {
  presets: [
    ['@babel/preset-env', {
      debug: true,
      useBuiltIns: 'usage',
      targets: {
        browsers: ['ios >= 8.0', 'android >= 4.1']
      },
      exclude: [
        'es6.promise'
      ]
    }]
  ],
  plugins: [
    ['@babel/plugin-transform-runtime', {
      corejs: 2
    }]
  ]
}
```

### Input
```js
// index.js

export const promises = () => new Promise(resolve => setTimeout(() => resolve('hello babel'), 100))
export const includes = () => [].includes(1)
```

### Output
```js
// index.js

"use strict";

var _interopRequireDefault = require("@babel/runtime-corejs2/helpers/interopRequireDefault");

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.includes = exports.promises = void 0;

require("core-js/modules/es7.array.includes");

require("core-js/modules/es6.string.includes");

var _promise = _interopRequireDefault(require("@babel/runtime-corejs2/core-js/promise"));

var promises = function promises() {
  return new _promise.default(function (resolve) {
    return setTimeout(function () {
      return resolve('hello babel');
    }, 100);
  });
};

exports.promises = promises;

var includes = function includes() {
  return [].includes(1);
};

exports.includes = includes;
```

**Comment by nicolo-ribaudo** [comment] 2021-01-31 22:35
Closing, the problem is that in the posted config you are using `@babel/plugin-transform-runtime`, which doesn't support `targets`. They are supported by the new https://github.com/babel/babel-polyfills packages.

**Closed by nicolo-ribaudo** 2021-01-31 22:35 UTC
