### ISSUE TITLE
Version 7.12.11 does not compile

### ISSUE THREAD

**Issue by miestr** [babel/babel#12519] opened 2020-12-17 09:29 UTC
## Bug Report

**Current behavior**
I use babel in a react application. When trying to produce a build (yarn run build), it fails with error code:
TypeScript error in /var/jenkins/.../node_modules/@babel/types/lib/index.d.ts(1450,50):
'{' or ';' expected.  TS1144
```
      1448 | }): ReturnedChild[];
      1449 | 
    > 1450 | declare function assertNode(node?: any): asserts node is Node;
           |                                                  ^
      1451 | 
```
As a current fix I declared a yarn resolution to use version 7.12.10, which compiles without any issues.
```
- Babel version:  v7.12.11
- Node 10.15.3, yarn 1.22.4, typescript 3.2.4
- OS: Windows 10
- How you are using Babel: webpack
- ```

**Comment by nicolo-ribaudo** [comment] 2020-12-17 11:12
Thanks for the bug report! It's the second like this we get, but I cannot reproduce it on the TS playground with any TS version >= 3.7 ( and for older versions we provide a different dts file).
What version are you using?

**Comment by miestr** [comment] 2020-12-17 11:32
Thank you for your reply! I am using typescript version 3.2.4, as mentioned
in the description.

чт, 17 дек. 2020 г. в 12:12, Nicolò Ribaudo <notifications@github.com>:

**Comment by nicolo-ribaudo** [comment] 2020-12-17 12:08
(I deleted my reply as soon as I posted it because I noticed you already mentioned it :sweat_smile:)

We specify `typesVersions` in out `package.json` (https://unpkg.com/browse/@babel/types@7.12.11/package.json), so I'm surprised that TS is reading that `index.d.ts` file :thinking:

**Comment by JLHwung** [comment] 2020-12-17 12:11
I think typeVersions does not work on legacy typescript versions. There was the reason why we specified >3.7 before 7.12.11.

**Comment by AviVahl** [comment] 2020-12-17 12:12
IIRC ts@3.2's support for `typeVersions` was kinda broken. The thing is, even DefinitelyTyped dropped support for that version already, per https://github.com/DefinitelyTyped/DefinitelyTyped#older-versions-of-typescript-31-and-earlier allowing them to start using that feature more widespread, as all supported ts versions of DT now handle typeVersions properly.

**Comment by nicolo-ribaudo** [comment] 2020-12-17 12:18
I have a fix for this, I will open a PR when I get home later (the code is already there, but I just turned off the PC 😛)

**Comment by salvoravida** [comment] 2020-12-17 12:29
great! we were waiting for your Christmas Edition CI break!

**Comment by nicolo-ribaudo** [comment] 2020-12-17 12:57
@salvoravida _Every_ time you comment in this repository you do so sarcastically, pretending we owe you something while we do not. Unless you want to be collaborative, you are not welcome to interact in this repository.

**Comment by sawo** [comment] 2020-12-17 16:33
It might sound silly, but as soon as I reformatted the index.d.ts file and the function declarations broke into multiple lines,
the errors disappeared and I was able to compile.

**Comment by nicolo-ribaudo** [comment] 2020-12-17 16:52
As another workaround until we release a fix, you can copy the contents of `@babel/types/lib/index-ts3.7.d.ts` into `@babel/types/lib/index.d.ts`.

**Closed** 2020-12-17 17:34 UTC
Labels: Flow -> TS, i: bug, i: regression, pkg: types

**Comment by DJmRek** [comment] 2020-12-17 19:06
Guys you saved me today! Had a similar error cause by typescript 3.4.5 and @bable/types. Thanks 
/sparkle @nicolo-ribaudo 
/sparkle @AviVahl

**Comment by mihanizm56** [comment] 2020-12-19 23:58
get a temp
![image](https://user-images.githubusercontent.com/37120827/102702065-4caad800-426f-11eb-853a-be7994878309.png)
 fix by providing the oldest version in "resolutions" field in package.json
awaiting for the fix
ts version 3.6.4
cra v3.4.3 with --typescript
