### ISSUE TITLE
Unsets instance properties set in superclass if type annotation is present

### ISSUE THREAD

**Issue by hallettj** [babel/babel#1396] opened 2015-04-30 21:11 UTC
If a class includes a Flow type annotation for a property, and that property is set by a call to `super()`, the property is reverted to `undefined` after the call to `super`.  Here is a simple example ([repl link](http://babeljs.io/repl/#?experimental=false&evaluate=true&loose=false&spec=false&code=class%20Parent%20%7B%0A%20%20constructor(prop)%20%7B%0A%20%20%20%20this.prop%20%3D%20prop%3B%0A%20%20%7D%0A%7D%0A%0Aclass%20Child%20extends%20Parent%20%7B%0A%20%20prop%3A%20number%3B%0A%20%20constructor(prop%3A%20number)%20%7B%0A%20%20%20%20super(prop)%3B%0A%20%20%20%20console.log(this.prop)%3B%20%20%2F%2F%20is%20undefined%2C%20should%20not%20be%0A%20%20%7D%0A%7D)):

```javascript
class Parent {
  constructor(input) {
    this.prop = input.length;
  }
}

class Child extends Parent {
  prop: number;
  constructor(input: string) {
    super(prop);
    console.log(this.prop);  // is undefined, should not be
  }
}
```

The problem appears to be that Babel interprets the `prop` type annotation as a property initializer.  I can see that `prop` is set to `undefined` in an `__initializeProperties()` call:

```javascript
_createClass(Child, [{
    key: "__initializeProperties",
    value: function __initializeProperties() {
      this.prop = undefined;
    }
  }]);
```

This happens even with experimental features turned off.  (My understanding is that property initializers are an experimental feature.)

I think it does make sense that the syntax for property initializers overlaps with the syntax for property type annotations.  But the behavior of unsetting properties is inconvenient for me. Two possible fixes occur to me:
- Do not initialize properties if no value is given in the initializer.
- Initialize properties before calling super.

**Comment by sebmck** [comment] 2015-04-30 21:14
cc @jeffmo What's the intended behaviour here? [14.5.14 23.iii.a](https://gist.github.com/jeffmo/054df782c05639da2adb#14514-runtime-semantics-classdefinitionevaluation) seems to imply that it should be `null`?

**Comment by jeffmo** [comment] 2015-04-30 21:46
Hmm, I think you need to specify the `prop` property type on the base class anyway so why specify it again on the child?

As far as the spec text -- I think my intent was to make it so that a lack of an initializer expression is simply a no-op though. I'll have to run back through and make sure there isn't a problem that causes elsewhere... I'm about to run to dinner, but I will try to come back to this either after dinner or tomorrow and see if I can find any reason we can't fix this to be a no-op

**Comment by sebmck** [comment] 2015-04-30 21:47
@jeffmo All good! Thanks for the quick response. FWIW, the decorator/property initializer interop relies on this behaviour wherein you can do:

```javascript
class Foo {
  @bar foo;
}
```

**Comment by hallettj** [comment] 2015-04-30 21:49
@jeffmo In the project I am working on the superclass is polymorphic.  The right thing to do would be to express the property type in a type parameter; e.g. `class Child Extends Parent<number>`.  But for reasons that I can summarize as "type checking in Javascript is very rough right now", I can't do that in my case.

**Comment by jeffmo** [comment] 2015-04-30 21:51
@sebmck: Looking again at my spec text, I believe it says what I expected -- note that `initExpr` is the initializer function value (not the initial value that gets assigned to the property slot). As far as decorators being reliant on `null` being a value -- couldn't they just observe that the `initializer` key on the psuedo-descriptor is null and use that as a signal that there is a property, but no initialization expression?

@hallettj: Ok, understand

**Comment by sebmck** [comment] 2015-04-30 21:55
@jeffmo 

> Looking again at my spec text, I believe it says what I expected -- note that initExpr is the initializer function (not the initial value that gets assigned to the property slot)

Ah right, noted.

> As far as decorators being reliant on null being a value -- couldn't they just observe that the initializer key on the psuedo-descriptor is null and use that as a signal that there is a property, but no initialization expression?

Sure, but setting a descriptor depending on whether it has a decorator or not feels kinda weird.

**Comment by jeffmo** [comment] 2015-04-30 22:01
> Sure, but setting a descriptor depending on whether it has a decorator or not feels kinda weird.

Wait, so there is still a psuedo-descriptor set. The only difference is that the psuedo-descriptor has a property keyed by `"initializer"` whose value is `null` when there is no initializer -- vs  a value of `function() { return <<initializer expression here>>; }` when there is an expression...so there's always a psuedo-descriptor for the property, there's just not always an initializer function.

Am I correctly understanding what you're saying?

**Comment by sebmck** [comment] 2015-04-30 22:03
@jeffmo Oh wait, nevermind. Upon reading your spec text for `[[Construct]]` again it's obvious now. Thanks for the clarification!

**Closed** 2015-04-30 22:09 UTC

**Comment by hallettj** [comment] 2015-04-30 22:10
Much thanks for the fast and reasoned responses!
