### ISSUE TITLE
Bug: 7.0.0-beta.0 - export default async function named() {} is broken

### ISSUE THREAD

**Issue by Ambroos** [babel/babel#6262] opened 2017-09-18 14:19 UTC
Bug report

### Input Code

```js
export default async function named(input) {
  return input;
}
```

Failing demo project: git@gist.github.com:e33790419e48fc6c504e39aa3b35572f.git or https://gist.github.com/Ambroos/e33790419e48fc6c504e39aa3b35572f - scripts in package.json.

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "scripts": {
    "babelify-ok": "babel input.js --out-file output.js",
  },
  "devDependencies": {
    "babel-cli": "^7.0.0-beta.0",
    "babel-preset-env": "^2.0.0-beta.0"
  },
  "babel": {
    "presets": [
      [
        "env",
        {
          "targets": {
            "browsers": [
              "IE 11",
              "last 3 Chrome versions",
              "last 2 Safari versions",
              "last 2 Firefox versions",
              "Firefox ESR",
              "last 2 Edge versions",
              "last 2 iOS versions"
            ]
          }
        }
      ]
    ]
  }
}

```

### Expected Behavior
Transpiling works as it did in 6.

### Current Behavior
```$ babel input.js --out-file output.js
TypeError: broken.js: Property declaration of ExportNamedDeclaration expected node to be of a type ["Declaration"] but instead got "ExpressionStatement"
    at Object.validate (project-dir/node_modules/babel-types/lib/definitions/index.js:86:13)
    at Object.validate (project-dir/node_modules/babel-types/lib/index.js:478:9)
    at NodePath._replaceWith (project-dir/node_modules/babel-traverse/lib/path/replacement.js:176:7)
    at NodePath.replaceWith (project-dir/node_modules/babel-traverse/lib/path/replacement.js:160:8)
    at Object.replaceWithOrRemove (project-dir/node_modules/regenerator-transform/lib/util.js:32:10)
    at PluginPass.exit (project-dir/node_modules/regenerator-transform/lib/visit.js:163:14)
    at newFn (project-dir/node_modules/babel-traverse/lib/visitors.js:236:21)
    at NodePath._call (project-dir/node_modules/babel-traverse/lib/path/context.js:68:19)
    at NodePath.call (project-dir/node_modules/babel-traverse/lib/path/context.js:42:17)
    at NodePath.visit (project-dir/node_modules/babel-traverse/lib/path/context.js:112:8)```
```

### Context
Only seems to happen when named async functions are exported in one statement: `export default async function name() {...}`. Splitting the function definition and `export default name` works, as does exporting unnamed async functions.

### Your Environment
babel-cli 7.0.0-beta.0, babel-env 2.0.0-beta.0

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-beta.0
| node             | 8.5.0
| yarn              | 1.0.2
| Operating System | macOS 10.13 Beta (17A358a)

(as you may have noticed, I like bleeding edge/beta stuff)

**Comment by hzoo** [comment] 2017-09-19 19:22
Not sure yet but my guess is that regenerator is using babel-types 6.x still and we have an issue https://github.com/facebook/regenerator/blob/3860530dce5d5988d42670858791b2b3b894c921/packages/regenerator-transform/package.json#L32 @benjamn?

**Comment by bradchristensen** [comment] 2017-09-19 22:30
I didn't realise what was actually causing this so thanks for pinpointing it! I was able to upgrade to the beta by using your suggestion of splitting up the function definition and export statement, which is good enough for me since I only have a few of these.

For what it's worth, I noticed that this became an issue for me during the alphas but I was able to work around it at the time by pinning to `babel-core@7.0.0-alpha.15` and `babel-preset-env@2.0.0-alpha.12`. It's nice to be able to upgrade so that my mish-mash of versions doesn't confuse the next dev who comes along :joy:

**Comment by hzoo** [comment] 2017-09-19 22:39
The error is coming from babel-types which validates ast node types, and we aren't know that regenerator is using a different version so it might be incompatible

**Comment by bradchristensen** [comment] 2017-09-19 23:31
Yikes! I've just tracked that down to being caused by a different breaking change in `babel-preset-env`. I had a `browserslist` section in my `package.json` (which I see now may not have even been used until now) which I intended to be conditionally overridden by my `node` target in `.babelrc.js`. I see in the code that the updated documentation states that this will now be merged in with the existing targets if no `browsers` are defined. This was causing just about all of the transformations to be applied when they shouldn't have been 😓 Adding `ignoreBrowserslistConfig: true` fixes this. I guess that explains why I didn't run into this problem when I pinned to a previous version of preset-env. 😛

**Comment by hzoo** [comment] 2017-09-26 14:40
Hmm ok, we just need a better changelog for preset-env then, thanks!

**Comment by Ambroos** [comment] 2017-09-27 13:09
@hzoo - I think this still is an issue. Targeting Node 8 with babel-preset-env probably just disables the relevant transform as it may not be needed.

export default async function named()... is still broken as mentioned in my issue. @bradchristensen's comments are not completely related to this.

**Comment by brokentone** [comment] 2017-09-27 21:20
I'm confirming this is still an issue in beta.2, [here is a repo/branch](https://github.com/brokentone/babel-7-async-default/tree/beta-2) reproducing with the following command:  `./node_modules/.bin/babel --out-dir lib src/`

I did notice that *anonymous* functions were fixed in this situation (export, default, async). However, *named* are still not.

**Comment by bradchristensen** [comment] 2017-09-27 21:53
@Ambroos is right - I *did* run into this issue, but I was luckily able to work around it because `regenerator` shouldn't have been included in my project in the first place 😅 (thanks for pointing me in the right direction there @hzoo!)

Apologies for the confusion.

**Comment by brokentone** [comment] 2017-09-28 14:55
I've dug in a little further, and I'm pretty confident this is an incompatibility between babylon 6/7 ASTs that affects `babel-types@6` in this tree:

```
└─┬ babel-preset-env@2.0.0-beta.2
  ├─┬ babel-plugin-transform-regenerator@7.0.0-beta.2
  │ └─┬ regenerator-transform@0.10.0
  │   └── babel-types@6.26.0 
```

I assume that `regenerator` needs to update to `babel@7-beta`

**Comment by hzoo** [comment] 2017-09-28 15:05
Good investigation, seems to be the case 

https://github.com/facebook/regenerator/blob/master/packages/regenerator-transform/package.json#L32 yeah @benjamn?

This is mostly a result of regenerator and some other plugins not being in this monorepo but being a dependency in the presets

**Comment by EmilTholin** [comment] 2017-11-23 10:02
Do you think the merged update to `babel-types@7.0.0-beta.3` in [regenerator transform](https://github.com/facebook/regenerator/blob/master/packages/regenerator-transform/package.json#L32) will be enough, or will `@babel/types@7.0.0-beta.32` be needed?

**Comment by hzoo** [comment] 2017-11-23 18:55
Not sure, although we should just remove the dependency so this won't be an issue in the future https://github.com/facebook/regenerator/issues/328

**Closed** 2017-11-27 22:16 UTC
Labels: 7.x: regression, i: bug

**Comment by terion-name** [comment] 2018-05-02 15:54
still an issue in beta 3

**Comment by loganfsmyth** [comment] 2018-05-02 15:56
@terion-name beta.3 is old at this point. We've renamed all of our packages to use the `@babel` scope, so you'll want to update to use those for the most recent betas.
