### ISSUE TITLE
Bug Report: Interaction between transform-modules, transform-runtime and transform-classes

### ISSUE THREAD

**Issue by ForbesLindesay** [babel/babel#5792] opened 2017-05-30 14:50 UTC
If a helper function is added by a plugin to the top of a file, and that helper function uses a babel-runtime function like `Object.keys`, the import does not always get converted.

This only seems to happen if the helper is added from within a class.

### Input Code

```js
const assert = require('assert');
const foo = {a: true};
class MyClass {
  static query = getKeys(foo);
}
assert.deepEqual(MyClass.query, ['a']);
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
const buildHelper = template(`
  function GET_KEYS(obj) {
    return Object.keys(obj);
  }
`);

writeFileSync(
  __dirname + '/output.js',
  transformFileSync(__dirname + '/fixture.js', {
    babelrc: false,
    plugins: [
      ({types: t}) => {
        return {
          visitor: {
            Identifier(path) {
              if (path.node.name === 'getKeys') {
                const identifier = this.file.scope.generateUidIdentifier('getKeys');
                const helper = buildHelper({
                  GET_KEYS: identifier,
                });
                this.file.path.unshiftContainer("body", helper);
                path.replaceWith(identifier);
              }
            },
          },
        };
      },
      require("babel-plugin-transform-class-properties"),
      require("babel-plugin-transform-es2015-classes"),
      require("babel-plugin-transform-es2015-modules-commonjs"),
      require("babel-plugin-transform-runtime"),
    ],
  }).code
);
```

### Expected Behavior

The output code should have the import statement transformed into a `require` call.

### Current Behavior

The import statement is left in the output code.

### Possible Solution

Ensure that transform-modules always detects imports, regardless of when they are added.

### Context

I'm attempting to maintain a couple of plugins that add helper functions to the top of files when they detect certain code.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.24.1
| node             | 6.4.0
| npm              | 3.10.3
| Operating System | OSX

I've uploaded a complete demonstration of this bug to https://github.com/ForbesLindesay/demo-transform-runtime-and-es2015-modules-commonjs-order-bug so you can easily reproduce it.

**Comment by loganfsmyth** [comment] 2017-09-13 03:20
Duplicate of https://github.com/babel/babel/issues/2877

**Closed by loganfsmyth** 2017-09-13 03:20 UTC
