### ISSUE TITLE
Comment from an empty function body is moved to the end of the file

### ISSUE THREAD

**Issue by emirotin** [babel/babel#2016] opened 2015-07-16 08:14 UTC
Compare this https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=function%20f%20()%7B%0A%20%20%2F%2F%20comment%20here%0A%20%20var%20f%0A%7D

to this https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=function%20f%20()%7B%0A%20%20%2F%2F%20comment%20here%0A%7D

Is there any reason for this behaviour? I used this trick https://github.com/ractivejs/ractive/blob/db7a5d61730ad72857ae355597838b3d77f5bc28/src/utils/log.js#L21 and suddenly realised it doesn't work because of the issue. I managed to solve it by switching to a similar technique (unused variable), but this still looks like an inconsistency.

**Comment by sebmck** [comment] 2015-07-16 08:52
Duplicate of #190 and #758.

**Closed by sebmck** 2015-07-16 08:52 UTC
