### ISSUE TITLE
@babel/plugin-transform-modules-commonjs doesn’t seem to work with export { default } from

### ISSUE THREAD

**Issue by anisometropie** [babel/babel#10240] opened 2019-07-19 10:35 UTC
Hey, I’m having an issue with @babel/plugin-transform-modules-commonjs

I’m running unit tests with node, and my project uses es6 import/exports.
That’s why I need this plugin.

All of my imports work just fine when my app is running in the browser.
But jest won’t run correctly some of my tests because of failing imports.

All of my problems seem to be coming from this index.js file
```
export { default } from './RectangleBuilder'
export { default as Rectangle } from './Rectangle'
export { default as MovableRectangle } from './MovableRectangle'
```

here is an example of what jest is giving me.
this MovableRectangle is imported correctly when running in the browser, but here it is undefined:

```
 FAIL  src/objects/__tests__/Rectangle.spec.js
  ● Test suite failed to run

    TypeError: Class extends value undefined is not a constructor or null

      2 | import Vector from 'objects/Vector'
      3 | 
    > 4 | class MovableRectangle extends Rectangle {
        |                                ^
      5 |   constructor(
      6 |     x,
      7 |     y,

      at Object.Rectangle (src/objects/Rectangle/MovableRectangle.js:4:32)
      at Object.<anonymous> (src/objects/Rectangle/RectangleBuilder.js:2:1)
      at Object.<anonymous> (src/objects/Rectangle/index.js:1:1)
      at Object.<anonymous> (src/sketch.js:17:1)
      at Object.<anonymous> (src/engine/physics.js:5:1)
      at Object.<anonymous> (src/objects/Rectangle/Rectangle.js:2:1)
      at Object.<anonymous> (src/objects/__tests__/Rectangle.spec.js:1:1)
```
**There is only 3 tests that fail because of that. the rest of my tests run normally. Which means all of the other imports are correctly processed by the plugin.**

here is my configuration :

```
// .babelrc
{
  "plugins": [
    [
      "module-resolver",
      {
        "root": ["./src"],
        "alias": {
          "test": "./test",
          "underscore": "lodash"
        }
      }
    ]
  ],
  "presets": [["@babel/preset-env", { "targets": { "node": "current" } }]],
  "env": {
    "test": {
      "plugins": ["@babel/plugin-transform-modules-commonjs"]
    }
  }
}
```

```
// package.json
{
  "name": "example-1",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@babel/core": "^7.5.5",
    "@babel/preset-env": "^7.5.5",
    "babel-jest": "^24.8.0",
    "babel-loader": "^8.0.6",
    "lodash": "^4.17.14",
    "socket.io": "^2.2.0",
    "socket.io-client": "^2.2.0",
    "webpack": "^4.31.0",
    "webpack-cli": "^3.3.2",
    "webpack-dev-server": "^3.4.1"
  },
  "scripts": {
    "start": "webpack-dev-server",
    "test": "jest"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ],
  "devDependencies": {
    "@babel/plugin-transform-modules-commonjs": "^7.5.0",
    "babel-plugin-module-resolver": "^3.2.0",
    "jest": "^24.8.0"
  }
}

```

**Comment by nicolo-ribaudo** [comment] 2019-07-19 16:39
It is probably not related to this bug, but you don't need
```
  "env": {
    "test": {
      "plugins": ["@babel/plugin-transform-modules-commonjs"]
    }
  }
```
in your config.
When you are not using webpack (i.e. you are using jest), `preset-env` should automatically transpile modules to commonjs.

**Comment by nicolo-ribaudo** [comment] 2019-07-20 07:49
How are you importing `Rectangle` inside the file the is throwing?

**Comment by anisometropie** [comment] 2019-07-20 15:08
I have found a solution using mocks.
I detail the solution here :
https://stackoverflow.com/questions/57080955/using-export-default-from-with-jest

But this is more a workaround than a real solution.

someone I asked suggested this might have to do with the absolute path I’m using.
I might have to incorporate the resolver I’m using in jest config.

Right now the resolver is configured as such :+1: 
```
//.babelrc
"plugins": [
    [
      "module-resolver",
      {
        "root": ["./src"]
      }
    ]
  ]
```

**Comment by gaurav5430** [comment] 2020-06-22 15:03
> It is probably not related to this bug, but you don't need
> 
> ```
>   "env": {
>     "test": {
>       "plugins": ["@babel/plugin-transform-modules-commonjs"]
>     }
>   }
> ```
> 
> in your config.
> When you are not using webpack (i.e. you are using jest), `preset-env` should automatically transpile modules to commonjs.

Are you suggesting that "plugin-transform-modules-commonjs" only needs to be used when using webpack ?

**Comment by nicolo-ribaudo** [comment] 2020-06-22 15:06
I should have worded it as "even if you are not using webpack, you don't need `plugin-transform-modules-commonjs`". If you are using webpack not only you don't need it, but it may even cause bugs since it conflicts with Webpack's `import`/`export` handling.

**Comment by gaurav5430** [comment] 2020-06-22 15:19
right, so when do we ever need to use `plugin-transform-module-commonjs` ? 

I am struggling with a similar problem with my setup, which is solved if i use the above plugin in my babel config. 
Just trying to understand why that is

**Comment by nicolo-ribaudo** [comment] 2020-06-22 15:21
When you are not using `@babel/preset-env` (for example, because you are creating a custom preset) and you are not using webpack/rollup/parcel.

**Comment by nicolo-ribaudo** [comment] 2021-01-31 23:00
Closing, since this was seemingly not caused by Babel but by Jest (https://github.com/babel/babel/issues/10240#issuecomment-513475174)

**Closed by nicolo-ribaudo** 2021-01-31 23:00 UTC
Labels: i: needs triage, i: question
