### ISSUE TITLE
Babel-node does not work rightly

### ISSUE THREAD

**Issue by chafel** [babel/babel#2218] opened 2015-08-17 03:26 UTC
I installed babel and run ```babel-node``` which version is 5.8.21.

```javascript
> const b = 1
'use strict'
> b =2 
2
> b
2
> const b = 3
'use strict'
> b
3
```

Obviously the ES6 code result is not correct. I compile the code with io.js, it throw the erro message:

```javascript
TypeError: Identifier 'b' has already been declared
```

Why babel-node let  constant variable changed？

**Comment by loganfsmyth** [comment] 2015-08-17 03:47
This is a duplicate of https://github.com/babel/babel/issues/1879

The short answer is that this is expected. `babel-node` is a quick way to execute an ES6 script, but the REPL part of it is not fully featured.

**Closed by loganfsmyth** 2015-08-17 03:47 UTC
