### ISSUE TITLE
bound class property arrow function access constructor's arguments instead of their own

### ISSUE THREAD

**Issue by constb** [babel/babel#2347] opened 2015-09-09 15:13 UTC
if I create class property and assign in a bound function, in the generated code I can access particular arguments without problem, but if I try to access `arguments` it brings class constructor's `arguments` into the closure and they become `arguments` of the bound function.

this is what I'm trying to achieve

```
class Foo extends Component {

  componentDidMount() {
    $(document).on('click', this.onEvent);
  }

  onEvent = (event) => {
    console.log(event);
    console.log(arguments);
  };
}
```

in `onEvent` the `event` argument will be a jquery event like expected. but `arguments` will not be method arguments but constructor arguments instead.

this [REPL](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=class%20Foo%20%7B%0A%20%20%0A%20%20componentDidMount%28%29%20%7B%0A%20%20%20%20%24%28document%29.on%28'click'%2C%20this.onEvent%29%3B%0A%20%20%7D%0A%20%20%0A%20%20onEvent%20%3D%20%28event%29%20%3D%3E%20%7B%0A%20%20%20%20console.log%28event%29%3B%0A%20%20%20%20console.log%28arguments%29%3B%0A%20%20%7D%3B%0A%7D) shows what code gets generated.

now, I may not know ES6 well enough to understand why is this happening. but I couldn't find any mention of such a "feature", so this might be a bug.

**Comment by loganfsmyth** [comment] 2015-09-09 15:43
This seems like an edge-case of the current spec. Arrow functions in general get their `arguments` from their parent environment, just like `this` and `super`. With the current proposed behavior of class properties, the parent environment of properties is the class constructor.

    function fn(){
        return () => Array.from(arguments);
    }

    fn(1, 2, 3)()
    // [1,2,3]

If you want the list of arguments for an arrow function, you need to use a spread

    (...args) => {
        let [event] = args;
        // stuff
    }

**Comment by sebmck** [comment] 2015-09-09 17:30
The behaviour that you expect is definently incorrect as @loganfsmyth explains. Although I'm not sure if it should be the constructor or not, depends on how the specification defines it. cc @jeffmo

**Comment by jeffmo** [comment] 2015-09-09 22:50
The parent environment of a class property is supposed to be the class body itself -- not the constructor. So the following [weird] example illustrates the intended behavior of the proposal:

```
> var MyClass = (function() {
  var stuff = 'outer stuff!';
  return class {
    constructor() {
      var stuff = 'constructor stuff!';
    }
    myProp = () => {
      console.log(arguments);
      console.log(stuff);
    };
  }
})(42);
> new MyClass('asdf').myProp();
42
'outer stuff!'
```

See step 23.ii.a here:

https://gist.github.com/jeffmo/054df782c05639da2adb#14514-runtime-semantics-classdefinitionevaluation

**Comment by sebmck** [comment] 2015-09-09 22:51
Great, thanks for the clarification @jeffmo!

**Comment by constb** [comment] 2015-09-10 09:25
Thank you @loganfsmyth and @jeffmo for the detailed answer, I'll stick with spread args from now on. As for this issue, it's not very clear still, should I close it or should I change it's title somehow? Because from what @jeffmo says it looks like babel doesn't really get it right...

**Comment by sebmck** [comment] 2015-09-10 19:05
There's still a bug here, yeah. I asked @jeffmo for clarification on the semantics to verify what the intended behaviour is.

**Comment by loganfsmyth** [comment] 2015-09-10 19:06
So this means there is a divergence of the `arguments` environment and the environment `this` comes from? Interesting.

**Comment by jeffmo** [comment] 2015-09-10 20:17
@loganfsmyth: That is interesting, I hadn't thought of that. Is there any reason you can think of why those two *should* be coupled? Or just making an observation?

**Comment by loganfsmyth** [comment] 2015-09-10 20:57
Mostly for this my reaction was surprise, but I guess there isn't anything stopping them from being separated. In normal code they'd always be tied though since the `arguments` binding is initialized for all function declarations/expressions, and that also matches up with the initialization of `this` bindings.

For me it's the proposed behavior of `this` that ends up being the odd one out. I understand the desire, but it seems like it really complicates things to essentially be creating a new scoping concept for initializers.

**Comment by nicolo-ribaudo** [comment] 2018-04-15 14:33
This has been fixed by https://github.com/babel/babel/pull/7718. It correctly throws now.

**Closed by nicolo-ribaudo** 2018-04-15 14:33 UTC
Labels: i: bug
