### ISSUE TITLE
transform-object-rest-spread doesn't work properly with default parameters

### ISSUE THREAD

**Issue by jmheik** [babel/babel#5018] opened 2016-12-19 12:11 UTC
When trying to use object spread in function parameters with default parameter present, transform-object-rest-spread doesn't apply.

### Input Code

[Minimal test case in REPL](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=stage-3&experimental=false&loose=false&spec=false&code=const%20a%20%3D%20(%7B%20x%2C%20...rest%20%7D)%20%3D%3E%20%7B%7D%3B%0Aconst%20b%20%3D%20(%7B%20x%2C%20...rest%20%7D%20%3D%20%7B%7D)%20%3D%3E%20%7B%7D%3B%0A) . Transform doesn't apply after adding default parameter.
```js
const b = ({ x, ...rest } = {}) => {};
```

### Expected Behavior

Transform applies also when default parameter is present.

### Current Behavior

Transform doesn't apply when default parameter is present.

### Context

I was trying to use object-rest-spread in node 6 without babel plugins for natively supported ES6 features.

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  
| node             | 
| npm              | 
| Operating System |

**Comment by hzoo** [comment] 2016-12-19 14:24
Thanks for the report! Although it looks like a duplicate of https://github.com/babel/babel/issues/4851, can you search for duplicates next time?

Workaround atm is to include the previous needed plugins (parameters/destructuring)

**Closed by hzoo** 2016-12-19 14:24 UTC

**Comment by jmheik** [comment] 2016-12-19 16:11
Somehow I missed it, sorry for the noise.
