### ISSUE TITLE
Manually inserted export declarations don't work properly

### ISSUE THREAD

**Issue by RReverser** [babel/babel#1979] opened 2015-07-11 13:43 UTC
Say I have stupid test plugin that replaces program with analogue of:

```javascript
export var x;
export default function initialize() {
  x = 1;
}
```

Code of plugin:

```javascript
module.exports = function ({ Plugin, types: t }) {
  return new Plugin("sample", {
    visitor: {
      Program(node, parent, scope, file) {
        return t.program([
          t.exportNamedDeclaration(t.variableDeclaration('var', [t.variableDeclarator(t.identifier('x'))])),
          t.exportDefaultDeclaration(t.functionDeclaration(
            t.identifier('initialize'),
            [],
            t.blockStatement([t.expressionStatement(
              t.assignmentExpression('=', t.identifier('x'), t.literal(1))
            )])
          ))
        ]);
      }
    }
  });
};
```

In output (obviously no matter what input is in this case) I get:

```javascript
"use strict";

exports["default"] = initialize;
var x;
exports.x = x;

function initialize() {
  x = 1;
}

module.exports = exports["default"];
```

While rather expected is:

```javascript
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports["default"] = initialize;
var x;
exports.x = x;

function initialize() {
  exports.x = x = 1;
}
```

There are two problems in current generation:
  1. Manual `export var x` isn't found and `module.exports` is replaced with `default` only.
  2. Live bindings are not enforced.

This seems to be a bug (unless I'm missing something obvious).

**Comment by RReverser** [comment] 2015-07-13 18:06
@sebmck I'd be happy to fix this on my own, but not sure even where to look. Can you please provide any pointers?

**Comment by jmm** [comment] 2015-07-13 18:25
@RReverser I wonder if this is along the same lines as my issue, #1777, the root cause of which apparently is that module formatter initialization runs before plugins. See https://babeljs.slack.com/archives/plugins/p1434549369000220.

**Comment by RReverser** [comment] 2015-07-13 18:32
Hm, maybe, but not sure since I never touched module internals.

**Comment by RReverser** [comment] 2015-07-14 07:54
Okay, I digged in the internals, and could make my case work with an ugly hack:
```javascript
// replace Program:
this.replaceWith(...);

// those were same before replacement, but not anymore, so fix manually:
file.scope = this.scope;

// module formatter should be re-initialized so that it can find new imports/exports
file.moduleFormatter.constructor.call(file.moduleFormatter, file);
```

Still, this obviously needs to be fixed properly on Babel side as hack is really ugly and unreliable I guess.

**Comment by RReverser** [comment] 2015-07-14 08:03
Another option is to just perform

```javascript
file.addAst(t.file(...new program..., [], []));
```

So that everything is completely reinitialized in reliable way.

**Comment by sebmck** [comment] 2015-07-14 13:34
Yeah it's basically the same reason as #1777. It's tricky dealing with modules as you may want to insert the declarations in a variety of different positions and for performance the amount of passes needs to be limited. It can likely be resolved by moving around the module metadata collection and assignment replacement.

**Comment by RReverser** [comment] 2015-07-15 09:03
I see. What if we would have (1) complete reinitialization on replacement of `Program` node (like I did with `file.addAst`, but maybe something more elegant) + (2) few more complementary methods for managing imports/exports aside from `addImport` - `addExport`, `getImports: Path[]`, `getExports: Path[]`, etc.?

**Comment by jmm** [comment] 2015-07-15 13:05
FWIW I'd note that it doesn't sound like that would solve #1777.

**Comment by RReverser** [comment] 2015-07-15 14:24
@jmm Partially it would - but you will still need to manually call api method on import references.

**Comment by jmm** [comment] 2015-07-15 14:35
@RReverser Is that something you can illustrate? Do you mean an API method that will be added or that already exists?

**Comment by RReverser** [comment] 2015-07-15 14:42
@jmm For now, trick above (https://github.com/babel/babel/issues/1979#issuecomment-121156579) should work for your case, but in future API this part - https://github.com/babel/babel/blob/master/packages/babel/src/transformation/modules/lib/remaps.js#L23-L37 - should be exposed for manual wrapping.

**Comment by jmm** [comment] 2015-07-15 15:46
@RReverser 
> For now, trick above (#1979 (comment)) should work for your case

Oh, ok, thanks.

> but in future API this part...should be exposed for manual wrapping (or you can replicate it on your own for now).

Oh ok, I'll have to figure out how that method works sometime. I should note that for my case in #1777 to be fully resolved the way I hoped for it to work, the following would need to happen:

1. Insert the `import` via plugin.
2. Transform JSX using the `jsxPragma` option value, but reconcile the identifier in `jsxPragma` to match the renamed import.

**Comment by RReverser** [comment] 2015-07-15 20:04
@jmm Hmm, can't you just do `file.opts.jsxPragma = file.addImport(...).name`? Or maybe I misunderstood the issue.

**Comment by jmm** [comment] 2015-07-16 14:13
@RReverser 
> Hmm, can't you just do `file.opts.jsxPragma = file.addImport(...).name`? Or maybe I misunderstood the issue.

Good idea! That does seem to be working, although I haven't traced the logic to 100% understand how, because `file.addImport(...).name` is different than the identifier that ultimately comes out for the import. Somehow they are staying in sync though.

Ironically, that does nothing for the more basic case I illustrate in #1777, but if that's resolved I'm not 100% sure it would address this case with `jsxPragma`. So it's possible your suggestion will be the ultimate solution for this situation anyway. I have to figure out `addImport()` better in general though -- it's rather confusing.

BTW, the use case for that is this plugin: https://github.com/jmm/babel-plugin-jsx-pragmatic. Automatically insert an import for the module corresponding to `jsxPragma`.

Thanks!

**Comment by PSpSynedra** [comment] 2015-08-11 15:41
@RReverser, @sebmck Another quick and dirty hack is:

```js
file.moduleFormatter.hasNonDefaultExports = true;
```

**Comment by sebmck** [comment] 2015-09-28 01:57
This problem wont occur in 6.0 as modules now operate as separate plugins and have no special state internally.

**Closed by sebmck** 2015-09-28 01:57 UTC
Labels: bug, transformation

**Comment by jmm** [comment] 2015-10-06 01:42
@PSpSynedra Thanks for the tip! I'm using that to temporarily work around https://github.com/babel/babel/issues/2047 and ensure that my CJS compiled modules always have `exports.default`
