### ISSUE TITLE
arrow functions should not have prototypes

### ISSUE THREAD

**Issue by angus-c** [babel/babel#1410] opened 2015-05-01 17:58 UTC
```js
typeof (()=>{}).prototype; // "object" (should be "undefined)
```

Also arrow functions should not implement [[construct]] so should throw an exception with `new`. However I appreciate this is difficult to shim.

```js
let obj1 = {
  outerFn: (x) => {
    return new (() => {})();
  }
}
      
console.log(obj1.outerFn()); // {}

let obj2 = {
  outerFn: (x) => {
    return new (() => {this.a = x})();
  }
}
      
console.log(obj2.outerFn(4)); // cannot set 'a' of undefined
```

**Comment by monsanto** [comment] 2015-05-01 19:37
Dupe of https://github.com/babel/babel/issues/616, sorry

**Closed by monsanto** 2015-05-01 19:37 UTC
