### ISSUE TITLE
Error when using babel-runtime with typeof-react-element helper 

### ISSUE THREAD

**Issue by dtothefp** [babel/babel#2377] opened 2015-09-14 01:33 UTC
Initially reported here https://github.com/babel/babel/issues/2371#issuecomment-139919324

Once updating to `5.8.24` in order to use React 14 production optimizations
```js
optional: [
  'runtime',
  'optimisation.react.inlineElements',
  'optimisation.react.constantElements'
]
```
I'm getting the error
```
babel-runtime/helpers/typeof-react-element.js Line 5: Unexpected string
```
 I think related to es6 compilation of the `typeof-react-element` helper.
```js
"use strict";

var _Symbol = require("babel-runtime/core-js/symbol")["default"];

exports["default"] = typeof _Symbol === "function" && _Symbol."for" && _Symbol."for"("react.element") || 60103;
exports.__esModule = true;
```

@sebmck @spicyj Looks like the `for` property from the `Symbol` object is being converted to a string from the following source:

https://github.com/babel/babel/blob/ade747eb9c9d4a0224d683140784e9da9b8beef5/packages/babel/src/transformation/templates/helper-typeof-react-element.js

Assuming this isn't intentional?

Not sure why this is happening because in the Babel repl code seems to compile correctly:

<img width="1433" alt="screen shot 2015-09-13 at 3 32 48 pm" src="https://cloud.githubusercontent.com/assets/4656726/9838491/cb70a6dc-5a2c-11e5-95f7-7a0dc190d371.png">

If I change code in the `runtime` helper to that of above, works correctly

```js
exports["default"] = typeof _Symbol === "function" && _Symbol["for"] && _Symbol["for"]("react.element") || 60103;
```

**Comment by taion** [comment] 2015-09-14 02:09
I've been seeing the same thing, and it's been making me not use the React optimizations.

**Comment by dtothefp** [comment] 2015-09-14 02:50
@taion seems to work fine if you don't use in conjunction with the runtime

**Comment by SpainTrain** [comment] 2015-09-18 21:06
+1, had to disable `runtime`

(I hate +1 spamming, but it's the current best option :-/ - https://www.change.org/p/github-inc-add-voting-functionality-for-github-issues)

**Comment by sebmck** [comment] 2015-09-19 01:13
Fixed in 5.8.26.

**Closed by sebmck** 2015-09-19 01:13 UTC

**Comment by dtothefp** [comment] 2015-09-19 17:47
@sebmck when can we expect `5.8.26`?

**Comment by sebmck** [comment] 2015-09-19 17:47
@dtothefp meant 5.8.25

**Comment by dtothefp** [comment] 2015-09-20 13:34
Hey @sebmck looks like what's on NPM currently is still 5.8.24 unless I'm mistaken

**Comment by sebmck** [comment] 2015-09-20 15:31
@dtothefp Nope. [5.8.25 is the latest.](https://www.npmjs.com/package/babel-core).

**Comment by BinaryMuse** [comment] 2015-09-20 21:14
I'm still seeing this issue with the latest `babel*` packages from npm:

```
$ npm ls | grep babel
├─┬ babel@5.8.23
│ ├─┬ babel-core@5.8.25
│ │ ├── babel-plugin-constant-folding@1.0.1
│ │ ├── babel-plugin-dead-code-elimination@1.0.2
│ │ ├── babel-plugin-eval@1.0.1
│ │ ├── babel-plugin-inline-environment-variables@1.0.1
│ │ ├── babel-plugin-jscript@1.0.4
│ │ ├── babel-plugin-member-expression-literals@1.0.1
│ │ ├── babel-plugin-property-literals@1.0.1
│ │ ├── babel-plugin-proto-to-assign@1.0.4
│ │ ├── babel-plugin-react-constant-elements@1.0.3
│ │ ├── babel-plugin-react-display-name@1.0.3
│ │ ├── babel-plugin-remove-console@1.0.1
│ │ ├── babel-plugin-remove-debugger@1.0.1
│ │ ├── babel-plugin-runtime@1.0.7
│ │ ├─┬ babel-plugin-undeclared-variables-check@1.0.2
│ │ ├── babel-plugin-undefined-to-void@1.1.6
├─┬ babel-loader@5.3.2
├─┬ babel-runtime@5.8.24

$ npm outdated
Package     Current      Wanted  Latest  Location
react    0.14.0-rc1  0.14.0-rc1  0.13.3  chrome-fast-tab-switcher
```

**Comment by sebmck** [comment] 2015-09-20 22:25
That's the CLI. Why would there be a new version of the `babel` package used if nothing changed in it?

**Comment by BinaryMuse** [comment] 2015-09-20 22:34
@sebmck I wasn't just referring to the `babel` package, but the other `babel-*` packages as well, which also seem fully up to date. Perhaps I'm missing something, but it appears to be using `babel-core@5.8.25`, which I thought fixed the issue based on your comment above. Even if I install `babel-core` and `babel-runtime` as top-level dependencies and end up with this:

```
$ npm ls | grep babel
├─┬ babel@5.8.23
├─┬ babel-core@5.8.25
│ ├── babel-plugin-constant-folding@1.0.1
│ ├── babel-plugin-dead-code-elimination@1.0.2
│ ├── babel-plugin-eval@1.0.1
│ ├── babel-plugin-inline-environment-variables@1.0.1
│ ├── babel-plugin-jscript@1.0.4
│ ├── babel-plugin-member-expression-literals@1.0.1
│ ├── babel-plugin-property-literals@1.0.1
│ ├── babel-plugin-proto-to-assign@1.0.4
│ ├── babel-plugin-react-constant-elements@1.0.3
│ ├── babel-plugin-react-display-name@1.0.3
│ ├── babel-plugin-remove-console@1.0.1
│ ├── babel-plugin-remove-debugger@1.0.1
│ ├── babel-plugin-runtime@1.0.7
│ ├─┬ babel-plugin-undeclared-variables-check@1.0.2
│ ├── babel-plugin-undefined-to-void@1.1.6
├─┬ babel-loader@5.3.2
├── babel-runtime@5.8.24
```

I get the same error

```
ERROR in ./~/babel-runtime/helpers/typeof-react-element.js
Module parse failed: /Users/btilley/src/chrome-fast-tab-switcher/node_modules/babel-runtime/helpers/typeof-react-element.js Line 5: Unexpected string
You may need an appropriate loader to handle this file type.
| var _Symbol = require("babel-runtime/core-js/symbol")["default"];
|
| exports["default"] = typeof _Symbol === "function" && _Symbol."for" && _Symbol."for"("react.element") || 60103;
| exports.__esModule = true;
 @ ./src/background.js 3:26-79
```

unless I remove `"runtime"` from the config.

**Comment by SpainTrain** [comment] 2015-09-20 23:16
I can corroborate that I am using `babel-core@5.8.25` and still experience this issue.  Please reopen =-D

**Comment by SpainTrain** [comment] 2015-09-20 23:22
```
$ npm ls | grep babel
├─┬ babel-core@5.8.25
│ ├── babel-plugin-constant-folding@1.0.1
│ ├── babel-plugin-dead-code-elimination@1.0.2
│ ├── babel-plugin-eval@1.0.1
│ ├── babel-plugin-inline-environment-variables@1.0.1
│ ├── babel-plugin-jscript@1.0.4
│ ├── babel-plugin-member-expression-literals@1.0.1
│ ├── babel-plugin-property-literals@1.0.1
│ ├── babel-plugin-proto-to-assign@1.0.4
│ ├── babel-plugin-react-constant-elements@1.0.3
│ ├── babel-plugin-react-display-name@1.0.3
│ ├── babel-plugin-remove-console@1.0.1
│ ├── babel-plugin-remove-debugger@1.0.1
│ ├── babel-plugin-runtime@1.0.7
│ ├─┬ babel-plugin-undeclared-variables-check@1.0.2
│ ├── babel-plugin-undefined-to-void@1.1.6
├─┬ babel-eslint@4.1.3
├─┬ babel-loader@5.3.2
├── babel-runtime@5.8.24
│   ├── babel-jscs@2.0.4
```

```
ERROR in ./~/babel-runtime/helpers/typeof-react-element.js
Module parse failed: /home/spainhower/repos/homebuddy-webapp/node_modules/babel-runtime/helpers/typeof-react-element.js Line 5: Unexpected string
You may need an appropriate loader to handle this file type.
| var _Symbol = require("babel-runtime/core-js/symbol")["default"];
| 
| exports["default"] = typeof _Symbol === "function" && _Symbol."for" && _Symbol."for"("react.element") || 60103;
| exports.__esModule = true;
 @ ./app/client-main.js 5:26-79
```

**Comment by novacrazy** [comment] 2015-09-21 19:55
I am also still experiencing this issue.

```
$ npm ls | grep babel
+-- babel-core@5.8.25
| +-- babel-plugin-constant-folding@1.0.1
| +-- babel-plugin-dead-code-elimination@1.0.2
| +-- babel-plugin-eval@1.0.1
| +-- babel-plugin-inline-environment-variables@1.0.1
| +-- babel-plugin-jscript@1.0.4
| +-- babel-plugin-member-expression-literals@1.0.1
| +-- babel-plugin-property-literals@1.0.1
| +-- babel-plugin-proto-to-assign@1.0.4
| +-- babel-plugin-react-constant-elements@1.0.3
| +-- babel-plugin-react-display-name@1.0.3
| +-- babel-plugin-remove-console@1.0.1
| +-- babel-plugin-remove-debugger@1.0.1
| +-- babel-plugin-runtime@1.0.7
| +-- babel-plugin-undeclared-variables-check@1.0.2
| +-- babel-plugin-undefined-to-void@1.1.6
+-- babel-runtime@5.8.24
+-- grunt-babel@5.0.3
```

**Comment by spicyj** [comment] 2015-09-22 21:51
Seems like this line in babel-plugin-runtime is to blame:

```
return t.memberExpression(file.addImport(RUNTIME_MODULE_NAME + "/core-js/" + modulePath, "" + obj.name, "absoluteDefault"), prop);
```

When changing `Symbol['for']` to `_Symbol['for']`, it doesn't copy over the computed-ness of the property. Earlier up (in `enter`) it looks like maybe the intention was to skip over computed properties entirely? I'm not sure why that would be though.

https://github.com/babel-plugins/babel-plugin-runtime gives me a 404 – is the code hosted somewhere else?

**Comment by forivall** [comment] 2015-09-23 05:12
I found a fork here: https://github.com/jkroso/babel-plugin-runtime but I'm guessing it was deleted or made private accidentally; duck duck go still returns https://github.com/babel-plugins/babel-plugin-runtime in the instant answer box.

**Comment by sebmck** [comment] 2015-09-23 16:10
Try `babel-runtime` 5.8.25.

**Comment by SpainTrain** [comment] 2015-09-23 16:50
> Try babel-runtime 5.8.25.

Worked for me. Thx :heart:

**Comment by just-boris** [comment] 2015-10-13 22:21
+1 to @spicyj 
@sebmck issue still here:
```
 $npm ls | grep babel
└─┬ babel@5.8.23
  ├─┬ babel-core@5.8.25
```
Without optional runtime works fine.
```
$ ./node_modules/.bin/babel test.js
'use strict';

Symbol['for'];
```
But with it breaks
```
$ ./node_modules/.bin/babel test.js --optional=runtime
'use strict';

var _Symbol = require('babel-runtime/core-js/symbol')['default'];

_Symbol.'for';
```

**Comment by dtothefp** [comment] 2015-10-14 01:47
@just-boris read the thread and use `5.8.25`

**Comment by just-boris** [comment] 2015-10-14 09:37
@dtothefp See dependency tree in my comment. I use `babel-core@5.8.25`.

**Comment by SpainTrain** [comment] 2015-10-14 14:39
See dep tree in my comment :smile_cat: , `babel-core@5.8.25` is not sufficient.  Try installing `babel-runtime@5.8.25.` in your project and see if that gets it.

**Comment by just-boris** [comment] 2015-10-14 14:51
Okay:

```
$ npm ls --depth 0 | grep babel
├─┬ babel@5.8.23
├─┬ babel-core@5.8.25
│ ├── babel-plugin-constant-folding@1.0.1
│ ├── babel-plugin-dead-code-elimination@1.0.2
│ ├── babel-plugin-eval@1.0.1
│ ├── babel-plugin-inline-environment-variables@1.0.1
│ ├── babel-plugin-jscript@1.0.4
│ ├── babel-plugin-member-expression-literals@1.0.1
│ ├── babel-plugin-property-literals@1.0.1
│ ├── babel-plugin-proto-to-assign@1.0.4
│ ├── babel-plugin-react-constant-elements@1.0.3
│ ├── babel-plugin-react-display-name@1.0.3
│ ├── babel-plugin-remove-console@1.0.1
│ ├── babel-plugin-remove-debugger@1.0.1
│ ├── babel-plugin-runtime@1.0.7
│ ├─┬ babel-plugin-undeclared-variables-check@1.0.2
│ ├── babel-plugin-undefined-to-void@1.1.6
├── babel-runtime@5.8.25
```
Still no effect
```js
$ ./node_modules/.bin/babel test.js --optional=runtime
'use strict';
var _Symbol = require('babel-runtime/core-js/symbol')['default'];
_Symbol.'for';
```
This is expected, because runtime is not actually executed during transpillation. This is a runtime dependency, so it will be imported after run.

**Comment by SpainTrain** [comment] 2015-10-14 14:54
Do you still receive an error when executing the code?

**Comment by just-boris** [comment] 2015-10-14 15:42
@SpainTrain yes, because browser can't read this code: `_Symbol.'for'`. It has syntax error.

**Comment by SpainTrain** [comment] 2015-10-14 17:20
Hmm, when I run that same command on source files locally, I don't seem to get the same error, and in my compiled output, I have 

```js
exports["default"] = typeof _Symbol === "function" && _Symbol["for"] && _Symbol["for"]("react.element") || 60103;
```

Could you share the contents of `test.js` in a gist?  I'd like to try it locally since we have the same deps installed but different behavior.

```
$ npm ls | grep babel
├─┬ babel@5.8.23
├─┬ babel-core@5.8.25
│ ├── babel-plugin-constant-folding@1.0.1
│ ├── babel-plugin-dead-code-elimination@1.0.2
│ ├── babel-plugin-eval@1.0.1
│ ├── babel-plugin-inline-environment-variables@1.0.1
│ ├── babel-plugin-jscript@1.0.4
│ ├── babel-plugin-member-expression-literals@1.0.1
│ ├── babel-plugin-property-literals@1.0.1
│ ├── babel-plugin-proto-to-assign@1.0.4
│ ├── babel-plugin-react-constant-elements@1.0.3
│ ├── babel-plugin-react-display-name@1.0.3
│ ├── babel-plugin-remove-console@1.0.1
│ ├── babel-plugin-remove-debugger@1.0.1
│ ├── babel-plugin-runtime@1.0.7
│ ├─┬ babel-plugin-undeclared-variables-check@1.0.2
│ ├── babel-plugin-undefined-to-void@1.1.6
├─┬ babel-eslint@4.1.3
├─┬ babel-loader@5.3.2
├── babel-runtime@5.8.25
│   ├── babel-jscs@2.0.4
```

**Comment by just-boris** [comment] 2015-10-14 17:29
@SpainTrain content of the `test.js` is simple
```js
Symbol['for']
```
This is the minimal expression to reproduce the issue.
Also, do not forget about set `optional=runtime`, it is necessary to get an error

**Comment by SpainTrain** [comment] 2015-10-14 17:46
Ok, this makes sense now.  Using `Symbol.for` to reference that method produces 

```js
var _Symbol$for = require("babel-runtime/core-js/symbol/for")["default"];
_Symbol$for;
```

which is correct, but using `Symbol["for"]` produces

```js
var _Symbol = require("babel-runtime/core-js/symbol")["default"];
_Symbol.'for';
```

Seems like a bug, but do you have any way to use the `Symbol.for` form as a workaround?

**Comment by sebmck** [comment] 2015-10-14 17:47
You're pulling in an old version. The version of `babel-core` or `babel` makes no difference. The package `babel-plugin-runtime` is the one that has been updated and fixed.
