### ISSUE TITLE
Babel will not call Visitor method Decorator (babel-plugin)

### ISSUE THREAD

**Issue by SerkanSipahi** [babel/babel#4968] opened 2016-12-08 18:11 UTC
Babel will not call Visitor function "Decorator" (babel-plugin). Is this a bug or not possible with babel?
 
### Input Code

```js
export default function () {  
  return {
    visitor: {
      Decorator(path){
        console.log('Decorator') // no log with babel
      },
      ClassDeclaration(path){
      	console.log('ClassDeclaration') // log
      },
      ClassMethod(path){
      	console.log('ClassMethod') // log
      }
    }
  };
}
```
### Expected Behavior
- It should call visitor function "Decorator" in Babel

### Current Behavior
- No visitor function call "Decorator" in Babel

### Context
- tests green, working well in my test env: https://github.com/SerkanSipahi/babel-plugin-app-decorators-view-precompile/blob/v1.0.0-alpha.3/test/index.js
- work also well with astexplorer, see example: https://astexplorer.net/#/YD25zHTNWd/6

### Environment

| software         | version
| ---------------- | -------
| Babel            |  6.18.0
| node             | 5.1.0
| npm              | 3.3.12
| Operating System | OS X El Captian

**Comment by rattrayalex** [comment] 2017-02-01 02:28
I am also experiencing this with the `AwaitExpression` node. 

The following code works:

```js
Expression(path) {
  if (!path.isAwaitExpression()) return;
  console.log('in AwaitExpression');
}
```
while this does not work:
```js
AwaitExpression(path) {
  console.log('in AwaitExpression');
}
```

other node types which are non-experimental work just fine, so I assume this has to do with the fact that `AwaitExpression` and `Decorator` are defined in `babel-types/src/definitions/experimental.js`. 

To be clear, `AwaitExpression`s are parsing just fine, and no error to the effect of `You gave a visitor of type AwaitExpression but it is not a valid node type` is being thrown.

**Comment by loganfsmyth** [comment] 2017-02-01 02:30
Do you have the `babel-plugin-transform-async-to-generator` enabled as well? Generally issues like this happen because the AwaitExpression has already been converted by another plugin before your plugin has time to run.

**Comment by rattrayalex** [comment] 2017-02-01 02:31
I do not; `await` is printed in the output.

**Comment by loganfsmyth** [comment] 2017-02-01 02:47
Would you be able to put together a repo that reproduces the issue for you? When I test it out, it seems to work as I'd expect.

**Comment by rattrayalex** [comment] 2017-02-01 02:54
My repo is at GitHub.com/lightscript/babel-plugin-lightscript but
unfortunately until https://github.com/babel/babel/pull/4886 is merged an
onerous number of `npm link` calls are required, so I wouldn't recommend
trying it there.

If you'd like, I can make a branch with the customer nodes removed and you
can try that?

**Comment by loganfsmyth** [comment] 2017-02-01 02:57
Yeah ideally something that is easily `npm install`able would be perfect.

**Comment by rattrayalex** [comment] 2017-02-01 03:02
Cool, I'm on my phone at the moment but hope to get something up soon -
thanks!

**Comment by rattrayalex** [comment] 2017-02-01 03:40
Hmm, when I remove my custom node types, `AwaitExpression` works. I'll try to dig into that more. May have to do with aliases, since I've defined a custom node type that has `AwaitExpression` as an alias.

**Comment by rattrayalex** [comment] 2017-02-01 03:41
@SerkanSipahi did you define any custom node types?

**Comment by SerkanSipahi** [comment] 2017-02-01 09:57
@rattrayalex what do you mean with custom node types?

this is/was im trying to do:
```js
export default function () {  
  return {
    visitor: {
      Decorator(path){
        console.log('Decorator') // no log with babel
      },
      ClassDeclaration(path){
      	console.log('ClassDeclaration') // log
      },
      ClassMethod(path){
      	console.log('ClassMethod') // log
      }
    }
  };
}
```

**Comment by rattrayalex** [comment] 2017-02-01 16:18
Confirming that my custom node type's definition was the cause. Apologies. 
Not sure if this helps in figuring out what was going on with `Decorator`.

(for the curious, the problem was that I was instantiating`babel-types.FLIPPED_ALIAS_KEYS['AwaitExpression']` as `[]` instead of as `['AwaitExpression']`)

I'll open an issue to discuss the problems laid out in #4886

**Comment by SerkanSipahi** [comment] 2017-02-09 21:19
@loganfsmyth see: https://astexplorer.net/#/YD25zHTNWd/6 
1.) It works in babylon
2.) In usage as plugin with babel it will never call visitor.Decorator

**Comment by loganfsmyth** [comment] 2017-02-10 16:43
On my machine:
```
$ cat .babelrc
{
  "plugins": [
    'syntax-decorators',
    './plugin',
  ],
}

$ cat plugin.js 
module.exports = {
  visitor: {
    ClassDeclaration(path){
      console.log('ClassDeclaration') // log
    },
    ClassMethod(path){
      console.log('ClassMethod') // log
    },
    Decorator(path){
      console.log('Decorator') // no log in babel
    }
  },
}

$ cat tmp.js 
@foo()
class Bar {
 x(){}
 y(){}
}

$ $(npm bin)/babel tmp.js
ClassDeclaration
ClassMethod
ClassMethod
Decorator

@foo()
class Bar {
  x() {}
  y() {}
}

```

**Comment by SerkanSipahi** [comment] 2017-02-11 13:36
@loganfsmyth hmmm, strange ! which version (babel) do you use? its over 2 month ago that i posted this issue. In the meantime i solved it differently. Over ClassDeclaration im looking for decorators.

**Comment by loganfsmyth** [comment] 2017-02-11 19:33
it could potentially have been an issue if you were also using `transform-decorators-legacy`? The only reason I'd expect something like that to not run is if the node was removed and transformed by something else first.

**Comment by SerkanSipahi** [comment] 2017-02-11 20:08
>it could potentially have been an issue if you were also using transform-decorators-legacy
exactly, It occurred while using `transform-decorators-legacy`. What to do now?

**Comment by loganfsmyth** [comment] 2017-02-11 20:21
You likely needed to swap the ordering of the two plugins in your `.babelrc`.

**Comment by SerkanSipahi** [comment] 2017-02-11 20:27
this is the ordering (in preset). Is that wrong?
```js
export default {
    plugins: [
        myPlugin
        transformDecoratorsLegacy,
        transformClassProperties
    ]
};
```

**Comment by loganfsmyth** [comment] 2017-02-11 20:36
Oh you know what, I was wrong, I don't think either ordering will work. Your approach of traversing for the class first then processing the decorators is indeed what I would recommend.

For what it's worth, I totally hear you that this is frustrating, in the future we're hoping to change up the API to make things like this less confusing.

**Comment by SerkanSipahi** [comment] 2017-02-11 20:40
@loganfsmyth its ok. You guys are so awesome. Thanks for all (babel, babylon, etc) :)

**Comment by SerkanSipahi** [comment] 2017-02-11 20:48
@loganfsmyth i think you can close this issue

**Closed** 2017-02-11 21:11 UTC
