### ISSUE TITLE
babel-runtime: use graceful-fs?

### ISSUE THREAD

**Issue by contra** [babel/babel#4582] opened 2016-09-27 21:21 UTC
### Current Behavior

babel-register throws:

```
Error: EMFILE: too many open files, open '/Users/contra/.babel.json'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.writeFileSync (fs.js:1224:33)
    at process.save (/Users/contra/Projects/staeco/node_modules/babel-register/lib/cache.js:49:16)
    at emitOne (events.js:95:20)
    at process.emit (events.js:182:7)
    at processEmit [as emit] (/Users/contra/Projects/staeco/node_modules/signal-exit/index.js:140:35)
    at process.exit (node.js:715:17)
    at /Users/contra/Projects/staeco/bin/seed/cli.js:46:20
    at /Users/contra/Projects/staeco/node_modules/async/dist/async.js:3679:13
    at /Users/contra/Projects/staeco/node_modules/async/dist/async.js:486:20
    at iterateeCallback (/Users/contra/Projects/staeco/node_modules/async/dist/async.js:865:21)
    at /Users/contra/Projects/staeco/node_modules/async/dist/async.js:847:20
    at /Users/contra/Projects/staeco/node_modules/async/dist/async.js:3676:17
    at /Users/contra/Projects/staeco/node_modules/async/dist/async.js:339:31
    at /Users/contra/Projects/staeco/node_modules/async/dist/async.js:952:25
```
### Possible Solution

Use graceful-fs to avoid EMFILE errors. Easy as replace `import fs from "fs"` with `import fs from "graceful-fs"`
### Context

I'm reading from 33K files on a node server that uses babel-register, which is totally fine because graceful-fs makes this no problem. babel-register, however, blows up while trying to write a cache file because it does not handle EMFILE from the OS.
### Your Environment

| software | version |
| --- | --- |
| babel-register | 6.14.0 |
| node | 5.7.1 |
| npm | 3.x |
| Operating System | OSX |

**Comment by hzoo** [comment] 2016-10-04 19:32
Cool, haven't used it before so many other's have thoughts

**Comment by hzoo** [comment] 2017-03-17 20:11
going to close as a dupe of https://github.com/babel/babel/issues/4582

**Closed by hzoo** 2017-03-17 20:11 UTC
Labels: enhancement, pkg: register
