### ISSUE TITLE
[Bug]: Parameter properties don't get transformed correctly / are broken

### ISSUE THREAD

**Issue by danieltroger** [babel/babel#13971] opened 2021-11-16 22:48 UTC
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```typescript
const API_VERSION = 4;

class Bruh {
  public a_method(): void {
    console.log(this._version);
  }
  public constructor(
    public options: string,
    private readonly _version: number = API_VERSION
  ) {
    console.log(this.options);
  }
}
var instance = new Bruh("👀");
instance.a_method();
```

### Configuration file name

babel.config.js

### Configuration

```js
module.exports = {
  presets: ["@babel/preset-typescript", "@parcel/babel-preset-env"]
};
```

## 🤔 Expected Behavior

`👀` and then `4` is logged to the console.

## 😯 Current Behavior

`undefined` and then `undefined` is logged to the console.

### Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.0.0-nightly.912+145bfb82
| Node             |v17.0.1
| npm/Yarn         |3.1.0
| Operating System |macOS 10.15.7 (19H1419)
| @babel/core | 7.16.0

### Possible solution

Make so that it works correctly.

### Additional context

https://github.com/parcel-bundler/parcel/issues/7313

https://www.typescriptlang.org/docs/handbook/2/classes.html#parameter-properties

**Comment by danieltroger** [comment] 2021-11-16 22:52
Wait is this a duplicate of https://github.com/babel/babel/issues/12066?

**Comment by danieltroger** [comment] 2021-11-16 22:55
Bruh fml forreal? How am I supposed to find out that my code breaks because I have some stuff in the wrong order in a config file?

**Comment by JLHwung** [comment] 2021-11-18 18:25
Closing this as a duplicate of #12066

**Closed by JLHwung** 2021-11-18 18:25 UTC
Labels: i: needs triage
