### ISSUE TITLE
[Bug]: transform error with @babel/proposal-class-properties@7.18.6

### ISSUE THREAD

**Issue by kagurazaka-0** [babel/babel#15341] opened 2023-01-12 00:11 UTC
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```ts
type Json = Record<string, unknown>

class C {
    constructor(public json: Json) {
    }

    hogeFoge = this.json.hoge_hoge;
}
```

### Configuration

```json
{
  "cacheDirectory": "/PATH/TO/node_modules/.cache/storybook/babel",
  "sourceType": "unambiguous",
  "presets": [
    [
      "/PATH/TO/node_modules/@babel/preset-env/lib/index.js",
      { "shippedProposals": true, "loose": true }
    ],
    "/PATH/TO/node_modules/@babel/preset-typescript/lib/index.js",
    ["/PATH/TO/node_modules/@babel/preset-react/lib/index.js", { "runtime": "automatic" }],
    "/PATH/TO/node_modules/@babel/preset-flow/lib/index.js"
  ],
  "plugins": [],
  "overrides": [
    {
      "test": {},
      "plugins": ["/PATH/TO/node_modules/babel-plugin-named-exports-order/index.js"]
    },
    {
      "test": {},
      "plugins": [
        [
          "/PATH/TO/node_modules/babel-plugin-react-docgen/lib/index.js",
          { "DOC_GEN_COLLECTION_NAME": "STORYBOOK_REACT_CLASSES" }
        ]
      ]
    }
  ]
}

```

This is output of  babel options in `.storybook/main.js`.

<details><summary>.storybook/main.js</summary>

```js
const path = require('path');

/** @type {import("@storybook/core-common").StorybookConfig} */
module.exports = {
  // ...
  babel: (options) => {
    options.plugins = [];
    console.log(JSON.stringify(options)) // <- this json
    return options;
  },
};

```
</details>

### Current and expected behavior

Babel currently output parameter property after field.

[Babel Playground](https://babeljs.io/repl/#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=C4TwDgpgBAUgzgewHZQLxQEoQMYIE4AmAPHMHgJZIDmANFAK5IDWSCA7kgHwBQ32ANgEM4cKAGEoAb25RZUXElJ562YPgAUYegCN-5bFABWiJAC5YJgJRSZcgL685UABYIqEAGJvo6YM_JwAHTGyIGu7gD64RAA3Nx2QA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Ctypescript&prettier=false&targets=&version=7.20.12&externalPlugins=&assumptions=%7B%7D)

```js
// ...

class C {
  constructor(json) {
    _defineProperty(this, "hogeFoge", this.json.hoge_hoge);
    this.json = json;
  }
}
```

Like output code of [TypeScript Playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAUgzgewHZQLxQEoQMYIE4AmAPHMHgJZIDmANFAK5IDWSCA7kgHwBQ32ANgEM4cKAGEoAb25RZUXElJ562YPgAUYegCN+5bFABWiJAC5YJgJRSZcgL685UABYIqEAGJvo6YM-JwAHTGyIGu7gD64RAA3NwOQA), I want field after parameter property.

```js
class C {
    constructor(json) {
        this.json = json;
        this.hogeFoge = this.json.hoge_hoge;
    }
}
```

### Environment

  System:
    OS: macOS 13.1
  Binaries:
    Node: 16.13.0 - ~/.nodenv/versions/16.13.0/bin/node
    Yarn: 1.22.19 - ~/.node_modules/bin/yarn
    npm: 8.1.0 - ~/.nodenv/versions/16.13.0/bin/npm
  npmPackages:
    @babel/cli: ^7.19.3 => 7.19.3 
    @babel/core: ^7.20.5 => 7.20.5 
    babel-loader: ^8.3.0 => 8.3.0 
    eslint: ^8.28.0 => 8.28.0 

### Additional context

[TypeScript Playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAUgzgewHZQLxQEoQMYIE4AmAPHMHgJZIDmANFAK5IDWSCA7kgHwBQ32ANgEM4cKAGEoAb25RZUXElJ562YPgAUYegCN+5bFABWiJAC5YJgJRSZcgL685UABYIqEAGJvo6YM-JwAHTGyIGu7gD64RAA3NwOQA)

**Comment by JLHwung** [comment] 2023-01-12 03:04
Duplicate of https://github.com/babel/babel/issues/13779

**Closed by JLHwung** 2023-01-12 03:04 UTC
Labels: i: needs triage
