### ISSUE TITLE
Object rest spread not working as would expect in object destructuring when keys are numbers

### ISSUE THREAD

**Issue by jEnbuska** [babel/babel#5470] opened 2017-03-15 15:20 UTC
I noticed this strange behavior just now. Is this something that has been thought of?
`const { a, ...otherNumbers } = { a: 1, b: 2, c: 3 };`
`console.log(a); // 1`
`console.log(otherNumbers);  {b: 2, c: 3}` 

So as expected variable 'a' gets to be its own variable with value 1, and 'a:1' is excluded from 'otherNumbers'

`excludeKey = 1;`
`const { [excludeKey]: one, ...otherLetters } = { 1: 'a', 2: 'b', 3: 'b' };`
`console.log(one); //'a'`
`console.log(otherLetters);//{ 1: 'a', 2: 'b', 3: 'b' }`

when the key was a number the variable 'one' gets to be its own variable, but '1:"a"' is not excluded from 'otherLetters' 

to get key value pair '1:"a"' to be excluded from 'otherLetters' 'excludeKey' must be cast into string first like so:

`const { [excludeKey + ""]: one, ...otherLetters } = { 1: 'a', 2: 'b', 3: 'b' };`

I'm using presets latest & state-0, if that's of any help.

**Comment by yavorsky** [comment] 2017-03-15 15:51
@jEnbuska Hi! Thanks for the report!

Seems like the problem covered in `objectWithoutProperties` helper's arguments.
It gets object and array of arguments to discard.
Then it calls `indexOf` to discard passed properties.
It compares argument `1` which actually a number with the key from target like `1 === "1"` and gets `false`.
So we need to pass an array of strings to prevent this.
Going to fix it.

**Comment by hzoo** [comment] 2017-03-15 16:16
BTW @yavorsky we have a few issues/prs related to this

**Comment by gsathya** [comment] 2017-03-15 16:17
Related: https://github.com/babel/babel/issues/4196

**Comment by yavorsky** [comment] 2017-03-15 16:17
@hzoo @existentialism pointed me to https://github.com/babel/babel/pull/3675.

**Comment by hzoo** [comment] 2017-03-16 03:38
Yeah this looks like a dupe of #4196?

**Closed by hzoo** 2017-03-16 03:38 UTC
Labels: bug
