### ISSUE TITLE
Initialized fat arrow functions are not being bound to their parent class

### ISSUE THREAD

**Issue by Jon-Biz** [babel/babel#1964] opened 2015-07-09 23:20 UTC
As per this blog post:
http://babeljs.io/blog/2015/06/07/react-on-es6-plus/

I'm trying to create a locally bound function by defining a fat arrow function using a property initializer. However, it appears to remaining unbound: `this` is `window`.

```
export default class ZipCodeConverter extends Component {
  changeZip = (event) => {
     // this is bound to window. It should be bound to the parent class.
  }
}
```

**Comment by sebmck** [comment] 2015-07-09 23:22
Can you please put together a reproducible example in the [REPL](http://babeljs.io/repl)?

**Comment by Jon-Biz** [comment] 2015-07-10 00:34
Correction: the loss of scope only appears to be happening when using Reactjs and passing the initialized function into a subcomponent. I will see what can build in the REPL to demonstrate this.

Thanks!

**Comment by sebmck** [comment] 2015-07-11 14:15
Closing due to lack of reproducible example. If you manage to reproduce this reliably then please comment with a code example and I'll reopen.

**Closed by sebmck** 2015-07-11 14:15 UTC
