### ISSUE TITLE
babel-plugin-transform-flow-strip-types does not support `import { type MyType } from '...'`

### ISSUE THREAD

**Issue by jomel** [babel/babel#8905] opened 2018-10-19 15:11 UTC
## Bug Report

**Current Behavior**
when using babel with plugin-transform-flow-strip-types type imports like `import { type MyType } from '...'` are not stripped out. Instead they are transformed to `require('math');`

**Input Code**
https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=true&code_lz=JYWwDg9gTgLgBAbzjAnmApnAsgQxgCzgF84AzKCEOAchD32oG4g&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=react%2Cenv&prettier=false&targets=Node-8.9&version=6.26.0&envVersion=1.6.2

**Expected behavior/code**
strip out type declaration

**Additional context/**
Why don't I just use the usual `import type { MyType } from '...'`  you ask...
My form is accepted by flow & intelliSence in VS Code, giving tooltip info on the types, whereas the usual form is accepted, but does not show any type information...

`import { type ` is accepted fine by flow...

**Comment by loganfsmyth** [comment] 2018-10-19 15:46
This is expected behavior because the two import forms do different things. This is a duplicate of https://github.com/babel/babel/issues/6300#issuecomment-331787868.

**Closed by loganfsmyth** 2018-10-19 15:46 UTC

**Comment by jomel** [comment] 2018-10-22 10:02
@loganfsmyth thanks so much for pointing me in the right direction. The explanation there makes perfect sense. 
In my case the types are imported using a relative path to a file that is outside of the compiled folder. Don't suppose you know any other babel plugin I could run in addition to my current babel setup, to remove those spurious `require('../../../types/myType')` imports?

**Comment by jomel** [comment] 2018-10-22 10:55
thanks @loganfsmyth - makes sense.

If anyone else lands here...
I used [babel-plugin-strip-typehint-imports](https://www.npmjs.com/package/babel-plugin-strip-typehint-imports) to strip those imports.

**Comment by loganfsmyth** [comment] 2018-10-23 03:16
@jomel Your call certainly, but I'd be very wary of doing that. `import { type Foo } from` is a real import, by stripping it out, you're hiding circular dependency problems with your code, so you could end up with code that shouldn't technically work, but happens to work because the imports are deleted by that plugin. If intellisense doesn't work, that should be a bug report for VSCode. I'm surprised it doesn't work though.
