### ISSUE TITLE
[Bug]: Package "exports" field stripped on publishing

### ISSUE THREAD

**Issue by Pandaxyz-xd** [babel/babel#14893] opened 2022-08-30 20:40 UTC
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

None, this is an error with the babel's publishing process.

### Configuration file name

babel.config.json

### Configuration

No response

### Current and expected behavior

No response

### Environment

Babel version: 7.18.10
Node: 18.7.0
Yarn: 1.22.17
OS: macOS 12.5.1

### Possible solution

No response

### Additional context

No response

**Comment by JLHwung** [comment] 2022-08-30 20:42
Duplicate of #14887, see https://github.com/babel/babel/issues/14887#issuecomment-1229200012.

**Closed by JLHwung** 2022-08-30 20:42 UTC
Labels: i: needs triage
