### ISSUE TITLE
Babylon (6 and 7): Flow typecast parsing bug

### ISSUE THREAD

**Issue by wcjohnson** [babel/babel#6447] opened 2017-10-09 04:32 UTC
Choose one: is this a bug report or feature request? Bug report.

### Input Code
```js
callee(castee: CastTo)
```

### Babel Configuration (.babelrc, package.json, cli command)
Babylon with `flow` plugin enabled. Appears to affect both Babylon 6 and 7.

### Expected Behavior
Both the Flow docs (https://flow.org/en/docs/types/casting/) and the Flow parser flag this as a parse error.
The Flow parser says `Unexpected token :` at line 1, column 13

It should be necessary to wrap type casts in explicit `( )`, so e.g. `callee((castee: CastTo))`.

### Current Behavior
Parses successfully leaving an AST like
```
ExprStmt( CallExpression( callee, TypeCastExpression( castee, CastTo ) ) )
```

### Possible Solution
I am working on a patch here: https://github.com/wcjohnson/babylon-lightscript/commit/322842abe7b9fd0ece731eaa2238edeaaa315876

The patch is against a heavily modified Babylon but may be useful nonetheless.

The basic idea is to parse as `TypeCastish` and then convert back to `TypeCastExpression` only during `parseParenAndDistinguishExpression`. Any time a `TypeCastish` is seen outside of there, throw an unexpected type cast error.

### Context
I work on the LightScript language, which uses a fork of Babylon as its parser. The LightScript issue that led to this issue is here: https://github.com/wcjohnson/lightscript/issues/22

### Your Environment
| software         | version(s)
| ---------------- | -------
| Babylon            |  approximately 6.16.0
| node             | 6
| npm              | 5
| Operating System | OS X

**Comment by loganfsmyth** [comment] 2017-10-09 04:43
This appears to be a duplicate of https://github.com/babel/babylon/issues/413

**Closed by loganfsmyth** 2017-10-09 04:43 UTC
