### ISSUE TITLE
undefined does not match type Pattern

### ISSUE THREAD

**Issue by wavded** [babel/babel#1187] opened 2015-04-07 17:18 UTC
When going from Babel 4 to 5 I am getting this error and not sure where it is coming from.  Any ideas?

My .babelrc is:

```
{
  "stage": 0,
  "auxiliaryComment": "istanbul ignore next"
}
```
The error is:

```
/Users/wavded/Projects/widnr/node_modules/babel/node_modules/babel-core/lib/babel/helpers/parse.js:70
    throw err;
          ^
AssertionError: /Users/wavded/Projects/widnr/modules/models/User.js: undefined does not match type Pattern
    at Type.Tp.assert (/Users/wavded/Projects/widnr/node_modules/babel/node_modules/babel-core/node_modules/ast-types/lib/types.js:53:16)
    at addPattern (/Users/wavded/Projects/widnr/node_modules/babel/node_modules/babel-core/node_modules/ast-types/lib/scope.js:220:24)
    at recursiveScanScope (/Users/wavded/Projects/widnr/node_modules/babel/node_modules/babel-core/node_modules/ast-types/lib/scope.js:167:9)
    at recursiveScanChild (/Users/wavded/Projects/widnr/node_modules/babel/node_modules/babel-core/node_modules/ast-types/lib/scope.js:214:9)
    at NodePath.<anonymous> (/Users/wavded/Projects/widnr/node_modules/babel/node_modules/babel-core/node_modules/ast-types/lib/scope.js:150:13)
    at NodePath.each (/Users/wavded/Projects/widnr/node_modules/babel/node_modules/babel-core/node_modules/ast-types/lib/path.js:96:22)
    at recursiveScanScope (/Users/wavded/Projects/widnr/node_modules/babel/node_modules/babel-core/node_modules/ast-types/lib/scope.js:149:14)
    at recursiveScanChild (/Users/wavded/Projects/widnr/node_modules/babel/node_modules/babel-core/node_modules/ast-types/lib/scope.js:214:9)
    at /Users/wavded/Projects/widnr/node_modules/babel/node_modules/babel-core/node_modules/ast-types/lib/scope.js:176:13
    at /Users/wavded/Projects/widnr/node_modules/babel/node_modules/babel-core/node_modules/ast-types/lib/types.js:627:18
    at Array.forEach (native)
    at Object.exports.eachField (/Users/wavded/Projects/widnr/node_modules/babel/node_modules/babel-core/node_modules/ast-types/lib/types.js:626:27)
    at recursiveScanScope (/Users/wavded/Projects/widnr/node_modules/babel/node_modules/babel-core/node_modules/ast-types/lib/scope.js:173:15)
    at recursiveScanChild (/Users/wavded/Projects/widnr/node_modules/babel/node_modules/babel-core/node_modules/ast-types/lib/scope.js:214:9)
    at NodePath.<anonymous> (/Users/wavded/Projects/widnr/node_modules/babel/node_modules/babel-core/node_modules/ast-types/lib/scope.js:150:13)
    at NodePath.each (/Users/wavded/Projects/widnr/node_modules/babel/node_modules/babel-core/node_modules/ast-types/lib/path.js:96:22)
```

**Comment by loganfsmyth** [comment] 2015-04-07 17:20
Looks like you are running into https://github.com/babel/babel/issues/1135

**Comment by wavded** [comment] 2015-04-07 17:23
Just pinpointed the code that produces that error.  Looks like the `async` keyword.

```js
schema.statics.auth = async function (creds) {
}
```

**Comment by sebmck** [comment] 2015-04-07 19:03
Yep, duplicate of #1135.

**Closed by sebmck** 2015-04-07 19:03 UTC
