### ISSUE TITLE
Classes and functions are transpiled into different scopes when no decorators are present

### ISSUE THREAD

**Issue by firelizzard18** [babel/babel#7374] opened 2018-02-13 01:30 UTC
#### Input Code

```js
export function f() {
    return new Class
}

class Class {}
```

#### Output Code

```js
System.register([], function (_export, _context) {
  "use strict";

  function f() {
    return new Class();
  }

  _export("f", f);

  return {
    setters: [],
    execute: function () {
      class Class {}
    }
  };
});
```

#### Input Code

```js
export function f() {
    return new Class
}

@decorator
class Class {}
```

#### Output Code

```js
System.register([], function (_export, _context) {
  "use strict";

  return {
    setters: [],
    execute: function () {
      var _class;

      function f() {
        return new Class();
      }

      _export("f", f);

      let Class = decorator(_class = class Class {}) || _class;
    }
  };
});
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
var path = require('path');
// var paths = require('./paths');

module.exports = function() {
  return {
    filename: '',
    filenameRelative: '',
    sourceMap: true,
    sourceRoot: '',
    moduleRoot: path.resolve('src').replace(/\\/g, '/'),
    moduleIds: false,
    comments: false,
    compact: false,
    code: true,
    presets: [
      '@babel/preset-typescript',
      ['@babel/preset-env', {
        loose: true,
        modules: 'systemjs',
        targets: {
          browsers: [
            "last 2 Chrome versions",
            "last 2 Edge versions"
          ]
        }
      }]
    ],
    plugins: [
      '@babel/plugin-proposal-optional-chaining',
      '@babel/plugin-proposal-decorators',
      ['@babel/plugin-proposal-class-properties', { loose: true }],
      // '@babel/plugin-transform-flow-strip-types'
    ]
  };
};
```

```json
{
  "devDependencies": {
    "@babel/core": "^7.0.0-beta.40",
    "@babel/plugin-proposal-class-properties": "^7.0.0-beta.40",
    "@babel/plugin-proposal-decorators": "^7.0.0-beta.40",
    "@babel/plugin-proposal-optional-chaining": "^7.0.0-beta.40",
    "@babel/plugin-transform-flow-strip-types": "^7.0.0-beta.40",
    "@babel/preset-env": "^7.0.0-beta.40",
    "@babel/preset-typescript": "^7.0.0-beta.40",
    "jspm": "^0.17.0-beta.47",
  }
}
```

### Expected Behavior
The transpiler should be consistent. I expect all declarations to be in the same scope in all cases. If the spec says something like classes must be declared before they are referred to by functions, then the transpiler should consistently transpile with functions in a separate scope.

### Current Behavior
When no decorators are present, declarations are transpiled into multiple scopes. When decorators are present, all declarations are transpiled into a single scope. The non-functional example breaks because `Class` is not in scope when it is used by `f()`.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-beta.40
| node             | v7.7.3
| npm              | 4.1.2
| Operating System | Win 10 Enterprise v1709

**Comment by edsrzf** [comment] 2019-10-03 03:52
Hi there, I'm just doing some issue triage. I'm not able to reproduce this anymore using Babel 7.6.2.

I used this configuration:

```js
module.exports = {
  presets: [
    ['@babel/preset-env', {
      loose: true,
      modules: 'systemjs',
      targets: {
        browsers: [
          "Chrome >= 62",
          "Edge >= 15"
        ]
      }
    }]
  ],
  plugins: [
    ['@babel/plugin-proposal-decorators', { decoratorsBeforeExport: false }],
    ['@babel/plugin-proposal-class-properties', { loose: true }]
  ]
};
```

This should be basically equivalent to the one used in the original report. I removed some things that didn't affect the output, I made the browser target list absolute rather than "last 2" so that the result will be consistent regardless of when the code is compiled, and I had to add `decoratorsBeforeExport: false` to satisfy the current decorator transform.

For the "bad" input, I get the output:

```js
System.register([], function (_export, _context) {
  "use strict";

  var Class;

  function f() {
    return new Class();
  }

  _export("f", f);

  return {
    setters: [],
    execute: function () {
      Class = class Class {};
    }
  };
});
```

Notice that, compared to the report, the `var Class` places the class in the module's scope. The "good" input provides similar results, but with a bunch of added code due to the decorator.

**Comment by nicolo-ribaudo** [comment] 2019-10-03 07:54
Thanks @edsrzf. It has probably been fixed by https://github.com/babel/babel/pull/9639

**Closed by nicolo-ribaudo** 2019-10-03 07:54 UTC
