### ISSUE TITLE
yarn / npm fails compiling when node is on v13 or v14

### ISSUE THREAD

**Issue by dennisdenk** [babel/babel#11491] opened 2020-04-27 16:31 UTC
## Bug Report

**Current Behavior**
When node is installed in Version 13 or 14 yarn dev will fail with following error:
```
yarn run v1.22.4
$ vue-cli-service serve
 INFO  Starting development server...
98% after emitting SizeLimitsPlugin

 ERROR  Failed to compile with 1 errors                                             4:37:32 PM

 error  in ./src/main.js

Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] /home/dennis/Documents/****/****/src/main.js: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
Require stack:
- /home/dennis/Documents/****/****/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js
- /home/dennis/Documents/****/****/node_modules/@babel/preset-env/lib/index.js
- /home/dennis/Documents/****/****/node_modules/@vue/babel-preset-app/index.js
- /home/dennis/Documents/****/****/node_modules/@vue/cli-plugin-babel/preset.js
- /home/dennis/Documents/****/****/node_modules/@babel/core/lib/config/files/plugins.js
- /home/dennis/Documents/****/****/node_modules/@babel/core/lib/config/files/index.js
- /home/dennis/Documents/****/****/node_modules/@babel/core/lib/index.js
- /home/dennis/Documents/****/****/node_modules/@vue/cli-plugin-babel/index.js
- /home/dennis/Documents/****/****/node_modules/@vue/cli-service/lib/Service.js
- /home/dennis/Documents/****/****/node_modules/@vue/cli-service/bin/vue-cli-service.js (While processing: "/home/dennis/Documents/****/****/node_modules/@vue/cli-plugin-babel/preset.js")
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:952:15)
    at Function.Module._load (internal/modules/cjs/loader.js:835:27)
    at Module.require (internal/modules/cjs/loader.js:1012:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/dennis//home/dennis/Documents/****/****/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js:10:55)
    at Module._compile (internal/modules/cjs/loader.js:1123:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:972:32)
    at Function.Module._load (internal/modules/cjs/loader.js:872:14)
    at Module.require (internal/modules/cjs/loader.js:1012:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/dennis/Documents/****/****/node_modules/@babel/preset-env/lib/index.js:29:44)
    at Module._compile (internal/modules/cjs/loader.js:1123:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:972:32)
    at Function.Module._load (internal/modules/cjs/loader.js:872:14)

 @ multi (webpack)-dev-server/client?http://192.168.188.21:8081/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```

**Input Code**
- Just add it to the dependencies

**Expected behavior/code**
To not fail when building.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
module.exports = {
  // https://github.com/vuejs/vue-cli/tree/master/packages/@vue/babel-preset-app
  presets: ['@vue/cli-plugin-babel/preset'],
}
```

**Environment**

```

```
  System:
    OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
  Binaries:
    Node: 12.16.2 - /usr/bin/node   <-- Only working with v12. if 14.0.0 or 13.x.x is installed its not working
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.4 - /usr/bin/npm
  npmPackages:
    babel-core: 7.0.0-bridge.0 => 7.0.0-bridge.0 
    babel-eslint: 10.1.x => 10.1.0 
    eslint: 6.8.x => 6.8.0

**Comment by JLHwung** [comment] 2020-04-27 16:43
Duplicate of #11439

**Comment by JLHwung** [comment] 2020-04-27 16:46
@dennisdenk Thanks for the report, see https://github.com/babel/babel/issues/11439#issuecomment-615185790 for the solution.

**Closed by JLHwung** 2020-04-27 16:46 UTC
Labels: i: bug, i: needs triage

**Comment by dennisdenk** [comment] 2020-04-27 17:08
> @dennisdenk Thanks for the report, see [#11439 (comment)](https://github.com/babel/babel/issues/11439#issuecomment-615185790) for the solution.

Not working for me. Neither V13 nor 14

**Comment by JLHwung** [comment] 2020-04-27 17:12
@dennisdenk Did you try removing your `node_modules` and install again?

**Comment by dennisdenk** [comment] 2020-04-27 17:27
yes. it works when I do npm install and then yarn dev.
but only with yarn its not working at all. same error as before

**Comment by JLHwung** [comment] 2020-04-27 20:20
Please update `vue-cli-service` to 4.3.0, which includes latest `@babel/preset-env` 7.9.0.

**Comment by Maksio** [comment] 2020-05-07 17:59
Had the same issue, have solved with advice above
`vue upgrade`
