### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by againksy** [babel/babel#8344] opened 2018-07-19 21:03 UTC
`node server.js 
/Users/z/project/webpack_babel7/reducers/index.js:1
(function (exports, require, module, __filename, __dirname) { import { combineReducers } from 'redux';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Module._compile (/Users/z/project/webpack_babel7/_server/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (module.js:663:10)
    at Object.newLoader [as .js] (/Users/z/project/webpack_babel7/_server/node_modules/pirates/lib/index.js:88:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)`

https://github.com/againksy/webpack4-serverside-react16/tree/babel7
branch babel7
everything set as in tutorials

**Comment by existentialism** [comment] 2018-07-20 20:10
Is this a duplicate of your other issue at https://github.com/babel/babel/issues/8344?

**Comment by againksy** [comment] 2018-07-26 13:54
@existentialism  no this is another case

**Comment by mintaras** [comment] 2019-01-17 08:52
@againksy Hey, have you ever managed to solve this issue?

**Comment by nicolo-ribaudo** [comment] 2019-10-03 16:53
Sorry for the late reply.

By default, `@babel/register` only comple files in the root folder of the project, which defaults to the cwd. You can overwrite this behavior by passing a custom `only` or `ignore` option:

```js
require("@babel/register")({
  only: [__dirname + "/.."],
  plugins: ["dynamic-import-node", "@babel/plugin-proposal-function-bind"],
  presets: [["@babel/preset-env"], "@babel/preset-react"]
});
```

**Closed by nicolo-ribaudo** 2019-10-03 16:53 UTC
