### ISSUE TITLE
TypeScript's "Immediately Destructured Parameters on Functions" don't work with babel

### ISSUE THREAD

**Issue by kevinOriginal** [babel/babel#9030] opened 2018-11-16 13:02 UTC
## Bug Report

**Current Behavior**
When using object destruction on function parameter types, babel seems not to understand this syntax. Error keep's saying

`SyntaxError: /path/to/my/file/inputs.tsx: Unexpected token, expected ")" `

I'm pretty sure this is a problem with babel because it works perfectly on ts-loader and tsc.
Also, I've tried two different babel settings 
1. create-react-app 2.1
2. custom webpack config with  `@babel/preset-typescript`

**Input Code**

```ts
type NumChangeHandler = ({ target }: any) => void
```

**Expected behavior/code**
ts-loader with webpack supported this syntax. Also is fine with tsc.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
create-react-app 2.1 configurations
```

*OR*

```json
{
	"presets": [
			"@babel/typescript"
	],
	"plugins": [
			"@babel/proposal-class-properties",
			"@babel/proposal-object-rest-spread"
	]
}
```

**Environment**
- Babel version(s): 7.1.6
- Node/npm version: Node 10.13/npm 6.4.1
- OS: mac OS 10.13.6
- Monorepo: no
- How you are using Babel: Create-react-app 2.1.1

**Possible Solution**

**Additional context/Screenshots**
![image](https://user-images.githubusercontent.com/18115360/48622816-548e5300-e9eb-11e8-86de-abcf99adc23c.png)

**Comment by danez** [comment] 2018-11-17 22:35
Thanks for reporting. This is a duplicate of #8745.

**Closed by danez** 2018-11-17 22:35 UTC
Labels: area: typescript, i: bug, pkg: parser (babylon)
