### ISSUE TITLE
how to get rid of regenerator runtime errors (I don't want that polyfill)

### ISSUE THREAD

**Issue by DrYSG** [babel/babel#9971] opened 2019-05-13 14:35 UTC
I continue to get:

App.jsx:11 Uncaught ReferenceError: regeneratorRuntime is not defined

on any line that does an async. I don't what that polyfill, but I am having a hard time getting rid of it:

**app.jsx:11)
```
 const fetcher = (async () => {

```

 ```
   "@babel/cli": "^7.4.4",
    "@babel/core": "^7.4.4",
    "@babel/preset-env": "^7.4.4",
    "@babel/preset-react": "^7.0.0",
    "@types/react": "^16.8.17",
    "babel-preset-env": "^1.7.0"
```

here is the .babelrc

```
{
    "presets": [
        [
            "@babel/preset-env",
            {
                "targets": {
                    "chrome": ">70",
                },
                "exclude": ["transform-regenerator"]
            },
            "@babel/preset-react"
        ]
    ]
}
```

**Comment by nicolo-ribaudo** [comment] 2019-05-13 19:26
What is the compiled output? Is there any other Babel configuration in your project?

PS. You don't need `babel-preset-env` if you are already using `@babel/preset-env`

**Comment by DrYSG** [comment] 2019-05-13 21:09
The bundler is parcel, and their are just 3 small JSX files and an main.html

I removed the babel-preset-env,

There are not other babel configurations.

I can provide the source also if that helps (I am just beginning to explore this)

The bundle below does have the transform-runtime plugin. And yes, it does work with that in it. I was really trying to see if I could avoid it:

```
{
    "presets": [
        [
            "@babel/preset-env",
            {
                "targets": {
                    "chrome": ">74",
                },
                "exclude": ["transform-regenerator"]
            },
            "@babel/preset-react"
        ]
    ],
    "plugins": [
        ["@babel/transform-runtime"]
    ]
}
```

[dist.zip](https://github.com/babel/babel/files/3174829/dist.zip)

**Comment by DrYSG** [comment] 2019-05-14 16:27
And attached is the bundle when I remove the @babel/transform-runtime plugin

[dist.zip](https://github.com/babel/babel/files/3178827/dist.zip)

**Comment by nicolo-ribaudo** [comment] 2019-05-14 21:57
Could you share a repository which I can use to reproduce the problem? It's impossible to debug it from the minified output.

**Comment by andrewnaeve** [comment] 2019-05-14 22:58
I'm also getting this error for Node 10.

```
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "node": "current",
          "esmodules": true
        }
      }
    ]
  ],
  "plugins": [["@babel/transform-runtime"]]
}

```

**Comment by DrYSG** [comment] 2019-05-15 13:57
Sure, included is the source. you first request was for the compiled output. That is the only reason I sent that. We use parcel as our bundler (it finds the .babelrc)

[bug.zip](https://github.com/babel/babel/files/3182819/bug.zip)

**Comment by nicolo-ribaudo** [comment] 2019-05-15 23:13
It's a bug with Parcel, which for some reason tries to parse your .babelrc file and use it to generate a new config to pass to Babel.

Can you check if this works for you? (I downloaded your zip and it seems to work)

```json
{
    "presets": [
        [
            "@babel/preset-env",
            {
                "targets": {
                    "chrome": 74,
                }
            }
        ],
        
        "@babel/preset-react"
    ]
}
```

Ref: https://github.com/parcel-bundler/parcel/issues/1762#issuecomment-462820098

**Comment by DrYSG** [comment] 2019-05-16 16:55
That also gives the regenerator bug. But as you say, it seems to be a parcel issue, not a babel issue.

**Comment by nicolo-ribaudo** [comment] 2019-07-15 18:26
Closing, since this issue is caused by Parcel which doesn't use the `.babelrc` file as-is.

**Closed by nicolo-ribaudo** 2019-07-15 18:26 UTC
Labels: i: question
