### ISSUE TITLE
"export default from" identifier not supported

### ISSUE THREAD

**Issue by guybedford** [babel/babel#11665] opened 2020-06-03 00:17 UTC
## Bug Report

**Current behavior**
A clear and concise description of the behavior.

- [REPL](babeljs.io/repl), [Codesandbox](https://codesandbox.io/s/babel-repl-custom-plugin-7s08o?file=/src/index.js), or GitHub Repo helps!

**Input Code**

```js
function from(x) {
    return x === x[Symbol.iterator]() ? Array.from(x) : x;
}
export default from;
```

**Expected behavior**

The above is a valid ES module and will execute in browsers, but throw when parsed by Babylon.

- Babel version(s): [e.g. v6.0.0, v7.0.0-beta.34] 7.10.2

**Possible Solution**

Acorn handles this parsing fine, so it should be a relatively straightforward parser fix.

**Comment by JLHwung** [comment] 2020-06-04 16:28
Duplicate of #7293

**Closed by JLHwung** 2020-06-04 16:28 UTC
Labels: i: bug, i: needs triage

**Comment by JLHwung** [comment] 2020-06-04 21:55
FYI this will be fixed in #11676.
