### ISSUE TITLE
Extraneous transforms when using properly scoped variables

### ISSUE THREAD

**Issue by polkovnikov-ph** [babel/babel#5013] opened 2016-12-17 10:15 UTC
### Input Code

I couldn't come up with a better name. Please, rename the issue as you see fit.

[Live version.](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&code=const%20f%20%3D%20x%20%3D%3E%20%7B%0D%0A%09if%20(true)%20%7B%0D%0A%09%09const%20a%20%3D%201%3B%0D%0A%09%09const%20b%20%3D%202%3B%0D%0A%09%09return%20function%20()%20%7B%0D%0A%09%09%20%20console.log(a%20%2B%20b)%3B%0D%0A%09%09%7D%3B%0D%0A%09%7D%0D%0A%7D%3B)

```js
const f = x => {
	if (true) {
		const a = 1;
		const b = 2;
		return function () {
			console.log(a + b);
		};
	}
};
```

### Babel Configuration (.babelrc, package.json, cli command)
Online version.

### Expected Behavior

```js
"use strict";

var f = function f(x) {
	if (true) {
		var a = 1;
		var b = 2;
		return function () {
			console.log(a + b);
		};
	}
};
```

### Current Behavior

Lots of useless code:

```js
"use strict";

var _typeof = typeof Symbol === "function" && typeof Symbol.iterator === "symbol" ? function (obj) { return typeof obj; } : function (obj) { return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj; };

var f = function f(x) {
	if (true) {
		var _ret = function () {
			var a = 1;
			var b = 2;
			return {
				v: function v() {
					console.log(a + b);
				}
			};
		}();

		if ((typeof _ret === "undefined" ? "undefined" : _typeof(_ret)) === "object") return _ret.v;
	}
};
```

### Possible Solution

Seems like it's trying to keep variables named the same way. Most likely it should create variables `a$1`/`b$1` when these are already used in current functional scope. I see no problem with that, given that it's `const`s.

### Context

This alone generates a decent chunk of JS on my page, and I don't have an idea what do all these `Symbol.*` have in common with this code.

### Your Environment

| software         | version
| ---------------- | -------
| Babel            | Your online version
| node             | Your online version
| npm              | Your online version
| Operating System | Your online version

**Comment by Kovensky** [comment] 2016-12-21 07:34
The `a` and `b` `const`s are not the direct children of a function's block, so they have to be wrapped in a function. The problem with not wrapping is probably easiest to see with a loop:

```js
const xs = [1, 2];
const result = [];
for (const x of xs) {
  const val = x;
  result.push(() => val);
}
for (const fn of result) {
  console.log(fn())
}
```

If the block is not wrapped in a `function`, and you got something like...

```js
for (var x of xs) {
  var val = x;
  result.push(() => val);
}
```

... the loop at the bottom would print `2` twice, instead of `1` and `2`.

TRWTF is that, as the returned value in the block has to be wrapped in an object (to detect cases like `break` or early `return`), the arrow function is receiving the wrong `Function.name` 😄

**Comment by polkovnikov-ph** [comment] 2016-12-21 15:48
@Kovensky Yes, I understand why IIFE is a thing, but it should be used for loops, not for `try...catch`, `if` or `switch`. In these cases variable renaming is enough, and I don't understand why IIFE is employed in such cases.

**Comment by gabor** [comment] 2017-01-16 15:19
i've found out about this issue from a cryptic Istanbul message, saying "else path not taken" at a place where there is no `if`. 

my guess is that it complains about the `if` that is inserted by babel (`if ((typeof _ret === "undefined" ? "undefined" : _typeof(_ret)) === "object") return _ret.v;`).

 the strange thing for me is that (considering the test-case presented in this issue), the 'before-transform' code always returns a function, but the 'after-transform' code can, in theory, return `undefined`. is this intended behavior? also, any idea how to stop Istanbul from complaining? (for me it seems it's complaint is legitimate. there indeed is an `else` situation, i am just not sure how to trigger it)

**Comment by nicolo-ribaudo** [comment] 2019-02-12 16:46
This is fixed now - https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&code=const%20f%20%3D%20x%20%3D%3E%20%7B%0D%0A%09if%20(true)%20%7B%0D%0A%09%09const%20a%20%3D%201%3B%0D%0A%09%09const%20b%20%3D%202%3B%0D%0A%09%09return%20function%20()%20%7B%0D%0A%09%09%20%20console.log(a%20%2B%20b)%3B%0D%0A%09%09%7D%3B%0D%0A%09%7D%0D%0A%7D%3B

```js
"use strict";

var f = function f(x) {
  if (true) {
    var a = 1;
    var b = 2;
    return function () {
      console.log(a + b);
    };
  }
};
```

**Closed by nicolo-ribaudo** 2019-02-12 16:46 UTC
Labels: i: bug

**Comment by polkovnikov-ph** [comment] 2019-02-12 23:51
And not only that, there is a new version of Babel REPL!
