### ISSUE TITLE
babel-plugin-transform-runtime 

### ISSUE THREAD

**Issue by jdalton** [babel/babel#6983] opened 2017-12-06 20:56 UTC
Using `@babel/plugin-transform-runtime` of `^7.0.0-beta.34` I noticed that it doesn't generate `_interopRequireDefault` with `useESModules:true` and `.js` files

The code is something like:
```js
var _wrapAsyncGenerator = require("@babel/runtime/helpers/builtin/es6/wrapAsyncGenerator");
```
However, if I rename my file from `.js` to `.mjs` then it produces the helper
```js
var _interopRequireDefault = require("@babel/runtime/helpers/builtin/es6/interopRequireDefault");
var _wrapAsyncGenerator2 = _interopRequireDefault(require("@babel/runtime/helpers/builtin/es6/wrapAsyncGenerator"));
```
I would expect the helper to exist for either file extension.

**Comment by jdalton** [comment] 2017-12-06 20:59
Also noticed that with `.mjs` the `_interopRequireDefault` should be used on itself
```js
var _interopRequireDefault = require("@babel/runtime/helpers/builtin/es6/interopRequireDefault");
```
should be
```js
var _interopRequireDefault = require("@babel/runtime/helpers/builtin/es6/interopRequireDefault");
_interopRequireDefault = _interopRequireDefault(_interopRequireDefault)
```

**Comment by jdalton** [comment] 2017-12-06 21:14
Also noticed that with `.mjs` the `_interopRequireDefault` should be used on itself
```js
var _interopRequireDefault = require("@babel/runtime/helpers/builtin/es6/interopRequireDefault");
```
should be
```js
var _interopRequireDefault = require("@babel/runtime/helpers/builtin/es6/interopRequireDefault");
_interopRequireDefault = _interopRequireDefault(_interopRequireDefault)
```

**Comment by jdalton** [comment] 2017-12-06 21:14
If I set `"modules": false` I noticed that with `useESModules:true` the `.mjs` will generate imports like
```js
import _wrapAsyncGenerator from "@babel/runtime/helpers/builtin/es6/wrapAsyncGenerator";
```
where as the `.js` file will generate `require` calls like
```js
var _wrapAsyncGenerator = require("@babel/runtime/helpers/builtin/es6/wrapAsyncGenerator");
```

The `"sourceType":"module"` or `"sourceType":"unambiguous"` doesn't resolve this since the file source is:
```js
async function* gen() {
  yield 'first'
  yield 'last'
}

async function main() {
  for await (let item of gen()) {
    console.log(item)
  }
}

main()
```
and has no `import` or `export`.
If I add an `export {}` then either sourceType of `"module"` or `"unambiguous"` seem to generate the imports.

**Comment by nicolo-ribaudo** [comment] 2017-12-06 21:51
`_interopRequireDefault` isn't needed when `require`ing helpers because they are guaranteed to be generated from es modules.

This is the `_interopRequireDefault` definition:
``` js
function _interopRequireDefault(obj) {
  return obj && obj.__esModule ? obj : { default: obj };
}
```

In babel helpers, `__esModule` is always true so that function is equivalent to the identity function, which can be elided.


When you use the `.mjs` extension, Babel injects`import _wrapAsyncGenerator from "@babel/runtime/...`. Then the `modules-to-commonjs` plugin runs, sees a default import and transforms it like it does for any default import: `var NAME = _interopRequireDefault(require("SOURCE"))`.

Regarding your last comment, babel inserts `require` calls instead of `import` statements (which would then be transpiled to `require` calls with `interopRequireDefault`) because if the extension is `.js` and the source code can be parsed as a script (it doesn't contain `export`/`import`), it inserts `require` calls for backwards compatibility. You can see the logic used to choose between `require` and `import` [here](https://github.com/babel/babel/blob/master/packages/babel-helper-module-imports/src/is-module.js).

**Comment by jdalton** [comment] 2017-12-06 22:29
With `"modules":false` and `useESModules:true` there is a state where the `require()` helper is ESM via `require("@babel/runtime/helpers/builtin/es6/wrapAsyncGenerator")` . This normally won't work, but with `@std/esm` it can *(kindof)*. Except that it would expect the result of `require` of the ESM code to be `{ default: wrapAsyncGeneratorFunc }`. So I use a compat mode which will load it with `__esModule` on its `module.export` which is normally handled by the `interopRequireDefault` helper but since the `interopRequireDefault` doesn't check itself then it's not helped :yum:

**Comment by nicolo-ribaudo** [comment] 2017-12-06 22:36
We can distinguish helper injection in two cases:
- **`require`** calls
    1) When `sourceType` is `script`
    2) When `sourceType` is `module` or `unambiguous`, but the extension is `.js` and the module can be parsed as a script. [This is needed for compatibility with older babel versions](https://github.com/babel/babel/blob/master/packages/babel-helper-module-imports/src/is-module.js#L31)
    ```js
    var _helper = require("@babel/runtime/.../helper.js");
    // ...
    _helper(/* ... */);
    ```
- **`module`** statements
    1) When the extension is `.mjs`
    2) When the extension is `.js`, `sourceType` is `module` or `unambiguous` and the module can't be parsed as a script (because it contains `import` or `export`s).
    ```js
    import _helper from "@babel/runtime/.../helper.js";
    // ...
    _helper(/* ... */);
    ```


After helpers are injected, the `moules-to-commonjs` plugin runs.
- **`require`** calls
  They are't transformed, so they remain as they were injected by `transform-runtime` (without `_interopRequireDefault`)
- **`module`** statements
  1) Every import statement is transpiled:
    ```js
    import foo from "foo";
    foo(/* ... */);

    // BECOMES

    var foo = _interopRequireDefault(require("foo"));
    (foo.default)(/* ... */);
    ```
    `_interopRequireDefault` is needed because Babel doesn't know if the imported module (which, in this case, is the helper) is a CommonJS module or a transpiled ES module. When the imported module is a CommonJS one, `_interopRequireDefault` returns `{ default: require("foo") }`, so that it can be used as if it was an ES module (using `foo.default`).
  2) `transform-modules-to-commonjs` imports injects `var _interopRequireDefault = require("...");`. Since it is directly injected as a `require` call and not as an `import` statement, it is always used directly (and not as `(_interopRequireDefault.default)(/* ... */)`), so it doesn't need to be wrapped by itself.

**Comment by nicolo-ribaudo** [comment] 2017-12-06 22:40
Oh, I get the problem now. So if `useESModules: true`, babel should always inject `import`s and then transpile them.

**Comment by jdalton** [comment] 2017-12-06 22:41
> Oh, I get the problem now. So if useESModules: true, babel should always inject imports and then transpile them.

That might be the easier way. Ya.

**Comment by nicolo-ribaudo** [comment] 2017-12-06 22:44
Or it could output something like
```js
var _awaitAsyncGenerator = require("@babel/runtime/helpers/es6/awaitAsyncGenerator").default;
var _wrapAsyncGenerator = require("@babel/runtime/helpers/es6/wrapAsyncGenerator").default;

let foo =
/*#__PURE__*/
(() => {
  var _ref = _wrapAsyncGenerator(function* () {});

  return function foo() {
    return _ref.apply(this, arguments);
  };
})();

```

This is possible only because we know that helpers' default export is never reassigned, so it doesn't need to be a live binding.

**Comment by jdalton** [comment] 2017-12-06 22:49
Yap, that would work too!

**Comment by loganfsmyth** [comment] 2017-12-06 23:35
To me this seems like expected behavior of using unambiguous grammar. I think I would have assumed that `std/esm` would add `export {};` to force processing as a ES module if that's what you want.

**Comment by jdalton** [comment] 2017-12-07 00:08
@loganfsmyth For the part of it generating `require` calls instead of static imports I found it odd that specifying `sourceType` of `"module"` didn't work either.

**Comment by loganfsmyth** [comment] 2017-12-07 00:52
Ah of course. You are right about sourceType:module. We added unambiguous logic to Babylon but haven't removed the logic from the module transform yet. If we remove that it should fix this.

We should also decide if we want to default to script for .js files. I feel like we should probably?

**Comment by jdalton** [comment] 2017-12-07 00:57
@loganfsmyth 
> We should also decide if we want to default to script for .js files.

Doesn't Babel just default to `"module"` for everything?

**Comment by loganfsmyth** [comment] 2017-12-07 01:28
It does default to module, but that means people trip over it whenever they want to compile things in `node_modules` since we inject use strict on things that aren't strict and rewrite `this` to `undefined`. Defaulting to script would be way better for consistency.

**Comment by jdalton** [comment] 2017-12-07 01:32
> It does default to module, but that means people trip over it whenever they want to compile things in `node_modules` since we inject use strict on things that aren't strict and rewrite `this` to `undefined`.

Ah, I thought that's what `"unambiguous"` was created to avoid. Would defaulting to `"unambiguous"` make sense? It's what TypeScript does I believe.

**Comment by jdalton** [comment] 2017-12-07 01:34
....Maybe that whole "What should the default thing rehash should be a separate issue though. Feel free to cc me on it though.

**Comment by loganfsmyth** [comment] 2017-12-07 02:01
Yeah fine with that being separate, though we may already have one for that. Can't look at the moment though.

**Comment by loganfsmyth** [comment] 2018-03-05 05:25
Woops, I linked the wrong ID when I closed it, but I fixed this in https://github.com/babel/babel/pull/7417.

**Closed by loganfsmyth** 2018-03-05 05:25 UTC
Labels: area: helpers, area: modules, i: bug
