### ISSUE TITLE
Issue in inheritance

### ISSUE THREAD

**Issue by hakobpogh** [babel/babel#5713] opened 2017-05-07 19:47 UTC
I have tested this input code in chrome and your compiled code also and discovered an issue. I have described that issue in the comments in the following code.
```javascript
class B extends RegExp {
  constructor(source, flags) {
    super(source, flags);
  }
  getName() {
    return 'name';
  }
}

new B('test', 'i').test('TeSt') // is true as should be
new B('test', 'i').test('TeSt') // throws error but should be "name"
```

**Comment by loganfsmyth** [comment] 2017-05-07 20:55
Did you mean to call `getName`?  I don't understand your example.

That said, the issue is likely that currently Babel does not support extending builtin constructor types like `RegExp`.

**Comment by hakobpogh** [comment] 2017-05-08 09:40
Yes. When I'm trying to extend `RegExp` the problem occurs with new methods on my type.
But in chrome with the ES6 code, there is no problem. So ES6 supports that but your compiler doesn't.

**Comment by loganfsmyth** [comment] 2017-05-08 17:28
Yeah, we've documented this behavior in https://babeljs.io/docs/usage/caveats/#classes. Unfortunately it's not an easy fix.

Closing this since it is a duplicate of https://github.com/babel/babel/issues/4480.

**Closed by loganfsmyth** 2017-05-08 17:28 UTC
