### ISSUE TITLE
--config-file option does not work with @babel/cli.

### ISSUE THREAD

**Issue by jwalton** [babel/babel#8919] opened 2018-10-23 21:35 UTC
## Bug Report

**Current Behavior**

```
17:33:10 [jwalton@morgana ~/benbria/node-promise-tools] (master) $ cat babelModules.js
module.exports = {
    "presets": [
        ["@babel/env", { "targets": "> 0.25%, not dead", "modules": false }]
    ]
}

17:33:09 [jwalton@morgana ~/benbria/node-promise-tools] (master) $ ./node_modules/.bin/babel --config-file babelModules.js -d dist/modules src
{ Error: Cannot find module 'babelModules.js' from '/Users/jwalton/benbria/node-promise-tools'
    at Function.module.exports [as sync] (/Users/jwalton/benbria/node-promise-tools/node_modules/@babel/core/node_modules/resolve/lib/sync.js:43:15)
    at loadConfig (/Users/jwalton/benbria/node-promise-tools/node_modules/@babel/core/lib/config/files/configuration.js:158:39)
    at buildRootChain (/Users/jwalton/benbria/node-promise-tools/node_modules/@babel/core/lib/config/config-chain.js:76:40)
    at loadPrivatePartialConfig (/Users/jwalton/benbria/node-promise-tools/node_modules/@babel/core/lib/config/partial.js:85:55)
    at loadFullConfig (/Users/jwalton/benbria/node-promise-tools/node_modules/@babel/core/lib/config/full.js:43:39)
    at process.nextTick (/Users/jwalton/benbria/node-promise-tools/node_modules/@babel/core/lib/transform-file.js:48:33)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
    at Function.Module.runMain (module.js:696:11)
    at startup (bootstrap_node.js:204:16) code: 'MODULE_NOT_FOUND' }

```

**Expected behavior**

Babel should load the config file specified and use it.

**Environment**
- Babel version(s): 7.1.2
- Node/npm version: Node 8.12.0/npm 6.4.1
- OS: OSX 10.13.6
- Monorepo No
- How you are using Babel: CLI

**Comment by loganfsmyth** [comment] 2018-10-23 22:55
I don't know if this was the right call design-wise, but this all behaves like `require("babelModules.js")`, which means that for it to find the config file, you need a `./` before the filename.

**Comment by jwalton** [comment] 2018-10-23 23:36
Should we perhaps add the "./" if the path doesn't start with "/" or "./" or `/[a-zA-Z]:\\/` already?  Or, maybe, if the file is not found, then add the "./" and try again?  This is kinda weird behavior for a command line switch.

**Comment by loganfsmyth** [comment] 2018-10-23 23:45
I don't think I'd want to change the behavior of it now, since it could be legitimately useful to do `--config-file my-build-tool/babel-config` or something to load `node_modules/my-build-tool/babel-config.js`. That said, I'd be 100% behind some logic to make the error message more helpful. It wouldn't be too hard to catch the module load failure and try again with "./" and log an error with a suggestion of how to fix the issue. We already do this kind of message improvement in https://github.com/babel/babel/blob/9d0dcedb2b42c95e51a7892b5139b752a98f6e20/packages/babel-core/src/config/files/plugins.js#L124 for example.

**Comment by javierguzman** [comment] 2019-11-03 14:43
Hello,

I am trying to specify my babel configuration under my config folder but it does not work. Is this option still not available? What would be the workaround? Thank you in advance and regards.

**Comment by nicolo-ribaudo** [comment] 2019-11-04 23:26
It is available. Please post your files tree, the command you are running, and where you are running that command from.

**Comment by javierguzman** [comment] 2019-11-05 09:33
Thanks for your message Nicolo! My project tree is as follows:
Project
  |
 +-- client
 +-- server
      |
     +-- config
          | 
          +-- babel.config.js
     +-- src
     +--package.json

I have been running "npm run build" from Project/server.

npm run build was: "babel -d dist --config-file config/config.babel.js src"
Still, I tried other folder combinations like ./config/config.babel.js for example.

On Reddit someone as suggested I should use @babel/cli rather than babel-cli as dependency, but I do not know why. 

On the other hand being honest I swapped yesterday to Webpack as it works in that way... Still I am interested to know if I was doing this in the correct manner because it was really bizarre.

Again thank you and regards.

**Comment by nicolo-ribaudo** [comment] 2019-11-05 09:36
Reddit's folks are correct. babel-cli is Babel 6 and @babel/cli is Babel 7 (babel.config.js has been introduced in v7.0.0)

**Comment by javierguzman** [comment] 2019-11-05 09:43
I see! Thanks for the clarification about @. Still I think I tried to use .babelrc which I think it should work, but taking into account I was using an old version who knows what was going on. Anyway, as I mentioned I swapped to Webpack, if I find time to try this again I will write back, just for the sake of curiosity... mainly!

**Comment by nicolo-ribaudo** [comment] 2019-11-05 09:44
When you came back to this, I suggest reading https://babeljs.io/docs/en/config-files for the difference between `babel.config.js` and `.babelrc`!

**Comment by see** [comment] 2022-08-19 01:31
same issue

**Comment by JLHwung** [comment] 2022-08-19 13:25
Closing this issue as `@babel/cli` works as intended per https://github.com/babel/babel/issues/8919#issuecomment-432450722.

@see Please open a new issue with a _reproducible_ repo (what is the error stack trace? what is the content of `.babelrc.umd.js`?) instead of a screenshot.

**Closed by JLHwung** 2022-08-19 13:25 UTC
Labels: help wanted, area: errors
