### ISSUE TITLE
Comment in empty argument list is misplaced in compiled output

### ISSUE THREAD

**Issue by CMTegner** [babel/babel#1911] opened 2015-07-03 10:47 UTC
Input:
```js
function foo(/* comment */) {}
```

Output:
```js
function foo() {}
/* comment */
```

Leading and trailing comments work as expected:

```js
function foo(arg /* comment */) {}
function foo(/* comment */ arg) {}
```

```js
function foo(arg /* comment */) {}
function foo( /* comment */arg) {}
```

[Reproducible in the online REPL](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=true&spec=true&code=function%20foo(%2F*%20comment%20*%2F)%20%7B%7D%0Afunction%20foo(arg%20%2F*%20comment%20*%2F)%20%7B%7D%0Afunction%20foo(%2F*%20comment%20*%2F%20arg)%20%7B%7D) at the time of writing.

**Comment by hzoo** [comment] 2015-07-03 11:01
duplicate of #1904 and others

**Closed** 2015-07-07 10:31 UTC
