### ISSUE TITLE
ngAnnotate with static methods

### ISSUE THREAD

**Issue by CWSpear** [babel/babel#2257] opened 2015-08-24 17:15 UTC
I'm using `gulp-babel` to compile assets, and I had a local version using `babel-core` `5.6.17`, and it was working correctly, but when I did a fresh `npm install`, it installed the latest: `5.8.21`.

Input (as part of a class):

```js
/*@ngInject*/
static productsCategoryProductRoute($stateProvider) {
    $stateProvider
        .state('products.category.product', {
            url: '/:slug',
            templateUrl: 'assets/products/category/products/product.detail.html',
            controllerAs: 'ctrl',
            controller: ProductDetailController,
            resolve: {
                product(api, $stateParams) {
                    return api.one('products', $stateParams.slug).get();
                },
                cartReadyCheck(Cart) {
                    Cart.onReady(angular.noop);
                },
            },
            nav: { breadcrumb: '{{ product.name }}' },
        });
}
```

Output with `5.6.17` (it does `babel` then `ng-annotate`):

```js
...
}], [{
    key: 'productsCategoryProductRoute',

     /*@ngInject*/
    value: ["$stateProvider", function productsCategoryProductRoute($stateProvider) {
        $stateProvider.state('products.category.product', {
            url: '/:slug',
            templateUrl: 'assets/products/category/products/product.detail.html',
            controllerAs: 'ctrl',
            controller: ProductDetailController,
            resolve: {
                product: ["api", "$stateParams", function product(api, $stateParams) {
                    return api.one('products', $stateParams.slug).get();
                }],
                cartReadyCheck: ["Cart", function cartReadyCheck(Cart) {
                    Cart.onReady(angular.noop);
                }]
            },
            nav: { breadcrumb: '{{ product.name }}' }
        });
    }]
}], [{
...
```

Output with `5.8.21`:

```js
...
    /*@ngInject*/
}], [{
    key: 'productsCategoryProductRoute',
    value: function productsCategoryProductRoute($stateProvider) {
        $stateProvider.state('products.category.product', {
            url: '/:slug',
            templateUrl: 'assets/products/category/products/product.detail.html',
            controllerAs: 'ctrl',
            controller: ProductDetailController,
            resolve: {
                product: ["api", "$stateParams", function product(api, $stateParams) {
                    return api.one('products', $stateParams.slug).get();
                }],
                cartReadyCheck: ["Cart", function cartReadyCheck(Cart) {
                    Cart.onReady(angular.noop);
                }]
            },
            nav: { breadcrumb: '{{ product.name }}' }
        });
    }
}], [{
...
```

Note that because `/*@ngInject*/` is no longer on the line above the function definition, `ng-annotate` can't do its thing.

I know just how much you love `ng-annotate`, but figured I should bring it to your attention.

--

**Edit**: As @olov commented, I accidentally pasted the same output twice, and I have fixed that now.

**Comment by olov** [comment] 2015-08-24 19:09
So I happened to stumble upon this issue when spending time in Babel github because I'd like to deprecate `defs` eventually, and it so happens that I'm responsible for `ng-annotate` too, so.. Here are my 2 cents, love them or not. You seem to have copied the output example twice so it's hard to see what's going on there but in general my advice is to use `"ngInject";` as a directive prologue (see ng-annotate docs) rather than an `/*ngInject*/` comment, because most tools just don't work that great in terms of preserving comments.

**Comment by olov** [comment] 2015-08-24 19:30
Thanks for the update. My advice is still to change `/*@ngInject*/ static productsCategoryProductRoute($stateProvider) { ...` to 
`static productsCategoryProductRoute($stateProvider) { "ngInject"; ... }` so you don't have to rely on Babel preserving comments. If you want more help on ng-annotate then just open up an issue on it.

**Comment by CWSpear** [comment] 2015-08-24 19:35
Ah, ok, I had actually tried `"ngInject";`, but I didn't realize it needed to go *inside* the function like a `'use strict';` would, and thus I was getting parse errors.

So, for completeness and posterity, changing my above "input" to the following is a working workaround:

```js
static productsCategoryProductRoute($stateProvider) {
    'ngInject';
    $stateProvider
        .state('products.category.product', {
            url: '/:slug',
            templateUrl: 'assets/products/category/products/product.detail.html',
            controllerAs: 'ctrl',
            controller: ProductDetailController,
            resolve: {
                product(api, $stateParams) {
                    return api.one('products', $stateParams.slug).get();
                },
                cartReadyCheck(Cart) {
                    Cart.onReady(angular.noop);
                },
            },
            nav: { breadcrumb: '{{ product.name }}' },
        });
}
```

I'll leave the ticket open for now, and let the `babel` team decide if they want to address it further.

Anyway, thanks @olov!

**Comment by sebmck** [comment] 2015-08-27 20:45
I can't replicate this. Can you please provide a full reproducible example in the [REPL](https://babeljs.io/repl/) please @CWSpear?

**Comment by CWSpear** [comment] 2015-08-27 21:31
Looks like there are [some scenarios](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=class%20Test%20%7B%0A%20%20%2F*%20%40ngAnnotate%20*%2F%0A%20%20static%20someFn%20()%20%7B%7D%0A%7D%0A) where it works, but here's [one where it doesn't](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=class%20Test%20%7B%0A%20%20someOtherFn()%20%7B%7D%0A%20%20%2F*%20%40ngAnnotate%20*%2F%0A%20%20static%20someFn%20()%20%7B%7D%0A%7D%0A)

**Comment by thejameskyle** [comment] 2015-09-23 08:20
Reduced test case:

```js
class Foo {
  // foo
  foo = 1;
  
  // bar
  static bar = 2;
  
  // baz
  baz() {}
  
  // bat
  static bat() {}
}
```

Becomes:

```js
var Foo = (function () {
  function Foo() {
    _classCallCheck(this, Foo);

    this.foo = 1;
  }

  _createClass(Foo, [{
    key: "baz",

    // baz
    value: function baz() {}

    // bat
  }], [{
    key: "bat",
    value: function bat() {}
  }, {
    key: "bar",

    // bar
    value: 2,
    enumerable: true
  }]);

  return Foo;
})();

// foo
```

So comments aren't being properly inherited/attached(?) for **static methods** and **instance properties**.

**Comment by thejameskyle** [comment] 2015-09-23 08:23
I'm going to create a new issue that just has the relevant information and close this one.

**Closed** 2015-09-23 08:23 UTC
Labels: confirmed
