### ISSUE TITLE
target environment options

### ISSUE THREAD

**Issue by tracker1** [babel/babel#1918] opened 2015-07-04 05:56 UTC
I know there are more than a few target environment options, but was thinking it would be nice if there were some basic targets of "es5" or "es6" so that for modern node/iojs where generators and other es6 features are in the box, they can be used (as well as newer browsers)...

I'm just thinking it would be nice if there were a less boilerplate option for those environments that have the needed capabilities... or for that matter, a self-detecting browser shim for a few different classes...

IE9 and IE10 need a lot more than say current chrome/ff or ie-edge.  And node 0.xx more than iojs 2.x ... Just a small wishlist, and just some ideas on this.. I'm sure it's probably been discussed

**Comment by sebmck** [comment] 2015-07-04 09:24
Duplicate of #631.

**Closed by sebmck** 2015-07-04 09:24 UTC
