### ISSUE TITLE
[Bug]: invalid code optimization with @babel/transform 7.17.10

### ISSUE THREAD

**Issue by mfukala** [babel/babel#14534] opened 2022-05-06 11:49 UTC
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code
`class Test {

   foo() {

      var self = this;

      var checkWithUserPromise = new Promise(function (resolve) {

        self.userInputComplete = resolve;

        console.log('--------------');

        document.getElementById('Dialog').open();

      });

      return checkWithUserPromise;

    }

}`

### Current and expected behavior

Transpiled code used to be 

`checkWithUserForItemOrgAssociation(){var a=this,b=new Promise(function(b){a.userInputComplete=b,console.log("--------------"),document.getElementById("Dialog").open()});return b}
`

since @babel/transform 7.17.10 it is transpiled to 

`checkWithUserForItemOrgAssociation(){var a=new Promise(function(a){this.userInputComplete=a,console.log("--------------"),document.getElementById("Dialog").open()});return a}`

which is obviously wrong.

### Environment

node v16.13.0
npm 8.1.0
@babel/core 7.17.10
babel-preset-minify: 0.5.1

### Possible solution

I had to use npm-shrinkwrap.json to enforce older @babel/transform sub dependency of @babel/core

**Comment by JLHwung** [comment] 2022-05-06 12:23
Duplicate of https://github.com/babel/minify/issues/1028.

**Closed by JLHwung** 2022-05-06 12:23 UTC
Labels: i: needs triage
