### ISSUE TITLE
[Bug]: Missing registerDeclaration in plugin-transform-typescript

### ISSUE THREAD

**Issue by amoeller** [babel/babel#15486] opened 2023-03-11 21:33 UTC
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```
import foo = bar
```

### Current and expected behavior

plugin-transform-typescript fails to register the declaration at

```
        path.replaceWith(
          t.variableDeclaration("var", [
            t.variableDeclarator(
              path.node.id,
              entityNameToExpr(path.node.moduleReference),
            ),
          ]),
        );
```
in packages/babel-plugin-transform-typescript/src/index.ts.

### Environment

@babel/plugin-transform-typescript: 7.20.13

### Possible solution

Insert
```
path.scope.registerDeclaration(path);
```
after this line:
https://github.com/babel/babel/blob/6e8ce9da64dbb2a9a572bef9ef9450cbd038aba3/packages/babel-plugin-transform-typescript/src/index.ts#L594

**Comment by nicolo-ribaudo** [comment] 2023-03-13 11:00
Thank you! I'm assigning this issue to you since you selected "Would you like to work on a fix?"

If it is the first time that you contribute to Babel, follow these steps: (you need to have `make` and `yarn` available on your machine)
1. Fork the repo
1. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
1. Run `yarn && make bootstrap`
1. Wait :hourglass_flowing_sand: 
1. Run `make watch` (or `make build` whenever you change a file)
1. Add a test in https://github.com/babel/babel/tree/main/packages/babel-plugin-transform-typescript/test. Testing this is a bit hard, maybe we could create a test with a custom `plugin.js` (like https://github.com/babel/babel/tree/main/packages/babel-plugin-transform-typescript/test/fixtures/regression/10162) which logs all the registered declaration on `Program:exit`, and with the `  "validateLogs": true` option enabled.
1. Update the code!
1. `yarn jest transform-typescript` to run the tests
    - If some test outputs don't match but the new results are correct, you can delete the bad `output.js` files and run the tests again
    - If you prefer, you can run `OVERWRITE=true yarn jest [name-of-the-package-to-test]` and they will be automatically updated.
1. If it is working, run `make test` to run all the tests
1. Run `git push` and open a PR!

Feel free to ask here if you need any other help :)

**Closed** 2023-03-14 13:55 UTC
Labels: i: bug, area: typescript
