### ISSUE TITLE
[flow] new and call expressions are not stripped in files where the `@flow` pragma isn't the first comment block

### ISSUE THREAD

**Issue by julienw** [babel/babel#9845] opened 2019-04-10 14:11 UTC
In #7934 the support for this new flow call type parameters has been implemented, but it was guarded by some check, namely that the file is actually checked by flow.
The problem is that the check doesn't work properly for us, where the `flow` pragma comes after a copyright comment, eg:
```js
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

// @flow

import * as React from 'react';
```

As a result the stripping behavior isn't triggered.

If possible, it would be much better to check other comments at the top of the file until the first code line.

Using babel 7.4.3.

**Comment by julienw** [comment] 2019-04-10 14:16
The code that does the check is https://github.com/babel/babel/pull/7934/files#diff-a739835084910b0ee3ea649df5a4d223R85

Likely `flowPragma` should be set to `null` only at the first non-comment "thing".

**Comment by nicolo-ribaudo** [comment] 2019-04-10 14:54
Is this a duplicate of https://github.com/babel/babel/issues/9240?

**Comment by julienw** [comment] 2019-04-10 15:17
Ah yes indeed, I believe it is a dupe of that issue.
I skimmed through the code but I have no idea of how to insert the code I have in mind. I don't know which method I should override, that would be called when it's _not_ a comment :)

**Closed** 2019-04-10 15:31 UTC
Labels: i: bug, i: needs triage
