### ISSUE TITLE
The transform-es2015-modules-commonjs plugin seems to be ignored in babel 6.1.2

### ISSUE THREAD

**Issue by jails** [babel/babel#2871] opened 2015-11-06 13:53 UTC
Using babel 6.1.2, the following js:

```js
export default {}
```

is transpiled to:

```js
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = {};
```

using the following command line

```bash
babel --presets es2015 --plugins transform-es2015-modules-commonjs test.js
```

However the output with the 5.x was:

```js
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports["default"] = {};
module.exports = exports["default"];
```

looks like `module.exports = exports["default"];` is missing although the `transform-es2015-modules-commonjs` is enabled.

Is it a bug or I'm missing something ?
Thank you !

**Comment by jmm** [comment] 2015-11-06 13:59
Hello @jails, welcome to the Babel community! This is a duplicate of #2724, #2679, and probably others. I don't know if it's properly documented, but that change is by design; see #2212.

**Closed by jmm** 2015-11-06 13:59 UTC

**Comment by jails** [comment] 2015-11-06 14:04
Ah gotcha, thank you @jmm.

**Comment by Kflash** [comment] 2015-11-11 01:25
@jails As a workaround, replace `export default { … }` with  `module.exports = { … }` and everything works as before.
