### ISSUE TITLE
Can't find symbol error

### ISSUE THREAD

**Issue by mfrye-intuit** [babel/babel#1679] opened 2015-06-03 20:13 UTC
having the same problem here but in Safari
https://github.com/babel/babel/issues/1574

**Comment by sebmck** [comment] 2015-06-03 20:14
Did you not look at what it was a duplicate of? Please see the link provided in #711. You need the a symbol polyfill for `for...of` as documented on the [caveats](http://babeljs.io/docs/advanced/caveats/) page. Babel includes a [polyfill](http://babeljs.io/docs/usage/polyfill/) by default that makes things a bit easier.

**Closed by sebmck** 2015-06-03 20:14 UTC
