### ISSUE TITLE
[Bug]:  TypeError: Cannot read property 'range' of null.  

### ISSUE THREAD

**Issue by xff1024** [babel/babel#14477] opened 2022-04-20 11:42 UTC
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/eslint-parser

### Input code

```js
//  "babel-eslint": "^10.0.3",
const asyncFn = () => {
    return new Promise((reslove) => {
        setTimeout(() => {
            reslove({
                code: 200,
                // The data may be null
                data: {
                    items: [],
                    total: '',
                }
            })
        })
    })
}

const getAsyncResult = async () => {
    const res = await asyncFn();
    if (res.code === 200 && res.data) {
        // The data may be null
       // ？with `${variable}`  must error 
        res?.data?.items?.forEach((item) => {
            item.name = `${item.otherName || 'test'}`
        })
    }
}

```

### Configuration file name

babel.config.js

### Current and expected behavior

I want to use chain operation to avoid errors

### Environment

- Babel version(s): [^10.0.3]
- Node: [v14.7.0]
- yarn version: [1.22.15]
- OS: [macOS 11.6.1]

**Comment by JLHwung** [comment] 2022-04-20 16:53
Duplicate of #10904.

> //  "babel-eslint": "^10.0.3",

Please migrate to `@babel/eslint-parser`.

**Closed** 2022-04-20 16:53 UTC
Labels: i: needs triage
