### ISSUE TITLE
Class declaration: Difference between implicit and explicit "extend Object" 

### ISSUE THREAD

**Issue by rickbeerendonk** [babel/babel#6146] opened 2017-08-22 20:37 UTC
### Bug

There is a difference between `class Base` and `class Base extends Object` that shouldn't be there.

Classes explicitly extending Object (and their subclasses) are always instances of Object and **are not instances of the respective classes**.

**Function calls fail** on classes explicitly extending Object (and their subclasses).

### Code demonstrating the differences between Babel & Node

Output of the console.log()'s are added as comments to the lines.

```js
class Base1 extends Object {
  constructor(name) {
    super();
    this.name = name;
  }
  getName() {
    return this.name;
  }
}

class Base2 {
  constructor(name) {
    this.name = name;
  }
  getName() {
    return this.name;
  }
}

let b = new Base1("name1");
                                   // --BABEL--                               // --NODE--
console.log(b instanceof Object);  // true                                    // true
console.log(b instanceof Base1);   // false                                   // true
console.log(b.constructor.name);   // Object                                  // Base1
console.log(b.getName());          // TypeError: b.getName is not a function  // name1
console.log(b);                    // { name: 'name1' }                       // Base1 { name: 'name1' }

console.log();

b = new Base2("name2");
                                   // --BABEL & NODE--
console.log(b instanceof Object);  // true
console.log(b instanceof Base2);   // true
console.log(b.constructor.name);   // Base2
console.log(b.getName());          // name2
console.log(b);                    // Base2 { name: 'name2' }
```

### Babel Configuration

.babelrc
```js
{
  "presets": ["es2015", "es2016", "es2017"]
}
```

package.json / cli command (file is in src folder and result in lib folder)
```js
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-es2016": "^6.24.1",
    "babel-preset-es2017": "^6.24.1"
  },
  "scripts": {
    "build": "babel src --out-dir lib",
    "watch": "babel src -w --out-dir lib"
  }
```
### Expected Behavior
There should be no difference between instances created with `class Base` and `class Base extends Object`.

### Current Behavior
`class Base` instances behave correctly.
`class Base extends Object` instances fail to implement functions and the correct type (constructor name, instanceof).

### Context
`class Base extends Object` is needed for [static type checker Flow](https://flow.org) to accept `obj['propName'] = 123`.

### Environment
| software         | version(s)
| ---------------- | -------
| Babel            | 6.26.0
| node             | 8.3.0
| npm              | 5.3.0
| Operating System | macOS 10.12 & Windows 10

**Comment by loganfsmyth** [comment] 2017-08-22 20:47
We currently document this in [the Caveats](https://babeljs.io/docs/usage/caveats/#classes) but subclassing builtin types is not currently something Babel supports.

**Comment by hzoo** [comment] 2017-08-22 20:49
Duplicate of https://github.com/babel/babel/issues/4480, can try https://github.com/WebReflection/babel-plugin-transform-builtin-classes

**Comment by rickbeerendonk** [comment] 2017-08-22 20:53
@loganfsmyth I've read that, but since Object wasn't explicitly mentioned (and is the most obvious build in type), I suspected it to be different.

@hzoo No, can't use [babel-plugin-transform-builtin-classes](https://github.com/WebReflection/babel-plugin-transform-builtin-classes), since [create-react-app](https://github.com/facebookincubator/create-react-app) doesn't allow users to change babel settings.

Conclusion: Don't combine Babel & [Flow](https://flow.org)... so forget about [create-react-app](https://github.com/facebookincubator/create-react-app) if you want static type checking in React.

**Comment by loganfsmyth** [comment] 2017-08-22 20:54
I will say, I've never even heard that Flow allowed dictionary-like lookups on classes. Are you sure that behavior is something they explicitly support? To be it screams of the class itself being strangely architected.

**Comment by rickbeerendonk** [comment] 2017-08-22 20:57
Flow doesn't complain about the dictionary like syntax if you use `extends Object` explicitly, otherwise Flow demands you explicitly implement the dictionary while it is already working out of the box. Weird, but true.

**Comment by loganfsmyth** [comment] 2017-08-22 21:03
Yeah I'm saying I wonder if `extends Object`'s behavior is a bug in Flow, or an explicit feature. It seems like a strange behavior since it's essentially letting you have properties on your class that could be overridden be dictionary properties on accident.

@samwgoldman Is this something we should be trying to handle?

**Comment by hzoo** [comment] 2017-08-31 18:55
Going to close for now

**Closed by hzoo** 2017-08-31 18:55 UTC
