### ISSUE TITLE
[Bug]: Syntax error when arrow function is given to Function.call

### ISSUE THREAD

**Issue by p51lee** [babel/babel#15131] opened 2022-11-04 19:26 UTC
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```js
Function . call ( 0 , x => 0 ) ;
```

### Current and expected behavior

`input.js` terminates normally:
```console
$ node input.js # no error

```

However, `output.js` throws `SyntaxError`:
```console
$ node output.js
undefined:3
function (x) {
^^^^^^^^

SyntaxError: Function statements require a function name
    at Number.Function (<anonymous>)
    at Object.<anonymous> output.js:1:10)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.11.0
```

### Environment

[Reproduction on Babel's own REPL](https://babeljs.io/repl#?browsers=since%202015&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=GIVwdgxgLglg9mABAOkRAhgG04gFIgBkQBpEAPRAXgD5DEBKRAbiA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=script&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.20.1&externalPlugins=&assumptions=%7B%7D)

**Comment by nicolo-ribaudo** [comment] 2022-11-08 14:44
I cannot reproduce this. In the linked repl I see this output:
```js
Function.call(0, function (x) {
  return 0;
});
```
that does not contain any function statements.

**Comment by liuxingbaoyu** [comment] 2022-11-08 14:46
I can reproduce this, but I don't know how to fix it. `new Funtion` seems to be constructed using `(function(){})+'''`. And we can't guarantee `func.toString`.

**Comment by nicolo-ribaudo** [comment] 2022-11-08 14:48
Oh thank you, I have to _evaluate_ the generated code. Yeah, maintaining the original `.toString` for functions is out of scope.

**Closed by nicolo-ribaudo** 2022-11-08 14:48 UTC
Labels: i: bug
