### ISSUE TITLE
Bluebird coroutines should also stub the global Promise (runtime transformer)

### ISSUE THREAD

**Issue by nevir** [babel/babel#2512] opened 2015-10-09 02:01 UTC
Currently, the bluebird coroutines transformer only swaps out coroutine usage (as its name implies). Ideally, this transformer's scope should also include replacing the runtime transformer's Promise implementation with Bluebird, too. 

Having the two Promise implementations leads to very confusing situations, primarily due to `Promise.cast()` comparing prototypes and not the shape of the object. For example:

```js
function bar() {
  return Promise.resolve(true);
}

async function foo() {
  return bar();
}

foo(); // Returns BluebirdPromise<CoreJSPromise<true>>!!
```

**Comment by nevir** [comment] 2015-10-09 02:03
My current workaround is this (avoiding the bluebird coroutine transformer all together):

```js
let Bluebird = require('bluebird');
// NOTE: You CANNOT rely on this in any file that imports boot! Babel grabs a
// reference to Promise _before_ any imports occur.
require('babel-runtime/core-js/promise').default = Bluebird;
// Just in case.
global.Promise = Bluebird;
```

Downside to this approach is that you _cannot_ reference Promises or async functions in any file that executes this code (Babel will grab a reference before evaluating it, or imports of it)

**Comment by loganfsmyth** [comment] 2015-10-09 02:55
If you are using Bluebird, why are you using the global `Promise` at all? If you did

```
import Bluebird from 'bluebird';

function bar() {
  return Bluebird.resolve(true);
}
```

and were using runtime, you wouldn't get any ES6 polyfill. It's also not clean why `Returns BluebirdPromise<CoreJSPromise<true>>` would be an issue.

**Comment by sebmck** [comment] 2015-10-09 02:57
I'm confused by why you think the `bluebirdCoroutines` transformer should do anything more than what it says on the tin. You explicitly point that out so I'm not sure what there is to discuss?

**Comment by nevir** [comment] 2015-10-09 02:59
I'm suggesting that there either be another transformer to tackle the runtime Promise (`bluebirdRuntime` transformer?), or that there be a combined `bluebird` transformer that does both

**Comment by nevir** [comment] 2015-10-09 02:59
Sometimes I'm interoperating with other libraries that assume a global `Promise` (for example, react-native libraries)

> It's also not clean why Returns BluebirdPromise<CoreJSPromise<true>> would be an issue.

The reason that's an issue is that it's not expected behavior. In a world where there's only one promise implementation (bluebird or core-js or native):

```js
function bar() {
  return Promise.resolve(true);
}

async function foo() {
  return bar();
}

foo(); // Returns Promise<true>!!
```

Note that the async function is implicitly calling `Promise.cast`, which just bumps the resolved promise straight out - it's not wrapped

**Comment by loganfsmyth** [comment] 2015-10-09 03:50
```
async function foo() {
  return Promise.resolve(true);
}

foo().then(result => console.log(result));
```

logs `true` for me when I run

   ./node_modules/.bin/babel-node --optional bluebirdCoroutines,runtime tmp.js

which is what I'd expect. Are you saying you are seeing that log the actual promise object? async functions are supposed to automatically wrap any thenables to their values.

**Comment by nevir** [comment] 2015-10-09 04:05
> Are you saying you are seeing that log the actual promise object?

Yeah, that's what I'm seeing - but I can also replicate your example, so now I'm really confused :-/  Going to dig around my environment to see where it differs...

**Comment by loganfsmyth** [comment] 2015-10-11 05:10
Any luck reproducing your issue on a smaller scale? As it is, this doesn't seem actionable since the two promise implementations _should_ work together properly, and if you are using `runtime`, native promises will only be used if your code uses them instead of Bluebird.

**Comment by thejameskyle** [comment] 2015-10-12 04:21
Trying to understand this. You're suggesting a `bluebird` transformer that turns `Promise` into `Bluebird` like this?

```js
Promise.resolve();
// to:
import BluebirdPromise from 'bluebird';
BluebirdPromise.resolve();
```

**Comment by callumlocke** [comment] 2015-10-12 17:19
Using `instanceof Promise` is just bad code. Promises are a spec to implement. The whole point is that multiple implementations can exist in harmony and talk to each other.

This is what `Promise.resolve()` is for. It takes any value or thenable (doesn't care which implementation) and returns a promise in *your* implementation.

I definitely would not want this Babel transformer modifying the global Promise in my environment.

**Comment by loganfsmyth** [comment] 2015-10-13 02:43
@thejameskyle Or at least inject `import Promise from 'bluebird';` instead, but that doesn't sound realistic to me. I feel like we should close this since I don't think the transform part is a good idea for core, but I was hoping to make sure there isn't some bug somewhere causing the wrapping @nevir was seeing.

**Comment by sebmck** [comment] 2015-10-13 02:45
Agree with @loganfsmyth. In 6.0 there will be no `bluebirdCoroutines` transformer and instead a more generic one so you can just do:

**.babelrc**

```json
{
  "plugins: [["async-to-generator-something", { "module": "bluebird", "method": "coroutine" }]]
}
```

or something.

**Closed by sebmck** 2015-10-13 02:45 UTC
