### ISSUE TITLE
Class decorator and computed property keys

### ISSUE THREAD

**Issue by otakustay** [babel/babel#1645] opened 2015-05-29 05:59 UTC
Babel encounters an error when I put a decorator on a class method with computed key:

```js
let foo = () => {
}

class Custom {
    @foo
    ['foo' + 'bar'](e) {
    }
}

// repl: Unexpected token (6:23)
```

I think it should be OK when decorators are used on computed property keys, the `key` argument in decorator factory should be the computed value

**Comment by otakustay** [comment] 2015-05-29 06:22
In a further study, I find when `@foo` is replaced to `@foo;`, it works

I think the `;` mark should be a grammar error?

**Comment by sebmck** [comment] 2015-05-29 12:46
Duplicate of #1238. Known issue, see wycats/javascript-decorators#10. Unfortunately, this is how the grammar is defined.

**Closed by sebmck** 2015-05-29 12:46 UTC
