### ISSUE TITLE
'this' is not allowed before super() error when using class properties with "this"

### ISSUE THREAD

**Issue by smussell** [babel/babel#3028] opened 2015-11-12 22:34 UTC
I am getting the following 

```
ERROR in ./src/main.jsx
Module build failed: SyntaxError: /Users/sam/src/main.jsx: 'this' is not allowed before super() (This is an error on an internal node. Probably an internal error)
    at File.buildCodeFrameError (/Users/sam/node_modules/@apple/reviz-dev/node_modules/babel-core/lib/transformation/file/index.js:408:15)
    at NodePath.buildCodeFrameError (/Users/sam/node_modules/@apple/reviz-dev/node_modules/babel-core/node_modules/babel-traverse/lib/path/index.js:143:26)
    at ThisExpression (/Users/sam/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-classes/lib/vanilla.js:73:20)
```

When I try to compile the following:

```
import React from 'react';
import ReactDOM from 'react-dom';

class Main extends React.Component {
  constructor() {
    super();
    this.state = {};
  }
  
  myHandler = () => {
    this.setState({newState: true});
  };

  render() {
    return (
        <div></div>
    );
  }
}
```

It is only failing when I include `this` inside the myHandler function.  There have been several issues similar to this, I had hoped this would resolve when #2942 was closed, but I'm still seeing it in the latest 6.1.19.

My babel settings look like:

```
        loader: 'babel-loader',
        query: {
          presets: ['es2015', 'stage-0', 'react']
        }
```

**Comment by yannispanousis** [comment] 2015-11-13 00:47
Seeing this as well, but only tested 6.1.18

**Comment by tleunen** [comment] 2015-11-13 01:02
Same thing.
this issue #2809 was closed in favor of this one #2774 and then closed for this one #2942 (which was another issue actually), therefore we still have the initial issue in Babel :/

**Comment by RussTheAerialist** [comment] 2015-11-13 02:41
I have a repro case against 6.1.19 that happens even without using this at all in the derived class.

```
// base class
export default class SimpleEvent {
  constructor () {
    this._callbacks = {}
  }

  on (event, callback) {
    if (!(event in this._callbacks)) {
      this._callbacks[event] = []
    }

    this._callbacks[event].push(callback)
  }

  hasEvent (event) {
    return event in this._callbacks
  }

  emit (event, ...args) {
    if (event in this._callbacks) {
      for (var callback of this._callbacks[event]) {
        callback(...args)
      }
    }
  }
}
```

```
// Derived Class
import SimpleEvent from '../simple-event-handler/index.js'

export default class Muscle extends SimpleEvent {
  constructor (sensor) {
    super()
  }
}
```

**Comment by phyllisstein** [comment] 2015-11-13 05:01
Just to amplify @smussell's observation a bit, I get a similar error when I don't explicitly create a constructor function:

```jsx
class Picker extends React.Component {
  goToStore = (e) => {
    e.preventDefault();
    console.log(this.refs.storeId.value);
  }

  render() {
    return (
      <form onSubmit={ this.goToStore }>
        <label>
          Whatchoo Want
          <input id="storeId" type="text" ref="storeId" defaultValue={ name({ words: 4 }).dashed } required />
        </label>
        <input type="submit" />
      </form>
    );
  }
}
```

Running that through Babel returns another `this`-before-`super` error, with the following traceback:

```
SyntaxError:
/Users/phyllisstein/Repos/Personal/React/src/app/application.es6:
'this' is not allowed before super() (This is an error on an internal node. Probably an internal error)
    at File.buildCodeFrameError (/Users/phyllisstein/Repos/Personal/React/node_modules/babel-core/lib/transformation/file/index.js:408:15)
    at NodePath.buildCodeFrameError (/Users/phyllisstein/Repos/Personal/React/node_modules/babel-traverse/lib/path/index.js:143:26)
    at [object Object].ThisExpression (/Users/phyllisstein/Repos/Personal/React/node_modules/babel-plugin-transform-es2015-classes/lib/vanilla.js:73:20)
    at NodePath._call (/Users/phyllisstein/Repos/Personal/React/node_modules/babel-traverse/lib/path/context.js:72:18)
    at NodePath.call (/Users/phyllisstein/Repos/Personal/React/node_modules/babel-traverse/lib/path/context.js:44:17)
    at NodePath.visit (/Users/phyllisstein/Repos/Personal/React/node_modules/babel-traverse/lib/path/context.js:102:12)
    at TraversalContext.visitQueue (/Users/phyllisstein/Repos/Personal/React/node_modules/babel-traverse/lib/context.js:151:16)
    at TraversalContext.visitSingle (/Users/phyllisstein/Repos/Personal/React/node_modules/babel-traverse/lib/context.js:111:19)
    at TraversalContext.visit (/Users/phyllisstein/Repos/Personal/React/node_modules/babel-traverse/lib/context.js:195:19)
    at Function.traverse.node (/Users/phyllisstein/Repos/Personal/React/node_modules/babel-traverse/lib/index.js:141:17)
    at NodePath.visit (/Users/phyllisstein/Repos/Personal/React/node_modules/babel-traverse/lib/path/context.js:106:22)
    at TraversalContext.visitQueue (/Users/phyllisstein/Repos/Personal/React/node_modules/babel-traverse/lib/context.js:151:16)
    at TraversalContext.visitMultiple (/Users/phyllisstein/Repos/Personal/React/node_modules/babel-traverse/lib/context.js:106:17)
    at TraversalContext.visit (/Users/phyllisstein/Repos/Personal/React/node_modules/babel-traverse/lib/context.js:193:19)
    at Function.traverse.node (/Users/phyllisstein/Repos/Personal/React/node_modules/babel-traverse/lib/index.js:141:17)
    at NodePath.visit (/Users/phyllisstein/Repos/Personal/React/node_modules/babel-traverse/lib/path/context.js:106:22)
    at TraversalContext.visitQueue (/Users/phyllisstein/Repos/Personal/React/node_modules/babel-traverse/lib/context.js:151:16)
```

Here's my `.babelrc`, if that's helpful:

```json
{
  "presets": [
    "react",
    "stage-0",
    "es2015"
  ],
  "plugins": [
    "transform-class-properties"
  ]
}
```

Thanks for looking into this, and good luck!

**Comment by sebmck** [comment] 2015-11-13 05:56
@phyllisstein Looks to be the exact same issue I just fixed. Can you blow away your entire `node_modules` and reinstall and then try it?

**Comment by rygine** [comment] 2015-11-13 07:10
Interestingly, I'm also getting this when running tests through `babel-tape-runner@1.3.0`, but not with `babel-cli@6.1.4`

Here's my basic class export that's generating the error:

Navigation.js
```javascript
import React, { Component } from 'react';

export default class Navigation extends Component {

  render() {
    return (
      <nav className='navbar navbar-default navbar-static-top'>
      </nav>
    );
  }

}
```

Here's the error log:

```
> babel-tape-runner tests/*-test.js | faucet

<hidden>/node_modules/babel-core/lib/transformation/file/index.js:541
      throw err;
      ^

SyntaxError: <hidden>/src/components/Navigation.js: 'this' is not allowed before super() (This is an error on an internal node. Probably an internal error)
    at File.buildCodeFrameError (<hidden>/node_modules/babel-core/lib/transformation/file/index.js:408:15)
    at NodePath.buildCodeFrameError (<hidden>/node_modules/babel-traverse/lib/path/index.js:143:26)
    at [object Object].ThisExpression (<hidden>/node_modules/babel-plugin-transform-es2015-classes/lib/vanilla.js:73:20)
    at NodePath._call (<hidden>/node_modules/babel-traverse/lib/path/context.js:72:18)
    at NodePath.call (<hidden>/node_modules/babel-traverse/lib/path/context.js:44:17)
    at NodePath.visit (<hidden>/node_modules/babel-traverse/lib/path/context.js:102:12)
    at TraversalContext.visitQueue (<hidden>/node_modules/babel-traverse/lib/context.js:151:16)
    at TraversalContext.visitMultiple (<hidden>/node_modules/babel-traverse/lib/context.js:106:17)
    at TraversalContext.visit (<hidden>/node_modules/babel-traverse/lib/context.js:193:19)
    at Function.traverse.node (<hidden>/node_modules/babel-traverse/lib/index.js:141:17)
```

**Comment by phyllisstein** [comment] 2015-11-13 07:18
@sebmck Same result, I'm afraid: identical error and identical stacktrace, with both `babel-loader#develop` and `babel-cli@6.1.8`. Let me know if I can provide more useful debugging info---not totally sure where to start with Babel's deep magic.

**Comment by julienvincent** [comment] 2015-11-13 08:06
@sebmck A previously open issue of this problem - [#2971](https://github.com/babel/babel/issues/2971) - was mistakenly marked as duplicate of [#2942](https://github.com/babel/babel/issues/2942) which is what you fixed in `6.1.18`.

**Comment by sebmck** [comment] 2015-11-13 09:16
I've fixed multiple bugs that people have reported over multiple versions.
People likely have stale versions and I will need a repro repo with a clean
node_modules directory with all the latest packages.

On Fri, Nov 13, 2015 at 12:07 AM, Julien Vincent <notifications@github.com>
wrote:

> @sebmck <https://github.com/sebmck> A previously open issue of this
> problem - #2971 <https://github.com/babel/babel/issues/2971> - was
> mistakenly marked as duplicate of #2942
> <https://github.com/babel/babel/issues/2942> which is what you fixed in
> 6.1.18.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/3028#issuecomment-156358288>.
>



-- 
Sebastian McKenzie

**Comment by julienvincent** [comment] 2015-11-13 10:00
@sebmck Here you go - https://github.com/julienvincent/scoped-function-babel-bug

**Comment by AJIh** [comment] 2015-11-13 10:23
+1. On 6.1.18

**Comment by ovaris** [comment] 2015-11-13 10:25
I think this is same as https://github.com/babel/babel/issues/2694

**Comment by sebmck** [comment] 2015-11-13 10:43
Thanks @julienvincent! I can reproduce now.

**Closed** 2015-11-13 11:37 UTC

**Comment by tleunen** [comment] 2015-11-15 20:08
Hey @sebmck, I still have the issue with 6.1.21.
```js
class Tab extends React.Component {
    constructor(props) {
        super(props);
    }
    a = () => {
        this.a = {}
    }
}
```

**Comment by goffreder** [comment] 2015-11-15 22:21
Same issue as @tleunen.

My webpack.config:
```
loaders: [{
    test: /\.jsx?$/,
    exclude: /node_modules[\/\\]/,
    loader: 'babel',
    query: {
        cacheDirectory: true,
        presets: ['es2015', 'react', 'stage-0']
    }
}
```

My package.json:
```
"babel-core": "^6.1.21",
"babel-loader": "^6.1.0",
"babel-preset-es2015": "^6.1.18",
"babel-preset-react": "^6.1.18",
"babel-preset-stage-0": "^6.1.18",
```
