### ISSUE TITLE
fail to parse decorator with computed name in class

### ISSUE THREAD

**Issue by laysent** [babel/babel#10978] opened 2020-01-10 06:41 UTC
## Bug Report

- [x] I would like to work on a fix!

**Current Behavior**

Babel is throwing syntax error (`Unexpected token`) when parsing decorator (legacy mode) with computed class property.

**Input Code**
```js
class Example {
  @computed ['name'] = 1;
}
```

**Expected behavior/code**

Babel should parse the above code without throwing out syntax error.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
module.exports = env => ({
  "presets": [
    "@babel/preset-env",
    "@babel/preset-typescript",
    "@babel/preset-react"
  ],
  "plugins": [
    ["@babel/plugin-proposal-decorators", {
      "legacy": true
    }],
    ["@babel/plugin-proposal-class-properties", {
      "loose": true
    }],
  ],
  "sourceMaps": true
});
```

**Environment**

- Babel version(s): v7.7.7
- Node/npm version: Node v10.16.0 / npm 6.9.0
- OS: OSX 10.14.6
- Monorepo: no
- How you are using Babel: `cli`, `loader`

It also fails on online demo (try [here](https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAECiAeYC2AHEBTaBvAUNaAAsAPaoCuALugCbQDaA5AHbLoMC60AvNAIwDcOAL5A&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2017%2Cstage-2&prettier=false&targets=&version=7.7.7&externalPlugins=))

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by nicolo-ribaudo** [comment] 2020-01-10 11:12
The problem is that they are ambiguous:
```js
class A {
  @computed["name"]
  foo
}
```

Am I decorating the `name` field with `@computed`, or the field `foo` with `@computed["name"]`?

A decision had to be made, and it was decided that `[...]` are part of the decorator.

**Comment by JLHwung** [comment] 2020-01-10 14:57
Closing this as it works as expected.

**Closed by JLHwung** 2020-01-10 14:57 UTC
Labels: i: invalid
