### ISSUE TITLE
babel-plugin-transform-runtime: ability to select what to polyfill?

### ISSUE THREAD

**Issue by olalonde** [babel/babel#4505] opened 2016-09-12 04:39 UTC
In Node v6, most polyfills provided by `babel-plugin-transform-runtime` are unnecessary. It would be nice if there could be an option to specify what needs to be polyfilled (e.g. only `Object.entries`).

**Comment by hzoo** [comment] 2016-09-12 12:24
Yeah for sure, I'm not sure if we already made an issue for this but it was brought up and it is our intention to do so. At least https://github.com/babel/notes/issues/4

At a minimum be able to specify the year. (same with the polyfill). Otherwise you can polyfill: false but that's everything

**Comment by a324539017** [comment] 2016-09-23 03:28
+1

**Comment by motiz88** [comment] 2016-10-05 07:05
There's some discussion in #3934 too.

**Comment by schmod** [comment] 2016-10-05 15:00
This also likely has synergies with https://github.com/babel/babel-preset-env (although I think this is mostly a dupe of #3934)

**Comment by hzoo** [comment] 2016-10-05 15:01
I think we can probably consolidate these issues

**Comment by hzoo** [comment] 2016-10-08 03:48
Ok lets move this into #3934 - basically the same ask (don't make polyfill/runtime an all for one thing)

**Closed by hzoo** 2016-10-08 03:48 UTC
Labels: enhancement
