### ISSUE TITLE
transform-async-generator-functions returns iterator without self reference

### ISSUE THREAD

**Issue by prezmo** [babel/babel#5893] opened 2017-06-28 04:51 UTC
I was playing with this plugin a bit and found that when I'm trying to use async generator with async iterator code like this:
```
async function* chunks(it, size) {
  let buffer = [];
  for await (let v of it) {
    buffer.push(v);
    if (buffer.length === size) {
      yield buffer;
      buffer = [];
    }
  }
  if (buffer.length > 0) yield buffer;
}
```
and than use it with async iterator function, like this:
```
async function forEach(it, f) {
  for await (let v of it) f(v);
}

const chunksIter = chunks([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 3);
var output = [];
forEach(chunksIter, function (val) {
    output.push(val)
  })
  .then(function () {
    console.log(output);
  });
```
I'm getting error saying that it[Symbol.iterator] is not a function. Not sure about spec, but it seems to me that all iterators should return itself when when passed to iterable consumer, like Array iterator does:
```
const arr = []
const arrIter = arr[Symbol.iterator]()
console.log(arrIter === arrIter[Symbol.iterator]()) //true
```

**Comment by jridgewell** [comment] 2017-07-04 04:31
This works on repl. Did you import the symbol polyfill?

**Comment by patrickhulce** [comment] 2017-08-03 01:32
I'm also experiencing this issue, and I've found a solution, but there's still a bug to be fixed here.

The issue is that the `_asyncGenerator` definition is hoisted above everything else in the file, including the `require('babel-polyfill')`, when it needs to be required before hand (all you need for this too btw is `require('core-js/es7/symbol')`).

The fix was to simply add a new file entry.js that does a `require('babel-polyfill'); require('./real-entry.js')`

**Comment by jridgewell** [comment] 2017-08-08 01:27
Ahh, that explains it. Closing for https://github.com/facebook/regenerator/issues/304.

**Closed by jridgewell** 2017-08-08 01:27 UTC
Labels: awaiting reply
