### ISSUE TITLE
Typescript - Unexpected token, expected ";"

### ISSUE THREAD

**Issue by CloudRex** [babel/babel#8116] opened 2018-06-05 00:24 UTC
## Bug Report

**Current Behavior**
Failing to compile correct code

**Input Code**
- REPL or Repo link if applicable:

```ts
import {NetworkListenerEvent} from "../listeners/network-listener";

export enum NetworkControllerEnvironment {
    Unicast,
    Multicast,
    Broadcast,
    All
}

export default interface NetworkController {
    readonly endpoint: string;
    readonly environment: NetworkControllerEnvironment;
    readonly handle: (event: NetworkListenerEvent) => void;
}
```

**Expected behavior/code**
Compile successfully

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
    "presets": [
        "@babel/env",
        "@babel/typescript"
    ],
    "plugins": [
        "@babel/proposal-class-properties",
        "@babel/proposal-object-rest-spread"
    ]
}
```

**Environment**
- Babel version(s): v7.0.0-beta.49
- Node/npm version: 5.6.0
- OS: Windows 10
- Monorepo: no
- How you are using Babel: cli

**Possible Solution**

**Additional context/Screenshots**
Stack trace:
```
$ tsc --emitDeclarationOnly && babel src --out-dir lib --extensions ".ts,.tsx"
{ SyntaxError: D:\Projects\local-network\src\core\network-controller.ts: Unexpected token, expected ";" (10:25)

   8 | }
   9 |
> 10 | export default interface NetworkController {
     |                          ^
  11 |     readonly endpoint: string;
  12 |     readonly environment: NetworkControllerEnvironment;
  13 |     readonly handle: (event: NetworkListenerEvent) => void;
    at _class.raise (D:\Projects\local-network\node_modules\@babel\parser\lib\index.js:3861:15)
    at _class.unexpected (D:\Projects\local-network\node_modules\@babel\parser\lib\index.js:5190:16)
    at _class.semicolon (D:\Projects\local-network\node_modules\@babel\parser\lib\index.js:5174:40)
    at _class.parseExportDefaultExpression (D:\Projects\local-network\node_modules\@babel\parser\lib\index.js:8149:12
)
    at _class.parseExportDefaultExpression (D:\Projects\local-network\node_modules\@babel\parser\lib\index.js:9801:65
)
    at _class.parseExport (D:\Projects\local-network\node_modules\@babel\parser\lib\index.js:8102:31)
    at _class.parseExport (D:\Projects\local-network\node_modules\@babel\parser\lib\index.js:9784:50)
    at _class.parseStatementContent (D:\Projects\local-network\node_modules\@babel\parser\lib\index.js:7172:27)
    at _class.parseStatementContent (D:\Projects\local-network\node_modules\@babel\parser\lib\index.js:9816:58)
    at _class.parseStatement (D:\Projects\local-network\node_modules\@babel\parser\lib\index.js:7085:17)
  pos: 200,
  loc: Position { line: 10, column: 25 },
  code: 'BABEL_PARSE_ERROR' }
```

**Comment by existentialism** [comment] 2018-06-05 01:17
@CloudRex thanks for the issue. This looks like a duplicate of https://github.com/babel/babel/issues/7118?

**Closed by existentialism** 2018-06-05 01:17 UTC
