### ISSUE TITLE
Failed to transform decorators with babel-plugin-transform-decorators@6.0.14

### ISSUE THREAD

**Issue by soulwu** [babel/babel#2801] opened 2015-11-04 03:25 UTC
source code `test.js` as below:
```js
function testable(target) {
  target.isTestable = true;
}

@testable
class MyTestableClass {}
```

and with `.babelrc`
```json
{
	"presets": ["es2015", "stage-0"]
}
```

When run babel, failed
```bash
$ babel test.js
TypeError: test.js: Property right of AssignmentExpression expected node to be of a type ["Expression"] but instead got "Decorator"
    at Object.validate (/Users/soulwu/test/node_modules/babel-types/lib/definitions/index.js:99:13)
    at validate (/Users/soulwu/test/node_modules/babel-types/lib/index.js:295:9)
    at Object.builder (/Users/soulwu/test/node_modules/babel-types/lib/index.js:248:7)
    at maybeMemoise (/Users/soulwu/test/node_modules/babel-helper-explode-class/lib/index.js:29:32)
    at memoiseDecorators (/Users/soulwu/test/node_modules/babel-helper-explode-class/lib/index.js:56:7)
    at Object.exports.default (/Users/soulwu/test/node_modules/babel-helper-explode-class/lib/index.js:61:3)
    at PluginPass.ClassDeclaration (/Users/soulwu/test/node_modules/babel-plugin-transform-decorators/lib/index.js:164:45)
    at /usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/visitors.js:271:19
    at NodePath._call (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/path/context.js:72:18)
    at NodePath.call (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/path/context.js:44:17)
```

need help...

**Comment by kstevens715** [comment] 2015-11-04 04:14
I've been having the same problem tonight.

**Comment by loganfsmyth** [comment] 2015-11-04 04:17
This looks like a duplicate of https://github.com/babel/babel/issues/2645

**Closed by loganfsmyth** 2015-11-04 04:17 UTC

**Comment by kritollm** [comment] 2015-11-04 23:45
Why close it when so many have the same problem, the other issue is closed for comments. Must be a bug or a very bad documented breaking change.
