### ISSUE TITLE
[parse error] Flow polymorphic arrow function causes parse error

### ISSUE THREAD

**Issue by jaredly** [babel/babel#2520] opened 2015-10-10 23:06 UTC
This fails to parse under babel, but correctly typechecks under flow:
```js
const fn = <T>(arg: T): Promise<T> => {
  return Promise.resolve(arg);
}
```
The error is:
```
repl: Unexpected token (4:2)
  2 | 
  3 | const fn = <T>(arg: T): Promise<T> => {
> 4 |   return Promise.resolve(arg);
    |   ^
  5 | }
```

This parses fine, though:
```js
const fn = function <T>(arg: T): Promise<T> {
  return Promise.resolve(arg);
}
```

**Comment by loganfsmyth** [comment] 2015-10-10 23:25
Dupe of https://github.com/babel/babel/issues/2400

**Closed by loganfsmyth** 2015-10-10 23:25 UTC
