### ISSUE TITLE
[@babel/core] Bug: “TypeError: Iterator result false is not an object” in Node 6 --harmony

### ISSUE THREAD

**Issue by GeoffreyBooth** [babel/babel#11226] opened 2020-03-10 06:38 UTC
## Bug Report

- [ ] I would like to work on a fix!

**Current Behavior**

In Node 6 running under `--harmony`, Babel’s `transform` throws `TypeError: Iterator result false is not an object`.

**Input Code**

You can reproduce the error with the following one-liner, assuming you have [Docker](https://docs.docker.com/install/) installed:

```shell
docker run --rm node:6-alpine sh -c \
  "npm install @babel/core@7.8.7 && node --harmony --eval \"require('@babel/core').transform('')\""
```

The error is present for Babel 7.8.0 and above. If you change the version in the above one-liner to 7.7.7, the command doesn’t error.

**Expected behavior/code**

No error.

**Actual behavior**

Output from above command (abbreviated):

```
/node_modules/@babel/core/lib/config/caching.js:57
    const asyncContext = yield* (0, _async.isAsync)();
                                                   ^
TypeError: Iterator result false is not an object
    at cachedFunction (/node_modules/@babel/core/lib/config/caching.js:57:52)
```

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**

None

**Environment**

- Babel version(s): 7.8.7
- Node/npm version: Node 6 `--harmony`
- OS: Linux

**Additional context/Screenshots**

I stumbled across this because I’m the maintainer of CoffeeScript, and our CI started failing after the release of Babel 7.8.0 because we run our test suite in Node 6 both normally and under `--harmony`. You can see the errors yourself with the following one-liner:

```shell
docker run --rm node:6 sh -c \
  "git clone --depth=1 https://github.com/jashkenas/coffeescript.git && cd coffeescript && npm install && node --harmony ./bin/cake test"
```

I understand that Node 6 has passed end-of-life, but I’m hoping to continue to support it until I _need_ to drop it; and per [this](https://babeljs.io/docs/en/v7-migration) it seems that Babel 7 still supports Node 6 as well.

**Comment by JLHwung** [comment] 2020-03-10 16:13
@GeoffreyBooth Thanks for the report. The issue is an upstream one (all the way up to V8), please refer to https://github.com/loganfsmyth/gensync/issues/4 for more details.

As a workaround, please explicitly enable the harmony toggles you need _except_ `harmony_tailcalls`. This toggle has been removed since node.js 8 so 8+ are not affected.

Note that `harmony_shipping` is enabled by default and Babel 7 still supports `node >= 6.9`, so you may also consider just removing the `--harmony` toggle.

I am gonna close this issue as it is an upstream one and relates to a removed V8 features.

**Closed by JLHwung** 2020-03-10 16:13 UTC
Labels: i: bug, i: regression

**Comment by GeoffreyBooth** [comment] 2020-03-10 17:00
In the meantime you might want to consider simply checking for Node version < 8 and `--harmony` and printing an error that `--harmony` mode is unsupported in Node < 8. This error is _always_ thrown in such a situation, as it throws for `transform('')`.
