### ISSUE TITLE
Bug: switch statements containing closures are broken

### ISSUE THREAD

**Issue by mbostock** [babel/babel#11800] opened 2020-07-07 00:59 UTC
## Bug Report

**Current behavior**
Switch statements containing closures are generating broken code causing adjacent cases to run. See this minimal reproduction with the default settings:

https://babeljs.io/en/repl#?browsers=defaults&build=&builtIns=false&spec=false&loose=false&code_lz=GYewTgBAFAxiB2BnALhAhhEwIG0CMAugJQQDeAUBBIgO4CWyMAFtMmAK4CmJFVVMaRJwhsuALjKU-_BCggAjCAF4IeANxTpUEkoB8CjdKp1sUUdwVhOaANaGjceMjrwu9qgF9NEAUIjA0ABshCV4jZCYwEBoIeE4YgFEwKLAoACJ2eCs0ZjR5QM40oncIL09yLyA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2%2Cenv&prettier=false&targets=&version=7.10.4&externalPlugins=

**Input Code**

```js
for (const a of [1]) {
  switch (true) {
    case true: {
      const b = 1;
      () => b;
      if (true) break;
      continue;
    }
    case false: {
      throw new Error("unreachable");
    }
  }
}
```

**Output Code**

```js
for (var _i = 0, _arr = [1]; _i < _arr.length; _i++) {
  var a = _arr[_i];

  switch (true) {
    case true:
      {
        var _ret = function () {
          var b = 1;

          (function () {
            return b;
          });

          if (true) return "break";
          return "continue";
        }();

        switch (_ret) {
          case "break":
            break;

          case "continue":
            continue;
        }
      }

    case false:
      {
        throw new Error("unreachable");
      }
  }
}
```

**Expected behavior**
No error is thrown (the break statement functions as intended, and the false case does not run).

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
Defaults. See the REPL.

**Environment**
Defaults. See the REPL.

**Possible Solution**
If you want to use a `break` statement here, it needs to be a labeled break to break the outer loop.

```js
switch (_ret) {
  case "break":
    break outer;

  case "continue":
    continue;
}
```

Alternatively, use an if instead of a nested switch.

```js
if (_ret === "break") break;
if (_ret === "continue") continue;
```

**Comment by Andarist** [comment] 2020-07-07 07:40
Thanks for the report! I'm marking this as "help wanted" - maybe some volunteer will jump into fixing this before the core team manages to do it. I believe the solution using `if` statements seems like the easier one.

**Comment by JLHwung** [comment] 2020-07-07 18:49
Duplicate of #11690

**Closed** 2020-07-07 22:38 UTC
Labels: Has PR, i: bug

**Comment by hzoo** [comment] 2020-07-08 03:56
Thanks for the report and suggested fix @mbostock!
