### ISSUE TITLE
Importing + Destructuring ES6 Module default export does not work

### ISSUE THREAD

**Issue by joshacheson** [babel/babel#3049] opened 2015-11-13 19:23 UTC
```
//moduleA.js
export default {
  foo: 'bar'
}
```

```
//moduleB.js
import { foo } from './moduleA';

const something = foo.baz;
```

Unfortunately the compiled code does not reference `default` at all, so i end up looking at `moduleA.foo.baz` instead of `moduleA.default.foo.baz`. I have noticed that `interopRequireDefault` is not used in this case (not sure what triggers the use of this helper, but it seems like I would want it to apply here).

Here is the query I pass to babel for refernece:

```
            query: {
                'presets': [
                    'react'
                ],
                'plugins': [
                    'transform-proto-to-assign',
                    'syntax-object-rest-spread',
                    'transform-object-rest-spread',
                    'babel-plugin-transform-es2015-arrow-functions',
                    'babel-plugin-transform-es2015-block-scoped-functions',
                    'babel-plugin-transform-es2015-block-scoping',
                    'babel-plugin-transform-es2015-computed-properties',
                    'babel-plugin-transform-es2015-destructuring',
                    'babel-plugin-transform-es2015-for-of',
                    'babel-plugin-transform-es2015-function-name',
                    'babel-plugin-transform-es2015-literals',
                    'babel-plugin-transform-es2015-object-super',
                    'babel-plugin-transform-es2015-parameters',
                    'babel-plugin-transform-es2015-shorthand-properties',
                    'babel-plugin-transform-es2015-spread',
                    'babel-plugin-transform-es2015-sticky-regex',
                    'babel-plugin-transform-es2015-template-literals',
                    'babel-plugin-transform-es2015-typeof-symbol',
                    'babel-plugin-transform-es2015-unicode-regex',
                    [
                        'transform-es2015-modules-commonjs',
                        { loose: true }
                    ],
                    [
                        'transform-es2015-classes',
                        { loose: true }
                    ]
                ]
            }
```

**Comment by jmm** [comment] 2015-11-13 19:28
Hello @joshacheson, welcome to the Babel community. This is a duplicate of #2871, #2724, #2679, and probably others. I don't know if it's properly documented, but that change is by design; see #2212. That's not destructuring, it just has similar syntax. It's an `ImportsList`.

**Closed by jmm** 2015-11-13 19:28 UTC

**Comment by gandazgul** [comment] 2017-03-13 18:39
I'm going to write this here because I had this issue and arrived here but still had to do more research.

@jmm this is not a dupe of any of those. It's also not exactly related to #2212. 

You are right in that the brackets in import { Baz } from 'Foo'; are different than the de-structuring brackets in const { Baz } = Foo;

Import lists will only work with explicit named exports and is not a de-structuring of the returned object. In order to achieve this import of a method you'd have to require it the old way:

const { Baz } = require('Foo').default;

Hope this helps someone else that is confused as we were.

**Comment by loganfsmyth** [comment] 2017-03-13 18:47
Personally I'd recommend

```
import Foo from 'Foo';
const  { Baz } = Foo;
```

Mixing CommonJS and ES6 imports in the same file isn't a good idea.

**Comment by agm1984** [comment] 2018-01-20 09:42
Here is a bonus solution that I have been using:

**./location/helpers/getPersonByEmail.js**
```
export default getPersonByEmail
```

**./location/helpers/index.js**
```
export { default as checkAuthorExists } from './checkAuthorExists'
export { default as checkEmailInUse } from './checkEmailInUse'
export { default as checkSlugInUse } from './checkSlugInUse'
export { default as getPersonByEmail } from './getPersonByEmail'
```

**./location/login.js**
```
import { getPersonByEmail } from './helpers'
```

This will allow you to pull them off by name. The index file acts as a "pass through". I imagine it like some kind of symlink.
