### ISSUE TITLE
Why double byte chars translate to unicode after babel.transform

### ISSUE THREAD

**Issue by jameslcj** [babel/babel#7261] opened 2018-01-23 12:57 UTC
Choose one: is this a bug report or feature request?

### Input Code

```js
let code = `class Demo extends React.Component {
    constructor(props) {
        super(props);
        this.state = {};
    }
    render() {

        return <div>
            <div id="："></div>
        </div>;
    }
}`
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
babel.transform(code, {
  compact: false,
  comments: true,
  plugins:  ["syntax-jsx", "syntax-object-rest-spread", function (babel) {
     return {
        visitor: {
           JSXOpeningElement: function ({node}) {
              // do something...
           }
        }
  }]
}
```

### Expected Behavior

I want to preserve double byte chars, like this

```js
class Demo extends React.Component {
    constructor(props) {
        super(props);
        this.state = {};
    }
    render() {

        return <div>
            <div id="："></div>
        </div>;
    }
}
```

### Current Behavior

but babel translates my double byte chars, "：" ===> "\uFF1A"

```js
class Demo extends React.Component {
    constructor(props) {
        super(props);
        this.state = {};
    }
    render() {

        return <div>
            <div id="\uFF1A"></div>
        </div>;
    }
}
```
### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.26.0
| Babylon          | 
| node             | v7.7.4
| npm              | 4.1.2
| Operating System | mac os

**Comment by nicolo-ribaudo** [comment] 2018-01-23 19:12
Thanks @jameslcj  for reporting this bug. This issue is a duplicate of https://github.com/babel/babel/issues/4909 and https://github.com/babel/babel/issues/7222

**Closed by nicolo-ribaudo** 2018-01-23 19:12 UTC
