### ISSUE TITLE
ES6 rest operator and Babel _ObjectWithoutProperties behave differently

### ISSUE THREAD

**Issue by dhananjaipai** [babel/babel#8927] opened 2018-10-25 12:34 UTC
## Bug Report

**Current Behavior**
let a = {1: 'one', 2: 'two', 3:'three'};
const {1:val, ...aWithoutOne} = a;
console.log(val); // prints 'one'
console.log(aWithoutOne); // Expects {2:'two', 3:'three'} , gets {1: 'one', 2: 'two', 3:'three'};

**Input Code**
Run the code above in JSBin against Javascript and ES6/Babel to see the difference.

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).
The problem is because ObjectWithoutProperties uses a for(key in obj) loop and compares with the keys sent. Since the key here is a number and for..in returns string, the behavior is incorrect. It is different from a v8 implementation. Making matters worse, `val` is set correctly, which made it harder to debug.

**Possible Solution**

Convert the keys to string before passing to ObjectWithoutProperties() function

**Additional context/Screenshots**
Try the code in Babel REPL and observe the output difference in Chrome console from both side.

**Comment by kyle1320** [comment] 2018-10-25 14:09
Looks like this is a duplicate of #8785, which should be fixed in release 7.1.4. The main Babel REPL seems to be down for me right now, but testing in https://babeljs.io/repl/build/9206/ for PR #8793 produces the expected output.

**Closed** 2019-09-03 21:18 UTC
