### ISSUE TITLE
[Bug]: Tuple members cannot use type keywords as names

### ISSUE THREAD

**Issue by pomek** [babel/babel#15404] opened 2023-02-03 11:41 UTC
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
export type Foo = {
	args: [ [
		object: number
	] ];
};
```

### Current and expected behavior

Current:

```
/repl.ts: Tuple members must be labeled with a simple identifier. (3:2)

  1 | export type Foo = {
  2 | 	args: [ [
> 3 | 		object: number
    | 		^
  4 | 	] ];
  5 | };
```

Expected:

No errors.

### Environment

* Binaries:
    * Node: 19.4.0 - /usr/local/bin/node
    * Yarn: 1.22.18 - ~/.yarn/bin/yarn
    * npm: 8.5.5 - /usr/local/bin/npm
* Monorepos:
    * Yarn Workspaces: 1.22.18
* npmPackages:
    * babel-standalone: ^6.26.0 => 6.26.0
    * eslint: ^7.19.0 => 7.32.0
    * webpack: ^5.58.1 => 5.75.0

### Additional context

https://babeljs.io/repl#?browsers=defaults&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=KYDwDg9gTgLgBDAnmYcBiEJwLxwN4BQAkAIZQDmAzgFxwDa9xREARgFbADGMtAdgK4BbFsCjEAunHEBuAgF9pQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Cstage-2%2Ctypescript&prettier=false&targets=Node-14&version=7.20.15&externalPlugins=&assumptions=%7B%7D

**Comment by JLHwung** [comment] 2023-02-03 15:03
Duplicate of #13702

**Closed as not planned by JLHwung** 2023-02-03 15:03 UTC
Labels: pkg: parser, area: typescript, outdated
