### ISSUE TITLE
different result between  site converter and cli

### ISSUE THREAD

**Issue by mogadanez** [babel/babel#1640] opened 2015-05-28 13:59 UTC
MacOSX, node 0.10.33

source:
```
import  _ from "lodash";
let some = '';
export default class Scope {
  constructor(arg = '' ) {
    this.member = arg;
  } 
}
```
 cli result:

```
'use strict';

exports.__esModule = true;

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { 'default': obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError('Cannot call a class as a function'); } }

var _lodash = require('lodash');

var _lodash2 = _interopRequireDefault(_lodash);

let some = '';

let Scope = function Scope() {
  let arg = arguments[0] === undefined ? '' : arguments[0];

  _classCallCheck(this, Scope);

  this.member = arg;
};

exports['default'] = Scope;
module.exports = exports['default'];
```
website result:

https://babeljs.io/repl/#?experimental=false&evaluate=false&loose=false&spec=false&code=import%20%20_%20from%20%22lodash%22%3B%0Alet%20some%20%3D%20''%3B%0Aexport%20default%20class%20Scope%20%7B%0A%20%20constructor(arg%20%3D%20''%20)%20%7B%0A%20%20%20%20this.member%20%3D%20arg%3B%0A%20%20%7D%20%0A%7D

[Q]:  why i stll have `let` in cli output

**Comment by sebmck** [comment] 2015-05-28 14:01
I don't get the `let` result at all. Both are the same to me. Do you have a `.babelrc` file interfering? What verison of Babel are you using?

**Comment by sebmck** [comment] 2015-05-31 03:11
Closing due to lack of reproducible example. Please create exact steps to reproduce if this is still an issue.

**Closed by sebmck** 2015-05-31 03:11 UTC
