### ISSUE TITLE
 Cannot read property 'file' of undefined at Scope.toArray

### ISSUE THREAD

**Issue by haf** [babel/babel#6950] opened 2017-12-01 15:32 UTC
Here's a minimal repro:

```js

const fn = edit => noop => {
  const a = [ 1, 2 ]
  const [ sid, ignored ] = [ 1, a[0] ];
}

```

Will not crash if:

 - you remove the access to `a`
 - you remove `edit`

Will not not crash if (aka, unaffected by):

 - you add a return statement
 - you rename any variable
 - you change the number of values in `a`

Versions

 -  "babel-plugin-react-transform": "2.0.2",
-  "babel-plugin-transform-react-constant-elements": "^6.23.0",
- "babel-plugin-transform-runtime": "6.23.0",

This is similar to https://github.com/babel/babel/issues/5915 which was closed as fixed when it's not (if the person who closed it had bothered to write a unit test for the bug, he'd know that).

**Comment by nicolo-ribaudo** [comment] 2017-12-01 16:03
That issue was closed as fixed in Babel 7.0.0-alpha.19, so it won't work in Babel 6. Can you test it with Babel 7.0.0-beta.32?

**Comment by haf** [comment] 2017-12-01 17:34
The comment about it being fixed referenced the REPL which is broken, which the latter comments in that thread indicate. I've given you a test case, and that test-case even breaks your REPL. Have you written a unit test with it?

Babel 7 is a beta right now, so it's not for us so far. Also, trying to migrate to the latest recommended settings so we can move straight to 7 once it's out of beta triggered #6951

**Comment by nicolo-ribaudo** [comment] 2017-12-02 12:00
Ok, can you post a reproducible example? WIth the informations you have given, I am unable to reproduce the bug (neither with babel 6.23 nor with babel 7.0.0-beta.32).

https://gist.github.com/nicolo-ribaudo/cc8fef58fee5ef70d9c16c9811854ba2

**Comment by edsrzf** [comment] 2019-10-02 13:05
I'm just reviewing some older issues. I also can't reproduce this with the code given in the issue. Can we close this issue? Or if it's still a problem, could we please get clearer instructions on how to reproduce it?

**Comment by nicolo-ribaudo** [comment] 2019-10-02 13:28
Given the two years without response, I'm closing this. Thanks @edsrzf!

**Closed by nicolo-ribaudo** 2019-10-02 13:28 UTC
