### ISSUE TITLE
[Bug]: Breaks react-router-dom

### ISSUE THREAD

**Issue by cdaycmc** [babel/babel#14229] opened 2022-02-03 03:43 UTC
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

- CRA
- `npm i react-router-dom` 
- Include `<BrowserRouter>`

### Current and expected behavior

Fails on `npm start`

```
ERROR in ./node_modules/history/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: C:\_src\xxx\node_modules\history\index.js: Cannot read property '    at SourceMapTree.originalPositionFor (C:\_src\xxx\node_modules\@ampproject\remapping\dist\remapping.umd.js:159:27)
    at trace (C:\_src\xxx\node_modules\@ampproject\remapping\dist\remapping.umd.js:102:37)
    at EncodedSourceMapImpl.map (C:\_src\xxx\node_modules\@jridgewell\trace-mapping\dist\trace-mapping.umd.js:347:36)
    at TraceMap.map (C:\_src\xxx\node_modules\@jridgewell\trace-mapping\dist\trace-mapping.umd.js:430:31)
    at SourceMapTree.traceMappings (C:\_src\xxx\node_modules\@ampproject\remapping\dist\remapping.umd.js:85:34)
    at remapping (C:\_src\xxx\node_modules\@ampproject\remapping\dist\remapping.umd.js:258:36)
    at mergeSourceMap (C:\_src\xxx\node_modules\@babel\core\lib\transformation\file\merge-map.js:19:30)
    at generateCode (C:\_src\xxx\node_modules\@babel\core\lib\transformation    at run (C:\_src\xxx\node_modules\@babel\core\lib\transformation\index.js:55:33)
    at run.next (<anonymous>)
 @ ./node_modules/react-router-dom/index.js 15:0-78 85:25-45 124:25-42 325:37-47 325:62-72
 @ consume shared module (default) react-router-dom@=6.2.1 (strict) (fallback: ./node_modules/react-router-dom/index.js)
 @ ./src/components/PassThrough.tsx 10:0-72 17:17-28 18:17-28 25:30-40 59:10-21 59:23-34
 @ container entry ./PassThrough[0]

Failed to compile.
```

### Environment

Babel 7.17.0
CRA 5.0.0
react-router-dom 6.2.1

### Possible solution

Revert to previous version of `@babel/core` 
`npm i -D @babel/core@7.16.12`

**Comment by milesj** [comment] 2022-02-03 04:14
I'm also seeing a similar error in Babel 7.17, but not in react-router-dom specifically. It triggers when upgrading Babel.

```
[BABEL]: /Users/milesj/Projects/packemon/packages/babel-plugin-env-constants/lib/types.js: Cannot read property 'originalPositionFor' of undefined (While processing: /Users/milesj/Projects/packemon/packages/babel-plugin-env-constants/lib/index.js)
```

**Comment by jridgewell** [comment] 2022-02-03 04:30
Looking into this.

**Comment by Ghustavh97** [comment] 2022-02-03 04:33
Same issue on Nuxt @ v2.15.8

```txt
Module build failed (from ./node_modules/babel-loader/lib/index.js): friendly-errors 06:24:50
TypeError: /home/project/nuxt/definitions/test/index.ts: Cannot read property 'originalPositionFor' of undefined
    at SourceMapTree.originalPositionFor (/home/project/nuxt/node_modules/@ampproject/remapping/dist/remapping.umd.js:159:27)
    at trace (/home/project/nuxt/node_modules/@ampproject/remapping/dist/remapping.umd.js:102:37)
    at EncodedSourceMapImpl.map (/home/project/nuxt/node_modules/@jridgewell/trace-mapping/dist/trace-mapping.umd.js:347:36)
    at TraceMap.map (/home/project/nuxt/node_modules/@jridgewell/trace-mapping/dist/trace-mapping.umd.js:430:31)
    at SourceMapTree.traceMappings (/home/project/nuxt/node_modules/@ampproject/remapping/dist/remapping.umd.js:85:34)
    at remapping (/home/project/nuxt/node_modules/@ampproject/remapping/dist/remapping.umd.js:258:36)
    at mergeSourceMap (/home/project/nuxt/node_modules/@babel/core/lib/transformation/file/merge-map.js:19:30)
    at generateCode (/home/project/nuxt/node_modules/@babel/core/lib/transformation/file/generate.js:72:39)
    at run (/home/project/nuxt/node_modules/@babel/core/lib/transformation/index.js:55:33)
    at run.next (<anonymous>)
    at Function.transform (/home/project/nuxt/node_modules/@babel/core/lib/transform.js:25:41)
    at transform.next (<anonymous>)
    at step (/home/project/nuxt/node_modules/gensync/index.js:261:32)
    at /home/project/nuxt/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/home/project/nuxt/node_modules/gensync/index.js:223:11)
```

**Comment by jridgewell** [comment] 2022-02-03 04:53
I found the bug, I'll publish a new `@jridgewell/trace-mapping` in a few minutes to fix.

**Comment by jridgewell** [comment] 2022-02-03 05:13
Ok, v0.2.3 is published which should resolve the issue.

**Comment by patotoma** [comment] 2022-02-03 05:22
> Ok, v0.2.3 is published which should resolve the issue.

confirmed, working now

if you have npm 7+ all you have to do is run: `npm update`

@jridgewell thanks for the fast fix

**Comment by nicolo-ribaudo** [comment] 2022-02-03 17:30
I'm closing this since it has been fixes in `@jridgewell/trace-mapping` (a dependency of a Babel dependency). Please make sure to update it! Your lockfile should show version 0.2.5.

**Closed by nicolo-ribaudo** 2022-02-03 17:30 UTC
Labels: i: regression
