### ISSUE TITLE
Recursive function fails 'Maximum call stack size exceeded' after babel updated via npm i

### ISSUE THREAD

**Issue by jomaora** [babel/babel#5048] opened 2016-12-27 15:52 UTC
I have a recursive function that we use in a project and worked very well until last month.

Today I restarted working on the project and I reinstall all the package, getting a new version of babel v6.21.0. The thing that this functions fails now with this error

```
Error: Maximum call stack size exceeded
```

### Input Code
This is the function

```js
const getErrorMessages = obj => {
  const v = values(obj);
  return flatMap(value => {
    if (isObject(value)) {
      return getErrorMessages(value);
    }
    return [value];
  }, v);
};
```

### Babel Configuration (.babelrc, package.json, cli command)

The last version set on our package.json was ^6.14.0 for babel-core. As I said after reinstalling everything, I've got the 6.21.1

### Context
We're fixed the problem rewriting the function by replacing the arrow function by a normal

```js
function getErrorMessages(obj) {
  const v = values(obj);
  return flatMap(value => {
    if (isObject(value)) {
      return getErrorMessages(value);
    }
    return [value];
  }, v);
};
```

We print the transformed version for each version and there's a difference :

Using arrow function (so the failing version)
```js
function getErrorMessages(obj) {
  ++cov_2fkhorkyo0.f[14];

  var v = (++cov_2fkhorkyo0.s[38], (0, _values2.default)(obj));
  ++cov_2fkhorkyo0.s[39];
  return (0, _flatMap2.default)(function getErrorMessages(value) {
    ++cov_2fkhorkyo0.f[15];
    ++cov_2fkhorkyo0.s[40];

    if ((0, _isObject2.default)(value)) {
      ++cov_2fkhorkyo0.b[8][0];
      ++cov_2fkhorkyo0.s[41];

      return getErrorMessages(value);
    } else {
      ++cov_2fkhorkyo0.b[8][1];
    }
    ++cov_2fkhorkyo0.s[42];
    return [value];
  }, v);
}
```

The version with function
```js
function getErrorMessages(obj) {
  ++cov_2fkhorkyo0.f[14];

  var v = (++cov_2fkhorkyo0.s[37], (0, _values2.default)(obj));
  ++cov_2fkhorkyo0.s[38];
  return (0, _flatMap2.default)(function (value) {
    ++cov_2fkhorkyo0.f[15];
    ++cov_2fkhorkyo0.s[39];

    if ((0, _isObject2.default)(value)) {
      ++cov_2fkhorkyo0.b[8][0];
      ++cov_2fkhorkyo0.s[40];

      return getErrorMessages(value);
    } else {
      ++cov_2fkhorkyo0.b[8][1];
    }
    ++cov_2fkhorkyo0.s[41];
    return [value];
  }, v);
}
```

Is there something that changed in the newest version that affects recursive functions?
Thanks

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.21.1
| node             | 6.5.0
| npm              | 3.10.3
| Operating System | OsX 10.11.6

**Comment by loganfsmyth** [comment] 2016-12-27 18:58
Could you please include your Babel configuration so we know what presets/plugins you are using?

Using just `es2015` I can't trigger that issue [in the REPL](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015&code=function%20getErrorMessages(obj)%20%7B%0A%20%20const%20v%20%3D%20values(obj)%3B%0A%20%20return%20flatMap(value%20%3D%3E%20%7B%0A%20%20%20%20if%20(isObject(value))%20%7B%0A%20%20%20%20%20%20return%20getErrorMessages(value)%3B%0A%20%20%20%20%7D%0A%20%20%20%20return%20%5Bvalue%5D%3B%0A%20%20%7D%2C%20v)%3B%0A%7D%3B) but it is possible it's an issue with Babel's core transform interacting with other things, which whichever code coverage plugin you're using.

**Comment by loganfsmyth** [comment] 2016-12-27 23:35
Closing this in favor of https://github.com/istanbuljs/istanbul-lib-instrument/issues/34 since that is the cause of the issue.

**Closed by loganfsmyth** 2016-12-27 23:35 UTC
