### ISSUE TITLE
babel-runtime needs to update to regenerator 0.8.28

### ISSUE THREAD

**Issue by mrm007** [babel/babel#1685] opened 2015-06-05 02:04 UTC
**regenerator** `0.8.28` breaks compatibility with **babel** because it's added a [new method `runtime.awrap`][awrap] which is not present in **babel-runtime**. A new version of **babel-runtime** needs to be published or update the dependency in **babel-core** to **regenerator** `<0.8.28`.

[awrap]: https://github.com/facebook/regenerator/commit/a4d2143bc8a8c639e90471942c63df89c7a22064

**Comment by sebmck** [comment] 2015-06-05 02:35
A breaking version of `regenerator` should not have been released as a minor pre-1.0.0. cc @benjamn

**Comment by fkling** [comment] 2015-06-05 03:16
To be fair, adding a new method is hardly a breaking change though. It rather looks like babel should always depend on a fixed version of regenerator, so that you have more control over the update process.

**Comment by UltCombo** [comment] 2015-06-05 03:21
My build is failing with `TypeError: _regeneratorRuntime.awrap is not a function`.
I assume this issue is the source of the problem?

**Comment by mrm007** [comment] 2015-06-05 03:38
@UltCombo yes, that is the effect.

**Comment by benjamn** [comment] 2015-06-05 04:19
@fkling is right. This is not a breaking change from Regenerator's perspective, only from the perspective of a consumer using an out of date version of the runtime.

What can we do to make sure the runtime and the compiler stay on the same version in Babel?

**Comment by benjamn** [comment] 2015-06-05 04:24
Depending on a fixed version of Regenerator seems like a reasonable strategy if you can't guarantee that the parts of it you're using independently remain consistent with each other.

**Comment by UltCombo** [comment] 2015-06-05 04:44
> Depending on a fixed version of Regenerator seems like a reasonable strategy if you can't guarantee that the parts of it you're using independently remain consistent with each other.

Yes, I believe it would fix the issue if Babel pins down the Regenerator version and consumers pin down their babel-runtime dependency version.

**Comment by sebv** [comment] 2015-06-05 06:35
If one of the babel guy run `make publish-runtime` that should fix it. Might also consider babel-runtime having npm dependencies, not sure what was the logic with the current setup.

**Comment by sebmck** [comment] 2015-06-05 06:37
@sebv The regenerator runtime has to be processed with the `runtime` transformer to ensure that `Promise` and `Symbol` are correctly aliased to `core-js`.

**Closed** 2015-06-05 06:56 UTC

**Comment by sebv** [comment] 2015-06-05 07:01
@sebmck  are you publishing new packages?

**Comment by sebmck** [comment] 2015-06-05 07:02
@sebv Yes. I haven't published a new version in over 2 weeks and need to verify that none of the changes made in the interim don't break everything. Give me time.

**Comment by sebv** [comment] 2015-06-05 07:09
Ok cool thx! 
Just generated a new `publish-runtime` and hard-copied it into my node_modules, that will definitely fix it. (For some reasons publish-runtime breaks `npm link`, but it's another issue)

**Comment by sebmck** [comment] 2015-06-05 07:11
Just published 5.5.0, hopefully it doesn't break the world.

**Comment by sebv** [comment] 2015-06-05 07:39
Seem to fixed it, might be a small regression, getting this:
```
SyntaxError: /Users/baba/Work/appium-base-driver/node_modules/appium-gulp-plugins/node_modules/mocha/bin/_mocha: 'return' outside of function (392:2)
```

**Comment by sebmck** [comment] 2015-06-05 07:39
How are you running `mocha`?

**Comment by sebv** [comment] 2015-06-05 07:40
using isparta: https://github.com/douglasduteil/isparta
babel-node node_modules/.bin/isparta cover --report text --report html node_modules/.bin/_mocha -- --reporter dot

**Comment by sebmck** [comment] 2015-06-05 07:42
This was changing behaviour in 5.0.0 that will compile files in `node_modules` provided that it's directly relative to the entry file. Isparta should not be recommending that behaviour as it's extremely hacky.

**Comment by mrm007** [comment] 2015-06-05 08:35
@sebmck Thank you, that was quick!

**Comment by UltCombo** [comment] 2015-06-05 12:53
@sebmck wouldn't it be better to depend on an exact version of Regenerator?

Right now, babel-core allows seamlessly upgrading regenerator when a new patch/minor version is published, but babel-runtime will not update automatically. If this isn't changed, this issue is fated to repeat itself.

**Comment by sebmck** [comment] 2015-06-05 12:54
@UltCombo Not possible and defeats the purpose of the runtime:

>  The regenerator runtime has to be processed with the `runtime` transformer to ensure that `Promise` and `Symbol` are correctly aliased to `core-js`,

**Comment by UltCombo** [comment] 2015-06-05 12:56
@sebmck I meant to remove the semver range from [this line](https://github.com/babel/babel/blob/2053610429824c4e21e53fad61e8382ace807cc1/package.json#L54) and use an exact version, e.g. `"regenerator": "0.8.28"`. This would ensure that the compiler and runtime stay with the same regenerator version, and still allow it to be processed by Babel, right?

**Comment by sebmck** [comment] 2015-06-05 12:57
I guess, it's just extremely annoying to have to manually bump the version whenever there's an update.

**Comment by UltCombo** [comment] 2015-06-05 13:00
Part of my build process is updating all dependencies, the same dependencies which a consumer would install with a clean `npm install`. It is rather annoying when my build and `npm install`s of my packages break due to conflicting regenerator versions in the compiled code vs runtime.

**Comment by UltCombo** [comment] 2015-06-05 13:11
If you'd really like to avoid using an exact version, it would perhaps be possible to set up a bot to watch the npm registry and build and publish the babel-runtime when a new regenerator version is published. The problem is that the babel-runtime version would no longer match babel-core's, and this doesn't warrant 100% uptime either.

**Comment by mrm007** [comment] 2015-06-06 01:38
How about declaring `regenerator` as dependency in `babel-runtime` and running the transformer on postinstall?

**Comment by sebmck** [comment] 2015-06-06 01:40
That would require an entire install of `babel-core` which would be crazy since the `babel-runtime` is supposed to be very small to install (it only relies on `core-js` which has 0 dependencies).

**Comment by benjamn** [comment] 2015-06-06 02:17
I could split the Regenerator runtime out into its own NPM package if that
would help.

**Comment by UltCombo** [comment] 2015-06-06 23:18
I guess I've been thinking about this more than I should, anyway, I've opened #1701 to sum up my thoughts. Can we relocate this discussion to there?
