### ISSUE TITLE
Regression: path.parentPath.get(path.listKey) can clobber a traversal's visitors with those from a separate traversal in the global path cache

### ISSUE THREAD

**Issue by jedwards1211** [babel/babel#12570] opened 2020-12-29 20:54 UTC
## Bug Report

- [x] I would like to work on a fix!

**Input Code**

```js
const {parse} = require('@babel/core')
const generate = require('@babel/generator').default
const traverse = require('@babel/traverse').default

const code = `
import { Foo } from './Foo'
import { Bar } from './Bar'
`

const presets = [
  ['@babel/preset-env', { targets: { node: 'current' } }],
]

const ast = parse(code, {plugins, presets})

traverse(ast, {
  Program(path) {
    path.traverse({
      ImportDeclaration: {
        enter(path) {
          console.log('ENTER', generate(path.node).code)
          if (path.node.source.value === './Bar')
            path.parentPath.get(path.listKey)
        },
        exit(path) {
          console.log('EXIT ', generate(path.node).code)
        }
      }
    })
  }
})
```

**Expected behavior**

I haven't bisected to find the version that introduced the regression yet, but with @babel/core, @babel/traverse, and @babel/preset-env 7.4.5, the exit visitor is called for both import statements:
```
ENTER import { Foo } from './Foo';
EXIT  import { Foo } from './Foo';
ENTER import { Bar } from './Bar';
EXIT  import { Bar } from './Bar';
```

**Current behavior**

With these versions:
├─ @babel/core@7.12.10
├─ @babel/preset-env@7.12.11
└─ @babel/traverse@7.12.12

The exit visitor for the second import statement isn't called because `path.parentPath.get(path.listKey)` has the side effect of replacing `path.opts` with those of the parent traversal (which only has a `Program` visitor)
```
ENTER import { Foo } from './Foo';
EXIT  import { Foo } from './Foo';
ENTER import { Bar } from './Bar';
```
(missing `EXIT import { Bar } from './Bar'`)

**Additional context**

`babel-plugin-flow-runtime` is no longer working after I upgraded `@babel/*`, and I uncovered this issue debugging it.

**Comment by jedwards1211** [comment] 2020-12-29 21:51
@nicolo-ribaudo okay even if I do a non-nested traversal like `traverse(path.node, { ... })` within the `Program` visitor, because there's an apparently global cache of paths (https://github.com/babel/babel/blob/main/packages/babel-traverse/src/path/index.js#L70) it pulls in a context that shouldn't be related in any way at all to the non-nested traversal, and clobbers its options.

Shouldn't each traversal own a separate path cache?  The effects this global cache is causing feels very wrong.

**Comment by jedwards1211** [comment] 2020-12-29 22:10
It seems like the only safe design is either to not cache, or if so, have a different cache per root traversal and `@babel/traverse` version instead of just one or the other.

**Comment by jedwards1211** [comment] 2020-12-30 00:08
This regression was introduced in @babel/traverse 7.12.7 (I'm guessing PR #12302 did it)

**Comment by fedeci** [comment] 2021-02-20 17:40
@jedwards1211 I just bisected and it seems to be a regression of #12331.

**Comment by jedwards1211** [comment] 2021-02-20 18:00
Huh. I didn't do an actual git bisect, just tried subsequent versions, so i bet you're right

**Comment by fedeci** [comment] 2021-02-21 12:18
After further investigation I discovered that the bug was already there since v6 😄 and #12331 just exposed it. 
```js
// quick temporary fix
path.parentPath.get(path.listKey, false)
```

**Comment by JLHwung** [comment] 2021-11-18 18:02
I think the behaviour is expected because `path.traverse` does not visit `path` itself. In this case, for an ImportDeclaration `path`, its `parentPath` is always a Program, whose `context` are the root context because the Program path is not visited in `path.traverse`. Now when we call `.get("body")`: all the immediate children of Program, including the ImportDeclaration, inherit the root context and hence the current context is overridden by root context.

A workaround for
```js
path.parentPath.get(path.listKey)
```

can be
```js
const siblings = [
  ...path.getAllPrevSiblings(),
  path,
  ...path.getAllNextSiblings(),
];
```

When `parentPath` is involved, it is difficult to preserve context as it may run out of the sub-traversal, unless we mark the whole AST as the new context (so plugin is free to visit anywhere), or we provide a `getParentPath(context: TraversalContext)`.

**Comment by jedwards1211** [comment] 2021-11-18 20:36
Huh I see.  FWIW, I wonder if a different API design would be possible where the context information is passed around instead of being a property on the paths that gets mutated.  This issue certainly wasn't a showstopper for me but I did burn a lot of time in a painful debugging session on it.

**Comment by JLHwung** [comment] 2021-11-18 20:54
Indeed, I will see if I can take on https://github.com/babel/babel/pull/12634

**Comment by jedwards1211** [comment] 2021-11-18 21:05
@JLHwung oh interesting.

I noticed that `visitor` is already an argument to `path.traverse` etc.  And this issue involved traversal getting the visitors from `path.opts`  in some cases, and that getting blown away by context changes.  So aside from changes in that PR, I wonder if it would be possible for traversal to always use the `visitor` passed around via function arguments instead of anything related to context?

**Comment by nicolo-ribaudo** [comment] 2023-06-27 10:46
The original example and the test in the attached PR both pass on `main`.

**Comment by nicolo-ribaudo** [comment] 2023-07-05 10:49
Fixed by https://github.com/babel/babel/pull/13813 (found by `git bisect`), I will add a test.

**Closed** 2023-07-05 13:44 UTC
Labels: i: bug, pkg: traverse, i: regression
