### ISSUE TITLE
[Bug]: Variable Value Overwrite Failed

### ISSUE THREAD

**Issue by clhiker** [babel/babel#14716] opened 2022-07-03 02:04 UTC
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```js
// не строгий режим
function mixArgs(first, second = "b") {
    var __es_vNaN = Array.prototype.sort.call("{}".split("writable", 10000));

    console.log(arguments.length);
    Number.parseFloat("+0");
    console.log(first === arguments[0]);
    console.log(second === arguments[1]);
    first = "c";
    second = "d";
    console.log(first === arguments[0]);
    console.log(second === arguments[1]);
}

mixArgs("a");
```
Here is the [REPL](https://babel.dev/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=true&loose=false&code_lz=PTAEl4QRWEFRBEEIRBACIIPhBDMIIDhBCcIKBlBsIGwHhAAoAMwFcA7AYwBcBLAewtAFs6APAQQCcBzAZwAUJOt340ANKH4BTKkwAmoALygARACM1ASlABvIqCOgAbgENuoAPpWZ_KyYByZxytA9uZgJ4A6AA7cDDRBXn4yPvwM3DQ-VGYANvGCanoAvmoRfvF0NMkA7tw5ZhrxMmpSAIwADDVV2toA3ESGxvIUkaU-8Qy8gha8ZCwyFDT8XcO8NAAWjS1GjoMaMtz-FrIAYt1muWoA1FU6TcagbR3h3b0iYjQqyqr9g8OjANpVALqzx6cMnReCsm0lHd7nxHiN-M8Kh8jsYruI3GoqGoYUYAYoEQpkXMTkwzl0esJRPDgaAHkNwa9odjvr8CWiKEC7qTQeSXlDZqlmmwuHwhGozIcgA&debug=false&forceAllTransforms=true&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=unambiguous&lineWrap=true&presets=env&prettier=false&targets=Node-10.13&version=7.18.7&externalPlugins=&assumptions=%7B%7D)

### Configuration file name

babel.config.json

### Configuration

```json
{
  "sourceType": "unambiguous",
  "presets": ["@babel/preset-env"],
  "plugins": [
    "@babel/plugin-transform-runtime"
  ]
}
```

### Current and expected behavior

The origin code run by node print
```js
1
true
false
false
false

```
But the transpiled code run by node print
```js
1
true
false
true
false
```

### Environment

- babel 
- - ├── @babel/cli@7.17.0=6
- - ├── @babel/generator@7.17.3
- - ├── @babel/plugin-transform-runtime@7.17.0
- - ├── @babel/preset-env@7.16.11
- Node: [v17.3.0]
- npm version [8.5.2]
- os [ubuntu 20.04]

**Comment by nicolo-ribaudo** [comment] 2022-07-04 14:36
Duplicate of #14718

**Closed by nicolo-ribaudo** 2022-07-04 14:36 UTC
Labels: i: needs triage
