### ISSUE TITLE
Rest operator fails on pattern operand

### ISSUE THREAD

**Issue by jmzhang** [babel/babel#4811] opened 2016-11-05 07:30 UTC
### Input Code

```js
function f(...[a, b, c]) {
    return a + b + c;
}
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": ["es2015", "stage-0"]
}
```

### Expected Behavior

It should compile.

### Current Behavior

```
repl: Unexpected token (1:14)
> 1 | function f(...[a, b, c]) {
    |               ^
  2 |     return a + b + c;
  3 | }
```

### Context

The sample code is taken from MDN ([here](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/rest_parameters)) and runs just fine on Chrome natively. 

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.18.0
| node             |  6.3.1
| npm              | 3.10.3
| Operating System | macOS 10.11.5

**Comment by loganfsmyth** [comment] 2016-11-05 18:12
Duplicate of https://github.com/babel/babylon/issues/53. This is an ES2016 feature we haven't gotten to yet.

**Closed by loganfsmyth** 2016-11-05 18:12 UTC
