### ISSUE TITLE
async arrow functions lose this context

### ISSUE THREAD

**Issue by rolandjitsu** [babel/babel#2982] opened 2015-11-11 11:21 UTC
It looks like if I have:
```js
class Test {
  constructor() {
    someService.get().then(async () => {
      this.foo = 'tada';
    })
  }
}
```
`this` is `undefined`. If I remove `async` I have the right `this`.

**Comment by jmm** [comment] 2015-11-11 13:42
I can't believe that even parses.

**Comment by rolandjitsu** [comment] 2015-11-11 13:43
@jmm I forgot to add the constructor ...

**Comment by foster** [comment] 2015-11-11 17:41
Just came here to post the same issue. Here's another example:

before transform:
```javascript
var obj = {
    foo: 'bar',
    
    async doThing () {
        var resp = await Promise.resolve([true, false]);;

        resp.forEach(() => console.log(this.foo)); // output: undefined undefined
        for (var r of resp) console.log(this.foo); // output: bar bar
    }
}

obj.doThing();
```

after transform:
```javascript
function _asyncToGenerator(fn) { return function () { var gen = fn.apply(this, arguments); return new Promise(function (resolve, reject) { var callNext = step.bind(null, "next"); var callThrow = step.bind(null, "throw"); function step(key, arg) { try { var info = gen[key](arg); var value = info.value; } catch (error) { reject(error); return; } if (info.done) { resolve(value); } else { Promise.resolve(value).then(callNext, callThrow); } } callNext(); }); }; }

var obj = {
    foo: 'bar',

    doThing() {
        var _this = this;

        return _asyncToGenerator(function* () {
            var resp = yield Promise.resolve([true, false]);;

            resp.forEach(() => console.log(this.foo)); // output: undefined undefined
            for (var r of resp) console.log(_this.foo); // output: bar bar
        })();
    }
};

obj.doThing();
```

**Comment by thejameskyle** [comment] 2015-11-12 08:30
Duplicate of #2765

**Closed by thejameskyle** 2015-11-12 08:30 UTC
