### ISSUE TITLE
Problem with babel@7 way of transforming export syntax (beta 36) + webpack require algorithm

### ISSUE THREAD

**Issue by jrencz** [babel/babel#7135] opened 2017-12-29 14:12 UTC
(Please do look at [Context](#user-content-#context) first. It will help understand the code examples which, according to the issue template should be above)

Choose one: is this a bug report or feature request?
Bug, more probably an edge case

### Input Code

(Snippet A: index module exporting 2 classes from modules which export each as default)
(2 ways of doing the same with different syntax are here on purpose, to prove neither works better than the other)
```js
// (domain 1)/lib/model/index.js
import Document from './Document';
export {
  Document,
};

export {
  default as DocumentRepresentation,
} from './DocumentRepresentation';
```

(Snippet B)
```js
// (domain 1)/lib/index.js
export * from './model';
```

(Snippet C1)
```js
// (domain 1)/lib/someOtherDir/someModule.js
import {
  DocumentRepresentation
} from '../model';

// DocumentRepresentation is a class
```

(Snippet C2)
```js
// (domain 2)/anyDir/anyModule.js
import {
  DocumentRepresentation,
} from '(domain 1)/lib';

// DocumentRepresentation is a class with babel@6 but it's undefined with babel@7
```

[`6.26.0` way of processing Snippet A (REPL)](http://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=JYWwDg9gTgLgBAEQgYwK4gKYDt4DMoQhwDkAdAPRJqY7EDcAUBgB6SxwDeDciK62MADQMAvoyato8LjwAmGXAENUAG3iKAzr2oCAShjBQMGgYpjAIWYSLj5CJClX459h46fOX6DIA&debug=false&circleciRepo=&evaluate=false&lineWrap=false&presets=stage-0%2Ces2015-loose&prettier=false&targets=&version=6.26.0)

<details><summary>(preview)</summary>

```js
'use strict';

exports.__esModule = true;
exports.DocumentRepresentation = exports.Document = undefined;

var _DocumentRepresentation = require('./DocumentRepresentation');

Object.defineProperty(exports, 'DocumentRepresentation', {
  enumerable: true,
  get: function get() {
    return _interopRequireDefault(_DocumentRepresentation).default;
  }
});

var _Document = require('./Document');

var _Document2 = _interopRequireDefault(_Document);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

exports.Document = _Document2.default;
```
</details>

<details><summary>webpack output</summary>

```js
(function(module, exports, __webpack_require__) {

"use strict";


exports.__esModule = true;
exports.DocumentRepresentation = exports.Document = undefined;

var _DocumentRepresentation = __webpack_require__(877);

Object.defineProperty(exports, 'DocumentRepresentation', {
  enumerable: true,
  get: function get() {
    return _interopRequireDefault(_DocumentRepresentation).default;
  }
});

var _Document = __webpack_require__(882);

var _Document2 = _interopRequireDefault(_Document);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

exports.Document = _Document2.default;

/***/ })
```
</details>

<br>

[`7.0.0-beta` way of processing Snippet A (REPL)](http://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=JYWwDg9gTgLgBAEQgYwK4gKYDt4DMoQhwDkAdAPRJqY7EDcAUBgB6SxwDeDciK62MADQMAvoyato8LjwAmGXAENUAG3iKAzr2oCAShjBQMGgYpjAIWYSLj5CJClX459h46fOX6DIA&debug=false&circleciRepo=&evaluate=false&lineWrap=false&presets=stage-0%2Ces2015-loose&prettier=false&targets=&version=7.0.0-beta.35)

<details><summary>(preview)</summary>

```js
"use strict";

exports.__esModule = true;
exports.DocumentRepresentation = void 0;

var _Document = _interopRequireDefault(require("./Document"));

exports.Document = _Document.default;

var _DocumentRepresentation = _interopRequireDefault(require("./DocumentRepresentation"));

exports.DocumentRepresentation = _DocumentRepresentation.default;

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
```
</details>

<details><summary>webpack output</summary>

```js
(function(module, exports, __webpack_require__) {

"use strict";


var _interopRequireDefault = __webpack_require__(0);


exports.__esModule = true;
exports.DocumentRepresentation = void 0;

var _Document = _interopRequireDefault(__webpack_require__(879));

exports.Document = _Document.default;

var _DocumentRepresentation = _interopRequireDefault(__webpack_require__(888));

exports.DocumentRepresentation = _DocumentRepresentation.default;

/***/ })
```
</details>

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

<details>
<summary>babel@6.26.0</summary>

```json
{
  "plugins": [
    ["babel-plugin-angularjs-annotate", {
      "explicitOnly": true
    }],
    ["babel-plugin-transform-runtime", {
      "polyfill": false
    }],
    ["babel-plugin-module-resolver", {
      "root": [
        "./src/App/",
        "./config/",
        "./lib/"
      ]
    }],
    ["babel-plugin-transform-builtin-extend", {
      "globals": [
        "Set",
        "Error"
      ]
    }],
    "babel-plugin-import-glob",
    "babel-plugin-transform-decorators-legacy"
  ],
  "presets": [
    ["env", {
      "useBuiltIns": true,
      "loose": true,

      "targets": {
        "browsers": ["> 0.5% in my stats", "> 2% in PL"]
      }
    }],
    "stage-0"
  ]
}
```
</details>

<details>
<summary>babel@7.0.0-beta</summary>

```js
module.exports = {
  // TODO: create babel-preset-wonga-app. Put plugins there.
  plugins: [
    ['babel-plugin-angularjs-annotate', {
      explicitOnly: true
    }],
    ['@babel/plugin-transform-runtime', {
      polyfill: false
    }],
    ['babel-plugin-module-resolver', {
      root: [
        './src/App/',
        './config/',
        './lib/'
      ]
    }],
    ['babel-plugin-transform-builtin-extend', {
      globals: [
        'Set',
        'Error'
      ]
    }],
    'babel-plugin-import-glob',
    'babel-plugin-transform-decorators-legacy'
  ],
  presets: [
    ['@babel/preset-env', {
      useBuiltIns: 'entry',
      loose: true
    }],
    '@babel/stage-0',
  ]
};
```
</details>

### Expected Behavior

There should be no difference how code compiled with the same version of webpack works regardless of whether babel@6 or babel@7 is used

### Current Behavior

Code compiled with webpack@3.10.0 (current latest stable) works if processed with babel@6.26.0 (current latest stable) but it doesn't work with bebel@7.0.0-beta.36 (current latest beta).
Output `babel@7.0.0-beta` produces seems to confuse webpack module initialisation sequence in a case described below:

### Possible Solution

Proving whether it's babel or webpack issue is sadly out of the scope of my knowledge

<a id="#context"></a>
### Context

The code given as example (Snippet A) is actual code I use in one of `index.js` files in my project (project is processed using `webpack@3.10.0`).
What that `index.js` exports is then used in 2 contexts: local (same code domain) and remote (other code domains)

1. local: either of named exports can be imported directly from the `index.js` module (like in Snippet C1)
2. remote: either of named exports can be imported from the domain main `index.js` which re-exports (as shown in Snippet B) and is (by convention) known to other domains (as shown in Snippet C2)

Places where `DocumentRepresentation` (which is a class) is imported locally (think: like Snippet C1) work fine with both babel@6 and babel@7

Places where the same class is imported from the "re-export" module (think: Snippet C2) work with babel@6 but with babel@7 webpack seems to get confused by the change in babel output code and what actually gets imported is `undefined` (as it gets assigned: `exports.DocumentRepresentation = void 0;` - if `void 0` is changed to anything else that thing gets imported).
Both ways of transforming code (babel@6 and babel@7) seem correct though.

I tried altering my code and here's the conclusion I came to:
To keep webpack from getting confused I need to decide on either of the ways of reaching the class. If i never reach it from the original `index.js` and always from the re-exporting one (Snippet C2) then it's all OK.

I'm not sure if what causes my current problem is 
- the fact that webpack does something wrong in their order of module initiation (which off course may be the case) or 
- is webpack confusion actually caused by the way bebal@7  transforms module syntax, but I decided to file this issue to let you know there may be some incompatibility between babel@7 and the latest webpack, or
- I'm misusing the modules syntax and I'm doing something that is either not specified enough (I doubt that) or directly against the spec (which I can't prove myself)

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  babel@6.26 & babel@7.0.0-beta.36
| Babylon          | 
| node             | 8.9.1
| npm              | 5.5.1
| Operating System | macOS 10.13.2

**Comment by loganfsmyth** [comment] 2017-12-29 16:29
I have an idea of what change caused this break, and I'm thinking this is probably a latent bug in your own code that Babel 7 exposed while fixing a bug. Easy to verify though. 

Can you see if your code works if you change your model index to 

```
export {
  default as DocumentRepresentation,
} from './DocumentRepresentation';

import Document from './Document';
export {
  Document,
};
```
So the `DocumentRepresentation` file will run first again, like it did on Babel 6? I'm thinking you have a dependency cycle that makes the order important.

**Comment by jrencz** [comment] 2017-12-29 17:00
It did help.

But I still don't understand why exactly.
I imagine import order may matter if we have `require` implementation that has side effects (in case of webpack: caching the already initialised modules)

Does the spec say anything about that?

**Comment by jrencz** [comment] 2017-12-29 17:05
So I understand it this way: babel@6 did change the order or *imports* (it doesn't matter why at the moment) and babel@7 keeps the order as authored. So: babel@7 does the right thing (at least: a predictable thing)

I do have some edge case in dependency graph then, but I don't yet know what is it.

**Comment by loganfsmyth** [comment] 2017-12-29 17:06
To me that indicates that your code has been written to have dependency cycles, some some modules depend on others that depend back on the original. This can lead to cases like yours, where the representation hasn't been initialized yet when your code tries to use it.

Could you post the stack trace from the error you were seeing originally? Usually the stack trace in these types of errors clearly shows a file requiring a module that eventually cycles back to the original again.

**Comment by loganfsmyth** [comment] 2017-12-29 17:22
> babel@6 did change the order or imports (it doesn't matter why at the moment) and babel@7 keeps the order as authored

Yup! We fixed https://github.com/babel/babel/issues/4356 which was causing re-exported items to be `require()`d in the wrong order compared to the source. It seems like your code was relying on that backward ordering.

**Comment by jrencz** [comment] 2017-12-29 17:26
>Could you post the stack trace from the error you were seeing originally?

I can't paste the trace but I analysed it. 
The error is a runtime error `Uncaught TypeError: _lib.DocumentRepresentation is not a constructor` (it's not thrown during build - I see it in dev tools, not in shell).

After removing webpack bootstrap elements it's more or less:
- Module with controller (where non-constructor is constructor-called)
- Module that combines the controller, the template and the stylesheet (a view component)
- Module that registers the component in a framework (AngularJS in that case)
- 3x a module that is a logical parent and a parent in terms of directory structure until project root is reached

> Usually the stack trace in these types of errors clearly shows a file requiring a module that eventually cycles back to the original again.

No cycles this time.

>  It seems like your code was relying on that backward ordering.

**Comment by jrencz** [comment] 2017-12-29 17:35
There's one thing that didn't seem to matter to me when I created the issue but now I see it does.

Below the `import Document from './Document';` was wrapped with some comments:

```js
// For unknown reason `export { default as Document } from './Document'`
// doesn't work. Document imported from here is undefined
import Document from './Document';
export {
  Document,
};

// TODO: restore code below
// export {
//   default as Document,
// } from './Document';
```

It looks like this was a workaround. An unintentional one but it apparently did work because of what babel@6 does.

BTW this (with order you suggested but with `export...from` syntax):

```js
export {
  default as DocumentRepresentation,
} from './DocumentRepresentation';
export {
  default as Document,
} from './Document';
```

works as well.

I need to figure out what's wrong with dependency structure in my code then.
Thank you for helping me understand what happens.

I guess if there is (or will be) a 6->7 migration guide then what https://github.com/babel/babel/issues/4356 introduced should be marked as a change that is somewhat likely to break the existing codebases just because they might (like mine) rely on the quirk present in babel@6

**Comment by loganfsmyth** [comment] 2017-12-29 17:45
It's super hard to diagnose this type of thing without real code to look at. I can elaborate more on my expectation though, because I don't think I described it well. When you break at the `Uncaught TypeError: _lib.DocumentRepresentation is not a constructor` error, look in the stack trace. I'd expect an entry for `DocumentRepresentation.js` somewhere in the stack trace, on a line that does an import from another file. Usually these things end up looking something like this, as an example:

```
// base.js
import Child from "./child";
export default class Base {
  doSpecialThing() {
    return new Child();
  }
  static initialize(){}
}

// child.js
import Base from "./Base";
export default class Child extends Base { }

// index.js
import Base from "./Base";
Base.initialize();

export { default } from "./child";
```
if you consider this code running `index.js`, we get the following

1. Import `index.js`
2. `index.js` imports `Base.js`
3. `Base.js` imports `Child.js`
4. `Child.js` imports `Base.js`, but `Base.js` is already mid-load from step (2) above
5. `Child.js` continues executing since there is no way for it to make `Base.js` execute more. 

This means that the line `class Child extends Base { }` will throw because the imported `Base` variable doesn't have a value yet because `export default class Base {` hasn't run, because it is paused on the line above that at `import Child from "./child";`.

In a real ES6 environment, this would throw an error telling you it hasn't been initialized, but with Babel all you get is an `undefined` value currently.

> I guess if there is (or will be) a 6->7 migration guide...

That's a fair point. We definitely have our work cut out for us once we start pulling all the breaking changes together to write a guide.

**Comment by nicolo-ribaudo** [comment] 2017-12-29 17:51
@jrencz Can you try to disable modules transformation? (Add `"modules": false` to the preset-env options)
Maybe Webpack handles untranspiled imports better.

**Comment by loganfsmyth** [comment] 2017-12-29 17:58
@nicolo-ribaudo In this case, I'd be quite surprised. If it works in Webpack, it seems like that would mean Webpack had the same bug that Babel 6 had, which I don't believe it does.

**Comment by jrencz** [comment] 2017-12-29 18:28
@nicolo-ribaudo I tried and it does handle the case!

And the total size of all chunks has been reduced by 5.9% (to be precise: it didn't change the size of a chunk where I place 3rd party libraries but it decreased the size of app chunk by 8.5%)

**Comment by loganfsmyth** [comment] 2017-12-29 18:41
Hmm, if it does work in Webpack but not Babel 7, it's definitely important to trim down a reproducible case of this, since either way there's either a bug in Webpack, or a bug in Babel.

Would you be able to trim down your code to a reproducible sample?

**Comment by jrencz** [comment] 2017-12-29 18:45
@loganfsmyth definitely not before first week of January.

Can't it "just" be that if webpack is given the "raw" modules it can apply more logic to optimise how dependencies are resolved?

**Comment by loganfsmyth** [comment] 2017-12-29 18:57
It could be that you're hitting an edge case of modules that Babel can't emulate in CommonJS, so doing ES6 -> Babel CommonJS ->Webpack could fail where ES6 -> Webpack works. As far as I'm aware those edge cases are pretty rare, but if they do come up, they'd likely be around `export * from` which you are using a bit of, so it's possible.

There's no rush, and it seems like you've got a couple options for moving forward at least. If you do have time to put together an example at some point it'd certainly be appreciated, at least to verify that there isn't actually a bug somewhere we've missed.

**Comment by jrencz** [comment] 2017-12-29 19:01
> they'd likely be around export * from which you are using a bit of

to be honest I actually use a lot of it.

My project consists of a tree of similar "components".

Each has its own `./lib` which has the logic. Each `./lib` has `index.js which gathers named outputs from the inner directories' indices.

**Comment by loganfsmyth** [comment] 2018-03-05 05:37
I think I'm going to close this since it isn't actionable for us, but if you can put together a reproducible example feel free to reopen.

**Closed by loganfsmyth** 2018-03-05 05:37 UTC
