### ISSUE TITLE
Typescript constructor property assigment 

### ISSUE THREAD

**Issue by Xesenix** [babel/babel#8328] opened 2018-07-15 21:09 UTC
## Bug Report

**Current Behavior**
After updating to `babel v7.0.0-beta.53` I can't use typescript assignment to class properties like this:
```typescript
class A {
  constructor(
    private privateProperty: any,
    protected protectedProperty: any,
    public publicProperty: any,
  ) {
    this.privateProperty; // not set during runtime
    this.protectedProperty; // not set during runtime
    this.publicProperty; // not set during runtime
  }
}

const a = new A('nothing', 'from', 'this will be set');
```

**Input Code**
Example https://github.com/Xesenix/xes-typescript-playground/tree/typescript-constructor-example run `npm run serve` in console you will see `undefined` for the class A property.

```typescript
class A {
	constructor(
		public property: any,
	) {}
};

const a = new A('test');

console.log('property', a.property); // undefined and i would expect this to be `test`
```

**Expected behavior/code**
I expect that properties defined via constructor are filed with values feed to the constructor when creating an instance of class.

**Babel Configuration (.babelrc, package.json, cli command)**
The minimal case is available here https://github.com/Xesenix/xes-typescript-playground/tree/typescript-constructor-example

**Environment**
- Babel version: v7.0.0-beta.53
- Node/npm version: 10.4.1
- OS: Windows 7
- How you are using Babel: webpack-4 loader

**Comment by miluoshi** [comment] 2018-08-01 08:05
duplicate of https://github.com/babel/babel/issues/7074

**Comment by Xesenix** [comment] 2018-08-01 21:04
@miluoshi I agree it looks similar I'm bad at searching

**Comment by nicolo-ribaudo** [comment] 2018-08-02 06:41
I'm closing this issue, let's keep only that one open.

**Closed by nicolo-ribaudo** 2018-08-02 06:41 UTC
