### ISSUE TITLE
Subclass of Function doesn't return expected instanceof

### ISSUE THREAD

**Issue by daurnimator** [babel/babel#5724] opened 2017-05-10 08:46 UTC
### Input Code

```
class function_proxy extends Function {
  constructor () {
    super([], "return 1");
  }
}
let a = new function_proxy();
console.log(a instanceof function_proxy)
```

### Expected Behavior
`true`

### Current Behavior
`false`

### Context
I'm trying to find a way to create an object that can be called but still works with `instanceof`.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  babel-core@6.24.1
| node             |  v7.9.0
| npm              | 4.5.0
| Operating System |

**Comment by xtuc** [comment] 2017-05-10 09:30
See https://babeljs.io/docs/usage/caveats/#classes, currently we cannot extend built-in classes properly.

Duplicate of #5713 and #4480

**Closed by xtuc** 2017-05-10 09:30 UTC
