### ISSUE TITLE
[Bug]: Typescript plugin fails on named tuple positions where the name is a reserved word in JS

### ISSUE THREAD

**Issue by happycollision** [babel/babel#13702] opened 2021-08-24 21:12 UTC
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

```
type FuncWithDescription = [
  function: (...args: any[]) => any,
  string: string
]
```

https://babeljs.io/repl#?browsers=defaults&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=C4TwDgpgBAYgrgOwMYHUCWwAWARCBnJAJzTGDQHsEoBeKAbQCgooAzRJMygLigAoA6QQENCAczw8hCEHQC6AShoA-KFJAAaJlDzBiCUTx17RDWQwZJKO1gnRZcBYqQoIJsdnZz4iJTgjk09FrMdLwAHlwIcAC2AEYQhIrUKmHqUABEhBDAcIRUWNBRcQnpsprMIeGRMfGEaSDVxYnKUGEAVBoZ0XAANmRgPSBQBVBFtXilpkA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2%2Ctypescript&prettier=false&targets=&version=7.15.3&externalPlugins=&assumptions=%7B%7D

### Configuration

See REPL link

#### Current
It throws at line 2: `/repl.tsx: Unexpected token (2:2)`
If you rename `function` to `fn`, then
it throws at line 3: `Tuple members must be labeled with a simple identifier. (3:2)`

#### Expected
It does not throw an error on either line. Why would I expect this? Because TS is totally fine with this same code: https://www.typescriptlang.org/play?ts=4.0.2#code/C4TwDgpgBAYgrgOwMYHUCWwAWARCBnJAJzTGDQHsEoBeKAbQFgAoKVqAM0STMoC4oAFADoRAQ0IBzPP1EIQdALoBKagD4oskABpmbKHmDEEE-gaMTmC5sySUDHBOiy4CxUhQTTYXJznxESHgRFGnpdNjoBAA9eBDgAWwAjCEIlGnUorSgAIkIIYDhCKixoOKSU7IUdFgjo2ITkwiyQevLU9KgogCptHPi4ABsyMAGQKBKoMsa8SssgA

### Environment

See REPL link for env details

### Possible solution

There are two ways to fix this problem, in my opinion

#### Option 1: Updated docs, and better error messages

Indicate in the docs (just like with [other caveats](https://babeljs.io/docs/en/babel-plugin-transform-typescript#caveats)) that there are certain tokens that are not acceptable for named tuple positions.

Then, ensure that the errors thrown in my example above clearly state this problem and/or reference the newly updated docs. I think the second error (`Tuple members must be labeled with a simple identifier.`) is possibly acknowledging this discrepancy, but it is not clear to me that the error is a known caveat vs an actual TS syntax issue. (The first error thrown against the word `function`, though, is quite vague.)

#### Option 2: Update the TypeScript plugin to handle these names

I do not know how many words fail in the Babel plugin, and yet succeed in TS. I do know that the following are in the list:

- `function`
- `string`
- `number`

**Comment by nicolo-ribaudo** [comment] 2021-08-29 16:50
Thanks for the bug report!

The problem is in the `tsParseTupleElementType` parser function: https://github.com/babel/babel/blob/1355d0078ca4df9e38f382d2f42684b860e60f6d/packages/babel-parser/src/plugins/typescript/index.js#L882-L892

Keywords are not valid types (i.e. `type X = [function]` is invalid), so the `tsParseType()` call at line 888 fails. We should be able to fix it by:
1. Checking if the current token is a keyword (if `this.state.type.keyword` is `true`)
  1. If it is not a keyword, then we can keep the current logic.
  2. Otherwise, we should:
    1. Parse the label as an identifier, using `this.parseIdentifier(/* allow keywords */ true)`.
    2. Consume a `:` token, using `this.expect(tt.colon)`.
    3. Finish parsing the tuple element, as in https://github.com/babel/babel/blob/1355d0078ca4df9e38f382d2f42684b860e60f6d/packages/babel-parser/src/plugins/typescript/index.js#L910-L911

---



If anyone wants to help fixing this bug and it is the first time that you contribute to Babel, follow these steps: (you need to have `make` and `yarn` available on your machine)
1. **Write a comment there** to let other possible contributors know that you are working on this bug.
1. Fork the repo
1. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
1. Run `yarn && make bootstrap`
1. Wait :hourglass_flowing_sand: 
1. Run `make watch` (or `make build` whenever you change a file)
1. Add a test (only `input.ts`; `output.json` will be automatically generated) in https://github.com/babel/babel/tree/main/packages/babel-parser/test/fixtures/typescript/types
   - We need a test for the valid case (the example in the bug report) and for the invalid case `[function]`.
1. Update the code!
1. `yarn jest parser` to run the tests
    - If some test outputs don't match but the new results are correct, you can delete the bad `output.js` files and run the tests again
    - If you prefer, you can run `OVERWRITE=true yarn jest parser` and they will be automatically updated.
    - New parser tests sometimes fail: don't worry, run `yarn jest parser` again after that 
1. If it is working, run `make test` to run all the tests
1. Run `git push` and open a PR!

**Comment by ChaitanyaGadodia** [comment] 2021-08-29 17:27
Hi! Can I pick this bug?

**Comment by nicolo-ribaudo** [comment] 2021-08-29 17:52
Sure, it's yours!

**Comment by aimanjaffer** [comment] 2021-09-02 18:35
@nicolo-ribaudo Once a check is added to handle situations where the current token is a keyword, should the code currently from line 889 to 922 be executed in both situations i.e. when the current token is a keyword and when it is not, or should this section execute only when the current token is not a keyword?

**Comment by aimanjaffer** [comment] 2021-09-03 09:20
Hey @nicolo-ribaudo pardon my ignorance, I'm new to this codebase and I was wondering if there is any documentation for the internal methods such as `this.eat()` and `this.expect()`. Will greatly appreciate your assistance!

**Comment by fedeci** [comment] 2021-09-03 11:31
Nope, there are no docs available for internal parser methods, however you can ask on [Slack](https://slack.babeljs.io/) and you will surely find someone that can help you.
For example `eat(_token)` checks if the specified token matches the current state, if it does the methods skips it returning true, if it doesn't the methods returns false. It is just a sugar for `.matches(_token)` and `.next()`.

`expect(_token)` instead returns `unexpected()` error if the current state token does not match the provided one.

**Comment by aimanjaffer** [comment] 2021-09-03 11:35
@fedeci Thank you so much for the explanation. Will definitely use the slack channel for these sorts of queries in the future!!

**Comment by nicolo-ribaudo** [comment] 2021-09-03 13:48
@aimanjaffer If you are asking because of this bug, please first leave some time (one more week) for @ChaitanyaGadodia since this bug is assigned to him :pray:

**Comment by aimanjaffer** [comment] 2021-09-03 14:56
@nicolo-ribaudo Sure thing!!

**Comment by ozanhonamlioglu** [comment] 2022-01-03 18:47
@nicolo-ribaudo 
If this bug is not maintained since September, can I take it? I want to solve it and it is gonna be my first issue.
Thanks

**Comment by macluiggy** [comment] 2022-02-23 00:21
I think the syntax is no correct, you should write this instead:
type FuncWithDescription = {
  function: (...args: any[]) => any,
  string: string
}

const fnWithDescriptions: FuncWithDescription[] = [
  {
    function: (a,b,c) => a+b+c,
    string: 'Some string'
  }
]

**Comment by happycollision** [comment] 2022-02-23 01:56
@macluiggy 
I am defining a named tuple, not a function that has an extra property. It’s valid syntax, but Babel gets confused.

@ozanhonamlioglu
I am not a team member, but I am willing to bet you can grab it. 🤷‍♂️

**Comment by ayush9398** [comment] 2022-08-15 18:55
@nicolo-ribaudo I see there is a PR in draft state, is this issue still available?

**Comment by Harpica** [comment] 2023-02-14 19:53
Hello!
I tried to solve this issue (pr https://github.com/babel/babel/pull/15423 ), judging by the local test results (.\make test), everything seems to work locally, but some ci tests fail. Could somebody give me some guidence on this problem, please?

**Closed** 2023-03-14 14:02 UTC
Labels: good first issue, i: bug, pkg: parser, area: typescript
