### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by maystrenkoYurii** [babel/babel#9147] opened 2018-12-07 15:30 UTC
Help. The server has a babel-node 6.5.3 installed globally, but @babel/node - 7.2.0 is used in the react project. When starting the command `"start:dev:server": "npm run clear && cross-env NODE_ENV=development BUILD_ENV=production babel-node -- ./src/mount/server.js"` on the nginx server, the compilation uses global 6.5.3 instead of local 7.2.0. Because of this, the project is not compiled.

**Comment by hzoo** [comment] 2018-12-07 16:15
Hi @maystrenkoYurii! A maintainer of the project has notified me that you're missing
some information we'll need to replicate this issue.

Please understand that we receive a high volume of issues, and there are only a limited number
of volunteers that help maintain this project. The easier it is for us to decipher an issue with the info provided,
the more likely it is that we'll be able to help.

Please make sure you have the following information documented in this ticket:

1. Your Babel configuration (typically in the form of a `.babelrc`)
2. The current (incorrect) behavior you're seeing
3. The behavior you expect
4. A [short, self-contained example](http://sscce.org/)

Please provide either a link to the problem via the [`repl`](https://babeljs.io/repl/), or if the `repl` is insufficient,
a new and minimal repository with instructions on how to build/replicate the issue.

**Comment by danez** [comment] 2018-12-15 21:17
This seems to be a problem with your setup. We usually do not recommend installing babel globally, and especially not two different versions of babel at the same time.

You can try using `./node_modules/.bin/babel-node` directly in your project to get the correct version.

Closing this though as not a bug with babel.

**Closed by danez** 2018-12-15 21:17 UTC
Labels: Needs Info, i: bug
