### ISSUE TITLE
Bug when parsing getters/setters with estree + typescript: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by bradzacher** [babel/babel#12335] opened 2020-11-08 19:42 UTC
## Bug Report

- [ ] I would like to work on a fix!

**Input Code**

```js
const babel = require('@babel/parser');
babel.parse(
  'class Foo { get test() {} }',
  {
    plugins: ['estree', 'typescript']
  }
);
```

**Actual behaviour**

```
Thrown:
TypeError: Cannot read property '0' of undefined
    at Object.getGetterSetterExpectedParamCount (/Users/bradzacher/github/typescript-eslint/packages/typescript-estree/node_modules/@babel/parser/lib/index.js:7318:37)
    at Object.checkGetterSetterParams (/Users/bradzacher/github/typescript-eslint/packages/typescript-estree/node_modules/@babel/parser/lib/index.js:11022:29)
    at Object.parseClassMemberWithIsStatic (/Users/bradzacher/github/typescript-eslint/packages/typescript-estree/node_modules/@babel/parser/lib/index.js:12600:12)
    at Object.parseClassMemberWithIsStatic (/Users/bradzacher/github/typescript-eslint/packages/typescript-estree/node_modules/@babel/parser/lib/index.js:6851:11)
    at Object.parseClassMember (/Users/bradzacher/github/typescript-eslint/packages/typescript-estree/node_modules/@babel/parser/lib/index.js:12501:10)
    at callParseClassMember (/Users/bradzacher/github/typescript-eslint/packages/typescript-estree/node_modules/@babel/parser/lib/index.js:6815:13)
    at Object.parseClassMember (/Users/bradzacher/github/typescript-eslint/packages/typescript-estree/node_modules/@babel/parser/lib/index.js:6821:7)
```

**Environment**

```
  System:
    OS: macOS 10.15.7
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
  npmPackages:
    @babel/parser: ^7.12.5 => 7.12.5 
    @babel/types: ^7.12.6 => 7.12.6
```

**Possible Solution**

**Additional context**

**Comment by nicolo-ribaudo** [comment] 2020-11-08 20:12
Duplicate of https://github.com/babel/babel/issues/12255. There is already a PR for this, so hopefully it will be fixed soon!

**Closed by nicolo-ribaudo** 2020-11-08 20:12 UTC
Labels: i: bug, i: needs triage
