### ISSUE TITLE
Vue-server-render throws ERR_REQUIRE_ESM error on importing @babel/runtime

### ISSUE THREAD

**Issue by sns45** [babel/babel#12223] opened 2020-10-20 02:33 UTC
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

Getting this error during runtime:
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/user/page/node_modules/@babel/runtime-corejs2/helpers/esm/arrayWithHoles.js
require() of ES modules is not supported.
require() of /Users/user/page/node_modules/@babel/runtime-corejs2/helpers/esm/arrayWithHoles.js from /Users/user/page/node_modules/vue-server-renderer/build.prod.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename arrayWithHoles.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/user/page/node_modules/@babel/runtime-corejs2/helpers/esm/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1217:13)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at /Users/user/page/node_modules/vue-server-renderer/build.prod.js:1:77377
    at Object.88c0 (js/main.d22015d4.js:1:174813)
    at n (webpack/bootstrap:33:22)
    at Module.0419 (js/main.d22015d4.js:1:61923)
    at n (webpack/bootstrap:33:22)
```
`@babel/runtime-corejs2` is sub-dependency of my direct dependency `@vue/cli-plugin-babel`:
└─┬ @vue/cli-plugin-babel@3.4.0
  └─┬ @vue/babel-preset-app@3.12.1
    └── @babel/runtime-corejs2@7.12.1 

Its working fine when I try to override a sub-dependency by doing `npm i @babel/runtime-corejs2@7.11.2`. After which, `npm ls @babel/runtime-corejs2` results this:
page@0.2.0 /Users/user/page
├── @babel/runtime-corejs2@7.11.2 
└─┬ @vue/cli-plugin-babel@3.4.0
  └─┬ @vue/babel-preset-app@3.12.1
    └── @babel/runtime-corejs2@7.11.2  deduped

This means the problem is with the newly released version of `@babel/runtime-corejs2@7.12.1`

Sorry, I currently don't have a minimal repro for my company's code. I am working on it. 

**Expected behavior**

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
module.exports = {
	presets: [
		'@vue/app',
	]
};

```

**Environment**

```

  System:
    OS: macOS 10.15.7
  Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
  npmPackages:
    babel-core: 7.0.0-bridge.0 => 7.0.0-bridge.0 
    babel-eslint: 10.0.1 => 10.0.1 
    babel-jest: 23.6.0 => 23.6.0 
    babel-plugin-component: 1.1.1 => 1.1.1 
    eslint: 5.8.0 => 5.8.0 

```
**Possible Solution**

**Additional context**

**Comment by Andarist** [comment] 2020-10-20 07:54
The provided configuration is somewhat insufficient for us to immediately spot the issue. Please provide a **runnable** repro case which we could investigate.

This happens because of `require('@babel/runtime-corejs2/helpers/esm/arrayWithHoles.js')` call somewhere, but how it got into your project is an unknown for me (given the provided report).

**Comment by nicolo-ribaudo** [comment] 2020-10-20 09:17
Are you using `@babel/node` or `@babel/register`?

**Comment by re3lex** [comment] 2020-10-22 09:43
I see this issue too.
One observation: it is not reproducible on Mac, but on Windows10 only in my case.

**Comment by nicolo-ribaudo** [comment] 2020-10-22 10:00
Can you try running the build command with the `BABEL_SHOW_CONFIG_FOR=[name of the file containing require]` env variable?

Where `[name of the file containing require]` would be, for example, `/foo/bar.js` in the following error message:

```
require() of /foo/@babel/runtime-corejs2/helpers/esm/arrayWithHoles.js from /foo/bar.js is an ES module file ...
```

This will help understanding why there is a wrong `require` call there.

**Comment by re3lex** [comment] 2020-10-22 11:37
hi @nicolo-ribaudo 
`vue-cli-service` is used to build the code.

I have tried to apply this flag in different ways but looks like `vue-cli-service` is not transferring it or just ignoring or not printing the output. Not sure.

**Comment by nicolo-ribaudo** [comment] 2020-10-22 11:44
Maybe you can try editing `node_modules/@babel/core/lib/index.js` and adding `process.env.BABEL_SHOW_CONFIG_FOR = "..."` as the first line. It should output some info to the console.

**Comment by re3lex** [comment] 2020-10-22 11:50
did that: no debug messages from babel.
Tried absolute and relative paths to `./node_modules/vue-server-renderer/build.prod.js` file
Also tried normal and reverse slash in the path (I'm on Windows10), but no luck.

**Comment by nicolo-ribaudo** [comment] 2020-10-22 11:57
You could try adding this to your Babel config:
```diff
  module.exports = {
+   ignore: [/vue-server-renderer/],
    presets: [
      '@vue/app',
    ]
  };
```
However, it's more a workaround than a fix (the problem is somewhere else).

**Comment by re3lex** [comment] 2020-10-22 12:08
I have added this option into my `babel.config.js` file, did build, started server, but still error exists and no babel debug messages

**Comment by JLHwung** [comment] 2020-10-27 16:59
Please share a reproduction repo, otherwise it is difficult to triage what is going wrong here.

**Comment by sns45** [comment] 2020-10-28 05:50
Here's a repro repo:
https://github.com/sns45/esm-issue
To get started. Simply clone, 
do npm install using node 12, 
npm run build 
npm run start

Sorry for all the jargon my repro has. 

In my repro, a super weird thing is:
If I comment out this function(which is not even used):
https://github.com/sns45/esm-issue/blob/dbdd0071be1651616e3cec11dbcfc488cd5d778d/src/store/modules/cms.es6.js#L39

then it does NOT throw that error. So weird.

**Comment by JLHwung** [comment] 2020-10-28 14:16
As a workaround, add `VUE_CLI_BABEL_TRANSPILE_MODULES=true` to your server renderer build scripts.
```diff
--- "build:server": "cross-env WEBPACK_TARGET=node vue-cli-service build",
+++"build:server": "cross-env WEBPACK_TARGET=node VUE_CLI_BABEL_TRANSPILE_MODULES=true vue-cli-service build",
```
For more info, see https://github.com/vuejs/vue-cli/issues/6018.

**Comment by Andarist** [comment] 2020-10-28 22:03
Note that this probably should be solved by Babel 8 (I believe that providing a proper dual-mode setup for those helpers is on the Babel 8 list) and the used solution could be backported to Babel 7 as an opt-in for `@babel/plugin-transform-runtime` but I'm not sure how this aligns with your roadmap.

The whole need to specify the flavor of what paths will be inserted into the transpiled file is a source of such mismatches so if you could eliminate that then the problem would be solved altogether.

**Comment by joaomede** [comment] 2020-11-19 03:17
hey guys, I managed to solve the problem by making two modifications:
in file "@babel/runtime/helpers/esm/defineProperty.js" I edit "export default to module.exports",
result:
```js
module.exports = function _defineProperty(obj, key, value) {
  if (key in obj) {
    Object.defineProperty(obj, key, {
      value: value,
      enumerable: true,
      configurable: true,
      writable: true
    });
  } else {
    obj[key] = value;
  }

  return obj;
}
```
and package.json

```json
{
  "type": "module"
}
```
I erased "type": "module" and and everything works normally

**Comment by joaomede** [comment] 2020-11-20 14:42
guys, this solved the problem in my case,

file "babel.config.js"
```js
module.exports = {
  presets: [
    [
      '@vue/app',
      {
        useBuiltIns: 'entry',
      },
    ],
  ]
}
```

**Comment by nicolo-ribaudo** [comment] 2021-01-31 22:07
I'm closing this issue since it's a `vue-cli` bug.

In Babel 7.13.0 it will be easier for `vue-cli` to avoid it, but it's already fixable.

**Closed by nicolo-ribaudo** 2021-01-31 22:07 UTC
Labels: area: downstream, i: bug
