### ISSUE TITLE
Webpack+babel produces code that is suboptimal for minification

### ISSUE THREAD

**Issue by jimbolla** [babel/babel#2596] opened 2015-10-26 14:34 UTC
X-post from https://github.com/webpack/webpack/issues/1544:

For example, if I have the js:

```javascript
    import React, {PropTypes} from "react";

    import Branding from "./Branding";

    const Layout = ({children, customSignIn}) => (
        <div className="container" style={{marginTop: 60}}>
            <div className="well" style={{padding: 50}}>

                <div className="panel-body">
                    <div className="col-lg-6" style={{textAlign: "center"}}>
                        <Branding customSignIn={customSignIn} />
                    </div>
                    <div className="col-lg-6">
                        {children}
                    </div>
                </div>
            </div>
        </div>
    );

    Layout.propTypes = {
        children:     PropTypes.node,
        customSignIn: PropTypes.string,
    };

    export {Layout as default};
```

Webpack+babel produces:

```javascript
    "use strict";
    
    Object.defineProperty(exports, "__esModule", {
        value: true
    });
    
    function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { "default": obj }; }
    
    var _react = __webpack_require__(3);
    
    var _react2 = _interopRequireDefault(_react);
    
    var _Branding = __webpack_require__(283);
    
    var _Branding2 = _interopRequireDefault(_Branding);
    
    var Layout = function Layout(_ref) {
        var children = _ref.children;
        var customSignIn = _ref.customSignIn;
        return _react2["default"].createElement(
            "div",
            { className: "container", style: { marginTop: 60 } },
            _react2["default"].createElement(
                "div",
                { className: "well", style: { padding: 50 } },
                _react2["default"].createElement(
                    "div",
                    { className: "panel-body" },
                    _react2["default"].createElement(
                        "div",
                        { className: "col-lg-6", style: { textAlign: "center" } },
                        _react2["default"].createElement(_Branding2["default"], { customSignIn: customSignIn })
                    ),
                    _react2["default"].createElement(
                        "div",
                        { className: "col-lg-6" },
                        children
                    )
                )
            )
        );
    };
    
    Layout.propTypes = {
        children: _react.PropTypes.node,
        customSignIn: _react.PropTypes.string
    };
    
    exports["default"] = Layout;
    module.exports = exports["default"];
```

Notice all the instances of `_react2["default"]`... these don't minify well because the "default" is not minified. What would be better would be if webpack added a `var _reactDefault = _react2["default"];` declaration at the top and used that instead.

Notice it also "inlined" my PropTypes definition and the usage became `_react.PropTypes`. Again, this is less minifiable than if it had generated `var _reactPropTypes = _react.PropTypes`.

This pattern isn't specific to React, but React code certainly suffers greatly from it.

**Comment by loganfsmyth** [comment] 2015-10-26 15:45
This is a duplicate of https://github.com/babel/babel/issues/1341, among others.

We can either get short imports or ES6 spec-compliant code, but not both. If you want shorter code, you can always use `require` directly. Keep in mind though that once your code is gzipped (which you should be doing), the size over the wire should be essentially the same.

**Closed** 2015-10-26 15:46 UTC
