### ISSUE TITLE
[preset-typescript] Re-export of interface fails 

### ISSUE THREAD

**Issue by johannes-z** [babel/babel#11464] opened 2020-04-22 06:58 UTC
## Bug Report

- [ ] I would like to work on a fix!

**Current Behavior**
I'm trying to bundle typescript with rollup and `@babel/preset-typescript`, but re-exporting an interface fails:

```
[!] Error: 'ITest' is not exported by src/types.ts, imported by src/main.ts
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
src/main.ts (1:9)
1: export { ITest } from './types'
            ^
Error: 'ITest' is not exported by src/types.ts, imported by src/main.ts
```

**Input Code**
- REPL or Repo link if applicable: I've prepared a Repo here: https://github.com/johannes-z/vue-lib-starter/tree/bug/babel-typescript. Please note the two `src`-files, and `build/rollup.config.esm.js`. You can run this repro by following these steps:

```sh
git clone ... # make sure to checkout branch bug/babel-typescript
yarn install
yarn build:module
```

```ts
// ./src/types.ts
export interface ITest {
  test: string
}

// ./src/main.ts
export { ITest } from './types'
```

**Expected behavior/code**
An empty file should be emitted.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `build/rollup.config.esm.js`

```js
{
      exclude: /node_modules/,
      extensions: ['.js', '.jsx', '.ts', '.tsx', '.vue'],
      plugins: [],
      babelrc: false,
      configFile: false,
      presets: [
        ['@babel/preset-typescript', {}],
        // basically preset-env; but not really used in my repro
        ['@vue/cli-plugin-babel/preset', {
          modules: false,
          useBuiltIns: false,
          polyfills: [],
        }],
      ],
    }
```

**Environment**

```
  System:
    OS: Linux 4.4 Ubuntu 18.04.4 LTS (Bionic Beaver)
  Binaries:
    Node: 13.13.0 - /usr/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.4 - /usr/bin/npm
  npmPackages:
    @babel/preset-typescript: ^7.9.0 => 7.9.0
    eslint: ^6.8.0 => 6.8.0
    rollup-plugin-babel: ^4.4.0 => 4.4.0
```

**Comment by nicolo-ribaudo** [comment] 2020-04-22 07:37
You can use
```js
export type { ITest } from './types'
```

The problem is that, by looking at that code (Babel works on a per-file basis), it's impossible to know that it is a type.

**Comment by nicolo-ribaudo** [comment] 2020-04-22 07:42
I'm closing this because:
- Babel's documented goal is to match TS's `--isolatedModules` mode, which [disallows that code](https://github.com/babel/babel/issues/10856#issuecomment-565279868)
- It can be easily worked around be explicitly marking the type export.

**Closed by nicolo-ribaudo** 2020-04-22 07:42 UTC
Labels: i: bug
