### ISSUE TITLE
[Bug]: generateUidIdentifierBasedOnNode with JSX returning `_objectObject`

### ISSUE THREAD

**Issue by blaumeise20** [babel/babel#14418] opened 2022-04-03 10:20 UTC
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

```js 
visitors: {
    JSXElement(path) {
        console.log(path.generateUidIdentifierBasedOnNode(path.node));
        // logs `_objectObject`
    }
}
```

### Current and expected behavior

Logs `_objectObject` to the console, but should log `_div` when calling with `<div></div>`

### Environment

```
  System:
    OS: macOS 10.15.7
  Binaries:
    Node: 17.7.2 - /usr/local/bin/node
    npm: 7.14.0 - /usr/local/bin/npm
  npmPackages:
    @babel/helper-plugin-utils: ^7.16.7 => 7.16.7 
    @babel/plugin-syntax-jsx: ^7.16.7 => 7.16.7 
    @babel/types: ^7.17.0 => 7.17.0 
```

### Possible solution

Change https://github.com/babel/babel/blob/982175b043d6e2c1439e55b473e69c786522d1fd/packages/babel-traverse/src/scope/index.ts#L201 to call `gatherNodeParts(node.name, parts)`.

**Comment by nicolo-ribaudo** [comment] 2022-04-04 20:28
Thanks for the bug report!

If it is the first time that you contribute to Babel, follow these steps: (you need to have `make` and `yarn` available on your machine)
1. **Write a comment there** to let other possible contributors know that you are working on this bug.
1. Fork the repo
1. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
1. Run `yarn && make bootstrap`
1. Wait :hourglass_flowing_sand: 
1. Run `make watch` (or `make build` whenever you change a file)
1. Add a test in `packages/babel-traverse/test/scope.js` (it looks like we don't have any test for that function yet, it's only tested in transform fixtures)
1. Update the code!
1. `yarn jest traverse` to run the tests
1. If it is working, run `make test` to run all the tests
1. Run `git push` and open a PR!

If you have any questions, feel free to ask!

**Comment by SophonieBouye** [comment] 2022-07-29 15:07
Hi @nicolo-ribaudo , it's still possible to work on this issue ?

**Comment by blaumeise20** [comment] 2022-07-29 17:14
Wow, I forgot that. I will try to fix it as soon as I can!

**Comment by EliphazBouye** [comment] 2022-08-01 12:46
Okay Nice 🚀

**Comment by AnmolBansalDEV** [comment] 2022-08-06 19:05
Can I work on this issue?

**Comment by blaumeise20** [comment] 2022-08-06 19:06
If you want ofc! I don't have much time anyways 😀

**Comment by AnmolBansalDEV** [comment] 2022-08-10 14:40
yes! was busy that's why couldn't reply

**Comment by AnmolBansalDEV** [comment] 2022-08-10 16:37
hey, I went through the file, the proposed change has already been applied

**Comment by JLHwung** [comment] 2022-08-10 17:03
@AnmolBansalDEV You are right. It has been fixed in #14648, specifically mentioned in https://github.com/babel/babel/pull/14648#discussion_r892676665.

Closing it as it has been fixed in another PR.

**Closed by JLHwung** 2022-08-10 17:03 UTC
Labels: good first issue, i: bug, pkg: traverse

**Comment by AnmolBansalDEV** [comment] 2022-08-10 17:08
Thank you for replying, although the issue is resolved. I'm new to open source, and few weeks into it I'm feeling lost. Can you guide me please .
 Thank you!

**Comment by saamuuel** [comment] 2022-08-24 18:29
@AnmolBansalDEV  read contribution rules and just take a issue and work on it ;)
