### ISSUE TITLE
EventTarget works in browser but not for babel

### ISSUE THREAD

**Issue by coodoo** [babel/babel#8329] opened 2018-07-16 00:59 UTC
```js
class MyTarget extends EventTarget {}
const target = new MyTarget();
target.addEventListener('move', () => console.log('target moved'));
target.dispatchEvent(new Event('move'));
```

Above code runs fine in Chrome devtools console, but when transpiled with babel, it crashes with following messages.

```
Uncaught TypeError: Failed to construct 'EventTarget': Please use the 'new' operator, this DOM object constructor cannot be called as a function.
```

Environment:
Chrome Canary Version 69.0.3492.0 (Official Build) canary (64-bit)
Babel 6.23.0

**Comment by jridgewell** [comment] 2018-07-16 01:06
This is fixed in v7. Dupe of https://github.com/babel/babel/issues/4480.

**Closed by jridgewell** 2018-07-16 01:06 UTC

**Comment by coodoo** [comment] 2018-07-16 01:11
Kudos for the fix and super quick response! 👍👍
