### ISSUE TITLE
[BUG] JSX transform fails when combined with rest spread.

### ISSUE THREAD

**Issue by 10xjs** [babel/babel#5663] opened 2017-04-25 08:05 UTC
A function with a destructured object argument and a rest spread value that returns single JSX tag with a descendent function which returns a JSX tag that references a value from the destructured argument is not correctly transformed.

### Input Code
```js
({b, ...p}) => <a>{() => <c x={b}/>}</a>;
```

### Babel Configuration
```js
{
  "plugins": [
    "babel-plugin-transform-react-constant-elements",
    "babel-plugin-transform-react-jsx",
    "babel-plugin-syntax-jsx",
    "babel-plugin-transform-es2015-destructuring",
    "babel-plugin-transform-object-rest-spread",
    "babel-plugin-transform-react-inline-elements"
  ]
}
```

### Expected Behavior
```js
(_ref) => {
  let b = _ref.b,
      p = _objectWithoutProperties(_ref, ["b"]);

  return _jsx("a", {}, void 0, () => _jsx("c", {
    x: b
  }));
};
```

### Current Behavior

The innermost jsx tag is not transformed. If the rest spread (`...p`) is removed or the inner JSX tag does not reference `b` as a prop value (`x={b}`), it is transformed as expected.

```js
((_temp = _ref, _ref2 = <c x={b} />, _temp)) => {
  var _temp, _ref2;

  let b = _ref.b,
      p = _objectWithoutProperties(_ref, ["b"]);

  return _jsx("a", {}, void 0, () => _ref2);
};
```

### Environment

| software         | version(s)
| ---------------- | -------
| Babel            | 6.24.1 
| node             | 6.3.1| Operating System | Mac OS 10.11.6

**Comment by existentialism** [comment] 2017-05-01 14:01
Looks like this is an issue specifically with `babel-plugin-transform-react-constant-elements`, without it:

```jsx
var _jsx = function () { var REACT_ELEMENT_TYPE = typeof Symbol === "function" && Symbol.for && Symbol.for("react.element") || 0xeac7; return function createRawReactElement(type, props, key, children) { var defaultProps = type && type.defaultProps; var childrenLength = arguments.length - 3; if (!props && childrenLength !== 0) { props = {}; } if (props && defaultProps) { for (var propName in defaultProps) { if (props[propName] === void 0) { props[propName] = defaultProps[propName]; } } } else if (!props) { props = defaultProps || {}; } if (childrenLength === 1) { props.children = children; } else if (childrenLength > 1) { var childArray = Array(childrenLength); for (var i = 0; i < childrenLength; i++) { childArray[i] = arguments[i + 3]; } props.children = childArray; } return { $$typeof: REACT_ELEMENT_TYPE, type: type, key: key === undefined ? null : '' + key, ref: null, props: props, _owner: null }; }; }();

function _objectWithoutProperties(obj, keys) { var target = {}; for (var i in obj) { if (keys.indexOf(i) >= 0) continue; if (!Object.prototype.hasOwnProperty.call(obj, i)) continue; target[i] = obj[i]; } return target; }

(_ref) => {
  let b = _ref.b,
      p = _objectWithoutProperties(_ref, ["b"]);

  return _jsx("a", {}, void 0, () => _jsx("c", {
    x: b
  }));
};
```

**Comment by jddxf** [comment] 2017-05-01 15:01
It also happens without inline when there's some code before like this:
```
console.log();
({b, ...p}) => (<a>{() => (<c x={b}/>)}</a>);
```

**Comment by apaatsio** [comment] 2017-05-09 09:35
This has been fixed by #5686 

Now the output for 
```js
({b, ...p}) => <a>{() => <c x={b}/>}</a>;
```
is
```js
(_ref) => {
  let b = _ref.b,
      p = _objectWithoutProperties(_ref, ["b"]);

  var _ref2 = _jsx("c", {
    x: b
  });

  return _jsx("a", {}, void 0, () => _ref2);
};
```
which looks correct.

**Comment by rgranger** [comment] 2017-06-26 09:02
Hi guys, i'm still running into this issue with the following input :

# Input : 

```javascript
import React from 'react'

const TestComponent = ({ title, children, ...other }) => {
  const wrapItems = (item, index) => {
    return (
      <div key={index} {...other}>
        <label>{title}</label>
        {item}
      </div>
    )
  }
  return (
    <div>
      {children.map((item, index) => wrapItems(item, index))}
    </div>
  )
}
```

# output :

```javascript
'use strict';

var _extends2 = require('babel-runtime/helpers/extends');

var _extends3 = _interopRequireDefault(_extends2);

var _objectWithoutProperties2 = require('babel-runtime/helpers/objectWithoutProperties');

var _objectWithoutProperties3 = _interopRequireDefault(_objectWithoutProperties2);

var _react = require('react');

var _react2 = _interopRequireDefault(_react);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

var TestComponent = function TestComponent((_temp = _ref, _ref2 = <label>{title}</label>, _temp)) {
  var _temp, _ref2;

  var title = _ref.title,
      children = _ref.children,
      other = (0, _objectWithoutProperties3.default)(_ref, ['title', 'children']);

  var wrapItems = function wrapItems(item, index) {
    return _react2.default.createElement(
      'div',
      (0, _extends3.default)({ key: index }, other),
      _ref2,
      item
    );
  };
  return _react2.default.createElement(
    'div',
    null,
    children.map(function (item, index) {
      return wrapItems(item, index);
    })
  );
};
```
Whereas, when i remove the {...other} :

# Input : 

```javascript
import React from 'react'

const TestComponent = ({ title, children }) => {
  const wrapItems = (item, index) => {
    return (
      <div key={index}>
        <label>{title}</label>
        {item}
      </div>
    )
  }
  return (
    <div>
      {children.map((item, index) => wrapItems(item, index))}
    </div>
  )
}
```

# correct output :

```javascript
'use strict';

var _react = require('react');

var _react2 = _interopRequireDefault(_react);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

var TestComponent = function TestComponent(_ref) {
  var title = _ref.title,
      children = _ref.children;

  var _ref2 = _react2.default.createElement(
    'label',
    null,
    title
  );

  var wrapItems = function wrapItems(item, index) {
    return _react2.default.createElement(
      'div',
      { key: index },
      _ref2,
      item
    );
  };
  return _react2.default.createElement(
    'div',
    null,
    children.map(function (item, index) {
      return wrapItems(item, index);
    })
  );
};
```

Here is my config :

# Babel configuration

```json
{
  "presets": [
    "babel-preset-es2015",
    "babel-preset-react",
    "babel-preset-stage-0"
  ],
  "env": {
    "production": {
      "plugins": [
        "babel-plugin-transform-react-remove-prop-types",
        "babel-plugin-transform-react-constant-elements"
      ]
    }
  },
  "plugins": [
    "babel-plugin-transform-runtime",
    "babel-plugin-transform-decorators-legacy"
  ]
}
```

# Environment

Node : 6.9.1
babel-cli : 6.24.1
babel-core : 6.25.0

**Comment by danez** [comment] 2018-12-03 08:32
I cannot reproduce this anymore with babel 7.1.6, no matter how I order the react-plugins.

In case there are cases where it still happens with the latest babel version please open a new issue with the input code and the configuration or a github repository where it can be reproduced.

**Closed by danez** 2018-12-03 08:32 UTC
Labels: area: react, i: bug
