### ISSUE TITLE
transform-runtime problem with treeshaking

### ISSUE THREAD

**Issue by dantodev** [babel/babel#10097] opened 2019-06-14 12:25 UTC
## Bug Report

**Current Behavior**
In the provided repository there is webpack configured with two entry points: caseA (`src/case-a.js`) and caseB (`src/case-a.js`). Booth files import different named exports from `src/helpers.js`. caseA and its imported functions from helper.js use async/await and Promises which need will be transformed by the transform-runtime plugin. This makes output file relatively big (~31kb).

CaseB doesn't use async/await and Promises and only imports a synchronous function from helper.js but the output size is still as big as the size from caseA. If I disabled the entry caseA and remove the unused functions in helper.js then the output size from caseB drops down to ~1.2kb.

**Input Code**
https://github.com/dantodev/babel-transform-runtime-treeshaking

**Expected behavior/code**
caseB should always be ~1.2kb without the need of manually removing unused functions from the sourcecode. Maybe there is only a missing configuration in this repo. 

Additionally I discovered that in the output files for both cases there are all imported function present not only the imported functions of the respective entry files. But this seams to be a webpack problem as this also happens when I disable babel-loader.

**Babel Configuration (.babelrc, package.json, cli command)**

https://github.com/dantodev/babel-transform-runtime-treeshaking/blob/master/babel.config.js

The build is made by executing `npm run build` on the command line which does:
```bash
cross-env NODE_ENV=production webpack --display-used-export
```

**Environment**
- Babel version(s): v7.4.5
- Node/npm version: Node 10.3.0/npm 6.9.0
- OS: Ubuntu 18.04.1 LTS
- Monorepo: no
- How you are using Babel: babel-loader via Webpack v.3.3.4

**Comment by nicolo-ribaudo** [comment] 2019-06-15 07:52
It's a webpack problem. Try adding this option in your webpack config, to make the webpack output readable:

```
  optimization: {
    minimize: false
  },
```

You'll see that  in `caseB` `testA` isn't used (not even by Babel-generated code), but it's still included.

**Comment by dantodev** [comment] 2019-06-18 19:01
I have added the terser-webpack-plugin and your provided configuration but it did not help. By setting `mangle: false` like you recommended the build size of both caseA and caseB have even increased to ~67kb.

Setting `mangle: { keep_fnames: true },` helped to get same results like with uglifyJS but still caseB is way to big.

I commited the change in my repository. Maybe you or someone else have the time to clone and test it and help me with my problem.

**Comment by nicolo-ribaudo** [comment] 2019-06-18 20:08
With that config I was showing that it's not a Babel bug but a terser/webpack bug: they should remove unused functions but they don't do so.

**Comment by dantodev** [comment] 2019-06-18 22:44
When is set terserOption `compress: { dead_code: true }` the unused Exports now gets removed correctly. Also with the babel-loader enabled. 

I discovered that when I run webpack with multiple entry points booth output files will include all imported methods and not only the ones they imported. But this is wepback problem and not babel related.

But one problem still remains. Even when i remove the entry caseA and only build caseB the output file is ~31kb. If I remove the unused async functions from the helpers.js manually and only `testE()` remains the size drops down to ~1.5kb. So it seams that babel does transforms on the unused exported functions and and terser is then unable to identify the transformed code as dead code.

**Comment by kzc** [comment] 2019-06-19 18:02
> Try adding this option in your webpack config, to prevend webpack from changing function names

The correct way to [disable webpack minification](https://webpack.js.org/configuration/optimization/#optimizationminimize) is:

```js
module.exports = {
  //...
  optimization: {
    minimize: false
  }
};
```

It will show the *unaltered* webpack output.

> When is set terserOption compress: { dead_code: true } the unused Exports now gets removed correctly.

`dead_code` is enabled by default. You've just effectively enabled all the default `compress` options. It is equivalent to `compress: true` or `compress: {}`.

**Comment by dantodev** [comment] 2019-06-21 11:30
Sure, but in the provided configuration in the second comment, compression and mangle where explicitly disabled. Then it is understandable that the code don't get optimized and dead code does not get removed.

My point is: when I **dont** use babel and have dead code removal enabled then webpack/terser does everything right and caseB does only include its imported functions from helper.js in the output. When I use babel the generated code for async/await seams to be generated in a way terser can not detect it as dead code.

I have read another issue some days ago that described an similar problem. Unfortunately i don't find the link to the issue anymore, but I remember that  transpiled async functions are especially hard to treeshake.

**Comment by nicolo-ribaudo** [comment] 2019-06-21 12:50
Sorry for jumping to the wrong conclusion earlier. I checked your bundle again, and I think I now came to the correct conclusion.

> My point is: when I dont use babel and have dead code removal enabled then webpack/terser does everything right and caseB does only include its imported functions from helper.js in the output. 

Can you share _exactly_ which webpack config are you using? When I disable Babel, I get this output: (beautified using https://prettier.io/playground)
<details>
<summary>caseA</summary>

```js
!(function(e, t) {
  "object" == typeof exports && "object" == typeof module
    ? (module.exports = t())
    : "function" == typeof define && define.amd
    ? define([], t)
    : "object" == typeof exports
    ? (exports.caseA = t())
    : (e.caseA = t());
})(window, function() {
  return (function(e) {
    var t = {};
    function n(o) {
      if (t[o]) return t[o].exports;
      var r = (t[o] = { i: o, l: !1, exports: {} });
      return e[o].call(r.exports, r, r.exports, n), (r.l = !0), r.exports;
    }
    return (
      (n.m = e),
      (n.c = t),
      (n.d = function(e, t, o) {
        n.o(e, t) || Object.defineProperty(e, t, { enumerable: !0, get: o });
      }),
      (n.r = function(e) {
        "undefined" != typeof Symbol &&
          Symbol.toStringTag &&
          Object.defineProperty(e, Symbol.toStringTag, { value: "Module" }),
          Object.defineProperty(e, "__esModule", { value: !0 });
      }),
      (n.t = function(e, t) {
        if ((1 & t && (e = n(e)), 8 & t)) return e;
        if (4 & t && "object" == typeof e && e && e.__esModule) return e;
        var o = Object.create(null);
        if (
          (n.r(o),
          Object.defineProperty(o, "default", { enumerable: !0, value: e }),
          2 & t && "string" != typeof e)
        )
          for (var r in e)
            n.d(
              o,
              r,
              function(t) {
                return e[t];
              }.bind(null, r)
            );
        return o;
      }),
      (n.n = function(e) {
        var t =
          e && e.__esModule
            ? function() {
                return e.default;
              }
            : function() {
                return e;
              };
        return n.d(t, "a", t), t;
      }),
      (n.o = function(e, t) {
        return Object.prototype.hasOwnProperty.call(e, t);
      }),
      (n.p = ""),
      n((n.s = 1))
    );
  })([
    function(e, t, n) {
      "use strict";
      async function o() {
        return console.log("testA"), "foo";
      }
      function r(e) {
        return (
          console.log("testC"),
          new Promise(t => {
            setTimeout(t, e);
          })
        );
      }
      function u() {
        return console.log("testE"), "baz";
      }
      n.d(t, "a", function() {
        return o;
      }),
        n.d(t, "b", function() {
          return r;
        }),
        n.d(t, "c", function() {
          return u;
        });
    },
    function(e, t, n) {
      "use strict";
      n.r(t);
      var o = n(0);
      (async () => {
        "foo" === (await Object(o.a)()) &&
          (await Object(o.b)(1e3), console.log("done"));
      })();
    }
  ]);
});
```
</details>
<details>
<summary>caseB</summary>

```js
!(function(e, t) {
  "object" == typeof exports && "object" == typeof module
    ? (module.exports = t())
    : "function" == typeof define && define.amd
    ? define([], t)
    : "object" == typeof exports
    ? (exports.caseB = t())
    : (e.caseB = t());
})(window, function() {
  return (function(e) {
    var t = {};
    function n(o) {
      if (t[o]) return t[o].exports;
      var r = (t[o] = { i: o, l: !1, exports: {} });
      return e[o].call(r.exports, r, r.exports, n), (r.l = !0), r.exports;
    }
    return (
      (n.m = e),
      (n.c = t),
      (n.d = function(e, t, o) {
        n.o(e, t) || Object.defineProperty(e, t, { enumerable: !0, get: o });
      }),
      (n.r = function(e) {
        "undefined" != typeof Symbol &&
          Symbol.toStringTag &&
          Object.defineProperty(e, Symbol.toStringTag, { value: "Module" }),
          Object.defineProperty(e, "__esModule", { value: !0 });
      }),
      (n.t = function(e, t) {
        if ((1 & t && (e = n(e)), 8 & t)) return e;
        if (4 & t && "object" == typeof e && e && e.__esModule) return e;
        var o = Object.create(null);
        if (
          (n.r(o),
          Object.defineProperty(o, "default", { enumerable: !0, value: e }),
          2 & t && "string" != typeof e)
        )
          for (var r in e)
            n.d(
              o,
              r,
              function(t) {
                return e[t];
              }.bind(null, r)
            );
        return o;
      }),
      (n.n = function(e) {
        var t =
          e && e.__esModule
            ? function() {
                return e.default;
              }
            : function() {
                return e;
              };
        return n.d(t, "a", t), t;
      }),
      (n.o = function(e, t) {
        return Object.prototype.hasOwnProperty.call(e, t);
      }),
      (n.p = ""),
      n((n.s = 2))
    );
  })([
    function(e, t, n) {
      "use strict";
      async function o() {
        return console.log("testA"), "foo";
      }
      function r(e) {
        return (
          console.log("testC"),
          new Promise(t => {
            setTimeout(t, e);
          })
        );
      }
      function u() {
        return console.log("testE"), "baz";
      }
      n.d(t, "a", function() {
        return o;
      }),
        n.d(t, "b", function() {
          return r;
        }),
        n.d(t, "c", function() {
          return u;
        });
    },
    ,
    function(e, t, n) {
      "use strict";
      n.r(t);
      var o = n(0);
      "baz" === Object(o.c)() && console.log("done");
    }
  ]);
});
```
</details>

As you can see, `testA`, `testC` and `testE` are still included in both bundles.

Then I removed the `a` entrypoint, re-enabled Babel and this is the output I get. I disabled `core-js` and `transform-runtime` to have a readable output:

<details>
<summary>caseB</summary>

```js
!(function(e, t) {
  "object" == typeof exports && "object" == typeof module
    ? (module.exports = t())
    : "function" == typeof define && define.amd
    ? define([], t)
    : "object" == typeof exports
    ? (exports.caseB = t())
    : (e.caseB = t());
})(window, function() {
  return (function(e) {
    var t = {};
    function n(o) {
      if (t[o]) return t[o].exports;
      var r = (t[o] = { i: o, l: !1, exports: {} });
      return e[o].call(r.exports, r, r.exports, n), (r.l = !0), r.exports;
    }
    return (
      (n.m = e),
      (n.c = t),
      (n.d = function(e, t, o) {
        n.o(e, t) || Object.defineProperty(e, t, { enumerable: !0, get: o });
      }),
      (n.r = function(e) {
        "undefined" != typeof Symbol &&
          Symbol.toStringTag &&
          Object.defineProperty(e, Symbol.toStringTag, { value: "Module" }),
          Object.defineProperty(e, "__esModule", { value: !0 });
      }),
      (n.t = function(e, t) {
        if ((1 & t && (e = n(e)), 8 & t)) return e;
        if (4 & t && "object" == typeof e && e && e.__esModule) return e;
        var o = Object.create(null);
        if (
          (n.r(o),
          Object.defineProperty(o, "default", { enumerable: !0, value: e }),
          2 & t && "string" != typeof e)
        )
          for (var r in e)
            n.d(
              o,
              r,
              function(t) {
                return e[t];
              }.bind(null, r)
            );
        return o;
      }),
      (n.n = function(e) {
        var t =
          e && e.__esModule
            ? function() {
                return e.default;
              }
            : function() {
                return e;
              };
        return n.d(t, "a", t), t;
      }),
      (n.o = function(e, t) {
        return Object.prototype.hasOwnProperty.call(e, t);
      }),
      (n.p = ""),
      n((n.s = 0))
    );
  })([
    function(e, t, n) {
      "use strict";
      n.r(t), "baz" == (console.log("testE"), "baz") && console.log("done");
    }
  ]);
});
```
</details>

As you can see, the unused async functions have been correctly removed and there is only "testE" left.
This is because webpack only remove exports which aren't used in **any** entrypoint: https://github.com/webpack/webpack/issues/4453. This is because when you load both the entry points in a browser, the second entry point can't re-execute `helpers.js` but must use the one executed by the first entry point.

---

Now let's take a look at the other big chunk of code in the bundle: `core-js` polyfills.
You are loading your polyfills both using `useBuiltIns: "entry"` and `transform-runtime`.
The first one loads every core-js polyfill unsupported by your target environments (since you haven't specified them, it loads every polyfill for ES5+ functionality). Since it modifies the global scope and thus isn't side-effect-free, webpack doesn't (and shouldn't) remove it. Let's disable it and only use `transform-runtime`, which should only load polyfills for features that you use but need to be polyfilled.

Even if I only have the "b" entry point, I still get a big output:
```
➜ npm run build

> babel-transform-runtime-treeshaking@0.1.0 build /home/nicolo/Documenti/dev/babel-bugs/babel-transform-runtime-treeshaking
> cross-env NODE_ENV=production webpack --display-used-exports

(node:15595) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
Hash: 926d6e46cf0ad75cd96b
Version: webpack 4.34.0
Time: 458ms
Built at: 2019-06-21 14:31:53
   Asset      Size  Chunks             Chunk Names
caseB.js  30.3 KiB       0  [emitted]  caseB
Entrypoint caseB = caseB.js
[57] (webpack)/buildin/global.js 472 bytes {0} [built]
[98] ./src/case-b.js + 2 modules 3.29 KiB {0} [built]
     | ./src/case-b.js 111 bytes [built]
     | ./src/helper.js 2.35 KiB [built]
     |     [only some exports used: testE]
     |     + 1 hidden module
    + 97 hidden modules
```
Why? It shouldn't need any polyfill, since async functions have been removed by webpack. The problem is that this is what happens:
1. Babel transpiles async functions to promises
2. Babel injects imports for promise polyfill
3. Webpack removes async functions
4. Webpack _does not remove_ imports for promise polyfill.

Why (4)? It's because core-js uses CommonJS, and webpack only three-shakes ECMAScript modules.

**Comment by kzc** [comment] 2019-06-21 13:30
Only unreferenced and unused functions can be dropped. Code with side effects is retained. It's possible that pure annotation comments may not have been emitted on key function calls by babel, regenerator or webpack. Examine the original webpack output prior to minification with `optimization: {minimize: false}` to determine what construct is preventing DCE from working. 

Better yet - remove webpack from the picture entirely and make a single source file test case that only uses babel and see whether its output can be minified correctly with `-b --compress toplevel=true`.

**Comment by dantodev** [comment] 2019-06-21 15:27
I don't have time to test it before weekend, but last time I have tried it the problem only occurred when I had `transform-runtime` enabled. So disabling it to check if it is working is not really a solution.

And you must have cloned an older version of my repository as I have changed the `useBuiltIns` settings to `"usage"` some days ago. I thought when using `@babel/preset-env` this way it would only include the needed polyfills directly where I has to use them.

And also with `@babel/preset-env` babel should use the [provider browserlistrc file](https://github.com/dantodev/babel-transform-runtime-treeshaking/blob/master/browserslistrc) in my repository to only include the needed Polyfills.

That webpack includes all imported functions in all entries is a problem I already discovered earlier. I think I will end up calling webpack twice to prevent this problem. 

----

Little background why i think I have to use the `transform-runtime`. I am building an third party browser library for websites which may use their own polyfills so I can not use global polyfills, This is why I need to regenerate Promises and async/await in place with the smallest possible output.

**Comment by nicolo-ribaudo** [comment] 2019-06-21 15:39
Oh ok, I will clone your repo again with the updated config.

> Little background why i think I have to use the transform-runtime. I am building an third party browser library for websites which may use their own polyfills so I can not use global polyfills, This is why I need to regenerate Promises and async/await in place with the smallest possible output.

Then you shouldn't use `useBuiltIns`. Currently you are injecting polyfills twice: first `@babel/preset-env` injects global polyfills, and then `transform-runtime` injects non-global polyfills.

**Comment by Aymkdn** [comment] 2019-11-28 15:21
Did you find any solution to this issue?

**Comment by liuxingbaoyu** [comment] 2023-11-11 13:27
Because this issue is out of date, I will close it.

**Closed by liuxingbaoyu** 2023-11-11 13:27 UTC
Labels: i: invalid
