### ISSUE TITLE
()=>{}() is not a valid program 

### ISSUE THREAD

**Issue by mohsen1** [babel/babel#2534] opened 2015-10-13 18:13 UTC
```
❯❯ babel --version
5.8.23 (babel-core 5.8.25)
```

input 

```
()=>{}()
```

output
```
"use strict";

(function () {})();
```

expected: 

```
Error: Unexpected token "("
```

**Comment by sebmck** [comment] 2015-10-13 18:14
Duplicate of #2154.

**Closed by sebmck** 2015-10-13 18:14 UTC
