### ISSUE TITLE
Promise Polyfill - No Error Stacktrace

### ISSUE THREAD

**Issue by Aourin** [babel/babel#2508] opened 2015-10-08 16:07 UTC
Seems like Promises throw all errors as unhandled rejections instead of common native implementation to throw the stacktrace. 

```
function brokenFunction (test) {
  return test.length;
}
function workingFunction () {
  return brokenFunction();
}

let moo = new Promise((res) => {
  setTimeout(() => {
    res('Cool');
  }, 100);
});

moo.then((resp) => {
  console.log('Response', resp);
  console.log('call some sync function');

  workingFunction();
});
```

For Example, in Chrome, will give stacktrace. But when running it with babel (polyfill on) it just throws all errors as not being a caught promise rejection.
`Unhandled promise rejection TypeError: Cannot read property 'length' of undefined(…)(anonymous function) @ es6.promise.js:112`

Is it possible to use runtime w/o promise polyfill?

**Comment by davezuko** [comment] 2015-10-08 16:44
To clarify why this is an issue (because clearly it's nice to not have promises silently fail): In a React/Redux application, actions are dispatched from promise handlers. However, these dispatches might result in re-renders that break somewhere down in the component hierarchy, and without the full stack trace it's pretty much impossible to know where exactly the error occurred. This is _not_ the case with native promises, so it would be nice to use babel-runtime without polyfilling promises.

That said, I'm not entirely sure why native promises _aren't_ used, since they seem to work fine in latest Chrome/Canary, though my knowledge is limited in this space so maybe there's a reason for this.

**Comment by jmm** [comment] 2015-10-08 17:09
Hello @Aourin, welcome to the Babel community.
> Is it possible to use runtime w/o promise polyfill?

No, not yet anyway. See https://github.com/babel/babel/issues/2059 and the linked issues.

**Comment by loganfsmyth** [comment] 2015-10-08 17:10
Just to be clear @davezuko, you say "silently fail" but it does print an error for you, right?

I think there may just be a misunderstanding here:
<img width="981" alt="screen shot 2015-10-08 at 10 07 00 am" src="https://cloud.githubusercontent.com/assets/132260/10373820/93a6f39c-6da4-11e5-8d39-4e66203d026d.png">

does show the stacktrace. You need to click the `(...)` on the right instead of the arrow on the left:
<img width="611" alt="screen shot 2015-10-08 at 10 09 15 am" src="https://cloud.githubusercontent.com/assets/132260/10373845/c6ac5e9e-6da4-11e5-937f-b4a0e1a8a46e.png">

**Comment by davezuko** [comment] 2015-10-08 17:15
@loganfsmyth here's what it displays for me (this is with babel-runtime enabled):

![screen shot 2015-10-08 at 1 12 22 pm](https://cloud.githubusercontent.com/assets/6439050/10373907/40878a22-6dbe-11e5-8d68-dbf81f4e34d7.png)

which doesn't reference the line number of the original error, but instead the `console.error` statement from the unhandled rejection error.

Whereas without babel-runtime I get the expected (full) stack trace to the original uncaught error:

![screen shot 2015-10-08 at 1 14 54 pm](https://cloud.githubusercontent.com/assets/6439050/10373984/98438144-6dbe-11e5-9865-bcafc0117027.png)

Does that help at all?

**Comment by loganfsmyth** [comment] 2015-10-08 17:19
@davezuko Don't click the arrow, click the "(...)"

**Comment by sebmck** [comment] 2015-10-08 17:20
Whatever the issue is, it's with [core-js](https://github.com/zloirock/core-js). Possibly related issue: zloirock/core-js#107. Closing this as there's nothing actionable on the behalf of Babel here.

**Comment by davezuko** [comment] 2015-10-08 17:20
@loganfsmyth wow I feel like such a fool, you're absolutely correct. My mistake, thank you.

**Closed by sebmck** 2015-10-08 17:20 UTC

**Comment by loganfsmyth** [comment] 2015-10-08 17:26
I do agree that it isn't ideal, but I'm not sure it's an easily solvable problem. As @sebmck said though, if this discussion is going to continue, it should be over in `core-js`.

**Comment by mistadikay** [comment] 2015-10-19 08:37
@loganfsmyth you just made my day. I feel so stupid for not noticing that one can click those three little dots
