### ISSUE TITLE
[Bug]: @babel/types@7.21.0 is breaking our application build

### ISSUE THREAD

**Issue by abhinavsinghvi** [babel/babel#15454] opened 2023-02-22 10:08 UTC
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

N/A

### Current and expected behavior

Application build has started breaking with @babel/types@7.21.0, works fine on reverting to @babel/types@7.20.7

[object Object]
    at isModuleDeclaration ( node_modules/@babel/types/lib/validators/generated/index.js:3939:11)
    at PluginPass.Program ( node_modules/babel-plugin-lodash/lib/index.js:102:44)
    at newFn ( node_modules/@babel/traverse/lib/visitors.js:148:21)
    at NodePath._call ( node_modules/@babel/traverse/lib/path/context.js:45:20)
    at NodePath.call ( node_modules/@babel/traverse/lib/path/context.js:35:17)
    at NodePath.visit ( node_modules/@babel/traverse/lib/path/context.js:80:31)
    at TraversalContext.visitQueue ( node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitSingle ( node_modules/@babel/traverse/lib/context.js:65:19)
    at TraversalContext.visit ( node_modules/@babel/traverse/lib/context.js:109:19)
    at traverseNode ( node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at traverse ( node_modules/@babel/traverse/lib/index.js:49:34)
    at transformFile ( node_modules/@babel/core/lib/transformation/index.js:81:29)
    at transformFile.next (<anonymous>:null:null)
    at run ( node_modules/@babel/core/lib/transformation/index.js:24:12)
    at run.next (<anonymous>:null:null)
    at transform ( node_modules/@babel/core/lib/transform.js:22:41)
    at transform.next (<anonymous>:null:null)
    at step ( node_modules/gensync/index.js:261:32)
    at  node_modules/gensync/index.js:273:13
    at async.call.result.err.err ( node_modules/gensync/index.js:223:11)

### Environment

- Babel version [7.21.0]

**Comment by nicolo-ribaudo** [comment] 2023-02-22 11:04
In which environment are you running Babel? Is that an error or a log?

**Comment by leschdom** [comment] 2023-02-22 11:53
It might be related to https://github.com/babel/babel/issues/15453, we had a similar issue and it got resolved by re-installing babel@7.21.0 (but that it uses internally https://github.com/babel/babel/releases/tag/v7.21.1, i.e. it updated the `package-lock.json` with this version).

**Comment by JLHwung** [comment] 2023-02-22 16:20
> at PluginPass.Program ( node_modules/babel-plugin-lodash/lib/index.js:102:44)

Duplicate of https://github.com/lodash/babel-plugin-lodash/issues/259.

**Closed by JLHwung** 2023-02-22 16:20 UTC
Labels: i: needs triage
