### ISSUE TITLE
Unsupported syntax  "catch { }" 

### ISSUE THREAD

**Issue by niget** [babel/babel#11020] opened 2020-01-16 16:05 UTC
npm build  , use   _jsdom@16.0.0@jsdom  , build error

```
 } catch {
          ^
SyntaxError: Unexpected token {
    at createScript 

```

https://github.com/jsdom/jsdom/commit/d2ae947c60297a8ec404b4adbd78267bedd439f4?diff=split

**Comment by JLHwung** [comment] 2020-01-16 16:21
What's your nodejs version? `jsdom` requires `node >= 10`.

**Comment by niget** [comment] 2020-01-16 16:29
> What's your nodejs version? `jsdom` requires `node >= 10`.

v10.15.3 and v12.14.1(lts)  both build error

**Comment by JLHwung** [comment] 2020-01-16 16:38
What's the output of the following snippet?
```
node -e "try {} catch {}"
node -v
```

**Comment by niget** [comment] 2020-01-16 16:41
> What's the output of the following snippet?
> 
> ```
> node -e "try {} catch {}"
> node -v
> ```

```
admin@admin node -e "try {} catch {}"
admin@admin node -v   
v12.14.1
```

**Comment by JLHwung** [comment] 2020-01-16 16:56
That means `node` does support optional catch bindings. You can check
1) if this `node` is exactly the same `node` used to run `jsdom`
2) if the syntax error is coming from another places other than the optional catch bindings

But I couldn't go further because lack of necessary information.

As babel-bot said
> Please make sure you have the following information documented in this ticket:

> Your Babel configuration (typically from .babelrc or babel.config.js)
> The current (incorrect) behavior you're seeing
> The behavior you expect
> A short, self-contained example

Following this etiquette would greatly help other people to diagnose and reproduce your issue. 

Out of curiosity, how does this issue relate to Babel?

**Comment by niget** [comment] 2020-01-16 17:00
> babel

thank you very much

**Comment by carlosesh** [comment] 2020-02-11 21:29
I have this exact same issue, any updates?

**Comment by niget** [comment] 2020-02-12 11:25
> I have this exact same issue, any updates?
> 
> I tried the following:
> 
> ```js
> import jsdom from 'jsdom'
> const doc = jsdom.jsdom('<!doctype html><html><body></body></html>')
> global.document = doc
> global.window = doc.defaultView
> ```
> 
> And this is the output error
> 
> ```js
> C:\Users\carlo\Documents\Git\Lnk-Shortner\node_modules\jsdom\lib\jsdom\living\helpers\dates-and-times.js:235
> W20200211-15:32:24.660(-6)? (STDERR)   } catch {
> W20200211-15:32:24.660(-6)? (STDERR)           ^
> W20200211-15:32:24.661(-6)? (STDERR) 
> W20200211-15:32:24.676(-6)? (STDERR) SyntaxError: Unexpected token {
> W20200211-15:32:24.677(-6)? (STDERR)     at createScript (vm.js:80:10)
> W20200211-15:32:24.678(-6)? (STDERR)     at Object.runInThisContext (vm.js:139:10)
> W20200211-15:32:24.678(-6)? (STDERR)     at Module._compile (module.js:617:28)
> W20200211-15:32:24.678(-6)? (STDERR)     at Object.Module._extensions..js (module.js:664:10)
> W20200211-15:32:24.694(-6)? (STDERR)     at Module.load (module.js:566:32)
> W20200211-15:32:24.695(-6)? (STDERR)     at tryModuleLoad (module.js:506:12)
> W20200211-15:32:24.696(-6)? (STDERR)     at Function.Module._load (module.js:498:3)
> W20200211-15:32:24.696(-6)? (STDERR)     at Module.require (module.js:597:17)
> W20200211-15:32:24.697(-6)? (STDERR)     at require (internal/module.js:11:18)
> W20200211-15:32:24.697(-6)? (STDERR)     at Object.<anonymous> (C:\Users\carlo\Documents\Git\Lnk-Shortner\node_modules\jsdom\lib\jsdom\living\helpers\form-controls.js:18:5)
> W20200211-15:32:24.698(-6)? (STDERR)     at Module._compile (module.js:653:30)
> W20200211-15:32:24.698(-6)? (STDERR)     at Object.Module._extensions..js (module.js:664:10)
> W20200211-15:32:24.699(-6)? (STDERR)     at Module.load (module.js:566:32)
> W20200211-15:32:24.699(-6)? (STDERR)     at tryModuleLoad (module.js:506:12)
> W20200211-15:32:24.699(-6)? (STDERR)     at Function.Module._load (module.js:498:3)
> W20200211-15:32:24.700(-6)? (STDERR)     at Module.require (module.js:597:17)
> ```

update node version > 10 , Version may be configured in package.json

**Comment by JLHwung** [comment] 2020-02-12 16:04
`jsdom@16` requires `node >= 10`, if you have the same issue, please update node to version 10. Closing this issue as it is not relevant to babel.

**Closed by JLHwung** 2020-02-12 16:04 UTC
Labels: Needs Info, i: question

**Comment by carlosesh** [comment] 2020-02-13 14:48
@JLHwung this makes no sense, I have the lates version of node, so I don't have idea of why this is not working, but this is not related to a problem with the version of node

**Comment by JLHwung** [comment] 2020-02-13 16:17
@carlosesh Yeah I understand what you are feeling right now. Please report an issue at jsdom (better prepare a reproducing repo) so people can help.

**Comment by nicolo-ribaudo** [comment] 2020-02-13 18:20
@carlosesh If you have a repository that reproduces the problem I would be happy to look at it.
