### ISSUE TITLE
Block scoping fails on IE9

### ISSUE THREAD

**Issue by globin** [babel/babel#2374] opened 2015-09-13 21:42 UTC
The following bug happens with "es6.spec.blockScoping" turned on.

**Possible code generated**
```js
var _temporalUndefined = {};
// ...
UserSettings.prototype.initArray = function (key) {
    var key = _temporalUndefined;
    key = arguments.length <= 0 || arguments[0] === undefined ? undefined : arguments[0];
// ...
}

settings.initArray('foo');
```

In IE 9, causing the code to fail with a TDZ error:
```
arguments[0] === _temporalUndefined;
```

otherwise:
```
arguments[0] === 'foo';
```

**Cause**: IE 9 mutates the `arguments` property when changing `key`, other browsers including newer IE versions and Edge don't.

**Possible Fix**: To fix this the parameter list has to be emptied, then a "new" variable gets created instead of mutating the function parameter.

**Comment by loganfsmyth** [comment] 2015-09-13 21:50
What's the input code you are transpiling in this case? This is similar to what was discussed briefly in https://github.com/babel/babel/issues/1075 so I wanted to confirm.

**Comment by sebmck** [comment] 2015-09-13 21:50
Yeah, this is a duplicate of #1075. This behaviour is not present in strict mode, please use it.

**Comment by loganfsmyth** [comment] 2015-09-13 21:52
@sebmck IE9 Doesn't support strict mode.

**Comment by sebmck** [comment] 2015-09-13 21:54
I hate JScript so much.

**Comment by globin** [comment] 2015-09-13 22:13
Yeah it's a duplicate, except for not having 'strict' support in IE9 :sob:

**Comment by loganfsmyth** [comment] 2015-09-14 02:32
Closing for the same reason as https://github.com/babel/babel/pull/2376.

**Closed by loganfsmyth** 2015-09-14 02:32 UTC
