### ISSUE TITLE
No babel-cli watch mode console output after first compilation

### ISSUE THREAD

**Issue by jaydenseric** [babel/babel#7926] opened 2018-05-14 07:34 UTC
## Bug Report

**Current Behavior**

The babel-cli in `--watch` mode does not output any messages following the first compilation. It seems as though the CLI is not doing anything even though files are compiling.

**Input Code**

```sh
babel src -d lib --watch
```

**Expected behavior/code**

The CLI should display an output summary after every `--watch` mode compilation.

**Babel Configuration (.babelrc, package.json, cli command)**

N/A.

**Environment**
- Babel version(s): v7.0.0-beta.41 - v7.0.0-beta.46
- Node/npm version: Node 10/npm 6
- OS: macOS v10.13.4
- Monorepo: No
- How you are using Babel: `cli`

**Possible Solution**

**Additional context/Screenshots**

This issue began with https://github.com/babel/babel/pull/7439 in [v7.0.0-beta.41](https://github.com/babel/babel/releases/tag/v7.0.0-beta.41). The babel-cli has a new a new `--verbose` flag for seeing exactly what files were compiled, but even with the verbose output of what files are being compiled there are no subsequent summary messages. An output summary should be displayed every compilation, regardless of the `--verbose` flag.

**Comment by wintercounter** [comment] 2018-11-09 09:46
I'm running babel-cli with spawn. I need the success messages to trigger some actions after success. Now there's no way to do that.

**Comment by itsjoekent** [comment] 2018-11-12 16:53
Ooof just noticed this as well, very bizarre.

**Comment by earksiinni** [comment] 2019-01-12 01:21
Any updates on this? Or workarounds?

**Comment by johnsogg** [comment] 2019-03-15 03:10
As a rough workaround I use `--verbose`, e.g.:

`babel ./src --watch --out-dir dest --extensions '.ts,.tsx' --verbose`

It will report modified and output files now, so at least I can see that it picks up changes and does something. I'd like a "Compilation OK" or something happy like that, but I'll take "src/index.ts -> dest/index.js" until then.

**Comment by wintercounter** [comment] 2019-03-15 09:52
The issue with that in my case that multiple files can be changed at the same time and I won't know for sure if compilation is finished or not because I dont know the exact number of files changed.

**Comment by yairEO** [comment] 2019-06-30 08:57
Happens also on my Mac, using

        "@babel/cli": "^7.4.4",
        "@babel/core": "^7.4.5",

**Comment by torressam333** [comment] 2019-08-18 18:10
Was this ever resolved? I am having this exact issue right now.
Thank you.

**Comment by wintercounter** [comment] 2019-08-28 04:55
That will eat all your CPU, especially if you're having many files.

**Comment by josias-r** [comment] 2020-02-07 14:55
Also, the non-watch mode has some colours for paths i.E, when errors appear. Would be nice if the Cli would do it similarly.

**Comment by novendi** [comment] 2020-02-07 16:44
Duplicate of #

**Comment by switz** [comment] 2020-03-05 19:10
Sorry for the additional "+1" message, but this would be really handy to have. It's rough UX without it. If someone wants to point me in the direction of where I might implement this, I'm happy to send a PR.

**Comment by dman777** [comment] 2020-03-16 21:03
> CHOKIDAR_USEPOLLING

probably best to export it as in `export CHOKIDAR_USEPOLLING=true`

**Comment by dman777** [comment] 2020-03-16 21:04
> This same issue came up in an online class I'm taking. The instructor, Andrew Mead, came up with a workaround using Chokidar from npm. Simply add this to the beginning of the babel command: CHOKIDAR_USEPOLLING=true
> This might just be an issue with Linux users.

probably best to export it as in export CHOKIDAR_USEPOLLING=true

**Comment by nicotroia** [comment] 2020-05-14 22:52
Currently running 
```
"@babel/cli": "^7.8.4",
"@babel/core": "^7.9.6",
```

`babel ./src --watch --out-dir ./dist`

and nothing outputs besides a single `Successfully compiled 7 files with Babel.`

**Closed** 2020-05-24 21:03 UTC
