### ISSUE TITLE
babel-register doesn't play well with npm link

### ISSUE THREAD

**Issue by olalonde** [babel/babel#4716] opened 2016-10-12 07:11 UTC
When installing a dependency with `npm link`, babel register will attempt to compile those modules instead of ignoring them like other modules in `node_modules`.

**Comment by DrewML** [comment] 2016-10-15 21:31
I think this has to do with symlinks, and `babel-register` getting the resolved value, which doesn't point to a location in `node_modules`. [This issue](https://github.com/babel/babel/issues/4011) seems related, but it's marked closed without much info (some info may have been lost in the Phabricator migration, but I'm honestly not sure).

**Comment by DrewML** [comment] 2016-10-15 22:55
Likely related to #4693

**Comment by danez** [comment] 2016-10-17 00:24
#4011 was closed as duplicate of #3918

**Comment by OrganicPanda** [comment] 2016-10-25 11:03
I get around this issue with a bit of regex hacking. Not pretty but it works:

```
var modulesToCompile = (modules) => new RegExp(
  `^((?!node_modules).)*$|(${modules.join('|')})(?!\/node_modules)`);

var ifDoesntMatch = (pattern) => (input) => !pattern.test(input);

require('babel-register')({
  presets: ['es2015'],
  ignore: ifDoesntMatch(modulesToCompile(['my-module-foo', 'my-module-bar'])),
});
```

**Comment by hzoo** [comment] 2017-03-24 19:51
Should be fixed by https://github.com/babel/babel/issues/5466 by resolving from cwd combined with using require in the babelc plugins/presets

This should be fixed in Babel 7

can test with: 
"babel-core": "7.0.0-alpha.3"
"babel-cli": "7.0.0-alpha.3"
"babel-register": "7.0.0-alpha.5"

**Closed by hzoo** 2017-03-24 19:51 UTC
Labels: pkg: register

**Comment by sospedra** [comment] 2017-08-24 07:35
@hzoo when will be Babel 7 ready? 🤔
