### ISSUE TITLE
IE11 throws error at _isNativeFunction

### ISSUE THREAD

**Issue by thgh** [babel/babel#9817] opened 2019-04-03 15:10 UTC
## Bug Report

**Current Behavior**
IE11 throws error at `_isNativeFunction`
=> `Function.prototype.toString: 'this' is not a Function object`

**Input Code**
- REPL or Repo link if applicable:

```js
class MyElement extends HTMLElement {}
```

**Expected behavior/code**
The code should return `true` and never throw error.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
preset-env
```

**Environment**
- Babel version(s): 7
- Node/npm version: node 11
- OS: all
- Monorepo: no
- How you are using Babel: rollup-plugin-babel

**Possible Solution**
This is **NOT** the solution:
```diff
export default function _isNativeFunction(fn) {
+  return typeof fn === 'function' && Function.toString.call(fn).indexOf("[native code]") !== -1;
-  return Function.toString.call(fn).indexOf("[native code]") !== -1;
}
```

**Additional context/Screenshots**
![Screenshot 2019-04-03 at 16 52 00](https://user-images.githubusercontent.com/1109982/55489948-2e342180-5633-11e9-9d63-65a89b813bd3.png)

**Comment by thgh** [comment] 2019-04-03 15:34
Sorry, duplicate, but it's not clear how to fix.
https://github.com/babel/babel/issues/4480
https://github.com/babel/babel/issues/4659

**Comment by nicolo-ribaudo** [comment] 2019-04-03 16:08
Actually, this is a bit different from #4480.

**Comment by nicolo-ribaudo** [comment] 2019-04-04 21:32
Oh, this is a duplicate of #8915

**Closed by nicolo-ribaudo** 2019-04-04 21:32 UTC
Labels: i: bug, i: needs triage
