### ISSUE TITLE
Very high memory usage compiling mozilla/PDF.js

### ISSUE THREAD

**Issue by artisb45** [babel/babel#10875] opened 2019-12-17 09:04 UTC
## Bug Report

**Current Behavior**
When running npm start or npm run build, while pdf.js is used in create-react-app project, memory usage seems to skyrocket to unreasonable amounts and fail with "JavaScript heap out of memory" error.
![unreasonable memory usage](https://user-images.githubusercontent.com/13067633/70979646-a146d080-20ba-11ea-8982-247b09b20ad1.png)
![NPM Error](https://user-images.githubusercontent.com/13067633/70979674-ac016580-20ba-11ea-90a2-a64387ac2c2d.png)
I've reported it to PDF.js guys, and they found that ejecting and downgrading babel from 7.7.0+ to 7.6.4 seems to fix the issue so they think it must be regression issue with Babel. The issue can be reproduced in any fresh create-react-app (version 3.3.0) project with pdfjs-dist installed. ([link to original issue](https://github.com/mozilla/pdf.js/issues/11410))

***Steps to reproduce the problem***
1. Create new react app with create-react-app
2. npm install pdfjs-dist
3. Copy [example](https://github.com/mozilla/pdf.js/tree/master/examples/create-react-app) 
4. npm start or npm run build

**Input Code**
[Example repo](https://github.com/astrada/pdf.js-cra-test)

**Expected behavior/code**
npm start or npm run build succesfully without unreasonable memory usage

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
No additional configuration except of what CRA gives us

**Environment**

```
System:
    OS: Windows 10 10.0.18362
  Binaries:
    Node: 12.13.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
```
- Babel version(s): v7.7.4
- Node/npm version: Node 12/npm 6
- OS: Windows 10 Enterprise 1903

**Comment by midgethoen** [comment] 2019-12-18 10:07
I just realise I commented underneath the [wrong issue](https://github.com/mozilla/pdf.js/issues/11410#issuecomment-566954257). 

I have patched the file described in the PR, but this doenst fix the memory error for me. 

FYI, however, by deleting the sourcemaps from the pdfjs-dist package i can get CRA to run again.

**Comment by JLHwung** [comment] 2019-12-18 17:34
Update: The issue is not fixed since I misidentified the memory bottleneck.

For CRA users, you can remove the source maps from the `pdfjs-dist` package (thanks to @midgethoen).

Babel 7.6.4 works because `inputSourceMap` is not functioning, which is later fixed in #10623. However `inputSourceMap` bloats the memory via `JSON.parse/JSON.stringify` on this big [source maps](https://unpkg.com/pdfjs-dist@2.2.228/build/pdf.worker.js.map) (3.13MB) in `pdfjs-dist`, just in order to merge this source map with the source map generated by babel transform.

**Closed** 2019-12-19 00:16 UTC
Labels: Has PR, area: perf, i: bug, i: regression, pkg: core

**Comment by midgethoen** [comment] 2019-12-19 08:41
Thnx for the quick response @JLHwung. Hopefully I can test the patch out later today.

**Comment by midgethoen** [comment] 2019-12-20 07:37
Huzzah :tada: it has been fixed for me. thnx again.
