### ISSUE TITLE
super call in constructor

### ISSUE THREAD

**Issue by quangbuule** [babel/babel#2890] opened 2015-11-07 00:12 UTC
This is weird, right?
```
Module build failed: SyntaxError: /Users/quangbuule/Projects/React/mui-bug/src/index.js: 'super.*' is not allowed before super()
   8 |
   9 |   constructor() {
> 10 |     super(...arguments);
```

**Comment by loganfsmyth** [comment] 2015-11-07 00:42
Duplicate of https://github.com/babel/babel/issues/2775.

**Closed by loganfsmyth** 2015-11-07 00:42 UTC
