### ISSUE TITLE
[plugin-transform-modules-commonjs] Does not always reference imports properly

### ISSUE THREAD

**Issue by dongryphon** [babel/babel#10609] opened 2019-10-28 01:00 UTC
## Bug Report

**Current Behavior**
In some cases `import` does not generate correct reference to imported names.

**Input Code**

```js
import {
    assert,
    Empty,
    chain, clone, copy, defineProp, is, merge, prototype, defProp
} from './Misc';

//...
@prototype({ /* ... */ })
class Config {
    // ...
    static mergers = {
        false (newValue, oldValue, target, mixinMeta) {
            return mixinMeta ? oldValue : newValue;
        },

        blend (newValue, oldValue, target, mixinMeta) {
            let key, ret;

            if (oldValue && newValue && newValue.constructor === Object &&
                oldValue.constructor === Object) {
                ret = clone(oldValue);

                if (mixinMeta) {
                    for (key in newValue) {
                        if (!(key in ret)) {
                            ret[key] = clone(newValue[key]);
                        }
                    }
                }
                else {
                    merge(ret, newValue);   // <<== BAD
                }
            }
            else {
                ret = (mixinMeta && oldValue != null) ? oldValue : newValue;
            }

            return ret;
        },
    };
```

The above reference to `merge` is left unchanged and hence does not refer to the imported `merge` function.

**Expected behavior/code**

All uses of imported names should be updated.

**Babel Configuration**

`./babel.config.js`
```js
// eslint-disable-next-line no-undef
module.exports = function (api) {
    // eslint-disable-next-line no-undef
    const ES6_MODULES = process.env.ES6_MODULES === "true";

    api.cache(false);

    return {
        ignore: ['node_modules'],
        test: ['./packages/**'],
        plugins: [
            [
                '@babel/plugin-proposal-decorators',
                {
                    legacy: false,
                    decoratorsBeforeExport: false
                }
            ],
            [
                '@babel/plugin-proposal-class-properties',
                {
                    loose: false
                }
            ],
            !ES6_MODULES ? ['@babel/plugin-transform-modules-commonjs'] : null
        ].filter(Boolean)
    };
};
```

`./babel.register.js`
```js
require('@babel/register')({
    ignore: ['node_modules'],
    test: ['./packages/**'],
    rootMode: 'upward'
});
```

**Environment**
- Babel version(s): 7.6
- Node/npm version: Node 12.8.1, npm 6.10.2
- OS: Windows 10
- Monorepo: Lerna
- How you are using Babel: `register`

**Possible Solution**

I noticed the issue when I upgraded to 7.4. This works:

    "devDependencies": {
        "@babel/cli": "7.1.x",
        "@babel/core": "7.1.x",
        "@babel/plugin-proposal-class-properties": "7.1.x",
        "@babel/plugin-proposal-decorators": "7.1.x",
        "@babel/plugin-transform-modules-commonjs": "7.1.x",
        "@babel/register": "7.0.x",

**Additional context/Screenshots**
![image](https://user-images.githubusercontent.com/722969/67645125-d02f9a00-f8f4-11e9-97f6-f6bae62efc7e.png)

In 7.1 the actual code looks like:
```js
    (0, _Misc.merge)(ret, newValue);
```
In 7.6, it looks like this:
```js
    merge(ret, newValue);
```

**Comment by dongryphon** [comment] 2019-10-28 01:15
I wish I could give you access to the repository but it is private.

**Comment by JLHwung** [comment] 2019-10-28 17:24
I could not reproduce this error on my local environment. Could you try remove the `node_modules` and reinstall?

**Comment by dongryphon** [comment] 2019-11-02 14:39
I got the same result. Which wasn't surprising because this bug is like a light switch when I toggle the package dependencies between 7.1 and latest and then redo the lerna bootstrap. Works in 7.1 and fails in latest.

How can I help you debug this? If you can point me at how to debug the transform maybe I can spot something. I've never hacked on the babel before so I have no clue how to step through its processing. This bug is also totally consistent as to which import references do not get properly transformed so I don't think it will be hard to iterate on testing it.

**Comment by JLHwung** [comment] 2019-11-21 20:29
@dongryphon Could you try upgrade to 7.2 or other versions? This can help us narrow down the possible changes that trigger this bug.

Above all, it would be great if you can construct a reproducible example on https://babeljs.io/repl

**Comment by dongryphon** [comment] 2019-12-27 16:22
I haven't forgotten about this... apologies. I will try to get around to this over the holidays.

**Comment by nicolo-ribaudo** [comment] 2021-03-07 13:15
I'm closing this issue, since without a reproduction is impossible to know if it's still valid after more than one year!

**Closed by nicolo-ribaudo** 2021-03-07 13:15 UTC
Labels: i: bug
