### ISSUE TITLE
[babel-preset-env] Object Rest/Spread Token Issue

### ISSUE THREAD

**Issue by noahgrant** [babel/babel#7099] opened 2017-12-23 16:27 UTC
Choose one: is this a bug report or feature request?
Bug

Hi, I'd like to follow up on [this issue](https://github.com/babel/babel-preset-env/issues/326) that was closed in the old preset-env repo. That issue concluded with a "workaround" that definitely fixes the babel's parsing issue, but I think that we should still consider that an open bug because it forces me to have to transpile my default parameters and my object/array destructuring, when all my supported browsers support those JS features; they just don't support object rest/spread.

### Input Code

(we can use any sample code from the [previous issue](https://github.com/babel/babel-preset-env/issues/326)).

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [
    ["env", {
      "targets": {
        "browsers": [
          "Chrome >= 55",
          "Firefox >= 53",
          "Edge >= 15",
          "Opera >= 48",
          "Safari >= 10.1"
        ]
      },
      "include": [
        "transform-es2015-destructuring",
        "transform-es2015-parameters"
      ]
    }],
    "react",
    "stage-2"
  ],
  "plugins": [
    "add-module-exports",
    "transform-decorators-legacy",
    "transform-runtime"
  ]
}
```

### Expected Behavior

My expectation is that using the `syntax-object-rest-spread` plugin would allow babel to parse the object rest/spread `...`, which would allow me to remove the two preset-env `include`d packages and not transpile default parameters and destructuring. Adding that plugin does not seem to help.

### Current Behavior

Currently without the two packages in the `include` property for preset-env, the babel parser fails on the first `...` object rest/spread it finds. With the two packages, as noted in the previous issue, the parser succeeds, but in my opinion, that's a great workaround, but the issue should be kept as an open bug.

### Context

This simply affects shipping full ES6 code, since we also make abundant use of object rest/spread. I'd like to be able to use it and not have things like:

```js
arguments.length > 0 && void 0 !== arguments[0] ? arguments[0] : <defaultValue>
```

all over the place.

### Your Environment

babel-preset-env v1.6.1
babel-loader v7.1.2
babel-preset-stage-2 v6.24.1
webpack v2.7
node 8.8
npm v5.6
Mac OS 10.12

**Comment by simonbuchan** [comment] 2018-01-11 00:15
I can't repro this as described?

```
// package.json
{
  "dependencies": {
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.0",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-preset-env": "^1.6.1"
  }
}
// .babelrc
{
  "presets": [
    ["env", {
      "debug": true,
      "targets": {
        "browsers": [
          "Chrome >= 55"
        ]
      }
    }]
  ],
  "plugins": [
    "syntax-object-rest-spread"
  ]
}
// input.js
const { foo, ...rest } = { foo: 1, bar: 2 };
```

Gives:

```
% yarn babel input.js
yarn run v1.3.2
warning package.json: No license field
$ /mnt/c/code/personal/babel-7099/node_modules/.bin/babel input.js
babel-preset-env: `DEBUG` option

Using targets:
{
  "chrome": "55"
}

Modules transform: commonjs

Using plugins:
  syntax-trailing-function-commas {"chrome":"55"}
"use strict";

const { foo, ...rest } = { foo: 1, bar: 2 };

Done in 0.84s.
```

and with `transform-object-rest-spread` instead:

```
function _objectWithoutProperties(obj, keys) { var target = {}; for (var i in obj) { if (keys.indexOf(i) >= 0) continue; if (!Object.prototype.hasOwnProperty.call(obj, i)) continue; target[i] = obj[i]; } return target; }

const _foo$bar = { foo: 1, bar: 2 },
      { foo } = _foo$bar,
      rest = _objectWithoutProperties(_foo$bar, ["foo"]);
```

Which seems legit. Probably something else going on in that config?

**Comment by noahgrant** [comment] 2018-01-11 06:19
Thanks for testing it out! Upon further debugging, I have a reproducible case, and it's kinda funky (but should be legal javascript). What you have above definitely works and seem reasonable. What errors for me is not simply using object rest parameters, but using them in a destructured object that itself is in a destructured array parameter. For example:

```js
const myObj = {foo: {something: 'bar', otherThing: 'baz'}};

Object.entries(myObj).map(([name, {something, ...rest}]) => something);
// ERROR
```

**Comment by simonbuchan** [comment] 2018-01-11 21:21
Yep, I can reproduce that! Given that input, no .babelrc,

```
> yarn -s babel --plugins transform-object-rest-spread input.js
const myObj = { foo: { something: 'bar', otherThing: 'baz' } };

Object.entries(myObj).map(([name, { something, ...rest }]) => something);
```

It doesn't transform, clear `plugin-transform-object-rest-spread` bug.
Tried it with 7 beta, works there:

```
> cat package.json
{
  "private": true,
  "dependencies": {
    "@babel/cli": "7.0.0-beta.37",
    "@babel/core": "7.0.0-beta.37",
    "@babel/plugin-proposal-object-rest-spread": "7.0.0-beta.37"
  }
}
> yarn -s babel --plugins @babel/proposal-object-rest-spread input.js
function _objectWithoutProperties(source, excluded) { if (source == null) return {}; var target = {}; var sourceKeys = Object.keys(source); var key, i; for (i = 0; i < sourceKeys.length; i++) { key = sourceKeys[i]; if (excluded.indexOf(key) >= 0) continue; target[key] = source[key]; } if (Object.getOwnPropertySymbols) { var sourceSymbolKeys = Object.getOwnPropertySymbols(source); for (i = 0; i < sourceSymbolKeys.length; i++) { key = sourceSymbolKeys[i]; if (excluded.indexOf(key) >= 0) continue; if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue; target[key] = source[key]; } } return target; }

const myObj = {
  foo: {
    something: 'bar',
    otherThing: 'baz'
  }
};
Object.entries(myObj).map(([name, _ref]) => {
  let {
    something
  } = _ref,
      rest = _objectWithoutProperties(_ref, ["something"]);

  return something;
});
```

So I guess it was fixed already and they didn't backport?

**Comment by noahgrant** [comment] 2018-01-13 19:12
yeah, looks like it!

**Comment by gaearon** [comment] 2018-01-14 14:16
I have a similar issue but not sure if the cause is the same.
In my case it's reproducible with the latest beta: https://github.com/babel/babel/issues/7215.

**Comment by nicolo-ribaudo** [comment] 2021-01-31 22:10
As mentioned in https://github.com/babel/babel/issues/7099#issuecomment-357065187, this was fixed in Babel 7.

**Closed by nicolo-ribaudo** 2021-01-31 22:10 UTC
Labels: pkg: preset-env
