### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by yoel-wiply** [babel/babel#15201] opened 2022-11-17 09:13 UTC
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

- run 'npm install @babel/plugin-proposal-class-properties --save-dev'
- add "plugins": ["@babel/plugin-proposal-class-properties"] to babel.config.json file
- run npm start

### Configuration file name

babel.config.json

### Configuration

{
  "presets": ["@nrwl/web/babel"],
  "babelrcRoots": ["*"],
  "plugins": ["@babel/plugin-proposal-class-properties"]
}

### Current and expected behavior

Current behaviour: babel seems to be throwing this error  
vendor.js:280159 Uncaught TypeError: _interopRequireDefault is not a function
    at ../../../node_modules/rc-util/lib/hooks/useMergedState.js (vendor.js:280159:23)
    at __webpack_require__ (bootstrap:79:1)
    at ../../../node_modules/antd/lib/typography/Base/index.js (vendor.js:183406:47)
    at __webpack_require__ (bootstrap:79:1)
    at ../../../node_modules/antd/lib/typography/Paragraph.js (vendor.js:184058:36)
    at __webpack_require__ (bootstrap:79:1)
    at ./app/components/ShareLink/index.tsx (main.js:19639:87)
    at __webpack_require__ (bootstrap:79:1)
    at ./app/components/games/GameCard.tsx (main.js:22083:68)
    at __webpack_require__ (bootstrap:79:1)

expected behavior:
to run the application 

### Environment

 "@babel/core": "7.9.6",
Node v16.17.0
Npm 8.15.0
MonoRepo with Nx

**Comment by liuxingbaoyu** [comment] 2022-11-17 09:15
Can you provide a repo to reproduce it?

**Comment by yoel-wiply** [comment] 2022-11-17 09:17
> Can you provide a repo to reproduce it?

Unfortunately I can't since it's enterprise software. Is there any other method I could use to help?

**Comment by JLHwung** [comment] 2022-11-18 15:35
Duplicate of #12854, please upgrade all `@babel/*` deps.

**Closed by JLHwung** 2022-11-18 15:35 UTC
Labels: i: needs triage
