### ISSUE TITLE
Simple reexport failed

### ISSUE THREAD

**Issue by KnisterPeter** [babel/babel#2804] opened 2015-11-04 08:05 UTC
Hi there,

a simple module just reexport a module fails.

```javascript
export * from './some-module';
```

My .babelrc looks like this:
```
{
  "presets": ["es2015", "stage-1"],
  "plugins": ["transform-async-to-generator"]
}
```

This should contain the required export-extensions transform.

The error message looks like this:
```
$ ./node_modules/.bin/babel test.js 
Error: test.js: Invariant Violation: To get a node path the parent needs to exist
    at Object.invariant [as default] (/home/markusw/source/ankara/node_modules/babel-cli/node_modules/babel-core/node_modules/babel-traverse/node_modules/invariant/invariant.js:44:15)
    at Function.get (/home/markusw/source/ankara/node_modules/babel-cli/node_modules/babel-core/node_modules/babel-traverse/lib/path/index.js:82:27)
    at TraversalContext.create (/home/markusw/source/ankara/node_modules/babel-cli/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:73:30)
    at NodePath._containerInsert (/home/markusw/source/ankara/node_modules/babel-cli/node_modules/babel-core/node_modules/babel-traverse/lib/path/modification.js:80:32)
    at NodePath._containerInsertBefore (/home/markusw/source/ankara/node_modules/babel-cli/node_modules/babel-core/node_modules/babel-traverse/lib/path/modification.js:138:15)
    at NodePath.insertBefore (/home/markusw/source/ankara/node_modules/babel-cli/node_modules/babel-core/node_modules/babel-traverse/lib/path/modification.js:57:19)
    at BlockScoping.wrapClosure (/home/markusw/source/ankara/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:485:21)
    at BlockScoping.run (/home/markusw/source/ankara/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:385:12)
    at PluginPass.Loop (/home/markusw/source/ankara/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:89:36)
    at /home/markusw/source/ankara/node_modules/babel-cli/node_modules/babel-core/node_modules/babel-traverse/lib/visitors.js:271:19
```

Any hint on this?

**Comment by loganfsmyth** [comment] 2015-11-04 16:46
Duplicate of https://github.com/babel/babel/issues/2763

**Closed by loganfsmyth** 2015-11-04 16:46 UTC
