### ISSUE TITLE
[Bug]: [plugin-transform-block-scoping] Generating es5 code error for switch statement contains closures 

### ISSUE THREAD

**Issue by TanMichael** [babel/babel#13279] opened 2021-05-07 06:52 UTC
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```js
switch (type) {
    case 'treemap':
        let path = [1,2,3];
        let searchNode = [{name:2}];
        for (let i = 0; i < path.length; i++) {
          let searchResult = searchNode.filter((item) => {
             return item.name === path[i];
          });
        }
       // ....other biz logic
       break;
//........other biz logic
```

### Configuration

inside Angular@9

### Current and expected behavior

Use Angular build production failed:
`ng build --prod`

[error] TypeError: /Users/.../10-es2015.b399c4298665af31d9be.js: Cannot read property 'split' of undefined
    at NodePath.get (/Users/.../node_modules/@babel/core/node_modules/@babel/traverse/lib/path/family.js:167:21)
    at BlockScoping.wrapClosure (/Users/.../node_modules/@babel/plugin-transform-block-scoping/lib/index.js:520:29)
    at BlockScoping.run (/Users/.../node_modules/@babel/plugin-transform-block-scoping/lib/index.js:354:12)
    at PluginPass.BlockStatement|SwitchStatement|Program (/Users/.../node_modules/@babel/plugin-transform-block-scoping/lib/index.js:95:24)
    at newFn (/Users/.../node_modules/@babel/core/node_modules/@babel/traverse/lib/visitors.js:179:21)
    at NodePath._call (/Users/.../node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (/Users/.../node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:42:17)
    at NodePath.visit (/Users/.../node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:90:31)
    at TraversalContext.visitQueue (/Users/.../node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitSingle (/Users/.../node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:84:19)
    at TraversalContext.visit (/Users/.../node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:140:19)
    at Function.traverse.node (/Users/.../node_modules/@babel/core/node_modules/@babel/traverse/lib/index.js:84:17)
    at NodePath.visit (/Users/.../node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:97:18)
    at TraversalContext.visitQueue (/Users/.../node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitMultiple (/Users/.../node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:79:17)
    at TraversalContext.visit (/Users/.../node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:138:19)

But normal `ng build` success

### Environment

System:
    OS: macOS 11.2.3
  Binaries:
    Node: 12.22.1 - ~/.nvm/versions/node/v12.22.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.12 - ~/.nvm/versions/node/v12.22.1/bin/npm

Windows env also failed.

### Possible solution

Use for of statement instead of `filter` function

**Comment by JLHwung** [comment] 2021-05-07 23:39
I can not reproduce this issue on [REPL](https://babel.dev/repl#?browsers=chrome%2088&build=&builtIns=usage&corejs=3.6&spec=false&loose=false&code_lz=M4dwlgLgxgFgBACggTwA4FMCUcDeAoOQuKAQ2HTgHIIAnddAWxNUoC4CjOAbdCOVEhHgBeOAG0AjABoATFIDMAXQDcHToR59yJGrAByAewAmFUWJwA7Eg3SsZAXxVr1AMwM1EmuGDiiADMrecAA8_IIwAHQ8FgDmQoFgANSJ2Pjq6l7aujAASujAAK5cfKJZ-sboES5gxeg0CAiQjNjCAHy4zulEdBAFNBbeEIwRVja-wqICQmJgTl1E9piq8_adhAD063AROxEGQnVwAEZgAF5wXAYxYFBrx3QkANaqm7tvewceJ-eX17f2QA&debug=false&forceAllTransforms=false&shippedProposals=true&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=false&targets=&version=7.14.1&externalPlugins=%40babel%2Fplugin-transform-block-scoping%407.14.1), can you attach the output of

```
BABEL_SHOW_CONFIG_FOR=path/to/your/input ng build --prod
```
? It will print the effective Babel configs.

**Comment by TanMichael** [comment] 2021-05-08 07:15
I have create a file and run `BABEL_SHOW_CONFIG_FOR=path/to/file ng build --prod` many times, but I couldn't get any output in this file.

My project is very big, so I'm not sure is there any other part related to this issue. But I just change the filter function inside `switch case` and the build could pass.
There is also others met this kind of issue https://stackoverflow.com/questions/66700724/angular-build-cannot-read-property-split-of-undefined

**Comment by liuxingbaoyu** [comment] 2022-11-29 14:28
Since a long time has passed and the problem cannot be reproduced, I will close it, if the problem still persists please open a new issue.

**Closed by liuxingbaoyu** 2022-11-29 14:28 UTC
Labels: i: needs triage
