### ISSUE TITLE
TypeError: programPath.hub.addHelper is not a function

### ISSUE THREAD

**Issue by aureooms** [babel/babel#8508] opened 2018-08-22 06:01 UTC
## Bug Report

Just [upgraded to 7.0.0-rc.2](https://github.com/aureooms/js-tape/pull/14). Now [this repo](https://github.com/aureooms/js-tape)'s test [is throwing](https://travis-ci.org/aureooms/js-tape/builds)

```
  ✖ Internal error
  TypeError: programPath.hub.addHelper is not a function
  TypeError: programPath.hub.addHelper is not a function
      at wrapInterop (/home/aureooms/dev/js/js-tape/node_modules/@babel/helper-module-transforms/lib/index.js:165:45)
      at PluginPass.exit (/home/aureooms/dev/js/js-tape/node_modules/@babel/plugin-transform-modules-commonjs/lib/index.js:174:70)
      at newFn (/home/aureooms/dev/js/js-tape/node_modules/ava/node_modules/@babel/traverse/lib/visitors.js:193:21)
      at NodePath._call (/home/aureooms/dev/js/js-tape/node_modules/ava/node_modules/@babel/traverse/lib/path/context.js:53:20)
      at NodePath.call (/home/aureooms/dev/js/js-tape/node_modules/ava/node_modules/@babel/traverse/lib/path/context.js:40:17)
      at NodePath.visit (/home/aureooms/dev/js/js-tape/node_modules/ava/node_modules/@babel/traverse/lib/path/context.js:97:8)
      at TraversalContext.visitQueue (/home/aureooms/dev/js/js-tape/node_modules/ava/node_modules/@babel/traverse/lib/context.js:118:16)
      at TraversalContext.visitSingle (/home/aureooms/dev/js/js-tape/node_modules/ava/node_modules/@babel/traverse/lib/context.js:90:19)
      at TraversalContext.visit (/home/aureooms/dev/js/js-tape/node_modules/ava/node_modules/@babel/traverse/lib/context.js:146:19)
      at Function.traverse.node (/home/aureooms/dev/js/js-tape/node_modules/ava/node_modules/@babel/traverse/lib/index.js:94:17)
      at traverse (/home/aureooms/dev/js/js-tape/node_modules/ava/node_modules/@babel/traverse/lib/index.js:76:12)
      at transformFile (/home/aureooms/dev/js/js-tape/node_modules/ava/node_modules/@babel/core/lib/transformation/index.js:88:29)
      at runSync (/home/aureooms/dev/js/js-tape/node_modules/ava/node_modules/@babel/core/lib/transformation/index.js:45:3)
      at Object.transformSync (/home/aureooms/dev/js/js-tape/node_modules/ava/node_modules/@babel/core/lib/transform.js:43:38)
      at Object.filename [as precompileFull] (/home/aureooms/dev/js/js-tape/node_modules/ava/lib/babel-pipeline.js:201:29)
      at map.reduce (/home/aureooms/dev/js/js-tape/node_modules/ava/api.js:161:28)
  From previous event:
      at emittedRun.then.then.precompilation (/home/aureooms/dev/js/js-tape/node_modules/ava/api.js:153:27)
```

**Input Code**
https://github.com/aureooms/js-tape

**Expected behavior/code**
It was not throwing with the previous release candidate.

**Environment**
Fails with node v10.9.0 and the default node on travis.ci

**Comment by nicolo-ribaudo** [comment] 2018-08-22 06:51
It's probably because Ava is using `rc.1` while you want `rc.2`.

**Comment by aureooms** [comment] 2018-08-22 07:26
Ha! Did not check that. This must be the answer. Sorry to bother with issues on the beta.

**Comment by gajus** [comment] 2018-08-22 09:33
> Ha! Did not check that. This must be the answer. Sorry to bother with issues on the beta.

Did you raise an issue with https://github.com/avajs/ava?

**Comment by aureooms** [comment] 2018-08-22 12:55
No

**Comment by novemberborn** [comment] 2018-08-23 08:18
For now I suggest you keep your plugin / preset dependencies pinned to rc1. I'll try and do another beta release of AVA after Babel 7 hits stable, where I'll change our dependencies to `^7.0.0`.

**Comment by nothingismagick** [comment] 2018-08-24 10:28
We fixed this issue by adding @babel/types as a dev dependency.

**Comment by RnbWd** [comment] 2018-08-25 18:29
I ran into a similar problem running react-native 0.56 - `bundling failed: TypeError: this._hub.addHelper is not a function` - error in the metro bundler

**Comment by loganfsmyth** [comment] 2018-08-25 22:58
@RnbWd Yeah, until we've released a stable 7.0.0 and things are updated to use it (which is likely going to happen on Monday), you'll want to use plugins and presets that correspond with the version of `@babel/core` used by Metro.

**Comment by loganfsmyth** [comment] 2018-08-25 22:59
I'm going to close this since it isn't actionable on our end. Stable is coming very soon.

**Closed by loganfsmyth** 2018-08-25 22:59 UTC

**Comment by Elf2707** [comment] 2018-08-30 20:14
I just change in the file
@babel/helper-module-transform/lib/index.js
line 165 from:
return t().callExpression(programPath.hub.addHelper(helper), [expr]);

to:
return t().callExpression(programPath.hub.file.addHelper(helper), [expr]);
and it works fine now)

**Comment by tscanlin** [comment] 2018-09-05 06:17
I am also running into this with latest versions.

**Comment by pecsiman** [comment] 2018-09-07 16:15
I'm having this issue with latest version. Is there any solution without edit module files?

**Comment by jotapdiez** [comment] 2018-09-07 16:16
I'm having this issue with latest version. Is there any solution without edit module files?

**Comment by nicolo-ribaudo** [comment] 2018-09-07 16:52
You could open a PR to the dependencies that needs to be updated: this would help the whole ecosystem :slightly_smiling_face:

**Comment by sakhisheikh** [comment] 2018-09-10 07:12
@jotapdiez  Are you getting `programPath.hub.addHelper is not a function` error? It is fixed in babel recent upgrade.

**Comment by ThePaulMcBride** [comment] 2018-09-18 20:46
I'm also still running into this error with the latest version of babel. Is this caused by babel?

**Comment by yellowiscool** [comment] 2018-09-20 14:50
Same here using babel `7.0.0-beta.47`  et babel/preset-env `7.1.0`.

**Comment by ThePaulMcBride** [comment] 2018-09-20 14:53
I figured my issues out, it was unrelated to babel. I was using Nextjs version 7 which already included babel. Try upgrading all of you babel dependencies to the latest stable built. No need to use the beta builds anymore.

**Comment by MsaadAl** [comment] 2018-10-09 11:13
I had the same problem and I check the versions of @bebel/core and it was an old version than @babel/preset-env" when I updated it's fixed. 

npm i @babel/core@7.1.0
