### ISSUE TITLE
AMD support for runtime transformation

### ISSUE THREAD

**Issue by patrickarlt** [babel/babel#895] opened 2015-02-25 16:51 UTC
I would love to start using Babel to develop apps but I really need AMD support. Everything works great until I want to use the `--optional runtime` flag on my build.

Here is a sample file.

```js
import Foo from 'foo';

export default "bar";
```

And the compiled output.

```js
"use strict";

define(["exports", "module", "foo", "babel-runtime/helpers"], function (exports, module, _foo, _babelRuntimeHelpers) {
  var _babelHelpers = _babelRuntimeHelpers["default"];

  var Foo = _babelHelpers.interopRequire(_foo);

  module.exports = "bar";
});
```

This all looks good and everything loads fine once I add a package called `babel-runtime` to my config.

```js
      var dojoConfig = {
        packages: [
          {
            name: 'babel-runtime',
            location: '/node_modules/babel-runtime'
          }
        ]
      };
```

But none of the runtime modules are actually AMD modules so they cant be loaded. For example helpers.js looks like this.

```js
"use strict";

var _core = require("babel-runtime/core-js")["default"];

var helpers = exports["default"] = {};
exports.__esModule = true;
```

Would it be possible to convert the runtime files to UMD so they could support AMD loaders and build systems?

**Comment by sebmck** [comment] 2015-02-25 20:58
Duplicate of #638.

**Closed by sebmck** 2015-02-25 20:58 UTC
Labels: duplicate

**Comment by patrickarlt** [comment] 2015-02-25 21:43
Looks like this has been asked for several times by me https://github.com/babel/babel/issues/638 and previously in https://github.com/babel/babel/issues/638. Adding a note about the runtime not supporting AMD might help reduce future duplicates of this.
