### ISSUE TITLE
Babel transforms polyfill in wrong place while using Generator.

### ISSUE THREAD

**Issue by Foolyou** [babel/babel#2178] opened 2015-08-07 03:18 UTC
With this code:
```
require('babel/polyfill');

function* g() {
	yield 1;
}
```

Babel gives:
```
'use strict';

var marked0$0 = [g].map(regeneratorRuntime.mark);
require('babel/polyfill');

function g() {
	return regeneratorRuntime.wrap(function g$(context$1$0) {
		while (1) switch (context$1$0.prev = context$1$0.next) {
			case 0:
				context$1$0.next = 2;
				return 1;

			case 2:
			case 'end':
				return context$1$0.stop();
		}
	}, marked0$0[0], this);
}
```
where <code>var marked0$0 = [g].map(regeneratorRuntime.mark);</code> appears before <code>require('babel/polyfill');</code>. That makes an error: <code>regeneratorRuntime undefined</code>.

**Comment by sebmck** [comment] 2015-08-07 10:31
Duplicate of #832 and #2095.

**Closed by sebmck** 2015-08-07 10:31 UTC
