### ISSUE TITLE
Cannot Select Presets and a File Input Directory via the CLI

### ISSUE THREAD

**Issue by maxbucknell** [babel/babel#6208] opened 2017-09-07 14:45 UTC
## Bug Report

If one is using the CLI to compile scripts that are not descendants of the directory containing `package.json`, and also sets a preset via the `--presets` flag, it will fail to find presets, and the compilation will die.

### Input Code

[maxbucknell/babel-test-preset-compilation](https://github.com/maxbucknell/babel-test-preset-compilation)

### Expected Behavior

It should minify `src/file.js` into `dist/file.js`

### Current Behavior

The script breaks, compilation doesn't happen, with an error resembling the following:

```
Error: Couldn't find preset "minify" relative to directory "../src"
    at /private/tmp/babel-test-preset-compilation/build/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/private/tmp/babel-test-preset-compilation/build/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/private/tmp/babel-test-preset-compilation/build/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/private/tmp/babel-test-preset-compilation/build/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/private/tmp/babel-test-preset-compilation/build/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/private/tmp/babel-test-preset-compilation/build/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/private/tmp/babel-test-preset-compilation/build/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/private/tmp/babel-test-preset-compilation/build/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transform (/private/tmp/babel-test-preset-compilation/build/node_modules/babel-cli/lib/babel/util.js:50:22)
```

### Possible Solution

Editing the compiled code `node_modules/babel-core/lib/helpers/resolve-preset.js` to something like this:

```js
function resolvePreset(presetName) {
  //var dirname = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : process.cwd();
    var dirname = process.cwd();

  return (0, _resolveFromPossibleNames2.default)((0, _getPossiblePresetNames2.default)(presetName), dirname);
}
```

fixes the problem completely. I had a look and tried to trace this back, and found [this file](https://github.com/babel/babel/blob/v6.26.0/packages/babel-core/src/helpers/resolve-preset.js). (I noticed that this seems to have been completely rewritten in version 7, so I'm not sure if this will still be an issue.).

Anyway, it seems to me that resolving presets should have nothing at all to do with where the file is, and always use the current working directory, since it's looking for build scripts, and things loaded via npm, rather than something colocated with the compilation targets.

Is there a reason we cannot just set the directory to search for presets to be the current working directory, and ignore the location of the file completely?

I only had a cursory, look, but it seems that plugins are probably affected by exactly the same problem.

### Context

I'm trying to compile static assets for a website using Babel. For reasons peculiar to me, I'm forced to use the CLI, and cannot easily adopt a `.babelrc`, or similar. Although, looking at this code, I'm not convinced that would solve the problem.

For other reasons peculiar to me, the directory with my source files is not in the same directory tree as the build scripts I've written to do my compilation.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  v6
| node             | v8
| npm              | v5
| Operating System | macOS Sierra

The attached Git repository has been tested on a variety of environments, though. It's not an environmental thing.

**Comment by loganfsmyth** [comment] 2017-09-07 16:44
This is expected behavior in 6.x, but I think your code works in 7.x as expected due to https://github.com/babel/babel/pull/5466. This would be a breaking change in 7.x though.

**Comment by jridgewell** [comment] 2017-09-08 23:32
Closing with https://github.com/babel/babel/issues/6208#issuecomment-327857141.

**Closed by jridgewell** 2017-09-08 23:32 UTC
