### ISSUE TITLE
Cannot find module 'to-fast-properties'

### ISSUE THREAD

**Issue by Rleahy22** [babel/babel#5347] opened 2017-02-20 04:35 UTC
### Babel Configuration (.babelrc, package.json, cli command)

webpack.config.js
```js
const path    = require('path');
const webpack = require('webpack');

module.exports = {
    entry: './src/main.js',
    output: {
        path: path.resolve(__dirname, 'dist'),
        filename: 'bundle.js',
        publicPath: '/assets',
    },
    devServer: {
        contentBase: path.resolve(__dirname, './src'),
    },
    plugins: [
        new webpack.optimize.UglifyJsPlugin({
            sourceMap: true
        }),
    ],
    module: {
        loaders: [
            {test: /\.js$/, loader: 'babel-loader', exclude: /(\.test.js$|node_modules)/},
            {test: /\.css$/, loader: 'style-loader!css-loader'},
            {test: /\.tpl.html/, loader: 'html-loader'},
            {test: /\.(png|jpg|gif|svg|eot|ttf|woff|woff2)$/, loader: 'url-loader?limit=50000'}
        ]
    },
};
```

package.json
```js
"devDependencies": {
    "angular-mocks": "^1.6.2",
    "awesome-typescript-loader": "^3.0.4",
    "babel-core": "^6.23.1",
    "babel-loader": "^6.3.2",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-es2015": "^6.22.0",
    "babel-register": "^6.23.0",
    "babel-runtime": "^6.23.0",
    "chai": "^3.5.0",
    "chalk": "^1.1.3",
    "clean-webpack-plugin": "^0.1.15",
    "connect": "^3.6.0",
    "cross-env": "^3.1.4",
    "css-loader": "^0.26.1",
    "eslint": "^3.15.0",
    "eslint-config-defaults": "^9.0.0",
    "file-loader": "^0.10.0",
    "gulp": "^3.9.1",
    "gulp-webpack": "^1.5.0",
    "html-loader": "^0.4.4",
    "html-webpack-plugin": "^2.28.0",
    "jasmine-core": "^2.5.2",
    "karma": "^1.4.1",
    "karma-chrome-launcher": "^2.0.0",
    "karma-jasmine": "^1.1.0",
    "karma-mocha-reporter": "^2.2.2",
    "karma-webpack": "^2.0.2",
    "minimist": "^1.2.0",
    "mocha": "^3.2.0",
    "ngtemplate-loader": "^1.3.1",
    "open-browser-webpack-plugin": "0.0.4",
    "serve-static": "^1.11.2",
    "sinon": "^1.17.7",
    "style-loader": "^0.13.1",
    "url-loader": "^0.5.7",
    "webpack": "^2.2.1",
    "webpack-dev-server": "^2.4.1"
  }
```

### Expected Behavior
Webpack/Babel to successfully build my application

### Current Behavior
ERROR in ./src/main.js
Module build failed: Error: Cannot find module 'to-fast-properties'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/{}/dev/node_modules/babel-types/lib/index.js:311:25)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

### Context
Any time I try to run webpack with babel-loader it breaks because it cannot find `to-fast-modules` even though it is in the `node_modules` directory.  I have done everything from `npm cache clean && rm -rf node_modules && npm install` to removing all globally installed node packages to completely uninstall and reinstalling node itself and still this problem persists.

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.23.1 
| node             |  7.5 (but also 6.9.5)
| npm              |  4.1.2 (but also 3.10.10)
| Operating System | OSX 10.12.3

**Comment by loganfsmyth** [comment] 2017-02-20 05:16
I'm not sure what to say. When you install, does npm say that the module was installed? You mentioned it was in node_modules, so `ls node_modules/to-fast-properties/` shows a list of files? I'm not sure what to say. If you run Node in the directory, can you run `require('to-fast-properties')`?

**Comment by Rleahy22** [comment] 2017-02-21 04:06
Yes everything says that `to-fast-properties` is there. I can require it from the node repl and I can open up the directory and see that the entire contents of `to-fast-properties/index.js` are simply
```
'use strict';
module.exports = function toFastProperties(obj) {
	function f() {}
	f.prototype = obj;
	new f();
	return;
	eval(obj);
};
```

I even replaced where to-fast-properties gets required in `babel-types/lib/index.js` with that block of code, and it still results in the same error. And yes I have made other changes to index.js to validate that it is saving correctly or not somehow getting cached.  Honestly I don't know what to do anymore, and was hoping this problem was familiar since it is so persistent for me.

**Comment by loganfsmyth** [comment] 2017-02-21 06:23
Would you be able to zip up an example repo, including node_modules, and post it somewhere I could look at? Also feel free to join our Slack if you want a faster back-and-forth.

**Comment by aaronang** [comment] 2017-03-08 22:26
Closing this issue due to no reply. If this is still an issue, please provide an example repository that reproduces your issue, or join our [Slack channel](https://slack.babeljs.io/) for faster back-and-forth.

**Closed by aaronang** 2017-03-08 22:26 UTC
Labels: awaiting reply

**Comment by larryboymi** [comment] 2017-08-18 13:06
Having this same issue, but this has been closed :)

**Comment by loganfsmyth** [comment] 2017-08-18 15:55
This issue is generally an npm install failure of some kind, is is not actionable for us.

**Comment by Rleahy22** [comment] 2017-08-18 15:58
Yes, fwiw it turned out to be an npm install issue for me, and then Atom was having caching issues and not properly replacing the file where the issue came from.  This was not a problem with Babel.

**Comment by larryboymi** [comment] 2017-08-18 16:13
Right, I updated my npm and it was taken care of. Some other dependency must have drawn this out in a weird way. Thanks!
