### ISSUE TITLE
Make JSX compilation play nicely with alternative virtual DOM libraries

### ISSUE THREAD

**Issue by nathansobo** [babel/babel#910] opened 2015-02-27 20:59 UTC
Fueled by the success of React, several alternative virtual DOM implementations have emerged, such as [Riot](https://muut.com/riotjs/), [Mithril](http://lhorie.github.io/mithril/), [Mercury](https://github.com/Raynos/mercury), and [virtual-dom](https://github.com/Matt-Esch/virtual-dom). 

Atom [recently integrated Babel into core](http://blog.atom.io/2015/02/04/built-in-6to5.html), and one of our major goals with core is to be as framework-agnostic as possible. One area where it would be nice to be agnostic is in the usage of JSX... it would be great if any of these frameworks could create JSX adaptors so the same convenient syntax could be used with a variety of underlying implementations.

Currently, JSX expressions are compiled to calls to `React.createElement`. While it's certainly possible to provide an alternative implementation of the `React` variable in a given scope, it would be nice if the language were a bit more neutral. One idea would be to call `JSX.createElement` instead if a `JSX` variable is in scope at the site of a JSX expression, or perhaps allow the create function to be specified via an option. Or maybe there's a better idea I haven't thought of. I'd prefer the `JSX` rule so it's consistent and we don't have to extend Atom's basic pragma system to support this option on every file.

Would your team be open to something like this?

**Comment by Dashed** [comment] 2015-02-27 21:30
This is interesting to have. 

@gcanti experimented with universal DOM that can be targeted to virtual DOM implementations.

https://github.com/gcanti/uvdom
Demo:
https://gcanti.github.io/resources/uvdom/demo/views.html


/cc @gcanti

**Comment by neVERberleRfellerER** [comment] 2015-02-27 21:34
@nathansobo Unless there is some misunderstanding, this is already implemented. Use

    /** @jsx dom */

    function dom(name, props) {
      console.log(name, props);
    }

    var x = (
      <div name="nothing">
        <span>Test!</span>
      </div>
    );

**Comment by eventualbuddha** [comment] 2015-02-27 21:37
I believe this is already possible, you'd just have to do something like this:

```js
/* @jsx JSX.createElement */
```

This ticket is a duplicate of #841 and both are fixed by 35bd5109304dcddb6daa6f60263241418d2a2124.

**Closed by eventualbuddha** 2015-02-27 21:37 UTC

**Comment by nathansobo** [comment] 2015-02-27 21:39
You guys rock, thanks. Should have done my homework.

**Comment by gaearon** [comment] 2015-02-28 20:20
I wonder if there's any sense in making this more generic, see https://github.com/eslint/eslint/issues/1905#issuecomment-76543956

Other tools also rely on this knowledge and it may be worth extracting away into JSX "adapters".
