### ISSUE TITLE
shouldn't there be a AsyncFunction type?

### ISSUE THREAD

**Issue by caub** [babel/babel#4691] opened 2016-10-06 17:54 UTC
demo: https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Cstage-0&code=async%20function%20foo()%7B%0A%20%20%0A%7D%0A%0Aconsole.log(foo.constructor)%3B&experimental=true&loose=false&spec=false&playground=true

it outputs 'Function'

The spec https://tc39.github.io/ecmascript-asyncawait/#async-function-constructor-arguments seems to tell about a AsyncFunction type

**Comment by hzoo** [comment] 2016-10-06 18:33
I think we would be overwriting the toString to make it AsyncFunction then? Not sure we want to do that

**Comment by caub** [comment] 2016-10-06 19:35
I tried on Chrome55, AsyncFunction or GeneratorFunction aren't exposed globally (I thought they would be), but you can catch them after creating one function

```
async function foo(){}
function* gen(){}
console.log(gen.contructor, foo.constructor) 
```

**Comment by MinJieLiu** [comment] 2017-07-14 01:17
```js
assert.equal(Object.getPrototypeOf(async function(){}).constructor.name, 'AsyncFunction');
```

But was not translated correctly by babel😭

**Comment by MinJieLiu** [comment] 2017-07-14 08:12
[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AsyncFunction](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AsyncFunction)

**Comment by damianobarbati** [comment] 2017-10-29 16:28
stumbled on this as well +1 T_T

**Comment by bertho-zero** [comment] 2021-04-07 15:18
This bug is still relevant.

**Comment by nicolo-ribaudo** [comment] 2021-04-07 15:22
Closing as a duplicate of https://github.com/babel/babel/issues/8642.

Thanks @bertho-zero for helping us finding duplicate issues :grimacing:

**Closed by nicolo-ribaudo** 2021-04-07 15:22 UTC
