### ISSUE TITLE
5.6.8 giving Fatal Error

### ISSUE THREAD

**Issue by job13er** [babel/babel#1839] opened 2015-06-25 22:57 UTC
Our CI system just picked up `5.6.8` and now we're getting:

```
Fatal error: Don't hotlink internal Babel files.
```

I'm not aware of us hot linking anything. Pinning our version to `5.6.7` resolved the problem for us.

**Comment by sebmck** [comment] 2015-06-25 22:58
Regression in 5.6.8. Fixed in 2e21795f57c437296dfe2266d40b8da2118d786b and released as of 5.6.9.

**Comment by job13er** [comment] 2015-06-25 22:58
cool, thanks

**Closed by sebmck** 2015-06-25 22:58 UTC

**Comment by michaelficarra** [comment] 2015-06-26 10:46
@sebmck This appears to be a problem for all earlier versions of Babel. Because of Babel's loose semver dependencies, once again a version of Babel that was working fine for me (5.2.17) no longer works for new installs, even though I have it locked down in my package.json. I really don't want to have to npm shrinkwrap each of my projects just because Babel's dependencies can't ever follow semver properly. Please lock down your dependency versions so that we reduce the risk of this happening again.

**Comment by sebmck** [comment] 2015-06-26 10:49
@michaelficarra This has nothing to do with dependencies, it was an inadvertent regression that has since been fixed and a new patch version was released in <1 hour.

**Comment by michaelficarra** [comment] 2015-06-26 10:52
@sebmck If that's true, how did my old install of babel 5.2.17 work fine and a fresh install of *the same version of babel*, 5.2.17, no longer work, failing with this error? There's no other way than a dependency issue.

**Comment by sebmck** [comment] 2015-06-26 10:53
@michaelficarra I don't know. That exact error message was only added in 5.6.8 so if that version was used in your app then it's an npm issue.

**Comment by michaelficarra** [comment] 2015-06-26 10:54
@sebmck Here is proof: https://travis-ci.org/shapesecurity/shift-codegen-js/jobs/68457000

Notice that babel version 5.2.17 is being used, but that error is being thrown from babel-core, a dependency of babel.

**Comment by sebmck** [comment] 2015-06-26 10:56
> babel-core@5.6.11

**Comment by sebmck** [comment] 2015-06-26 10:58
Wasn't clear from your original comment that it was due to the dependencies of the CLI. In the future the CLI wont be released in conjunction with `babel-core` so it doesn't make sense to make it strict.

**Comment by michaelficarra** [comment] 2015-06-26 10:58
Yes, @sebmck, that's exactly the problem. 5.2.17 should not get a newer version of babel-core than the one that was released with it. I have no way to control the version of babel-core that I get other than npm shrinkwrap.

For others' reference, I previously raised this issue at https://github.com/babel/babel/issues/1476 because a babel-core update had broken the "auxiliary comment" feature.

**Comment by michaelficarra** [comment] 2015-06-26 11:06
> In the future the CLI wont be released in conjunction with `babel-core`

Cool, that sounds like a workable solution.

**Comment by sebmck** [comment] 2015-06-26 11:09
Also related #1847, #1837, #1838.
