### ISSUE TITLE
Browser bundle is huge (1.3+ MB minified)

### ISSUE THREAD

**Issue by aldanor** [babel/babel#2242] opened 2015-08-22 20:37 UTC
Is it possible to build a subset of babel to just use the `transform` function for compiling es6/es7/jsx to js in the browser, does it generally have to be this huge? Are there any tricks for using it with webpack?

`JSXTransformer` and `react-tools` are going away and babel seems to remain the only available option for transpiling JSX in the browser, however it's 10 times bigger than those two which is often quite a problem.

**Comment by aldanor** [comment] 2015-08-22 20:38
Just noticed there was another issue recently posted: #2232, however it may be a different question; even if entire babel as a bundle is compiled more efficiently, it wouldn't bring the file size down that much.

**Comment by zertosh** [comment] 2015-08-22 20:53
This is a large contributing factor: https://github.com/benjamn/ast-types/issues/6#issuecomment-126561784

**Comment by sebmck** [comment] 2015-08-24 13:38
There's a bunch of modules that have dependencies that are not used. It's mostly the fault of `regenerator` that pulls in `recast` and `esprima-fb` as well as a bunch of other libraries that aren't even used.

**Comment by zertosh** [comment] 2015-08-24 13:57
`source-map`'s use of `amdefine` is one of the libs that's preventing me optimizing the build. hopefully https://github.com/mozilla/source-map/pull/202 will get merged

**Comment by sebmck** [comment] 2015-09-01 04:37
Moreorless a duplicate of #2232.

**Closed by sebmck** 2015-09-01 04:37 UTC
