### ISSUE TITLE
[Bug]: Parsing error '!' with typescript + react presets

### ISSUE THREAD

**Issue by Connormiha** [babel/babel#13456] opened 2021-06-12 00:06 UTC
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```ts
maxHeight! < 1
```

### Current and expected behavior

Should transform to
```js
maxHeight < 1;
```

Omit typescript's `!`

### Environment

Babel v7.14.5
@babel/preset-typescript: 7.14.5 => 7.14.5
@babel/preset-react: 7.14.5 => 7.14.5
Node 14

### Additional context

https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=LYQwHgEgpglg5gCwC4EIAEAeNBGIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Ctypescript&prettier=false&targets=&version=7.14.5&externalPlugins=

This bug reproduces only with `react` + `typescript` presets.

**Comment by fedeci** [comment] 2021-06-12 05:37
Duplicate of #13445.
It has been fixed in #13449.

**Closed by fedeci** 2021-06-12 05:37 UTC
Labels: i: duplicate
