### ISSUE TITLE
undefined is not a function (evaluating 'object.getownpropertydescriptors(arguments n )')

### ISSUE THREAD

**Issue by MLK57** [babel/babel#10183] opened 2019-07-09 09:37 UTC
This is an issue after launch my apk on a device or emulator. 
![error_apk](https://user-images.githubusercontent.com/50232392/60877337-e4fcfa80-a23d-11e9-9d10-5220c54cbaad.png)

**Comment by nicolo-ribaudo** [comment] 2019-07-09 09:40
Duplicate of https://github.com/babel/babel/issues/10166

**Closed by nicolo-ribaudo** 2019-07-09 09:40 UTC
Labels: i: bug, i: needs triage

**Comment by MLK57** [comment] 2019-07-09 09:58
> Duplicate of #10166

It's not the same issue

**Comment by nicolo-ribaudo** [comment] 2019-07-09 10:08
How is it different? It's exactly the same error, happening in the same engine.

**Comment by MLK57** [comment] 2019-07-09 11:59
In my case the problem is "undefined is not a function(evaluation 'object.getOwnPropertyDescriptors(arguments[n])')". In #10166 the problem is "undefined is not a function(evaluation 'object.getOwnPropertyDescriptors(arguments[i])')". It's not exactly the same and 
my problem is not resolved in the same way as the other

**Comment by nicolo-ribaudo** [comment] 2019-07-09 12:01
You see `n` instead of `i` because you are minifying your code, and it renames the variables. Try disabling minification.

**Comment by MLK57** [comment] 2019-07-09 12:11
I don't know..
I am not an expert of Babel, but I tried to do what you told me but I still have a n and not an i

**Comment by nicolo-ribaudo** [comment] 2019-07-09 12:29
What is the code around the line which is throwing?

**Comment by pwnreza** [comment] 2019-07-09 13:48
@nicolo-ribaudo  How can one disable minification in case of react native. Is it a option for metro bundler which I am using?
I would like to see what happens in detail.

**Comment by nicolo-ribaudo** [comment] 2019-07-09 14:32
Looking at the screenshot in https://github.com/babel/babel/issues/10166#issuecomment-509397077, you need to modify your build process to add `minify=false` to the requested url. I have never used React Native, so I don't know how that URL is generated.
