### ISSUE TITLE
After upgrading babel core, preset-env, babel-loader, preset-react, preset-typescript export from not working

### ISSUE THREAD

**Issue by brneto** [babel/babel#11308] opened 2020-03-21 20:23 UTC
## Bug Report

After updating the following dependencies ESLint started to complains about all imports from export-from files:
- @babel/core: 7.9.0
- @babel/preset-env: 7.9.1
- @babel/preset-react: 7.9.0
- @babel/preset-typescript: 7.9.0

- [x] I would like to work on a fix!

**Current Behavior**
When I run ESLint src, it throws a "not found in" error the message. 

**Input Code**
- https://github.com/brneto/todos-app/blob/master/src/client/redux/sagas/todo-workers.js
- https://github.com/brneto/todos-app/blob/master/src/client/redux/actions/index.js
- https://github.com/brneto/todos-app/blob/master/src/client/redux/actions/commands.js
- https://github.com/brneto/todos-app/blob/master/src/client/redux/actions/events.js
- https://github.com/brneto/todos-app/blob/master/src/client/redux/actions/documents.js

```js
// actions/index.js
export * as effects from './effects';
export * as commands from './commands';
export * as events from './events';
export * as documents from './documents';

// sagas/todo-workers.js
import { commands, events, documents } from '../actions';
//  3:10  error  commands not found in '../actions'             import/named
//   3:20  error  events not found in '../actions'               import/named
//   3:28  error  documents not found in '../actions'            import/named
```

**Expected behavior/code**
I expect ESLint recognize those import without any complaints.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
{
  "plugins": [
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    ["@babel/plugin-proposal-class-properties", { "loose": true }],
    ["@babel/plugin-proposal-private-methods", { "loose": true }],
    "@babel/plugin-proposal-export-namespace-from",
    "@babel/plugin-proposal-export-default-from",
    "@babel/plugin-proposal-function-bind",
    "@babel/plugin-proposal-throw-expressions"
  ],
  "presets": [
    ["@babel/preset-env", {
      "targets": { "node": "current" },
      "useBuiltIns": "usage",
      "corejs": 3,
      "bugfixes": true
    }],
    "@babel/preset-react",
    "@babel/preset-typescript",
    "@emotion/babel-preset-css-prop"
  ]
}
```

**Environment**

```
System:
    OS: Linux 4.15 elementary OS 5.1.2 Hera
    CPU: (3) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 15.14 GB / 21.43 GB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.16.1 - /usr/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.13.4 - /usr/bin/npm
    Watchman: 4.9.0 - /home/linuxbrew/.linuxbrew/bin/watchman
  Managers:
    Apt: 1.6.12 - /usr/bin/apt
    Gradle: 4.4.1 - /usr/bin/gradle
    Maven: 3.6.0 - /usr/bin/mvn
    pip2: 9.0.1 - /usr/bin/pip2
    pip3: 19.0.3 - /home/linuxbrew/.linuxbrew/bin/pip3
  Utilities:
    Make: 4.1 - /usr/bin/make
    GCC: 7.5.0 - /usr/bin/gcc
    Git: 2.17.1 - /usr/bin/git
    FFmpeg: 3.4.6 - /usr/bin/ffmpeg
  Virtualization:
    Docker: 19.03.6 - /usr/bin/docker
  IDEs:
    Nano: 2.9.3 - /bin/nano
    VSCode: 1.43.1 - /usr/bin/code
    Vim: 8.0 - /usr/bin/vim
  Languages:
    Bash: 4.4.20 - /bin/bash
    Go: 1.12.4 - /home/linuxbrew/.linuxbrew/bin/go
    Java: 1.8.0_211 - /usr/bin/javac
    Perl: 5.28.1 - /home/linuxbrew/.linuxbrew/bin/perl
    Python: 2.7.17 - /usr/bin/python
    Python3: 3.7.3 - /home/linuxbrew/.linuxbrew/bin/python3
  Databases:
    SQLite: 3.28.0 - /home/linuxbrew/.linuxbrew/bin/sqlite3
  Browsers:
    Chrome: 80.0.3987.149
    Firefox: 74.0
```

**Possible Solution**
No idea.

**Additional context/Screenshots**
![image](https://user-images.githubusercontent.com/35544241/77235891-a2076b00-6bb1-11ea-9a55-10c1a295b1b9.png)

**Comment by nicolo-ribaudo** [comment] 2020-03-21 20:28
What is your ESLint config?

**Comment by nicolo-ribaudo** [comment] 2020-03-21 21:07
I'm sorry but this is "working as intended".

When using ESLint (without Babel), the ESLint parser produces an AST which matches [the ESTree specification](https://github.com/estree/estree).

When using Babel's parser (without ESLint), there is an option (`"estree"`) to make Babel's output match the ESTree specification. However, Babel implements new features years before that they are specified in ESTree: for every AST node that isn't specified, we keep our own format. However, when a new AST node is specified, we _must_ align it. Not doing so (and thus keep using our own AST format) would be the opposite of what `@babel/parser` users are asking with the `"estree"` option.

When using `babel-eslint`, it enables the `"estree"` option of Babel's parser. This is needed necessary all the ESLint plugins expect an AST conformant to the ESTree specification because it's what ESLint uses. If we used our own AST format, all the ESLint plugins wouldn't work with `babel-eslint`.

Since `export * as foo from "module"` recently became part of the ECMAScript standard (it will be included in ES2020), the ESTree specification defined its AST format (https://github.com/estree/estree/pull/205).
For this reason, `@babel/parser` with the `"estree"` plugin (and thus `babel-estree`) aligned to the new format: it's what the `"estree"` option is explicitly asking for. ESLint will soon support `export * as foo` by default (https://github.com/eslint/eslint/issues/12629), and it will use the same AST format defined in the ESTree specification.

However, `eslint-plugin-import` relies on the Babel-specific format, so it doesn't recognize the `export * as foo` declarations. Note that not only it doesn't work with `babel-eslint`, but it will not work with ESLint alone as soon as https://github.com/eslint/eslint/issues/12629 is fixed.

For this reason, I suggest asking in the `eslint-plugin-import` repository to align to the recently specified format, which is something that all the ESLint plugins should do ASAP to ensure their compatibility with "pure" ESLint.

**Closed by nicolo-ribaudo** 2020-03-21 21:07 UTC
Labels: i: bug, i: needs triage

**Comment by brneto** [comment] 2020-03-21 21:41
@nicolo-ribaudo, would have something I could do in meantime to stop this issue in my project? Some workaround?

**Comment by nicolo-ribaudo** [comment] 2020-03-21 21:43
Yes! I edited the end of my comment a few minutes ago (maybe you missed it)
