### ISSUE TITLE
Is it possible to selectively perform only certain transformations?

### ISSUE THREAD

**Issue by callumlocke** [babel/babel#1213] opened 2015-04-09 14:39 UTC
Say I want to write code for io.js, and I want to use ES6 generators. But I also want to use some other features that io.js [doesn't support yet](http://kangax.github.io/compat-table/es6/#iojs), like rest parameters and destructuring assignments. Enter Babel.

Is there some way I can use Babel to compile my code, but tell it not to compile the generators, just leave them as they are? This way my app would be running real generators natively – the benefits of which are (1) it should be faster, (2) no regenerator/runtime dep, (3) compiled code is more readable, (4) stack traces would be clearer.

It would be awesome if there was a way to tell Babel exactly which platform I'm targeting, and it would do only the minimal transformations needed to compile down my ES.next source code for that particular platform, based on knowledge from the [compatibility table](http://kangax.github.io/compat-table/es6/).

**Comment by sebmck** [comment] 2015-04-09 14:41
You can already blacklist **all** of the Babel transformers. For a full list see the [docs](http://babeljs.io/docs/usage/transformers/) or run `$ babel --help`.

```javascript
require("babel-core").transform("code", { blacklist: ["regenerator", "es6.destructuring"] });
```

```sh
$ babel --blacklist regenerator,es6.destructuring
```

**Comment by sebmck** [comment] 2015-04-09 14:42
To address your specific request:

> It would be awesome if there was a way to tell Babel exactly which platform I'm targeting, and it would do only the minimal transformations needed to compile down my ES.next source code for that particular platform, based on knowledge from the compatibility table.

Duplicate of #631 and #686.

**Closed by sebmck** 2015-04-09 14:41 UTC

**Comment by callumlocke** [comment] 2015-04-09 14:43
I should have searched more carefully, thanks :)
