### ISSUE TITLE
Using spread with Set doesn’t works as expected on babel 7

### ISSUE THREAD

**Issue by huhuanming** [babel/babel#9344] opened 2019-01-15 16:06 UTC
## Bug Report

**Current Behavior**
const a = [1, 2, 3].contact(new Set([1, 2, 3]))
// [1, 2, 3, [Set Object]]

**Input Code**

```js
 const a = [1, 2, 3, ...new Set([1, 2, 3])]
```

**Expected behavior/code**
[1, 2, 3, 1, 2, 3]

**Babel Configuration (.babelrc, package.json, cli command)**

```js

{
    "presets": [[
      "@babel/env", {
            "targets": {
                "browsers": ["> 1%", "ios >= 8", "android >= 4.4", "not ie < 99", "not edge < 99"]
            },
            "useBuiltIns": "usage",
            "loose": true, 
            "modules": false,
          }
      ], 
    "@babel/preset-react"
    ],
    "plugins": [
      ["@babel/plugin-proposal-decorators", { "legacy": true }],
      [
        "@babel/plugin-proposal-class-properties",
        {
          "noMangle": true
        }
      ],
      "@babel/plugin-transform-modules-commonjs"
    ],
    "ignore": [
      "node_modules/**/*.js"
    ],
    "env": {
      "test": {
        "sourceMaps": "inline"
      }
    }
  }
  
```

**Environment**
- @babel/core: "7.2.2"
- Node 8/npm 6
- macOS 10.14.1
- no
- babel-loader: 8.0.4

**Comment by mAAdhaTTah** [comment] 2019-01-15 16:11
Setting `loose: true` assumes all spreads are arrays. If you intend to use Sets, you need `loose: false`.

**Comment by zloirock** [comment] 2019-01-15 16:18
@mAAdhaTTah is right. I proposed [the unification of iterators protocol-related syntax features](https://github.com/babel/babel/issues/4916) a long ago, with adding a way to work with iterables to loose mode too, but we haven't any progress here. I think it can be marked as a duplicate of that issue.

**Closed by zloirock** 2019-01-15 16:18 UTC
Labels: i: bug, i: needs triage
