### ISSUE TITLE
Shadowed const variable in switch block not correctly transpiled

### ISSUE THREAD

**Issue by croes** [babel/babel#12050] opened 2020-09-10 12:53 UTC
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**
In a switch case, when I use a `const` variable with the same name as the variable being switched on, the code isn't correctly transpiled to ES5.

- [babeljs.io/repl](https://babeljs.io/repl#?browsers=ie%2011&build=&builtIns=false&spec=false&loose=false&code_lz=G4QwTgBAZg9jEF5oFcB2BjALgSxqgFAKYCUEA3gFAQQDOA7tpugBZGmXXXog2EQCMALiqcueGpgh8kAVgDcI0QCMwhEAGsF1AL4VtQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Cenv&prettier=false&targets=&version=7.11.6&externalPlugins=)

**Input Code**

```js
function foo(e) {
  switch(e) {
    case 1:
      const e = 5;
      break;
  }
}
```

**Output Code**
```js
"use strict";

function foo(e) {
  switch (_e) {
    case 1:
      var _e = 5;
      break;
  }
}
```
**Expected behavior**
The transpiled code doesn't switch on `_e`, but on `e`.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
{
 "presets": [
   ["@babel/preset-env", {
     "targets": {
       "browsers": [
           "ie >= 11"
       ]
     },
   }],
 ]
}

```

**Environment**

```
System:
    OS: Linux 4.15 Ubuntu 18.04.5 LTS (Bionic Beaver)
  Binaries:
    Node: 12.18.1 - ~/.nvm/versions/node/v12.18.1/bin/node
    npm: 6.14.5 - ~/.nvm/versions/node/v12.18.1/bin/npm
  npmPackages:
    @babel/cli: 7.10.3 => 7.10.3 
    @babel/core: 7.10.3 => 7.10.3 
    @babel/preset-env: 7.10.3 => 7.10.3 
```

**Possible Solution**
Workaround: don't shadow the variable being switched on, in the switch case. This isn't really an option for us, as it's Terser that introduces the name conflict.

**Additional context**
You probably wouldn't shadow the existing variable when manually writing code. As a library developer, we ship code that was minified using Terser. It mangles the names, which results in code as described in this issue (with the name conflicts). A library user that wants to target IE11, needs to transpile the ES6 modules down to ES5, and will run into the issue.

**Comment by JLHwung** [comment] 2020-09-11 15:10
Duplicate of #11509

**Closed by JLHwung** 2020-09-11 15:10 UTC
Labels: i: bug, i: needs triage
