### ISSUE TITLE
NodeLists do not have a default generator as they're expected to. 

### ISSUE THREAD

**Issue by lozandier** [babel/babel#790] opened 2015-02-16 12:49 UTC
For some reason, the specified behavior in ES6 JavaScript (or "JavaScript 2015") of nodeLists having default iterators that allow you to iterate through them with behavior similar to `values()`  or a `for..of` loop isn't defined in Babel yet. 

In fact, unlike other transpilers that at least explicitly explains its lack of finding the default iterator for things, Babel  currently merely states `TypeError: undefined is not a function`:

![screen shot 2015-02-16 at 7 48 31 am](https://cloud.githubusercontent.com/assets/1223224/6212189/46c7a654-b5b0-11e4-988f-c043e4c99b39.png)

**Comment by sebmck** [comment] 2015-02-16 12:51
Why are you using the Traceur runtime?

**Comment by sebmck** [comment] 2015-02-16 12:52
Actually this is a duplicate of #545. The polyfill by @zloirock  included with Babel is required: http://babeljs.io/docs/usage/polyfill/

**Closed by sebmck** 2015-02-16 12:52 UTC

**Comment by lozandier** [comment] 2015-02-16 12:53
@sebmck I tried both Traceur and Babel to see what errors they throw regarding this; JSBin didn't seem to clean itself up when I temporarily switched to it. 

Will look into the polyfill by @zloirock; thanks for the quick response.
