### ISSUE TITLE
[Bug]: Safari class fields implementation is buggy - ReferenceError: Can't find variable

### ISSUE THREAD

**Issue by liamcmitchell-sc** [babel/babel#14289] opened 2022-02-21 09:48 UTC
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

This bug can be triggered by input code like the following, when compiled with webpack and a babel config with preset-env that targets latest Safari/iOS (class fields are not transformed).
```js
import helper from './helper'

class C {
  property = helper(() => {})
}
```

### Current and expected behavior

Extra parens in class fields cause ReferenceErrors in Safari, see webkit bug: https://bugs.webkit.org/show_bug.cgi?id=236843

Generated code will produce an error like "ReferenceError: Can't find variable a".

Until the webkit implementation is fixed, class fields should continue to be transpiled when targeting Safari/iOS.

### Environment

@babel/core 7.17
@babel/preset-env 7.16.11
@babel/compat-data 7.16.8
webpack 5.38.1

### Possible solution

Remove Safari and iOS from `proposal-class-properties` compat data:
https://github.com/babel/babel/blob/v7.17.5/packages/babel-compat-data/data/plugins.json#L19-L29

Does this require updating the upstream compatibility data?
https://github.com/kangax/compat-table

### Workaround

If anyone else experiences this issue, the easy fix is to force transformation of class properties in preset-env config:
```js
presets: [
  [
    '@babel/preset-env',
    {
      include: ['@babel/plugin-proposal-class-properties'],
    },
  ]
],
```

**Comment by ashharrison90** [comment] 2022-02-21 11:57
also hit this - just wanted to say great repro steps and workaround @liamcmitchell-sc 🙌

**Comment by JLHwung** [comment] 2022-02-21 14:29
We will need a bugfix plugin so when `bugfix: true` is enabled (Babel 8 defaults), we only transpile class properties when
1. User code is affected by the specific browser bug
2. User targets to affected browser versions
An example of bugfix plugin can be found in https://github.com/babel/babel/pull/13842, where we workaround another JSC bug.

We will need a new test in `compat-table`, similar to https://github.com/kangax/compat-table/pull/1765 and implement such plugin.

## Experiments on this bug

Another affected example

```js
{
  let a = [];
  new class {
    c = a[(0)]; 
  }
}
```

This one runs without `ReferenceError`, but `c` is correctly initialized as `42`, which should have been `undefined`:
```js
let a = [42];
{
  let a = [];
  new class {
    c = a[(0)]; 
  }
}
```

and this works as expected
```js
let a = [];
new class {
  c = a[(0)];
}
```

So the bug is that, when resolving referenced identifiers within field initializer (`a` under `c = ...`), Safari miscalculate the scope of such bindings to the upper level (if exists), when the referenced identifiers are outside of a parenthesized expression `(i)`. So when the class is defined in top level (popular cases), we don't have to apply the bug fix.

When `bugfix: false` is used, we will apply the transform on Safari.

**Comment by nicolo-ribaudo** [comment] 2022-02-21 17:19
> Do plugins know if compiled code is run at the top level or bundled into functions?

Good point, we should probably be more conservative and apply the fix even if the plugin is at the top level.

**Comment by nicolo-ribaudo** [comment] 2022-02-21 23:22
I propose to fix this bug by wrapping class fields initializers in an IIFE if they contain any reference to a variable defined in the parent scope, and that reference is not nested within another function:
```js
let a = [];
{
  let b = [];
  new class {
    x = a[0];
    y = b[0];
    z = () => b[0];
  };
}
```
becomes
```js
let a = [];
{
  let b = [];
  new class {
    x = a[0];
    y = (() => b[0])();
    z = () => b[0];
  };
}
```

I don't think we should explicitly check for parentheses, because they are hard to predict in a transform. In some cases they are explicit, while in other cases they are implicitly printed by the generator (for example, when printing a multiplication between a number and a sum). Also, even if the class field _currently_ does not contain parentheses they could be easily introduced by new transforms that transform an expression nested within the class field value.

Also, we'll need tests to make sure that the bugfix plugin works with all our other class-related plugins.

**Comment by OliverJAsh** [comment] 2023-01-07 17:38
Quick note to say that the WebKit bug has been fixed and no longer reproduces in Safari 16, but of course the issue still applies in Safari 15.

**Comment by 7rulnik** [comment] 2023-01-16 07:49
Just faced and fought this bug for 3 days. So it's not clear to me where should be fixed. In babel or in terser?

**Comment by sirreal** [comment] 2023-11-07 12:00
One important note for the workaround, if you start to use private methods you'll also need to include `@babel/plugin-transform-private-methods`. There seems to be a dependency where `@babel/plugin-proposal-class-properties` requires `@babel/plugin-transform-private-methods`. (This makes intuitive sense, we probably need to transform private methods if we're going to transform class properties.)

If you start to use private methods in an environment that doesn't transform them but have applied the workaround to include `@babel/plugin-proposal-class-properties`, you'll get an error like:

```
Class private methods are not enabled. Please add `@babel/plugin-transform-private-methods` to your configuration.
```

I would update the workaround to include both:

```jsonc
{
presets: [
  [
    '@babel/preset-env',
    {
      include: [
        // See https://github.com/babel/babel/issues/14289
        '@babel/plugin-proposal-class-properties',
        // Private methods cannot be used with the class properties transform, ensure they're transformed as well
        '@babel/plugin-transform-private-methods'
      ],
    },
  ]
],
}
```

This is easy to see in the REPL. The following [fails without the additional transform](https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=MYGwhgzhAEDC0G8BQ1oGIAOAnAlgNzABcBTABSwHsMBuFdAW2MIAsKATACgEpEBfJXkA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=false&targets=&version=7.23.2&externalPlugins=%40babel%2Fplugin-transform-class-properties%407.22.5&assumptions=%7B%7D), but [is compiled correctly with both transforms](https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=MYGwhgzhAEDC0G8BQ1oGIAOAnAlgNzABcBTABSwHsMBuFdAW2MIAsKATACgEpEBfJXkA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=false&targets=&version=7.23.2&externalPlugins=%40babel%2Fplugin-transform-class-properties%407.22.5%2C%40babel%2Fplugin-transform-private-methods%407.22.5&assumptions=%7B%7D):

```js
class C {
  #privateProp;
  #method() {}
}
```

**Comment by maheshramaiah** [comment] 2024-01-04 10:41
Faced similar issue for below code snippet in Safari < 16 with error - "Reference error: Cant find variable t".

```
var t, a;   

class l {
    static staticVar = null === (t = window.someVariable) || void 0 === t || null === (a = t.someRandomFn("abcd")) || void 0 === a ? void 0 : a.then((e=>e));
}
```

The variable `t` was defined externally and initialized within a static variable of the class. While initializing `t`, the static variable failed to resolve the lexical scope for `t`. This issue occurred intermittently, resulting in a "Reference error: Can't find variable t." It was resolved by adding the @babel/plugin-transform-class-properties plugin.

Seeking insights into the transient nature of this error. Any ideas on what might have caused this intermittent failure?

**Closed** 2024-07-26 09:46 UTC
Labels: i: browser bug
