### ISSUE TITLE
Support for Literate Programming

### ISSUE THREAD

**Issue by agilgur5** [babel/babel#2592] opened 2015-10-26 03:21 UTC
I'm a huge fan of both literate programming and ES6/Babel, but currently it seems like I can't use them together and would have to use literate CoffeeScript if I want to do literate programming. I'd love to help and potentially issue a PR if I had any idea how to create a Babel plugin... :/

**Comment by sebmck** [comment] 2015-10-26 03:44
Duplicate of #2115.

**Closed by sebmck** 2015-10-26 03:44 UTC

**Comment by agilgur5** [comment] 2015-10-26 21:55
@sebmck I saw #2115 but that was taken as a "question" and not actually responded to. Wanted to differentiate this as a feature request as per the README and was hoping to get an actual response...

**Comment by sebmck** [comment] 2015-10-26 22:00
It's not a part of any standard and isn't going to be supported.
