### ISSUE TITLE
Async function transpile breaks dead code elimination

### ISSUE THREAD

**Issue by renarsvilnis** [babel/babel#7665] opened 2018-04-04 21:02 UTC
While cleaning up private feature code for production build noticed that dead code elimination is ignored if the dead code is in an async function.

### Input Code

In the code below I have 2 examples:

1. broken behaviour using `async function`
2. working behavour using normal `function`

 I'm using this flow `<in.js> => babel => uglify => beautify => <out.js>` to process and get the results.

> To test it out use `npm run compress` command.

`package.json`

```js
{
  "scripts": {
    "compress": "rm -f ./out.js && babel ./in.js | uglifyjs --compress --define EXECUTE_CODE_PART=false | js-beautify -f -  -o out.js"
  },
  "dependencies": {
    "babel-cli": "6.26.0",
    "babel-preset-env": "1.6.1",
    "js-beautify": "1.7.5",
    "uglify-js": "3.3.18"
  }
}
```

`.babelrc`

```js
{
  "presets": ["env"]
}
```

`in.js`

```js
// NOTE: EXECUTE_CODE_PART is defined in uglify cli property (simulating webpack.DefinePlugin)

// Broken example
async function  doStuffAsync (input) {
  switch (input) {
    case "jobNr1": {
      console.log ('Hello World!');
      break;
    }
    case "jobNr2": {
      if (EXECUTE_CODE_PART) {
        await Promise.resolve();
        console.log('Should remove this');
      }
      break;
    }
  }
}

// Working example
function doStuff (input) {
  switch (input) {
    case "jobNr1": {
      console.log ('Hello World!');
      break;
    }
    case "jobNr2": {
      if (EXECUTE_CODE_PART) {
        console.log('Should remove this');
      }
      break;
    }
  }
}
```

`out.js`

```js
"use strict";
var doStuffAsync = function() {
    var _ref = _asyncToGenerator(regeneratorRuntime.mark(function _callee(input) {
        return regeneratorRuntime.wrap(function(_context) {
            for (;;) switch (_context.prev = _context.next) {
                case 0:
                    _context.t0 = input, _context.next = "jobNr1" === _context.t0 ? 3 : "jobNr2" === _context.t0 ? 5 : 10;
                    break;
                case 3:
                    return console.log("Hello World!"), _context.abrupt("break", 10);
                case 5:
                    _context.next = 9;
                    break;
                case 8:
                    console.log("Should remove this");
                case 9:
                    return _context.abrupt("break", 10);
                case 10:
                case "end":
                    return _context.stop()
            }
        }, _callee, this)
    }));
    return function(_x) {
        return _ref.apply(this, arguments)
    }
}();

function _asyncToGenerator(fn) {
    return function() {
        var gen = fn.apply(this, arguments);
        return new Promise(function(resolve, reject) {
            return function step(key, arg) {
                try {
                    var info = gen[key](arg),
                        value = info.value
                } catch (error) {
                    return void reject(error)
                }
                if (!info.done) return Promise.resolve(value).then(function(value) {
                    step("next", value)
                }, function(err) {
                    step("throw", err)
                });
                resolve(value)
            }("next")
        })
    }
}

function doStuff(input) {
    switch (input) {
        case "jobNr1":
            console.log("Hello World!");
            break;
        case "jobNr2":
            0
    }
}
```

### Expected Behavior
Expect the `out.js` not have `console.log("Should remove this");` line of code.

### Current Behavior
`out.js` contains `console.log("Should remove this");` line of code.

### Possible Solution
The problem is that the babel transpiles `async function` into fake "generator" of switch statements and the `regeneratorRuntime` keeps `switch` statements that can't be reached from any other `case`. Uglify and `babel-plugin-minify-dead-code-elimination` plugin won't see this as dead code thus the code is left.

I think it would be much easier and more generic improve babel transpile side of async functions rather than add static analytics of dead code for unused switch statements. :/

### Context
Unable to reliably remove development code by putting it in a dead code `if (false) {}` statement.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            | 6.26.0
| node             | v9.10.1
| npm              | 5.6.0
| yarn             | 1.5.1
| Operating System | macOS 10.12.6

**Comment by kzc** [comment] 2018-04-05 14:33
Just run an ES6+ minifier (`uglify-es` or `babel-minify` with a define plugin) against the original high-level code and DCE will be performed correctly in `async` functions. Then transpile the result to ES5.

The code following `await` is actually run after another pass through the event loop. It's not reasonable to expect a state machine code generator to add redundant comparisons to every state branch - particularly if there are side effects involved - just for the purposes of minification.

**Comment by renarsvilnis** [comment] 2018-04-05 14:51
In the real project I was having the problem I'm using newest webpack (`v4.5.0`) with `uglifyjs-webpack-plugin` which uses `uglify-es`. Yeah, but still the problem is that dead code happens after transpiling.

Well, I tried adding `babel-plugin-minify-dead-code-elimination` plugin not the entire `babel-minify`, can I somehow enforce it do the plugin before any other presets, plugins that transpile it to ES5 and eliminate the dead code?

**Comment by kzc** [comment] 2018-04-05 15:12
It's quite simple. Have `webpack` or `rollup` produce an ES6+ bundle *without* `babel` transpiling to ES5. Run an ES6+ minifier such as `uglify-es` on that ES6+ bundle with the desired define/global_defs via plugin or CLI. Then take that output and run it through `babel` to produce ES5. You will probably want to minify again at this stage.

I'll leave the bundling configury up to you. It's out of scope for `babel`.

**Comment by nicolo-ribaudo** [comment] 2018-04-05 16:46
Babel transpiles async functions in a way which _is_ dead-code eliminable:

```js
function doStuffAsync(_x) {
  return _doStuffAsync.apply(this, arguments);
}

function _doStuffAsync() {
  _doStuffAsync = _asyncToGenerator(function* (input) {
    switch (input) {
      case "jobNr1":
        {
          console.log('Hello World!');
          break;
        }

      case "jobNr2":
        {
          if (EXECUTE_CODE_PART) {
            yield Promise.resolve();
            console.log('Should remove this');
          }

          break;
        }
    }
  });
  return _doStuffAsync.apply(this, arguments);
}
``` 

The problem is how generators are transpiled. This feature request should be done either to [regenerator](https://github.com/facebook/regenerator) (which Babel uses to transpile generators) or to the various minifiers.
Personally I think that minifiers should learn how to minify regenerator's output, since it looks easier to me than changing how regenerator works.

**Closed by nicolo-ribaudo** 2018-04-05 16:46 UTC

**Comment by kzc** [comment] 2018-04-05 18:24
> Personally I think that minifiers should learn how to minify regenerator's output

It's unlikely that such a non-generic low level transform would be implemented by any minifier.

High level minification options performing the DCE already exist and are known to work with existing tools.

**Comment by renarsvilnis** [comment] 2018-04-05 20:34
> It's quite simple. Have webpack or rollup produce an ES6+ bundle without babel transpiling to ES5. Run an ES6+ minifier such as uglify-es on that ES6+ bundle with the desired define/global_defs via plugin or CLI. Then take that output and run it through babel to produce ES5. You will probably want to minify again at this stage.

@kzc It's not that simple.
If I use webpack `import()`, react JSX or any new and shiny ES2018+ (object spread, ..) syntax, babel-minify won't understand it without other presets for transpiling. So I need to manage which stuff gets transpiled for the first pass of DCE so webpack understands it - more dependencies to keep track of and more configuration at best.

My initial posted `in.js` example with this webpack config eliminates dead code correctly.

```js
module.exports = {
  mode: 'production',
  entry: './in.js',
  output: {
    path: __dirname,
    filename: 'out.js'
  },
  module: {
    rules: [
      {
        test: /\.js$/i,
        use: [
          {
            loader: 'babel-loader'
          },
          {
            loader: 'babel-loader',
            options: {
              babelrc: false,
              presets: [
                'minify'
              ]
            }
          },

        ]
      }
    ]
  }
}
```

I love that DCE exists, but so far when using it with `webpack (/w treeshake) + babel + uglify` I always need to manually check if the code has been removed. I don't rely on it to work. Most of the time a code refactor fixes the issue.

**Comment by kzc** [comment] 2018-04-05 21:27
Keep in mind that DCE is just nice to have. It's never guaranteed. And yes, if you use `yield` or `await` with a non-standard extension like JSX you have to be prepared for such manual multi-pass hackery if you want to squeeze every last byte from your final bundle. Programmers have to be fully aware of the idiosyncrasies of the transform pipeline to use the tools effectively. Welcome to open source javascript programming.
