### ISSUE TITLE
Parsing bug

### ISSUE THREAD

**Issue by hansl** [babel/babel#1227] opened 2015-04-10 22:41 UTC
The following code fails to parse:

    import {a} from 'B';
    
    export let OBJ = {
        *[Symbol.iterator]() {},
    };

    export class CLASS {
        *[Symbol.iterator]() {}
    }

The error is: "repl: undefined does not match type Pattern".

Removing the `import` fixes it. Removing any of the two `Symbol.iterator` mentions fixes it. Replacing ONE of the two `Symbol.iterator` by a `get [Symbol.iterator]() { return function* () { ... }; }` fixes it. Removing the export on OBJ fixes it. Replacing OBJ by its own class fixes it.

This is the smallest example that I could reduce our code to.

**Comment by sebmck** [comment] 2015-04-10 22:42
Duplicate of #1135.

**Closed by sebmck** 2015-04-10 22:42 UTC
