### ISSUE TITLE
Ability to suppress creation of global variable for external helpers

### ISSUE THREAD

**Issue by scottgonzalez** [babel/babel#903] opened 2015-02-26 20:17 UTC
Following up from #898, it would be nice to have an option in `babel.buildExternalHelpers()` to not create globals.

**Comment by sebmck** [comment] 2015-02-27 13:12
A use-case would be nice, how are you planning on referencing the external helpers unless they're defined globally?

**Comment by scottgonzalez** [comment] 2015-02-27 13:28
I'm transpiling each source file individually, with `es6.module` excluded. I collect the required helpers and then call `.buildExtenalHelpers()` with that list. I then run the transpiled modules through esperanto to do the concatenation (I don't want to go through browserify) and inject the helpers at the top. The end result is a single file containing a UMD module. This works right now, but it leaks the `babelHelpers` global.

So one option would be to have the ability to get the external helpers as a module which I can then import. Another option would be to just not create a closure at all.

**Comment by neVERberleRfellerER** [comment] 2015-03-01 20:47
@scottgonzalez Can you do something like this?

  var fakeGlobal = {};
  (function (global) {
    // inject babel helpers closure here
    (function (global) { // start of helpers closure
      var babelHelpers = global.babelHelpers = {};

      babelHelpers.superfun = function () {
        console.log('Hello, world!');
      };
    })(typeof global === "undefined" ? self : global); // end of helpers closure
  })(fakeGlobal);
  var babelHelpers = fakeGlobal.babelHelpers;

  babelHelpers.superfun();

**Comment by jquense** [comment] 2015-03-02 05:54
I'd like to +1 one this suggestion. I tend to write a lot of small component modules using babel, so usually keep my es6 features limited to things that don't require all of corejs, or I pollyfill things like Promises myself, by using bluebird. The runtime transformer doesn't generally help b/c its an all or nothing require. I generally just let babel inline the helpers, but since we are already give the option to extract them out, wrapping them in a UMD wrapper would offer an added level of flexibility. 

In practice now I use webpack to inject a module for all instances of a variable via the provide plugin. (and do some fancy work to keep it off the global object)

```js
new webpack.ProvidePlugin({
  babelHelpers: "babel/external-helpers"
})
````

This just help automate @neVERberleRfellerER suggestion is a way. wrapping the module in a IIFE that provides the exported value of babel/external-helpers. I realize that this is perhaps a niche case, but it might provide better flexibility with minimal changes, for those that don't mind the global setting its easy enough to opt into via `global.babelHelpers = require("babel/external-helpers");` which is only slightly more verbose that it is now. For browser `<link/>` users nothing changes :)

**Comment by neVERberleRfellerER** [comment] 2015-03-02 11:39
@jquense I think, that you use either:

- Simple build tool - the concatenator. Then my suggestion is eay to do: simply create a file that contains first two lines, the helpers itself, and file with last two lines. Concat together -> profit.
- Advanced build tool - webpack. Then you can export helpers (probably only those you need) and do this:

```
new webpack.ProvidePlugin({
  babelHelpers: "exports?global.babelHelpers!imports?global=>{}!./exported-babel-helpers.js"
})
```

then:
console.log(babelHelpers.slicedToArray); // [Function]
console.log(global.slicedToArray); // undefined

In my opionion, neither solution introduces serious maintenance burden.

**Comment by jquense** [comment] 2015-03-02 16:06
It looks good to me! Tho I think that there may be a bug in the global case. 

shouldn't: `factory(root)` also set the root object to the global object? `factory(root); global.babelHelpers = root;`

**Comment by neVERberleRfellerER** [comment] 2015-03-02 16:31
@jquense When running without module support, *root* is set to *babelHelpers*. I have created babelHelpers with var to prevent pollution of gllbal scope. When you use
```<script src="generated-babel-helpers"></script>```
it should be same as if helpers were assigned directly to *global* (if not, tell me the differences please) and when wrapped, for example in IIFE (after concatenating) it will be properly scoped (which is, if I understant correctly, what scottgonzalez wants).

**Comment by jquense** [comment] 2015-03-02 16:45
I may just be misunderstanding how babel generates the helpers. I was assuming the output was didn't change based on a configuration or other input, perhaps it doesn't. If not, I was just noticing that that the outer `babelHelpers` is passed in to the `factory()`. I annotated my thoughts below, if i'm just missing the point ignore me :)

```js
var babelHelpers = {};

(function (root, factory) {
  if (typeof define === "function" && define.amd) {
    define(["exports"], factory);
  } else if (typeof exports === "object") {
    factory(exports);
  } else {
    // this is the path that executes when you <script src="generated-babel-helpers"></script> right?
    // in which factory just mutates `babelHelpers`, but doesn't assign it to window
    factory(root);

   //to expose it you would also need to:
   window.babelHelpers = root;
  }
})(babelHelpers, function (global) {
  var babelHelpers = global;
  babelHelpers.inherits = ...
})
```

**Comment by neVERberleRfellerER** [comment] 2015-03-02 16:52
@jquense 
This
```window.babelHelpers = root;```
is exactly what I do not want, sicen it is global scope pollution. Also, when you include this in script tag, the babelHelpers are in global scope and usable by every script that you include later. For example, this works (and it will work even with ```<script src="..."></script>```):

```html
<script>
  var babelHelpers = {};

  (function (root, factory) {
      if (typeof define === "function" && define.amd) {
          define(["exports"], factory);
      } else if (typeof exports === "object") {
          factory(exports);
      } else {
          factory(root);
      }
  })(babelHelpers, function (global) {
      var babelHelpers = global;
      babelHelpers.inherits = function () { console.log('XXX'); };
  });
</script>
<script>
  babelHelpers.inherits();
</script>
```

**Comment by jquense** [comment] 2015-03-02 16:54
@neVERberleRfellerER yeah sorry I misunderstood the intent and caught on as soon as I sent the response :P. Generally umd does attach to the global object in a non module environment so it threw me for a loop. I edited my above response to make more sense.

**Comment by neVERberleRfellerER** [comment] 2015-03-02 16:57
@jquense No problem. I was afraid that UMD know something that I do not know (why else would they attach  directly to *window* ? I do not know but I would like to know the answer).

> and caught on as soon as I sent the response

This happens to me ALL THE TIME.

**Comment by jquense** [comment] 2015-03-02 17:09
Generally the reason you'd attach to window is it allows you to avoid closing over a variable in a scope (this is my assumption anyway for why UMD does it). This doesn't really affect babel though b/c the compiler is inserting the references to `babelHelpers`.

```js
window.foo = 5;

(function(){
  var foo = 'bar';

  console.log(window.foo, foo);
})();
```

**Comment by neVERberleRfellerER** [comment] 2015-03-02 17:26
@jquense I have found another reason: AMD does not sandbox modules. When my code is used with AMD, babelHelpers would be accessible globally and we are at the beginning. I am afraid, that due to this limitation, this whole problem can not be solved in clean way (there will be either global variable when concatenating or AMD with leaking variable).
Is AMD still used in its original form? I have probably never seen require.js in production - when AMD modules were used, they were always packed and sandboxed by browserify or webpack (they wrap everything).

**Comment by scottgonzalez** [comment] 2015-03-02 17:30
@neVERberleRfellerER No, that's not a good solution for me, for two reasons. The first reason is that this whole thing is an attempt at being self-contained and as small as possible. Adding additional closures to fake out the globals goes in the opposite direction. Second, because the code runs through esperanto for bundling, I don't have control over variable names that live at the top level. If it's not exported, then the variable names aren't safe; esperanto can rename them to avoid collisions with other modules that are being bundled.

**Comment by jquense** [comment] 2015-03-02 17:45
@scottgonzalez I too am looking for small builds, but what else would you do? By my count the additional closure approach (first suggestion), is gonna be less bytes then a proper wrapping in a UMD definition.

@neVERberleRfellerER that stinks :/ about AMD. Though I don't think its a big deal to create globals in the browser linked case. That is pretty much accepted as the expected behavior for this sort of thing in the js world, and if you are using modules there is no issue, b/c no globals, preserving the AMD case. tbqh if you are concerned about this sort of thing in the first place you wouldn't be including additional small scripts in a link tag to begin with :P

**Comment by scottgonzalez** [comment] 2015-03-02 18:11
I guess I'll have to work around the variable renaming either way, since I can't import this a proper module anyway. I can deal with that by doing the insertion after the bundling instead of before.

Just removing the closure entirely will be enough to solve the problem and will be the smallest size. Right now I can get the same results with:

```js
var helpers = babel.buildExternalHelpers( listOfHelpers );
helpers = helpers.split( "\n" );

// Remove the wrapper
helpers.shift();
helpers.pop();

// Remove the global creation
helpers[ 0 ] = "var babelHelpers = {};";

helpers = helpers.join( "\n" );
```

But obviously I'd rather not rely on knowing the formatting that `babel.buildExternalHelpers()` produces.

**Comment by neVERberleRfellerER** [comment] 2015-03-02 18:11
@jquense Yeah. I have never liked AMD and now I see, that it is even worse.

@scottgonzalez 
If this is reaction to the first proposal:
to the first reason: closure is run exactly once and overhead is around 100 bytes without minification.
to the second reason: You can reexport babelHelpers variable in whatever way you want.

If it was reaction to the UMD approach: UMD is probably only simple way, how to be compatible with different module systems. I have just tested that it works with esperanto without any problems. Overhead is around 260 bytes.

**Comment by scottgonzalez** [comment] 2015-03-02 18:21
I certainly don't want UMD for helpers inside my module if I can avoid that, that's just even more bytes. I didn't really follow the discussion you two were having; I think you may be confused about AMD/UMD.

Getting back to my original request, is there a reason that not having the IIFE can't or shouldn't be supported?

**Comment by jquense** [comment] 2015-03-02 18:36
>Getting back to my original request, is there a reason that not having the IIFE can't or shouldn't be supported?

It seems that we were looking for a generic solution, not having the IIFE would work in your use case but not mine (I don't think). I don't want unwrapped code, but instead want the helpers to be require-able. I am a bit fuzzy on your use case, but wouldn't unwrapped code risk leaking all sorts of internal variables, if anything in helpers was defined locally?

**Comment by neVERberleRfellerER** [comment] 2015-03-02 18:37
@scottgonzalez No, we are solving practical problem - how to make external helpers easy to bundle when runtime transformer is not used. And we want solution that is compatible with CommonJS, AMD and direct inclusion by script tag.

You want something, that is not usable in CommonJS and AMD worlds. Also, try code I have posted in my last comment - it gives exactly what you want and you use something similar already, so this should not be problem for you.

While I understand what you are trying to achieve, I have to mention this:
One class with one letter name and one method, also one letter name - if you did this, you flush 240 bytes without minification. Price of empty method is 130 bytes. One time price of 250 bytes for UMD is nothing.

**Comment by neVERberleRfellerER** [comment] 2015-03-04 07:16
I have something that should work for all and I would like to have your opionion before eventually showing this to sebmck .
It adds options to babel-external-helpers command line script to allow setting of whitelist (somehow useles as command line option) and, more importantly, more output types.

List of output types and possible use cases:

- "global" This is the same as previously only available output. Global helpers without unneccessary overhead.
- "umd" Well, UMD. I have tested it with webpack and its ProvidePlugin --- works well and overhead is only 130 bytes after processing. Suitable for environments where ES6 polyfill is already loaded, but it is required that babelHelpers variable does not leak into global scope (possible use case: multiple bundles are used on single page --- one polyfill, helpers as needed).
- "var" This outputs simple var inicialized to empty object. Babel helpers are then set as properties of that object. Could not be smaller and could be easily postprocessed when something special is required. It work works with webpack too (using imports-loader) and overhead is only 40 bytes after processing.

Output type is selectable from both CLI and API. When no output type is specified, nothing changes and everything is exactly same as it used to be before this change. Code is pretty simple and should not introduce noticeable maintenance burden:

https://github.com/babel/babel/compare/master...neVERberleRfellerER:helper-globals-fix

@jquense What is your opinion on this?

@scottgonzalez 

> Another option would be to just not create a closure at all.

Would the "var" output mode work for you?

**Comment by scottgonzalez** [comment] 2015-03-04 13:58
> Would the "var" output mode work for you?

Yes. That's essentially https://github.com/babel/babel/issues/903#issuecomment-76766390 with a preceding `var babelHelpers = {};`, correct?

**Comment by neVERberleRfellerER** [comment] 2015-03-04 14:19
@scottgonzalez 

> That's essentially https://github.com/babel/babel/issues/903#issuecomment-76766390 with a preceding var babelHelpers = {};, correct?

Exactly.

**Comment by jquense** [comment] 2015-03-04 15:57
LGTM This would certainly solve my use cases,I appreciate also that it adds more options without breaking the current +1.Thanks for working on this!

**Closed** 2015-03-07 15:56 UTC
Labels: enhancement
