### ISSUE TITLE
asyncAwait AST error

### ISSUE THREAD

**Issue by stefanpenner** [babel/babel#1174] opened 2015-04-06 17:26 UTC
```js
 % babel --optional es7.asyncFunctions example.js                                                                                                                               !10039

/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/babel/helpers/parse.js:70
    throw err;
          ^
AssertionError: foo.js: undefined does not match type Pattern
    at Type.Tp.assert (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/ast-types/lib/types.js:53:16)
    at addPattern (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/ast-types/lib/scope.js:220:24)
    at recursiveScanScope (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/ast-types/lib/scope.js:167:9)
    at recursiveScanChild (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/ast-types/lib/scope.js:214:9)
    at NodePath.<anonymous> (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/ast-types/lib/scope.js:150:13)
    at NodePath.each (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/ast-types/lib/path.js:96:22)
    at recursiveScanScope (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/ast-types/lib/scope.js:149:14)
    at recursiveScanChild (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/ast-types/lib/scope.js:214:9)
    at /usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/ast-types/lib/scope.js:176:13
    at /usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/ast-types/lib/types.js:627:18

```

where: 

```js
// example.js
import f from 'f';

    f(async function(assert) { });
//  ^ this function is imported
```

```
± % babel --v
5.0.9

± % npm version
{ 'ember-jobs': '0.0.0',
  npm: '2.7.4',
  http_parser: '2.3',
  modules: '14',
  node: '0.12.2',
  openssl: '1.0.1m',
  uv: '1.4.2-node1',
  v8: '3.28.73',
  zlib: '1.2.8' }
```

**Comment by stefanpenner** [comment] 2015-04-06 17:48
it is only an issue if the function is un-named

**Comment by sebmck** [comment] 2015-04-06 18:21
Duplicate of #1135.

**Closed by sebmck** 2015-04-06 18:21 UTC
Labels: bug

**Comment by stefanpenner** [comment] 2015-04-06 18:22
@sebmck oops, my bad. I swear i searched.
